添加指针的讲解
OI-wiki/OI-wiki pull request #1920
Opened 2020-01-17 09:46 UTC by szdytom

添加指针的讲解， 原来没有内容，现在加上。

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论你是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈你的感受
3. 如果你熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2020-01-17 09:48 UTC, Enter-tainer commented on docs/lang/pointer.md
> +指针就是指向一个变量或者指针的变量，它里面存储的值是一个内存空间的地址。
此处强调“指向变量或指针”是否略显重复？

2020-01-17 09:48 UTC, Enter-tainer commented on docs/lang/pointer.md
> +### 代码实现
```suggestion
### 代码示例
```

2020-01-17 09:48 UTC, Enter-tainer commented on docs/lang/pointer.md
> +Hint:
```suggestion
提示:
```

2020-01-17 09:49 UTC, Enter-tainer commented on docs/lang/pointer.md
> +```cpp
建议给这部分加上注释

2020-01-17 09:50 UTC, Enter-tainer commented on docs/lang/pointer.md
> +还没有听明白吗？看图。
建议将图穿插在上面的讲解中

2020-01-17 09:51 UTC, Enter-tainer commented on docs/lang/pointer.md
> +不知道大家刚才有没有注意到,我们在将`a`和`b`传递到函数change的时候，在前面加了一个`&`符号，这个符号的作用是取出变量的地址，所以它叫取址符。
取地址 和 解引用 等语法应当在文章的开头就介绍，请重新组织一下结构

2020-01-17 09:52 UTC, Enter-tainer commented on docs/lang/pointer.md
> +但是在上面代码中，参数`x`和`y`变量前面的符号也是`&`，可是它的作用就不是取址了。这个符号叫引用符，引用符相当于给变量取了个“别名”，实际上他们两个是同一个变量。所以我们在改变参数`x`和`y`的时候，变量`a`和`b`也会相应的改变。
此处同理，请首先讲清楚各种语法，然后再放代码

2020-01-17 09:52 UTC, Enter-tainer commented on docs/lang/pointer.md
> +在这个代码中，我们首先定义了指针`*p`，用来指向数组a的第一个元素`a[0]`,随后我们每次输出指针`*p`，然后将`p++`（注意这里的`p++`是将`p`原来指向的地址向前挪动一个`sizeof(int)`，而一个`sizeof(int)`的刚好是4个字节，是一个`int`所占用的内存空间。所以在我们当`p++`之后，`p`的指针恰好就跳到了数组的下一位）。最后我们要判断，让`p`不要超过
```suggestion
在这段代码中，我们首先定义了指针`*p`，用来指向数组a的第一个元素`a[0]`,随后我们每次输出指针`*p`，然后将`p++`（注意这里的`p++`是将`p`原来指向的地址向前挪动一个`sizeof(int)`，而一个`sizeof(int)`的刚好是4个字节，是一个`int`所占用的内存空间。所以在我们当`p++`之后，`p`的指针恰好就跳到了数组的下一位）。最后我们要判断，让`p`不要超过数组`a`所占的内存空间。
```

2020-01-17 09:52 UTC, Enter-tainer commented on docs/lang/pointer.md
> +数组其实就是一种特殊的指针，所以说访问数组也可以这么写：
此处错，数组不是指针

2020-01-17 09:53 UTC, Enter-tainer commented on docs/lang/pointer.md
> +数组由于是在内存中连续存储的，所以，而数组这个`a`本身他其实也就是一个指针，当我们访问`a[3]`时。其实就是在访问诶这个指针后移三位的位置。那么它其实也就等价于`a+3`在访问里面的内容啦。
此处同上

2020-01-17 09:53 UTC, Enter-tainer commented on docs/lang/pointer.md
> +3[a] = 5;
仅限未重载的 operator[]

2020-01-17 09:54 UTC, Enter-tainer commented on docs/lang/pointer.md
> +这时候`p`就是一个结构体指针，其类型是`node`
p 的类型应当是 node *

2020-01-17 09:54 UTC, Enter-tainer commented on docs/lang/pointer.md
> +怎么读取/写入结构体指针?
此处问题与上面的 & * 类似。个人认为应当先讲解它的作用，然后再用代码实例分析

2020-01-17 09:55 UTC, Enter-tainer commented on docs/lang/pointer.md
> +也差不多。
```suggestion
与读取类似。
```

2020-01-17 09:56 UTC, Enter-tainer commented on docs/lang/pointer.md
> +指针申明后是没有内存空间的，必须申请后才有。
此句有点混乱...虽然能理解到你的意思...建议换个描述方式

2020-01-17 09:57 UTC, Enter-tainer commented on docs/lang/pointer.md
> +申请的内存需要释放，否则会造成内存泄露，引起RE或MLE。
申请-释放 是好习惯。但是内存泄漏**几乎**不会引起 RE 和 MLE。

唯一能想到的情况是，你把系统的内存用光了，导致 bad_malloc

2020-01-17 09:57 UTC, Enter-tainer commented on docs/lang/pointer.md
> +说明一个指针被释放了两次或释放后又进行了操作。
```suggestion
说明一个指针被释放了两次或释放后又进行了解引用操作。
```

2020-01-19 04:20 UTC, sshwy commented on docs/lang/pointer.md
> +0x22fec4 就是指针 \* p 的地址
```suggestion
0x22fec4 就是指针 `*p` 的地址
```

2020-01-19 04:21 UTC, sshwy commented on docs/lang/pointer.md
> +数组其实就是一种特殊的指针，所以说访问数组也可以这么写：
你想表达的应该是，数组的变量名是指向它第一个元素的指针

2020-01-23 04:02 UTC, orzAtalod commented on docs/lang/pointer.md
> +在这个代码中，我们首先定义了指针 `*p` ，用来指向数组 a 的第一个元素 `a[0]` , 随后我们每次输出指针 `*p` ，然后将 `p++` （注意这里的 `p++` 是将 `p` 原来指向的地址向前挪动一个 `sizeof(int)` ，而一个 `sizeof(int)` 的刚好是 4 个字节，是一个 `int` 所占用的内存空间。所以在我们当 `p++` 之后， `p` 的指针恰好就
```suggestion
在这个代码中，我们首先定义了指针 `*p` ，用来指向数组 a 的第一个元素 `a[0]` , 随后我们每次输出指针 `*p` ，然后将 `p` 自增 （注意这里的 `p++` 是将 `p` 保存的地址前移 `sizeof(int)` ，所以当 `p++` 之后， `p` 的指针就跳到了数组的下一位）。最后我们要判断 `p` 是否超过数组 `a` 所占的内存空间，防止越界。
```
隐去无关细节，顺便我认为这里没有“恰好”。另外，仍旧建议在上面详细讲解地址的概念。

2020-01-23 04:03 UTC, orzAtalod commented on docs/lang/pointer.md
> +综上所述，访问数组也可以这么写：
逻辑跳跃似乎有点大。

2020-01-23 04:03 UTC, orzAtalod commented on docs/lang/pointer.md
> +## 结构体中的指针
```suggestion
## 结构体指针
```

2020-01-23 04:04 UTC, orzAtalod commented on docs/lang/pointer.md
> +这时候 `p` 就是一个结构体指针，其类型是 `node`
```suggestion
这时候 `p` 就是一个结构体指针，其类型是 `node*` 
```

2020-01-23 04:11 UTC, orzAtalod commented on docs/lang/pointer.md
> +用 `->` 运算符
```suggestion
你可能会认为这里可以使用 `*p.a` 这样的语法，但是实际编译却会报错。因为[运算符优先级]()规定，`.` 运算符比 `*` 运算符优先级更高，这一句会被解释成 `*(p.a)`。当然可以使用 `(*p).a` 这样麻烦的语法，但是为了避免这样的麻烦，标准定义了 `->` 运算符
```
在我写这段话的时候 OI-Wiki 403 了所以我并找不到那个内容的内链。

2020-01-23 12:17 UTC, orzAtalod commented on docs/lang/pointer.md
> +申请的内存需要释放，否则会造成内存泄露，引起RE或MLE。
大量的内存泄漏会引起系统保护模块杀死进程导致 RE（至少在洛谷），我不知道这一条现在适不适用，而且这里是 **大量的**

2020-01-23 12:45 UTC, Enter-tainer commented on docs/lang/pointer.md
> +申请的内存需要释放，否则会造成内存泄露，引起RE或MLE。
> 大量的内存泄漏会引起系统保护模块杀死进程导致 RE（至少在洛谷），我不知道这一条现在适不适用，而且这里是 **大量的**

“内存泄漏”实际上就是没有 delete 应该 delete 的内存...在 OS 的眼里大概就是你用的内存多了一点，杀死进程指的就是 OOM Killer 吧...

但是...在 OI 的一般情况下，如果申请的内存的多到耗尽了系统内存...我想锅应该不算是“泄漏”，而是因为你申请的太多，而非“申请了而未释放”

2020-02-03 01:42 UTC, Enter-tainer commented
@szdytom 你好！请问可以跟进一下这个 PR 吗😀

2020-02-05 09:37 UTC, szdytom commented
抱歉，前几天回老家了，网络卡到上洛谷都要好几秒，github登不上qwq

2020-02-05 09:50 UTC, szdytom commented on docs/lang/pointer.md
> +不知道大家刚才有没有注意到,我们在将`a`和`b`传递到函数change的时候，在前面加了一个`&`符号，这个符号的作用是取出变量的地址，所以它叫取址符。
不同意，我觉得这样叫循序渐进。

2020-02-05 09:51 UTC, Enter-tainer commented
![image](https://user-images.githubusercontent.com/25521218/73830709-14a9ca80-4840-11ea-93e7-fd0d85bd24fd.png)

嗯...?似乎没改完的样子

2020-02-05 09:54 UTC, szdytom commented on docs/lang/pointer.md
> +申请的内存需要释放，否则会造成内存泄露，引起RE或MLE。
在OI中，是否释放的确无关紧要。但申请-释放 是好习惯。并且把代码写好是信仰问题。

2020-02-05 09:59 UTC, Enter-tainer commented on docs/lang/pointer.md
> +申请的内存需要释放，否则会造成内存泄露，引起RE或MLE。
> 申请-释放 是好习惯。但是内存泄漏几乎不会引起 RE 和 MLE。

请重新看一下我在此处给的建议，我指出的问题是 “A 并不一定会造成 B，B 不一定会造成 C”，而原文错误的使用了因果关系。

请换用更加精确的描述，如

```
申请的内存需要释放，否则会造成内存泄露，甚至可能引起RE或MLE。
```

2020-02-16 04:00 UTC, orzAtalod commented
要不我直接修改这一页面的内容了

2020-02-16 04:10 UTC, Enter-tainer commented
@orzAtalod 我觉得可，原作者似乎不再跟进了

2020-02-16 08:02 UTC, Enter-tainer commented on docs/lang/pointer.md
> +比如，我们之前学过变量，一个单独的变量就是左值。你可以写 `a=3` ，但是不能写 `3=a` ，因为 `3` 是右值。而有时候左值不是一个单独的变量，是通过一系列运算得到的。例如数组 `a[2]=3` ，这里的左值是 `a[2]` ，进行了一次运算。（严格来说是两次，下面会解释。）
```suggestion
比如，我们之前学过变量，一个单独的变量就是左值。你可以写 `a = 3` ，但是不能写 `3 = a` ，因为 `3` 是右值。而有时候左值不是一个单独的变量，是通过一系列运算得到的。例如数组 `a[2] = 3` ，这里的左值是 `a[2]` ，进行了一次运算。（严格来说是两次，下面会解释。）
```

2020-02-16 08:03 UTC, Enter-tainer commented on docs/lang/pointer.md
> +一般来说，每一个左值都可以视为内存中一个确定的区域，可以对这个区域进行写入和读取。有时候我们需要写入和读取的内存区域并不是一个固定的变量，于是就有了数组。而指针是解决这个问题的另一个利器。
```suggestion
一般来说，每一个左值都可以视为内存中一个确定的区域，可以对这个区域进行写入和读取。
```

感觉这两句好神秘，不太懂

2020-02-16 08:04 UTC, Enter-tainer commented on docs/lang/pointer.md
> +![example](./images/pointer1.png)
图片上为啥有洛谷水印（

2020-02-16 08:04 UTC, Enter-tainer commented on docs/lang/pointer.md
> +![example](./images/pointer1.png)
另外这个图...质量好像不太好的样子，如果有空的话可以重置一下（低优先级）

2020-02-16 08:05 UTC, Enter-tainer commented on docs/lang/pointer.md
> +![example](./images/pointer1.png)
图上为什么是 *p 和 **q 啊，感觉应该用 p 和 q 来表示指针本身

2020-02-16 08:06 UTC, Enter-tainer commented on docs/lang/pointer.md
> +而定义一个 `int` 指针 `p` 的方法就是 `int *p;` ，可以念作“ `*p` 的类型是 `int` ”。这是 C++ 的一个“解方程风格”的类型声明机制。例如，类型声明 `int cmp(int,int)` 就可以念作“ `cmp(int,int)` 的类型是 `int` ”，这是一个函数的类型声明，以后会学到。
> 而定义一个 `int` 指针 `p` 的方法就是 `int *p;` ，可以念作“ `*p` 的类型是 `int` ”。这是 C++ 的一个“解方程风格”的类型声明机制。例如，类型声明 `int cmp(int,int)` 就可以念作“ `cmp(int,int)` 的类型是 `int` ”，这是一个函数的类型声明，以后会学到。

需要讨论

我个人好像没见过这样读的/fad

2020-02-16 08:11 UTC, Enter-tainer commented on docs/lang/pointer.md
> +指针加整数 `p+x` 的值即为一个新指针，该新指针的值为 `p` 右移 `x` 位的值。注意“右移”不是“右位移”，“右位移”是位运算的操作。
建议直接写成向右移动 x 个 sizeof(*p) 。

移动 x 位这个表述感觉挺模糊的。

2020-02-16 08:12 UTC, Enter-tainer commented on docs/lang/pointer.md
> +因为内存是连续的，因此连续内存区域的编号也是连续的。而数组的内存也是连续的，因此若数组 `a[0]` 的编号是 `8` ，那么 `a[1]` 的编号就是 `12` ， `a[3]` 的编号就是 `20` 。 `&(a[3])=&(a[0])+3` 。
```suggestion
数组占据一块连续的内存空间，因此若数组 `a[0]` 的编号是 `8` ，那么 `a[1]` 的编号就是 `12` ， `a[3]` 的编号就是 `20` 。 `&(a[3])=&(a[0])+3` 。
```

2020-02-16 08:12 UTC, Enter-tainer commented on docs/lang/pointer.md
> +因为内存是连续的，因此连续内存区域的编号也是连续的。而数组的内存也是连续的，因此若数组 `a[0]` 的编号是 `8` ，那么 `a[1]` 的编号就是 `12` ， `a[3]` 的编号就是 `20` 。 `&(a[3])=&(a[0])+3` 。
此处应指出，所谓“编号”的单位是字节

2020-02-16 08:13 UTC, Enter-tainer commented on docs/lang/pointer.md
> +指针减整数 `p-x` 的值和指针加整数类似，也是一个新指针，指向 `p` 左移 `x` 位的值。
同上右移

2020-02-16 08:13 UTC, Enter-tainer commented on docs/lang/pointer.md
> +例如，如果 `a` 是一个数组，那么 `&(a[0])=&(a[3])-3` 。
```suggestion
例如，如果 `a` 是一个数组，那么 `&(a[0]) == &(a[3])-3` 。
```

2020-02-16 08:15 UTC, Enter-tainer commented on docs/lang/pointer.md
> +指针减指针是一个很强大的操作。指针减指针得到的是一个偏移量，该偏移量是一个正数，代表指针间相距元素的个数。
感觉不太一定是正数的样子？

2020-02-16 08:15 UTC, Enter-tainer commented on docs/lang/pointer.md
> +指针减指针是一个很强大的操作。指针减指针得到的是一个偏移量，该偏移量是一个正数，代表指针间相距元素的个数。
![图片](https://user-images.githubusercontent.com/25521218/74601302-9539b800-50d7-11ea-83aa-160796c833a5.png)

``` cpp
Margatroid@MiPro MINGW64 ~/Desktop
$ cpprepl
? >>= » int a[10]
√ >>= · int a[10]
? >>= » &(a[0])-&(a[3])
√ >>= · &(a[0])-&(a[3])
&(a[0])-&(a[3]) = -3 :: long long int
```

2020-02-16 08:17 UTC, Enter-tainer commented on docs/lang/pointer.md
> +可以强制转换指针的类型，即可以通过 `(long long*)p` 得到一个新指针，该指针指向的地址和 `p` 相同，类型由原来的 `int*` 强制转换成 `long long*` ，之后对其的解引用操作会获得一个 `long long` 类型的左值，各种运算也是以 `long long` 为基础类型。
这个 “即” 感觉有点谜之突兀。另外，p 是什么呢

2020-02-16 08:18 UTC, Enter-tainer commented on docs/lang/pointer.md
> +虽然 `void` 类型不是一个合法的左值，但是存在 `void*` 类型的指针。在 ANSI C 标准中这种类型的指针无法解引用，也无法加减，在 GNU 标准中，这种类型的指针加减的单位是一个字节。在 C 中这种类型的指针可以由其他类型隐式转换而来，也可以隐式转换成其他类型的指针，在 C++ 中必须强制转换成其他类型的指针（即必须使用 `(int*)` 等进行强制类型转换才可转为其他类型）。
这段好绕，一会 cpp 一会 c（

2020-02-16 08:18 UTC, Enter-tainer commented on docs/lang/pointer.md
> +所有类型的指针的值都是地址，在 32 位机上地址的单位是 32 位，64 位机上则为 64 位。可以使用 `%p` 输出。
请指出，%p 是 printf 的占位符

2020-02-16 08:22 UTC, Enter-tainer commented on docs/lang/pointer.md
> +数组名可以视作一个指针，即如果 `a` 是一个 `int` 类型的数组，那么 `a` 等价于 `&(a[0])` ，注意数组名是右值。因此， `a[3]` 就等价于 `*(a+3)` ，实际上它就是这么定义的，因此可以认为 `a[3]` 经历两次运算，一次指针和整数的加法，一次解引用。因为 `a+3=3+a` ，所以 `3[a]` 也可以表示同一个左值。因此， `a[3]=5` 还可以这么写：
```suggestion
数组名可以隐式转换为指向数组首元素的指针，即如果 `a` 是一个 `int` 类型的数组，那么 `a` 在大多数地方等价于 `&(a[0])` ，注意数组名是右值（？？？）。因此（原因是什么呢？）， `a[3]` 就等价于 `*(a+3)` ，实际上它（它是什么？，请指出）就是这么定义的，因此可以认为 `a[3]` 经历两次运算，一次指针和整数的加法，一次解引用。因为 `a + 3 == 3 + a` ，所以 `3[a]` 也可以表示同一个左值。因此， `a[3] = 5` 还可以这么写：
```
数组名似乎不是右值吧。

关于为什么 a !== &(a[0])，可以试着输出 sizeof(a) 和 sizeof(&a[0])

2020-02-16 08:28 UTC, Enter-tainer commented on docs/lang/pointer.md
> +当然，这种写法有点麻烦，因此 C 标准规定了 `->` 运算符。直接使用 `->` 运算符就可以获取相应左值。
```suggestion
当然，这种写法有点麻烦。我们可以使用 `->` 运算符。`a->b` 等价于 `(*a).b`
```

2020-02-16 08:30 UTC, Enter-tainer commented on docs/lang/pointer.md
> +指针声明后没有经过初始化，其指向的内存空间是无意义的。如果需要为其分配一定大小的内存空间，必须经过申请。
“必须经过申请” 感觉过于绝对了，完全可以 int *p = &a; 之类的，其中 a 是个局部变量

2020-02-16 08:30 UTC, Enter-tainer commented on docs/lang/pointer.md
> +可以使用 `new` 关键字，在 C 中可以使用 `malloc` 。
emm既然是 cpp 的入门教程就不要提 malloc 了吧

2020-02-16 08:31 UTC, Enter-tainer commented on docs/lang/pointer.md
> +区别在于，malloc 是 `stdlib.h` （ `cstdlib` ）中的函数，功能是接受一个 `size_t` 类型表示分配的字节数，返回一个 `void*` 表示分配的字节，而 `new` 是一个运算符。
```suggestion
区别在于，malloc 是 `stdlib.h` （ `cstdlib` ）中的函数，功能是接受一个 `size_t` 类型表示分配的字节数，返回一个 类型为 `void*` 的指针，指向分配的字节，而 `new` 是一个运算符。
```

2020-02-16 08:32 UTC, Enter-tainer commented on docs/lang/pointer.md
> +这里需要注意， `int *w[100]` 所定义的是一个一维的指针数组，而 `int (*w)[100]` 定义的是一个指向一维数组的指针，这两个概念是不一样的。由于二维数组是“一维数组的一维数组”，因此二维数组名是“指向一维数组的指针”，所以必须使用 `int(*)[100]` 类型。
希望此处可以更详细一些，这是初学者容易分不清的地方

2020-02-16 08:33 UTC, Enter-tainer commented on docs/lang/pointer.md
> +本质上是利用了构造函数，可以在[类]里面进一步了解。
int[] 是基本类型，没有构造函数

2020-02-16 08:37 UTC, Enter-tainer commented on docs/lang/pointer.md
> +函数指针的定义很简单，根据“解方程规则”，一个接收两个 `int` 类型参数、返回 `int` 类型的函数指针 `calc` 可以定义为 `int (*calc)(int,int)` ，意思是“ `(*calc)(int,int)` 的类型是 `int` ”。如果使用 `int *calc(int,int)` 的话，就会变成一个接收两个 `int` 返回 `int*` 的函数了。
此处同最前面的 comment。我好像没有见过这样读的

2020-02-16 08:38 UTC, Enter-tainer commented on docs/lang/pointer.md
> +而调用就很有趣了。第一种调用方法是 `(*calc)(1,2)` ，从声明中体现出来。而第二种调用方式是 `calc(1,2)` ，从赋值中可以看出。实际上，这两种调用方式都是合法的。
建议不要“看出”。请给出这样都合法的原因。

2020-02-16 08:40 UTC, Enter-tainer commented on docs/lang/pointer.md
> +typedef (*func)(int, int) int;
这里的 typedef 写错了吧，应该是 typedef int (*func)(int, int);

2020-02-16 09:19 UTC, orzAtalod commented on docs/lang/pointer.md
> +而定义一个 `int` 指针 `p` 的方法就是 `int *p;` ，可以念作“ `*p` 的类型是 `int` ”。这是 C++ 的一个“解方程风格”的类型声明机制。例如，类型声明 `int cmp(int,int)` 就可以念作“ `cmp(int,int)` 的类型是 `int` ”，这是一个函数的类型声明，以后会学到。
我觉得这样会更容易理解一些/fad

或者将“念作”改成“理解为”？这样理解以后讲函数指针也会轻松（

2020-02-16 10:06 UTC, Enter-tainer commented on docs/lang/pointer.md
> +而定义一个 `int` 指针 `p` 的方法就是 `int *p;` ，可以念作“ `*p` 的类型是 `int` ”。这是 C++ 的一个“解方程风格”的类型声明机制。例如，类型声明 `int cmp(int,int)` 就可以念作“ `cmp(int,int)` 的类型是 `int` ”，这是一个函数的类型声明，以后会学到。
emm我感觉把一个函数的类型拆成了两部分读很怪，我的读法是 cmp 的参数是 (int, int)，返回值类型是 int

2020-02-16 10:14 UTC, Enter-tainer commented on docs/lang/pointer.md
> +而调用就很有趣了。由于定义是 `int (*calc)(int,int)`，因此可以使用 `(*calc)(1,2)` 的形式来调用函数。而从另外一个方面，因为我们赋值的时候有 `calc=add`，那么既然可以直接用 `add(1,2)`，也应该能直接用 `calc(1,2)`。
下面的代码是可以通过编译的：

``` cpp
#include <iostream>
using namespace std;

int f(int t) {
  return t * t;
}

int main () {
  int (*fp)(int) = f;
  cout << fp(2) << ' ' << (*fp)(2) << (**fp)(2) << (******fp)(2);
}
```

2020-02-16 10:15 UTC, Enter-tainer commented on docs/lang/pointer.md
> +（记得提醒作者他咕了）
🕊🕊🕊🕊🕊🕊🕊🕊🕊🕊🕊（大雾

2020-02-16 12:10 UTC, Xeonacid commented on docs/lang/pointer.md
> +这里就可以用到指针了。利用取址和解引用操作，我们可以在函数内创建和 `main` 中的 `a`  `b` 相同的左值。
并不是“创建”？

2020-02-16 12:12 UTC, Xeonacid commented on docs/lang/pointer.md
> +一般而言，函数的参数分为“形参”和“实参”。形参只是将参数的值复制一份，是一个不同的左值，修改形参无法更改函数外对应参数的值，而实参和原参数是相同的左值。为什么要这么麻烦？因为函数的参数有时候不一定是左值，这时候只能用形参。
这种说法是错误的，“实参”就是“原参数”，即函数调用处的参数

2020-02-16 12:14 UTC, Xeonacid commented on docs/lang/pointer.md
> +实际类型是 `ptrdif_t` ，包含在 `stddif.h` （C++ 中则为 `cstddif` ）中。
```suggestion
实际类型是 `ptrdiff_t` ，包含在 `stddif.h` （C++ 中则为 `cstddif` ）中。
```

2020-02-16 12:17 UTC, Xeonacid commented on docs/lang/pointer.md
> +所有类型的指针的值都是地址，在 32 位机上地址是 32 位，64 位机上则为 64 位，以字节为单位。在 `scanf` 中的占位符是 `%p` 。
这句话放这不合适吧，放指针定义那吧

2020-02-16 12:18 UTC, Xeonacid commented on docs/lang/pointer.md
> +数组名可以视作一个指针，即如果 `a` 是一个 `int` 类型的数组，那么 `a` 等价于 `&(a[0])` ，注意数组名是右值。因此， `a[3]` 就等价于 `*(a+3)` ，实际上它就是这么定义的，因此可以认为 `a[3]` 经历两次运算，一次指针和整数的加法，一次解引用。因为 `a+3=3+a` ，所以 `3[a]` 也可以表示同一个左值。因此， `a[3]=5` 还可以这么写：
suggestion不是这么用的（雾），容易被人不小心merge了

2020-02-16 12:22 UTC, Xeonacid commented on docs/lang/pointer.md
> +这时候 `p` 就是一个结构体指针，其类型是 `node *`
```suggestion
这时候 `p` 就是一个结构体指针，其类型是 `node *` 。
```
下同

2020-02-16 12:26 UTC, Ir1d commented
我觉得好像没讲过.. :thinking:

2020-02-16 12:28 UTC, orzAtalod commented
文章最开头。。？

2020-02-16 12:34 UTC, orzAtalod commented
有谁会 note 里的无序列表啊（

2020-02-20 00:50 UTC, accelsao commented
> 有谁会 note 里的无序列表啊（

你指的是这个吗
* 列表 1
* 列表 2
* 列表 3
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

2020-02-28 15:05 UTC, ShyButHandsome commented on docs/lang/pointer.md
> +可以发现 `a` 和 `b` 的值没有成功交换。因为函数的参数 `x` 和 `y` 是一个与原来的 `a`  `b` 不同的左值，修改他们并不能修改 `main` 函数中的 `a` 和 `b` 。同样，这样做也不行：
个人认为这里解释的不太好，其实我觉得这里应该用**作用域**来解释，好吧，其实连作用域都用不上。我觉得可以这么说：
——分割线——
请思考并解释下面这段代码含义
```cpp
void change(int x, int y) {
  int t = x;
  x = y;
  y = t;
}
// main
int a = 1, b = 2;
change(a, b);
```

也许你会这么认为：
 这段代码声明了t并用把a的值赋给t
又把b的值赋给a
再让变量t（原来a的值）赋给b
哈哈！不就是交换了a、b的值嘛！

不对，并不是这样
其实这段代码是这样的：
1. 在函数执行时创建两个int类型的局部变量x，y（称为形参）
2. 用a，b（称为实参）的值为x，y初始化
3. 创建一个int类型的变脸t（temp，临时的意思）并使用x的值（即a的值）为其初始化
4. 将形参y的值赋给x（注意！是赋给了x，x与a之间并不存在唯一的映射关系，换句话来说，就是已经和a没关系了）
5. 将t的值赋给y（而不是b）
得出结论：这段代码仅仅是交换了两个形参x，y的值，对实参并没有影响
想想是不是？
如果还是不明白，可以在评论区进行交流哦！
——分割线——
怎么写着写着写出了种营销号的感觉？？？

2020-11-24 10:31 UTC, PeterlitsZo commented on docs/lang/pointer.md
> +数组其实就是一种特殊的指针，所以说访问数组也可以这么写：
数组的变量名也不是指向它的第一个元素的指针。它可以进行转换，在内部却是不一样的。比如：
``` C
sizeof(array)
```
返回的并不是指针应该占有的长度。

另外，数组它并不存在一个所谓的储存地址的值，和指针很不一样。

2020-11-24 10:35 UTC, PeterlitsZo commented
这个还没 OK 吗 www

2020-12-29 09:37 UTC, ksyx commented on docs/lang/pointer.md
> +指针一个经典应用就是 **交换两数的值** 。接下来将会给出几份用函数实现交换两数的值的代码。
这个 case 感觉指针用的有点生硬 可以 t=a，a=b，b=t，但是上了指针
另外 经典应用 citation needed

2020-12-29 09:37 UTC, ksyx commented on docs/lang/pointer.md
> +    包含：+void 类型（可有 cv 限定，即 const 或 volatile 限定）；+ 已声明（例如由前置声明）但未定义的类类型；+ 未知边界数组；+ 不完整类型元素的数组；+ 枚举类型，从其声明点到确定其底层类型之间。
这个 + 是啥

2020-12-29 09:37 UTC, ksyx commented on docs/lang/pointer.md
> +// 现在 w 是一个 int 数组了，长度为 500
w 指向 长度为 500 的 int 数组

2020-12-29 09:37 UTC, ksyx commented on docs/lang/pointer.md
> +（记得提醒作者他咕了）
todo

2021-01-27 01:56 UTC, CoelacanthusHex commented on docs/lang/pointer.md
> +学习指针之前，我们需要先学习 **左值** （leftvalue）和 **右值** （rightvalue）的概念。在 C++ 中，能够出现在赋值运算符（ `=` ）左边的值就叫左值，只能出现在赋值运算符右边的值就叫右值[^note1]。
我没记错的话这个左值右值的定义仅适用于 CPL 语言，C++ 在 C++11 前（左值和右值，但定义和判断方式都不同），C++11 到 C++17 （左值，纯右值和亡值）和 C++17 后（一套很复杂的）分别有三套分类方法，但是都不是使用的这一套，C 语言分为左值和非左值

2021-01-27 01:58 UTC, CoelacanthusHex commented on docs/lang/pointer.md
> +学习指针之前，我们需要先学习 **左值** （leftvalue）和 **右值** （rightvalue）的概念。在 C++ 中，能够出现在赋值运算符（ `=` ）左边的值就叫左值，只能出现在赋值运算符右边的值就叫右值[^note1]。
你的描述和脚注指向的链接就不符

2021-01-27 02:00 UTC, CoelacanthusHex commented on docs/lang/pointer.md
> +学习指针之前，我们需要先学习 **左值** （leftvalue）和 **右值** （rightvalue）的概念。在 C++ 中，能够出现在赋值运算符（ `=` ）左边的值就叫左值，只能出现在赋值运算符右边的值就叫右值[^note1]。
-	C 的表达式被分为“左值 (lvalue) 表达式”和其他（函数和非对象值）
-	“C 社区中对此的观点主要围绕着 lvalue 的含义而有所差异，一组人认为 lvalue 是任何种类的对象定位器，另一组人认为 lvalue 在赋值运算符的左侧时才有意义。C89 委员会采纳了作为对象定位器的定义。”—— ANSI C 基本原理，6.3.2.1/10 。
- 	2011 年前的 C++ 遵循 C 模型，但恢复了对非左值表达式的“右值 (rvalue)”称呼，令函数为左值，并添加了引用能绑定到左值但唯有 const 的引用能绑定到右值的规则。几种非左值的 C 表达式在 C++ 中成为了左值表达式。

2021-01-27 02:04 UTC, CoelacanthusHex requested changes

2021-01-27 02:04 UTC, CoelacanthusHex commented on docs/lang/pointer.md
> +[^note1]&#x3A; 这里使用的是 C 中的定义，C++98 标准中继续沿用了该种划分方式。但在 C++11 标准中，值类型被重新定义，所有的值被分为左值，纯右值和亡值三类。更详细的内容可以参考 [值类别 - cppreference.com](https://zh.cppreference.com/w/cpp/language/value_category) 。
```suggestion
[^note1]: 这里使用的是 C 中的定义，C++98 标准中继续沿用了该种划分方式。但在 C++11 标准中，值类型被重新定义，所有的值被分为左值，纯右值和亡值三类。更详细的内容可以参考 [值类别 - cppreference.com](https://zh.cppreference.com/w/cpp/language/value_category) 。
```

2021-03-16 13:17 UTC, CoderOJ commented on docs/lang/pointer.md
> +学习指针之前，我们需要先学习 **左值** （leftvalue）和 **右值** （rightvalue）的概念。在 C++ 中，能够出现在赋值运算符（ `=` ）左边的值就叫左值，只能出现在赋值运算符右边的值就叫右值[^note1]。
现在 OI-wiki 上已经有[一个页面](https://oi-wiki.org/lang/value-category/) 讲值类别了，这个地发是不是放个链接就好了

2021-05-16 03:26 UTC, ksyx reviewed
- 建议添加 shared_ptr 相关
- 一些不是很 OI 的东西
  - 类成员函数指针

2021-05-16 03:26 UTC, ksyx commented on docs/lang/pointer.md
> +cout << a << b;
```suggestion
int main() {
  int a = 1, b = 2;
  swap(a, b);
  cout << a << b;
}
```

2021-05-16 03:26 UTC, ksyx commented on docs/lang/pointer.md
> +可以发现 `a` 和 `b` 的值没有成功交换。因为 `swap` 函数的参数 `a` 和 `b` 与 `main` 函数中的 `a`  `b` 不同（虽然它们的名字相同）。交换 `swap` 函数中的 `a` 和 `b` ，并不会对 `main` 中的两个变量造成影响。
[为什么？]

2021-05-16 03:26 UTC, ksyx commented on docs/lang/pointer.md
> +cout << a << b;
```suggestion
int main() {
  int a = 1, b = 2;
  swap(&a, &b);
  cout << a << b;
}
```

2021-05-16 03:26 UTC, ksyx commented on docs/lang/pointer.md
> +指针除了取址和解引用之外，还有不少运算操作。以下选段假设 `p` 是指向 `int` 类型变量的指针， `x` 是某一个整数。
```suggestion
指针除了取址和解引用之外，还有不少运算操作。以下假设 `p` 是指向 `int` 类型变量的指针， `x` 是一个整数。
```

2021-05-16 03:26 UTC, ksyx commented on docs/lang/pointer.md
> +指针加整数 `p+x` 的值即为一个新指针，该新指针的值为 `p` 右移 `x*sizeof(*p)` 字节的值。注意“右移”不是“右位移”，“右位移”是位运算的操作。 `sizeof(*p)` 取出 `*p` 类型对应的字节数。
```suggestion
指针加整数 `p+x` 的值即为一个新指针，该新指针的值为 `p` 右移 `x*sizeof(*p)` 字节的值。注意“右移”不是“右位移”（`>>`）。 `sizeof(*p)` 可以通过 `sizeof` **运算符**计算出 `*p` 类型对应的字节数。
```

2021-05-16 03:26 UTC, ksyx commented on docs/lang/pointer.md
> +这里为什么是四个四个加呢？因为各类型占内存大小不同。指针编号的单位是字节，而 `int` 类型占四个字节。因为 `char` 类型正好占一个字节，所以如果需要指定位移的字节数，我们会将指针强制转换成 `char*` 类型。
指明 x86/64？

2021-05-16 03:26 UTC, ksyx commented on docs/lang/pointer.md
> +有时候一些字符串题从 1 开始读入字符串会更为方便，而如果用 `scanf` 读入字符串的话，实际上需要用一个字符数组。
```suggestion
有时候一些字符串题从下标 $1$ 开始读入字符串会更为方便，而如果用 `scanf` 读入字符串的话，实际上需要传入一个 `char*` 指针。
```

2021-05-16 03:26 UTC, ksyx commented on docs/lang/pointer.md
> +scanf("%s", str)
```suggestion
char str[100005];

int main() {
  scanf("%s", str)
}
```

2021-05-16 03:26 UTC, ksyx commented on docs/lang/pointer.md
> +```
```suggestion
而这里的读入是从下标 0 开始读入的。要从下标 $1$ 读入，则需要写成 `scanf("%s", str + 1);`。
```

2021-05-16 03:26 UTC, ksyx commented on docs/lang/pointer.md
> +同样，使用 `strlen(str+1)` 可以处理从 1 开始的字符串的长度。
```suggestion
同样，使用 `strlen(str+1)` 可以计算从下标 $1$ 开始的字符串的长度。
```

2021-05-16 03:26 UTC, ksyx commented on docs/lang/pointer.md
> +// read2
```suggestion
```

2021-05-16 03:26 UTC, ksyx commented on docs/lang/pointer.md
> +// read
```suggestion
```

2021-05-16 03:26 UTC, ksyx commented on docs/lang/pointer.md
> +具体来说，假设我们定义 `int *w1[100]` ， `int (*w2)[100]` 以便于区分，那么 w1 就是一个长度为 100 的数组，这里面的每一个元素都是一个 `int *` 。而 `w2` 是一个指针，指向一个长度为 100 的数组。如果 `w2` 到 `w2+99` 都是一个与 `w2` 类型相同的指针，即如果他们都指向一个长度为 100 的数组，那么 `w2` 就可以作为一
```suggestion
具体来说，假设我们定义 `int *w1[100]` ， `int (*w2)[100]` 以便于区分，那么 w1 就是一个长度为 100 的数组，这里面的每一个元素都是一个 `int *` 。而 `w2` 是一个指针，指向一个长度为 100 的数组。如果 `w2` 到 `w2+99` 都是一个与 `w2` 类型相同的指针，即如果他们都指向一个长度为 $100$ 的数组，那么 `w2` 就可以作为一个长度为 $100\times 100$ 的二维数组名来访问与读取。
```

2021-05-16 03:26 UTC, ksyx commented on docs/lang/pointer.md
> +  // 也可写作 std::printf("%d",(*(calc(opt)))(a,b));
一定需要 `std::` 吗

2021-05-16 03:26 UTC, ksyx commented on docs/lang/pointer.md
> +实际上，这样的类型声明很恶心，容易出错。借助 `typedef` ，可以这样干：
```suggestion
实际上，这样的类型声明并不是非常美观，且容易出错。此时我们可以借助 `typedef` 使代码更清晰：
```

2021-05-16 03:26 UTC, ksyx commented on docs/lang/pointer.md
> +    1, 2, 3, 4, 5, 6};  // 定义了一个长度为 6 的数组，元素依次为 1,2,3,4,5,6
```suggestion
 `new` 还可以在分配内存的同时进行初始化。例如，如果想要分配一个 $100\times 100$ 的二维 int 数组，都初始化成 $0$，可以写成：`int (*w)[100] = new int[100][100]{};`，其类似于在全局命名空间中定义数组时的初始化。
 
此外，还可以通过 `int *arr = new int[6]{1, 2, 3, 4, 5, 6};` 这样的形式来初始化。这一语句定义了一个长度为 $6$ 的数组，其内的元素依次为 $1,~2,~3,~4,~5,~6$。
```

2021-05-16 04:06 UTC, Xeonacid commented on docs/lang/pointer.md
> +    1, 2, 3, 4, 5, 6};  // 定义了一个长度为 6 的数组，元素依次为 1,2,3,4,5,6
@ksyx 
> $1,~2,~3,~4,~5,~6$

这里为什么要加空格？wiki 里现在好像并没有这么干过（

2021-05-16 04:07 UTC, Xeonacid commented on docs/lang/pointer.md
> +  // 也可写作 std::printf("%d",(*(calc(opt)))(a,b));
不一定，虽然这更符合C++标准，但是按照习惯我也支持不写（

2021-05-16 04:07 UTC, Xeonacid commented on docs/lang/pointer.md
> +scanf("%s", str)
@ksyx 分号？

2021-05-16 04:08 UTC, Xeonacid commented on docs/lang/pointer.md
> +指针加整数 `p+x` 的值即为一个新指针，该新指针的值为 `p` 右移 `x*sizeof(*p)` 字节的值。注意“右移”不是“右位移”，“右位移”是位运算的操作。 `sizeof(*p)` 取出 `*p` 类型对应的字节数。
@ksyx 为什么要加粗「运算符」呢

2021-05-16 04:08 UTC, ksyx commented on docs/lang/pointer.md
> +    1, 2, 3, 4, 5, 6};  // 定义了一个长度为 6 的数组，元素依次为 1,2,3,4,5,6
> @ksyx
$1,~2,~3,~4,~5,~6$
这里为什么要加空格？wiki 里现在好像并没有这么干过（

reverted.

2021-05-16 04:09 UTC, Xeonacid commented
@ksyx 不是很 OI 的东西也可以加进来吧（

2021-06-28 12:44 UTC, CoelacanthusHex commented on docs/lang/pointer.md
> +  // 也可写作 std::printf("%d",(*(calc(opt)))(a,b));
> 一定需要 `std::` 吗

~~一般需要看上下文吧，如果是 include 的 stdio.h 就不能加，如果是 cstdio 就可以加
前者会报错~~
```log
test.cpp: In function ‘int main()’:
test.cpp:10:14: error: ‘printf’ is not a member of ‘std’; did you mean ‘printf’?
   10 |         std::printf("%d", 1);
      |              ^~~~~~
In file included from test.cpp:8:
/usr/include/stdio.h:332:12: note: ‘printf’ declared here
  332 | extern int printf (const char *__restrict __format, ...);
      |            ^~~~~~
```
啊是 cstdio 啊，那没事了（
无论加不加都会查找到这个名字（
（只不过加上更美观也更符合 C++ 的习惯

2021-06-28 12:45 UTC, CoelacanthusHex commented
?ping @szdytom @orzAtalod

2021-07-01 09:33 UTC, szdytom commented
!pong @CoelacanthusHex

2021-09-12 08:52 UTC, StudyingFather commented
#3480 已经把这坑填了，这个就 close 了 :smile:

2021-09-12 08:52 UTC, closed without merging