增加linear-sieve内容，就是对埃氏筛的改良，改进为线性时间复杂度。
OI-wiki/OI-wiki pull request #2493
Opened 2020-08-03 13:30 UTC by zyj2297349886

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论你是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈你的感受
3. 如果你熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2020-08-03 13:31 UTC, ksyx commented on mkdocs.yml
> +      -线性埃氏筛: math/linear-eratosthenes-sieve.md
```suggestion
      - 线性埃氏筛: math/linear-eratosthenes-sieve.md
```

2020-08-03 13:32 UTC, ksyx commented on docs/math/linear-eratosthenes-sieve.md
> +## 线性埃拉托色尼筛（Sieve of Eratosthenes Having Linear Time Complexity）
不需要重复标题

2020-08-04 08:01 UTC, Enter-tainer commented
建议与 https://oi-wiki.org/math/sieve/ 页面合并

2020-08-04 12:20 UTC, ksyx commented
标题级别不对

2020-08-06 03:08 UTC, Enter-tainer commented on docs/math/sieve.md
> +我们的目的是计算范围 $[2,n]$ 中每个整数的最小质因数 $lp [i]$ 。
请阅读格式手册 
![image](https://user-images.githubusercontent.com/25521218/89486206-1c3d3280-d7d5-11ea-82e2-f30f6e1b95a3.png)

此处建议使用 `lp[i]`

2020-08-06 03:13 UTC, Enter-tainer commented
线性埃氏筛 和 页面前面介绍的线性筛是同一种算法，且页面前面介绍的更加详细，closed.

2020-08-06 03:14 UTC, ouuan commented
这个就是这篇中的"以上做法仍有优化空间，我们发现这里面似乎会对某些数标记了很多次其为合数。有没有什么办法省掉无意义的步骤呢？"。可以把 素数筛法 拆成埃氏筛和线性筛，然后扩充一下线性筛的内容。

> 线性埃氏筛 和 页面前面介绍的线性筛是同一种算法，且页面前面介绍的更加详细，closed.

前面，真的，更详细吗？

2020-08-06 03:14 UTC, ouuan commented
![图片](https://user-images.githubusercontent.com/30581822/89486606-ffedc580-d7d5-11ea-9d6f-cb7a15d8940d.png)

《前面》

2020-08-06 03:17 UTC, ksyx commented on docs/math/sieve.md
> +我们的目的是计算范围 $[2,n]$ 中每个整数的最小质因数 $lp [i]$ 。
如果要使用公式建议 \textit{lp}_i

2020-08-06 07:14 UTC, zyj2297349886 commented on docs/math/sieve.md
> +我们的目的是计算范围 $[2,n]$ 中每个整数的最小质因数 $lp [i]$ 。
![image](https://user-images.githubusercontent.com/52376036/89502362-7949e000-d7f7-11ea-8d13-ffe1bb3528f2.png)
那这些也都写成  `lp[i]`   样式？

2020-08-06 07:17 UTC, Enter-tainer commented on docs/math/sieve.md
> +我们的目的是计算范围 $[2,n]$ 中每个整数的最小质因数 $lp [i]$ 。
可以参考 ksyx 的建议，两种都可以

2020-08-07 12:48 UTC, Xeonacid commented on docs/math/sieve.md
> +线性筛算法的缺点是使用的空间比 **Eratosthenes 筛法** 更多：它需要一个大小为 $n$ 数组。
```suggestion
线性筛算法的缺点是使用的空间比 **Eratosthenes 筛法** 更多：它需要一个大小为 $n$ 的数组。
```

2020-08-07 12:49 UTC, Xeonacid commented on docs/math/sieve.md
> +我们可以通过使用数组和计数器替换 $pr$ 并省去 $for$ 循环中的乘法来加快速度（为此，我们只需要记录每一次的乘积即可）。
```suggestion
我们可以通过使用数组和计数器替换 $pr$ 并省去 for 循环中的乘法来加快速度（为此，我们只需要记录每一次的乘积即可）。
```

2020-08-07 12:50 UTC, Xeonacid commented on docs/math/sieve.md
> +考虑算法的空间复杂度：一个大小为 $n$ 的数组 $lp []$ , 和一个大小为 $\frac n {\ln n}$ 的数组 $pr []$ , 这个算法的空间复杂度显然比经典 **Eratosthenes 筛** 算法要差。
```suggestion
考虑算法的空间复杂度：一个大小为 $n$ 的数组 $lp []$ , 和一个大小为 $\dfrac n {\ln n}$ 的数组 $pr []$ , 这个算法的空间复杂度显然比经典 **Eratosthenes 筛** 算法要差。
```
行内公式中表示分数应使用 `\dfrac`，请仔细阅读格式手册

2020-08-10 03:41 UTC, zyj2297349886 commented
已更新

2020-09-02 13:20 UTC, zyj2297349886 commented
已更新

2020-09-02 13:45 UTC, ksyx commented on docs/math/sieve.md
> +该算法空间复杂度是 $n$ 。
不是很清楚这里在干什么

2020-09-02 13:45 UTC, ksyx commented on docs/math/sieve.md
> +该算法空间复杂度是 $n$ 。
不是很清楚这里在干什么

2020-10-06 02:10 UTC, sshwy requested changes

2020-10-06 02:10 UTC, sshwy commented on docs/graph/mod-shortest-path.md
> + [\[国家集训队\]墨墨的等式](https://www.luogu.com.cn/problem/P2371)
```suggestion
 [「国家集训队」墨墨的等式](https://www.luogu.com.cn/problem/P2371) 
```

2020-10-06 02:10 UTC, sshwy commented on docs/math/sieve.md
> +该算法的正确性及其运行时间的证明放在代码实现之后。
是废话，删了吧（

2020-10-06 02:10 UTC, sshwy commented on docs/math/sieve.md
> +此外，我们还需要把找到的质数存起来，存到数组 $\textit{pr}[]$ 当中。
```suggestion
此外，我们还需要把找到的质数存起来，存到数组 $\textit{pr}$ 当中。
```

2020-10-06 02:10 UTC, sshwy commented on docs/math/sieve.md
> +此外，我们还需要把找到的质数存起来，存到数组 $\textit{pr}[]$ 当中。
其他同理

2020-10-06 02:10 UTC, sshwy commented on docs/math/sieve.md
> +该算法将具有线性运行时间，时间复杂度为 $O(n)$ 。
```suggestion
该算法时间复杂度为 $O(n)$ 。
```

2020-10-06 02:10 UTC, sshwy commented on docs/math/sieve.md
> +该算法空间复杂度是 $n$ ，而经典 **Eratosthenes 筛** 算法的空间复杂度是 $\dfrac n {\ln n}$ 。
```suggestion
该算法空间复杂度 $O(n)$ ，而经典 **Eratosthenes 筛** 算法的空间复杂度是 $\dfrac n {\ln n}$ 。
```

2020-10-06 02:10 UTC, sshwy commented on docs/math/sieve.md
> +
评论性的语句可以删了（

2020-10-06 02:43 UTC, zyj-111 commented on docs/math/sieve.md
> +
👌

2020-10-07 07:01 UTC, zyj-111 commented on docs/graph/mod-shortest-path.md
> + [\[国家集训队\]墨墨的等式](https://www.luogu.com.cn/problem/P2371)
啊这，，这不是我翻译文件里的东西。那我一并改了？

2020-10-20 15:17 UTC, closed without merging