增加Counting labeled graph内容
OI-wiki/OI-wiki pull request #2531
Opened 2020-08-07 11:53 UTC by zyj2297349886

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论你是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈你的感受
3. 如果你熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2020-10-06 00:47 UTC, sshwy requested changes

2020-10-06 00:47 UTC, sshwy commented on docs/graph/counting-labeled-graphs.md
> +## 连通分支标号图
```suggestion
## 无向连通图
```

之后同理

2020-10-06 00:47 UTC, sshwy commented on docs/graph/counting-labeled-graphs.md
> +我们用 $C_n$ 表示 $n$ 顶点连通图所需数量。
什么叫所需数量

2020-10-06 00:47 UTC, sshwy commented on docs/graph/counting-labeled-graphs.md
> +在此我们还附加了连通图的限制条件。
都说了是连通图了，这句话就不用说了（

2020-10-06 00:47 UTC, sshwy commented on docs/graph/counting-labeled-graphs.md
> +首先我们讨论存在多少非连通图。然后用 $G_n$ 减去非连通图数就可以得到连通图数。另外我们会计算连通根图的数量。根图就是我们通过讲一个顶点标记为根顶点的一类图。显然，对于一个 $n$ 点标号图，可以产生 $n$ 中根图。因此我们在最后将结果除以 $n$ ，这样获得的结果就是非连通图的数目。
```suggestion
首先我们讨论存在多少非连通图。然后用 $G_n$ 减去非连通图数就可以得到连通图数。另外我们会计算连通根图的数量。根图就是我们通过将一个顶点标记为根顶点的一类图。显然，对于一个 $n$ 点标号图，可以产生 $n$ 种根图。因此我们在最后将结果除以 $n$ ，这样获得的结果就是非连通图的数目。
```

2020-10-06 00:47 UTC, sshwy commented on docs/graph/counting-labeled-graphs.md
> +根顶点会出现在大小为 $1,\cdots,n-1$ 的连通分支中。有 $k \dbinom{n}{k} C_k G_{n-k}$ 种方式使得根顶点位于具有 $k$ 个顶点的连通分支中。（有 $\dbinom{n}{k}$ 中方式选择 $k$ 个分支，它们以 $C_k$ 种方式被连通到一起。 $k$ 个顶点中任意一个都可以是根顶点，而剩下的 $n-k$ 个顶点可以以任何方式连通或者断开，从而了 $
连通分支改为连通块

2020-10-06 00:47 UTC, sshwy commented on docs/graph/counting-labeled-graphs.md
> +我们可以通过 dp 算法计算该数字。对于每个 $i\le n$ 和 $j\le k$ ，计算 $D[i][j]$ ——具有 $i$ 个顶点和 $j$ 个分量的标号图的数量。
```suggestion
考虑 DP。对于每个 $i\le n$ 和 $j\le k$ ，计算 $D[i][j]$ ——具有 $i$ 个顶点和 $j$ 个分量的标号图的数量。
```

2020-10-06 00:47 UTC, sshwy commented on docs/graph/counting-labeled-graphs.md
> +如果我们已经知道上一个值，就可以计算当前的 $D[n][k]$ 。取最后一个顶点（标号为 $n$ ），这个点属于某个分支。如果这个分支的大小为 $s$ ，那么就有 $\dbinom{n-1}{s-1}$ 中方法选择构成此分支的点集，并且有 $C_s$ 种方法连通它们。这样我们就得到如下的递归关系：
“上一个值”是什么，说清楚

如果说不清楚，不如吧这段话删掉

2020-10-15 06:11 UTC, sshwy requested changes
有关latex的格式要求可以阅读 https://oi-wiki.org/intro/format/#latex

2020-10-15 06:11 UTC, sshwy commented on docs/graph/counting-labeled-graphs.md
> +## 含 $k$ 个连通块的无向连通图
```suggestion
## 含 $k$ 个连通块的无向图
```
含k个连通块的图，不叫连通图（
其他地方同理

2020-10-15 06:11 UTC, sshwy commented on docs/graph/counting-labeled-graphs.md
> +考虑 DP。对于每个 $i\le n$ 和 $j\le k$ ，计算 $D[i][j]$ ——具有 $i$ 个顶点和 $j$ 个分量的标号图的数量。
```suggestion
考虑 DP。设 $D(i,j)$ 表示具有 $i$ 个顶点和 $j$ 个连通块的带标号图的数量。
```
其他地方同理

2021-01-27 11:47 UTC, Konano commented on docs/graph/counting-labeled-graphs.md
> +考虑 DP。设 $D(i,j)$ 表示具有 $i$ 个顶点和 $j$ 个连通块的带标号图的数量。
这里的 `D(i,j)` 和下面的 `D[i][j]` 统一一下？

2021-11-10 09:48 UTC, qwqAutomaton commented
这是否可以合到计数 dp 里面？感觉单独开一个页面内容有点少 qwq

2021-12-20 13:44 UTC, StudyingFather commented
stale pr, closed.

2021-12-20 13:44 UTC, closed without merging