修改2d的一处细节
OI-wiki/OI-wiki pull request #2533
Opened 2020-08-07 16:18 UTC by zyj2297349886

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论你是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈你的感受
3. 如果你熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2020-08-10 02:13 UTC, Xeonacid commented on docs/geometry/2d.md
> +通过 `Cramer` 法则，我们可以很快地求得方程组地解，即为两直线交点：
```suggestion
通过 Cramer 法则，我们可以很快地求得方程组的解，即为两直线交点：
```

2020-08-10 02:13 UTC, Xeonacid commented on docs/geometry/2d.md
> +```c
```suggestion
```cpp
```

2020-08-10 02:13 UTC, Xeonacid commented on docs/geometry/2d.md
> +```c
```suggestion
```cpp
```

2020-09-23 23:34 UTC, ksyx reviewed
先改这个 影响高亮了

2020-09-23 23:34 UTC, ksyx commented on docs/geometry/2d.md
> +    ```
unexpected end of code

2020-09-23 23:34 UTC, ksyx commented on docs/geometry/2d.md
> +    ```
```suggestion

```

2020-10-06 00:25 UTC, sshwy requested changes

2020-10-06 00:25 UTC, sshwy commented on docs/geometry/2d.md
> +通过 Cramer 法则，我们可以很快地求得方程组的解，即为两直线交点：
Cramer法则是什么

2020-10-06 00:25 UTC, sshwy commented on docs/geometry/2d.md
> +    ```
```suggestion
    
```

2020-10-06 00:25 UTC, sshwy commented on docs/geometry/2d.md
> +### 求线段长度和
这不是计算几何的技巧，建议删除

2020-10-20 15:15 UTC, closed without merging