Update monotonous-queue-stack.md
OI-wiki/OI-wiki pull request #2571
Opened 2020-08-18 07:53 UTC by fogsail

添加单调队列优化dp的参考代码

2020-08-19 11:02 UTC, StudyingFather commented on docs/dp/opt/monotonous-queue-stack.md
> +    ```bash
```suggestion
    ```cpp
```

2020-08-19 11:03 UTC, StudyingFather approved these changes

2020-08-19 17:39 UTC, Konano approved these changes

2020-08-20 01:04 UTC, Early0v0 approved these changes

2020-08-20 06:45 UTC, StudyingFather approved these changes

2020-08-20 06:47 UTC, StudyingFather requested changes
似乎有些地方缩进没补够，我先 block 下 :thinking:

2020-08-20 07:34 UTC, StudyingFather approved these changes

2020-08-20 17:43 UTC, Konano approved these changes

2020-08-20 23:33 UTC, Early0v0 approved these changes

2020-08-21 01:21 UTC, merged