Update monotonous-queue-stack.md
OI-wiki/OI-wiki pull request #2587
Opened 2020-08-23 17:47 UTC by fogsail

对单调队列优化中的例题，"Watching Fireworks is Fun" 的参考代码进行修改
这次加的代码是我已经 AC 通过的了
之前的参考代码忘记加上一些头文件和宏定义，导致会 CE

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论你是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈你的感受
3. 如果你熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2020-08-24 01:15 UTC, StudyingFather submitted a review, later dismissed
Thx!

另外，如果之前的修改有问题，可以直接在原来的分支上进行修改，修改进度会自动同步至相应的 PR，不用重新开新的 PR :smile:

2020-08-26 12:52 UTC, Konano commented
代码内大量 define 是不是可以稍微整理下？里面甚至都出现了 debug……

以及感觉也混入了很多没必要的 include，可以一行 `#include<bits/stdc++.h>` 搞定？或者稍微整理下 include

2020-09-15 05:01 UTC, Enter-tainer requested changes
折叠框内的代码需要保留四个空格

2020-11-07 16:49 UTC, Konano approved these changes

2020-11-10 04:30 UTC, Enter-tainer approved these changes

2020-11-10 04:30 UTC, merged