refactor associative-container.md
OI-wiki/OI-wiki pull request #2604
Opened 2020-08-26 11:27 UTC by StudyingFather

`set` 和 `multiset`，`map` 和 `multimap` 中重复的内容较多，这次将这些内容进行了合并。

另外添加了自定义比较器和遍历容器的相关内容。

closes #1843.

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论你是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈你的感受
3. 如果你熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2020-08-26 12:43 UTC, Konano approved these changes

2020-08-26 12:43 UTC, Konano commented on docs/lang/op-overload.md
> +    // a.name);
auto format 问题

2020-08-26 12:43 UTC, Konano commented on docs/lang/csl/associative-container.md
> +和数学中的集合相似， `set` 中不会出现值相同的元素。如果需要有相同元素的集合，需要使用 `multiset` 。 `multiset` 的使用方法与 `set` 的使用方法基本相同。
```suggestion
和数学中的集合相似， `set` 中不会出现值相同的元素。如果需要有相同元素的集合，需要使用 `multiset`。 `multiset` 的使用方法与 `set` 的使用方法基本相同。
```

2020-08-26 12:56 UTC, Konano approved these changes

2020-08-27 00:15 UTC, Xeonacid requested changes
map 还是 `map`，需要统一一下

2020-08-27 09:09 UTC, Xeonacid commented on docs/lang/op-overload.md
> -    // this->score<a.score||(this->score==a.score&&this->name>a.name);
这个为什么要干掉呢 🤔

2020-08-27 19:15 UTC, Konano approved these changes

2020-08-28 01:05 UTC, Xeonacid approved these changes

2020-08-28 01:05 UTC, merged