Update mobius.md 更改了例题二中不必要的分类讨论，并增加了线筛的推导过程
OI-wiki/OI-wiki pull request #2622
Opened 2020-08-31 15:45 UTC by Vxlimo

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论你是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈你的感受
3. 如果你熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2020-09-01 11:38 UTC, Early0v0 requested changes

2020-09-01 11:38 UTC, Early0v0 commented on docs/math/mobius.md
> +\operatorname g(p_j^{k+1})=g(p_j^k)+p_j^{2k+1}\cdot(p_j-1)
```suggestion
\operatorname g(p_j^{k+1})=\operatorname g(p_j^k)+p_j^{2k+1}\cdot(p_j-1)
```

2020-09-01 11:38 UTC, Early0v0 commented on docs/math/mobius.md
> +\operatorname g(i\cdot p_j)=\operatorname g(i)+(\operatorname g(i)-\operatorname g(\frac{i}{p_j}))\cdot p_j^2
```suggestion
\operatorname g(i\cdot p_j)=\operatorname g(i)+\left (\operatorname g(i)-\operatorname g(\frac{i}{p_j})\right )\cdot p_j^2
```

2020-09-01 11:56 UTC, Early0v0 approved these changes

2020-09-05 16:54 UTC, StudyingFather approved these changes

2020-09-05 16:54 UTC, merged