feat: add Git
OI-wiki/OI-wiki pull request #2627
Opened 2020-09-04 09:39 UTC by StudyingFather

添加了 Git 的使用指南。

目前还没写完，里面有些内容还是照搬的我之前写的 [一篇不太充实的文章](https://studyingfather.blog.luogu.org/git-guide)，在格式和内容上要改的应该还不少（

closes #1674.

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论你是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈你的感受
3. 如果你熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2020-09-06 12:22 UTC, Xeonacid commented on docs/tools/git.md
> +对于 Mac 系统，只需在终端执行 `brew install git` 命令即可安装。
```suggestion
对于 macOS 系统，只需在终端执行 `brew install git` 命令即可安装。（需安装 [Homebrew](https://brew.sh/)）
```

2020-09-06 12:22 UTC, Xeonacid commented on docs/tools/git.md
> +$ git config --global user.name "OI Wiki"
这里要不要标一下改成自己的用户名和邮箱（雾）

2020-09-11 07:38 UTC, NachtgeistW commented on docs/tools/git.md
> +$ git config --global user.name "OI Wiki"
我认为还是应该改的，毕竟真的会有照着改成 OI Wiki 的人

2020-09-11 08:05 UTC, NachtgeistW commented on docs/tools/git.md
> +新建一个 Git 仓库非常简单，只需在你想要建立仓库的文件夹输入如下命令：
```suggestion
新建一个 Git 仓库非常简单，只需在当前目录输入如下命令：
```

2020-09-11 08:05 UTC, NachtgeistW commented on docs/tools/git.md
> +如果别人已经建立了一个仓库，你想要把这个仓库拷贝到自己的电脑上（比如将 **OI Wiki** 的代码拷贝到本地上进行编辑），采用 `git clone` 命令即可。
```suggestion
如果想把别人的仓库拷贝到自己的电脑上（比如将 **OI Wiki** 的代码拷贝到本地上进行编辑），采用 `git clone` 命令即可。
```

2020-09-11 08:06 UTC, NachtgeistW commented
还是得注意下，尽量避开第一人称

2020-09-11 15:30 UTC, ouuan commented on docs/tools/git.md
> +新建一个 Git 仓库非常简单，只需在你想要建立仓库的文件夹输入如下命令：
不是很懂为啥要改成“当前目录”。我好像在 Reddit 见过在 Windows 的 home 建仓库的（（（

2020-09-11 15:31 UTC, ouuan commented on docs/tools/git.md
> +如果别人已经建立了一个仓库，你想要把这个仓库拷贝到自己的电脑上（比如将 **OI Wiki** 的代码拷贝到本地上进行编辑），采用 `git clone` 命令即可。
“把一个仓库拷贝到本地”会不会更好，因为不一定是别人的。

2020-09-11 15:56 UTC, ouuan reviewed
~~还有一点就是，命令为啥每条加个 `$`，除了没法复制，它到底有啥作用啊 /fad 没搜到，盲猜一波以前没高亮没 Markdown 的时候用来标识的。~~

我在 2020.9.14 左右就已经指导 `$` 和 `#` 用来区别是否有 root 权限了。

请看下面的 https://github.com/OI-wiki/OI-wiki/pull/2627#issuecomment-698934464

2020-09-11 15:56 UTC, ouuan commented on docs/tools/git.md
> +在 Windows 下，配置编辑器的过程可能会稍有麻烦，具体配置方式可以在网络上查找相关资料。
为啥会麻烦啊 /yun 是说可执行文件不在 path 里吗。

2020-09-11 15:56 UTC, ouuan commented on docs/tools/git.md
> +Git 是目前使用最广泛的版本控制系统。**OI Wiki** 也使用了 Git 作为版本控制系统。
> Git 是目前使用最广泛的版本控制系统。

来源请求 /fad

2020-09-11 15:56 UTC, ouuan commented on docs/tools/git.md
> +3. 当前仓库目录下的 `.git/config` 文件：只适用于该仓库。
1. 这个是针对 Linux 的，感觉不太好。
2. 一般不需要关心放哪吧，尤其是初学，会 `git config --global` 就够了。

2020-09-11 15:56 UTC, ouuan commented on docs/tools/git.md
> +可以通过 `git config --list` 列出当前已经设置的所有配置参数。
```suggestion
可以通过 `git config -l` 列出当前已经设置的所有配置参数。使用 `git config --global -l` 可以列出所有全局配置。
```

2020-09-11 15:56 UTC, ouuan commented on docs/tools/git.md
> +$ git clone https://github.com/OI-wiki/OI-wiki.git
```suggestion
$ git clone https://github.com/OI-wiki/OI-wiki
```

2020-09-11 15:56 UTC, ouuan commented on docs/tools/git.md
> +这样在当前文件夹下，就会新建一个名为 `OI-wiki` 的仓库，里面存放着原来仓库的所有信息。
```suggestion
这样在当前文件夹下，就会新建一个名为 `OI-wiki` 的仓库，里面存放着被克隆的仓库的内容。
```

诸如 PR/issues，被 force-push 掉的 commits 之类的应该不会有。

2020-09-11 15:56 UTC, ouuan commented on docs/tools/git.md
> +$ vi README.md # 写点东西
```suggestion
```

上文已经“假设我们在一个空仓库中新增了一个 `README.md` 文件”了，这里有点冗余。

2020-09-11 15:56 UTC, ouuan commented on docs/tools/git.md
> +- `-a`：自动将非暂存区内的提交放入暂存区，然后提交暂存区中的所有更改。需要注意的是未被跟踪的文件（新创建的文件）不会被自动加入暂存区，需要用 `git add` 命令手动添加。
```suggestion
- `-a`：在提交前将所有已跟踪的文件的更改放入暂存区。需要注意的是未被跟踪的文件（新创建的文件）不会被自动加入暂存区，需要用 `git add` 命令手动添加。
```

2020-09-11 15:56 UTC, ouuan commented on docs/tools/git.md
> +另外，commit 过程中可以利用几个参数来简化提交过程：
在合适的位置加个 `git add -A` 吧。

2020-09-11 15:56 UTC, ouuan commented on docs/tools/git.md
> +可以看到，提交历史里记录了每次提交时的 SHA-1 校验和，提交的作出者，提交时间和 commit 信息。
```suggestion
可以看到，提交历史里记录了每次提交时的 SHA-1 校验和，提交的作者，提交时间和 commit 信息。
```

这里确实是 author 而不是 committer，例如 cherry-pick 后 author 不变。

2020-09-11 15:56 UTC, ouuan commented on docs/tools/git.md
> +利用 `git branch` 命令可以创建分支，`git checkout` 命令可以切换分支。
```suggestion
利用 `git branch` 命令可以创建分支，`git switch` 命令可以切换分支，`git switch -c` 命令可以创建分支并切换到这个新分支。
```

2020-09-11 15:56 UTC, ouuan commented on docs/tools/git.md
> +利用 `git branch` 命令可以创建分支，`git checkout` 命令可以切换分支。
checkout 已经是时代的眼泪了（两个功能分别被 `git switch` 和 `git restore` 取代了）（虽然我自己还在用 checkout）

2020-09-11 15:56 UTC, ouuan commented on docs/tools/git.md
> +$ git checkout dev # 切换当前分支到 dev
```suggestion
$ git switch -c dev # 创建一个叫做 dev 的新分支并切换当前分支到 dev
```

2020-09-11 15:56 UTC, ouuan commented on docs/tools/git.md
> +$ git branch # 查看所有分支信息
```suggestion
$ git branch # 查看分支列表
```

远程分支等不会在这显示，而且这里只有名字没有其它信息。

2020-09-11 15:56 UTC, ouuan commented on docs/tools/git.md
> +
```suggestion
```

大多数情况下创建分支都会立刻切过去，不用放 note 里吧。

2020-09-11 15:56 UTC, ouuan commented on docs/tools/git.md
> +$ git commit -m "QAQ"
不要 QAQ，不要 QAQ，不要 QAQ（

2020-09-11 15:56 UTC, ouuan commented on docs/tools/git.md
> +在新分支上修改似乎和在 master 分支上修改没什么太大区别，事实上也确实如此，每个分支都是平等的。
```suggestion
```

理论上平等，实践中不平等。

2020-09-11 15:56 UTC, ouuan commented on docs/tools/git.md
> +[^note1]: `git log` 的更多用法可以参考 [Pro Git Book v2](https://git-scm.com/book/zh/v2/Git-%E5%9F%BA%E7%A1%80-%E6%9F%A5%E7%9C%8B%E6%8F%90%E4%BA%A4%E5%8E%86%E5%8F%B2)。
那么多命令，为啥唯独 log 给个 reference？

2020-09-11 15:59 UTC, ouuan commented
另外可以给个 https://learngitbranching.js.org/ 的 link /fad

2020-09-11 16:03 UTC, ouuan commented
可以在 htc 里给个 link。

2020-09-12 03:13 UTC, NachtgeistW commented on docs/tools/git.md
> +如果别人已经建立了一个仓库，你想要把这个仓库拷贝到自己的电脑上（比如将 **OI Wiki** 的代码拷贝到本地上进行编辑），采用 `git clone` 命令即可。
有道理，我改改

2020-09-12 03:14 UTC, NachtgeistW commented on docs/tools/git.md
> +新建一个 Git 仓库非常简单，只需在你想要建立仓库的文件夹输入如下命令：
为了避开第一人称啦（

2020-09-12 03:18 UTC, NachtgeistW commented on docs/tools/git.md
> +新建一个 Git 仓库非常简单，只需在你想要建立仓库的文件夹输入如下命令：
我还是再改改吧

2020-09-12 03:18 UTC, ouuan commented on docs/tools/git.md
> +新建一个 Git 仓库非常简单，只需在你想要建立仓库的文件夹输入如下命令：
首先这是第二人称。

然后我觉得这样写没啥问题。

你觉得不行的话把”你“去掉也行，”想要建立仓库的文件夹“这个意思要保留。

2020-09-12 03:29 UTC, NachtgeistW commented on docs/tools/git.md
> +新建一个 Git 仓库非常简单，只需在你想要建立仓库的文件夹输入如下命令：
嗯我直接把“你”去掉了。
之前改掉的原因是 git init 就是直接在当前目录下 init 的，要指定目录的话得在后面加上路径。

2020-09-12 03:31 UTC, NachtgeistW commented on docs/tools/git.md
> +$ git commit -m "QAQ"
```suggestion
$ git commit -m "添加一个 cpp 文件"
```

2020-09-12 03:32 UTC, ouuan commented on docs/tools/git.md
> +新建一个 Git 仓库非常简单，只需在你想要建立仓库的文件夹输入如下命令：
> 之前改掉的原因是 git init 就是直接在当前目录下 init 的，要指定目录的话得在后面加上路径。

那是命令的作用是“在当前目录新建仓库”，你需要做的事情是“在想要建立仓库的文件夹输入命令”。

2020-09-12 03:35 UTC, ouuan commented on docs/tools/git.md
> +$ git commit -m "QAQ"
> 一定要让新人从零开始养成良好的 commit 习惯new_moon_with_face

草，“一个 cpp 文件”也算良好吗（

```suggestion
$ git commit -m "添加 test.cpp"
```

其实最好是说一下具体做了什么，但这里没有 test.cpp 的内容，所以只能文件名了。

2020-09-12 03:38 UTC, NachtgeistW commented on docs/tools/git.md
> +
不，并不会，直接用 `git branch` 命令的话，git 是不会切到新分支去的

2020-09-12 03:39 UTC, ouuan commented on docs/tools/git.md
> +
> 不，并不会，直接用 `git branch` 命令的话，git 是不会切到新分支去的

我是说，大多数情况你会切过去，不是大多数命令会切过去。

2020-09-12 08:36 UTC, Xeonacid commented on docs/tools/git.md
> +$ vi README.md # 再随便修改点东西
```suggestion
$ vim README.md # 再随便修改点东西
```
其他同

2020-09-12 08:36 UTC, Xeonacid commented on docs/tools/git.md
> +    本页面将着重介绍 Git 这一版本控制系统，与 GitHub 相关的内容，请参考 [GitHub 帮助](https://docs.github.com/cn) 和 [如何参与 - OI Wiki](https://oi-wiki.org/intro/htc/) 。
```suggestion
    本页面将着重介绍 Git 这一版本控制系统，与 GitHub 相关的内容，请参考 [GitHub 帮助](https://docs.github.com/cn) 和 [如何参与 - OI Wiki](../intro/htc.md) 。
```
建议煲汤（

2020-09-12 16:02 UTC, StudyingFather commented
> 还有一点就是，命令为啥每条加个 `$`，除了没法复制，它到底有啥作用啊 /fad 没搜到，盲猜一波以前没高亮没 Markdown 的时候用来标识的。

命令前加 $ 可以将输入的命令和命令运行的结果区别开来 :thinking:

2020-09-12 16:04 UTC, StudyingFather commented on docs/tools/git.md
> +    本页面将着重介绍 Git 这一版本控制系统，与 GitHub 相关的内容，请参考 [GitHub 帮助](https://docs.github.com/cn) 和 [如何参与 - OI Wiki](https://oi-wiki.org/intro/htc/) 。
我谢罪 /wq

2020-09-12 16:35 UTC, StudyingFather commented on docs/tools/git.md
> +利用 `git branch` 命令可以创建分支，`git checkout` 命令可以切换分支。
学多.webp

2020-09-13 04:11 UTC, StudyingFather commented
Checklist：

- Git 基本操作（wiki 编辑者需要掌握的内容）
  - [x] 创建新仓库
  - [x] 从已有仓库克隆
  - [x] 跟踪文件
  - [x] 提交更改
  - [x] 分支的创建与切换
  - [x] 分支的合并
  - [x] 解决合并冲突
  - [ ] 远程仓库的管理
- Git 进阶操作
  - [ ] 其他合并分支的方式（squash，rebase）
  - [ ] git reset 命令
- 其他工作
  - [ ] 添加 htc 等页面指向 git 页面的内部链接
  - [ ] 修正格式问题

2020-09-13 16:09 UTC, NachtgeistW commented
> > 还有一点就是，命令为啥每条加个 `$`，除了没法复制，它到底有啥作用啊 /fad 没搜到，盲猜一波以前没高亮没 Markdown 的时候用来标识的。
> 
> 命令前加 $ 可以将输入的命令和命令运行的结果区别开来 🤔

这个算是约定俗成的习惯，例如 git 的官方文档：
![image](https://user-images.githubusercontent.com/35161925/93022962-74f6bb00-f61e-11ea-9220-80a6900799ee.png)
没有修改的必要。

2020-09-13 16:11 UTC, NachtgeistW commented
> 另外可以给个 https://learngitbranching.js.org/ 的 link /fad
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/d24d8ca719a8258c817b6a65cc8564d8b8fca8da/68747470733a2f2f70636f74746c652e6769746875622e696f2f6c6561726e4769744272616e6368696e672f6173736574732f6c6561726e4769744272616e6368696e672e706e67">**[Learn Git Branching](https://pcottle.github.io/learnGitBranching/index.html?demo)**An interactive Git visualization tool to educate and challenge!

我推荐把 git 的官方文档作为外部链接一起加上。
[Git - Reference](https://git-scm.com/docs)

2020-09-13 16:14 UTC, NachtgeistW commented
> Checklist：
> 
> * Git 基本操作（wiki 编辑者需要掌握的内容）
>   
>   * [x]  创建新仓库
>   * [x]  从已有仓库克隆
>   * [x]  跟踪文件
>   * [x]  提交更改
>   * [x]  分支的创建与切换
>   * [x]  分支的合并
>   * [x]  解决合并冲突
>   * [ ]  远程仓库的管理
> * Git 进阶操作
>   
>   * [ ]  其他合并分支的方式（squash，rebase）
>   * [ ]  git reset 命令
> * 其他工作
>   
>   * [ ]  添加 htc 等页面指向 git 页面的内部链接
>   * [ ]  修正格式问题

分支的删除可以在创建切换那里一起提一下？

2020-09-16 04:22 UTC, Xeonacid commented on docs/tools/git.md
> +对于 Mac 系统，只需在终端执行 `brew install git` 命令即可安装。
修改被覆盖了（

2020-09-16 07:01 UTC, NachtgeistW commented on docs/tools/git.md
> +对于 Mac 系统，只需在终端执行 `brew install git` 命令即可安装。
重新开这个的 review 吧

2020-09-16 13:51 UTC, Xeonacid commented on docs/tools/git.md
> +对于 Mac 系统，只需在终端执行 `brew install git` 命令即可安装。
我选择直接改（）

2020-09-19 12:06 UTC, ouuan commented on docs/tools/git.md
> +[^note1]: `git log` 的更多用法可以参考 [Pro Git Book v2](https://git-scm.com/book/zh/v2/Git-%E5%9F%BA%E7%A1%80-%E6%9F%A5%E7%9C%8B%E6%8F%90%E4%BA%A4%E5%8E%86%E5%8F%B2)。
不要随便 resolve 啊（

2020-09-20 09:39 UTC, Xeonacid commented on docs/intro/htc.md
> +4. 将这些更改推送（push）到你克隆的仓库。
```suggestion
4. 将这些更改推送（push）到你克隆的仓库；
5. 提交 Pull Request 至主仓库。
```

2020-09-22 11:38 UTC, StudyingFather commented on docs/tools/git.md
> +另外，commit 过程中可以利用几个参数来简化提交过程：
这个命令是啥 🤔，没在文档里找到 /fad

2020-09-22 11:41 UTC, StudyingFather commented
基础的内容写的差不多了，先 ready for review 吧。

进阶内容之后慢慢写吧（

2020-09-22 13:31 UTC, Enter-tainer approved these changes

2020-09-22 13:40 UTC, Xeonacid commented on docs/intro/htc.md
> +详细的操作方式可以参考 [Git - OI Wiki](../tools/git.md) 页面。
```suggestion
详细的操作方式可以参考 [Git](../tools/git.md) 页面。
```

2020-09-22 13:40 UTC, Xeonacid commented on docs/tools/git.md
> +点击 Next >，选择安装路径。
```suggestion
点击 `Next >`，选择安装路径。
```
下同

2020-09-22 13:40 UTC, Xeonacid commented on docs/tools/git.md
> +[^note2]: 但是，Git for Windows 对 Vim 的描述是“虽然强大，但是可能会难以使用。用户界面反人类，键位映射卡手。Git 使用 Vim 作为默认编辑器只是出于历史原因，强烈推荐换用一个 UI 设计现代化的编辑器。”，并给“难以使用”加上了 [“StackOverflow 每年帮助一百万名开发者退出 Vim”的页面链接](https://stackoverflow.blo
```suggestion
[^note2]: 但是，Git for Windows 对 Vim 的描述是“虽然强大，但是可能会难以使用。用户界面反人类，键位映射卡手。Git 使用 Vim 作为默认编辑器只是出于历史原因，强烈推荐换用一个 UI 设计现代化的编辑器。”，并给“难以使用”加上了 [Stack Overflow 每年帮助一百万名开发者退出 Vim](https://stackoverflow.blog/2017/05/23/stack-overflow-helping-one-million-developers-exit-vim/)的页面链接。
```

2020-09-23 07:31 UTC, Enter-tainer submitted a review, later dismissed

2020-09-23 07:36 UTC, Enter-tainer submitted a review, later dismissed

2020-09-25 09:59 UTC, ouuan commented on docs/tools/git.md
> +另外，commit 过程中可以利用几个参数来简化提交过程：
> 这个命令是啥 🤔，没在文档里找到 /fad

添加所有未被忽略的文件，包括 untracked。你用的什么版本，为啥会找不到啊..

2020-09-25 10:46 UTC, Enter-tainer commented on docs/tools/git.md
> +另外，commit 过程中可以利用几个参数来简化提交过程：
```
❯ git add -h | grep A
    -A, --all             add changes from all tracked and untracked files
```

2020-09-25 13:07 UTC, Xeonacid approved these changes

2020-09-25 13:20 UTC, ouuan requested changes
先 request changes 再 review（

2020-09-25 13:22 UTC, ouuan commented on docs/tools/git.md
> +3. 当前仓库目录下的 `.git/config` 文件：只适用于该仓库。
unresolved

2020-09-25 13:23 UTC, ouuan commented on docs/tools/git.md
> +另外，commit 过程中可以利用几个参数来简化提交过程：
unresolved

2020-09-25 13:34 UTC, ouuan requested changes

2020-09-25 13:34 UTC, ouuan commented on docs/tools/git.md
> +  (use "git checkout -- <file>..." to discard changes in working directory)
```suggestion
  (use "git restore -- <file>..." to discard changes in working directory)
```

[2.28.0](https://github.com/OI-wiki/OI-wiki/pull/2627/files#diff-922cd4d7d078fb7f0b61a02c862b1346R11) 的话应该是 restore。

2020-09-25 13:34 UTC, ouuan commented on docs/tools/git.md
> +[master fe92c6b] merge branch readme-refactor into master
```suggestion
$ git commit -m "Merge branch readme-refactor into master"
[master fe92c6b] Merge branch readme-refactor into master
```

我是觉得不 `-m` 比较好..默认的 merge 标题应该就差不多长这样。

2020-09-25 13:34 UTC, ouuan commented on docs/tools/git.md
> +
`set-url` 和 `get-url` 也挺有用的，感觉加上比较好。

2020-09-25 13:34 UTC, ouuan commented on docs/tools/git.md
> +需要注意的是，你的更改能成功推送，需要满足两个条件：你拥有向这个仓库的写入权限，且之前没有人推送过。当远程分支有新更改而当前分支没有时，需要执行 `git pull` 命令完成合并再提交。
```suggestion
需要注意的是，你的更改能成功推送，需要满足两个条件：你拥有向这个仓库（分支）的写入权限，且你的这个分支比远程仓库的这个分支新（可以理解为没有人在你进行修改的这段时间进行了推送）。当远程分支有当前分支没有的新更改时，可以执行 `git pull` 命令完成合并再提交。
```

2020-09-25 13:39 UTC, ouuan commented
现在的远程仓库管理貌似就只有 master 分支？

至少要有：

- `git switch <remote branch name>`
- `git push -u origin <current branch>`

然后可以简单提一下 local branch track remote branch（pull push 不用加 `origin master`，切换时提醒与远程的差异之类的）。

2020-09-25 13:42 UTC, Enter-tainer commented on docs/tools/git.md
> +Git 是目前使用最广泛的版本控制系统。**OI Wiki** 也使用了 Git 作为版本控制系统。
???这个也要来源请求？

2020-09-25 13:42 UTC, Enter-tainer commented on docs/tools/git.md
> +Git 是目前使用最广泛的版本控制系统。**OI Wiki** 也使用了 Git 作为版本控制系统。
> The Eclipse Foundation reported in its annual community survey that as of May 2014, Git is now the most widely used source-code management tool, with 42.9% of professional software developers reporting that they use Git as their primary source-control system[82] compared with 36.3% in 2013, 32% in 2012; or for Git responses excluding use of GitHub: 33.3% in 2014, 30.3% in 2013, 27.6% in 2012 and 12.8% in 2011.[83] Open-source directory Black Duck Open Hub reports a similar uptake among open-source projects.[84]

https://en.wikipedia.org/wiki/Git

2020-09-25 15:20 UTC, NachtgeistW commented on docs/tools/git.md
> +[master fe92c6b] merge branch readme-refactor into master
> Commit message options 
> -m, --message <message>                   commit message
`-m` 就是一个普通的 commit 命令吧，为什么不要用🤔

2020-09-25 15:23 UTC, ouuan commented on docs/tools/git.md
> +[master fe92c6b] merge branch readme-refactor into master
> 为什么不要用🤔

> 默认的 merge 标题应该就差不多长这样。

2020-09-25 15:24 UTC, ouuan commented on docs/tools/git.md
> +[master fe92c6b] merge branch readme-refactor into master
就是说，你 `git commit`，文本编辑器里的内容差不多就是 "Merge branch readme-refactor into master"，不需要手动输入。

2020-09-26 10:50 UTC, StudyingFather commented on docs/tools/git.md
> +[master fe92c6b] merge branch readme-refactor into master
嗯，有点道理（

2020-09-26 10:55 UTC, StudyingFather commented on docs/tools/git.md
> +另外，commit 过程中可以利用几个参数来简化提交过程：
啊之前看成 `git commit -A` 了，我谢罪（捂脸

2020-09-26 11:36 UTC, ouuan commented on docs/tools/git.md
> +2. 对系统的当前用户，以及该系统上的所有仓库有效的配置文件。
```suggestion
2. 对系统的当前用户，以及该用户的所有仓库有效的配置文件。
```

不知道有没有更好的表达方式 :thinking: “该用户操作的所有仓库”？

2020-10-20 11:19 UTC, leoleoasd commented on docs/tools/git.md
> +点击 Next >，选择安装可选项。
19行的next有 ` `` ` 包裹, 这一行的没2333
是否需要统一?

2020-10-20 11:21 UTC, leoleoasd commented on docs/tools/git.md
> +点击 Next >，选择安装可选项。
下面的next好像也都没有

2020-12-19 03:20 UTC, PeterlitsZo commented
> > 还有一点就是，命令为啥每条加个 `$`，除了没法复制，它到底有啥作用啊 /fad 没搜到，盲猜一波以前没高亮没 Markdown 的时候用来标识的。
> 
> 命令前加 $ 可以将输入的命令和命令运行的结果区别开来 🤔

而且 Linux 默认的命令提示符就是 `$`，在 Linux 的绝大多数发行版中，就是以 `$` 开头的，就像：
``` text
$ git version
git version 2.28.0
```

2021-01-29 11:52 UTC, wujx7923 commented
> 还有一点就是，命令为啥每条加个 `$`，除了没法复制，它到底有啥作用啊 /fad 没搜到，盲猜一波以前没高亮没 Markdown 的时候用来标识的。

`$` 是普通用户的标志。相对地，`#`  为 root 用户的标志。
一个例子：
```bash
$ sudo emerge --ask --verbose app-editros/emacs
```
这是在普通用户(处于 wheel 组)时 Gentoo 安装 Emacs 的命令。
```bash
# emerge --ask --verbose app-editors/emacs
```
这一条是处于 root 用户时执行的。在 Linux 和 unix-like 系统上（如 macOS 、BSDs）这算是用户权限的标志吧。

2021-02-17 01:35 UTC, ksyx commented on docs/tools/git.md
> +执行 `git add <文件>` 命令可以将指定的文件纳入到版本跟踪中。
这个“文件”是否有需要说明是相对当前命令行路径

2021-02-17 01:35 UTC, ksyx commented on docs/tools/git.md
> +执行 `git remote remame <oldname> <newname>` 可以将名字为 `oldname` 的远程仓库改名为 `newname` 。
```suggestion
执行 `git remote rename <oldname> <newname>` 可以将名字为 `oldname` 的远程仓库改名为 `newname` 。
```

另外这里可能要说明一下不选 oldname 和 newname 时的行为

2021-02-17 13:46 UTC, StudyingFather commented on docs/tools/git.md
> +执行 `git add <文件>` 命令可以将指定的文件纳入到版本跟踪中。
个人认为没有太大必要 :thinking:，毕竟命令引用的路径，大都是相对当前的路径。

2021-03-12 09:45 UTC, Early0v0 commented on docs/tools/git.md
> +$ git clone https://github.com/OI-wiki/OI-wiki
要不要加个 ssh 的链接？

2021-03-12 09:45 UTC, Early0v0 commented on docs/tools/git.md
> +执行 `git add <文件>` 命令可以将指定的文件纳入到版本跟踪中。
要不要提及一下 `git add .`？

2021-03-12 10:21 UTC, CoelacanthusHex commented on docs/tools/git.md
> +$ git clone https://github.com/OI-wiki/OI-wiki
我觉得是比较有必要的，GitHub 把用户名+密码的连接方式干掉了，现在只能用户名+Personal Token或者 SSH，其中 SSH 相对简单和方便些

2021-05-29 15:43 UTC, StudyingFather commented on docs/tools/git.md
> +执行 `git add <文件>` 命令可以将指定的文件纳入到版本跟踪中。
> 要不要提及一下 `git add .`？

有 `git add -A` 了（

2021-06-13 18:08 UTC, StudyingFather commented
`git reset` 命令和 ssh 连接先 🕊️ 了:new_moon_with_face:

剩下的部分已经根据各位 reviewer 的建议进行了修改。欢迎各位继续 review。

2021-06-14 08:36 UTC, Enter-tainer approved these changes
辛苦了

2021-06-14 08:45 UTC, Xeonacid commented on docs/tools/git.md
> +在下拉菜单栏中，Git 提供了 nano、 [Vim](editor/vim.md) 、 [Notepad++](editor/npp.md) 、 [Visual Studio Code](editor/vscode.md) 、Visual Studio Code Insider（VSCode 预览版）、Sublime Text、 [Atom](editor/atom.md) 和 VSCodiu
```suggestion
在下拉菜单栏中，Git 提供了 nano、 [Vim](editor/vim.md) 、 [Notepad++](editor/npp.md) 、 [Visual Studio Code](editor/vscode.md) 、Visual Studio Code Insider（VS Code 预览版）、Sublime Text、 [Atom](editor/atom.md) 和 VSCodium 作为默认编辑器的预设方案。如果系统已经安装了上述的一种或多种编辑器，可以直接选择其中一种并进入下一步。另外，还可通过 `Select other editor as Git's default editor` 项手动指定默认编辑器。
```

2021-06-14 08:52 UTC, Xeonacid submitted a review, later dismissed
thx

2021-06-14 08:53 UTC, Enter-tainer approved these changes

2021-06-14 08:58 UTC, Enter-tainer submitted a review, later dismissed

2021-06-14 10:19 UTC, ksyx commented on docs/tools/git.md
> +修改配置文件需要用到 `git config` 命令。
```suggestion
修改配置文件需要用到 `git config` 命令，加上 `--global` 开关后则写入适用于当前用户的全局设置。
```

2021-06-14 10:19 UTC, ksyx commented on docs/tools/git.md
> +这样在当前文件夹下，就会新建一个名为 `OI-wiki` 的仓库，里面存放着被克隆的仓库的内容。
```suggestion
这样，被克隆的仓库的内容就会被储存到当前文件夹下一个与仓库同名的新文件夹。在本例中，当前文件夹下会出现一个名为 `OI-wiki` 的新文件夹。
```

2021-06-14 10:19 UTC, ksyx commented on docs/tools/git.md
> +但在进行这一工作之前，先对 `README.md` 做点小修改。
```suggestion
但在进行这一工作之前，让我们先对 `README.md` 做点小修改。
```

表示不是必须的？

2021-06-14 10:19 UTC, ksyx commented on docs/tools/git.md
> +- `-m`：该参数后跟提交信息，表示以该提交信息提交本次更改。
```suggestion
- `-m`：该参数后跟提交信息，表示以该提交信息提交本次更改。例如 `git commit -m "fix: typo` 会创建一条标题为 `fix: typo` 的 commit。
```

2021-06-14 10:19 UTC, ksyx commented on docs/tools/git.md
> +如果在两个分支中，对同一个文件的同一部分进行了不同的修改，Git 就无法自动合并这两个分支，也就是发生了合并冲突。
```suggestion
如果在两个分支中，对同一个文件的同一行号进行了不同的修改，Git 就无法自动合并这两个分支，也就是发生了合并冲突。
```

2021-06-14 10:19 UTC, ksyx commented on docs/tools/git.md
> +使用 Rebase 完成合并可以让 commit 历史线性化。但是这样做的缺点也很明显：Rebase 会改变已有的 commit 历史，在多人协作时会有出现冲突或丢失更改的风险。
风险例如？

2021-06-14 10:20 UTC, Enter-tainer commented on docs/tools/git.md
> +使用 Rebase 完成合并可以让 commit 历史线性化。但是这样做的缺点也很明显：Rebase 会改变已有的 commit 历史，在多人协作时会有出现冲突或丢失更改的风险。
应该是指不要rebase在远程的分支？

2021-06-14 10:21 UTC, ksyx commented on docs/tools/git.md
> +使用 Rebase 完成合并可以让 commit 历史线性化。但是这样做的缺点也很明显：Rebase 会改变已有的 commit 历史，在多人协作时会有出现冲突或丢失更改的风险。
那也不对啊 🤔 
但是 rebase 确实是对你本地修改有风险倒是

2021-06-14 10:22 UTC, Enter-tainer commented on docs/tools/git.md
> +使用 Rebase 完成合并可以让 commit 历史线性化。但是这样做的缺点也很明显：Rebase 会改变已有的 commit 历史，在多人协作时会有出现冲突或丢失更改的风险。
![image](https://user-images.githubusercontent.com/25521218/121877696-78e67380-cd3d-11eb-954c-ca60ed9910cb.png)

2021-06-14 10:22 UTC, Enter-tainer commented on docs/tools/git.md
> +如果在两个分支中，对同一个文件的同一部分进行了不同的修改，Git 就无法自动合并这两个分支，也就是发生了合并冲突。
这个是行号吗 🤔 ，我觉得还是改成部分吧？

2021-06-14 10:22 UTC, Enter-tainer commented on docs/tools/git.md
> +如果在两个分支中，对同一个文件的同一部分进行了不同的修改，Git 就无法自动合并这两个分支，也就是发生了合并冲突。
和diff的算法相关，我感觉

2021-06-14 11:26 UTC, ouuan commented on docs/tools/git.md
> +使用 Rebase 完成合并可以让 commit 历史线性化。但是这样做的缺点也很明显：Rebase 会改变已有的 commit 历史，在多人协作时会有出现冲突或丢失更改的风险。
> ![image](https://user-images.githubusercontent.com/25521218/121877696-78e67380-cd3d-11eb-954c-ca60ed9910cb.png)

这个“如果提交存在于你的仓库之外”的“提交”指代不明，TA 想表达的应该是“被 rebase 改变的 commits”。

2021-06-14 15:46 UTC, StudyingFather commented on docs/tools/git.md
> +修改配置文件需要用到 `git config` 命令。
其实这个在下一节已经提及过了（

2021-06-15 01:58 UTC, ksyx commented on docs/tools/git.md
> +使用 Rebase 完成合并可以让 commit 历史线性化。但是这样做的缺点也很明显：Rebase 会改变已有的 commit 历史，在多人协作时会有出现冲突或丢失更改的风险。
> > ![image](https://user-images.githubusercontent.com/25521218/121877696-78e67380-cd3d-11eb-954c-ca60ed9910cb.png)
> 
> 这个“如果提交存在于你的仓库之外”的“提交”指代不明，TA 想表达的应该是“被 rebase 改变的 commits”。

@ouuan  倒是 get 到了（

2021-06-15 02:05 UTC, ksyx reviewed
> 其实这个在下一节已经提及过了（
我紫菜（ @StudyingFather

2021-06-15 02:05 UTC, ksyx commented on docs/tools/git.md
> +    - `Associate .sh files to be run with Bash`：将所有扩展名为 `.sh` 的文件与 Git 命令行关联，并用其执行。
```suggestion
    - `Associate .sh files to be run with Bash`：将所有扩展名为 `.sh` 的文件与 Git Bash 关联，并用其执行。
```

2021-06-17 07:32 UTC, Enter-tainer approved these changes

2021-06-17 12:30 UTC, Marcythm submitted a review, later dismissed

2021-06-18 05:09 UTC, livrth approved these changes

2021-06-18 05:45 UTC, ouuan requested changes
1.  suggestions
2.  https://github.com/OI-wiki/OI-wiki/pull/2627/files#r593063943
3.  感觉可以统一一下 diff 的用词，以及统一一下 modify 的用词，用“修改”还是“更改”。

2021-06-18 05:45 UTC, ouuan commented on docs/tools/git.md
> +
```suggestion

    如果只需更新已被纳入版本跟踪的文件，而不将未纳入版本跟踪的文件加入暂存区，可以使用 `git add -u`。

```

2021-06-18 05:45 UTC, ouuan commented on docs/tools/git.md
> +你会发现 `README.md` 同时处于暂存区和非暂存区。如果这时候执行 `git commit` 命令，只有处于暂存区的更改会被提交，而非暂存区的修改，则不会被提交。
```suggestion
你会发现 `README.md` 同时处于暂存区和非暂存区。实际上，是否处于暂存区是对于更改而言的，而不是对于文件而言的，所以对 `README.md` 的前一次修改已被纳入暂存区，而后一次修改还没有。如果这时候执行 `git commit` 命令，只有处于暂存区的更改会被提交，而非暂存区的更改，则不会被提交。
```

2021-06-18 05:45 UTC, ouuan commented on docs/tools/git.md
> +使用 Rebase 完成合并可以让 commit 历史线性化。但是这样做的缺点也很明显：Rebase 会改变已有的 commit 历史，在多人协作时会有出现冲突或丢失更改的风险。
```suggestion
使用 Rebase 完成合并可以让 commit 历史线性化，在适当的场景下正确地使用 Rebase 可以达到比 Merge 更好的效果。但是这样做会改变提交历史，在进行 Rebase 时和 Rebase 后再进行相关合并操作时都会增加出现冲突的可能，如果操作不当可能反而会使提交历史变得杂乱。因此，如果对 Rebase 操作没有充分的了解，不建议使用。
```

2021-06-18 05:45 UTC, ouuan commented on docs/tools/git.md
> +在远程仓库中，其他人可能会推送一些更改，执行 `git fetch` 命令可以将这些更改拉取到本地。
```suggestion
在远程仓库中，其他人可能会推送一些更改，执行 `git fetch` 命令可以将这些更改获取到本地。
```

“拉取”感觉就很 pull :thinking:

2021-06-18 05:45 UTC, ouuan commented on docs/tools/git.md
> +需要注意的是，`git fetch` 命令只会拉取远程仓库的信息，而不会将这些信息合并到本地仓库中。如果需要将这些更改进行合并，需要使用 `git pull` 命令。
```suggestion
需要注意的是，`git fetch` 命令只会获取远程仓库的更改，而不会将这些更改合并到本地仓库中。如果需要将这些更改进行合并，可以使用 `git pull` 命令。在默认情况下，`git pull` 相当于 `git fetch` 后 `git merge FETCH_HEAD`。
```

2021-06-18 05:45 UTC, ouuan commented on docs/tools/git.md
> +
`push -f` 和 `push --force-with-lease` :thinking:

2021-06-18 05:48 UTC, ouuan commented on docs/tools/git.md
> +$ git fetch <remote-name> # 拉取 <remote-name> 的数据
```suggestion
$ git fetch <remote-name> # 获取 <remote-name> 的更改
```

2021-06-18 05:50 UTC, ouuan commented on docs/tools/git.md
> +$ git pull <remote-name> <branch> # 抓取 <remote-name> 的数据并自动和本地的 <branch> 分支合并
```suggestion
$ git pull <remote-name> <branch> # 获取 <remote-name> 的更改，然后将这些更改合并到 HEAD。
```

2021-06-18 05:50 UTC, ouuan commented on docs/tools/git.md
> +$ git push <remote-name> <branch> # 将 <branch> 分支的数据推送至 <remote-name>
```suggestion
$ git push <remote-name> <branch> # 将 <branch> 分支的更改推送至 <remote-name> 的 <branch> 分支
```

2021-06-18 05:56 UTC, ouuan commented on docs/tools/git.md
> +`======` 作为分界线将两个分支的内容隔开，`<<<<<< HEAD` 标记和 `======` 之间的部分是 `master` 分支的内容，而 `======` 和 `>>>>>> readme-refactor` 标记之间的部分是 `readme-refactor` 分支的内容。
```suggestion
`======` 作为分界线将两个分支的内容隔开，`<<<<<< HEAD` 标记和 `======` 之间的部分是 HEAD 指针（`master` 分支）的内容，而 `======` 和 `>>>>>> readme-refactor` 标记之间的部分是 `readme-refactor` 分支的内容。
```

2021-06-18 05:57 UTC, ouuan commented on docs/tools/git.md
> +删除这些冲突解决标记，保存文件，将这些文件纳入暂存区后提交，就可以解决合并冲突了。
```suggestion
解决冲突，删除这些冲突标记，保存文件，将这些文件纳入暂存区后提交，就可以解决合并冲突了。
```

2021-06-18 06:01 UTC, ouuan commented on docs/tools/git.md
> +使用 Squash 方式合并可以简化 commit 记录，但是会丢失一些原分支上的 commit 信息（包括原分支上每次 commit 的提交者，每次 commit 的具体更改等等）。
```suggestion
使用 Squash 方式合并可以简化 commit 记录，但是会丢失具体到每一次 commit 的信息（每次 commit 的提交者，每次 commit 的更改等等），只留下合并为一个整体的信息（每次 commit 的提交者会以 "Co-authored-by" 的形式在提交信息中列出）。

但如果是在 GitHub 上进行 Squash and Merge，原有的信息都可以在 Pull Request 中查看。
```

2021-06-18 06:07 UTC, ouuan commented on docs/tools/git.md
> +接下来执行 `git switch <remote-name>/<remote-branch>` 切换到你想切换的远程分支。该操作会在本地自动创建名字为 `<remote-branch>` 的新分支，并设定该分支自动追踪相应的远程分支。
```suggestion
接下来执行 `git switch <remote-branch>`，会在本地自动创建名字为 `<remote-branch>` 的新分支，并设定该分支自动追踪相应的远程分支。
```

不能 switch 到远程分支吧，有测试过吗

2021-06-18 15:33 UTC, StudyingFather commented on docs/tools/git.md
> +接下来执行 `git switch <remote-name>/<remote-branch>` 切换到你想切换的远程分支。该操作会在本地自动创建名字为 `<remote-branch>` 的新分支，并设定该分支自动追踪相应的远程分支。
看起来并不 work，可能晚上写这这段的时候有点犯困 :sleeping:

2021-06-18 17:17 UTC, ouuan commented
https://zhidao.baidu.com/question/22913964.html :thinking:

2021-06-20 04:26 UTC, ouuan commented on docs/tools/git.md
> +如果你需要强制将本地分支的更改推送到远程仓库的话，可以加入 `-f` 参数。此时**远程仓库的提交历史会被本地的提交历史覆盖**，因此该命令应谨慎使用。
```suggestion
如果你需要强制将本地分支的更改推送到远程仓库的话，可以加入 `-f` 参数。此时**远程仓库的提交历史会被本地的提交历史覆盖**，因此该命令应谨慎使用。更好的选择是使用 `--force-with-lease` 参数，该参数仅在远程仓库没有更新时才会进行覆盖。需要注意的是，此处“更新”是相对于上一次 fetch 而言的，如果使用了 VS Code 提供的 Auto Fetch 功能，可能会没有注意到更新而使 `--force-with-lease` 和 `-f` 一样危险。
```

2021-06-20 04:28 UTC, ouuan commented on docs/tools/git.md
> +在使用 ssh 连接到远程仓库之前，需要先在本地添加 ssh 密钥。具体操作方式可以参考 [missing semester 上的教程](https://missing-semester-cn.github.io/2020/command-line/#%E8%BF%9C%E7%AB%AF%E8%AE%BE%E5%A4%87)，这里不再展开。
我觉得这篇教程有大量连接 GitHub 所不需要了解的内容，建议还是自己写一下，可以参考 [我的 hexo 指北](https://ouuan.github.io/post/hexo%E5%8D%9A%E5%AE%A2%E6%90%AD%E5%BB%BA%E6%8C%87%E5%8C%97/#%E5%B0%86%E5%8D%9A%E5%AE%A2%E4%B8%8A%E4%BC%A0%E8%87%B3-github)，但也别直接 link 过去。

2021-06-20 04:30 UTC, ouuan commented on docs/tools/git.md
> +在使用 ssh 连接到远程仓库之前，需要先在本地添加 ssh 密钥。具体操作方式可以参考 [missing semester 上的教程](https://missing-semester-cn.github.io/2020/command-line/#%E8%BF%9C%E7%AB%AF%E8%AE%BE%E5%A4%87)，这里不再展开。
刚刚没看清，没看到下面两行..所以你 link 这个教程就是本地添加啊..那你自己写可能比“具体操作方式可以参考，这里不再展开”字数还少一些 🌚

2021-06-20 04:33 UTC, ouuan commented on docs/tools/git.md
> +在使用 ssh 连接到远程仓库之前，需要先在本地添加 ssh 密钥。具体操作方式可以参考 [missing semester 上的教程](https://missing-semester-cn.github.io/2020/command-line/#%E8%BF%9C%E7%AB%AF%E8%AE%BE%E5%A4%87)，这里不再展开。
```suggestion
在使用 ssh 连接到远程仓库之前，需要先在本地添加 ssh 密钥。具体来说，需要在命令行运行 `ssh-keygen` ，如果不想每次输入密码的话，不需要输入内容，连按三次回车即可。
```

2021-06-20 04:37 UTC, ouuan commented on docs/tools/git.md
> +接下来需要将本地添加的 ssh 密钥的**公钥**上传到远程仓库。以 GitHub 为例，用户需要在个人设置里点击 **SSH and GPG keys**，随后点击 **New SSH key** 来添加 ssh 密钥。
```suggestion
接下来需要将本地添加的 ssh 密钥的**公钥**上传到远程仓库。公钥可以在用户目录（Windows 上即 `C:\Users\电脑用户名`）下的 `.ssh/id_rsa.pub` 查看。

以 GitHub 为例，用户需要在 [SSH and GPG keys 设置](https://github.com/settings/keys) 中点击 **New SSH key** 来添加 ssh 密钥。
```

2021-06-20 06:22 UTC, CoelacanthusHex commented on docs/tools/git.md
> +在使用 ssh 连接到远程仓库之前，需要先在本地添加 ssh 密钥。具体操作方式可以参考 [missing semester 上的教程](https://missing-semester-cn.github.io/2020/command-line/#%E8%BF%9C%E7%AB%AF%E8%AE%BE%E5%A4%87)，这里不再展开。
> 我觉得这篇教程有大量连接 GitHub 所不需要了解的内容，建议还是自己写一下，可以参考 [我的 hexo 指北](https://ouuan.github.io/post/hexo%E5%8D%9A%E5%AE%A2%E6%90%AD%E5%BB%BA%E6%8C%87%E5%8C%97/#%E5%B0%86%E5%8D%9A%E5%AE%A2%E4%B8%8A%E4%BC%A0%E8%87%B3-github)，但也别直接 link 过去。

我认为直接链接 GitHub Doc 就好

2021-06-20 06:25 UTC, CoelacanthusHex commented on docs/tools/git.md
> +接下来需要将本地添加的 ssh 密钥的**公钥**上传到远程仓库。以 GitHub 为例，用户需要在个人设置里点击 **SSH and GPG keys**，随后点击 **New SSH key** 来添加 ssh 密钥。
根据 `ssh-keygen` 运行时填写的内容，可能并不是这个文件名

2021-06-20 11:53 UTC, StudyingFather commented on docs/tools/git.md
> +在使用 ssh 连接到远程仓库之前，需要先在本地添加 ssh 密钥。具体操作方式可以参考 [missing semester 上的教程](https://missing-semester-cn.github.io/2020/command-line/#%E8%BF%9C%E7%AB%AF%E8%AE%BE%E5%A4%87)，这里不再展开。
> > 我觉得这篇教程有大量连接 GitHub 所不需要了解的内容，建议还是自己写一下，可以参考 [我的 hexo 指北](https://ouuan.github.io/post/hexo%E5%8D%9A%E5%AE%A2%E6%90%AD%E5%BB%BA%E6%8C%87%E5%8C%97/#%E5%B0%86%E5%8D%9A%E5%AE%A2%E4%B8%8A%E4%BC%A0%E8%87%B3-github)，但也别直接 link 过去。
> 
> 我认为直接链接 GitHub Doc 就好

感觉还是扔个 GitHub Doc 的链接更好些。

1. 写这个页面的目的主要是给想给 OI Wiki 的各位 contributors 提供一个 guideline，让他们能用 Git 更高效的完成贡献。
2. 基于 1 的原因，他们使用的 Git 托管平台主要是 GitHub，所以扔 GitHub 的帮助会更合适些。
3. GitHub 帮助写的足够详细。

如果真的有人想对 ssh 的用法有更深入的了解的话，可以给个外部链接 :thinking:

2021-06-20 14:48 UTC, ouuan commented on docs/tools/git.md
> +在使用 ssh 连接到远程仓库之前，需要先在本地添加 ssh 密钥。具体操作方式可以参考 [missing semester 上的教程](https://missing-semester-cn.github.io/2020/command-line/#%E8%BF%9C%E7%AB%AF%E8%AE%BE%E5%A4%87)，这里不再展开。
> 感觉还是扔个 GitHub Doc 的链接更好些。
> 
>     1. 写这个页面的目的主要是给想给 OI Wiki 的各位 contributors 提供一个 guideline，让他们能用 Git 更高效的完成贡献。
> 
>     2. 基于 1 的原因，他们使用的 Git 托管平台主要是 GitHub，所以扔 GitHub 的帮助会更合适些。
> 
>     3. GitHub 帮助写的足够详细。
> 
> 
> 如果真的有人想对 ssh 的用法有更深入的了解的话，可以给个外部链接 thinking

你说的“更好”是相对什么？我觉得你给出的原因不能说明给 GitHub Doc 的链接比自己写更好。

2021-06-20 14:50 UTC, ouuan commented on docs/tools/git.md
> +在使用 ssh 连接到远程仓库之前，需要先在本地添加 ssh 密钥。具体操作方式可以参考 [missing semester 上的教程](https://missing-semester-cn.github.io/2020/command-line/#%E8%BF%9C%E7%AB%AF%E8%AE%BE%E5%A4%87)，这里不再展开。
我是觉得对于一般人来说 GitHub Doc 的内容也过多了，按我的 suggestion 基本上已经足够了。

2021-06-20 14:51 UTC, ouuan commented on docs/tools/git.md
> +在使用 ssh 连接到远程仓库之前，需要先在本地添加 ssh 密钥。具体操作方式可以参考 [missing semester 上的教程](https://missing-semester-cn.github.io/2020/command-line/#%E8%BF%9C%E7%AB%AF%E8%AE%BE%E5%A4%87)，这里不再展开。
而且我这直连上不了 GitHub Docs

2021-06-20 15:14 UTC, CoelacanthusHex commented on docs/tools/git.md
> +在使用 ssh 连接到远程仓库之前，需要先在本地添加 ssh 密钥。具体操作方式可以参考 [missing semester 上的教程](https://missing-semester-cn.github.io/2020/command-line/#%E8%BF%9C%E7%AB%AF%E8%AE%BE%E5%A4%87)，这里不再展开。
> 我是觉得对于一般人来说 GitHub Doc 的内容也过多了，按我的 suggestion 基本上已经足够了。

GitHub Doc 给的内容就是最基本的操作步骤，我不觉得有什么多余的东西

2021-06-20 15:17 UTC, CoelacanthusHex commented on docs/tools/git.md
> +在使用 ssh 连接到远程仓库之前，需要先在本地添加 ssh 密钥。具体操作方式可以参考 [missing semester 上的教程](https://missing-semester-cn.github.io/2020/command-line/#%E8%BF%9C%E7%AB%AF%E8%AE%BE%E5%A4%87)，这里不再展开。
> 而且我这直连上不了 GitHub Docs

事实上直连上不了 GitHub Doc 的 GitHub 的连接性也不怎么样，如何参与贡献呢（既然如 StudyingFather 所说本文主要目的是 contribute OI Wiki 的 guideline）

2021-06-20 15:21 UTC, ouuan commented on docs/tools/git.md
> +在使用 ssh 连接到远程仓库之前，需要先在本地添加 ssh 密钥。具体操作方式可以参考 [missing semester 上的教程](https://missing-semester-cn.github.io/2020/command-line/#%E8%BF%9C%E7%AB%AF%E8%AE%BE%E5%A4%87)，这里不再展开。
> 事实上直连上不了 GitHub Doc 的 GitHub 的连接性也不怎么样

我这就不是

2021-06-20 15:22 UTC, ouuan commented on docs/tools/git.md
> +在使用 ssh 连接到远程仓库之前，需要先在本地添加 ssh 密钥。具体操作方式可以参考 [missing semester 上的教程](https://missing-semester-cn.github.io/2020/command-line/#%E8%BF%9C%E7%AB%AF%E8%AE%BE%E5%A4%87)，这里不再展开。
> GitHub Doc 给的内容就是最基本的操作步骤，我不觉得有什么多余的东西

我觉得你的意思是“没有任何人都用不到的内容”，但我的意思是“有一个人很可能用不到的内容”。

2021-06-20 15:24 UTC, ouuan commented on docs/tools/git.md
> +在使用 ssh 连接到远程仓库之前，需要先在本地添加 ssh 密钥。具体操作方式可以参考 [missing semester 上的教程](https://missing-semester-cn.github.io/2020/command-line/#%E8%BF%9C%E7%AB%AF%E8%AE%BE%E5%A4%87)，这里不再展开。
那你觉得

> 在使用 ssh 连接到远程仓库之前，需要先在本地添加 ssh 密钥。具体来说，需要在命令行运行 `ssh-keygen` ，如果不想每次输入密码的话，不需要输入内容，连按三次回车即可。
>
> 接下来需要将本地添加的 ssh 密钥的**公钥**上传到远程仓库。公钥可以在用户目录（Windows 上即 `C:\Users\电脑用户名`）下的 `.ssh/id_rsa.pub` 查看。
>
> 以 GitHub 为例，用户需要在 [SSH and GPG keys 设置](https://github.com/settings/keys) 中点击 **New SSH key** 来添加 ssh 密钥。

这对于（不设置密码，不更改默认保存位置的）普通用户来说缺什么吗？

2021-06-21 07:09 UTC, CoelacanthusHex submitted a review, later dismissed

2021-06-21 08:45 UTC, Early0v0 commented on docs/tools/git.md
> +  ...
应该是英文吧（

```suggestion
$ git remote show origin
* remote origin
  Fetch URL: git@github.com:OI-wiki/OI-wiki.git
  Push  URL: git@github.com:OI-wiki/OI-wiki.git
  HEAD branch: master
  Remote branches:
    git             tracked
    master          tracked
  ...
```

2021-06-21 12:17 UTC, CoelacanthusHex approved these changes

2021-06-21 12:56 UTC, Enter-tainer approved these changes
辛苦了

2021-06-21 12:56 UTC, merged