补充crt内容
OI-wiki/OI-wiki pull request #2634
Opened 2020-09-06 17:01 UTC by zyj2297349886

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论你是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈你的感受
3. 如果你熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2020-09-16 12:19 UTC, Marcythm commented on docs/math/crt.md
> +例如，令 $p$ 是前一千个素数的乘积，通过计算我们得知 $p$ 的位数大概有 3000 位。
```suggestion
例如，令 $p$ 为前一千个素数的乘积，通过计算我们得知 $p$ 在十进制下大概有 3000 位。
```

2020-09-16 12:19 UTC, Marcythm commented on docs/math/crt.md
> +上述代码可以在 $O(k^2)$ 时间下计算出参数 $x_i$ 。计算出参数后 $a$ 就可以用前面提到的公式表示：
```suggestion
上述代码可以在 $O(k^2)$ 时间内计算出参数 $x_i$ 。计算出参数后 $a$ 就可以用前面提到的公式表示：
```

2020-09-16 12:19 UTC, Marcythm commented on docs/math/crt.md
>  某些计数问题或数论问题出于加长代码、增加难度、或者是一些其他不可告人的原因，给出的模数： **不是质数** ！
```suggestion
某些计数问题或数论问题出于加长代码、增加难度、或者是一些其他原因，给出的模数 **不是质数** 。
```

2020-09-16 12:20 UTC, Marcythm reviewed
为什么最后一行多了个 `$$`。。。

2020-09-16 12:20 UTC, Marcythm commented on docs/math/crt.md
> +$$
```suggestion

```

2020-09-16 14:00 UTC, Xeonacid commented on docs/math/crt.md
> +$$
> 行间公式前后各要有一行空行，否则会被当做是行内公式。

2020-09-16 14:00 UTC, Xeonacid commented on docs/math/crt.md
> +$$
因为被bot安排了

2020-09-16 14:47 UTC, zyj2297349886 commented on docs/math/crt.md
> +$$
确实，我看了下我这边改的时候是没问题的。那怎么解决？

2020-09-17 14:00 UTC, Xeonacid commented on docs/math/crt.md
> +G^{\\sum\_{k\\mid n}\\binom{n}{k} \\bmod 999~911~658} \\bmod 999~911~659
下面全都被转义了

2020-09-21 05:01 UTC, ksyx commented on docs/math/crt.md
> +x \\equiv a_1 \\pmod 2\\x \\equiv a_2 \\pmod 3\\x \\equiv a_3 \\pmod {4679}\\x \\equiv a_4 \\pmod {35617}
还是被转义了

2020-09-21 16:01 UTC, zyj2297349886 commented on docs/math/crt.md
> +x \\equiv a_1 \\pmod 2\\x \\equiv a_2 \\pmod 3\\x \\equiv a_3 \\pmod {4679}\\x \\equiv a_4 \\pmod {35617}
emmm我明明改过了啊

2020-10-06 01:58 UTC, sshwy requested changes

2020-10-06 01:58 UTC, sshwy commented on docs/math/crt.md
> +    a_2 - x_1 &\equiv& x_2 p_1 &\pmod{p_2} \\\\
少了一个begin array

2020-10-06 01:58 UTC, sshwy commented on docs/math/crt.md
> +
不用重复提公式表示（

2020-10-09 16:53 UTC, zyj-111 commented
更新啦

2020-10-10 13:01 UTC, sshwy reviewed
额 抱歉啊 是我没说清楚

2020-10-10 13:01 UTC, sshwy commented on docs/math/crt.md
> +$$
```suggestion
时间复杂度 $O(k^2)$。
```

2020-10-11 03:27 UTC, zyj-111 commented on docs/math/crt.md
> +$$
好的，更新啦

2020-10-12 03:32 UTC, Konano approved these changes

2020-10-13 10:51 UTC, sshwy requested changes

2020-10-13 10:51 UTC, sshwy commented on docs/math/crt.md
> +    ```
```suggestion
??? note "参考代码"
    ```cpp
    for (int i = 0; i < k; ++i) {
      x[i] = a[i];
      for (int j = 0; j < i; ++j) {
        x[i] = r[j][i] * (x[i] - x[j]);
        x[i] = x[i] % p[i];
        if (x[i] < 0){
            x[i] += p[i];
        }
    }
    ```
```

2020-10-13 15:35 UTC, Konano approved these changes

2020-10-15 03:06 UTC, sshwy commented on docs/math/crt.md
> +$$
x_3说完了，再说一下 x_k的表达式吧

2021-02-13 15:10 UTC, StudyingFather commented
比较两 CRT 下整数和 Garner 算法重复的部分不少，所以进行了合并。

2021-02-14 02:13 UTC, sshwy approved these changes
lgtm

2021-02-14 07:51 UTC, StudyingFather approved these changes

2021-02-14 07:51 UTC, merged