增加max-flow内容
OI-wiki/OI-wiki pull request #2658
Opened 2020-09-17 16:51 UTC by zyj2297349886

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论你是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈你的感受
3. 如果你熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2020-09-21 05:00 UTC, ksyx commented on docs/graph/flow/max-flow.md
> +同时我们令 $p_{in}(s) = p_{out}(t) = \infty$ 。
in out 等建议套 mathit
下同

2020-09-21 05:00 UTC, ksyx commented on docs/graph/flow/max-flow.md
> +$$
？

2020-09-21 16:00 UTC, zyj2297349886 commented on docs/graph/flow/max-flow.md
> +$$
啊这，，bot?

2020-09-21 16:00 UTC, zyj2297349886 commented on docs/graph/flow/max-flow.md
> +$$
已经更新

2020-09-22 03:11 UTC, Konano approved these changes

2020-09-27 17:21 UTC, zyj2297349886 commented
差一个approve啦

2020-10-06 00:30 UTC, sshwy requested changes
别 mathit 了
渲染不出来的
https://deploy-preview-2658--oi-wiki.netlify.app/graph/flow/max-flow/#mpm
吧 mathit 删了吧（

2020-10-20 15:13 UTC, closed without merging