补充combination内容
OI-wiki/OI-wiki pull request #2660
Opened 2020-09-18 15:53 UTC by zyj2297349886

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论你是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈你的感受
3. 如果你熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2020-09-21 04:58 UTC, ksyx reviewed
可能需要指明参考资料
vector 为了码风统一可以在函数外面当作全局变量

2020-09-21 04:58 UTC, ksyx commented on docs/math/combination.md
> +给定一个元素从 $1$ 到 $N$ 连续变化的集合，以及一个小于 $N$ 的自然数 $K$ ，要求枚举所有大小为 $K$ 的子集。
元素从 1 到 n 连续变化可能需要改进表述

2020-09-23 23:47 UTC, ksyx reviewed
![image](https://user-images.githubusercontent.com/18738953/94085264-2a551a00-fe3a-11ea-899b-b7e4ea5acb1b.png)
原文这里有一块好像没出来

2020-09-23 23:47 UTC, ksyx commented on docs/math/combination.md
> + **本页面主要译自博文 [Тернарный поиск](http://e-maxx.ru/algo/ternary_search) 与其英文翻译版 [Ternary Search](https://cp-algorithms.com/num_methods/ternary_search.html) 。其中俄文版版权协议为 Public Domain + Leave a Link；英文版版权
Ternary Search

2020-09-27 17:21 UTC, zyj2297349886 commented
已更新

2020-09-28 07:44 UTC, Konano submitted a review, later dismissed

2020-10-06 02:14 UTC, sshwy requested changes

2020-10-06 02:14 UTC, sshwy commented on docs/math/combination.md
> +给定一个元素是从 $1$ 到 $n$ 连续变化的整数集合，以及一个小于 $n$ 的自然数 $k$ ，要求枚举所有大小为 $k$ 的子集。
连续变化是什么

2020-10-06 02:14 UTC, sshwy commented on docs/math/combination.md
> +很显然，第一个组合是 ${1, 2, ..., K}$ 。然后找到该组合里最右边并且小于 $N$ 的数。一旦找到这个数，我们就让它自增，并用类似的方法来处理前面的数。
```suggestion
很显然，第一个组合是 $\{1, 2, ..., K\}$ 。然后找到该组合里最右边并且小于 $N$ 的数。一旦找到这个数，我们就让它自增，并用类似的方法来处理前面的数。
```

2020-10-06 02:14 UTC, sshwy commented on docs/math/combination.md
> + **本页面主要译自博文 [Генерация сочетаний из N элементов Сочетания из N элементов по K в лексикографическом порядке](http://e-maxx.ru/algo/generating_combinations) 与其英文翻译版 [generating_combinations](https://c
```suggestion
 **本页面小部分内容译自博文 [Генерация сочетаний из N элементов Сочетания из N элементов по K в лексикографическом порядке](http://e-maxx.ru/algo/generating_combinations) 与其英文翻译版 [generating_combinations](https://cp-algorithms.com/combinatorics/generating_combinations.html) 。其中俄文版版权协议为 Public Domain + Leave a Link；英文版版权协议为 CC-BY-SA 4.0。** 
```

2020-10-10 13:06 UTC, sshwy commented on docs/math/combination.md
> +给定一个包含从 $1$ 到 $n$ 的整数集合，以及一个小于 $n$ 的自然数 $k$ ，要求枚举所有大小为 $k$ 的子集。
```suggestion
给出 $n,k$，要求枚举 $\{1,2,\ldots,n\}$ 的所有大小为 $k$ 的子集。
```

2020-10-10 13:06 UTC, sshwy commented on docs/math/combination.md
> +很显然，第一个组合是 $\{1, 2, ..., K\}$ 。然后找到该组合里最右边并且小于 $N$ 的数。一旦找到这个数，我们就让它自增，并用类似的方法来处理前面的数。
啊 这段话说得很迷惑 建议来个志愿者写一个人能看懂的ver

2020-12-07 04:52 UTC, Konano approved these changes

2021-12-20 13:52 UTC, StudyingFather commented
stale pr, closed.

2021-12-20 13:52 UTC, closed without merging