补充shortest-path内容
OI-wiki/OI-wiki pull request #2672
Opened 2020-09-21 16:42 UTC by zyj2297349886

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论你是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈你的感受
3. 如果你熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2020-09-22 14:19 UTC, ksyx commented on docs/graph/shortest-path.md
> +在大部分的情况下 D´Esopo-Pape 算法比 Dijkstra 算法和 Bellman-Ford 算法要快一些。和 Johnson 算法一样，该算法可以在负权图里工作，但图中不可以有负环。该算法可以计算出所有点到起始点的最短路。
```suggestion
在大部分的情况下 D´Esopo-Pape 算法比 Dijkstra 算法和 Bellman-Ford 算法要快一些。和 Johnson 算法一样，该算法适用于无负环的父权图。该算法可以计算出起始点到所有点的最短路。
```

2020-09-22 14:19 UTC, ksyx commented on docs/graph/shortest-path.md
> + **本页面主要译自博文 [Тернарный поиск](http://e-maxx.ru/algo/ternary_search) 与其英文翻译版 [Ternary Search](https://cp-algorithms.com/num_methods/ternary_search.html) 。其中俄文版版权协议为 Public Domain + Leave a Link；英文版版权
ternary search

2020-09-23 04:34 UTC, Early0v0 commented on docs/graph/shortest-path.md
> +在大部分的情况下 D´Esopo-Pape 算法比 Dijkstra 算法和 Bellman-Ford 算法要快一些。和 Johnson 算法一样，该算法可以在负权图里工作，但图中不可以有负环。该算法可以计算出所有点到起始点的最短路。
是「负权」（

2020-09-23 07:23 UTC, ksyx commented on docs/graph/shortest-path.md
> +在大部分的情况下 D´Esopo-Pape 算法比 Dijkstra 算法和 Bellman-Ford 算法要快一些。和 Johnson 算法一样，该算法可以在负权图里工作，但图中不可以有负环。该算法可以计算出所有点到起始点的最短路。
sry(

2020-09-27 17:20 UTC, zyj2297349886 commented on docs/graph/shortest-path.md
> + **本页面主要译自博文 [Тернарный поиск](http://e-maxx.ru/algo/ternary_search) 与其英文翻译版 [Ternary Search](https://cp-algorithms.com/num_methods/ternary_search.html) 。其中俄文版版权协议为 Public Domain + Leave a Link；英文版版权
更新啦

2020-10-05 02:02 UTC, sshwy requested changes

2020-10-05 02:02 UTC, sshwy commented on docs/graph/shortest-path.md
> +- 如果 $v$ 属于 $M_0$ ，并且 $d_v$ 可以被改进到 $d_v > d_u + w$ ，那么我们就更新 $d_v$ ，并将 $v$ 插入到集合 $M_1$ 的头。
```suggestion
- 如果 $v$ 属于 $M_0$ ，并且 $d_v$ 可以被改进到 $d_v > d_u + w$ ，那么我们就更新 $d_v$ ，并将 $v$ 插入到 $M_1$ 的队首。
```

2020-10-05 02:02 UTC, sshwy commented on docs/graph/shortest-path.md
> +- 如果 $v$ 属于 $M_2$ ，将 $v$ 插入集合 $M_1$ ， $d_v=d_u + w$ 。
```suggestion
- 如果 $v$ 属于 $M_2$ ，将 $v$ 插入 $M_1$ 队尾， $d_v=d_u + w$ 。
```

2020-10-05 09:20 UTC, zyj-111 commented
new

2020-10-06 01:48 UTC, sshwy requested changes

2020-10-06 01:48 UTC, sshwy commented on docs/graph/shortest-path.md
> +在大部分的情况下 D´Esopo-Pape 算法比 Dijkstra 算法和 Bellman-Ford 算法要快一些。和 Johnson 算法一样，该算法适用于无负环的负权图。该算法可以计算出起始点到所有点的最短路。
```suggestion
在大部分的情况下 D´Esopo-Pape 算法比 Dijkstra 算法和 Bellman-Ford 算法要快一些。和 Johnson 算法一样，该算法适用于无负环的负权图。该算法用于计算单源最短路。
```

2020-10-06 01:48 UTC, sshwy commented on docs/graph/shortest-path.md
> +使用一个数组 $d$ 存储所有的最短路，比如 $d_i$ 就代表 $v_0$ 到点 $i$ 的最短路径。数组除了 $d_{v_0} = 0$ 以外，初始值都为无穷大。
```suggestion
设 $d_i$ 表示起点 $s$ 到点 $i$ 的最短路长度。初始时 $d_s = 0$，其他都设为无穷大。
```

2020-10-06 01:48 UTC, sshwy commented on docs/graph/shortest-path.md
> +再使用一个数组 $p$ 存放当前节点的前一个节点，比如 $p_i$ 就是点 $i$ 在最短路径上的祖先。
```suggestion
设 $p_i$ 表示点 $i$ 在最短路树上的父亲。
```

2020-10-06 01:48 UTC, sshwy commented on docs/graph/shortest-path.md
> +每一步都将涉及三个点：
```suggestion
维护三个点集：
```

2020-10-06 01:48 UTC, sshwy commented on docs/graph/shortest-path.md
> +每一步都将从 $M_1$ 中取一个点 $u$ ，然后将点 $u$ 存入 $M_0$ 。然后我们遍历所有从这个顶点出来的边。设另一端是点 $v$ ，权值为 $w$ 。
```suggestion
每次我们从 $M_1$ 中取一个点 $u$ ，然后将点 $u$ 存入 $M_0$ 。然后我们遍历从 $u$ 出发的所有边，设边的另一端点是 $v$ ，权值为 $w$ ：
```

2020-10-06 01:48 UTC, sshwy commented on docs/graph/shortest-path.md
> +- 如果 $v$ 属于 $M_2$ ，将 $v$ 插入 $M_1$ 队尾， $d_v=d_u + w$ 。
```suggestion
- 如果 $v \in M_2$ ，将 $v$ 插入 $M_1$ 队尾， 并更新 $d_v$：$d_v\gets d_u + w$ 。
```

2020-10-06 01:48 UTC, sshwy commented on docs/graph/shortest-path.md
> +- 如果 $v$ 属于 $M_1$ ，那我们就更新 $d_v$ ： $d_v = \min(d_v, d_u + w)$ 。
```suggestion
- 如果 $v \in M_1$ ，那我们就更新 $d_v$ ： $d_v \gets \min(d_v, d_u + w)$ 。
```

2020-10-06 01:48 UTC, sshwy commented on docs/graph/shortest-path.md
> +- 如果 $v$ 属于 $M_0$ ，并且 $d_v$ 可以被改进到 $d_v > d_u + w$ ，那么我们就更新 $d_v$ ，并将 $v$ 插入到 $M_1$ 的队首。
```suggestion
- 如果 $v \in M_0$ ，并且 $d_v$ 可以被更新到 $d_v > d_u + w$ ，那么我们就更新 $d_v$ ，并将 $v$ 插入到 $M_1$ 的队首。
```

2020-10-06 01:48 UTC, sshwy commented on docs/graph/shortest-path.md
> +
格式不太对
加一下缩进

2020-10-10 13:11 UTC, sshwy commented on docs/graph/shortest-path.md
> +    ```cpp desopo_pape
```suggestion
    ```cpp
```

2020-10-11 07:52 UTC, sshwy approved these changes
辛苦

2020-10-12 03:17 UTC, Enter-tainer approved these changes
thx

2020-10-12 03:17 UTC, merged