增加dp内容
OI-wiki/OI-wiki pull request #2677
Opened 2020-09-24 16:54 UTC by zyj2297349886

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论你是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈你的感受
3. 如果你熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2020-09-26 03:40 UTC, Konano submitted a review, later dismissed

2020-09-26 07:59 UTC, partychicken approved these changes

2020-09-26 10:40 UTC, StudyingFather requested changes
相关内容可以并入四边形不等式优化页面（本质都是利用决策单调性进行优化）。

另外 build 挂了（

2020-09-29 16:04 UTC, zyj-111 commented
已更

2020-09-30 06:35 UTC, Konano submitted a review, later dismissed

2020-10-06 00:33 UTC, sshwy commented
@StudyingFather

2020-10-06 00:54 UTC, sshwy commented on docs/dp/opt/quadrangle.md
> +这也就是所谓的 **单调条件** 。
单词条件是什么啊
如果没有含义的解释或者在文章说明过程中的应用，就不要引入这个概念

2020-10-12 03:30 UTC, Konano approved these changes

2020-10-13 10:44 UTC, StudyingFather approved these changes

2020-10-13 10:44 UTC, merged