修改 hash.md 中 Hash 函数定义前后不一致的问题
OI-wiki/OI-wiki pull request #2689
Opened 2020-09-29 05:10 UTC by 1292224662

1、字符串 Hash 函数有两种定义，二者在计算子串哈希值时的式子是不一样的，但原文中在第一部分介绍时介绍的是一种定义，却在代码实现和子串哈希时使用了另一种，容易对初学者造成误导。因此修改了第一部分的定义使之与下文一致，并增加了强调这两种 Hash 方法区别的内容。

2、增加了对子串哈希计算式子的说明。

2020-09-29 06:24 UTC, partychicken commented on docs/string/hash.md
> +对比观察上述两个式子，我们发现 $f(s[l..r])=f_r(s)-f_{l-1}(s) \times b^{r-l+1}$ 成立（可以手动代入验证一下），因此我们用这个式子就可以快速得到子串的哈希值。其中 $b^{r-l+1}$ 可以预处理出来（当然也可以快速幂）。
这个除法需要求逆元吧。。。
其实感觉一般都不会除，而是把另一边乘上来比较？

2020-09-29 06:29 UTC, 1292224662 commented on docs/string/hash.md
> +对比观察上述两个式子，我们发现 $f(s[l..r])=f_r(s)-f_{l-1}(s) \times b^{r-l+1}$ 成立（可以手动代入验证一下），因此我们用这个式子就可以快速得到子串的哈希值。其中 $b^{r-l+1}$ 可以预处理出来（当然也可以快速幂）。
这里并没有除法呀，就是用82行那样的式子就算就可以了，就是原页面最后一题参考代码里get()函数那样

2020-09-29 14:02 UTC, Early0v0 commented on docs/string/hash.md
>  这样的话，就可以在 $O(n)$ 的预处理后每次 $O(1)$ 地计算子串的哈希值了。
如果用快速幂的话是 $\mathcal O(\log p)$ 的，最好给个提示（

比如 `CF504E` 就必须预处理次幂，否则我会 T 大概 1000ms

2020-09-30 06:37 UTC, Konano approved these changes

2020-10-09 18:06 UTC, 1292224662 commented on docs/string/hash.md
>  这样的话，就可以在 $O(n)$ 的预处理后每次 $O(1)$ 地计算子串的哈希值了。
okk，修改了一下（但似乎顺便把之前的审核重置了）

2020-10-12 03:23 UTC, Konano submitted a review, later dismissed

2020-10-13 10:59 UTC, sshwy requested changes

2020-10-13 10:59 UTC, sshwy commented on docs/string/hash.md
> +现在，我们想要用类似前缀和的方式快速求出 $f(s[l..r])$ ，按照定义有字符串 $s[l..r]$ 的哈希值为 $f(s[l..r])=s[l]*b^{r-l}+s[l+1]*b^{r-l-1}+...+s[r-1]*b+s[r]$
改为 \cdot 或者 \times

2020-10-13 13:25 UTC, 1292224662 commented on docs/string/hash.md
> +现在，我们想要用类似前缀和的方式快速求出 $f(s[l..r])$ ，按照定义有字符串 $s[l..r]$ 的哈希值为 $f(s[l..r])=s[l]*b^{r-l}+s[l+1]*b^{r-l-1}+...+s[r-1]*b+s[r]$
已修改

2020-10-13 15:49 UTC, Konano approved these changes

2020-10-14 04:28 UTC, Early0v0 approved these changes

2020-10-20 06:39 UTC, 1292224662 commented
顶一顶，我现在还需要做什么嘛，还是等着就行了

2020-10-20 06:40 UTC, Enter-tainer commented
@sshwy ping

2020-10-20 07:35 UTC, sshwy approved these changes

2020-10-20 07:36 UTC, merged