style[basic]: 算法基础
OI-wiki/OI-wiki pull request #2692
Opened 2020-09-30 09:46 UTC by NachtgeistW

对算法基础分类的下属页面进行小型语法修正。
完结撒花*★,°*:.☆(￣▽￣)/$:*.°★* 。

2020-09-30 18:26 UTC, Konano reviewed
为什么括号内要统一成「（英语：小写）」的形式？
我个人觉得说「（大写英语）」会好一点，毕竟都是专业词汇

2020-09-30 18:27 UTC, Konano submitted a review, later dismissed

2020-10-01 12:03 UTC, Xeonacid requested changes

2020-10-01 12:03 UTC, Xeonacid commented on docs/basic/sort-intro.md
> +与时间复杂度类似，空间复杂度用来描述算法空间消耗的规模。一般来说，空间复杂度越小，算法越好。
这里如果要放的话应该只放对排序算法的空间复杂度的介绍，对于空间复杂度的定义介绍应该放到上面那个复杂度页面去
（上面那个时间复杂度可能也要挪一部分）

2020-10-02 15:47 UTC, NachtgeistW commented
> 为什么括号内要统一成「（英语：小写）」的形式？
> 我个人觉得说「（大写英语）」会好一点，毕竟都是专业词汇

唔……维基百科里也是乱七八糟的，有每个单词首字母都用大写的，有只大写第一个词的，有全都小写的。我也不知道用哪种好。

2020-10-02 15:52 UTC, NachtgeistW commented on docs/basic/sort-intro.md
> +与时间复杂度类似，空间复杂度用来描述算法空间消耗的规模。一般来说，空间复杂度越小，算法越好。
开个 suggestion 改一下吧，我有点不知道该怎么改了🤔

2020-10-03 06:45 UTC, Konano commented
> > 为什么括号内要统一成「（英语：小写）」的形式？
> > 我个人觉得说「（大写英语）」会好一点，毕竟都是专业词汇
> 
> 唔……维基百科里也是乱七八糟的，有每个单词首字母都用大写的，有只大写第一个词的，有全都小写的。我也不知道用哪种好。

我觉得还是保持原状比较好，个人意见

2020-10-03 06:46 UTC, Konano commented
大概就是除非特别有必要的修改，否则还是维持原状。况且大部分词条都是「（大写英语）」的格式。

2020-10-03 14:07 UTC, Xeonacid commented on docs/basic/sort-intro.md
> +与时间复杂度类似，空间复杂度用来描述算法空间消耗的规模。一般来说，空间复杂度越小，算法越好。
我觉得不用加这段，空间复杂度基本都O(n)的吧

2020-10-06 03:56 UTC, sshwy commented on docs/basic/divide-and-conquer.md
> +// 我就是要写递归，递归天下第一
？？？

2020-10-07 03:29 UTC, NachtgeistW commented on docs/basic/divide-and-conquer.md
> +// 我就是要写递归，递归天下第一
> ？？？

不要再问啦这个是说递归的缺点的原作者基本就这样写的

2020-10-07 03:29 UTC, NachtgeistW commented
> 大概就是除非特别有必要的修改，否则还是维持原状。况且大部分词条都是「（大写英语）」的格式。

嗯，我还是把它们都改成大写吧。其实主要都是为了看着格式一致

2020-10-07 03:32 UTC, NachtgeistW commented on docs/basic/bubble-sort.md
> +冒泡排序（英语：bubble sort）是一种简单的排序算法。由于在算法的执行过程中，较小的元素像是气泡般慢慢「浮」到数列的顶端，故叫做冒泡排序。
```suggestion
冒泡排序（英语：Bubble sort）是一种简单的排序算法。由于在算法的执行过程中，较小的元素像是气泡般慢慢「浮」到数列的顶端，故叫做冒泡排序。
```

2020-10-07 05:36 UTC, NachtgeistW commented on docs/basic/bucket-sort.md
> +桶排序（英文：bucket sort）是排序算法的一种，适用于待排序数据值域较大但分布比较均匀的情况。
```suggestion
桶排序（英文：Bucket sort）是排序算法的一种，适用于待排序数据值域较大但分布比较均匀的情况。
```

2020-10-07 05:36 UTC, NachtgeistW commented on docs/basic/counting-sort.md
> +计数排序（英语：counting sort）是一种线性时间的排序算法。
```suggestion
计数排序（英语：Counting sort）是一种线性时间的排序算法。
```

2020-10-07 05:36 UTC, NachtgeistW commented on docs/basic/divide-and-conquer.md
> +递归（英语：recursion），在数学和计算机科学中是指在函数的定义中使用函数自身的方法，在计算机科学中还额外指一种通过重复将问题分解为同类的子问题而解决问题的方法。
```suggestion
递归（英语：Recursion），在数学和计算机科学中是指在函数的定义中使用函数自身的方法，在计算机科学中还额外指一种通过重复将问题分解为同类的子问题而解决问题的方法。
```

2020-10-07 05:36 UTC, NachtgeistW commented on docs/basic/divide-and-conquer.md
> +分治（英语：conquer），字面上的解释是“分而治之”，就是把一个复杂的问题分成两个或更多的相同或相似的子问题，直到最后子问题可以简单的直接求解，原问题的解即子问题的解的合并。
```suggestion
分治（英语：Conquer），字面上的解释是“分而治之”，就是把一个复杂的问题分成两个或更多的相同或相似的子问题，直到最后子问题可以简单的直接求解，原问题的解即子问题的解的合并。
```

2020-10-07 05:36 UTC, NachtgeistW commented on docs/basic/enumerate.md
> +枚举（英语：enumerate）是基于已有知识来猜测答案的一种问题求解策略。
```suggestion
枚举（英语：Enumerate）是基于已有知识来猜测答案的一种问题求解策略。
```

2020-10-07 05:37 UTC, NachtgeistW commented on docs/basic/heap-sort.md
> +堆排序（英语：heapsort）是指利用 [堆](../ds/heap.md) 这种数据结构所设计的一种排序算法。堆排序的适用数据结构为数组。
```suggestion
堆排序（英语：Heapsort）是指利用 [堆](../ds/heap.md) 这种数据结构所设计的一种排序算法。堆排序的适用数据结构为数组。
```

2020-10-07 05:37 UTC, NachtgeistW commented on docs/basic/insertion-sort.md
> +插入排序（英语：insertion sort）是一种简单直观的排序算法。它的工作原理为将待排列元素划分为“已排序”和“未排序”两部分，每次从“未排序的”元素中选择一个插入到“已排序的”元素中的正确位置。
```suggestion
插入排序（英语：Insertion sort）是一种简单直观的排序算法。它的工作原理为将待排列元素划分为“已排序”和“未排序”两部分，每次从“未排序的”元素中选择一个插入到“已排序的”元素中的正确位置。
```

2020-10-07 05:37 UTC, NachtgeistW commented on docs/basic/quick-sort.md
> +快速排序（英语：quicksort），又称分区交换排序（英语：partition-exchange sort），简称快排，是一种被广泛运用的排序算法。
```suggestion
快速排序（英语：Quicksort），又称分区交换排序（英语：partition-exchange sort），简称快排，是一种被广泛运用的排序算法。
```

2020-10-07 05:38 UTC, NachtgeistW commented on docs/basic/radix-sort.md
> +基数排序（英语：radix sort）是一种非比较型的排序算法，最早用于解决卡片排序的问题。
```suggestion
基数排序（英语：Radix sort）是一种非比较型的排序算法，最早用于解决卡片排序的问题。
```

2020-10-07 05:38 UTC, NachtgeistW commented on docs/basic/selection-sort.md
> +选择排序（英语：selection sort）是排序算法的一种，它的工作原理是每次找出第 $i$ 小的元素（也就是 $A_{i..n}$ 中最小的元素），然后将这个元素与数组第 $i$ 个位置上的元素交换。
```suggestion
选择排序（英语：Selection sort）是排序算法的一种，它的工作原理是每次找出第 $i$ 小的元素（也就是 $A_{i..n}$ 中最小的元素），然后将这个元素与数组第 $i$ 个位置上的元素交换。
```

2020-10-07 05:38 UTC, NachtgeistW commented on docs/basic/shell-sort.md
> +希尔排序（英语：shell sort），也称为缩小增量排序法，是 [插入排序](insertion-sort.md) 的一种改进版本。希尔排序以它的发明者希尔（英语：Donald Shell）命名。
```suggestion
希尔排序（英语：Shell sort），也称为缩小增量排序法，是 [插入排序](insertion-sort.md) 的一种改进版本。希尔排序以它的发明者希尔（英语：Donald Shell）命名。
```

2020-10-07 05:38 UTC, NachtgeistW commented on docs/basic/sort-intro.md
> + **排序算法** （英语：sorting algorithm）是一种将一组特定的数据按某种顺序进行排列的算法。排序算法多种多样，性质也大多不同。
```suggestion
 **排序算法** （英语：Sorting algorithm）是一种将一组特定的数据按某种顺序进行排列的算法。排序算法多种多样，性质也大多不同。
```

2020-10-07 05:42 UTC, NachtgeistW commented on docs/basic/sort-intro.md
> +与时间复杂度类似，空间复杂度用来描述算法空间消耗的规模。一般来说，空间复杂度越小，算法越好。
（（（
![image](https://user-images.githubusercontent.com/35161925/95291811-dcf99380-08a2-11eb-9c01-b77f48955bb5.png)

2020-10-08 09:31 UTC, Konano commented
才发现三个 suggestions 可以变成一个 commit……我的锅（

2020-10-08 09:31 UTC, Konano approved these changes

2020-10-08 10:15 UTC, Xeonacid commented on docs/basic/sort-intro.md
> +与时间复杂度类似，空间复杂度用来描述算法空间消耗的规模。一般来说，空间复杂度越小，算法越好。
那不就是咯，算上原数组不就O(n)了（
除了计数排序/桶排序以外，其他排序没人会强调空间复杂度的吧

2020-10-08 10:16 UTC, Xeonacid commented on docs/basic/sort-intro.md
> +与时间复杂度类似，空间复杂度用来描述算法空间消耗的规模。一般来说，空间复杂度越小，算法越好。
留着可以，但是要按上面说的改一下 🤔

2020-10-09 12:55 UTC, Xeonacid requested changes
> 这里如果要放的话应该只放对排序算法的空间复杂度的介绍，对于空间复杂度的一般定义介绍应该放到上面那个复杂度页面去

见上

2020-10-19 09:01 UTC, Enter-tainer submitted a review, later dismissed

2020-10-19 09:04 UTC, Xeonacid approved these changes
先把这合了，之后我把时间和空间复杂度的往复杂度那页挪一下吧 🌚

2020-10-19 09:14 UTC, Xeonacid approved these changes

2020-10-19 16:59 UTC, Konano approved these changes

2020-10-19 17:00 UTC, merged