add Dev-C++下载地址
OI-wiki/OI-wiki pull request #2714
Opened 2020-10-08 05:34 UTC by bit00011011

fix #2713 

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论你是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈你的感受
3. 如果你熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2020-10-08 09:25 UTC, Konano requested changes
建议只保留官方源

2020-10-10 13:31 UTC, sshwy commented
童程童美是什么骚操作 震撼

2020-10-13 12:03 UTC, Ravenclaw-OIer requested changes
百度网盘和tctm的，鬼知道干不干净，就留个sourceforge的就好。

2020-10-13 13:07 UTC, bit00011011 commented
> 百度网盘和tctm的，鬼知道干不干净，就留个sourceforge的就好。

我试过，干净的（百度网盘是我发的

2020-10-13 13:13 UTC, ayalhw commented
> > 百度网盘和tctm的，鬼知道干不干净，就留个sourceforge的就好。
> 
> 我试过，干净的（百度网盘是我发的

So who trusts your inspection? How do you convince others of your inspection?Can you take full responsibility for your inspection?

2020-10-13 13:28 UTC, NachtgeistW commented
> > 百度网盘和tctm的，鬼知道干不干净，就留个sourceforge的就好。
> 
> 我试过，干净的（百度网盘是我发的

在官方提供下载链接的情况下应尽量提供官方链接，而非第三方下载源。官方承认的镜像站除外。
百度网盘不属于官方源也不属于镜像站；且由于众所周知的原因它并不是一个被广受认可的下载源。个人认为不应提供百度网盘下载链接。

2020-10-14 02:29 UTC, Ravenclaw-OIer commented
Please close this as #2730 does the work better.

2020-10-14 04:33 UTC, closed without merging