style[backtracking.md]: 回溯法
OI-wiki/OI-wiki pull request #2721
Opened 2020-10-11 02:35 UTC by NachtgeistW

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论你是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈你的感受
3. 如果你熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2020-10-12 03:29 UTC, Konano requested changes

2020-10-12 03:29 UTC, Konano commented on docs/search/backtracking.md
> +    ```
代码块分隔出错，建议修改后 Preview 一下

2020-10-13 01:13 UTC, NachtgeistW commented on docs/search/backtracking.md
> +    ```
fixed

2020-10-13 11:04 UTC, sshwy commented on docs/search/backtracking.md
> +    给定一个 N\*M 方格的迷宫，迷宫里有 T 处障碍，障碍处不可通过。给定起点坐标和终点坐标，问：每个方格最多经过 1 次，有多少种从起点坐标到终点坐标的方案。在迷宫中移动有上下左右四种方式，每次只能移动一个方格。数据保证起点上没有障碍。
既然都refactor了，就把该latex的部分给latex掉吧
其他地方同理

2020-10-14 03:08 UTC, NachtgeistW commented on docs/search/backtracking.md
> +    给定一个 N\*M 方格的迷宫，迷宫里有 T 处障碍，障碍处不可通过。给定起点坐标和终点坐标，问：每个方格最多经过 1 次，有多少种从起点坐标到终点坐标的方案。在迷宫中移动有上下左右四种方式，每次只能移动一个方格。数据保证起点上没有障碍。
Fixed.

2020-10-15 05:39 UTC, Konano submitted a review, later dismissed

2020-10-15 06:01 UTC, sshwy requested changes
其他同理

2020-10-15 06:01 UTC, sshwy commented on docs/search/backtracking.md
> +    上面的布局可以用序列 $2 4 6 1 3 5$ 来描述，第 $i$ 个数字表示在第 $i$ 行的相应位置有一个棋子，如下：
```suggestion
    上面的布局可以用序列 $\{2,4,6,1,3,5\}$ 来描述，第 $i$ 个数字表示在第 $i$ 行的相应位置有一个棋子，如下：
```

2020-10-16 00:48 UTC, NachtgeistW commented on docs/search/backtracking.md
> +    上面的布局可以用序列 $2 4 6 1 3 5$ 来描述，第 $i$ 个数字表示在第 $i$ 行的相应位置有一个棋子，如下：
Thx，还不是很会写LaTeX

2021-02-20 06:22 UTC, Konano approved these changes

2021-02-20 06:47 UTC, ksyx commented on docs/search/backtracking.md
> +    这只是跳棋放置的一个解。请遍一个程序找出所有跳棋放置的解。并把它们以上面的序列方法输出。解按字典顺序排列。请输出前 $3$ 个解。最后一行是解的总个数。特别注意：对于更大的 $N$ （棋盘大小 $N \times N$ ）你的程序应当改进得更有效。
```suggestion
    现在有一个如下的 $6 \times 6$ 的跳棋棋盘，有六个棋子被放置在棋盘上，使得每行，每列，每条对角线（包括两条主对角线的所有对角线）上都至多有一个棋子。
    
    ```plain
    0   1   2   3   4   5   6
      -------------------------
    1 |   | O |   |   |   |   |
      -------------------------
    2 |   |   |   | O |   |   |
      -------------------------
    3 |   |   |   |   |   | O |
      -------------------------
    4 | O |   |   |   |   |   |
      -------------------------
    5 |   |   | O |   |   |   |
      -------------------------
    6 |   |   |   |   | O |   |
      -------------------------
    ```
    
    上面的布局可以用序列 $\{2,4,6,1,3,5\}$ 来描述，第 $i$ 个数字表示在第 $i$ 行的第 $a_i$ 列有一个棋子，如下所示
    
    行号 $i$： $\{1,2,3,4,5,6\}$ 
    
    列号 $a_i$：$\{2,4,6,1,3,5\}$ 
    
    这只是跳棋放置的一个方案。请编一个程序找出所有方案并把它们以上面的序列化方法输出，按字典顺序排列。你只需输出前 $3$ 个解并在最后一行输出解的总个数。特别注意：你需要优化你的程序以保证在更大棋盘尺寸下的程序效率。
```

2021-02-20 06:47 UTC, ksyx commented on docs/search/backtracking.md
> +    给定一个 $N \times M$ 方格的迷宫，迷宫里有 $T$ 处障碍，障碍处不可通过。给定起点坐标和终点坐标，问：每个方格最多经过 $1$ 次，有多少种从起点坐标到终点坐标的方案。在迷宫中移动有上下左右四种方式，每次只能移动一个方格。数据保证起点上没有障碍。
```suggestion
    给定一个 $N \times M$ 方格的迷宫，迷宫里有 $T$ 处障碍，障碍处不可通过。给定起点坐标和终点坐标，且每个方格最多经过一次，问有多少种从起点坐标到终点坐标的方案。在迷宫中移动有上、下、左、右四种移动方式，每次只能移动一个方格。数据保证起点上没有障碍。
```

2021-02-20 06:51 UTC, ksyx approved these changes
thx

2021-02-23 01:54 UTC, Konano approved these changes

2021-02-23 11:06 UTC, sshwy approved these changes

2021-02-23 11:10 UTC, merged