fix #2724 为斜率优化式子增加细节
OI-wiki/OI-wiki pull request #2725
Opened 2020-10-12 13:40 UTC by expect2004

增加细节，使得更容易被理解

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论你是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈你的感受
3. 如果你熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2020-10-12 16:08 UTC, Konano requested changes

2020-10-12 16:08 UTC, Konano commented on docs/dp/opt/slope.md
> +将 $f_j$ 视作 $y$ ，将 $s_i$ 视作 $k$ ，将 $s_j + L'$ 视作 $x$ ，将 $- f_i + s_i^2 + (s_j+L')^2$ 视作 $b$
这句话单独出来感觉怪怪的，建议和下一行结合在一起：

形如 $b+k\times x=y$（将 xxx 视作 xxx，……）

2020-10-13 10:44 UTC, expect2004 commented on docs/dp/opt/slope.md
> +将 $f_j$ 视作 $y$ ，将 $s_i$ 视作 $k$ ，将 $s_j + L'$ 视作 $x$ ，将 $- f_i + s_i^2 + (s_j+L')^2$ 视作 $b$
az 我不太会用 GitHub，那应该怎么继续编辑啊

2020-10-13 10:45 UTC, expect2004 commented on docs/dp/opt/slope.md
> +将 $f_j$ 视作 $y$ ，将 $s_i$ 视作 $k$ ，将 $s_j + L'$ 视作 $x$ ，将 $- f_i + s_i^2 + (s_j+L')^2$ 视作 $b$
> 
> 
> 这句话单独出来感觉怪怪的，建议和下一行结合在一起：
> 
> 形如 $b+k\times x=y$（将 xxx 视作 xxx，……）

az 我不太会用 GitHub，那应该怎么继续编辑啊

2021-07-22 08:15 UTC, sshwy commented
目前的页面已大致包含本 pr 修改的内容，先 close 了
如有异议再 reopen

2021-07-22 08:15 UTC, closed without merging