Update quad-residue (Add Tonelli-Shanks algorithm).md
OI-wiki/OI-wiki pull request #2731
Opened 2020-10-13 16:39 UTC by TachikakaMin

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论你是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈你的感受
3. 如果你熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2020-10-15 05:49 UTC, Konano requested changes

2020-10-15 05:49 UTC, Konano commented on docs/math/quad-residue.md
> + [https://yutong.site/？p=1192](https://yutong.site/?p=1192)
方括号内的内容修改成网页标题

2020-10-15 06:41 UTC, TachikakaMin commented on docs/math/quad-residue.md
> + [https://yutong.site/？p=1192](https://yutong.site/?p=1192)
Done

2020-10-15 17:23 UTC, Konano submitted a review, later dismissed

2020-10-16 02:13 UTC, Xeonacid commented on docs/math/quad-residue.md
> +前提条件：p 为质数，a 是 p 的二次剩余
```suggestion
前提条件：$p$ 为质数，$a$ 是 $p$ 的二次剩余
```
下同

2020-10-16 02:13 UTC, Xeonacid commented on docs/math/quad-residue.md
> +## 证明
这个格式看起来有点乱emmmm

2020-12-12 05:15 UTC, Enter-tainer approved these changes
先合上吧要不

2020-12-30 14:36 UTC, StudyingFather commented
原来的格式实在有点混乱🌚

刚才稍微改了下，现在应该能看了（

2021-01-05 02:25 UTC, sshwy approved these changes
我看没啥问题了

2021-01-05 03:11 UTC, Enter-tainer approved these changes

2021-01-05 03:11 UTC, merged