add 二分和CDQ/Splay配合斜率优化
OI-wiki/OI-wiki pull request #2735
Opened 2020-10-14 13:03 UTC by GavinZhengOI

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论你是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈你的感受
3. 如果你熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2020-10-14 13:04 UTC, GavinZhengOI commented
可能有些小细节和格式问题需要帮助修改一下QAQ

2020-10-14 13:05 UTC, GavinZhengOI commented
#2592

2020-10-15 03:18 UTC, sshwy requested changes
把内容移到小结前面
“最基础的斜率优化模板题”是什么，请描述题面
请解释清楚符号定义
请别“显然” “众所周知”
如果链接的题目没有给出题面和讲解，这叫习题而不叫例题
“CDQ分治”之类的名词请链接到OI-wiki上对应的页面

2020-10-15 03:18 UTC, sshwy commented on docs/dp/opt/slope.md
> +3\. 加入状态 $dp_i$ 。如果一个状态（即凸包上的一个点）在 $dp_i$ 加入后不再是凸包上的点，需要在 $dp_i$ 加入前将其剔除。
```suggestion
在我们回忆一下最基础的斜率优化模板题的过程：

1. 将初始状态入队。
2. 每次使用一条和 $i$ 相关的直线 $f(i)$ 去切维护的凸包，找到最优决策，更新 $dp_i$ 。
3. 加入状态 $dp_i$ 。如果一个状态（即凸包上的一个点）在 $dp_i$ 加入后不再是凸包上的点，需要在 $dp_i$ 加入前将其剔除。
```

2020-10-19 03:26 UTC, Konano requested changes
习题需要放在文章的末尾

2020-10-19 03:26 UTC, Konano commented on docs/dp/opt/slope.md
> +例题： [\[NOI2007\]货币兑换](https://www.luogu.com.cn/problem/P4027)
```suggestion
例题： [「NOI2007」货币兑换](https://www.luogu.com.cn/problem/P4027) 
```

2020-10-19 03:26 UTC, Konano commented on docs/dp/opt/slope.md
> +例题： [Codeforces 1420E](https://codeforces.com/contest/1420/problem/E)
```suggestion
例题： [「Codeforces 1420E」Battle Lemmings](https://codeforces.com/contest/1420/problem/E) 
```

2020-10-20 16:34 UTC, Konano submitted a review, later dismissed

2021-01-27 11:49 UTC, Konano approved these changes

2021-01-27 11:54 UTC, sshwy commented
@Konano  啊 别急别急 等我完善一下例题（

2021-01-27 11:55 UTC, GavinZhengOI commented
> @Konano 啊 别急别急 等我完善一下例题（

老哥们交给你们了啊 我退役了 估计一年之内不会动算法竞赛了

2021-01-28 10:21 UTC, sshwy commented
嗯 我改好了 求 review

2021-02-06 01:21 UTC, Enter-tainer approved these changes

2021-02-06 01:26 UTC, sshwy approved these changes

2021-02-06 01:26 UTC, merged