费用流的SSP算法，原先把名字误作MCMF，这里修正
OI-wiki/OI-wiki pull request #2742
Opened 2020-10-17 02:00 UTC by s0cks5

SSP: Successive Shortest Path
MCMF: Min Cost Max Flow

2020-10-17 05:08 UTC, sshwy requested changes

2020-10-17 05:08 UTC, sshwy commented on docs/graph/flow/min-cost.md
```suggestion
## SSP 算法

SSP（Successive Shortest Path）算法：在最大流的 EK 算法求解最大流的基础上，把 **用 BFS 求解任意增广路** 改为 **用 SPFA 求解单位费用之和最小的增广路** 即可。

```

2020-10-18 03:49 UTC, Konano approved these changes

2020-10-23 04:47 UTC, sshwy approved these changes

2020-10-23 04:47 UTC, merged