docs: (fast-mul) 模 N 意义下的快速乘法
OI-wiki/OI-wiki pull request #2818
Opened 2020-11-27 07:08 UTC by PeterlitsZo

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论你是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈你的感受
3. 如果你熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2020-11-27 07:08 UTC, PeterlitsZo commented
相关的 issue 在 #2817

2020-11-27 13:24 UTC, Early0v0 requested changes
感谢！

但是这~~显然~~不是数论内容，建议改到专题（`/topic`）？

2020-11-27 13:24 UTC, Early0v0 commented on docs/math/fast-mul.md
> +模 N 快速乘法，可以用来解决在模 N 意义下乘法溢出的问题。
请把 N 用 LaTeX 表示。

2020-11-27 13:24 UTC, Early0v0 commented on docs/math/fast-mul.md
> +在有时候，我们需要将两个比较大的数相乘再取模（比如说，在 [rho 算法](./pollard-rho.md) 中，我们给定了一个比较大的数 $x$ ，需要计算 $x\times x\bmod b$ ，如果直接计算乘法时可能会发生溢出）。为了避免溢出的情况，需要引入在模 N 意义下进行快速乘法的算法。
同上。  
还有 $\bmod b$ 中的 $b$ 要不要换个字母（比如 $p$）？

2020-11-27 13:24 UTC, Early0v0 commented on docs/math/fast-mul.md
> +
建议给出复杂度：$O(\log x \log y)$。

2020-11-27 13:29 UTC, PeterlitsZo commented
ok, 今晚或者明天跟进

2020-11-28 14:58 UTC, StudyingFather requested changes
这部分内容和 [快速幂](https://oi-wiki.org/math/quick-pow/) 在思路和实现上都很相似，建议合并至快速幂页面。

2020-11-28 14:59 UTC, PeterlitsZo commented
好的，明天凌晨更新，快进到我室友必保研。

2020-11-28 16:25 UTC, PeterlitsZo commented
how about this version?

2020-11-28 16:32 UTC, StudyingFather commented
> how about this version?

啊非常抱歉，刚才 review 的时候没看到 quick-pow 下面已经有快速乘的相关内容了（见 [模意义下大整数乘法](https://deploy-preview-2818--oi-wiki.netlify.app/math/quick-pow/#_9)）/wq

您再把新的更改和那部分内容合并下吧 :smile:

2020-11-29 03:23 UTC, PeterlitsZo commented
不用合并了啦，都差不多wwww

话说，我感觉 tag 和 树形结构用来做笔记都有点难受，就没有基于图的吗 wwww
没事我就 cloas 了哦

2020-11-29 03:23 UTC, closed without merging