docs: (shortest-path) 增加最短路算法对应 C++ 代码
OI-wiki/OI-wiki pull request #2860
Opened 2020-12-31 13:09 UTC by PeterlitsZo

增加最短路算法对应的 C++ 代码

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论你是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈你的感受
3. 如果你熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2020-12-31 13:23 UTC, Enter-tainer requested changes

2020-12-31 13:23 UTC, Enter-tainer commented on docs/graph/shortest-path.md
> +  priority<Pair, vector<Pair>, greater<Pair>> Q;  // 小根堆
这个不太对吧，应该是 priority_queue?

有没有编译过这段代码

2021-01-01 08:45 UTC, PeterlitsZo commented on docs/graph/shortest-path.md
> +  priority<Pair, vector<Pair>, greater<Pair>> Q;  // 小根堆
是的！请等等 `>_<`

2021-01-23 16:13 UTC, CoelacanthusHex commented
?ping

2021-01-24 12:39 UTC, PeterlitsZo commented
done.

2021-01-26 15:07 UTC, Enter-tainer commented
hi~由于bot之前出了故障，导致误修改了这个pr里面的很多文件，因此目前这里有很多 conflict，没有办法合并。你可以 revert 一下 a927f49 这个 commit 吗

2021-01-28 04:31 UTC, PeterlitsZo commented
淦欸，patch-8 应该是好的，我想把 patch-8 merge 到 patch-6 去结果自动合并了。我要不然重新写一个 PR 吧

2021-01-28 04:33 UTC, closed without merging