增加算法：主元素问题
OI-wiki/OI-wiki pull request #2865
Opened 2021-01-03 07:29 UTC by SDLTF

增加主元素问题的三种算法（位于杂项中

2021-01-04 08:24 UTC, Early0v0 requested changes
Thx！

英文名建议改成 `main-element`。

请在 `mkdocs.yml` 中添加目录索引。

中英文间需要有空格。

2021-01-04 08:24 UTC, Early0v0 commented on docs/misc/mainelement
> +作者：``SDLTF``
```suggestion
author: SDLTF
```

2021-01-04 08:24 UTC, Early0v0 commented on docs/misc/mainelement
> +## 做法1：桶计数做法
```suggestion
## 做法

### 桶计数做法
```

2021-01-04 08:24 UTC, Early0v0 commented on docs/misc/mainelement
> +## 做法2：排序做法
```suggestion
### 排序做法
```

2021-01-04 08:24 UTC, Early0v0 commented on docs/misc/mainelement
> +显然，若一个数列存在主元素，那么这个主元素在排序后一定位于$\frac{n}{2}$的位置。
```suggestion
显然，若一个数列存在主元素，那么这个主元素在排序后一定位于$\frac{n}{2}$的位置。

```

2021-01-04 08:24 UTC, Early0v0 commented on docs/misc/mainelement
> +看起来不错！$O(N\log N)$的复杂度可还行？
```suggestion
看起来不错！$O(N\log N)$的复杂度可还行？

```

2021-01-04 08:24 UTC, Early0v0 commented on docs/misc/mainelement
> +## 做法3：主元素数列的特性
```suggestion
### 利用主元素数列的特性
```

2021-01-04 14:17 UTC, Early0v0 submitted a review, later dismissed

2021-01-05 08:42 UTC, Enter-tainer requested changes

2021-01-05 08:42 UTC, Enter-tainer commented on docs/misc/main-element.md
> +给一个有 $n$ 个元素的数列，保证有一个数$a$出现的次数**超过** $50\%$，求这个数。
```suggestion
给一个有 $n$ 个元素的数列，保证有一个数 $a$ 出现的次数**超过** $\dfrac n 2$，求这个数。
```

2021-01-05 08:42 UTC, Enter-tainer commented on docs/misc/main-element.md
> +时间复杂度$\mathcal O(N + M)$。
```suggestion
时间复杂度为 $O(n+m)$。
```

2021-01-05 08:42 UTC, Enter-tainer commented on docs/misc/main-element.md
> +时间复杂度$\mathcal O(N + M)$。
m 是什么？

2021-01-05 08:42 UTC, Enter-tainer commented on docs/misc/main-element.md
> +看起来不错！$\mathcal O(N\log N)$ 的复杂度可还行？
```suggestion
看起来不错！$O(n\log n)$ 的复杂度可还行？
```

2021-01-05 08:42 UTC, Enter-tainer commented on docs/misc/main-element.md
> +但是，一旦有 $\mathcal O(N\log N)$，就一定有人想得出 $\mathcal O(N)$ 的做法。
```suggestion
```

2021-01-05 08:42 UTC, Enter-tainer commented on docs/misc/main-element.md
> +有吗？还真的有 ——
```suggestion
下面介绍本问题的 $O(n)$ 解法。
```

2021-01-05 08:42 UTC, Enter-tainer commented on docs/misc/main-element.md
> +由于主元素的出现的次数超过 $50\%$，那么在不断的消掉两个不同的元素之后，最后一定剩下主元素。
```suggestion
由于主元素的出现的次数超过 $\dfrac n 2$，那么在不断的消掉两个不同的元素之后，最后一定剩下主元素。
```

2021-01-05 08:42 UTC, Enter-tainer commented on docs/misc/main-element.md
> +由于主元素的出现的次数超过 $50\%$，那么在不断的消掉两个不同的元素之后，最后一定剩下主元素。
这里的意思应该是两个相邻的不同元素？

2021-01-05 08:42 UTC, Enter-tainer commented on docs/misc/main-element.md
> +再进行优化后，空间复杂度也可以降至 $\mathcal O(1)$。
```suggestion
再进行优化后，空间复杂度也可以降至 $O(1)$。
```

2021-01-05 09:25 UTC, Early0v0 commented on docs/misc/main-element.md
> +时间复杂度$\mathcal O(N + M)$。
他应该指 m 是桶的大小

2021-01-05 09:27 UTC, Enter-tainer commented on docs/misc/main-element.md
> +for(int i = 0;i < 10001;i ++) {
这个 10001 有点草率了，建议写成 m 什么的，并在上面的文字里面标明值域

2021-01-05 09:32 UTC, Early0v0 approved these changes

2021-01-05 09:33 UTC, Enter-tainer approved these changes
辛苦了

2021-01-05 09:33 UTC, merged