[refine][z-func] 显著优化算法介绍的主体部分
OI-wiki/OI-wiki pull request #2867
Opened 2021-01-03 11:21 UTC by minghu6

z函数算法部分从冗长拗口难以理解的原文翻译，转成更简洁且更易懂的语言。

2021-01-04 05:02 UTC, sshwy requested changes
没学过z-func，没看懂

2021-01-04 05:02 UTC, sshwy commented on docs/string/z-func.md
> +最后记得当新的 $z[i]$ 匹配段的右边界超出了 $r$ ，计算得到 $z[i]$ 后需要更新 $l,\ r$ 为 $i,\ i+z[i]-1$ 。
复杂度证明的部分为啥被删掉了？
即使z-func算法复杂度证明显然，也应该在文末说一句「算法复杂度是...」才完整

2021-01-04 10:00 UTC, minghu6 commented on docs/string/z-func.md
> +其中 $z[i]$ 可以被认为是字符串 $s$ 的 $z$ 函数前缀即 $s[0\dots z[i]]$ 的右边界。
就是这个子串的右端点坐标：z[i] 是 s[0...z[i]]右边界

2021-01-04 10:01 UTC, minghu6 commented on docs/string/z-func.md
> +*这句话可以 Write once paste anywhere, 简称 WOPA*
字符串这部分其他会用到，只要能和自动机扯上关系的，都可以把这句话复制过去，请结合上下文

2021-01-04 10:03 UTC, minghu6 commented on docs/string/z-func.md
> +如同大多数字符串主题所介绍的算法，其关键在于，运用自动机的思想寻找限制条件下的状态转移函数，使得可以借助之前的状态来加速计算新的状态。
这不是z函数的定义，这是对一些列类似算法的抽象总结，z函数的定义不是在前面吗

2021-01-04 10:07 UTC, minghu6 commented on docs/string/z-func.md
> +我们把符合 $z$ 函数定义的那些子串的前缀称为 **匹配段**，其中我们关注的是最靠右的那一个匹配段，假定它为: $s[l\dots r]$ 。
？ 我在哪里说过‘z函数是个数组。子串不是数组’这种莫名其妙的话，我感觉如果不熟悉z函数的话还是看全文而不是changes好一点吧

2021-01-04 10:11 UTC, minghu6 commented on docs/string/z-func.md
> +最后记得当新的 $z[i]$ 匹配段的右边界超出了 $r$ ，计算得到 $z[i]$ 后需要更新 $l,\ r$ 为 $i,\ i+z[i]-1$ 。
这个请看修改后的完整文本，我只是把啰里啰嗦、抓不住重点的复杂度证明的部分用一句更简洁精确的描述代替了。

2021-01-05 04:43 UTC, sshwy requested changes
一个 Pull Request 应当只做一件事情
bm算法的格式调整不应当在 z-func 的 Pull Request 里实现
最好的方式是另起一个 Pull Request
我做为审核人员，首要确保的是修改后的页面是「能读懂的」，尤其是针对没有学过对应算法的人。不管这个页面之前是谁编辑的，我看的是修改后的整体效果。指出问题的目的不是推锅，而是希望帮忙修正一下。就目前来看，z-func我是没读懂的。（z-func我没学过

2021-01-05 04:43 UTC, sshwy commented on docs/string/z-func.md
> +*这句话可以 Write once paste anywhere, 简称 WOPA*
我是说 「*这句话可以 Write once paste anywhere, 简称 WOPA*」和zfunc没关系（

2021-01-05 04:43 UTC, sshwy commented on docs/string/z-func.md
> +我们把符合 $z$ 函数定义的那些子串的前缀称为 **匹配段**，其中我们关注的是最靠右的那一个匹配段，假定它为: $s[l\dots r]$ 。
「假设我们有一个长度为 $n$ 的字符串 $s$ 。该字符串的 **Z 函数** 为一个长度为 $n$ 的数组，其中第 $i$ 个元素为满足从位置 $i$ 开始且为 $s$ 前缀的字符串的最大长度。」

这是前文对Z函数的定义
我知道这个定义不是你写的，但是上文的Z函数的定义使得你的「匹配段」的定义是不严谨的
既然你在修订这个页面，麻烦你顺便改一下Z函数的定义，或者改一下匹配段的定义，使得上下文通顺

2021-01-05 04:46 UTC, sshwy commented on docs/string/z-func.md
> +如同大多数字符串主题所介绍的算法，其关键在于，运用自动机的思想寻找限制条件下的状态转移函数，使得可以借助之前的状态来加速计算新的状态。
即使这不是Z函数的定义，也应当解释「状态」的具体定义。
我说的「解释」不一定指阐述它的含义，其实也可以指出它的出处。
例如，如果在OI-Wiki的自动机页面对「状态」有完整的定义，你可以写 `[状态](页面链接)` 或者`（关于状态的定义详见[页面标题](链接)）`

2021-01-05 06:28 UTC, minghu6 commented on docs/string/z-func.md
> +*这句话可以 Write once paste anywhere, 简称 WOPA*
如果你同时看过比如前缀函数与kmp和自动机那一章节，就知道这句话是有意思的。

2021-01-05 06:36 UTC, minghu6 commented on docs/string/z-func.md
> +如同大多数字符串主题所介绍的算法，其关键在于，运用自动机的思想寻找限制条件下的状态转移函数，使得可以借助之前的状态来加速计算新的状态。
这里并不需要逐词进行解释吧，因为这不是一个正式的定义，只是为了帮助串联知识点，过度纠结这个恐怕是搞错了重点。
比如这里的状态就按照字面意义去理解也没什么影响。

2021-01-05 06:50 UTC, minghu6 commented on docs/string/z-func.md
> +我们把符合 $z$ 函数定义的那些子串的前缀称为 **匹配段**，其中我们关注的是最靠右的那一个匹配段，假定它为: $s[l\dots r]$ 。
“串S的z函数这个数组关联了一系列子串的前缀“ 这句话能理解吧

如果能的话，那么这些的子串的前缀就是匹配段。

2021-01-05 06:56 UTC, minghu6 commented
> 一个 Pull Request 应当只做一件事情
> bm算法的格式调整不应当在 z-func 的 Pull Request 里实现
> 最好的方式是另起一个 Pull Request
> 我做为审核人员，首要确保的是修改后的页面是「能读懂的」，尤其是针对没有学过对应算法的人。不管这个页面之前是谁编辑的，我看的是修改后的整体效果。指出问题的目的不是推锅，而是希望帮忙修正一下。就目前来看，z-func我是没读懂的。（z-func我没学过

为什么不试着读一下修改前的文本呢？ 易懂不易懂我以为是个相对概念。我修改的内容是确保比原文更加易懂。

2021-01-05 08:20 UTC, Enter-tainer commented on docs/string/z-func.md
> +*这句话可以 Write once paste anywhere, 简称 WOPA*
我建议这句话写成注释的形式，而不是以斜体的形式放进正文

2021-01-05 08:31 UTC, sshwy approved these changes

2021-01-05 08:32 UTC, Marcythm approved these changes
LGTM.
（对算法渐进时间复杂度的分析确实简明扼要了很多）

2021-01-05 08:33 UTC, Enter-tainer approved these changes
感谢！

2021-01-05 08:33 UTC, merged

2021-01-05 08:35 UTC, Enter-tainer commented
btw，需要开 pr 的时候，可以开一个新分支，在上面进行工作，并用这个分支来开 pr。这样可以同时开多个pr，并且不会干扰工作进度。

这样做也可以减少和上游进行同步麻烦。