为 vector 添加了 emplace_back 的描述
OI-wiki/OI-wiki pull request #2882
Opened 2021-01-13 06:43 UTC by MaoLongLong

`push_back()` 先构造临时对象，然后再拷贝（拷贝构造）到 vector 里。

`emplace_back()` 直接在末尾构造元素，相较 `push_back()` 省去了拷贝的过程，需要 C++11。

2021-01-13 07:23 UTC, Konano submitted a review, later dismissed

2021-01-14 04:43 UTC, Early0v0 requested changes
在 [cppreference 关于 emplace_back 的介绍](https://zh.cppreference.com/w/cpp/container/vector/emplace_back)中，明确给出 warning：
> 若新的 `size()` 大于 `capacity()`，则所有迭代器和引用（包含尾后迭代器）都被非法化。否则仅尾后迭代器被非法化。

请添加警告。

2021-01-14 05:35 UTC, MaoLongLong commented
感谢指出，看了文档之后发现增加和删除都存在这个警告，所以一起做了修改。

2021-01-14 13:17 UTC, Xeonacid approved these changes
thx

2021-01-14 13:57 UTC, Early0v0 commented on docs/lang/csl/sequence-container.md
> +    插入元素时，若新的 `size()` 大于 `capacity()` ，则所有迭代器和引用（包含尾后迭代器）都被非法化。否则仅尾后迭代器被非法化。
```suggestion
    使用 `emplace_back()` 插入元素时，若新的 `size()` 大于 `capacity()` ，则所有迭代器和引用（包含尾后迭代器）都被非法化。否则仅尾后迭代器被非法化。
```

删除元素的函数名称最好也写一下

2021-01-14 13:59 UTC, MaoLongLong commented on docs/lang/csl/sequence-container.md
> +    插入元素时，若新的 `size()` 大于 `capacity()` ，则所有迭代器和引用（包含尾后迭代器）都被非法化。否则仅尾后迭代器被非法化。
`insert()` , `emplace_back()` , `push_back()` 都存在这个问题，所以我就统一用 “插入元素” 来描述。

2021-01-14 14:03 UTC, Early0v0 commented on docs/lang/csl/sequence-container.md
> +    插入元素时，若新的 `size()` 大于 `capacity()` ，则所有迭代器和引用（包含尾后迭代器）都被非法化。否则仅尾后迭代器被非法化。
`push_back()` 会自动检查 `size()` 是否大于 `capacity()`，如果大于则整体移动。

所以您的意思可能是之前创造的 `iterator` 非法化？

2021-01-14 14:05 UTC, MaoLongLong commented on docs/lang/csl/sequence-container.md
> +    插入元素时，若新的 `size()` 大于 `capacity()` ，则所有迭代器和引用（包含尾后迭代器）都被非法化。否则仅尾后迭代器被非法化。
https://zh.cppreference.com/w/cpp/container/vector/insert

https://zh.cppreference.com/w/cpp/container/vector/push_back

文档是这么描述的，我也觉得整体移动是会造成非法化。

2021-01-14 14:07 UTC, MaoLongLong commented on docs/lang/csl/sequence-container.md
> +    插入元素时，若新的 `size()` 大于 `capacity()` ，则所有迭代器和引用（包含尾后迭代器）都被非法化。否则仅尾后迭代器被非法化。
对的，可能会导致之前创造的迭代器非法化。

2021-01-14 14:13 UTC, Early0v0 commented on docs/lang/csl/sequence-container.md
> +    插入元素时，若新的 `size()` 大于 `capacity()` ，则所有迭代器和引用（包含尾后迭代器）都被非法化。否则仅尾后迭代器被非法化。
可以看看 https://stackoverflow.com/a/28435599/14964823。

整体移动后的确会造成之前的 `iterator` 非法化。

2021-01-14 14:19 UTC, MaoLongLong commented on docs/lang/csl/sequence-container.md
> +    插入元素时，若新的 `size()` 大于 `capacity()` ，则所有迭代器和引用（包含尾后迭代器）都被非法化。否则仅尾后迭代器被非法化。
这段代码能解释一下我的想法

```cpp
#include <iostream>
#include <vector>
using namespace std;

int main() {
    vector<int> v = {1, 2};

    auto it = v.begin(); // old

    cout << v.capacity() << endl;
    v.push_back(3); // cap: 2 -> 4
    cout << v.capacity() << endl;

    v.insert(it, 0); // [0, 1, 2, 3]
    // v.insert(v.begin(), 0); // [536887160, 1, 2, 3]

    for (int i : v) {
        cout << i << ' ';
    }
    return 0;
}
```

2021-01-14 14:20 UTC, MaoLongLong commented on docs/lang/csl/sequence-container.md
> +    插入元素时，若新的 `size()` 大于 `capacity()` ，则所有迭代器和引用（包含尾后迭代器）都被非法化。否则仅尾后迭代器被非法化。
这段代码能解释一下我的想法

```cpp
#include <iostream>
#include <vector>
using namespace std;

int main() {
    vector<int> v = {1, 2};

    auto it = v.begin(); // old

    cout << v.capacity() << endl;
    v.push_back(3); // cap: 2 -> 4
    cout << v.capacity() << endl;

    v.insert(it, 0); // [536887160, 1, 2, 3]
    // v.insert(v.begin(), 0); // [0, 1, 2, 3]

    for (int i : v) {
        cout << i << ' ';
    }
    return 0;
}
```

2021-01-14 15:02 UTC, MaoLongLong commented on docs/lang/csl/sequence-container.md
> +    插入元素时，若新的 `size()` 大于 `capacity()` ，则所有迭代器和引用（包含尾后迭代器）都被非法化。否则仅尾后迭代器被非法化。
辛苦您了，我已经完成了修改

2021-01-15 04:14 UTC, Early0v0 commented on docs/lang/csl/sequence-container.md
> +-  `emplace_back()` 直接在末尾构造元素，相较 `push_back()` 省去了拷贝的过程，需要 C++11。
还是尽量使用 `push_back` 吧，不然有可能在 `vec.emplace_back(vec.front())` 时出错。

2021-01-15 07:14 UTC, closed without merging

2021-01-17 10:08 UTC, Xeonacid commented on docs/lang/csl/sequence-container.md
> +-  `emplace_back()` 直接在末尾构造元素，相较 `push_back()` 省去了拷贝的过程，需要 C++11。
在一定要（非拷贝/移动）构造的情况下用 `emplace_back` 完全没问题，并且是应当是更推荐的吧