关于对顶堆的讨论的修改
OI-wiki/OI-wiki pull request #2887
Opened 2021-01-16 11:41 UTC by ZJsonJun

关于对顶堆的讨论，原始页面有错误，主要错误在于对于小顶堆和大顶堆所存储元素的大小关系认识偏差。已帮忙修改。
应该是小顶堆存大值， 大顶堆存小值。这里要求第k大的话，应该是维护小顶堆的大小为k；
当插入元素时，如果元素比小顶堆的堆顶元素大，则插入小顶堆；否则插入大顶堆；之后再维护堆大小
查询第k大元素即是小顶堆堆顶元素

2021-01-17 07:01 UTC, ranwen requested changes
前面解释部分修改后意思很清楚，很好。

后头代码改错了。
具体为：新代码提交不能通过 https://www.luogu.com.cn/record/45069915
而原代码提交是可以通过的 https://www.luogu.com.cn/record/45069977

以及在 priority_queue 中，使用less比较的是大根堆，使用greater比较的是小根堆，注释也改错了。在本wiki"堆介绍"中有简单阐述。

2021-01-17 11:24 UTC, ZJsonJun commented
> 前面解释部分修改后意思很清楚，很好。
> 
> 后头代码改错了。
> 具体为：新代码提交不能通过 https://www.luogu.com.cn/record/45069915
> 而原代码提交是可以通过的 https://www.luogu.com.cn/record/45069977
> 
> 以及在 priority_queue 中，使用less比较的是大根堆，使用greater比较的是小根堆，注释也改错了。在本wiki"堆介绍"中有简单阐述。

哦哦，那应该是c++堆的实现不同吧，我是Java用户……

2021-01-17 12:06 UTC, ranwen approved these changes
thx

2021-01-20 09:45 UTC, Enter-tainer approved these changes

2021-01-20 09:45 UTC, merged