为斯特林数页面添加了内容
OI-wiki/OI-wiki pull request #2942
Opened 2021-01-30 04:28 UTC by FNatsuka

添加了第二类斯特林数通项公式及其推导。
添加了第一、二类斯特林数的行列求法。
添加了“多项式下降阶乘幂表示与多项式点值表示的关系”。
添加了两道习题。
稍微修改了文字表述。
将第二类斯特林数改置于第一类斯特林数之前。

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论你是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈你的感受
3. 如果你熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2021-01-30 05:47 UTC, sshwy commented on docs/math/stirling.md
> + **第二类斯特林数** （斯特林子集数） $\begin{Bmatrix}n\\ k\end{Bmatrix}$ 表示将 $n$ 个两两不同的元素，划分为 $k$ 个互不区分的非空子集的方案数。
额   不建议在标题里打括号，写英文术语，因为这会导致 toc 变得很冗长
建议吧「（斯特林子集数）」改成「，也称斯特林子集数（英文：Stirling Number of the Second Kind）」
下面第一类斯特林数同理

2021-01-30 05:47 UTC, sshwy commented on docs/math/stirling.md
> + **第二类斯特林数** （斯特林子集数） $\begin{Bmatrix}n\\ k\end{Bmatrix}$ 表示将 $n$ 个两两不同的元素，划分为 $k$ 个互不区分的非空子集的方案数。
另外，可以顺便提一句斯特林数的S记号，「S(n,k)」对应第二类，「s(n,k)」对应第一类（加在各自的定义里）

2021-01-30 05:47 UTC, sshwy commented on docs/math/stirling.md
> +### 同一行第二类斯特林数的计算
已经有「第二类斯特林数」的父标题了，可以精简一下（例如改为「计算同一行」之类的）
下面同理

2021-01-30 05:47 UTC, sshwy commented on docs/math/stirling.md
> +```
建议以更完整的代码供参考。代码的作用是给予实现上的参考。这个poly类的代码还是最好放上来，不然初学者很容易不明所以

如果认为代码太长影响阅读，就包裹在 ??? note 里

2021-01-30 05:47 UTC, sshwy commented on docs/math/stirling.md
> + [UOJ269 清华集训2016 如何优雅地求和](https://uoj.ac/problem/269)
```suggestion
- [HDU3625 Examining the Rooms](http://acm.hdu.edu.cn/showproblem.php?pid=3625) 
- [UOJ540 联合省选2020 组合数问题](https://uoj.ac/problem/540)
- [UOJ269 清华集训2016 如何优雅地求和](https://uoj.ac/problem/269)
```

不然全粘在一行上了

2021-01-30 05:47 UTC, sshwy commented on docs/math/stirling.md
> +一个盒子装 $i$ 个物品的方案是 $\begin{cases}1&\text{if }i>0\\0&\text{else}\end{cases}$。我们可以写出它的指数型生成函数为 $F(x)=\sum\limits_{i=1}^{+\infty}\dfrac{x^i}{i!}$。经过之前的学习，我们明白 $F^k(x)$ 就是 $i$ 个有标号物品放到 $k$ 个有标号盒子里的指数型生成函数
```suggestion
一个盒子装 $i$ 个物品且盒子非空的方案数是 $[i>0]$。我们可以写出它的指数型生成函数为 $F(x)=\sum\limits_{i=1}^{+\infty}\dfrac{x^i}{i!} = e^x-1$。经过之前的学习，我们明白 $F^k(x)$ 就是 $i$ 个有标号物品放到 $k$ 个有标号盒子里的指数型生成函数，$\exp F(x)=\sum\limits_{i=0}^{+\infty}\dfrac{F^i(x)}{i!}$ 就是 $i$ 个有标号物品放到任意多个无标号盒子里的指数型生成函数（EXP 通过每项除以一个 $i!$ 去掉了盒子的标号）。这里涉及到很多“有标号”“无标号”的内容，注意辨析。
```

讲道理，一个盒子什么都不放也算一种方案，所以得强调非空
后面 $e^x-1$ 是我擅自加的，用于加强不同板块知识的练习，如果觉得不合适可以删掉

2021-01-30 05:53 UTC, FNatsuka commented on docs/math/stirling.md
> +一个盒子装 $i$ 个物品的方案是 $\begin{cases}1&\text{if }i>0\\0&\text{else}\end{cases}$。我们可以写出它的指数型生成函数为 $F(x)=\sum\limits_{i=1}^{+\infty}\dfrac{x^i}{i!}$。经过之前的学习，我们明白 $F^k(x)$ 就是 $i$ 个有标号物品放到 $k$ 个有标号盒子里的指数型生成函数
强调非空确实会显得更有道理

2021-01-30 05:56 UTC, FNatsuka commented on docs/math/stirling.md
> + **第二类斯特林数** （斯特林子集数） $\begin{Bmatrix}n\\ k\end{Bmatrix}$ 表示将 $n$ 个两两不同的元素，划分为 $k$ 个互不区分的非空子集的方案数。
原文如此，我个人也没感觉特别不合理。S记号的确应该提及。

2021-01-30 05:58 UTC, FNatsuka commented on docs/math/stirling.md
> +### 同一行第二类斯特林数的计算
我觉得这样的问题其实比较偏主观。希望可以有更多人讨论一下对此的看法。

2021-01-30 06:11 UTC, FNatsuka commented on docs/math/stirling.md
> +```
已经在折叠框中添加了poly的代码。

2021-02-02 00:15 UTC, sshwy approved these changes
LGTM

2021-02-06 01:17 UTC, Enter-tainer requested changes

2021-02-06 01:17 UTC, Enter-tainer commented on docs/math/stirling.md
> +??? note "poly"
```suggestion
??? note "参考代码"
```

2021-02-06 01:36 UTC, Enter-tainer approved these changes

2021-02-06 01:37 UTC, sshwy approved these changes

2021-02-06 01:38 UTC, merged