Update seg-beats.md 添加一道题的参考实现
OI-wiki/OI-wiki pull request #2953
Opened 2021-02-01 16:17 UTC by opsiff

添加CPU监控例题的实现

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论你是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈你的感受
3. 如果你熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2021-02-01 16:52 UTC, Enter-tainer requested changes

2021-02-01 16:52 UTC, Enter-tainer commented on docs/ds/seg-beats.md
> +	int mx,_mx;
请不要使用tab和空格混合的代码缩进

2021-02-01 17:13 UTC, opsiff commented on docs/ds/seg-beats.md
> +	int mx,_mx;
嗯，应该是修正了。

2021-02-01 23:42 UTC, sshwy submitted a review, later dismissed

2021-02-02 09:03 UTC, Enter-tainer approved these changes

2021-02-02 11:52 UTC, sshwy approved these changes

2021-02-02 11:52 UTC, merged