chore: format files
OI-wiki/OI-wiki pull request #2965
Opened 2021-02-06 01:50 UTC by Enter-tainer

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论你是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈你的感受
3. 如果你熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2021-02-06 07:38 UTC, Konano approved these changes

2021-02-06 08:01 UTC, Konano requested changes
PR 前确定有检查过吗……（小声
不过还是辛苦了 w

2021-02-06 08:01 UTC, Konano commented on docs/basic/divide-and-conquer.md
> +
上面的换行是有必要的吗？

2021-02-06 08:38 UTC, Enter-tainer commented on docs/graph/dynamic-tree-divide.md
> +
这里应该是要添加的，因为下面的文字和上面同属一个代码框，加上空格之后才能连在一起

2021-02-06 08:45 UTC, CoelacanthusHex commented on docs/intro/faq.md
> +Linux 和 macOS 用户可以尝试使用 [依云](https://github.com/lilydjwg/) 的 [gh-check 脚本](https://gist.github.com/lilydjwg/93d33ed04547e1b9f7a86b64ef2ed058) 获取访问最快的 IP，使用 `--hosts` 参数可以直接更新 hosts 文件。使用 `--help` 参数可以
我觉得这里的依云这个超链接不加空格会比较自然（下一段那个「阅读其使用文档」也是），但是波特好像不能单独处理这种情况？

2021-02-08 10:05 UTC, Enter-tainer commented
本 pr 做的事情：

- 升级了 details 与 space 依赖，解决了波特乱加空格，不收敛等问题
- 修复了 分治 页面的代码块bug
- 手动扮演波特，格式化了所有文件
- @Konano 提出的与空格相关的问题已经修复，我已经对照检查过了。与嵌套列表相关的bug也已经修复，感谢review,辛苦了！
- 目前修改的300多个文件中，几乎全部是对空格的更改

2021-02-08 10:08 UTC, Enter-tainer commented
顺便介绍一下更新后的波特的加空格思路：

对于 行内公式，行内代码，链接，加粗 这四种样式，如果两侧是 中文汉字，或英文字母，数字，那么在两侧添加空格

2021-02-08 10:11 UTC, Enter-tainer commented
欢迎大家来检查一下 deploy preview, 看看有没有出错的渲染 https://deploy-preview-2965--oi-wiki.netlify.app/

2021-02-08 10:28 UTC, Xeonacid commented on docs/basic/binary-lifting.md
> +    数据范围：$1\leq n\leq 10^6$,$1\leq m\leq 10^{18}$,$1\leq k\leq n$,$0\le a_i\le 10^9$。
```suggestion
    数据范围：$1\leq n\leq 10^6, 1\leq m\leq 10^{18}, 1\leq k\leq n, 0\le a_i\le 10^9$。
```
是这么改好呢还是改成中文逗号好呢🤔
（翻了翻有不少类似情况）

2021-02-08 10:33 UTC, Enter-tainer commented on docs/basic/binary-lifting.md
> +    数据范围：$1\leq n\leq 10^6$,$1\leq m\leq 10^{18}$,$1\leq k\leq n$,$0\le a_i\le 10^9$。
🤔感觉弄成中文逗号都会比较可，但是应该超出了波特的能力了

2021-02-08 13:49 UTC, Enter-tainer commented on docs/basic/binary-lifting.md
> +    数据范围：$1\leq n\leq 10^6$,$1\leq m\leq 10^{18}$,$1\leq k\leq n$,$0\le a_i\le 10^9$。
fixed

2021-02-09 12:38 UTC, merged