结合本人的经验和实际操作对命令行这一页进行更新
OI-wiki/OI-wiki pull request #2966
Opened 2021-02-06 03:51 UTC by qinyihao

发起PR的原因：在读OI-Wiki的时候，发现与我自己使用的时候有一点出入，所以结合本人经验和实际操作（写的时候进行了实际测试）更新本页。

更新的内容：

1. 将一些可能过时的内容进行更新
2. 附加了一张图片

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论你是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈你的感受
3. 如果你熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2021-02-06 03:53 UTC, Enter-tainer approved these changes
lgtm

2021-02-06 03:55 UTC, qinyihao commented
不知为啥check没有过，请审核的同学帮忙改一下，谢谢！

2021-02-06 03:57 UTC, Enter-tainer commented on docs/tools/cmd.md
> +![](./images/cmd_exec.jpg)
```suggestion
![](./images/cmd_exec.png)
```

2021-02-06 03:57 UTC, Enter-tainer approved these changes

2021-02-06 08:58 UTC, CoelacanthusHex requested changes
注意格式

2021-02-06 08:58 UTC, CoelacanthusHex commented on docs/tools/cmd.md
> +对于 Windows 系统， **当前目录也在命令行的默认搜索范围内** 。例如 Windows 系统中，输入 `hello` 命令就可以执行当前目录下的 `hello.exe` 。特别的，在Windows10的Powershell中，必须要使用`.\hello.exe`，**注意这里的斜杠是反斜杠**。否则，就会出现以下的报错（以cf-tool的cf.exe为例）：
```suggestion
对于 Windows 系统， **当前目录也在命令行的默认搜索范围内** 。例如 Windows 系统中，输入 `hello` 命令就可以执行当前目录下的 `hello.exe` 。但是在 PowerShell 中，PowerShell 默认不会从当前目录寻找可执行文件（这与在 Linux 的行为一致），因而在 PowerShell 中需要使用相对路径或绝对路径调用当前目录下的可执行文件，例如 `.\hello.exe`，否则，你将看到以下报错（以cf-tool的cf.exe为例）：
```

2021-02-06 08:58 UTC, CoelacanthusHex commented on docs/tools/cmd.md
> +在 Windows 下，使用 `dir` 命令可以列出当前目录的文件列表。在 Linux 下，列出文件列表的命令是 `ls` 。特别的，在Windows Powershell下，可以使用与Linux相同的`ls`命令。
```suggestion
在 Windows 下，使用 `dir` 命令可以列出当前目录的文件列表。在 Linux 下，列出文件列表的命令是 `ls` 。特别的，在 Windows Powershell 下，可以使用与 Linux 相同的 `ls` 命令。
```

2021-02-06 08:58 UTC, CoelacanthusHex commented on docs/tools/cmd.md
> +在 Windows 下，使用 `md <目录>` 或者`mkdir <目录>`命令创建一个新目录，使用 `rd <目录>` 命令删除一个目录。在 Linux 下，这两个命令分别是 `mkdir` 和 `rmdir` 。需要注意的是， **使用 `rd` 或是 `rmdir` 删除一个目录前，这个目录必须是空的** 。如果想要删除非空目录（和该目录下的所有文件）的话，Linux 下可以执行 `rm
```suggestion
在 Windows 下，使用 `md <目录>` 或者 `mkdir <目录>` 命令创建一个新目录，使用 `rd <目录>` 命令删除一个目录。在 Linux 下，这两个命令分别是 `mkdir` 和 `rmdir` 。需要注意的是， **使用 `rd` 或是 `rmdir` 删除一个目录前，这个目录必须是空的** 。如果想要删除非空目录（和该目录下的所有文件）的话，Linux 下可以执行 `rm -r <目录>` 命令，Windows 下可以执行 `rd /s <目录>` 命令。
```

2021-02-06 09:07 UTC, CoelacanthusHex commented
有兴趣的话你可以补充下 PowerShell 里 `curl` 和 `Invoke-WebRequest` 的问题

2021-02-06 09:17 UTC, Xeonacid commented on docs/tools/cmd.md
> +![](./images/cmd_exec.png)
```suggestion
![](./images/cmd-exec.png)
```

2021-02-06 11:34 UTC, qinyihao commented
全都弄过了，请再审核一下，谢谢！

2021-02-06 14:43 UTC, qinyihao commented
@CoelacanthusHex 请再审核一下，谢谢！

2021-02-07 02:18 UTC, CoelacanthusHex approved these changes
thx

2021-02-07 02:31 UTC, Enter-tainer approved these changes
辛苦了

2021-02-07 02:31 UTC, merged