Update tree.md 添加__gnu_pbds::tree
OI-wiki/OI-wiki pull request #2991
Opened 2021-02-12 01:40 UTC by opsiff

添加__gnu_pbds::tree

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论你是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈你的感受
3. 如果你熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2021-02-12 03:21 UTC, Xeonacid requested changes

2021-02-12 03:21 UTC, Xeonacid commented on docs/lang/pb-ds/tree.md
> +    有序向量树只是一个由 vector 实现的有序结构，类似于排序的 vector 来实现平衡树，性能取决于数据想不想卡你
```suggestion
-   `ov_tree_tag`：有序向量树，只是一个由 `vector` 实现的有序结构，类似于排序的 `vector` 来实现平衡树，性能取决于数据想不想卡你
```

2021-02-12 03:21 UTC, Xeonacid commented on docs/lang/pb-ds/tree.md
> +- `insert(x)`：向树中插入一个元素 x，返回 `std::pair<point_iterator,bool>`。
```suggestion
- `insert(x)`：向树中插入一个元素 x，返回 `std::pair<point_iterator, bool>`。
```

2021-02-12 08:55 UTC, opsiff commented on docs/lang/pb-ds/tree.md
> +- `Node_Update`：用于更新节点的策略，默认使用 `tree_order_statistics_node_update`
如果使用null_node_update 则树不可支持find_by_order和order_of_key方法

2021-02-12 09:10 UTC, opsiff commented on docs/lang/pb-ds/tree.md
> +- `Key`: 储存的元素类型，一般为 `pair<T1,T2>` T1 为第一关键字类型，T2 为第二关键字类型，类似于存储元素在 `std::set` 中
如果不使用pair的话 那么由于null_type,树上不可存储多个相同元素，使用pair类似于给一个同样的值元素加了多个标签，为了找到某个值元素，可以使用lower_bound方法和upper_bound方法

2021-02-12 09:12 UTC, Xeonacid commented on docs/lang/pb-ds/tree.md
> +- `Node_Update`：用于更新节点的策略，默认使用 `tree_order_statistics_node_update`
但是默认的确是 null_node_update 呀

2021-02-12 09:12 UTC, Xeonacid commented on docs/lang/pb-ds/tree.md
> +- `Node_Update`：用于更新节点的策略，默认使用 `tree_order_statistics_node_update`
> 如果使用null_node_update 则树不可支持find_by_order和order_of_key方法

这句话可以加进去（

2021-02-12 09:12 UTC, Xeonacid commented on docs/lang/pb-ds/tree.md
> +- `Key`: 储存的元素类型，一般为 `pair<T1,T2>` T1 为第一关键字类型，T2 为第二关键字类型，类似于存储元素在 `std::set` 中
> 如果不使用pair的话 那么由于null_type,树上不可存储多个相同元素，使用pair类似于给一个同样的值元素加了多个标签，为了找到某个值元素，可以使用lower_bound方法和upper_bound方法

这句话也可以加进去（

2021-02-12 09:13 UTC, opsiff commented on docs/lang/pb-ds/tree.md
> +- `Node_Update`：用于更新节点的策略，默认使用 `tree_order_statistics_node_update`
那我多说一点废话吧

2021-02-12 09:14 UTC, Xeonacid commented on docs/lang/pb-ds/tree.md
> +- `Key`: 储存的元素类型，一般为 `pair<T1,T2>` T1 为第一关键字类型，T2 为第二关键字类型，类似于存储元素在 `std::set` 中
我的意思是，很多情况下都是更多关键字的 struct 之类的，并不“一般为 pair”

2021-02-12 09:19 UTC, opsiff commented on docs/lang/pb-ds/tree.md
> +- `Key`: 储存的元素类型，一般为 `pair<T1,T2>` T1 为第一关键字类型，T2 为第二关键字类型，类似于存储元素在 `std::set` 中
那为啥吧`Mapped`删掉了，不大对吧

2021-02-12 09:19 UTC, opsiff commented on docs/lang/pb-ds/tree.md
> +- `Key`: 储存的元素类型，一般为 `pair<T1,T2>` T1 为第一关键字类型，T2 为第二关键字类型，类似于存储元素在 `std::set` 中
我重新修一下我的表述

2021-02-12 10:00 UTC, Xeonacid commented on docs/lang/pb-ds/tree.md
> +- `Mapped`: 映射规则（Mapped-Policy）类型，指示关联容器是 **集合**, 为 `null_type`，低版本 `g++` 此处为 `null_mapped_type`，类似于存储元素在 `std::set` 中，如果想要存储多个相同的 `Key`元素，则需要使用类似于 `std::pair` 和 `struct` 的方法,并配合使用 `lower_bound` 和 `u
应该放Key后面吧（

2021-02-12 10:00 UTC, Xeonacid commented on docs/lang/pb-ds/tree.md
> +- `Mapped`: 映射规则（Mapped-Policy）类型，指示关联容器是 **集合**, 为 `null_type`，低版本 `g++` 此处为 `null_mapped_type`，类似于存储元素在 `std::set` 中，如果想要存储多个相同的 `Key` 元素，则需要使用类似于 `std::pair` 和 `struct` 的方法，并配合使用 `lower_bound` 和 `
应该放Key后面吧（

2021-02-12 10:15 UTC, opsiff commented on docs/lang/pb-ds/tree.md
> +- `Mapped`: 映射规则（Mapped-Policy）类型，指示关联容器是 **集合**, 为 `null_type`，低版本 `g++` 此处为 `null_mapped_type`，类似于存储元素在 `std::set` 中，如果想要存储多个相同的 `Key` 元素，则需要使用类似于 `std::pair` 和 `struct` 的方法，并配合使用 `lower_bound` 和 `
我再多啰嗦一些（

2021-02-12 10:26 UTC, opsiff commented
害，其实这个东西本质上就是增强的set和map。

2021-02-12 10:34 UTC, Xeonacid approved these changes
thx

2021-02-12 19:48 UTC, Konano approved these changes

2021-02-13 06:51 UTC, opsiff commented
问：是否需要我重新合成一份commit 这个太丑了

2021-02-13 06:54 UTC, opsiff commented
> 问：是否需要我重新合成一份commit 这个太丑了

指的是十几个commit 你们merge进去想想就难看(

2021-02-13 06:56 UTC, Xeonacid commented
> 问：是否需要我重新合成一份commit 这个太丑了

不需要啦 😆 这 repo history 已经非常乱了（

2021-02-13 06:57 UTC, merged