更新了 Python 的获取方式。
OI-wiki/OI-wiki pull request #2998
Opened 2021-02-15 18:20 UTC by alissa42

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论你是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈你的感受
3. 如果你熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2021-02-15 18:21 UTC, abc1763613206 commented
条件允许的话，顺便把那个「装3.7得3.6」的生草bug修了吧

2021-02-15 18:24 UTC, billchenchina requested changes

2021-02-15 18:24 UTC, billchenchina commented on docs/lang/python.md
> +额外地，可以在 Microsoft 商店免费获取 Python。
```suggestion
额外地，可以在 Microsoft 商店[免费获取 Python](https://www.microsoft.com/store/productId/9P7QFQMJRFP7)。
```

2021-02-15 18:24 UTC, billchenchina commented on docs/lang/python.md
> +而由于种种依赖问题（如 CentOS 的 yum )，自行编译安装后通常还要处理种种问题，这已经超出了本文的讨论范畴。可以使用软件包管理器 Nix 来管理 Python、Python 工具链和 Python 软件包，这样不会出现依赖问题。
python 各种工具链、版本啥的感觉方法太多了...还有 pipenv、pyenv、conda 等等...

2021-02-16 00:12 UTC, abc1763613206 commented on docs/lang/python.md
> +而由于种种依赖问题（如 CentOS 的 yum )，自行编译安装后通常还要处理种种问题，这已经超出了本文的讨论范畴。可以使用软件包管理器 Nix 来管理 Python、Python 工具链和 Python 软件包，这样不会出现依赖问题。
建议只把 Nix 当举例用（

2021-02-16 00:47 UTC, Enter-tainer commented on docs/lang/python.md
> +而由于种种依赖问题（如 CentOS 的 yum )，自行编译安装后通常还要处理种种问题，这已经超出了本文的讨论范畴。可以使用软件包管理器 Nix 来管理 Python、Python 工具链和 Python 软件包，这样不会出现依赖问题。
建议还是把用的人比较多的东西（conda。venv）什么的放在nix前面，nix还是比较适合 power user

2021-02-16 07:16 UTC, billchenchina requested changes

2021-02-16 07:16 UTC, billchenchina commented on docs/lang/python.md
> +而由于种种依赖问题（如 CentOS 的 yum )，自行编译安装后通常还要处理种种问题，这已经超出了本文的讨论范畴。可以使用软件包管理器 Nix 来管理 Python、Python 工具链和 Python 软件包，这样不会出现依赖问题。
```suggestion
而由于种种依赖问题（如 CentOS 的 yum )，自行编译安装后通常还要处理种种问题，这已经超出了本文的讨论范畴。可以使用 venv、conda、Nix 等方法来管理 Python、Python 工具链和 Python 软件包，这样不会出现依赖问题。
```

2021-02-16 07:23 UTC, billchenchina approved these changes

2021-02-16 07:43 UTC, StudyingFather approved these changes

2021-02-16 07:43 UTC, merged