添加了关于包和foreach以及获取输入的内容，顺便把switch从循环小节移动到了条件小节里面。
OI-wiki/OI-wiki pull request #3027
Opened 2021-03-01 13:00 UTC by AmemiyaSigure

添加了关于包和foreach以及获取输入的内容，顺便把switch从循环小节移动到了条件小节里面。

Signed-off-by: 秋雨落 <i@rain.cx>

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论你是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈你的感受
3. 如果你熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2021-03-01 13:16 UTC, CoelacanthusHex submitted a review, later dismissed
thx

2021-03-02 12:06 UTC, ksyx requested changes
thx

2021-03-02 12:06 UTC, ksyx commented on docs/lang/java.md
> +一个打包的 `Java` 程序（名称一般是 `*.jar`）中可以有很多个类似的函数，但是当双击运行这个程序的时候，只有其中一个函数会被运行，这是定义在 `Jar` 的 `Manifest` 文件中的，在 OI 比赛中一般用不到关于它的知识。
```suggestion
一个打包的 `Java` 程序（名称一般是 `*.jar`）中可以有很多个类似的函数，但是当运行这个程序的时候，只有其中一个函数会被运行，这是定义在 `Jar` 的 `Manifest` 文件中的，在 OI 比赛中一般用不到关于它的知识。
```
在 oi 里 java 也用得不多的说

2021-03-02 12:06 UTC, ksyx commented on docs/lang/java.md
> +如果想要导入某包下面所有的类，只需要把这个语句最后的分号前的类名换成星号 `*`。
```suggestion
如果想要导入某包下面所有的类，只需要把这个语句最后的分号前的类名换成 `*`。
```

2021-03-02 12:06 UTC, ksyx commented on docs/lang/java.md
> +              break; // 如果不加上 break 语句,会让程序按顺序往下执行,执行所有的 case 语句
```suggestion
              break; // 如果不加上 break 语句,会让程序按顺序往下执行直到 break
```

2021-03-02 12:06 UTC, ksyx commented on docs/lang/java.md
> +for 关键字有两种使用方法，其中第一种是普通的 for 循环，形式如下：
```suggestion
`for` 关键字有两种使用方法，其中第一种是普通的 `for` 循环，形式如下：
```

2021-03-02 12:06 UTC, ksyx commented on docs/lang/java.md
> +第二种是类似 `C++` 的 foreach 使用方法，用于循环数组或者集合中的数据，相当于把上一种方式中的循环变量隐藏起来了，形式如下：
```suggestion
第二种是类似 C++ 的 `foreach` 使用方法，用于循环数组或者集合中的数据，相当于把上一种方式中的循环变量隐藏起来了，形式如下：
```

2021-03-02 12:06 UTC, ksyx commented on docs/lang/java.md
> +创建 `Java` 源程序需要类名和文件名一致才能编译通过，否则编译器会提示找不到 `类`。通常该文件名会在具体 OJ 中指定。
```suggestion
创建  Java 源程序需要类名和文件名一致才能编译通过，否则编译器会提示找不到类。通常该文件名会在具体 OJ 中指定。
```

2021-03-02 12:11 UTC, ksyx commented
另外不建议在 master 工作哦

2021-03-02 12:16 UTC, ksyx commented
可以在 pr 的 Files tab 里 Add to batch 一次性提交

2021-03-02 12:17 UTC, ksyx approved these changes

2021-03-02 12:18 UTC, AmemiyaSigure commented
> 可以在 pr 的 Files tab 里 Add to batch 一次性 commit review

学到了

2021-03-02 12:23 UTC, CoelacanthusHex submitted a review, later dismissed

2021-03-02 12:58 UTC, CoelacanthusHex approved these changes
thx

2021-03-02 13:34 UTC, ksyx approved these changes
thx

2021-03-02 13:34 UTC, merged