添加压位高精下的高效除法方法
OI-wiki/OI-wiki pull request #3043
Opened 2021-03-10 13:14 UTC by Baobaobear

feat: 添加压位高精下的高效除法方法
feat: 添加一个迷你实现模板
fix: 末尾模板改为const引用

2021-03-23 05:44 UTC, Enter-tainer commented on docs/math/bignum.md
> +压位高精下，比如说用万进制，如果每个位仍然使用前面介绍的，大于等于就减 1 的方法，那在除法下常数会非常大，在万进制下那每个位平均需要减个 5000 次，这个是不可接受的。这里需要一个高效的试商办法，平均每个位只需要试一次。
重新组织一下语言?这段有点病句太多了

2021-03-25 01:18 UTC, Enter-tainer requested changes

2021-03-25 01:18 UTC, Enter-tainer commented on docs/math/bignum.md
> +在压位高精下，如果试商时仍然使用上文介绍的方法，那么计算常数会非常大，因为试商次数会非常多。比如说在万进制下，平均每个位需要试商 5000 次，这个巨大的常数是不可接受的。所以在压位高精下需要一个更高效的试商办法。
```suggestion
在使用压位高精时，如果试商时仍然使用上文介绍的方法，由于试商次数会很多，计算常数会非常大。例如在万进制下，平均每个位需要试商 5000 次，这个巨大的常数是不可接受的。因此我们需要一个更高效的试商办法。
```

2021-03-25 01:18 UTC, Enter-tainer commented on docs/math/bignum.md
> +我们可以利用 double 作为媒介，假设被除数有 4 个位，是 $a_4,a_3,a_2,a_1$，除数有 3 个位，是 $b_3,b_2,b_1$，那么我们只要试一位的商（多个位就是一位的写法加个循环），使用 $base$ 进制，用式子 $\dfrac{a_4 base + a_3}{b_3 + b_2 base^{-1} + (b_1+1)base^{-2}}$ 来估商，由于使用 3 位的
```suggestion
我们可以把 double 作为媒介。假设被除数有 4 位，是 $a_4,a_3,a_2,a_1$，除数有 3 位，是 $b_3,b_2,b_1$，那么我们只要试一位的商：使用 $base$ 进制，用式子 $\dfrac{a_4 base + a_3}{b_3 + b_2 base^{-1} + (b_1+1)base^{-2}}$ 来估商。而对于多个位的情况，就是一位的写法加个循环。由于使用 3 位的精度，能保证估的商小于等于实际商，且误差不超过 1，这样每个位只需要一次试商。但由于此方法需要 3 个位，所以要求这在 double 的有效精度内，建议不要使用超过 32768 进制，如超过，那需要换一种试商办法。
```

2021-03-25 01:18 UTC, Enter-tainer commented on docs/math/bignum.md
> +我们可以利用 double 作为媒介，假设被除数有 4 个位，是 $a_4,a_3,a_2,a_1$，除数有 3 个位，是 $b_3,b_2,b_1$，那么我们只要试一位的商（多个位就是一位的写法加个循环），使用 $base$ 进制，用式子 $\dfrac{a_4 base + a_3}{b_3 + b_2 base^{-1} + (b_1+1)base^{-2}}$ 来估商，由于使用 3 位的
```
由于使用 3 位的精度，能保证估的商小于等于实际商，且误差不超过 1，这样每个位只需要一次试商。但由于此方法需要 3 个位，所以要求这在 double 的有效精度内，建议不要使用超过 32768 进制，如超过，那需要换一种试商办法。
```

这句也需要改改，但是我没有太读懂

2021-03-30 13:13 UTC, Enter-tainer approved these changes
thx!

2021-04-01 11:52 UTC, StudyingFather approved these changes

2021-04-01 11:52 UTC, merged