在常见错误中添加换行符不同导致的错误
OI-wiki/OI-wiki pull request #3094
Opened 2021-04-05 09:55 UTC by swift-zym

fix #2007 

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论你是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈你的感受
3. 如果你熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2021-04-05 10:01 UTC, Enter-tainer requested changes
请注意本页面的分类

2021-04-05 10:06 UTC, swift-zym commented
> 请注意本页面的分类

#2007 里不是说要这么加吗。。。

2021-04-05 10:07 UTC, Enter-tainer commented
注意目录 
![image](https://user-images.githubusercontent.com/25521218/113563179-d07bab00-9639-11eb-909f-c7a218abad0b.png)

2021-04-05 10:09 UTC, swift-zym commented
> 注意目录
> ![image](https://user-images.githubusercontent.com/25521218/113563179-d07bab00-9639-11eb-909f-c7a218abad0b.png)

您的意思是把它放到 “会导致WA的错误” 下面吗？

2021-04-05 10:12 UTC, Enter-tainer commented
嗯感觉应该可以

2021-04-05 10:23 UTC, Enter-tainer approved these changes
thx

2021-04-05 10:29 UTC, Enter-tainer submitted a review, later dismissed

2021-04-05 10:33 UTC, Xeonacid commented on docs/contest/common-mistakes.md
> +- CR（用 `\r` 表示）：`Mac OS` 至版本 9
这常用吗（？

2021-04-05 10:35 UTC, Xeonacid commented on docs/contest/common-mistakes.md
> +- 使用 `cin` 读入，**这可能会增大代码常数**。
为什么不能使用scanf直接读入呢

2021-04-05 10:35 UTC, swift-zym commented on docs/contest/common-mistakes.md
> +- CR（用 `\r` 表示）：`Mac OS` 至版本 9
因为用 CR 的操作系统就这一个，所以就加上了（

2021-04-05 10:36 UTC, Xeonacid commented on docs/contest/common-mistakes.md
> +    在正式比赛中会保证选手答题的环境和最终测试的环境相同。
某些省份的NOIP/省选并不能保证这一点（

2021-04-05 10:42 UTC, swift-zym commented on docs/contest/common-mistakes.md
> +- 使用 `cin` 读入，**这可能会增大代码常数**。
因为直接 scanf 也会读入换行符啊

2021-04-05 14:15 UTC, Xeonacid commented on docs/contest/common-mistakes.md
> +- 使用 `cin` 读入，**这可能会增大代码常数**。
`scanf(" %c",&c)`
🤔

2021-04-05 14:17 UTC, swift-zym commented on docs/contest/common-mistakes.md
> +- 使用 `cin` 读入，**这可能会增大代码常数**。
我没试过 QwQ

2021-04-05 23:49 UTC, swift-zym commented on docs/contest/common-mistakes.md
> +- 使用 `cin` 读入，**这可能会增大代码常数**。
这样在 `\r\n` 的时候也只能过滤掉 `\r` 吧

2021-04-06 08:21 UTC, Enter-tainer submitted a review, later dismissed
辛苦了

2021-04-06 08:22 UTC, Enter-tainer approved these changes

2021-04-06 09:42 UTC, Xeonacid approved these changes
thx

2021-04-06 10:00 UTC, merged