试着写了写编译最简单的入门，可以处理字符串问题
OI-wiki/OI-wiki pull request #3101
Opened 2021-04-09 06:02 UTC by Great-designer

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论你是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈你的感受
3. 如果你熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

感觉这个坑说大不大，说小不小

2021-04-09 06:14 UTC, ksyx reviewed
感谢您的贡献。这里文章结构稍有跳跃，lex 和 parse 看上去边界不是太清晰，以及：

- 请在 [目录](https://github.com/OI-wiki/OI-wiki/blob/master/mkdocs.yml) 中加入对应项
- 建议加入对应专有名词的英文；**请阅读格式手册**，将符号用 `` 包起来。这里的很好的例题是 [未来程序改](https://uoj.ac/problem/98)
- 不建议在 master branch 上工作

2021-04-09 06:14 UTC, ksyx commented on docs/string/compiling.md
> +用“：:=”符号，表示“由……组成”。文法规则一般形如：
```suggestion
用 `::=` 符号，表示“由……组成”。文法规则一般形如：
```

2021-04-09 06:14 UTC, ksyx commented on docs/string/compiling.md
> +&lt;谓语> ::= &lt; 动词 > &lt; 宾语 >
```suggestion
```plain
<句子> ::= <主语> <谓语>

<谓语> ::= <动词 > <宾语>
```
```
此外自然语言对这个例子来说并不是很好的选择

2021-04-09 06:22 UTC, Xeonacid requested changes
> 事实上几乎可以解决所有的字符串问题

希望可以写一下如何解决字符串问题，配一些例题之类的

2021-04-09 06:24 UTC, ksyx commented
> > 事实上几乎可以解决所有的字符串问题
> 
> 希望可以写一下如何解决字符串问题，配一些例题之类的

另外建议减少绝对性描述，而是描述解决哪一类问题

2021-04-13 02:46 UTC, Enter-tainer commented on docs/string/compiling.md
> +本文讲一些编译入门的基础知识与算法。如果掌握了编译里面的一些算法，可以解决大多数字符串匹配类型的问题。
> 可以解决大多数字符串匹配类型的问题

这个可能有点言过其实了(?)

2021-04-15 06:01 UTC, Great-designer commented on docs/string/compiling.md
> +本文讲一些编译入门的基础知识与算法。如果掌握了编译里面的一些算法，可以解决大多数字符串匹配类型的问题。
对于单纯检查“源程序是否符合文法规则”，即检查“字符串是否符合题目给的条件”，只考虑“检查”，不考虑“处理”的时候，并且不涉及上下文有关文法（这属于语义分析，比如变量先声明再使用这种规则），语法分析**确实可以解决100%的此类问题**。
如果涉及“处理”，一般考虑在语法分析的基础上增加动作。比如“字符串逆序”是一个典型的“处理”型问题。那么在语法分析的基础上，设计一个栈，相当于在语法中插入动作符号，从而实现“字符串逆序”这一“处理”的目的。
如果涉及“上下文有关文法”，那么语义分析也建立在语法分析的基础上，并且借助一些附加工具。比如上面提到的实现“变量先声明再使用”的功能，就需要借助“符号表”这种工具，通过查表来解决问题。这也是在语法分析程序框架已经搭好之后，通过在框架当中对应位置插入各类工具来实现。
综上，一切变式都在解决语法分析的基础上才能进行。编译可以解决100%的字符串问题，“语法分析可以解决大多数字符串匹配类型的问题”，该叙述比较保守，没有言过其实。

2021-04-15 08:13 UTC, Marcythm commented on docs/string/compiling.md
> +本文讲一些编译入门的基础知识与算法。如果掌握了编译里面的一些算法，可以解决大多数字符串匹配类型的问题。
您好，可否指教一下如何利用语法分析来实现一个后缀自动机的功能？如果能提供代码就更好了。感激不尽！

2021-04-15 08:27 UTC, ksyx commented
对于这个“能解决 100% 的字符串问题”，是否有出处（citation needed），或者是原创研究？

2021-04-15 10:11 UTC, Great-designer commented on docs/string/compiling.md
> +本文讲一些编译入门的基础知识与算法。如果掌握了编译里面的一些算法，可以解决大多数字符串匹配类型的问题。
> 您好，可否指教一下如何利用语法分析来实现一个后缀自动机的功能？如果能提供代码就更好了。感激不尽！

您好。查了一下，这可能属于正则文法（词法分析解决的III型文法）的范畴，也可能属于LR(1)文法。正则文法已经由最小化DFA解决了，LR(1)文法以及一系列的SLR(1)、LALR(1)等等，已经过于复杂，我写不了。

OIwiki上关于自动机相关，已经写了非常多的内容。编译课上的词法分析，基本上就是DFA、NFA等等，这部分没必要写了。

2021-04-15 10:18 UTC, Great-designer commented
> 对于这个“能解决 100% 的字符串问题”，是否有出处（citation needed），或者是原创研究？

您好。艾弗拉姆·诺姆·乔姆斯基（Avram Noam Chomsky）于1956年提出乔姆斯基体系：

0型文法（无限制文法或短语结构文法）包括所有的文法。该类型的文法能够产生所有可被图灵机识别的语言。可被图灵机识别的语言是指能够使图灵机停机的字串，这类语言又被称为递归可枚举语言。

I型文法（上下文相关文法）生成上下文相关语言。这种文法的产生式规则取如 αAβ -> αγβ 一样的形式。这里的A是非终结符号，而 α, β 和 γ 是包含非终结符号与终结符号的字串；α, β 可以是空串，但 γ 必须不能是空串；这种文法也可以包含规则 S->ε ，但此时文法的任何产生式规则都不能在右侧包含 S 。这种文法规定的语言可以被线性有界非确定图灵机接受。

II型文法（上下文无关文法）生成上下文无关语言。这种文法的产生式规则取如A-> γ 一样的形式。这里的A是非终结符号，γ 是包含非终结符号与终结符号的字串。这种文法规定的语言可以被非确定下推自动机接受。

III型文法（正规文法）生成正规语言。这种文法要求产生式的左侧只能包含一个非终结符号，产生式的右侧只能是空串、一个终结符号或者一个终结符号后随一个非终结符号；如果所有产生式的右侧都不含初始符号 S ，规则 S -> ε 也允许出现。这种文法规定的语言可以被有限状态自动机接受，也可以通过正则表达式来获得。

（以上内容摘自百度百科乔姆斯基文法词条）

词法分析利用DFA理论解决III型文法问题，语法分析解决II型文法问题，语义分析等手段解决编程语言中出现的的部分I型文法问题。

而编译这门学科的主要研究对象就是以上所有的文法，当然涵盖了100%的字符串问题。

2021-04-15 10:23 UTC, Enter-tainer commented
字符串问题是一个很大的范畴..并不是只有字符串匹配. 而即使是字符串的匹配, 也有很多不同的算法, 他们在时间和空间上都有不同的  tradeoff.

不如先去看看 [LOJ 的字符串类型的题目](https://loj.ac/p?tagIds=7) 和 [OI WIki 的字符串标签](https://next.oi-wiki.org/tags/string) 再来讨论?

2021-04-15 10:24 UTC, Enter-tainer commented
另一方面, 给某种算法加上"可以解决100%问题"的修饰很容易给刚刚接触该算法的同学造成不必要的误导, 更何况这种类型的题目在 OI 的正式比赛中很少出现.

2021-04-15 10:31 UTC, Great-designer commented
（在具体文章中没有“100%”这样的表述，并且这个大坑也不只是一种算法）

看了看楼上的提问。目前感觉用这门学科的东西去解OI问题，似乎有一些杀鸡用牛刀了，而且本人确实水平有限，很多复杂的东西难以写清楚，若是试图以简单的口吻去写又容易造成一些其他困扰。

还是等更专业的人来写这个坑好了。这个Commit终结。

2021-04-15 10:31 UTC, closed without merging

2021-04-15 10:35 UTC, Great-designer commented
> 字符串问题是一个很大的范畴..并不是只有字符串匹配. 而即使是字符串的匹配, 也有很多不同的算法, 他们在时间和空间上都有不同的 tradeoff.
> 
> 不如先去看看 [LOJ 的字符串类型的题目](https://loj.ac/p?tagIds=7) 和 [OI WIki 的字符串标签](https://next.oi-wiki.org/tags/string) 再来讨论?

这些确实也都在这个学科的范畴里，可能并不在这篇文章的范畴里。不讨论了。