fix: fixed update time display format(#3099)
OI-wiki/OI-wiki pull request #3102
Opened 2021-04-09 16:52 UTC by imp2002

fix #3099

2021-04-10 12:09 UTC, Henry-ZHR commented
![图片](https://user-images.githubusercontent.com/51886614/114269252-824f1900-9a38-11eb-9fc8-b1bc40af9945.png)

看起来有什么东西锅了

2021-04-10 12:17 UTC, imp2002 commented
> ![图片](https://user-images.githubusercontent.com/51886614/114269252-824f1900-9a38-11eb-9fc8-b1bc40af9945.png)
> /
> 看起来有什么东西锅了

呜呜写成HH了，emmm您是怎看到效果的呢？我在本地部署看不到。
![image](https://user-images.githubusercontent.com/41513919/114269463-cd1d6080-9a39-11eb-9286-abd4d5fe61b5.png)

2021-04-10 12:19 UTC, Henry-ZHR commented
@imp2002

2021-04-13 02:42 UTC, Enter-tainer requested changes

2021-04-13 02:42 UTC, Enter-tainer commented on docs/_static/js/extra.js
> +    Date.prototype.format = function (fmt) {
建议写个正常的函数吧,这样去注入全局对象..emmm就感觉不太好

2021-04-13 02:43 UTC, Enter-tainer commented
可以考虑试试这样, 然后拼起来?
![image](https://user-images.githubusercontent.com/25521218/114489056-0bd33680-9c45-11eb-8a45-c5ddadbe1f3c.png)

```
t.toLocaleTimeString('zh-CN', { timeZone: "Asia/Shanghai", hour12: false })
```

2021-04-13 10:39 UTC, Enter-tainer approved these changes
辛苦了

2021-04-13 14:11 UTC, Henry-ZHR commented
写死时区感觉不太好吧

2021-04-13 14:12 UTC, Enter-tainer commented
> 写死时区感觉不太好吧

原来就是写死的, 如果有其他想法的话建议新开 issue

2021-04-15 10:17 UTC, Ir1d approved these changes
LGTM. Thx! 辛苦啦～

2021-04-15 15:25 UTC, merged