Update seg.md 更新"线段树"
OI-wiki/OI-wiki pull request #3144
Opened 2021-04-30 11:45 UTC by 2020020201

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论你是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈你的感受
3. 如果你熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2021-04-30 12:40 UTC, Early0v0 requested changes
`s + (t - s) >> 1` 为 `(s + (t - s)) >> 1`，请修正

2021-05-01 01:03 UTC, 2020020201 commented
> `s + (t - s) >> 1` 为 `(s + (t - s)) >> 1`，请修正

(s + (t - s)) >> 1 = t >> 1 然而好像是不对的

2021-05-01 09:12 UTC, hly1204 commented
> `s + (t - s) >> 1` 为 `(s + (t - s)) >> 1`，请修正

话说这不是没区别吗。。

2021-05-01 09:18 UTC, Enter-tainer commented
> > `s + (t - s) >> 1` 为 `(s + (t - s)) >> 1`，请修正
> 
> (s + (t - s)) >> 1 = t >> 1 然而好像是不对的

移位运算符优先级的优先级是低于加法的。。。所以请你重新阅读你所回复的评论，然后改一下。

2021-05-01 09:22 UTC, hly1204 commented
> > > `s + (t - s) >> 1` 为 `(s + (t - s)) >> 1`，请修正
> > 
> > 
> > (s + (t - s)) >> 1 = t >> 1 然而好像是不对的
> 
> 移位运算符优先级的优先级是低于加法的。。。所以请你重新阅读你所回复的评论，然后改一下。

为啥我觉得俩都错了。。

2021-05-01 09:23 UTC, Enter-tainer commented
@hly1204 请再读一遍。。。

2021-05-01 09:23 UTC, Enter-tainer commented
@hly1204 “x 为 y” 的意思是，x 加上括号在 y。。。

2021-05-01 09:25 UTC, hly1204 commented
> @hly1204 “x 为 y” 的意思是，x 加上括号是 y。。。

我还以为是那个意思。。

2021-05-02 14:22 UTC, Early0v0 commented
44 行那里还有一个没改（

2021-05-03 11:32 UTC, Early0v0 approved these changes

2021-05-04 00:59 UTC, Xeonacid approved these changes
thx

2021-05-04 03:48 UTC, merged

2021-05-04 04:39 UTC, Ir1d commented on docs/ds/seg.md
> +  int m = s + (t - s) >> 1;
mark

2021-05-04 04:40 UTC, Ir1d commented on docs/ds/seg.md
> +      int mid = ((t - s) >> 1);
mark