feat (bigraph-match)：为两道例题添加了分析与代码
OI-wiki/OI-wiki pull request #3156
Opened 2021-05-07 11:20 UTC by zhuyifan314

2021-05-22 09:22 UTC, sshwy requested changes

2021-05-22 09:22 UTC, sshwy commented on docs/graph/graph-matching/bigraph-match.md
> +    每天都有学生退出社团，我们很难维护这种操作，正难则反，我们倒叙枚举删去的学生，统计完当天的答案后，就将当前枚举的学生加入图中。注意匹配和标记数组初始化应为 $-1$，因为 $0$ 也是能力值。
```suggestion
    每天都有学生退出社团，我们很难维护这种操作，正难则反，我们倒序枚举删去的学生，统计完当天的答案后，就将当前枚举的学生加入图中。注意匹配和标记数组初始化应为 $-1$，因为 $0$ 也是能力值。
```

2021-06-13 07:12 UTC, Enter-tainer requested changes

2021-06-13 07:12 UTC, Enter-tainer commented on docs/graph/graph-matching/bigraph-match.md
> +        add(p\[k[i]], c\[k[i]]);
这是什么？除号写反了吗

2021-06-13 07:13 UTC, Enter-tainer commented on docs/graph/graph-matching/bigraph-match.md
> +        add(p\[k[i]], c\[k[i]]);
请确保你贴上来的代码是正确的

2022-04-17 01:25 UTC, closed without merging