refactor: sublime.md 大幅更改并增加了 sublime text 的内容
OI-wiki/OI-wiki pull request #3184
Opened 2021-05-21 13:05 UTC by ToUNVRSe

之前的 ST3 是好久前写的了，过去了这么久加点使用经验进去。修改了亿些问题。
主要是自定义方面的，毕竟这种东西用越久好东西越多（
其次是编辑方面的（指变成 Ctrl 的形状了）。
然后就是对标了一下 vim 。
总算写完了，大家知道我手残人比较滞涨估计又是一堆锅。

结果 ST4 出来了 emm……
~~（界面真的好帅）~~
做了一些兼容准备，然后没有精力开箱了准备等别人来写（

2021-05-21 13:11 UTC, CoelacanthusHex commented on docs/tools/editor/sublime.md
> +```html
这里的高亮应该用XML？
```suggestion
```xml
```

2021-05-21 13:21 UTC, ksyx reviewed
- kbd 两边请加空格（但是好像会被 bot revert 掉
- JSON，Vim 大小写
- 代码块内中英之间的空格

2021-05-21 13:21 UTC, ksyx commented on docs/tools/editor/sublime.md
> +Sublime Text 是一款轻量级的文本编辑器，支持多种语言的语法高亮及代码补全。具有高度的可拓展性以及 vim 模式，特别的热启动模式大幅避免了文件丢失的可能。
```suggestion
Sublime Text 是一款轻量级的文本编辑器，支持多种语言的语法高亮及代码补全。具有高度的可拓展性以及 Vim 模式，特别的热启动模式大幅避免了文件丢失的可能。
```

2021-05-21 13:21 UTC, ksyx commented on docs/tools/editor/sublime.md
> +直接前往 [官网](https://www.sublimetext.com/3) 下载即可，如果使用搜索引擎，可能会搜索到中文官网，提供的安装包与英文官网是同一个链接。
建议直接给中文官网链接

2021-05-21 13:21 UTC, ksyx commented on docs/tools/editor/sublime.md
> +    "cmd": [“g++","-Wall","${file}","-o","${file_path}/${file_base_name}"],
```suggestion
    "cmd": ["g++","-Wall","${file}","-o","${file_path}/${file_base_name}"],
```

2021-05-21 13:21 UTC, ksyx commented on docs/tools/editor/sublime.md
> +    "shell_cmd": [g++","-Wall","${file}","-o","${file_path}/${file_base_name}","&&","${file_path}/${file_base_name}& pause"],
```suggestion
    "shell_cmd": ["g++","-Wall","${file}","-o","${file_path}/${file_base_name}","&&","${file_path}/${file_base_name}& pause"],
```

不确定，但是看着不对劲

2021-05-21 13:21 UTC, ksyx commented on docs/tools/editor/sublime.md
> +??? note "为什么感觉时间多了？"
~~👓~~

2021-05-21 13:21 UTC, ksyx commented on docs/tools/editor/sublime.md
> +    注意这个时间是从按下<kbd>Ctrl</kbd>+<kbd>B</kbd>到程序结束的时间，也就是说包括编译的时间和输入的时间，以及如果在外部 CMD 运行还包括 CMD 开启关闭的时间，总之确实不太准。
挂钟时间，并不能说*不太准*。

2021-05-21 13:21 UTC, ksyx commented on docs/tools/editor/sublime.md
> +a + b* a + b* a + b
🤔 乘号空格

2021-05-21 13:21 UTC, ksyx commented on docs/tools/editor/sublime.md
> +按右下角的 `Plain Text` 然后修改为你需要的语言即可。
窗口缩小再截图可以更突出重点

2021-05-21 13:21 UTC, ksyx commented on docs/tools/editor/sublime.md
> +#### 与真正 vim 的不同
真正 🤔  考虑更好的表述

2021-05-21 13:21 UTC, ksyx commented on docs/tools/editor/sublime.md
> +	{ "keys": ["shift+f9"], "command": "sort_lines", "args": {"case_sensitive": false} },  //将原有的行排序的快捷键改为shift+f9，由于大部分时候这个功能用不到，这一行也可以不添加
```suggestion
	//将build命令改为f9
	{ "keys": ["f9"], "command": "build" },
	//将原有的行排序的快捷键改为 Shift+F9，由于大部分时候这个功能用不到，这一行也可以不添加
	{ "keys": ["shift+f9"], "command": "sort_lines", "args": {"case_sensitive": false} },  
```

2021-05-21 13:21 UTC, ksyx commented on docs/tools/editor/sublime.md
> +由于插件会时不时更新，所以建议备份自己更改的文件。
```suggestion
由于插件会不时更新，所以建议备份自己更改的文件。
```

2021-05-21 13:21 UTC, ksyx commented on docs/tools/editor/sublime.md
> +建议在首选项中将 `"auto_find_in_selection"` 设置为 `true` 这样在选择超过一个词时使用查找会自动只在选段中查找。
```suggestion
建议在首选项中将 `"auto_find_in_selection"` 设置为 `true`。这样在选择超过一个词时使用查找会自动只在选段中查找。
```

2021-05-21 13:21 UTC, ksyx commented on docs/tools/editor/sublime.md
> +以下假定读者已经开启了 vim 插件。
[为什么？]

2021-05-21 13:21 UTC, ksyx commented on docs/tools/editor/sublime.md
> +
```suggestion
```

2021-05-21 14:49 UTC, Early0v0 commented on docs/tools/editor/sublime.md
> +    从快捷键设置可以看出 ST3 的模式与 vim 很像，理论上只要至包含一个非控制字符的快捷键，可以大部分配置成 vim，但显然需要相当的耐心。
“大部分配置成 vim” 最好也考虑更改一下表述

2021-05-21 14:49 UTC, Early0v0 commented on docs/tools/editor/sublime.md
> +```
能不能折叠一下（

2021-05-22 06:28 UTC, alphagocc commented on docs/tools/editor/sublime.md
> +直接前往 [官网](https://www.sublimetext.com/3) 下载即可，如果使用搜索引擎，可能会搜索到中文官网，提供的安装包与英文官网是同一个链接。
这个没区别，中文官网上下载还是要跳转到英官网

2021-05-22 08:15 UTC, ToUNVRSe commented on docs/tools/editor/sublime.md
> +直接前往 [官网](https://www.sublimetext.com/3) 下载即可，如果使用搜索引擎，可能会搜索到中文官网，提供的安装包与英文官网是同一个链接。
其实，并没有中文官网（似乎）

2021-05-22 08:17 UTC, ToUNVRSe commented
在改了在改了
~~（ST4 首战 APIO，感觉过于好使）~~

2021-05-22 08:20 UTC, ToUNVRSe commented
> 在改了在改了
> ~（ST4 首战 APIO，感觉过于好使）~

另外，这个 bot 的格式化实在诡异（

2021-06-04 11:51 UTC, ToUNVRSe commented
似乎是解决了代码框内的 bot 问题
但 <kbd> 真救不了

2021-06-11 12:19 UTC, ToUNVRSe commented
目前差不多了
接下来无论出现什么滞涨问题
我都要先咕几周QWQ
~~暑假之前 我就是从这里跳下去也不碰这个文件，绝对不改~~

2021-06-13 07:06 UTC, Enter-tainer commented
刚刚试图把 master merge 到这个 pr 上，结果失败了，可能现在存在冲突了，需要注意一下

```
❯ git merge master
Auto-merging mkdocs.yml
CONFLICT (modify/delete): docs/tools/editor/sublime3.md deleted in HEAD and modified in master. Version master of docs/tools/editor/sublime3.md left in tree.
```

2021-07-17 08:11 UTC, ToUNVRSe commented
NOI Linux 有 Sublime 了！
准备看一下版本什么的再写一点。

2021-07-17 13:14 UTC, ToUNVRSe commented
做了更多的兼容性内容，在 ST4 下都确认了一遍是否通用。

~~虽然 NOI Linux 已经限定了要以 ST3 为主~~

然后就是把一些冗余的东西 ~~宏~~ 定义了一下什么的，表述（也许）更清晰全面了 ~~吧~~ 。

还有亿些杂七杂八的历史遗留问题，感觉自己之前都写废了。

感觉又能找出亿吨问题。

~~到底是谁给这堆垃圾点了赞啊~~

2021-07-17 13:25 UTC, ToUNVRSe commented
话说 ST 的开发者也是很用心，VSC 的 Vim 是 Vim 官方写的，ST 的 Vintage 是他们自己写的

2021-07-17 13:33 UTC, CoelacanthusHex commented
@ToUNVRSe VSC 的 Vim mode 居然是 Bram 写的？

2021-07-17 13:46 UTC, ToUNVRSe commented
不对头

为什么他们搞了一个新的用户啊 QAQ，我白激动了……

emm……完了完了。

2021-07-20 07:29 UTC, Xeonacid commented
目录路径等要不要都加上Linux的？

2021-07-20 13:15 UTC, ToUNVRSe commented
@Xeonacid 好啊好啊~~我去开虚拟机~~

2021-07-20 13:53 UTC, ToUNVRSe commented
加完了，因为对 Linux ~~非常~~ 不了解就写的非常的 ~~保守~~

2021-07-20 14:12 UTC, CoelacanthusHex commented on docs/tools/editor/sublime.md
> +    在以 NOI Linux 所使用的 Ubuntu 20.04.1 中，ST3 的数据目录为 `/home/用户名/.config/sublime-text-3`，ST4 的数据目录为 `/home/用户名/.config/sublime-text`，使用的具体规则同 Windows 环境。
Linux 下一般使用 `~` 或者 `$HOME` 表示家目录吧

2021-07-20 14:12 UTC, CoelacanthusHex commented on docs/tools/editor/sublime.md
> +ST 的开发者为 Vi 使用者提供了一个可选插件 Vintage，可模拟 Vi 的部分功能。
```suggestion
### 使用 Vim Mode

ST 的开发者为 Vim 使用者提供了一个可选插件 Vintage，可模拟 Vim 的部分功能。
```
或许使用 Vim 和 Vim Mode 这两个词汇更准确

2021-07-20 14:12 UTC, CoelacanthusHex commented on docs/tools/editor/sublime.md
> +ST 的 Vintage 插件与 Vi 有一定不同，部分列于此处：
```suggestion
#### 与 Vim 的不同

ST 的 Vintage 插件与 Vim 有一定不同，部分列于此处：
```
同上

2021-07-22 11:11 UTC, ToUNVRSe commented
@CoelacanthusHex 路径改了，作者说是 vi ，所以改成的 vi

2021-07-22 11:21 UTC, CoelacanthusHex commented
> @CoelacanthusHex 路径改了，作者说是 vi ，所以改成的 vi

但是 Vi 到 Vi Mode 还是改下比较好吧

2021-08-18 11:29 UTC, ToUNVRSe commented
冲突解决完了
~~鬼知道我写第一份的时候怎么那么多笔误~~
新文件里其实都改了
~~时间过长以至重复修改~~

2021-09-10 02:45 UTC, CoelacanthusHex requested changes

2021-09-10 02:45 UTC, CoelacanthusHex commented on docs/tools/editor/sublime.md
> +    在以 NOI Linux 所使用的 Ubuntu 20.04.1 中，ST3 的数据目录为 `$HOME/用户名/.config/sublime-text-3`，ST4 的数据目录为 `$HOME/用户名/.config/sublime-text`，使用的具体规则同 Windows 环境。
```suggestion
    在以 NOI Linux 所使用的 Ubuntu 20.04.1 中，ST3 的数据目录为 `$HOME/.config/sublime-text-3`，ST4 的数据目录为 `$HOME/.config/sublime-text`，使用的具体规则同 Windows 环境。
```
`$HOME` 就已经是 `/home/用户名` 了

2021-09-10 02:48 UTC, CoelacanthusHex commented
@ToUNVRSe please resolve change requests and conflicts

2021-10-02 07:58 UTC, CoelacanthusHex approved these changes

2021-10-02 09:58 UTC, Enter-tainer approved these changes
辛苦

2021-10-02 09:58 UTC, merged