增加枚举页面复杂度分析
OI-wiki/OI-wiki pull request #3192
Opened 2021-05-25 15:11 UTC by qiqistyle

请管理员审核一下

2021-05-25 15:14 UTC, Xeonacid commented
请注意不要覆盖以前的author

2021-05-25 15:36 UTC, qiqistyle commented on docs/basic/enumerate.md
> +    算法的时间复杂度分析 $unordered\_map$ 的底层实现是个类似于链表查询效率类似于数组每次查询的时间复杂度为 $O(1)$, 这个算法中只要遍历 a 数组 2 遍就可以求出最终结果，没有循环嵌套所以实现的时间复杂度为 $O(n)$, 空间复杂度在 数组 $a$ 的数互不相同则 $unordered\_map$ 的空间用了 $n$ 个 故空间复杂度为 $O(n)$, 在这个题目
ok thanks

2021-05-26 01:28 UTC, qiqistyle commented
请管理员帮忙看一下

2021-05-26 08:58 UTC, Early0v0 requested changes
- 有错别字
- 有些地方忘记加 LaTeX
- 中英文间请添加空格
- 复杂度分析请不要直接跟在原先的段后，建议写个小标题

2021-05-26 14:03 UTC, ksyx requested changes

2021-05-26 14:03 UTC, ksyx commented on docs/basic/enumerate.md
> +    unordered_map<int, int> mp;
unordered_map 是 [since cpp11](https://en.cppreference.com/w/cpp/container/unordered_map) 的，OI 中并不适用，不建议做此修改

2021-05-26 14:03 UTC, ksyx commented on docs/basic/enumerate.md
> +    当 $i=1$ 时下一层循环 $if$ 语句执行 1 次，$i=2$ 时下一层循环 $if$ 语句执行两次，到 $i=n$ 是 $if$ 语句执行 $n$ 次，利用求和公式 $1+2+\cdots+n= (n+1)*n/2$ 故时间复杂度为 $O(n^2)$，空间复杂度还是为 $O(1)$。
参考格式手册。

2021-05-26 14:13 UTC, qiqistyle commented on docs/basic/enumerate.md
> +    时间复杂度分析第一个循环执行 $n$ 次，每执行一次第一层循环第二层循环需要执行 $n$ 次故时间复杂度为 $O(n^2)$，空间复杂度由于数组 $a$ 为输入数组则变量 $ans$ 为用户定义变量为常量故空间复杂的为 $O(1)$。
确认空间复杂度计算是什么意思呢？

2021-05-28 02:06 UTC, qiqistyle commented
请管理员有空审核一下

2021-05-28 04:18 UTC, Early0v0 commented on docs/basic/enumerate.md
> +#### **算法优化**
这里不需要加粗

2021-05-28 04:18 UTC, Early0v0 commented on docs/basic/enumerate.md
> +算法的时间复杂度分析 对 `a ` 数组遍历了一遍就能完成题目要求，当 `n` 足够大的时候时间复杂度为 $O(n)$，算法的空间复杂度分析，当 `MAXN` 足够大的时候空间复杂度为 $O(MAXN)$。
```suggestion
- 时间复杂度分析：对 $a$ 数组遍历了一遍就能完成题目要求，当 $n$ 足够大的时候时间复杂度为 $O(n)$。
- 空间复杂度分析：当 $MAXN$ 足够大的时候空间复杂度为 $O(MAXN)$。
```

2021-05-28 07:46 UTC, qiqistyle commented
ok ,请管理员有空审核一下，thanks

2021-05-28 07:51 UTC, Enter-tainer commented
@qiqistyle 你好 每次修改后，editor都会自动收到邮件，不需要手动回复

2021-05-28 09:25 UTC, Early0v0 commented on docs/basic/enumerate.md
> +#### 复杂度分析
复杂度分析应该再增加一级标题

2021-05-28 09:25 UTC, Early0v0 commented on docs/basic/enumerate.md
> +#### 复杂度分析
同上

2021-05-28 09:25 UTC, Early0v0 commented on docs/basic/enumerate.md
> +#### 复杂度分析
同上

2021-05-29 11:22 UTC, Early0v0 commented
呃，可能我没表达清楚。

请把 4 级标题改成 5 级而并非 3 级（

2022-03-13 11:00 UTC, xyf007 requested changes

2022-03-24 19:07 UTC, Saisyc reviewed
if语句不宜写作$if$语句

2022-08-07 04:09 UTC, Great-designer commented
这个的conflicts涉及很多代码

2022-08-07 04:17 UTC, Great-designer commented
很好。conflicts似乎没了。

2022-08-07 04:22 UTC, qiqistyle commented
各位老哥好，我真的很感动这是我一年前的pr。一年里我这个pr被关闭又被打开，看到你们近期还在解决我提交pr真的觉得这个社区好牛逼，远古pr都在认真维护。

2022-08-07 08:03 UTC, Konano requested changes

2022-08-07 08:03 UTC, Konano commented on docs/basic/enumerate.md
> +- 空间复杂度分析：当 $MAXN$ 足够大的时候空间复杂度为 $O(MAXN)$。
这里的 MAXN 需要修改，O(MAXN) 可以被理解成 M*A*X*N

2022-08-07 08:05 UTC, Konano commented on docs/basic/enumerate.md
> +- 空间复杂度分析：当 $MAXN$ 足够大的时候空间复杂度为 $O(MAXN)$。
主要我也不知道正确写法是什么……

2022-08-07 09:47 UTC, Early0v0 commented on docs/basic/enumerate.md
> +- 空间复杂度分析：当 $MAXN$ 足够大的时候空间复杂度为 $O(MAXN)$。
> 主要我也不知道正确写法是什么……

空间复杂度与 $MAXN$ 呈线性？

2022-08-08 09:16 UTC, Xeonacid commented on docs/basic/enumerate.md
> +- 空间复杂度分析：当 $MAXN$ 足够大的时候空间复杂度为 $O(MAXN)$。
$O(\textit{MAXN})$
多字母变量包括上面的MAXN都应该改成这样，格式手册里有写（

2022-08-09 13:39 UTC, Konano commented on docs/basic/enumerate.md
> +- 空间复杂度分析：当 $MAXN$ 足够大的时候空间复杂度为 $O(MAXN)$。
> O(MAXN) 多字母变量包括上面的MAXN都应该改成这样，格式手册里有写（

可是这里他想表达的是 `max(n)`？

2022-08-09 14:24 UTC, qiqistyle commented on docs/basic/enumerate.md
> +- 空间复杂度分析：当 $MAXN$ 足够大的时候空间复杂度为 $O(MAXN)$。
```
  bool met[MAXN * 2];
    memset(met, 0, sizeof(met));
    for (int i = 0; i < n; ++i) {
      if (met[MAXN - a[i]]) ans += 1;
      met[MAXN + a[i]] = true;
    }
```
根据这一段代码的分析，MAXN是输入数组a中的一个绝对值最大的数，代码想把这个值看做坐标轴的终点，如果输入a的的输入形式是 -1 0 1 那么MAXN为1，我想这个应该是这样吧

2022-08-10 00:01 UTC, Early0v0 commented on docs/basic/enumerate.md
> +- 空间复杂度分析：当 $MAXN$ 足够大的时候空间复杂度为 $O(MAXN)$。
> ```
>   bool met[MAXN * 2];
>     memset(met, 0, sizeof(met));
>     for (int i = 0; i < n; ++i) {
>       if (met[MAXN - a[i]]) ans += 1;
>       met[MAXN + a[i]] = true;
>     }
> ```
> 
> 根据这一段代码的分析，MAXN是输入数组a中的一个绝对值最大的数，代码想把这个值看做坐标轴的终点，如果输入a的的输入形式是 -1 0 1 那么MAXN为1，我想这个应该是这样吧

代码想把这个值看做坐标轴的原点，只是为了处理负数下标而把所有量向右平移 MAXN。

2022-09-13 09:04 UTC, Great-designer commented
一个月过去了

2022-10-02 05:16 UTC, Tiphereth-A commented on docs/basic/enumerate.md
> +- 空间复杂度分析：当 $MAXN$ 足够大的时候空间复杂度为 $O(MAXN)$。
看起来应该改成
```suggestion
- 空间复杂度分析：$O(\max(\{n\}\cup\{|x|:x\in a\}))$。
```

2022-10-03 06:34 UTC, Tiphereth-A commented
@Konano @ksyx @Early0v0

2022-10-06 07:26 UTC, Great-designer commented
也可以联系一个code owner来dismiss所有的changes request

2022-10-08 03:38 UTC, Early0v0 approved these changes

2022-12-16 13:02 UTC, Great-designer submitted a review, later dismissed

2022-12-27 15:38 UTC, Great-designer commented
> 也可以联系一个code owner来dismiss所有的changes request

考虑一下罢……

2023-01-01 02:48 UTC, Great-designer commented
@Konano @ksyx

2023-01-18 02:50 UTC, yanboishere approved these changes

2023-01-20 07:14 UTC, Great-designer commented
这个pr实在是太老了

2023-02-23 12:37 UTC, jifbt commented
我建议关掉重新开一个 pr，不知道可不可行

2023-02-24 07:55 UTC, Great-designer commented
> 我建议关掉重新开一个 pr，不知道可不可行

我认为可行。

2023-02-24 12:25 UTC, jifbt commented
@qiqistyle 你可以关掉这个 pr，重新开一个。

2023-02-27 07:14 UTC, Great-designer commented
> 你可以关掉这个 pr，重新开一个。

历时两年，原作者可能已经承担了过多的要求，要求原作者做这做那，到现在还不得妥善完结。

最好的处理办法还是请经验丰富的管理员来执行相关操作。

2023-02-27 07:49 UTC, qiqistyle commented
我是原作者，我认为可以Close掉这个PR，但是我的github上好像无法取消这个pr，请管理员帮忙取消一下吧，谢谢

2023-02-27 07:57 UTC, Ir1d commented
大家辛苦了，谢谢各位 🙏

2023-02-27 07:57 UTC, closed without merging