Update algorithm.md
OI-wiki/OI-wiki pull request #3220
Opened 2021-06-02 11:05 UTC by wlbksy

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论你是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈你的感受
3. 如果你熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2021-06-02 11:36 UTC, Xeonacid commented on docs/lang/csl/algorithm.md
> +- `find_end`：从前往后查找最后一次匹配的序号。`find_end(v.begin(), v.end(), value)`。
```suggestion
- `find_end`：从前往后查找最后一次匹配的位置。`find_end(v.begin(), v.end(), value)`。
```

2021-06-02 13:24 UTC, Backl1ght commented
我看[cpp_reference](https://en.cppreference.com/w/cpp/algorithm/find_end)里find_end是子串最后出现的位置啊

2021-06-02 13:39 UTC, wlbksy commented on docs/lang/csl/algorithm.md
> +- `find_end`：从前往后查找最后一次匹配的序号。`find_end(v.begin(), v.end(), value)`。
done

2021-06-02 13:40 UTC, wlbksy commented
> 我看[cpp_reference](https://en.cppreference.com/w/cpp/algorithm/find_end)里find_end是子串最后出现的位置啊

你看到没错，所以我要把master上有错的地方改成对的

2021-06-03 05:05 UTC, Early0v0 requested changes

2021-06-03 05:05 UTC, Early0v0 commented on docs/lang/csl/algorithm.md
> +- `find_end`：从前往后查找最后一次匹配的位置。`find_end(v.begin(), v.end(), value)`。
**请仔细查看 cppreference 的内容。**  
[std::find_end - cppreference.com](https://zh.cppreference.com/w/cpp/algorithm/find_end)

> 在范围 `[first, last)` 中搜索序列 `[s_first, s_last)` 的最后一次出现。

函数传参错误。

2021-06-03 05:38 UTC, wlbksy commented on docs/lang/csl/algorithm.md
> +- `find_end`：从前往后查找最后一次匹配的位置。`find_end(v.begin(), v.end(), value)`。
嗯，太麻烦了，不准备改这里了。我先关掉吧。

2021-06-03 05:39 UTC, closed without merging