Fix #2070
OI-wiki/OI-wiki pull request #3257
Opened 2021-06-27 03:51 UTC by nanmenyangde

将虚线加粗了。

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论你是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈你的感受
3. 如果你熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2021-06-27 04:02 UTC, ksyx commented
> order.svg
> data:image/png

2021-06-27 04:02 UTC, nanmenyangde commented
感觉SVG的画质就很糊，有点发虚。

2021-06-27 04:05 UTC, Enter-tainer commented
@nanmenyangde 请不要在矢量图中嵌入位图

2021-06-27 04:14 UTC, CoelacanthusHex requested changes
请不要

2021-06-27 04:14 UTC, CoelacanthusHex commented on docs/basic/images/order.svg
> +    href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA+gAAAFeCAYAAAAWrzWlAAAABGdBTUEAALGPC/xhBQAAACBjSFJN
请不要在SVG中插入位图

2021-06-27 04:16 UTC, nanmenyangde commented on docs/basic/images/order.svg
> +    href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA+gAAAFeCAYAAAAWrzWlAAAABGdBTUEAALGPC/xhBQAAACBjSFJN
啊（发现了

2021-06-27 04:17 UTC, nanmenyangde commented on docs/basic/images/order.svg
> +    href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA+gAAAFeCAYAAAAWrzWlAAAABGdBTUEAALGPC/xhBQAAACBjSFJN
怎么rebase回去

2021-06-27 04:18 UTC, nanmenyangde commented
删了

2021-06-28 05:32 UTC, Early0v0 approved these changes
25% 及以上貌似都可见了

2021-06-28 12:02 UTC, nanmenyangde commented
@CoelacanthusHex 删完要review一下。

2021-07-02 12:30 UTC, Enter-tainer approved these changes

2021-07-02 12:31 UTC, Enter-tainer commented
@CoelacanthusHex 来看一下新图

2021-07-02 14:20 UTC, CoelacanthusHex approved these changes

2021-07-02 15:12 UTC, merged