tree-diameter: 消除歧义
OI-wiki/OI-wiki pull request #3299
Opened 2021-07-08 05:52 UTC by PeterlitsZo

原来是：记 y 到 t 的最短路首先与 theta(s, t) 相交的结点是 x。

修改为：记从 y 到 t 的路上，第一个也在路 theta(s,t) 上的结点是 x。

但是首先树上说路就可以了，说最短路没有必要，两个点只能有一条路。其次，路本来是无向的，由何来“首先”二字呢？修改为从 ... 到 ... 的路上，更符合想要表示的意思。后半句同理。

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论你是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈你的感受
3. 如果你熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2021-07-08 08:04 UTC, ouuan commented
你在哪学过“路”的严格定义吗..可以参考 https://oi-wiki.org/graph/concept/#_5。但是路径相关的概念大家用的都不一样，所以“最短路”是最没有歧义的，比如说，如果是从 y 到 t 的途径，就不一定是最短的那条。

再怎么也不应该用“路”吧，别说严格定义，我个人从来没听过这种不带“径”的说法..

2021-07-08 08:10 UTC, sshwy commented
其实 主要的问题是，原文没有【歧义】，只是描述得不符合一些人的习惯。

2021-07-08 08:57 UTC, PeterlitsZo commented
尝试修改得更加严谨。

2021-07-09 11:35 UTC, Konano submitted a review, later dismissed

2021-07-10 02:35 UTC, Enter-tainer submitted a review, later dismissed

2021-07-10 02:39 UTC, sshwy requested changes
还有 netlify 渲染的 cases 为啥没有换行啊
不知道是写法错了还是 netlify 的问题

2021-07-10 02:39 UTC, sshwy commented on docs/graph/tree-diameter.md
> +![当 y 不在 s-t 上，且 z 也不在的情况](./iamges/tree-diameter.png)
```suggestion
![当 y 不在 s-t 上，且 z 也不在的情况](./images/tree-diameter.png)
```

2021-07-10 12:51 UTC, PeterlitsZo commented on docs/graph/tree-diameter.md
> +![当 y 不在 s-t 上，且 z 也不在的情况](./iamges/tree-diameter.png)
I am coming XD

2021-07-11 07:16 UTC, PeterlitsZo commented
这个 style bot 好烦欸

2021-07-11 07:17 UTC, PeterlitsZo commented
> 还有 netlify 渲染的 cases 为啥没有换行啊
> 不知道是写法错了还是 netlify 的问题

不知道修没有修好。感觉应该修好了 >_<。谢谢！！

2021-07-11 07:40 UTC, Enter-tainer commented
> > 还有 netlify 渲染的 cases 为啥没有换行啊
> > 不知道是写法错了还是 netlify 的问题
> 
> 不知道修没有修好。感觉应该修好了 >_<。谢谢！！

看起来修完之后 LaTeX 导出 build 失败了, 建议回退到之前的写法再看看是怎么回事.

2021-07-13 15:40 UTC, PeterlitsZo commented
原来是静态生成 SVG 吗...... 有无测试的地方啊？毕竟使用 xelatex 或者其他的 latex 渲染引擎都是没有问题的，我也没有用 amsmath 包啊...... 没有用过这种把数学东西渲染成 SVG 的东西。可以麻烦告知这玩意儿是个啥一哈吗，谢谢！我之后再改改。

2021-07-16 02:37 UTC, ouuan commented
像这种 bot 突然好了的可以 rebase master

2021-07-16 02:47 UTC, ouuan commented
dd4f340a9fd1745d0e2ccf793812dc6bff2bcd37 这个是 bug 吗，一次没 lint 完

2021-07-16 03:42 UTC, PeterlitsZo commented
我人傻了。我 LaTeX 公式也不至于写错啊，为什么改成了这个样子，只有 `\end{array}` 没有 `\begin{array}{l}`......

2021-07-16 04:26 UTC, ouuan commented
行间公式是不是 `$$` 要单独一行

2021-07-16 04:27 UTC, ouuan commented
话说这几个式子为啥要用大括号..

2021-07-16 06:02 UTC, PeterlitsZo commented
> 话说这几个式子为啥要用大括号..

因为是一组式子？不过现在应该是能编译成功了？太好了！

2021-07-19 03:25 UTC, sshwy approved these changes

2021-07-20 06:15 UTC, Enter-tainer approved these changes

2021-07-20 06:15 UTC, merged