feat(vscode): Configure clangd
OI-wiki/OI-wiki pull request #3317
Opened 2021-07-12 09:17 UTC by HeliumOI

这个PR中增加了用 clangd 实现 VS Code 代码补全等功能的内容。

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论你是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈你的感受
3. 如果你熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2021-07-12 12:15 UTC, Enter-tainer approved these changes

2021-07-14 08:00 UTC, sunmy2019 requested changes

2021-07-15 08:41 UTC, HeliumOI commented on docs/tools/editor/vscode.md
> +VS Code 的 C/C++ 插件也有自动补全等功能。但这些功能是由插件本身实现的，而非专业的 Language Server，在提示信息的易读程度的准确度等方面与 clangd 相比也稍逊一筹。所以我们有时会使用 clangd 代替 C/C++ 插件来实现代码自动补全等功能。
感谢指出，已改正

2021-07-17 14:40 UTC, Enter-tainer approved these changes

2021-07-25 13:28 UTC, StudyingFather approved these changes

2021-07-25 13:28 UTC, merged