refactor(graph/cut): Vectorize figures
OI-wiki/OI-wiki pull request #3326
Opened 2021-07-15 11:23 UTC by mcendu

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论你是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈你的感受
3. 如果你熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2021-07-15 12:39 UTC, CoelacanthusHex requested changes

2021-07-15 12:39 UTC, CoelacanthusHex commented on docs/graph/cut.md
>  红色箭头指向的就是割边。
```suggestion
红色的边就是割边。
```
根据实际变化对原文做适当修改

2021-07-15 13:34 UTC, CoelacanthusHex approved these changes

2021-07-17 03:38 UTC, StudyingFather approved these changes

2021-07-17 03:38 UTC, merged