refactor(graph/block-forest): Vectorize figures
OI-wiki/OI-wiki pull request #3327
Opened 2021-07-15 13:22 UTC by mcendu

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论你是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈你的感受
3. 如果你熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2021-07-15 14:03 UTC, CoelacanthusHex requested changes
似乎应该多加一张原图连线未断，方点不做连接的图（也就是原文图一的中间那副）

2021-07-15 14:03 UTC, CoelacanthusHex commented on docs/graph/images/block-forest2.tex
> +\begin{scope}[dashed]
```suggestion
\begin{scope}[rectangle]
```
使用方点似乎更加尊重原图的意思

2021-07-17 10:37 UTC, ksyx commented on docs/graph/images/block-forest4.tex
> +                child {node (I) {$9$}}
和原图比节点编号反了

2021-07-17 10:37 UTC, ksyx commented on docs/graph/images/block-forest5.tex
> +                child {node (I) {$9$}}
同，节点编号貌似反了

2021-07-17 10:37 UTC, ksyx commented on docs/graph/images/block-forest2.tex
> +\begin{scope}[rectangle]
两节点连线上的矩形是否方便旋转 30 度左右使得边与节点连线平行 🤔 
另外这张图中使用灰色做边的颜色是什么考虑呢

2021-07-17 11:45 UTC, CoelacanthusHex commented on docs/graph/images/block-forest2.tex
> +\begin{scope}[rectangle]
灰色是考虑的原图的边吧

2021-07-18 01:21 UTC, ksyx commented on docs/graph/images/block-forest2.tex
> +\begin{scope}[rectangle]
嗯 但是好像之前看的时候原图和重置图不太能对应上

2021-07-18 12:05 UTC, mcendu commented on docs/graph/images/block-forest2.tex
> +\begin{scope}[rectangle]
使用灰色作边大概是为了减弱原图边的存在感吧

2021-08-04 14:35 UTC, CoelacanthusHex submitted a review, later dismissed

2021-08-08 13:23 UTC, ksyx reviewed
(suggestion)

2021-08-08 13:23 UTC, ksyx commented on docs/graph/images/block-forest2.tex
> +    \node (FB) at (-0.75,-0.5) {};
```suggestion
    \node (FB) [rotate=27] at (-0.75,-0.5) {};
```

2021-09-14 09:30 UTC, CoelacanthusHex approved these changes

2021-09-16 05:37 UTC, Enter-tainer approved these changes

2021-09-17 16:05 UTC, StudyingFather commented
?ping @ksyx 
来 review 一下看看还有没有啥需要更改的地方 :thinking:

2021-09-17 17:32 UTC, ksyx commented
> ?ping @ksyx
> 来 review 一下看看还有没有啥需要更改的地方 🤔

感觉没有大问题？

2021-09-18 00:14 UTC, merged