feat(contest/resources): Add Introduction of HydroOJ
OI-wiki/OI-wiki pull request #3368
Opened 2021-07-26 04:43 UTC by HeliumOI

增加了对 [HydroOJ](https://hydro.ac/) 的介绍

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论你是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈你的感受
3. 如果你熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2021-07-26 05:45 UTC, undefined-moe commented
纠正：2020年已经上线，只不过当时跑在非标准端口也没人知道（xs

2021-07-26 05:53 UTC, HeliumOI commented
> 纠正：2020年已经上线，只不过当时跑在非标准端口也没人知道（xs

所以说需要更正为“始于2020年”吗（

2021-07-26 05:54 UTC, undefined-moe commented
那得取决于 `始于` 是指 `投入使用` 还是 `面向大众开放` （）

2021-07-28 06:07 UTC, Konano submitted a review, later dismissed

2021-07-28 14:59 UTC, Xeonacid requested changes
请按照字典序排序

2021-07-29 13:32 UTC, Xeonacid approved these changes
thx

2021-07-30 00:52 UTC, Early0v0 approved these changes

2021-07-30 00:53 UTC, merged