增加数位dp内容
OI-wiki/OI-wiki pull request #3455
Opened 2021-08-14 04:07 UTC by Alphnia

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论你是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈你的感受
3. 如果你熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2021-08-14 05:02 UTC, Xeonacid commented
以后在pr所在分支更新即可，不需要新开pr

2021-08-14 05:44 UTC, Konano requested changes
「参考资料」部分页面标题不规范，请重新修改。

2021-08-14 07:52 UTC, Marcythm commented on docs/dp/number.md
> +# 一、介绍
```suggestion
## 简介
```

2021-08-14 07:52 UTC, Marcythm commented on docs/dp/number.md
> +# 一、介绍
wiki 中每个页面的一级标题是由根目录下 mkdocs.yml 中的 title 决定的，页面内的标题从二级标题开始。
（[格式手册-文档的基本格式要求](https://oi-wiki.org/intro/format/#_4): 不要使用如 `<h1>` 或者 `# 标题` 的一级标题

2021-08-14 07:52 UTC, Marcythm commented on docs/dp/number.md
> +4、上界很大（比如 1e18），暴力枚举验证会超时
```suggestion
1. 要求统计满足一定条件的数的数量（即，最终目的为计数）；

2. 这些条件经过转化后可以使用「数位」的思想去理解和判断；

3. 输入会提供一个数字区间（有时也只提供上界）来作为统计的限制；

4. 上界很大（比如 $10^{18}$ ），暴力枚举验证会超时。
```

2021-08-14 07:52 UTC, Marcythm commented on docs/dp/number.md
> +4、上界很大（比如 1e18），暴力枚举验证会超时
此处应使用 markdown 列表，另标点符号的使用参见[格式手册](https://oi-wiki.org/intro/format/#_5)

2021-08-14 07:52 UTC, Marcythm commented on docs/dp/number.md
> +考虑人类数数（shǔ  shù）的方式，最朴素的数数就是从小到大开始依次加一。但我们发现对于位数比较多的数，这样的过程中有许多重复的部分，就比如，从 7000 数到 7999、从 8000 数到 8999、和从 9000 数到 9999 的过程非常相似，它们都是后三位从 000 变到 999，不一样的地方只有千位这一位，所以我们可以把这些过程归并起来，将这些过程中产生的计数答案也都存在一个通用的
```suggestion
考虑人类计数的方式，最朴素的计数就是从小到大开始依次加一。但我们发现对于位数比较多的数，这样的过程中有许多重复的部分。例如，从 7000 数到 7999、从 8000 数到 8999、和从 9000 数到 9999 的过程非常相似，它们都是后三位从 000 变到 999，不一样的地方只有千位这一位，所以我们可以把这些过程归并起来，将这些过程中产生的计数答案也都存在一个通用的数组里。此数组根据题目具体要求设置状态，用递推/dp 的方式进行状态转移。
```
一些语言上的建议。将「数数」改为「计数」应当可以更好地表达原意？

2021-08-14 07:52 UTC, Marcythm commented on docs/dp/number.md
> +数位 dp 中通常利用常规计数问题技巧，比如把一个区间内的答案拆成两部分相减，最终答案是：${ans_{[0,r]}-ans_{[0,l-1]}}$
```suggestion
数位 dp 中通常会利用常规计数问题技巧，比如把一个区间内的答案拆成两部分相减（即 $ans_{[l, r]} = ans_{[0, r]}-ans_{[0, l - 1]}$
```

2021-08-14 07:52 UTC, Marcythm commented on docs/dp/number.md
> +那么有了通用答案数组，接下来就是统计答案。统计答案可以选择记忆化搜索，也可以选择循环。为了不遗漏地统计所有不超过上限的答案，要从高到低枚举每一位，再考虑每一位都可以填哪些数字，最后利用通用答案数组统计答案。
```suggestion
那么有了通用答案数组，接下来就是统计答案。统计答案可以选择记忆化搜索，也可以选择循环迭代递推。为了不重不漏地统计所有不超过上限的答案，要从高到低枚举每一位，再考虑每一位都可以填哪些数字，最后利用通用答案数组统计答案。
```

2021-08-14 07:52 UTC, Marcythm commented on docs/dp/number.md
> +# 二、例题
```suggestion
## 例题
```

2021-08-14 07:52 UTC, Marcythm commented on docs/dp/number.md
> +### 解法 $1$:
此处其实不建议使用 markdown 标题，因为例题的题面都是折叠可选的，题解应当也折叠可选。
可参考[格式手册-Markdown 格式与主题扩展格式要求](https://oi-wiki.org/intro/format/#markdown)中的嵌套折叠样式

2021-08-14 07:52 UTC, Marcythm commented on docs/dp/number.md
> +### 解法 $2$:
同上，建议去掉标题，改为嵌套折叠样式

2021-08-14 07:52 UTC, Marcythm commented on docs/dp/number.md
> +##
```suggestion
```

2021-08-14 07:52 UTC, Marcythm commented on docs/dp/number.md
> +### 解法：
同上

2021-08-14 07:52 UTC, Marcythm commented on docs/dp/number.md
> +需要额外注意的是，这道题的记忆化部分，不能用 memset，否则会导致超时。
```suggestion
需要额外注意的是，这道题的记忆化部分，不能用 `memset`，否则会导致超时。
```

2021-08-14 07:52 UTC, Marcythm commented on docs/dp/number.md
> +???+note "例5.[P3311 数数 ](https://www.luogu.com.cn/problem/P3311)"
```suggestion
???+note "例5. [P3311 数数](https://www.luogu.com.cn/problem/P3311)"
```

2021-08-14 07:52 UTC, Marcythm commented on docs/dp/number.md
> +### 解法
同上

2021-08-14 07:52 UTC, Marcythm commented on docs/dp/number.md
>  ## 几道练习题
```suggestion
## 习题
```

2021-08-14 07:52 UTC, Marcythm commented on docs/dp/number.md
> +[add 数位 DP·Issue #2440·OI-wiki/OI-wiki (github.com)](https://github.com/OI-wiki/OI-wiki/issues/2440)
```suggestion
## References

[小学生都能看懂的数位 dp - y2823774827y](https://www.cnblogs.com/y2823774827y/p/10301145.html)

[数位 dp 介绍 - Young-children](https://www.cnblogs.com/young-children/p/11327950.html)

[数位 dp 总结 之 从入门到模板](https://blog.csdn.net/wust_zzwh/article/details/52100392)
```

2021-08-14 09:19 UTC, Marcythm commented on docs/dp/number.md
> +???+note "参考代码"
```suggestion
现在来考虑前导 $0$，第 $i$ 位为前导 $0$ 时，实际上我们多算了填满 $i-1$ 位的次数，减去就好。

???+note "参考代码"
```

2021-08-14 09:19 UTC, Marcythm commented on docs/dp/number.md
> +### 方法 $1$:
```suggestion
方法一：
```
> 请尽量避免在标题中使用 MathJax 公式，无论是几级标题。在标题中使用公式有可能会导致目录显示错误。
另此处不适合使用标题，因为与内容结构层级不符（标题「例题」与标题「方法 1」间应还有一个「例题 1」层级

2021-08-14 09:19 UTC, Marcythm commented on docs/dp/number.md
> +???+note "参考代码"
```suggestion
详见代码注释

???+note "参考代码"
```

2021-08-14 09:19 UTC, Marcythm commented on docs/dp/number.md
> +    题面大意：假如手写下 $[n,m]$ 之间所有整数，会有多少数看起来和在镜子里看起来一模一样？$n,m<10^{44};T<10^5$
```suggestion
    题面大意：假如手写下 $[n,m]$ 之间所有整数，会有多少数看起来和在镜子里看起来一模一样？（ $n,m<10^{44}, T<10^5$ )
```

2021-08-14 09:19 UTC, Marcythm commented on docs/dp/number.md
> +???+note "参考代码"
```suggestion
需要额外注意的是，这道题的记忆化部分，不能用 `memset`，否则会导致超时。

???+note "参考代码"
```

2021-08-14 09:19 UTC, Marcythm commented on docs/dp/number.md
> +    $1≤n<10^1201，1 \leq m \leq 100，1 \leq \sum_{i = 1}^m |s_i| \leq 1500，\min_{i = 1}^m |s_i| \geq 1$，其中 $|s_i|$ 表示字符串 $s_i$ 的长度。$n$ 没有前导 $0$，但是 $s_i$ 可能有前导 $0$。
```suggestion
    $1≤n<10^{1201}，1 \leq m \leq 100，1 \leq \sum_{i = 1}^m |s_i| \leq 1500，\min_{i = 1}^m |s_i| \geq 1$，其中 $|s_i|$ 表示字符串 $s_i$ 的长度。$n$ 没有前导 $0$，但是 $s_i$ 可能有前导 $0$。
```

2021-08-14 09:19 UTC, Marcythm commented on docs/dp/number.md
> +???+note "参考代码"
```suggestion
转移很好想，详见代码 `main` 函数部分。

???+note "参考代码"
```

2021-08-14 10:37 UTC, Marcythm commented
回头看一看 comments 啊 / 擦汗
别一直埋头 commit（

2021-08-14 10:37 UTC, Marcythm commented
二叉树页面上的代码块语法写错了，应该是三个 `

2021-08-14 10:58 UTC, Xeonacid commented on docs/dp/number.md
> +[BZOJ 3679 数字之积](https://www.lydsy.com/JudgeOnline/problem.php?id=3679)
有其他OJ可以提交吗，没有的话建议删掉，不要放一个不存在的OJ（

2021-08-14 11:06 UTC, Alphnia commented on docs/dp/number.md
> +[BZOJ 3679 数字之积](https://www.lydsy.com/JudgeOnline/problem.php?id=3679)
好

2021-08-14 11:06 UTC, Xeonacid commented on docs/graph/tree-basic.md
> +2. 先确定根节点，然后根据中序遍历，在根左边的为左子树，根右边的为右子树
```suggestion
2. 先确定根节点，然后根据中序遍历，在根左边的为左子树，根右边的为右子树。
```

2021-08-14 11:15 UTC, Marcythm commented on docs/dp/number.md
> +    $1≤n<10^{1201}，1 \leq m \leq 100，1 \leq \sum_{i = 1}^m |s_i| \leq 1500，\min_{i = 1}^m |s_i| \geq 1$，其中 $|s_i|$ 表示字符串 $s_i$ 的长度。$n$ 没有前导 $0$，但是 $s_i$ 可能有前导 $0$。
```suggestion
    $1 \leq n<10^{1201}，1 \leq m \leq 100，1 \leq \sum_{i = 1}^m |s_i| \leq 1500，\min_{i = 1}^m |s_i| \geq 1$，其中 $|s_i|$ 表示字符串 $s_i$ 的长度。$n$ 没有前导 $0$，但是 $s_i$ 可能有前导 $0$。
```

2021-08-14 11:20 UTC, ksyx commented
不建议在 master branch 上工作
在多个 branch 上工作还可以同时开好几个 pr 方便 Review

thx

2021-08-14 11:23 UTC, ksyx reviewed
> `docs/graph/images/tree-basic-Postorder.png`

建议文件名全小写

2021-08-14 11:23 UTC, ksyx commented on docs/dp/plug.md
> +    题目大意：有一个 N\*M 的图，每个格子有独立概率 p 变成障碍物。你要从迷宫左上角走到迷宫右下角。求每个格子成为一个 **有解迷宫（即起点终点四联通）** 中的障碍物的概率。N&lt;= 5，M&lt;= 6
题面请是用数学公式；基本上 `题目大意：` 这个 header 是不需要加的

下同

2021-08-14 11:23 UTC, ksyx commented on docs/dp/plug.md
> +    题目大意：一块 $N*M$ 的电路板，上面有些位置是电线不能走的障碍，给定 $K$ 个格子对，要求每对格子都有电线相连，且电线之间互不相交。具体来说：为了保证电路线不相交，可以一条电路线从上边界进入当前格子，从左边界离开这个格子，另外一条电路线可以从下边界进入格子，从右边界出去。（需要注意的是：电路线本身是没有方向感念的，即格子对描述的边关系是无向边。）求满足要求的最短电线长度和方案数。
```suggestion
    题目大意：一块 $N\times M$ 的电路板，上面有些位置是电线不能走的障碍，给定 $K$ 个格子对，要求每对格子都有电线相连，且电线之间互不相交。具体来说：为了保证电路线不相交，可以一条电路线从上边界进入当前格子，从左边界离开这个格子，另外一条电路线可以从下边界进入格子，从右边界出去。（需要注意的是：电路线本身是没有方向感念的，即格子对描述的边关系是无向边。）求满足要求的最短电线长度和方案数。输出对 25619849 取余数后的结果。
```
下同

2021-08-14 11:25 UTC, Alphnia commented
> 不建议在 master branch 上工作
> 在多个 branch 上工作还可以同时开好几个 pr 方便 Review
> 
> thx

哦哦还可以这样啊，我试试 thx

2021-08-14 11:27 UTC, ksyx commented on docs/dp/number.md
> +数位 dp：用来解决一类特定问题，这种问题比较好辨认，一般具有这几个特征：
DP 用大写吧

2021-08-14 11:27 UTC, ksyx commented on docs/dp/number.md
> +???+note " 例1 [P2602 数字计数](https://www.luogu.com.cn/problem/P2602)"
中英（数字）空格

2021-08-14 11:27 UTC, ksyx commented on docs/dp/number.md
> +    #include <cstdio>  //code by y2823774827y
不是很确认这样会不会影响阅读体验

2021-08-14 11:27 UTC, ksyx commented on docs/dp/number.md
> +      }
建议 // 后跟一个空格 下同

2021-08-14 11:27 UTC, ksyx commented on docs/dp/number.md
> +没有 4 的话在枚举的时候判断一下，不枚举 4 就可以保证状态合法了，所以这个约束没有记忆化的必要，而对于 62 的话，涉及到两位，当前一位是 6 或者不是 6 这两种不同情况我计数是不相同的，所以要用状态来记录不同的方案数。$dp[pos][sta]$ 表示当前第 pos 位，前一位是否是 6 的状态，这里 sta 只需要取 0 和 1 两种状态就可以了，不是 6 的情况可视为同种，不会影响计
用到的变量请使用数学公式并用 mathit 套变量名

2021-08-14 11:33 UTC, Xeonacid requested changes

2021-08-14 11:33 UTC, Xeonacid commented on docs/graph/tree-basic.md
> +![preorder](images/tree-basic-Preorder.png)
https://blog.csdn.net/weixin_43357638/article/details/99730284
> 版权声明：本文为博主原创文章，遵循 CC 4.0 BY-SA 版权协议，转载请附上原文出处链接和本声明。

2021-08-14 11:33 UTC, Xeonacid commented on docs/dp/number.md
> +    #include <cstdio>  //code by y2823774827y
需要注意版权问题

2021-08-14 11:47 UTC, Alphnia commented on docs/dp/number.md
> +    #include <cstdio>  //code by y2823774827y
在文后reference中把这个代码所在的博客网址列出来就可以了吗？

2021-08-14 11:53 UTC, Alphnia commented on docs/dp/plug.md
> +    题目大意：有一个 N\*M 的图，每个格子有独立概率 p 变成障碍物。你要从迷宫左上角走到迷宫右下角。求每个格子成为一个 **有解迷宫（即起点终点四联通）** 中的障碍物的概率。N&lt;= 5，M&lt;= 6
这整篇文档的例题题面前面都有 ·题目大意：·😂

2021-08-14 12:02 UTC, Xeonacid commented on docs/dp/number.md
> +    #include <cstdio>  //code by y2823774827y
我没有在原博客中找到授权协议，需要联系原博主确认授权协议。
没有明确协议的情况下不建议使用。

2021-08-14 12:35 UTC, Alphnia commented on docs/graph/tree-basic.md
> +![preorder](images/tree-basic-Preorder.png)
请问这个版权声明加在哪里比较合适呢，放在最后参考资料里吗？

2021-08-14 12:40 UTC, Xeonacid commented on docs/graph/tree-basic.md
> +![preorder](images/tree-basic-Preorder.png)
可以参考下其他页面（搜索 e-maxx），文末加粗吧

2021-08-16 08:25 UTC, Xeonacid commented on docs/graph/tree-basic.md
> +**本页面部分内容引用自博文 [二叉树：前序遍历、中序遍历、后续遍历](https://blog.csdn.net/weixin_43357638/article/details/99730284)，遵循 CC 4.0 BY-SA 版权协议**
```suggestion
**本页面部分内容引用自博文 [二叉树：前序遍历、中序遍历、后续遍历](https://blog.csdn.net/weixin_43357638/article/details/99730284)，遵循 CC 4.0 BY-SA 版权协议。**
```

2021-08-16 10:24 UTC, Xeonacid commented on docs/dp/number.md
> +    #define rep(i, a, b) for (int i = (a); i <= (b); ++i)
不要使用这样的 define，会降低可读性

2021-08-16 10:24 UTC, Xeonacid commented on docs/dp/number.md
> +??? note "参考代码"
```suggestion
???+ note "参考代码"
```

2021-08-16 10:26 UTC, Xeonacid commented on docs/dp/number.md
> +发现对于满 $\mathit{i}$ 位的数，所有数字出现的次数都是相同的，故设数组 $dp_i$ 为满 $\mathit{i}$ 位的数中每个数字出现的次数，此时暂时不处理前导 0。则有 $dp_i=10*dp_{i−1}+10^{i−1}$，这两部分前一个是来自前 $\mathit{i-1}$ 位数字的贡献，后一个是来自第 $\mathit{i}$ 位的数字的贡献。
```suggestion
发现对于满 $\mathit{i}$ 位的数，所有数字出现的次数都是相同的，故设数组 $dp_i$ 为满 $\mathit{i}$ 位的数中每个数字出现的次数，此时暂时不处理前导 0。则有 $dp_i=10 \times dp_{i−1}+10^{i−1}$，这两部分前一个是来自前 $\mathit{i-1}$ 位数字的贡献，后一个是来自第 $\mathit{i}$ 位的数字的贡献。
```

2021-08-17 05:37 UTC, Marcythm submitted a review, later dismissed
感觉差不多了（虽然可能还有一些小细节需要改，但我看了两遍着实没看出来

2021-08-17 06:08 UTC, Xeonacid commented on docs/dp/plug.md
> +    题目大意：现有一共 12 种图案的瓷砖，每种瓷砖数量给定。要求铺到一块可视为 $R\times C$ 网格图的矩形地板上，一个格子铺一块瓷砖，且左上角格子的中心与右下角格子的中心通过瓷砖图案上的线联通。$(2 ≤ R × C ≤ 15)$
```suggestion
    题目大意：现有一共 12 种图案的瓷砖，每种瓷砖数量给定。要求铺到一块可视为 $R\times C$ 网格图的矩形地板上，一个格子铺一块瓷砖，且左上角格子的中心与右下角格子的中心通过瓷砖图案上的线联通。$(2 \le R × C \le 15)$
```

2021-08-17 06:10 UTC, Xeonacid commented on docs/dp/plug.md
> +    题目大意：一块可视为 $N\times M$ 网格的蛋糕，现沿着格线将蛋糕切成数块，问有多少种不同的切割方法。切法相同当且仅当切成的每块蛋糕都形状相同且在同一位置上。$min(N,M)<=5, max(N,M)<=130$
```suggestion
    题目大意：一块可视为 $N\times M$ 网格的蛋糕，现沿着格线将蛋糕切成数块，问有多少种不同的切割方法。切法相同当且仅当切成的每块蛋糕都形状相同且在同一位置上。$min(N,M) \le 5, max(N,M) \le 130$
```

2021-08-17 06:11 UTC, Xeonacid commented on docs/dp/plug.md
> +    题目大意：有一个 $N\times M$ 的图，每个格子有独立概率 $\mathit{p}$ 变成障碍物。你要从迷宫左上角走到迷宫右下角。求每个格子成为一个 **有解迷宫（即起点终点四联通）** 中的障碍物的概率。N&lt;= 5，M&lt;= 6
```suggestion
    题目大意：有一个 $N\times M$ 的图，每个格子有独立概率 $\mathit{p}$ 变成障碍物。你要从迷宫左上角走到迷宫右下角。求每个格子成为一个 **有解迷宫（即起点终点四联通）** 中的障碍物的概率。N \le 5，M \le 6
```

2021-08-17 06:12 UTC, Xeonacid commented on docs/dp/number.md
> +???+note " 例 1 [P2602 数字计数](https://www.luogu.com.cn/problem/P2602)"
```suggestion
???+note " 例 1 [Luogu P2602 数字计数](https://www.luogu.com.cn/problem/P2602)"
```

2021-08-17 06:14 UTC, Xeonacid commented on docs/dp/number.md
> +其次，由于数值超过 long long 范围，所以 $[n,m]=[1,m]-[1,n-1]$ 不再适用（高精度太麻烦 qwq），而是需要对 n 是否合法进行判断，得出：$[n,m]=[1,m]-[1,n]+check(n)$
```suggestion
其次，由于数值超过 long long 范围，所以 $[n,m]=[1,m]-[1,n-1]$ 不再适用（高精度比较繁琐），而是需要对 $n$ 是否合法进行判断，得出：$[n,m]=[1,m]-[1,n]+check(n)$。
```

2021-08-17 06:14 UTC, Xeonacid commented on docs/dp/number.md
> +没有 4 的话在枚举的时候判断一下，不枚举 4 就可以保证状态合法了，所以这个约束没有记忆化的必要，而对于 62 的话，涉及到两位，当前一位是 6 或者不是 6 这两种不同情况我计数是不相同的，所以要用状态来记录不同的方案数。$dp[pos][sta]$ 表示当前第 $\mathit{pos}$ 位，前一位是否是 6 的状态，这里 $\mathit{sta}$ 只需要取 0 和 1 两种状态就可
```suggestion
没有 4 的话在枚举的时候判断一下，不枚举 4 就可以保证状态合法了，所以这个约束没有记忆化的必要，而对于 62 的话，涉及到两位，当前一位是 6 或者不是 6 这两种不同情况我计数是不相同的，所以要用状态来记录不同的方案数。$dp[pos,sta]$ 表示当前第 $\mathit{pos}$ 位，前一位是否是 6 的状态，这里 $\mathit{sta}$ 只需要取 0 和 1 两种状态就可以了，不是 6 的情况可视为同种，不会影响计数。
```

2021-08-17 08:53 UTC, Marcythm approved these changes

2021-08-17 09:28 UTC, Xeonacid approved these changes

2021-08-18 12:29 UTC, Konano approved these changes

2021-08-19 04:33 UTC, merged