Minimax算法和alpha-beta剪枝的讲解
OI-wiki/OI-wiki pull request #3458
Opened 2021-08-15 03:00 UTC by Alphnia

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论你是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈你的感受
3. 如果你熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2021-08-15 07:38 UTC, llh721113 commented
是α-β剪枝，太棒了

2021-08-16 16:06 UTC, Marcythm commented on docs/search/minimax-ab.md
> +### $\alpha-\beta$ 剪枝
```suggestion
## alpha-beta 剪枝
```
标题中不要使用数学公式环境，以及是从二级标题开始而不是三级标题

2021-08-16 16:06 UTC, Marcythm commented on docs/search/minimax-ab.md
> +??? + note "参考代码"
```suggestion
???+ note "参考代码"
```

2021-08-16 16:06 UTC, Marcythm commented on docs/search/minimax-ab.md
> +??? + note "参考代码"
这里不能空格，不然样式会失效

2021-08-16 16:06 UTC, Marcythm commented on docs/search/minimax-ab.md
> +
```suggestion
    ```cpp
```

2021-08-16 16:06 UTC, Marcythm commented on docs/search/minimax-ab.md
> +
```suggestion
    ```
```

2021-08-16 16:06 UTC, Marcythm commented on docs/search/minimax-ab.md
> +
记得加一下代码环境

2021-08-16 16:06 UTC, Marcythm commented on docs/search/minimax-ab.md
> +### 参考资料
```suggestion
## References
```

2021-08-16 16:06 UTC, Marcythm commented on docs/search/minimax-ab.md
> +### 参考资料
请使用二级标题

2021-08-16 16:06 UTC, Marcythm commented on docs/search/minimax-ab.md
> +### Minimax 算法
```suggestion
## Minimax 算法
```

2021-08-16 17:03 UTC, Xeonacid commented on docs/search/minimax-ab.md
> +### 参考资料
为啥要改英文（

2021-08-16 17:05 UTC, Xeonacid requested changes
需要处理 git，去掉非本 pr 的页面，否则会与 #3455 造成 conflict

2021-08-17 02:53 UTC, Xeonacid commented on docs/search/minimax-ab.md
> +此页面将简要介绍 minimax 算法和 $\alpha-\beta$ 剪枝
```suggestion
此页面将简要介绍 minimax 算法和 $\alpha-\beta$ 剪枝。
```

2021-08-17 02:54 UTC, Xeonacid commented on docs/search/minimax-ab.md
> +朴素的 minmax 算法常常需要构建一棵庞大的搜索树，时间和空间复杂度都将不能承受。而 $\alpha-\beta$ 剪枝就是利用搜索树每个节点取值的上下界来对 Minimax 进行剪枝优化的一种方法。
```suggestion
朴素的 Minimax 算法常常需要构建一棵庞大的搜索树，时间和空间复杂度都将不能承受。而 $\alpha-\beta$ 剪枝就是利用搜索树每个节点取值的上下界来对 Minimax 进行剪枝优化的一种方法。
```

2021-08-17 05:38 UTC, Marcythm commented on docs/search/minimax-ab.md
> +### 参考资料
我也不知道，但是之前 pr nano 都说这样不规范

2021-08-17 05:42 UTC, Marcythm commented on docs/search/minimax-ab.md
> +### 参考资料
不太懂，主要是我看到的页面都是英文的，没见过中文的
不过中文也行，但标题级数反正要改

2021-08-17 06:07 UTC, Xeonacid commented on docs/search/minimax-ab.md
> +### 参考资料
搜索一下你会发现中文比英文多的

2021-08-17 08:54 UTC, Marcythm submitted a review, later dismissed

2021-08-17 09:26 UTC, Xeonacid approved these changes

2021-08-19 06:09 UTC, Marcythm commented
哦等一下，还没有在站点配置里添加这个页面呢（就是在目录里会找不到这个页面）

2021-08-22 06:07 UTC, Marcythm submitted a review, later dismissed

2021-08-22 08:12 UTC, Xeonacid commented on mkdocs.yml
> +    - Alpha-Beta 剪枝: search/minimax-ab.md
标题与链接最好对应？

2021-08-23 16:36 UTC, Xeonacid approved these changes

2021-09-04 14:46 UTC, Marcythm approved these changes

2021-09-04 14:48 UTC, merged