增加点分治例题内容 折叠长代码
OI-wiki/OI-wiki pull request #3459
Opened 2021-08-15 10:58 UTC by Alphnia

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论你是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈你的感受
3. 如果你熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2021-08-16 00:58 UTC, Early0v0 commented on docs/graph/tree-divide.md
> +求出所有的 $sum_i$  $1 \le n, c_i \le 10^5$
```suggestion
对所有的 $1\leq i\leq n$，求 $sum_i$（$1 \le n, c_i \le 10^5$）
```

2021-08-16 03:57 UTC, Marcythm requested changes

2021-08-16 03:57 UTC, Marcythm commented on docs/graph/tree-divide.md
> +??? + note "[例题 2 P2664 树上游戏](https://www.luogu.com.cn/problem/P2664)"
```suggestion
???+ note "[例题 2 P2664 树上游戏](https://www.luogu.com.cn/problem/P2664)"
```

2021-08-16 03:57 UTC, Marcythm commented on docs/graph/tree-divide.md
> +??? + note "[例题 2 P2664 树上游戏](https://www.luogu.com.cn/problem/P2664)"
折叠样式这里不要加空格，否则折叠不了的（

2021-08-16 03:57 UTC, Marcythm commented on docs/graph/tree-divide.md
> +??? note "参考代码"
> 使用 `???` 或 `!!!` 开头的 Details 语法时，每一行要包括在 Details 语法的文本框的文本，开头必须至少有 4 个空格。

2021-08-16 03:57 UTC, Marcythm commented on docs/graph/tree-divide.md
> +??? note "参考代码"
看网页预览可以看到这里折叠是失效的，要修改一下

2021-08-16 03:57 UTC, Marcythm commented on docs/graph/tree-divide.md
> +```c++
这里代码折叠问题同上

2021-08-16 16:02 UTC, Marcythm reviewed
看起来把这个改掉以后就基本没啥问题了

2021-08-16 16:02 UTC, Marcythm commented on docs/graph/tree-divide.md
> +    一棵每个节点都给定颜色的树，定义 $s(i,j)$ 为 $\mathit{i}$ 到 $\mathit{j}$ 的颜色数量，$sum_{i}=\sum_{j=1}^n s(i,j)$ 对所有的 $1\leq i\leq n$，求 $sum_i$（$1 \le n, c_i \le 10^5$）
```suggestion
    一棵每个节点都给定颜色的树，定义 $s(i,j)$ 为 $\mathit{i}$ 到 $\mathit{j}$ 的颜色数量，$sum_{i}=\sum_{j=1}^n s(i,j)$。对所有的 $1\leq i\leq n$，求 $sum_i$（$1 \le n, c_i \le 10^5$）
```

2021-08-16 17:08 UTC, Xeonacid requested changes
多字母变量需要加 \mathit{}

2021-08-16 17:08 UTC, Xeonacid commented on docs/graph/tree-divide.md
> +??? note "[例题 3 P2664 树上游戏](https://www.luogu.com.cn/problem/P2664)"
```suggestion
??? note "[例题 3 Luogu P2664 树上游戏](https://www.luogu.com.cn/problem/P2664)"
```

2021-08-16 17:08 UTC, Xeonacid commented on docs/graph/tree-divide.md
> +??? note " 例题 1 [luogu P3806【模板】点分治 1](https://www.luogu.com.cn/problem/P3806)"
例题链接格式最好统一一下

2021-08-16 17:11 UTC, Xeonacid commented on docs/graph/tree-divide.md
> +    一棵每个节点都给定颜色的树，定义 $s(i,j)$ 为 $\mathit{i}$ 到 $\mathit{j}$ 的颜色数量，$sum_{i}=\sum_{j=1}^n s(i,j)$ 对所有的 $1\leq i\leq n$，求 $sum_i$（$1 \le n, c_i \le 10^5$）
```suggestion
    一棵每个节点都给定颜色的树，定义 $s(i,j)$ 为 $\mathit{i}$ 到 $\mathit{j}$ 的颜色数量，$sum_{i}=\sum_{j=1}^n s(i,j)$。对所有的 $1\leq i\leq n$，求 $sum_i$。（$1 \le n, c_i \le 10^5$）
```

2021-08-16 17:12 UTC, Xeonacid commented on docs/graph/tree-divide.md
> +      clear(u, 0, 0);                      //清空的同时统计答案
```suggestion
      clear(u, 0, 0);                      // 清空的同时统计答案
```

2021-08-19 06:09 UTC, Marcythm approved these changes

2021-08-19 08:49 UTC, Xeonacid reviewed
需要 separate code

2022-07-15 00:17 UTC, shuzhouliu commented
> 需要 separate code

done

2022-07-15 00:27 UTC, shuzhouliu approved these changes

2022-07-15 00:34 UTC, Enter-tainer commented
请先回退bot的更改，然后merge一下当前的master分支

2022-07-15 00:56 UTC, shuzhouliu commented
<img width="593" alt="image" src="https://user-images.githubusercontent.com/64518651/179125380-bad750f6-a4a1-4e7b-bf36-22e503cb79a0.png">
emm

@24OI-bot stop linting please

2022-07-15 00:58 UTC, Enter-tainer commented
🌚🌚原作者已经不跟进了，建议你把他的分支偷过来一份到自己的仓库里面，然后重开pr

2022-07-15 01:00 UTC, shuzhouliu commented
> 🌚🌚原作者已经不跟进了，建议你把他的分支偷过来一份到自己的仓库里面，然后重开pr

这不太好吧

2022-07-15 01:17 UTC, closed without merging