add 旋转卡壳
OI-wiki/OI-wiki pull request #3484
Opened 2021-08-22 19:51 UTC by Alphnia

可能还需要添加内容

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论你是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈你的感受
3. 如果你熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2021-08-23 06:17 UTC, Marcythm commented on docs/geometry/rotating-calipers.md
> +旋转卡壳，基于凸包算法之上，通过在枚举凸包上某一条边，同时维护其他需要的点，能够在线性时间内求解如凸包直径、最小矩形覆盖等和凸包性质相关的问题。”旋转卡壳“是很形象的说法，因为根据我们枚举的边，可以从每个维护的点画出一条直线，我们的任务就是用这些直线把凸包卡住。边通常是按照向某一方向旋转的顺序来枚举，所以整个过程就是在边”旋转“，边”卡壳“。
「基于凸包算法之上」建议改为「建立在...的基础之上」或「基于...」（高中语文.jpg

2021-08-23 06:17 UTC, Marcythm commented on docs/geometry/rotating-calipers.md
> +给定平面上 $n$ 个点，求所有点对的最长距离。（$2\leq n \leq 50000,|x|,|y| \leq 10^4$)
```suggestion
给定平面上 $n$ 个点，求所有点对距离的最大值。（$2\leq n \leq 50000,|x|,|y| \leq 10^4$)
```
感觉原本的表述有点模糊🤔如果有更好的改法也没问题

2021-08-23 16:51 UTC, Xeonacid requested changes
需要删除本分支的minimax内容

2021-08-23 16:51 UTC, Xeonacid commented on docs/geometry/rotating-calipers.md
> +[Luogu P1452 Beauty Contest G](https://www.luogu.com.cn/problem/P1452)
参考其他页面的例题格式，用 note 包起来

2021-08-23 16:51 UTC, Xeonacid commented on docs/geometry/rotating-calipers.md
> +[可能这里加张图配合讲解会更好，明天加]
没有ready for review的话请使用draft pr

2021-09-01 07:03 UTC, Marcythm approved these changes

2021-09-05 01:36 UTC, Xeonacid approved these changes

2021-09-05 05:58 UTC, Konano approved these changes

2021-09-06 02:59 UTC, merged