refactor(tools/wsl): Replaced figures with text and tweaked interaction examples
OI-wiki/OI-wiki pull request #3529
Opened 2021-09-13 14:18 UTC by mcendu

- 使用了 `$` 和 `#` 来区分是否开了 root。
- 将一系列的表和图改成了 markdown 形式。
- 安装中文字体的部分把微软字库换成了思源宋体和思源黑体。

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论你是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈你的感受
3. 如果你熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2021-09-13 14:20 UTC, Enter-tainer submitted a review, later dismissed

2021-09-13 15:34 UTC, CoelacanthusHex requested changes

2021-09-13 15:34 UTC, CoelacanthusHex commented on docs/tools/wsl.md
> +    The program 'gcc' is currently not installed. You can install it by typing:
表示在终端的输入输出用 \`\`\`console
下同

2021-09-13 17:57 UTC, ksyx reviewed
thx

2021-09-13 17:57 UTC, ksyx commented on docs/tools/wsl.md
> +# apt install  language-pack-zh-han* -y
```suggestion
# apt install language-pack-zh-han* -y
```

2021-09-13 17:57 UTC, ksyx commented on docs/tools/wsl.md
> +```
描述一下 # 和 $？

2021-09-13 17:57 UTC, ksyx commented on docs/tools/wsl.md
>  之后关闭 Ubuntu 并重启，系统就会变成中文。
🤔 这句话对 wsl 来说好怪

2021-09-13 17:57 UTC, ksyx commented on docs/tools/wsl.md
> +            <Ok>            <Cancel>
套 code block 里？

2021-09-13 17:57 UTC, ksyx commented on docs/tools/wsl.md
> +这是基础的 + NOI 官方要求环境，如有需要可以用 `apt install <程序名>` 来安装别的。
```suggestion
这里安装的是基础 + NOI 官方要求的环境，如有需要可以用 `apt install <程序名>` 来安装其它软件包。
```

2021-09-13 17:57 UTC, ksyx commented on docs/tools/wsl.md
> +    chtholly@SENIORIOUS:~$
写一下 # 和 $ 的区别
以及是不是 sudo 而不是 sudo su 更好一些

2021-09-14 06:52 UTC, mcendu commented on docs/tools/wsl.md
> +```
这部分我建议新开一页讲命令行（

2021-09-14 06:58 UTC, mcendu commented on docs/tools/wsl.md
> +```
个人认为这一块的描述应该放到[命令行](https://oi-wiki.org/tools/cmd/)下面讲

毕竟是另一页，所以以后再说

2021-09-14 07:06 UTC, mcendu commented on docs/tools/wsl.md
> +            <Ok>            <Cancel>
因为是文字界面所以套 code block 里了

2021-09-15 03:35 UTC, Early0v0 commented on docs/tools/wsl.md
> +运行 `sudo service xrdp restart`，然后去开始菜单，用 `localhost:qwq` 来访问。
话说用 `qwq` 不太好吧（

2021-09-15 12:00 UTC, ksyx commented on docs/tools/wsl.md
> +            <Ok>            <Cancel>
哦没注意到缩进不好意思（

2021-09-15 12:01 UTC, ksyx commented on docs/tools/wsl.md
> +运行 `sudo service xrdp restart`，然后去开始菜单，用 `localhost:qwq` 来访问。
[suggest]
```
运行 `sudo service xrdp restart`，然后去开始菜单，用 `localhost:port` 来访问。
```

2021-09-15 12:01 UTC, ksyx commented on docs/tools/wsl.md
> +            <Ok>            <Cancel>
哦没注意到缩进 不好意思 qwq

2021-09-15 12:02 UTC, ksyx commented on docs/tools/wsl.md
> +运行 `sudo service xrdp restart`，然后去开始菜单，用 `localhost:qwq` 来访问。
[suggest]
```diff
- 运行 `sudo service xrdp restart`，然后去开始菜单，用 `localhost:qwq` 来访问。
+ 运行 `sudo service xrdp restart`，然后去开始菜单，用 `localhost:port` 来访问。
```

2021-09-16 12:14 UTC, mcendu commented on docs/tools/wsl.md
> +运行 `sudo service xrdp restart`，然后去开始菜单，用 `localhost:qwq` 来访问。
https://github.com/OI-wiki/OI-wiki/blob/1e1bdc7629c26f823ef3f8d3224e712991d16a70/docs/tools/wsl.md#L233

顺带想把这里的 `qwq` 改掉

2021-09-19 16:42 UTC, ksyx commented on docs/tools/wsl.md
> +运行 `sudo service xrdp restart`，然后去开始菜单，用 `localhost:qwq` 来访问。
> https://github.com/OI-wiki/OI-wiki/blob/1e1bdc7629c26f823ef3f8d3224e712991d16a70/docs/tools/wsl.md#L233
> 
> 顺带想把这里的 `qwq` 改掉

可（

2021-09-28 12:07 UTC, CoelacanthusHex approved these changes
LGTM

2021-09-28 17:50 UTC, Enter-tainer approved these changes

2021-09-28 17:50 UTC, merged