feat:工具/MinGW
OI-wiki/OI-wiki pull request #3575
Opened 2021-09-28 18:07 UTC by THE-NAMELESS-SPECTRE

大概对MinGW做了个简介

2021-09-29 10:02 UTC, Early0v0 reviewed
文段后面需要加上句号。

另外 OI-Wiki 可能不太适合发表感想（

2021-09-29 10:02 UTC, Early0v0 commented on docs/tools/mingw.md
> +Write by GHOST
这个署名请放到开头（在开头加上一句 `author: THE-NAMELESS-SPECTRE`）

2021-09-30 11:58 UTC, Xeonacid requested changes

2021-09-30 11:58 UTC, Xeonacid commented on docs/tools/mingw.md
> +对于 OIer 而言，您可以单纯地把它当成 Windows 下的 gcc（准确来讲，叫能生成 win 可执行文件的 gcc, 也就是所谓交叉编译器 CrossCompiler).
在win下生成win下的可执行文件，不叫交叉编译

2021-09-30 11:58 UTC, Xeonacid commented on docs/tools/mingw.md
> +- “标准”支持好，这个标准，其实指的是 NOI 的标准，即 GCC 4.8.5 的 GNU++98（注意 C++ 与 GNU++ 的区别），MinGW 基本能完全支持，除去一些非常偏门且其中大部分功能可被代替的库，同时也有一些 Windows 下的库，能开发一些基础的字符界面的程序（包括但不限于移动控制台光标到指定行列，控制/检测鼠标和键盘等）。
NOI Linux 2.0已经开始使用了

2021-09-30 11:58 UTC, Xeonacid commented on docs/tools/mingw.md
> +下载 x86_64-posix-seh 包，当然其它的也可以，具体区别不做赘述（时间，篇幅等原因，以后可能会施工），在线安装器也可以，但非常慢且不稳定，需要一点聪明才智
```suggestion
下载 x86_64-posix-seh 包，当然其它的也可以，具体区别不做赘述，在线安装器也可以，但非常慢且不稳定，需要一点聪明才智。
```

2021-09-30 11:58 UTC, Xeonacid commented on docs/tools/mingw.md
> +实际上，这是由于 MinGW 的 Windows 包长期无人维护导致的，内置的 GCC 停留在 8.1.0 版本，很多 C++17 特性尚未支持
只是sourceforge的包无人维护，msys的mingw-w64包很新

2021-09-30 11:58 UTC, Xeonacid commented on docs/tools/mingw.md
> +可以考虑使用 Cygwin 或 Msys2 下的 MinGW, 或者在 WSL 下使用包管理器安装，winget 不清楚是否支持
```suggestion
可以考虑使用 Cygwin 或 MSYS2 下的 MinGW, 或者在 WSL 下使用包管理器安装。
```
不清楚就不要写了

2021-09-30 11:58 UTC, Xeonacid commented on docs/tools/mingw.md
> +由于手头上只有 Mac 还是最低配的 Intel MBP, 暂时无法实际验证
```suggestion
```
这种就不要写了

2021-09-30 15:06 UTC, THE-NAMELESS-SPECTRE commented on docs/tools/mingw.md
> +对于 OIer 而言，您可以单纯地把它当成 Windows 下的 gcc（准确来讲，叫能生成 win 可执行文件的 gcc, 也就是所谓交叉编译器 CrossCompiler).
MinGW本身是跨平台的, 也就是说, 我可以在Linux或Mac上生成win可执行文件, 使用"交叉编译"完全没问题

2021-09-30 15:42 UTC, Xeonacid commented on docs/tools/mingw.md
> +对于 OIer 而言，您可以单纯地把它当成 Windows 下的 gcc（准确来讲，叫能生成 win 可执行文件的 gcc, 也就是所谓交叉编译器 CrossCompiler).
可你现在不在Linux或Mac上啊，你就在win上啊

2021-10-03 14:22 UTC, THE-NAMELESS-SPECTRE commented on docs/tools/mingw.md
> +实际上，这是由于 MinGW 的 Windows 包长期无人维护导致的，内置的 GCC 停留在 8.1.0 版本，很多 C++17 特性尚未支持
emmm那应该算msys build吧

2021-11-21 09:05 UTC, CoelacanthusHex commented
Lost response……

2021-12-26 11:39 UTC, NachtgeistW commented
@github-actions[bot] 欸，上洗桑拿了啊

2022-01-16 01:02 UTC, closed without merging