加入可持久化并查集的内容
OI-wiki/OI-wiki pull request #3663
Opened 2021-11-15 08:05 UTC by Honeta

在“可持久化线段树”部分中添加了基于主席树的可持久化并查集的具体实现，扩充相关章节，作为对这一主席树数据结构应用的一个拓展示例供参考，同时也填补了可持久化并查集相关具体内容的空白。

2021-11-15 13:09 UTC, Early0v0 requested changes
主席树实现可持久化并查集不能使用路径压缩，只能按秩合并。

2021-11-15 13:33 UTC, Early0v0 reviewed
- `Log4N` 可能有歧义，建议改一下。
- 请将代码按照 https://oi-wiki.org/intro/format/#_9 的格式存放。

2021-11-16 04:38 UTC, Early0v0 approved these changes
辛苦了

2021-12-10 20:06 UTC, Enter-tainer approved these changes

2021-12-10 20:07 UTC, merged