feat: add Pull Request auto stale
OI-wiki/OI-wiki pull request #3704
Opened 2021-12-20 13:29 UTC by CoelacanthusHex

close #3671 

希望大家一起完善

2021-12-20 13:29 UTC, Xeonacid commented
@CoelacanthusHex 我觉得有必要考虑一下reviewer鸽了的情况（

2021-12-20 13:29 UTC, Enter-tainer approved these changes
lgtm

2021-12-20 13:33 UTC, CoelacanthusHex commented
> @CoelacanthusHex 我觉得有必要考虑一下reviewer鸽了的情况（

我没有发现可以自动 request-review 的功能，在 stale message 里 @ OI-wiki/editors 似乎可以作为一种替代方案，但是又会对所有编辑无差别推送

2021-12-20 13:34 UTC, ksyx commented on .github/workflows/pr-stale.yml
> +            如果此 PR 在将来的14天内仍未恢复活动，它将被关闭。
```suggestion
            这个 Pull Request 已经 30 天未响应。
            如果此 PR 在将来的 14 天内仍未恢复活动，它将被关闭。
```

2021-12-20 13:36 UTC, Menci requested changes

2021-12-20 13:36 UTC, Menci commented on .github/workflows/pr-stale.yml
> +            如果此 PR 在将来的14天内仍未恢复活动，它将被关闭。
```suggestion
            这个 Pull Request 已经 30 天未响应。
            如果此 PR 在将来的 14 天内仍未恢复活动，它将被关闭。
```

加空格。

2021-12-20 13:36 UTC, Xeonacid commented
> > @CoelacanthusHex 我觉得有必要考虑一下reviewer鸽了的情况（
> 
> 我没有发现可以自动 request-review 的功能，在 stale message 里 @ OI-wiki/editors 似乎可以作为一种替代方案，但是又会对所有编辑无差别推送

request-review可能并不能解决这个问题，还是没人review的话照样会被close（
我建议改workflow（有这种轮子吗）

2021-12-20 13:40 UTC, CoelacanthusHex commented
> > > @CoelacanthusHex 我觉得有必要考虑一下reviewer鸽了的情况（
> > 
> > 
> > 我没有发现可以自动 request-review 的功能，在 stale message 里 @ OI-wiki/editors 似乎可以作为一种替代方案，但是又会对所有编辑无差别推送
> 
> request-review可能并不能解决这个问题，还是没人review的话照样会被close（ 我建议改workflow（有这种轮子吗）

问题在于，这样想的话我们根本无从处理，不动用人工的话根本无从判断一个PR是wait for review 还是no response,上人工的话，既然都用人工了，为什么不直接review呢

2021-12-20 13:42 UTC, Xeonacid commented
> > > > @CoelacanthusHex 我觉得有必要考虑一下reviewer鸽了的情况（
> > > 
> > > 
> > > 我没有发现可以自动 request-review 的功能，在 stale message 里 @ OI-wiki/editors 似乎可以作为一种替代方案，但是又会对所有编辑无差别推送
> > 
> > 
> > request-review可能并不能解决这个问题，还是没人review的话照样会被close（ 我建议改workflow（有这种轮子吗）
> 
> 问题在于，这样想的话我们根本无从处理，不动用人工的话根本无从判断一个PR是wait for review 还是no response,上人工的话，既然都用人工了，为什么不直接review呢

可以检查last update是谁？（不知道有没有这种API）

2021-12-20 13:42 UTC, ksyx commented
> > > > > @CoelacanthusHex 我觉得有必要考虑一下reviewer鸽了的情况（
> > > > 
> > > > 
> > > > 我没有发现可以自动 request-review 的功能，在 stale message 里 @ OI-wiki/editors 似乎可以作为一种替代方案，但是又会对所有编辑无差别推送
> > > 
> > > 
> > > request-review可能并不能解决这个问题，还是没人review的话照样会被close（ 我建议改workflow（有这种轮子吗）
> > 
> > 
> > 问题在于，这样想的话我们根本无从处理，不动用人工的话根本无从判断一个PR是wait for review 还是no response,上人工的话，既然都用人工了，为什么不直接review呢
> 
> 可以脚本检查last update是谁？（不知道有没有这种API）

你 wiki 应该不存在一个月没人看的 PR 吧
（这样没人愿意看的可能确实有理由 stale

2021-12-20 13:43 UTC, CoelacanthusHex commented
@Xeonacid ？no reponse 和 wait for review last update 都不确定哦

2021-12-20 13:44 UTC, Xeonacid commented
> > > > > > @CoelacanthusHex 我觉得有必要考虑一下reviewer鸽了的情况（
> > > > > 
> > > > > 
> > > > > 我没有发现可以自动 request-review 的功能，在 stale message 里 @ OI-wiki/editors 似乎可以作为一种替代方案，但是又会对所有编辑无差别推送
> > > > 
> > > > 
> > > > request-review可能并不能解决这个问题，还是没人review的话照样会被close（ 我建议改workflow（有这种轮子吗）
> > > 
> > > 
> > > 问题在于，这样想的话我们根本无从处理，不动用人工的话根本无从判断一个PR是wait for review 还是no response,上人工的话，既然都用人工了，为什么不直接review呢
> > 
> > 
> > 可以脚本检查last update是谁？（不知道有没有这种API）
> 
> 你 wiki 应该不存在一个月没人看的 PR 吧 （这样没人愿意看的可能确实有理由 stale

#3650 差不多一个月

2021-12-20 13:46 UTC, CoelacanthusHex commented
> 
> #3650 差不多一个月


时间可以改，我最初的想法是三个月

2021-12-20 14:01 UTC, CoelacanthusHex commented
Waiting for voting result in Telegram to determine time.

https://t.me/c/1344172945/121673
https://t.me/c/1344172945/121675

2021-12-23 02:51 UTC, Ir1d approved these changes
LGTM!🙏🏻

2021-12-23 06:58 UTC, Konano approved these changes

2021-12-24 02:48 UTC, Ir1d approved these changes

2021-12-24 06:27 UTC, merged