feat: 添加了镜像站列表
OI-wiki/OI-wiki pull request #3705
Opened 2021-12-21 17:21 UTC by Enter-tainer

目前只加上了我目前知道的镜像站，可能还有一些镜像站我没有加上的，麻烦补充。

这个PR是一个不太成熟的想法，欢迎提出各种意见

2021-12-21 17:24 UTC, Ir1d commented
`oi-wiki.com`: @billchenchina 
`demo.oi-wiki.org`: netlify

这俩要不要也加上

2021-12-21 20:53 UTC, CoelacanthusHex commented
建议添加同步频率

2021-12-22 01:55 UTC, Menci requested changes

2021-12-22 01:55 UTC, Menci commented on docs/intro/mirrors.md
> +-   维护者：Menci([men.ci](https://men.ci))，线路：Azure + 阿里云 CDN
统一用全角括号？

```suggestion
-   维护者：Menci（[men.ci](https://men.ci)），线路：Azure + 阿里云 CDN
```

2021-12-22 07:00 UTC, Enter-tainer commented
> 建议添加同步频率

目前列出来的镜像，都是通过 webhook 同步的，理论上来说更新频率和主站是差不多的。

2021-12-22 07:18 UTC, CoelacanthusHex commented
@Enter-tainer 那加一句统一说明吧

2021-12-23 06:57 UTC, Konano approved these changes

2021-12-23 07:45 UTC, Xeonacid commented on docs/intro/mirrors.md
> +
```suggestion
<https://oiwiki.com>

```
from the cert of `oiwiki.moe`

2021-12-24 05:14 UTC, Xeonacid approved these changes

2021-12-24 14:30 UTC, Ir1d approved these changes

2021-12-24 14:30 UTC, merged