Update python.md
OI-wiki/OI-wiki pull request #3727
Opened 2021-12-30 03:18 UTC by zzjjbb

- fix errors about "typing" in Python
- fix a formatting error

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论你是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈你的感受
3. 如果你熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2021-12-30 03:19 UTC, ksyx commented
请阅读 [如何参与](https://oi-wiki.org/intro/htc/) 及 [格式手册](https://oi-wiki.org/intro/format/) 以方便 PR 更顺利地被合并，thx

2021-12-30 06:29 UTC, CoelacanthusHex requested changes

2021-12-30 06:29 UTC, CoelacanthusHex commented on docs/lang/python.md
> +```python3.6+
There is no language named `python3.6`, you should still use `python3`

2021-12-30 06:29 UTC, CoelacanthusHex commented on docs/lang/python.md
> -??? note "C++"
Why remove note? Please tell me the reason!

2021-12-30 06:49 UTC, CoelacanthusHex requested changes

2021-12-30 06:49 UTC, CoelacanthusHex commented on docs/lang/python.md
> +类型标注是自 Python 3.5 引入的特征 ([PEP 484](https://www.python.org/dev/peps/pep-0484/))，是添加类型提示的重要方法。例如这段代码就引入了类型标注，你可以通过调用 `circumference.__annotations__` 来查看函数中所有的类型标注。
Strictly speaking, this feature was first introduced in Python 3.0 by [PEP 3107](https://www.python.org/dev/peps/pep-3107/), after [PEP 484](https://www.python.org/dev/peps/pep-0484/), it is basically available in [PEP 526](https://www.python.org/dev/peps/pep-0526/).

2021-12-31 14:17 UTC, Xeonacid commented on docs/lang/python.md
> +自 Python 3.6 起 ([PEP 526](https://www.python.org/dev/peps/pep-0526/))，除了函数函数，变量也是可以类型标注的，你可以通过调用 `__annotations__` 来查看模块和类中所有的变量类型标注。
```suggestion
自 Python 3.6 起 ([PEP 526](https://www.python.org/dev/peps/pep-0526/))，除了函数参数，变量也是可以类型标注的，你可以通过调用 `__annotations__` 来查看模块和类中所有的变量类型标注。
```

2022-01-02 22:45 UTC, zzjjbb commented
Thanks for reviewing this! I think most part of this PR contains problems and is kind of confusing. I'll submit a new one instead.

2022-01-02 22:45 UTC, closed without merging