feat(ds/splay): add time complexity analysis of splay operation
OI-wiki/OI-wiki pull request #3733
Opened 2021-12-31 15:39 UTC by isdanni

### Isssue

close #3694 

### Change

- docs/ds/splay.md
- mkdocs.yml

### Add 

- docs/ds/images/splay-zig-zag.gif
- docs/ds/images/splay-zig-zig.gif
- docs/ds/images/splay-zig.png

这三个图都是wiki的(

2021-12-31 16:30 UTC, Xeonacid reviewed
请去掉所有zig/zag的$$

2022-01-01 08:13 UTC, Xeonacid reviewed
请注意正确使用公式

2022-01-01 08:13 UTC, Xeonacid commented on docs/ds/splay.md
> +Splay 操作即对 $x$ 做一系列的 **splay 步骤**。每次对 $x$ 做一次 splay 步骤，$x$ 到根节点的距离都会更近。定义 $p$ 为 $x$ 的父节点。Splay 步骤有三种，具体分为 $6$ 种情况：
```suggestion
Splay 操作即对 $x$ 做一系列的 **splay 步骤**。每次对 $x$ 做一次 splay 步骤，$x$ 到根节点的距离都会更近。定义 $p$ 为 $x$ 的父节点。Splay 步骤有三种，具体分为六种情况：
```

2022-01-01 08:13 UTC, Xeonacid commented on docs/ds/splay.md
> +即直接将 $x$ 左旋或右旋（图 $1,2$）
```suggestion
即直接将 $x$ 左旋或右旋（图 1, 2）
```

2022-01-01 08:13 UTC, Xeonacid commented on docs/ds/splay.md
> +即首先将 $g$ 左旋或右旋，然后将 $x$ 右旋或左旋（图 $3,4$）。
```suggestion
即首先将 $g$ 左旋或右旋，然后将 $x$ 右旋或左旋（图 3, 4）。
```

2022-01-01 08:13 UTC, Xeonacid commented on docs/ds/splay.md
> +即将 $x$ 先左旋再右旋、或先右旋再左旋（图 $5,6$）。
```suggestion
即将 $x$ 先左旋再右旋、或先右旋再左旋（图 5, 6）。
```

2022-01-01 08:13 UTC, Xeonacid commented on docs/ds/splay.md
> +因为 zig 和 zag 是 **对称** 操作，我们只需要对 zig，zig−zig，zig−zag 操作分析复杂度。采用 [势能分析](../basic/complexity.md#势能分析)，定义一个 $n$ 个节点的 splay 树进行了 $m$ 次 splay 步骤。可记 $w(x)=[\log(size(x))]$, 定义势能函数为 $\varphi =\sum w(x)$,$\va
```suggestion
因为 zig 和 zag 是 **对称** 操作，我们只需要对 zig，zig−zig，zig−zag 操作分析复杂度。采用 [势能分析](../basic/complexity.md#_11)，定义一个 $n$ 个节点的 splay 树进行了 $m$ 次 splay 步骤。可记 $w(x)=[\log(size(x))]$, 定义势能函数为 $\varphi =\sum w(x)$,$\varphi (0) \leq n \log n$，在第 $i$ 次操作后势能为 $\varphi (i)$, 则我们只需要求出初始势能和每次的势能变化量的和即可。
```
mkdocs不支持中文锚点（

2022-01-01 08:14 UTC, Xeonacid submitted a review, later dismissed

2022-01-02 06:06 UTC, CoelacanthusHex requested changes
@isdanni 我只想问一个问题，为什么你的 GIF 是静态图片……

2022-01-02 15:57 UTC, isdanni commented
> @isdanni 我只想问一个问题，为什么你的 GIF 是静态图片……

因为那三个图其实应该全部是静态的( 
等我研究下把它们全改成svg & tex的格式 :sweat_smile:

2022-01-08 10:17 UTC, Early0v0 commented
![](https://user-images.githubusercontent.com/44915258/148640468-da530393-0c94-4d9e-bd2c-04126119f2a0.png)

公式长度过长，能否考虑增加一些换行？

2022-01-08 10:39 UTC, isdanni commented
> ![](https://user-images.githubusercontent.com/44915258/148640468-da530393-0c94-4d9e-bd2c-04126119f2a0.png)
> 
> 公式长度过长，能否考虑增加一些换行？

好的，和svg图片下一次commit一起更新 :+1:

2022-09-05 02:24 UTC, Great-designer commented
至今没有任何更新

2022-09-08 18:49 UTC, isdanni commented
> 至今没有任何更新

这周末前修完，抱歉拖了这么久 😅 ☠️ 🙏

2022-09-19 17:22 UTC, Tiphereth-A commented on docs/ds/splay.md
> +因为 zig 和 zag 是 **对称** 操作，我们只需要对 zig，zig−zig，zig−zag 操作分析复杂度。采用 [势能分析](../basic/complexity.md#_11)，定义一个 $n$ 个节点的 splay 树进行了 $m$ 次 splay 步骤。可记 $w(x)=[\log(size(x))]$, 定义势能函数为 $\varphi =\sum w(x)$,$\var
```suggestion
因为 zig 和 zag 是 **对称** 操作，我们只需要对 zig，zig−zig，zig−zag 操作分析复杂度。采用 [势能分析](../basic/complexity.md#势能分析)，定义一个 $n$ 个节点的 splay 树进行了 $m$ 次 splay 步骤。可记 $w(x)=[\log(\operatorname{size}(x))]$, 定义势能函数为 $\varphi =\sum w(x)$,$\varphi (0) \leq n \log n$，在第 $i$ 次操作后势能为 $\varphi (i)$, 则我们只需要求出初始势能和每次的势能变化量的和即可。
```

2022-09-19 17:22 UTC, Tiphereth-A commented on docs/ds/splay.md
> +$$
公式缩进似乎有些不便阅读，建议调整一下
另外不懂为什么要将 `'` 写成上标，写成上标的话公式渲染出来之后字母和该符号被隔开，观感很奇怪，一并建议修改
```suggestion
$$
\begin{align}
1+w'(x)+w'(fa)−w(x)−w(fa) \leq & 1+w'(fa)−w(x) \\
\leq & 1+w'(x)−w(x)
\end{align}
$$
```

2022-09-19 17:23 UTC, Tiphereth-A commented on docs/ds/splay.md
> +$$
同上
```suggestion
$$
\begin{align}
1+w'(x)+w'(fa)+w'(g)−w(x)−w(fa)−w(g) \leq & 1+w'(fa)+w'(g)−w(x)−w(fa) \\
\leq & 1+ w'(x)+w'(g)−2w(x) \\
\leq & 3(w'(x)−w(x))
\end{align}
$$
```

2022-09-19 17:23 UTC, Tiphereth-A commented on docs/ds/splay.md
> +$$
同上
另外这里的 `'` 写成了 `′`
```suggestion
$$
\begin{align}
1+w'(x)+w'(fa)+w'(g)−w(x)−w(fa)−w(g) \leq & 1+w'(fa)+w'(g)−w(x)−w(fa) \\
\leq & 1+w'(g)+w'(fa)−2w(x) \\
\leq & 2 w'(x)−w'(g)−w'(fa) + w'(fa)+w'(g)−w(x)−w(fa) \\
\leq & 2(w'(x)−w(x))
\end{align}
$$
```

2022-09-19 17:24 UTC, Tiphereth-A commented on docs/ds/splay.md
> +$$
$w^{'''}\cdots(x_{1})$ 这个记号看起来非常奇怪，也许可以考虑用递归定义表示
另外，看这个公式的换行感觉作者希望将该公式分为两行，但目前显然不能实现该效果
```suggestion
由此可见，三种 splay 步骤的势能全部可以缩放为 $\leq 3(w'(x)−w(x))$. 令 $w^{(n)}(x)=w^{(n-1)}'(x)$, $w^{(0)}(x)=w(x)$, 假设 splay 操作一次依次访问了 $x_{1}, x_{2}, \cdots, x_{n}$, 最终 $x_{1}$ 成为根节点，我们可以得到：

$$
\begin{align}
3(\sum_{i=0}^{n-2}(w^{(i+1)}(x_{1})-w^{(i)}(x_{1}))+w(n)−w^{(n-1)}(x_{1}))+1 = & 3(w(n)−w(x_{1}))+1 \\
\leq & \log n
\end{align}
$$
```

2022-09-19 17:24 UTC, Tiphereth-A commented on docs/ds/splay.md
> +$$
```suggestion
$$
\sum_{i=1}^m (\varphi (m-i+1)−\varphi (m−i)) +\varphi (0) = n \log n+m \log n
$$
```

2022-09-20 03:56 UTC, Tiphereth-A reviewed
这样编译文档应该就不会出问题了

2022-09-20 03:56 UTC, Tiphereth-A commented on docs/ds/splay.md
> +$$
```suggestion
$$
\begin{aligned}
1+w'(x)+w'(fa)−w(x)−w(fa) & \leq 1+w'(fa)−w(x) \\
& \leq 1+w'(x)−w(x)
\end{aligned}
$$
```

2022-09-20 03:56 UTC, Tiphereth-A commented on docs/ds/splay.md
> +$$
```suggestion
$$
\begin{aligned}
1+w'(x)+w'(fa)+w'(g)−w(x)−w(fa)−w(g) & \leq 1+w'(fa)+w'(g)−w(x)−w(fa) \\
& \leq 1+ w'(x)+w'(g)−2w(x) \\
& \leq 3(w'(x)−w(x))
\end{aligned}
$$
```

2022-09-20 03:56 UTC, Tiphereth-A commented on docs/ds/splay.md
> +$$
```suggestion
$$
\begin{aligned}
1+w'(x)+w'(fa)+w'(g)−w(x)−w(fa)−w(g) & \leq 1+w'(fa)+w'(g)−w(x)−w(fa) \\
& \leq 1+w'(g)+w'(fa)−2w(x) \\
& \leq 2 w'(x)−w'(g)−w'(fa) + w'(fa)+w'(g)−w(x)−w(fa) \\
& \leq 2(w'(x)−w(x))
\end{aligned}
$$
```

2022-09-20 03:56 UTC, Tiphereth-A commented on docs/ds/splay.md
> +$$
```suggestion
$$
\begin{aligned}
3\left(\sum_{i=0}^{n-2}\left(w^{(i+1)}(x_{1})-w^{(i)}(x_{1})\right)+w(n)−w^{(n-1)}(x_{1})\right)+1 & = 3(w(n)−w(x_{1}))+1 \\
& \leq \log n
\end{aligned}
$$
```

2022-09-20 03:58 UTC, isdanni commented on docs/ds/splay.md
> +$$
好耶，正准备今晚修来着（

2022-09-20 04:47 UTC, Tiphereth-A commented on docs/ds/splay.md
> +由此可见，三种 splay 步骤的势能全部可以缩放为 $\leq 3(w'(x)−w(x))$. 令 $w^{(n)}(x)=w^{(n-1)}'(x)$, $w^{(0)}(x)=w(x)$, 假设 splay 操作一次依次访问了 $x_{1}, x_{2}, \cdots, x_{n}$, 最终 $x_{1}$ 成为根节点，我们可以得到：
好像是这里的问题😇
```suggestion
由此可见，三种 splay 步骤的势能全部可以缩放为 $\leq 3(w'(x)−w(x))$. 令 $w^{(n)}(x)=w'^{(n-1)}(x)$, $w^{(0)}(x)=w(x)$, 假设 splay 操作一次依次访问了 $x_{1}, x_{2}, \cdots, x_{n}$, 最终 $x_{1}$ 成为根节点，我们可以得到：
```

2022-09-21 06:59 UTC, Great-designer commented
@CoelacanthusHex 不知道现在这样是否可以了？

2022-09-21 09:17 UTC, CoelacanthusHex commented
是渲染问题还是我视力问题，我怎么看着有两张图的线条很模糊

2022-09-21 09:18 UTC, CoelacanthusHex commented
就像是用没多少水的毛笔画图然后把灰度低于一定程度的抹去

2022-09-21 16:22 UTC, kLiHz commented
> 是渲染问题还是我视力问题，我怎么看着有两张图的线条很模糊

因为估计又是强转的 SVG … 得手动重绘吧？

2022-09-24 13:41 UTC, CoelacanthusHex approved these changes
LGTM

2022-09-24 13:42 UTC, Tiphereth-A commented
画完了

2022-09-27 04:18 UTC, Great-designer approved these changes

2022-09-27 06:27 UTC, merged