refactor(number-theory/quad-residue): refactor
OI-wiki/OI-wiki pull request #3741
Opened 2022-01-08 14:05 UTC by hly1204

基本重写了一下？

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论你是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈你的感受
3. 如果你熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2022-01-14 00:17 UTC, Early0v0 commented on docs/math/number-theory/quad-residue.md
> +## $p\bmod 4=3$
标题尽量不要出现公式？

2022-01-14 00:17 UTC, Early0v0 commented on docs/math/number-theory/quad-residue.md
> +### 计算 $e$
同上。

2022-01-14 07:05 UTC, hly1204 commented
话说还是把所有非二次剩余改成了二次非剩余，因为英文的 quadratic non-residue 我觉得还是翻译成二次非剩余比较合适？

2022-01-14 07:14 UTC, Early0v0 commented
> 话说还是把所有非二次剩余改成了二次非剩余，因为英文的 quadratic non-residue 我觉得还是翻译成二次非剩余比较合适？

查了一下 [Wikipedia](https://zh.wikipedia.org/wiki/%E4%BA%8C%E6%AC%A1%E5%89%A9%E4%BD%99)，的确是「二次非剩余」

2022-01-14 07:23 UTC, Early0v0 submitted a review, later dismissed

2022-01-14 13:39 UTC, Backl1ght requested changes

2022-01-14 13:39 UTC, Backl1ght commented on docs/math/number-theory/quad-residue.md
> +后文可能在模 $p$ 显然的情况下简写成（非）二次剩余。
```suggestion
后文可能在模 $p$ 显然的情况下简写成二次（非）剩余。
```

2022-01-14 17:34 UTC, hly1204 commented on docs/math/number-theory/quad-residue.md
> +后文可能在模 $p$ 显然的情况下简写成（非）二次剩余。
Fixed, thanks!

2022-01-15 01:16 UTC, Early0v0 approved these changes

2022-01-15 09:03 UTC, Backl1ght approved these changes
LGTM

2022-01-16 14:10 UTC, merged