fix(greedy.md): 补充了贪心算法中国王游戏的解题思路
OI-wiki/OI-wiki pull request #3768
Opened 2022-01-26 04:43 UTC by HuPeng333

~想发issue的但是GitHub莫名其妙报500~
[贪心 - OI Wiki](https://oi-wiki.org/basic/greedy/)

之前的解题思路是有问题的(不完整)

如果按照目前提供的解题思路，即按照公式**max(b[i + 1], a[i] * b[i]) < max(b[i], a[i + 1] * b[i + 1])** 在某些情况下会违反**传递性**(即如果a > b，b > c，则a > c)

举例:

现有如下数据，每行分别对应左右手
```
1 1 
1 2
2 1
2 2
```

为了方便描述，按照数据输入的索引，从0给与相关的id(即1 1的id为0；1 2的id为2)，并且a代表id0，b代表id1......
```
id: 0, compareId: 0 -> m(1, 1) - m(1, 1) a = a
id: 0, compareId: 1 -> m(2, 1) - m(1, 2) a = b
id: 0, compareId: 2 -> m(1, 1) - m(1, 2) a < c  line3
id: 0, compareId: 3 -> m(2, 1) - m(1, 4) a < d
id: 1, compareId: 0 -> m(1, 2) - m(2, 1) b = a  line5
id: 1, compareId: 1 -> m(2, 2) - m(2, 2) b = b
id: 1, compareId: 2 -> m(1, 2) - m(2, 2) b = c  line7
```
在line7处得到了b = c，但line5处得到了b = a，line3处得到了a < c，此处结合传递性理论上应该为b < c 。三者结合起来有误!

在某些语言下可能会发生意料之外的情况(*如java直接抛异常*; 在洛谷上提交应该会WA一个点)

目前已经在这个基础上，推出了正确的公式

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论你是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈你的感受
3. 如果你熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2022-02-10 05:02 UTC, ouuan requested changes

2022-02-10 05:02 UTC, ouuan commented on docs/basic/greedy.md
> +    为了方便表述从左往右，分别给其中的数标识 $A$,$B$,$C$,$D$
我是觉得写成 ABCD 反而不方便阅读，不如直接用原式。

2022-02-10 05:02 UTC, ouuan commented on docs/basic/greedy.md
> +    $a_{i}\cdot b_{i} < a_{i + 1} \cdot b_{i + 1}$
我感觉这里说的有点繁琐，指出那个恒大于等于直接化简就可以了吧，中间的需要写出来吗

2022-03-13 10:43 UTC, xyf007 commented
类似《国王游戏》这种 Exchange Arguments 的贪心策略可以参考今年张隽恺的集训队论文？

2022-03-13 11:20 UTC, ouuan commented
> 类似《国王游戏》这种 Exchange Arguments 的贪心策略可以参考今年张隽恺的集训队论文？

这个论文哪能看到啊 /fad

2022-03-24 18:48 UTC, Saisyc reviewed
解释得比较复杂且可能存在一些逻辑纰漏，此外某些符号如\leq不宜写作<=；但原词条的国王游戏题解确实有待改良，两害相权…下选择暂时中立

2022-05-08 01:36 UTC, closed without merging