feat(basic/quick-sort.md): 添加快速排序的时间复杂度分析 fix #3816
OI-wiki/OI-wiki pull request #3828
Opened 2022-03-02 12:21 UTC by zhangjunyan2580

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论您是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈您的感受
3. 如果您熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2022-03-02 16:34 UTC, Backl1ght requested changes

2022-03-02 16:34 UTC, Backl1ght commented on docs/basic/quick-sort.md
> +所以 $E[X] = \sum \limits _ {i = 1} ^ {n - 1} \sum \limits _ {j = i + 1} ^ n P(a_i\ 和\ a_j\ 比较) = \sum \limits _ {i = 1} ^ {n - 1} \sum \limits _ {j = i + 1} ^ n \dfrac{2}{j - i + 1} = \sum \limits _ {
按照格式要求，请把数学公式中的中文置于`\text{}`环境中

2022-03-02 23:06 UTC, zhangjunyan2580 commented on docs/basic/quick-sort.md
> +所以 $E[X] = \sum \limits _ {i = 1} ^ {n - 1} \sum \limits _ {j = i + 1} ^ n P(a_i\ 和\ a_j\ 比较) = \sum \limits _ {i = 1} ^ {n - 1} \sum \limits _ {j = i + 1} ^ n \dfrac{2}{j - i + 1} = \sum \limits _ {
fixed

2022-03-03 06:53 UTC, zhangjunyan2580 commented
修了 latex，能再 review 一下吗

2022-03-04 04:30 UTC, zhangjunyan2580 commented
fixed

2022-03-05 05:53 UTC, Backl1ght approved these changes
LGTM

2022-03-05 06:02 UTC, Enter-tainer approved these changes

2022-03-05 06:02 UTC, merged