feat(basis.md): 添加了高斯消元法构造线性基的相关知识点和模板题链接
OI-wiki/OI-wiki pull request #3837
Opened 2022-03-09 02:46 UTC by rsdbkhusky

feat(basis.md): 添加了高斯消元法构造线性基的相关知识点和模板题链接

fix #3836 

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论您是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈您的感受
3. 如果您熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2022-03-09 03:33 UTC, rsdbkhusky commented
第三行少加了一个句号。

2022-03-09 03:36 UTC, rsdbkhusky reviewed
补上了第三行少加的句号。

2022-03-11 07:08 UTC, Menci requested changes

2022-03-11 07:08 UTC, Menci commented on docs/math/basis.md
> +如果只需要求 $0/1$ 的线性基，使用 [异或高斯消元](https://oiwiki.org/math/gauss/#_17) 即可。
推荐通过直接引用 md 文件相对路径的方式来引用站内链接，不然对[镜像站](https://oi.wiki)会很不友好。

```suggestion
如果只需要求 $0/1$ 的线性基，使用 [异或高斯消元](gauss.md#_17) 即可。
```

2022-03-11 07:08 UTC, Menci commented on docs/math/basis.md
> +如果对这条性质的正确性不理解，可以跳转 [高斯消元](https://oiwiki.org/math/gauss)。
```suggestion
如果对这条性质的正确性不理解，可以跳转 [高斯消元](gauss.md)。
```

2022-03-11 07:08 UTC, Menci commented on docs/math/basis.md
> +[Luogu P3812【模板】线性基](https://www.luogu.com.cn/problem/P3812)&[Acwing 3164. 线性基](https://www.acwing.com/problem/content/description/3167)
```suggestion
[Luogu P3812【模板】线性基](https://www.luogu.com.cn/problem/P3812) & [Acwing 3164. 线性基](https://www.acwing.com/problem/content/description/3167)
```

注意排版空格

2022-03-11 07:08 UTC, Menci commented on docs/math/basis.md
> +如果只需要求 $0/1$ 的线性基，使用 [异或高斯消元](https://oiwiki.org/math/gauss/#_17) 即可。
才发现你贴的链接也是个镜像站（）

2022-03-11 07:40 UTC, rsdbkhusky commented
我在 161 行加上了空格，可是又变回去了。

2022-03-11 07:42 UTC, rsdbkhusky commented
被机器人变回去了

2022-03-11 08:16 UTC, rsdbkhusky commented
我把 "Allow edits by maintainers" 应该就好了。

2022-03-11 08:23 UTC, ouuan commented
> 我把 "Allow edits by maintainers" 关掉应该就好了。

那后面所有 PR 都会被改吧

2022-03-11 08:25 UTC, ouuan commented
放在两行不好吗，这两题连数据范围都不一样（

2022-03-11 08:26 UTC, rsdbkhusky commented
> 放在两行不好吗，这两题连数据范围都不一样（

好吧。

2022-03-11 08:26 UTC, ouuan commented
也可以试一试 `&nbsp;`

2022-03-20 07:40 UTC, Enter-tainer commented on docs/math/basis.md
> +#### 运行效率
运行...效率？ 这个说法有点奇怪

2022-03-21 05:43 UTC, Ir1d commented on docs/math/basis.md
> +#### 运行效率
直接叫复杂度（？

2022-03-21 05:47 UTC, rsdbkhusky commented on docs/math/basis.md
> +#### 运行效率
ok

2022-03-22 13:52 UTC, Enter-tainer approved these changes

2022-03-27 12:20 UTC, rsdbkhusky commented
添加了更多内容。

2022-03-27 13:24 UTC, Saisyc requested changes
较为冒昧的，作者的线性代数水平可能不足以良好解释 basis 在异或空间中的作用。

2022-03-27 14:04 UTC, Enter-tainer commented
> 较为冒昧的，作者的线性代数水平可能不足以良好解释 basis 在异或空间中的作用。

如果你认为文章内容存在问题，请给出更加有建设性的意见。

2022-03-27 15:04 UTC, Saisyc commented
> > 较为冒昧的，作者的线性代数水平可能不足以良好解释 basis 在异或空间中的作用。
> 
> 如果你认为文章内容存在问题，请给出更加有建设性的意见。

详细内容已在2022年3月27日21:45-21:52中在QQ群中向原作者解释；此后，若非特别必要，我将放弃对#3837的跟进。

2022-06-03 12:05 UTC, untitledunrevised commented
为了避免造成误导，建议保留原本 wiki 中的线性基的性质，而把你替换的这些性质另外开一个小标题，并使用名词 “基” 而不是 “线性基”。
因为在算法竞赛中，“线性基” 一般指在 $\mathbb{F}_2^n$ 上定义的基，而你说的这些性质可以用 “基” 来称呼。

2022-06-03 12:09 UTC, Saisyc commented
> 为了避免造成误导，建议保留原本 wiki 中的线性基的性质，而把你替换的这些性质另外开一个小标题，并使用名词 “基” 而不是 “线性基”。 因为在算法竞赛中，“线性基” 一般指在 F2n 上定义的基，而你说的这些性质可以用 “基” 来称呼。

“线性基”一词似乎并没有相应的英文；此外，此称呼可能导致初学者误认为：“基”不一定是线性的而线性的才称为“线性基”

2022-06-04 02:06 UTC, ouuan commented on docs/math/basis.md
> +- 高斯消元后的矩阵是一个阶梯矩阵。
这个性质好像不是“阶梯型矩阵”，而是“简化列阶梯形矩阵或简约行梯形式矩阵（reduced row echelon form），也称作行规范形矩阵（row canonical form）”。我所学的以及 wikipedia 上的“阶梯型矩阵”就没有你想表达的这一条“额外性质”。

另外，这个性质是包含上面两条的，导致“额外满足一条性质”让人感到一些困惑，所以我建议就把额外的这一条性质写出来，即“对于一个基的最高位，这个基是这组基中唯一一个这一位是 1 的”

2022-06-04 02:06 UTC, ouuan commented on docs/math/basis.md
> +提供一组样例：
这个样例太大了，我的建议是最多 4~6 个数，8 位

2022-06-04 02:15 UTC, ouuan commented on docs/math/basis.md
> +对于其他比较经典的问题，比如查询一个数能否被异或得到，查询能被异或得到的第 $k$ 大数……高斯消元法得到的线性基也能更加方便地解决问题。
这个第 k 大好像是高斯消元求异或基的主要应用吧，根据我自己三年前的博客好像这个题必须高斯消元求。高斯消元求线性基做异或最大值的“方便”其实根本没多方便吧，复杂度还略高..只说了异或最大值的做法而略过第 k 大感觉有点本末倒置，给人一种高斯消元求线性基没用的感觉。

2022-06-06 07:04 UTC, Saisyc commented on docs/math/basis.md
> +对于其他比较经典的问题，比如查询一个数能否被异或得到，查询能被异或得到的第 $k$ 大数……高斯消元法得到的线性基也能更加方便地解决问题。
> 

异或第k大的问题不是“必须高斯消元求”

2022-06-06 07:08 UTC, Saisyc commented
所谓“求线性基”的实质是求 $\mathbb F_2^n$ 中向量组的秩；因此，异或基更适合作为线性空间的基的常用情形的介绍，而不是一个没头没尾的新词条

2022-06-06 07:09 UTC, Saisyc commented
> 为了避免造成误导，建议保留原本 wiki 中的线性基的性质，而把你替换的这些性质另外开一个小标题，并使用名词 “基” 而不是 “线性基”。 因为在算法竞赛中，“线性基” 一般指在 F2n 上定义的基，而你说的这些性质可以用 “基” 来称呼。

个人认为“异或基”是更准确和合理的名称

2022-06-06 07:12 UTC, Saisyc commented
> > 为了避免造成误导，建议保留原本 wiki 中的线性基的性质，而把你替换的这些性质另外开一个小标题，并使用名词 “基” 而不是 “线性基”。 因为在算法竞赛中，“线性基” 一般指在 F2n 上定义的基，而你说的这些性质可以用 “基” 来称呼。
> 
> 个人认为“异或基”是更准确和合理的名称

应当强调，许多做法求出的异或基不是向量组的异或基（不是该向量组的向量）而是该向量组张成的异或空间的异或基

2022-06-06 08:53 UTC, ouuan commented
> 应当强调，许多做法求出的异或基不是向量组的异或基（不是该向量组的向量）而是该向量组张成的异或空间的异或基

那个不是叫极大无关组吗，还有向量组的基这种说法吗

2022-06-07 06:25 UTC, Saisyc commented
> > 应当强调，许多做法求出的异或基不是向量组的异或基（不是该向量组的向量）而是该向量组张成的异或空间的异或基
> 
> 那个不是叫极大无关组吗，还有向量组的基这种说法吗

没有这种说法，但很多博客都“求向量组的线性基”

2022-06-07 06:29 UTC, ouuan commented
> 没有这种说法，但很多博客都“求向量组的线性基”

那“求向量组的线性基”求的是张成空间的基还是极大无关组呢

2022-06-07 06:36 UTC, ouuan commented
> 应当强调，许多做法求出的异或基不是向量组的异或基（不是该向量组的向量）而是该向量组张成的异或空间的异或基

就是说，你这个“强调”，对应的，博客/教程/wiki 应该写成啥样？你是说得用规范的线性代数语言来写吗？既然没有“向量组的基”这种说法，我觉得“求向量组的线性基”就只是一种不规范但能听得懂的说法，而不是一个错误。

2022-06-07 09:08 UTC, Saisyc commented
> > 应当强调，许多做法求出的异或基不是向量组的异或基（不是该向量组的向量）而是该向量组张成的异或空间的异或基
> 
> 就是说，你这个“强调”，对应的，博客/教程/wiki 应该写成啥样？你是说得用规范的线性代数语言来写吗？既然没有“向量组的基”这种说法，我觉得“求向量组的线性基”就只是一种不规范但能听得懂的说法，而不是一个错误。

“向量组的基”不是初学者能听懂的说法，而应被认为是语法错误

2022-06-07 09:37 UTC, ouuan commented
> > > 应当强调，许多做法求出的异或基不是向量组的异或基（不是该向量组的向量）而是该向量组张成的异或空间的异或基
> > 
> > 
> > 就是说，你这个“强调”，对应的，博客/教程/wiki 应该写成啥样？你是说得用规范的线性代数语言来写吗？既然没有“向量组的基”这种说法，我觉得“求向量组的线性基”就只是一种不规范但能听得懂的说法，而不是一个错误。
> 
> “向量组的基”不是初学者能听懂的说法，而应被认为是语法错误，应当严格避免使用此说法

能不能给一个具体文本..我都不知道你是在什么语境、场景下在说这个问题..而且我感觉你 off-topic 了，我真的不知道你说的这些和这个 PR 有什么关系

2022-06-10 13:55 UTC, Saisyc commented
> > > > 应当强调，许多做法求出的异或基不是向量组的异或基（不是该向量组的向量）而是该向量组张成的异或空间的异或基
> > > 
> > > 
> > > 就是说，你这个“强调”，对应的，博客/教程/wiki 应该写成啥样？你是说得用规范的线性代数语言来写吗？既然没有“向量组的基”这种说法，我觉得“求向量组的线性基”就只是一种不规范但能听得懂的说法，而不是一个错误。
> > 
> > 
> > “向量组的基”不是初学者能听懂的说法，而应被认为是语法错误，应当严格避免使用此说法
> 
> 能不能给一个具体文本..我都不知道你是在什么语境、场景下在说这个问题..而且我感觉你 off-topic 了，我真的不知道你说的这些和这个 PR 有什么关系

此PR现有的commit明显没有分清“基”和“极大线性无关组”

2022-06-10 14:04 UTC, ouuan commented
> 此PR现有的commit明显没有分清“基”和“极大线性无关组”

你倒是给个 inline comment 啊..在外面发这么一长串别人也不知道你说的是哪，也不好 resolve，而且外面只有一串 thread 没法树状讨论。

我又看了一遍，稍微有点混淆的我只看到了“高斯消元法是从线性基本身含义的角度去构造线性基，可以求 $0/1$ 向量（二进制数）的线性基，也可以求非 $0/1$ 向量的线性基”这一处。首先我不觉得这里会让人无法看懂，因为这句话的重点在于强调异或线性基的特殊性和高斯消元法求基的普适性，而非线性基的性质之类的；其次这也不是没有分清“基”和“极大线性无关组”而是没有分清“向量”和“线性空间”，因为这一处说的是“向量的基”而不是“向量组的基”。

如果还有哪里有混淆的话请用 inline comment 指出。

2022-06-10 14:09 UTC, Saisyc commented
> > 此PR现有的commit明显没有分清“基”和“极大线性无关组”
> 
> 你倒是给个 inline comment 啊..在外面发这么一长串别人也不知道你说的是哪，也不好 resolve，而且外面只有一串 thread 没法树状讨论。
> 
> 我又看了一遍，稍微有点混淆的我只看到了“高斯消元法是从线性基本身含义的角度去构造线性基，可以求 向量（二进制数）的线性基，也可以求非 向量的线性基”这一处。首先我不觉得这里会让人无法看懂，因为这句话的重点在于强调异或线性基的特殊性和高斯消元法求基的普适性，而非线性基的性质之类的；其次这也不是没有分清“基”和“极大线性无关组”而是没有分清“向量”和“线性空间”，因为这一处说的是“向量的基”而不是“向量组的基”。
> 
> 如果还有哪里有混淆的话请用 inline comment 指出。

能让人看懂的错误说法也是错误说法

2022-06-10 14:15 UTC, ouuan commented
> 能让人看懂的错误说法也是错误说法

我不是否认这句话有错误，但是如果你还想讨论的话请给个 inline comment 完整陈述你的观点。否则的话，像现在这样，我指出讨论中的问题以及对文本进行分析后你只是说“也是错误说法”，你可能回复了个正确的观点，但这对这个 PR 是没有多少价值的，也只是浪费我的时间，我是不会再继续参与讨论的。

2022-06-10 14:19 UTC, Saisyc commented
> > 能让人看懂的错误说法也是错误说法
> 
> 我不是否认这句话有错误，但是如果你还想讨论的话请给个 inline comment 完整陈述你的观点。否则的话，像现在这样，我指出讨论中的问题以及对文本进行分析后你只是说“也是错误说法”，你可能回复了个正确的观点，但这对这个 PR 是没有多少价值的，也只是浪费我的时间，我是不会再继续参与讨论的。

此PR的commit的作者可能对一般域上的线性空间以及基没有较好的了解，并且异或基在常用的性质上似乎并无特例于其他线性空间的基之处；因此，个人认为此 PR 可能直接并入线性代数基础相关内容更好

2022-06-10 14:34 UTC, ouuan commented
> 异或基在常用的性质上似乎并无特例于其他线性空间的基之处；因此，个人认为此 PR 可能直接并入线性代数基础相关内容更好

关于这一点我是有话想说的，但是我实在不明白你这段话为什么要 quote reply 我，或者说为什么你要用这段话 reply 我，所以我不认为讨论能健康地继续下去... unsubscribe 了

2022-06-10 14:44 UTC, Saisyc commented
差不多没救的 PR 也许还是关了然后等 dalao 重开比较好（逃

2022-08-07 04:28 UTC, Great-designer commented
这个肯定和线性代数那个是冲突的。不急，处理完一个之后必然会修另一个。

2022-08-27 06:19 UTC, llh721113 commented
这个PR要怎么办

2022-09-06 14:01 UTC, Great-designer commented
由于文件移动，这个pr已经产生了无法在线解决的冲突

2022-09-16 08:36 UTC, Great-designer commented
本问题已经转移至#4302

2022-09-16 08:36 UTC, closed without merging