fix(csl/iterator.md):修正表述使得更易读
OI-wiki/OI-wiki pull request #3839
Opened 2022-03-09 11:25 UTC by opsiff

typo imporve

2022-03-09 11:33 UTC, Marcythm reviewed
感谢您贡献的意愿，不过我认为修改的部分中仍有些许问题，详见 comments

2022-03-09 11:33 UTC, Marcythm commented on docs/lang/csl/iterator.md
> +在 C++ 11 以后可以使用 `std::next(it)` 获取向前迭代器 `it` 的后继，此时迭代器 `it` 不变，`std::next(it, n)` 获取向前迭代器 `it` 的第 `n` 个后继。
首先，我参考了 cppreference，似乎没有在 “C++“ 与 "11" 间加上空格的实例；
其次，「使用 `std::next(it)` 获取向前迭代器 `it` 的后继，此时迭代器 `it` 不变，`std::next(it, n)` 获取向前迭代器 `it` 的第 `n` 个后继。」这一句话中，「此时迭代器 `it` 不变」是从属于前句还是后句？请使用句号来明确语义（而非一概使用逗号）。

2022-03-09 16:12 UTC, opsiff commented on docs/lang/csl/iterator.md
> +可以使用 `std::advance(it, n)` 使得迭代器 `it` 向后 `n` 步；若 `n` 为负数，则使得迭代器向前 `n` 步，此时若迭代器不满足双向迭代器，行为未定义。
感谢

2022-03-11 07:16 UTC, Menci requested changes

2022-03-11 13:57 UTC, opsiff commented on docs/lang/csl/iterator.md
> +在 C++11 以后可以使用 `std::prev(it)` 获取双向迭代器 `it` 的前驱（此时迭代器 `it` 不变），`std::prev(it, n)` 获取双向迭代器 `it` 的第 `n` 个前驱。
好的，谢谢。

2022-03-13 00:54 UTC, Early0v0 submitted a review, later dismissed

2022-03-13 00:54 UTC, Early0v0 commented on docs/lang/csl/iterator.md
> +可以使用 `std::advance(it, n)` 将迭代器 `it` 向后移动 `n` 步；若 `n` 为负数，则将迭代器向前移动 `n` 步。迭代器必须满足双向迭代器，否则行为未定义。
```suggestion
可以使用 `std::advance(it, n)` 将迭代器 `it` 向后移动 `n` 步；若 `n` 为负数，则将迭代器向前移动 `-n` 步。迭代器必须满足双向迭代器，否则行为未定义。
```

2022-03-13 03:29 UTC, Menci commented on docs/lang/csl/iterator.md
> +可以使用 `std::advance(it, n)` 将迭代器 `it` 向后移动 `n` 步；若 `n` 为负数，则将迭代器向前移动 `n` 步。迭代器必须满足双向迭代器，否则行为未定义。
建议用「如果小于 0，则对应向前移动」这种更简洁的表述

2022-03-14 13:30 UTC, Marcythm reviewed
forward iterator 是否应译为「前向迭代器」而非「向前迭代器」？

2022-03-14 16:10 UTC, Xeonacid commented
> forward iterator 是否应译为「前向迭代器」而非「向前迭代器」？

@Marcythm 我觉得没差（

2022-03-16 02:48 UTC, Early0v0 approved these changes
cppreference 用的是 [向前迭代器](https://zh.cppreference.com/w/cpp/named_req/ForwardIterator)。

2022-03-19 02:29 UTC, Enter-tainer approved these changes

2022-03-19 02:30 UTC, merged