feat(math/bit): 添加更多的详细推导
OI-wiki/OI-wiki pull request #3881
Opened 2022-03-26 04:56 UTC by Pr-159

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论您是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈您的感受
3. 如果您熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2022-03-26 04:57 UTC, Pr-159 commented
萌新实在找不到 Author 的文件在哪里，求管理员审核后添加一下，谢谢/qq

2022-03-26 05:12 UTC, Saisyc requested changes
verbose and informal

2022-03-26 07:06 UTC, Pr-159 commented
> verbose and informal

Thanks for reading!
I think OI-Wiki should me easier. I mean it should let newbies know how the algorithm work, so I wrote many more information.
This is my first time to add something in this wiki. If there is some informal pleaces, please let me know .
Can you give me more suggest? I'll fix it as fast as I can.

2022-03-26 16:23 UTC, Saisyc commented
> > verbose and informal
> 
> Thanks for reading! I think OI-Wiki should me easier. I mean it should let newbies know how the algorithm work, so I wrote many more information. This is my first time to add something in this wiki. If there is some informal pleaces, please let me know . Can you give me more suggest? I'll fix it as fast as I can.

作为 OI-Wiki 的词条，“详细推导”的内容可以是关于代码实现的进一步解释，但绝不应该是个人博客题解风格的教程式研究笔记；这意味着，“在实现这几个操作前，先来填一个和这些操作息息相关的表”“刚刚推出来的这些性质又与开头的操作有什么联系呢？”等 **不提供有效信息** 的语句不应出现。

许多语句有明显的英文机翻痕迹，非常不符合中文的正式表述规范；如“是时候把本节开头的表补充完整了”与"It is time to finish the table we mentioned before."高度雷同。

此外，文中对二进制“最后一位”“第一位”的解释明显与主流理解相悖；一般的，称任意进制表示的最低位为“第零位”。

最后，不建议对不熟悉的领域进行大幅度甚至重构性的更改；语言的规范性应尽可能向 Wikipedia 的主要词条或 IEEE 等期刊的学术论文靠拢。

2022-03-26 17:34 UTC, Saisyc commented
> > verbose and informal
> 
> Thanks for reading! I think OI-Wiki should me easier. I mean it should let newbies know how the algorithm work, so I wrote many more information. This is my first time to add something in this wiki. If there is some informal pleaces, please let me know . Can you give me more suggest? I'll fix it as fast as I can.

OI-Wiki 不必苛求将

    “乘x巴士到A处转y巴士到B处再步行至C处”

等繁琐过程写成

    “乘z地铁能直达C处”

等巧妙精炼的表述，但绝对应避免

    “那么应该怎么做到达C处呢？下面让我们来研究一下吧。首先呢，我们可以看一看这个A地，你想呀，如果要到A地的话，是可以坐x巴士的。既然坐了x巴士，那么到了A处我们就突然发现还有y巴士；现在我们来想一想y巴士有什么用，显然啊，y巴士可以让我们从A处到达B处。可是，我们的目标是到达C处而不是到达A处或者B处啊，所以到达了B处究竟有什么意义呢？原来，B处到C处竟然是可以步行抵达的呢。让我们来总结一下吧，总结：有x巴士可以到A处，想要到B处可以从A处乘巴士，乘的是y巴士，接着从B处想要到最终目的地C处就完全可以只凭步行啦！”

等充斥着大量无效信息的informal表达。

2022-03-26 17:49 UTC, Xeonacid commented
我支持删除无效信息语句，但是不支持将它变得过于 formal。

> 最后，不建议对不熟悉的领域进行大幅度甚至重构性的更改；语言的规范性应尽可能向 Wikipedia 的主要词条或 IEEE 等期刊的学术论文靠拢。

我认为 OI Wiki 应该是（对当前条目的）新手友好的教程，而不是学术论文。加一点可以帮助理解的 informal 内容是有好处的。

2022-03-26 17:49 UTC, ksyx reviewed
- 各段过于简短读起来有点跳跃，请善用折叠框
- 请参考 [格式手册](https://oi-wiki.org/intro/format)

2022-03-26 17:49 UTC, ksyx commented on docs/math/bit.md
> +
- 与、或、异或一节已经有了位运算基本操作的描述，此部分过度重复

2022-03-26 17:49 UTC, ksyx commented on docs/math/bit.md
> +    为了去除前面的前导 $0$（此时为逻辑右移），可以加上一步 $\&\,1$，虽然最终结果不变，但是更加保险（有些编辑器仍采用逻辑右移）。
编辑器？

2022-03-26 17:49 UTC, ksyx commented on docs/math/bit.md
> +    现在，**我们将整个值 $-1$**，就像是 $100-1=99$ 一样，**达到取反的效果**。（这里大家可以重点试验）
这里跨进制思考不是非常建议

2022-03-26 17:50 UTC, undefined-moe requested changes

2022-03-26 17:50 UTC, undefined-moe commented on docs/math/bit.md
> +1. 取出整数 $n$ 在二进制表示下的第 $k$ 位
做成页内链接快速导航至对应部分？

2022-03-26 17:50 UTC, undefined-moe commented on docs/math/bit.md
> +在实现这几个操作前，先来填一个和这些操作息息相关的表。
这是一个 wiki，不是一本教材，个人认为此设计不合理。

2022-03-26 17:50 UTC, undefined-moe commented on docs/math/bit.md
> +$$1\qquad0\qquad0\qquad1\qquad0\qquad1\qquad1\qquad0$$
pc 端占据大量版面，观感欠佳。看起来也没有什么必要。

2022-03-26 17:50 UTC, undefined-moe commented on docs/math/bit.md
> +    	可以发现，**对于按位与，只要一个操作位上的数字为 $0$，结果一定恒为 $0$**。
1000 & 0000 = 0000, 1111 & 0000 = 0000, 可以发现，**对于按位与，只要一个操作位上的数字为 $0$，结果一定恒为 $0$**。

完全可以简单的写进一行，没有必要占据大量版面，下同

2022-03-27 01:14 UTC, Pr-159 commented on docs/math/bit.md
> +    	可以发现，**对于按位与，只要一个操作位上的数字为 $0$，结果一定恒为 $0$**。
感谢建议，我修改一下。

2022-03-27 01:16 UTC, Pr-159 commented
> > > verbose and informal
> > 
> > 
> > Thanks for reading! I think OI-Wiki should me easier. I mean it should let newbies know how the algorithm work, so I wrote many more information. This is my first time to add something in this wiki. If there is some informal pleaces, please let me know . Can you give me more suggest? I'll fix it as fast as I can.
> 
> 作为 OI-Wiki 的词条，“详细推导”的内容可以是关于代码实现的进一步解释，但绝不应该是个人博客题解风格的教程式研究笔记；这意味着，“在实现这几个操作前，先来填一个和这些操作息息相关的表”“刚刚推出来的这些性质又与开头的操作有什么联系呢？”等 **不提供有效信息** 的语句不应出现。
> 
> 许多语句有明显的英文机翻痕迹，非常不符合中文的正式表述规范；如“是时候把本节开头的表补充完整了”与"It is time to finish the table we mentioned before."高度雷同。
> 
> 此外，文中对二进制“最后一位”“第一位”的解释明显与主流理解相悖；一般的，称任意进制表示的最低位为“第零位”。
> 
> 最后，不建议对不熟悉的领域进行大幅度甚至重构性的更改；语言的规范性应尽可能向 Wikipedia 的主要词条或 IEEE 等期刊的学术论文靠拢。



> > > verbose and informal
> > 
> > 
> > Thanks for reading! I think OI-Wiki should me easier. I mean it should let newbies know how the algorithm work, so I wrote many more information. This is my first time to add something in this wiki. If there is some informal pleaces, please let me know . Can you give me more suggest? I'll fix it as fast as I can.
> 
> OI-Wiki 不必苛求将
> 
> ```
> “乘x巴士到A处转y巴士到B处再步行至C处”
> ```
> 
> 等繁琐过程写成
> 
> ```
> “乘z地铁能直达C处”
> ```
> 
> 等巧妙精炼的表述，但绝对应避免
> 
> ```
> “那么应该怎么做到达C处呢？下面让我们来研究一下吧。首先呢，我们可以看一看这个A地，你想呀，如果要到A地的话，是可以坐x巴士的。既然坐了x巴士，那么到了A处我们就突然发现还有y巴士；现在我们来想一想y巴士有什么用，显然啊，y巴士可以让我们从A处到达B处。可是，我们的目标是到达C处而不是到达A处或者B处啊，所以到达了B处究竟有什么意义呢？原来，B处到C处竟然是可以步行抵达的呢。让我们来总结一下吧，总结：有x巴士可以到A处，想要到B处可以从A处乘巴士，乘的是y巴士，接着从B处想要到最终目的地C处就完全可以只凭步行啦！”
> ```
> 
> 等充斥着大量无效信息的informal表达。

现在我决定删除前面的推导过程，只保留剩下操作的推导，并精简化。这样是否可行？

感谢阅读。

2022-03-27 07:27 UTC, Saisyc commented
> > > > verbose and informal
> > > 
> > > 
> > > Thanks for reading! I think OI-Wiki should me easier. I mean it should let newbies know how the algorithm work, so I wrote many more information. This is my first time to add something in this wiki. If there is some informal pleaces, please let me know . Can you give me more suggest? I'll fix it as fast as I can.
> > 
> > 
> > 作为 OI-Wiki 的词条，“详细推导”的内容可以是关于代码实现的进一步解释，但绝不应该是个人博客题解风格的教程式研究笔记；这意味着，“在实现这几个操作前，先来填一个和这些操作息息相关的表”“刚刚推出来的这些性质又与开头的操作有什么联系呢？”等 **不提供有效信息** 的语句不应出现。
> > 许多语句有明显的英文机翻痕迹，非常不符合中文的正式表述规范；如“是时候把本节开头的表补充完整了”与"It is time to finish the table we mentioned before."高度雷同。
> > 此外，文中对二进制“最后一位”“第一位”的解释明显与主流理解相悖；一般的，称任意进制表示的最低位为“第零位”。
> > 最后，不建议对不熟悉的领域进行大幅度甚至重构性的更改；语言的规范性应尽可能向 Wikipedia 的主要词条或 IEEE 等期刊的学术论文靠拢。
> 
> > > > verbose and informal
> > > 
> > > 
> > > Thanks for reading! I think OI-Wiki should me easier. I mean it should let newbies know how the algorithm work, so I wrote many more information. This is my first time to add something in this wiki. If there is some informal pleaces, please let me know . Can you give me more suggest? I'll fix it as fast as I can.
> > 
> > 
> > OI-Wiki 不必苛求将
> > ```
> > “乘x巴士到A处转y巴士到B处再步行至C处”
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 等繁琐过程写成
> > ```
> > “乘z地铁能直达C处”
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 等巧妙精炼的表述，但绝对应避免
> > ```
> > “那么应该怎么做到达C处呢？下面让我们来研究一下吧。首先呢，我们可以看一看这个A地，你想呀，如果要到A地的话，是可以坐x巴士的。既然坐了x巴士，那么到了A处我们就突然发现还有y巴士；现在我们来想一想y巴士有什么用，显然啊，y巴士可以让我们从A处到达B处。可是，我们的目标是到达C处而不是到达A处或者B处啊，所以到达了B处究竟有什么意义呢？原来，B处到C处竟然是可以步行抵达的呢。让我们来总结一下吧，总结：有x巴士可以到A处，想要到B处可以从A处乘巴士，乘的是y巴士，接着从B处想要到最终目的地C处就完全可以只凭步行啦！”
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 等充斥着大量无效信息的informal表达。
> 
> 现在我决定删除前面的推导过程，只保留剩下操作的推导，并精简化。这样是否可行？
> 
> 感谢阅读。

期待你的修改，不过请注意“操作位”似乎不是比较明确的术语

2022-03-27 13:41 UTC, Early0v0 commented on docs/math/bit.md
> +$$7\qquad6\qquad5\qquad4\qquad3\qquad2\qquad1\qquad0$$
请加上行名，比如 “数值” 和 “位”

2022-03-27 13:41 UTC, Early0v0 commented on docs/math/bit.md
> +        $$
这边 markdown 挂掉了（

2022-03-27 13:41 UTC, Early0v0 commented on docs/math/bit.md
> +        $$
同上

2022-03-27 13:41 UTC, Early0v0 commented on docs/math/bit.md
> +        $$
同上

2022-03-27 13:41 UTC, Early0v0 commented on docs/math/bit.md
> +    为了去除前面的前导 $0$（此时为逻辑右移），可以加上一步 $\&\,1$，虽然最终结果不变，但是更加保险（有些编辑器仍采用逻辑右移）。
这应该不是保险的问题吧，应该就是必须

2022-03-27 14:08 UTC, Pr-159 commented
感谢阅读。

我会尽快修改。

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年3月27日 21:41
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [OI-wiki/OI-wiki] feat(math/bit): 更多的详细推导 (PR #3881)


@Early0v0 commented on this pull request.


In docs/math/bit.md<https://github.com/OI-wiki/OI-wiki/pull/3881#discussion_r835909078>:

> +$$1\qquad0\qquad0\qquad1\qquad0\qquad1\qquad1\qquad0$$







-```cpp



-// C++ Version



-// 将 a 的第 b 位设置为 0 ，最低位编号为 0



-int unsetBit(int a, int b) { return a & ~(1 << b); }



-```



+$$7\qquad6\qquad5\qquad4\qquad3\qquad2\qquad1\qquad0$$



请加上行名，比如 “数值” 和 “位”


In docs/math/bit.md<https://github.com/OI-wiki/OI-wiki/pull/3881#discussion_r835909195>:

> +   - 与常数 $1$ 进行操作



+



+        $$



+        \begin{array}{cc}



+        \quad\,\,\,\,\,1000\\



+        \underline{\&\,\,\,\,\,\,\,\,\,\,\,\, 0001\quad}\\



+        \quad\,\,\,\,\,0000



+        \end{array}



+        $$



+



+        $$



+        \begin{array}{cc}



+        \quad\,\,\,\,\,1111\\



+        \underline{\&\,\,\,\,\,\,\,\,\,\,\,\, 0001\quad}\\



+        \quad\,\,\,\,\,0001



+        \end{array}



+        $$



这边 markdown 挂掉了（


In docs/math/bit.md<https://github.com/OI-wiki/OI-wiki/pull/3881#discussion_r835909261>:

> +   - 与常数 $1$ 进行操作



+



+        $$



+        \begin{array}{cc}



+        \quad\,\,\,\,\,1000\\



+        \underline{\mid\,\,\,\,\,\,\,\,\,\,\,\,\,\, 0001\quad}\\



+        \quad\,\,\,\,\,1001



+        \end{array}



+        $$



+



+        $$



+        \begin{array}{cc}



+        \quad\,\,\,\,\,1111\\



+        \underline{\mid\,\,\,\,\,\,\,\,\,\,\,\,\,\, 0001\quad}\\



+        \quad\,\,\,\,\,1111



+        \end{array}



+        $$



同上


In docs/math/bit.md<https://github.com/OI-wiki/OI-wiki/pull/3881#discussion_r835909358>:

> +   - 与常数 $1$ 进行操作



+



+        $$



+        \begin{array}{cc}



+        \quad\,\,\,\,\,1000\\



+        \underline{\operatorname{xor}\,\,\,\,\,\,\, 0001\quad}\\



+        \quad\,\,\,\,\,1001



+        \end{array}



+        $$



+



+        $$



+        \begin{array}{cc}



+        \quad\,\,\,\,\,1111\\



+        \underline{\operatorname{xor}\,\,\,\,\,\,\, 0001\quad}\\



+        \quad\,\,\,\,\,1110



+        \end{array}



+        $$



同上


In docs/math/bit.md<https://github.com/OI-wiki/OI-wiki/pull/3881#discussion_r835909498>:

> +\begin{matrix}



+&\text{按位与}&\text{按位或}&\text{按位异或}\\



+\text{常数}&0/1&0/1&0/1\\



+\text{结果}&\text{恒为 $0$}/\text{不变}&\text{不变}/\text{恒为 $1$}&\text{不变}/\text{取反}



+\end{matrix}



+$$



+



+刚刚推出来的这些性质又与开头的操作有什么联系呢？



+



+- 操作一：「取出整数 $n$ 在二进制表示下的第 $k$ 位」



+



+    首先，考虑让操作位更容易操作，**把它放在整个串的末尾**。



+



+    可以使用右移操作，即 $n >> k$，把操作位移到末尾。



+



+    为了去除前面的前导 $0$（此时为逻辑右移），可以加上一步 $\&\,1$，虽然最终结果不变，但是更加保险（有些编辑器仍采用逻辑右移）。



这应该不是保险的问题吧，应该就是必须

―
Reply to this email directly, view it on GitHub<https://github.com/OI-wiki/OI-wiki/pull/3881#pullrequestreview-922453392>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AQGJZ5S2YQJB36DIEEPGVP3VCBQSBANCNFSM5RWAMYTQ>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-07-12 23:46 UTC, shuzhouliu requested changes
请resolve一下 @undefined-moe 等的suggestion

2022-07-15 02:54 UTC, Pr-159 commented
好的，感谢提醒，明天有个重要考试，考完以后就去看看

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Shuzhou ***@***.***>
发送时间: 2022年7月13日 7:46
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [OI-wiki/OI-wiki] feat(math/bit): 更多的详细推导 (PR #3881)


@shuzhouliu requested changes on this pull request.

请resolve一下 @undefined-moe<https://github.com/undefined-moe> 等的suggestion

―
Reply to this email directly, view it on GitHub<https://github.com/OI-wiki/OI-wiki/pull/3881#pullrequestreview-1036596829>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AQGJZ5SXKIVI7ZZ2T2O3QYLVTX7W7ANCNFSM5RWAMYTQ>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-09-13 09:02 UTC, Great-designer commented
作者看样子是鸽了

2022-10-02 04:06 UTC, Great-designer commented
这我也很难修，前面讨论太多了，并且以非支持意见为主，看一遍很费劲……

2022-10-02 06:50 UTC, Great-designer commented
观感很差。表格使用markdown表格，在latex中不要写中文汉字

2022-10-02 06:51 UTC, Great-designer commented
中间部分的latex公式似乎崩了

2022-10-02 06:52 UTC, Pr-159 commented
我看看吧，有时间的话一定修

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年10月2日 14:51
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [OI-wiki/OI-wiki] feat(math/bit): 更多的详细推导 (PR #3881)


中间部分的latex公式似乎崩了

―
Reply to this email directly, view it on GitHub<https://github.com/OI-wiki/OI-wiki/pull/3881#issuecomment-1264567686>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AQGJZ5XXU4PULXJDQPRY6MTWBEWHPANCNFSM5RWAMYTQ>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-10-02 06:53 UTC, Great-designer commented
啊这，作者还在，那很好

2022-10-02 09:35 UTC, Great-designer commented
试着修了一下

2022-10-02 09:37 UTC, Great-designer commented on docs/math/bit.md
> +1. 取出整数 $n$ 在二进制表示下的第 $k$ 位
感觉不必要

2022-10-02 09:38 UTC, Great-designer commented on docs/math/bit.md
> +    为了去除前面的前导 $0$（此时为逻辑右移），可以加上一步 $\&\,1$，虽然最终结果不变，但是更加保险（有些编辑器仍采用逻辑右移）。
这个是硬伤

2022-10-02 09:41 UTC, Great-designer commented on docs/math/bit.md
> +在实现这几个操作前，先来填一个和这些操作息息相关的表。
确实

2022-10-02 09:44 UTC, Great-designer commented
接下来有5个红叉，却没有文件冲突，我觉得是rebase的问题。这个看来要麻烦其他管理员看看

2022-10-02 09:45 UTC, Great-designer commented
另外我看了一眼评论区，有些评论过长，占据版面太大，所以进行了折叠处理。

2022-10-02 09:56 UTC, Great-designer commented
另外其实主要是格式问题，别的问题都不太大。

刚刚我把“先来试图填一个表格”删了。由于Wiki类似于论文，目的是展示（presentation），而不是教程，只需要在最后进行结论归纳的“总结陈词”就足够了。保留后面填写完毕的表格即可。

除非内容过于困难，实在难以理解，需要提前剧透一下后文，其余时候无需剧透，类似于“提前填表”大可不必。

2022-10-02 10:33 UTC, Tiphereth-A commented
> 另外我看了一眼评论区，有些评论过长，占据版面太大，所以进行了折叠处理。

可是那几个评论没 off-topic 吧, 也许 outdated 更合适些 🤔

2022-10-03 02:27 UTC, Great-designer commented
> 可是那几个评论没 off-topic 吧, 也许 outdated 更合适些 🤔

已将 outdated 的评论改为 outdated。

2022-10-11 07:34 UTC, Pr-159 commented
正确的（

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年9月13日 17:02
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [OI-wiki/OI-wiki] feat(math/bit): 更多的详细推导 (PR #3881)


作者看样子是鸽了

―
Reply to this email directly, view it on GitHub<https://github.com/OI-wiki/OI-wiki/pull/3881#issuecomment-1245112151>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AQGJZ5QQ7D7PZPHMAVFVTO3V6A7LRANCNFSM5RWAMYTQ>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-01-01 08:13 UTC, Great-designer commented
算了……感觉这个实在是太老了，救不过来

2023-01-01 08:13 UTC, closed without merging