feat(group-theory.md):添加半群、幺半群、环、域的定义
OI-wiki/OI-wiki pull request #3896
Opened 2022-04-03 23:44 UTC by wangr-x

为严格化的多项式代数作铺垫

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论您是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈您的感受
3. 如果您熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2022-04-04 07:00 UTC, Saisyc requested changes
英文翻译的一般词汇不应大写，“单位元”是比“标识元”更正规的名称，逆元需要分左右讨论（因为运算不必有交换律）

2022-04-04 09:34 UTC, wangr-x commented
逆元已经分左右讨论了

2022-04-04 09:40 UTC, wangr-x commented
请说明什么是“英文翻译的一般词汇”

2022-04-04 09:47 UTC, wangr-x commented
> 英文翻译的一般词汇不应大写，“单位元”是比“标识元”更正规的名称，逆元需要分左右讨论（因为运算不必有交换律）

逆元已经被定义为同时是左逆和右逆了，无需再分左右讨论。
此外，请详细说明哪些是“英文翻译的一般词汇”

2022-04-04 10:17 UTC, Saisyc commented
> > 英文翻译的一般词汇不应大写，“单位元”是比“标识元”更正规的名称，逆元需要分左右讨论（因为运算不必有交换律）
> 
> 逆元已经被定义为同时是左逆和右逆了，无需再分左右讨论。 此外，请详细说明哪些是“英文翻译的一般词汇”

意思就是该大写的词才大写，不要莫名其妙什么词都首字母大写

2022-04-04 10:18 UTC, Saisyc commented
> > 英文翻译的一般词汇不应大写，“单位元”是比“标识元”更正规的名称，逆元需要分左右讨论（因为运算不必有交换律）
> 
> 逆元已经被定义为同时是左逆和右逆了，无需再分左右讨论。 此外，请详细说明哪些是“英文翻译的一般词汇”

既然你讨论的是一般环而不是交换环，左逆和右逆的讨论就是必要的，逆元的存在性是不显然的。

2022-04-04 10:37 UTC, wangr-x commented
> > > 英文翻译的一般词汇不应大写，“单位元”是比“标识元”更正规的名称，逆元需要分左右讨论（因为运算不必有交换律）
> > 
> > 
> > 逆元已经被定义为同时是左逆和右逆了，无需再分左右讨论。 此外，请详细说明哪些是“英文翻译的一般词汇”
> 
> 既然你讨论的是一般环而不是交换环，左逆和右逆的讨论就是必要的，逆元的存在性是不显然的。

环处乘法逆元的定义与上文群的逆元定义相同，均为双侧的，引入过多不必要的定义会对初学者造成困扰

2022-04-04 10:38 UTC, wangr-x commented
> > > 英文翻译的一般词汇不应大写，“单位元”是比“标识元”更正规的名称，逆元需要分左右讨论（因为运算不必有交换律）
> > 
> > 
> > 逆元已经被定义为同时是左逆和右逆了，无需再分左右讨论。 此外，请详细说明哪些是“英文翻译的一般词汇”
> 
> 意思就是该大写的词才大写，不要莫名其妙什么词都首字母大写

这里的意思是哪些是应该大写的专有名词，如半群的英文 semigroup 无法确定是否是专有名词。

2022-04-04 10:40 UTC, Saisyc commented
> > > > 英文翻译的一般词汇不应大写，“单位元”是比“标识元”更正规的名称，逆元需要分左右讨论（因为运算不必有交换律）
> > > 
> > > 
> > > 逆元已经被定义为同时是左逆和右逆了，无需再分左右讨论。 此外，请详细说明哪些是“英文翻译的一般词汇”
> > 
> > 
> > 意思就是该大写的词才大写，不要莫名其妙什么词都首字母大写
> 
> 这里的意思是哪些是应该大写的专有名词，如半群的英文 semigroup 无法确定是否是专有名词。

你可以参考一些英文文献，显然绝大部分名词都是 **不需要** 大写的，尤其是 inverse element 还大写简直离谱

2022-04-04 10:44 UTC, wangr-x commented
> > > > > 英文翻译的一般词汇不应大写，“单位元”是比“标识元”更正规的名称，逆元需要分左右讨论（因为运算不必有交换律）
> > > > 
> > > > 
> > > > 逆元已经被定义为同时是左逆和右逆了，无需再分左右讨论。 此外，请详细说明哪些是“英文翻译的一般词汇”
> > > 
> > > 
> > > 意思就是该大写的词才大写，不要莫名其妙什么词都首字母大写
> > 
> > 
> > 这里的意思是哪些是应该大写的专有名词，如半群的英文 semigroup 无法确定是否是专有名词。
> 
> 你可以参考一些英文文献，显然绝大部分名词都是 **不需要** 大写的，尤其是 inverse element 还大写简直离谱

历史遗留问题，已经修复

2022-04-04 10:52 UTC, Saisyc approved these changes

2022-04-11 08:38 UTC, Saisyc requested changes
Abel 是人名，不应小写

2022-04-11 08:57 UTC, Saisyc reviewed
“标识元”似乎不是正规的名称

2022-04-11 12:13 UTC, wangr-x commented
> Abel 是人名，不应小写

此处使用的是形容词 'abelian' 而非名词 'Abel'，不属于人名范畴。

实际上大小写均可，具体可以参考 https://math.stackexchange.com/questions/1299414/why-lower-case-a-for-abelian-group-and-upper-case-c-for-cauchy-sequence

2022-04-11 12:17 UTC, wangr-x commented
> “标识元”似乎不是正规的名称

“标识元”可能是历史遗留的机翻问题，已经修复

2022-04-11 12:18 UTC, Saisyc commented
> > Abel 是人名，不应小写
> 
> 此处使用的是形容词 'abelian' 而非名词 'Abel'，不属于人名范畴。
> 
> 实际上大小写均可，具体可以参考 https://math.stackexchange.com/questions/1299414/why-lower-case-a-for-abelian-group-and-upper-case-c-for-cauchy-sequence
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/266cccaaccb0588e99a8d396e11f164eade2fb8ef3c50941974ea669d97ed0f8/68747470733a2f2f63646e2e737374617469632e6e65742f53697465732f6d6174682f496d672f6170706c652d746f7563682d69636f6e40322e706e673f763d346563316466326534396231">Mathematics Stack Exchange**[Why lower case "a" for "abelian group" and upper case "C" for "Cauchy sequence"?](https://math.stackexchange.com/questions/1299414/why-lower-case-a-for-abelian-group-and-upper-case-c-for-cauchy-sequence)**This has been bugging me. 
> >   Why is the lower case letter "a" used to spell "abelian group" when
> >   upper case letters are used to spell the terms, "Gaussian Integral",
> >   "Cantor set" or "Cauchy se...

似乎确实如此，不过en.wikipedia的词条名采用的还是大学（雾

2022-04-11 12:23 UTC, wangr-x commented
还是采用大写吧，避免后来人在这里提出同样的问题

2022-04-11 12:24 UTC, Saisyc commented
> 还是采用大写吧，避免后来人在这里提出同样的问题

我个人倾向于人名作为词根时保持大写

2022-04-11 12:28 UTC, hly1204 commented
> > Abel 是人名，不应小写
> 
> 此处使用的是形容词 'abelian' 而非名词 'Abel'，不属于人名范畴。
> 
> 实际上大小写均可，具体可以参考 https://math.stackexchange.com/questions/1299414/why-lower-case-a-for-abelian-group-and-upper-case-c-for-cauchy-sequence

个人来说不太喜欢“阿贝尔群”，而更喜欢 Able 群。。而且这样甚至无需添加注释。。。

2022-04-11 12:34 UTC, wangr-x commented
> > > > Abel 是人名，不应小写
> > > 
> > > 
> > > 此处使用的是形容词 'abelian' 而非名词 'Abel'，不属于人名范畴。
> > > 实际上大小写均可，具体可以参考 https://math.stackexchange.com/questions/1299414/why-lower-case-a-for-abelian-group-and-upper-case-c-for-cauchy-sequence
> > 
> > 
> > 个人来说不太喜欢“阿贝尔群”，而更喜欢 Abel 群（对不起之前 typo 了）。。而且这样甚至无需添加注释。。。

> 个人觉得这跟全英文时的 ‘abelian’ 不符，还是保持英文的原有风格。
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/266cccaaccb0588e99a8d396e11f164eade2fb8ef3c50941974ea669d97ed0f8/68747470733a2f2f63646e2e737374617469632e6e65742f53697465732f6d6174682f496d672f6170706c652d746f7563682d69636f6e40322e706e673f763d346563316466326534396231">Mathematics Stack Exchange**[Why lower case "a" for "abelian group" and upper case "C" for "Cauchy sequence"?](https://math.stackexchange.com/questions/1299414/why-lower-case-a-for-abelian-group-and-upper-case-c-for-cauchy-sequence)**This has been bugging me. 
> >   Why is the lower case letter "a" used to spell "abelian group" when
> >   upper case letters are used to spell the terms, "Gaussian Integral",
> >   "Cantor set" or "Cauchy se...

2022-04-11 12:52 UTC, wangr-x commented
> > > Abel 是人名，不应小写
> > 
> > 
> > 此处使用的是形容词 'abelian' 而非名词 'Abel'，不属于人名范畴。
> > 实际上大小写均可，具体可以参考 https://math.stackexchange.com/questions/1299414/why-lower-case-a-for-abelian-group-and-upper-case-c-for-cauchy-sequence
> 
> 个人来说不太喜欢“阿贝尔群”，而更喜欢 Abel 群（对不起之前 typo 了）。。而且这样甚至无需添加注释。。。

个人觉得这样未和全英文的 'abelian' 保持一致。

2022-05-22 10:54 UTC, Enter-tainer approved these changes

2022-05-22 10:56 UTC, Marcythm approved these changes

2022-05-22 10:57 UTC, merged