feat(poly/intro.md):添加形式幂级数环、多项式复合及复合逆、多项式欧几里得相关内容
OI-wiki/OI-wiki pull request #3899
Opened 2022-04-04 03:48 UTC by wangr-x

初稿，希望接下来能再作下简化。。。

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论您是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈您的感受
3. 如果您熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2022-04-04 06:46 UTC, Saisyc requested changes
混淆了序列卷积与多项式乘积的概念，英文的翻译及使用不规范，对逆的存在性讨论不太够充分，不能解决模多项式意义下的求逆问题。

2022-04-04 07:07 UTC, Saisyc reviewed
对于一般环 $R$，$R$ 上的形式幂级数环 $R[[x]]$ 是一个与向量空间类似的代数结构

更准确的说法是R[[x]]是R上的自由模

2022-04-04 07:14 UTC, wangr-x commented
模意义下乘法逆的讨论挪到了多项式欧几里得部分

2022-04-04 07:18 UTC, Saisyc commented
> 模意义下乘法逆的讨论挪到了多项式欧几里得部分

多项式商环与形式幂级数取模还是存在一些本质上的区别；此外，需要特别注意的是，辗转相除法并不是对于任意的环都能进行，这样你还需说明你所得到的多项式环是欧几里得环

2022-04-04 08:44 UTC, wangr-x commented
已完成欧几里得整环的讨论，并将形式幂级数环和多项式环作了一定的分离

2022-04-04 09:48 UTC, wangr-x commented
> > 模意义下乘法逆的讨论挪到了多项式欧几里得部分
> 
> 多项式商环与形式幂级数取模还是存在一些本质上的区别；此外，需要特别注意的是，辗转相除法并不是对于任意的环都能进行，这样你还需说明你所得到的多项式环是欧几里得环

已完成欧几里得整环的讨论，并将形式幂级数环和多项式环作了一定的分离

2022-04-04 12:40 UTC, wangr-x commented
有管理看一下还有什么问题吗

2022-04-04 13:28 UTC, xyf007 commented
通篇用专业名词的后果是劝退，，感觉完全起不到引入写效果

2022-04-05 01:02 UTC, Saisyc commented
> 通篇用专业名词的后果是劝退，，感觉完全起不到引入的效果

专业名词的使用是必要的，但是此文章确实缺失了许多关于动机（motivation）的解释和启发式引导，这或许是劝退感的重要成因

2022-04-05 06:01 UTC, wangr-x commented
> > 通篇用专业名词的后果是劝退，，感觉完全起不到引入的效果
> 
> 专业名词的使用是必要的，但是此文章确实缺失了许多关于动机（motivation）的解释和启发式引导，这或许是劝退感的重要成因

那我再作下完善

2022-04-05 07:27 UTC, wangr-x commented
> > 通篇用专业名词的后果是劝退，，感觉完全起不到引入的效果
> 
> 专业名词的使用是必要的，但是此文章确实缺失了许多关于动机（motivation）的解释和启发式引导，这或许是劝退感的重要成因

是否考虑给形式幂级数环单开一个页面？

2022-04-05 08:05 UTC, Great-designer commented
> > > 通篇用专业名词的后果是劝退，，感觉完全起不到引入的效果
> > 
> > 
> > 专业名词的使用是必要的，但是此文章确实缺失了许多关于动机（motivation）的解释和启发式引导，这或许是劝退感的重要成因
> 
> 是否考虑给形式幂级数单开一个页面？感觉作为引入无法做到简洁。

我早就提出过建议，把多项式和生成函数合在一个目录下。结果因为

“生成函数是一种描述数学问题或者模型的方式，类似一种数学语言

多项式是则包含了相关的抽象变换与计算方法”

遭到了否决。

上述讨论见

https://github.com/OI-wiki/OI-wiki/pull/3489

“生成函数”和“形式幂级数”基本上说的是一回事。

建议把上次否决的管理员at出来，请她/他再前来把这个想法否决一遍。

@sshwy 

https://github.com/sshwy

2022-04-05 08:10 UTC, Great-designer commented
> > > > 通篇用专业名词的后果是劝退，，感觉完全起不到引入的效果
> > > 
> > > 
> > > 专业名词的使用是必要的，但是此文章确实缺失了许多关于动机（motivation）的解释和启发式引导，这或许是劝退感的重要成因
> > 
> > 
> > 是否考虑给形式幂级数单开一个页面？感觉作为引入无法做到简洁。
> 
> 我早就提出过建议，把多项式和生成函数合在一个目录下。结果因为
> 
> “生成函数是一种描述数学问题或者模型的方式，类似一种数学语言
> 
> 多项式是则包含了相关的抽象变换与计算方法”
> 
> 遭到了否决。
> 
> 上述讨论见
> 
> #3489
> 
> “生成函数”和“形式幂级数”基本上说的是一回事。
> 
> 建议把上次否决的管理员at出来，请她/他再前来把这个想法否决一遍。
> 
> @sshwy
> 
> https://github.com/sshwy
> 
> > <img alt="" width="48" src="https://avatars.githubusercontent.com/u/34973312?v=4?s=400"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[sshwy - Overview](https://github.com/sshwy)**Roll to Death. | @OI-wiki. sshwy has 40 repositories available. Follow their code on GitHub.

“提出否决”是这样的。不能说否了A，然后后续的B以同样的理由出现，就默许，就坐视不管了，这样是违反一致性原则的。

否决请一否到底，每次出现复现的想法的时候，就应该把前一个提出过否决意见的人请出来，再把一模一样的话讲一遍。

未来如果这样的想法无数次出现，就会无数次的调用旧否决，再at一遍。这就是前代判例的作用。

2022-04-05 09:56 UTC, wangr-x commented
@sshwy

2022-04-05 11:01 UTC, wangr-x commented
> > > > 通篇用专业名词的后果是劝退，，感觉完全起不到引入的效果
> > > 
> > > 
> > > 专业名词的使用是必要的，但是此文章确实缺失了许多关于动机（motivation）的解释和启发式引导，这或许是劝退感的重要成因
> > 
> > 
> > 是否考虑给形式幂级数单开一个页面？感觉作为引入无法做到简洁。
> 
> 我早就提出过建议，把多项式和生成函数合在一个目录下。结果因为
> 
> “生成函数是一种描述数学问题或者模型的方式，类似一种数学语言
> 
> 多项式是则包含了相关的抽象变换与计算方法”
> 
> 遭到了否决。
> 
> 上述讨论见
> 
> #3489
> 
> “生成函数”和“形式幂级数”基本上说的是一回事。
> 
> 建议把上次否决的管理员at出来，请她/他再前来把这个想法否决一遍。
> 

其实我觉得更准确的说法是，

“多项式”侧重于代数，将幂级数看作单一的对象去研究。

“生成函数”侧重于和数论、组合方面的联系，是应用性的。

2022-04-05 11:05 UTC, yzhx233666 commented
> > > > > 通篇用专业名词的后果是劝退，，感觉完全起不到引入的效果
> > > > 
> > > > 
> > > > 专业名词的使用是必要的，但是此文章确实缺失了许多关于动机（motivation）的解释和启发式引导，这或许是劝退感的重要成因
> > > 
> > > 
> > > 是否考虑给形式幂级数单开一个页面？感觉作为引入无法做到简洁。
> > 
> > 
> > 我早就提出过建议，把多项式和生成函数合在一个目录下。结果因为
> > “生成函数是一种描述数学问题或者模型的方式，类似一种数学语言
> > 多项式是则包含了相关的抽象变换与计算方法”
> > 遭到了否决。
> > 上述讨论见
> > #3489
> > “生成函数”和“形式幂级数”基本上说的是一回事。
> > 建议把上次否决的管理员at出来，请她/他再前来把这个想法否决一遍。
> 
> 其实我觉得更准确的说法是，
> 
> “多项式”侧重于代数，将幂级数看作单一的对象去研究。
> 
> “生成函数”侧重于和数论、组合方面的联系，是应用性的。

所以。。。请问真的有非Au选手需要学形式幂级数环吗

2022-04-05 12:54 UTC, werner-yin commented
最后补充的**参考资料与拓展阅读**部分还是不要使用作者 fork 仓库的地址吧

2022-04-05 12:59 UTC, yzhx233666 commented
建议单开一个页面，现在的“简介”确实对多项式入门者较不友好，容易使有兴趣与需要的同学产生误解

2022-04-05 13:03 UTC, yzhx233666 commented
现在的简介，感觉与普及知识这一初衷已经背道而驰了，反倒是给人一种编写者在炫耀学识的感觉。另外，请问 @wangr-x 为什么要将文末的参考资料使用您的 fork 仓库的地址呢

2022-04-05 19:53 UTC, Saisyc requested changes
文中关于多项式复合的结论有误，请考虑g=x^m的情形

作者对于微分和exp的理解有纰漏，文中对多项式求导和多项式exp的讨论存在一些根本性的问题

2022-04-05 20:14 UTC, Saisyc reviewed
对于任意域 $P$ 上的多项式环 $P[x]$，  
    多项式均可唯一因式分解，且可用欧几里得算法计算最大公因式。

这个结论真的成立吗？

2022-04-05 20:55 UTC, Saisyc commented
> ```
> 对于任意域 $P$ 上的多项式环 $P[x]$，  
> 多项式均可唯一因式分解，且可用欧几里得算法计算最大公因式。
> ```
> 
> 
>      
>   
> 
> 这个结论真的成立吗？

@wangr-x 令域F是（关于y的）一次项系数模m为0的整系数多项式的分式域，显然F上的多项式环F[x]不唯一分解；我推测你是误认为代数基本定理在任意域上显然成立而得出的此结论

综合全文而言，较为冒昧的，我认为作者的抽象代数和微分学水平不太足以**足够良好**地介绍多项式环和形式幂级数环的重要性质；此后，若非特别必要，我将放弃对#3899的跟进

2022-04-06 07:20 UTC, wangr-x commented
> 文中关于多项式复合的结论有误，请考虑g=x^m的情形
> 
> 作者对于微分和exp的理解有纰漏，文中对多项式求导和多项式exp的讨论存在一些根本性的问题

多项式复合对于 g=x^m 的讨论没有问题，但复合的结论确实存在问题，已经修复。

对于微分和 exp 存在的问题，一方面是因为其依赖多项式复合方面的结论，另一方面，它们 **极度依赖** 环 R 的性质。
（比如一般环上的导数无法公理化定义）

2022-04-06 07:32 UTC, wangr-x commented
目前最大的问题在于，环 R 的性质对其上多项式的性质影响巨大，很难对适用范围进行分类。

《信息学竞赛中的生成函数计算理论框架》给出的分类是实用性的，而非理论性的。

2022-04-06 07:41 UTC, EntropyIncreaser commented on docs/math/poly/intro.md
> +[HALF-GCD](https://loj.ac/p/172) 允许我们在 $O(n\log n)$ 时间内计算多项式欧几里得。
这里复杂度应当是两个 log

2022-04-06 07:50 UTC, wangr-x commented on docs/math/poly/intro.md
> +[HALF-GCD](https://loj.ac/p/172) 允许我们在 $O(n\log n)$ 时间内计算多项式欧几里得。
已修正，还有什么问题吗

2022-04-06 08:18 UTC, Saisyc commented
> > 文中关于多项式复合的结论有误，请考虑g=x^m的情形
> > 作者对于微分和exp的理解有纰漏，文中对多项式求导和多项式exp的讨论存在一些根本性的问题
> 
> 多项式复合对于 g=x^m 的讨论没有问题，但复合的结论确实存在问题，已经修复。
> 
> 对于微分和 exp 存在的问题，我认为一方面是因为其依赖多项式复合方面的结论，另一方面，它们 **极度依赖** 环 R 的性质。 （比如一般环上的导数无法公理化定义）



> > 文中关于多项式复合的结论有误，请考虑g=x^m的情形
> > 作者对于微分和exp的理解有纰漏，文中对多项式求导和多项式exp的讨论存在一些根本性的问题
> 
> 多项式复合对于 g=x^m 的讨论没有问题，但复合的结论确实存在问题，已经修复。
> 
> 对于微分和 exp 存在的问题，我认为一方面是因为其依赖多项式复合方面的结论，另一方面，它们 **极度依赖** 环 R 的性质。 （比如一般环上的导数无法公理化定义）

多项式环上的微分所需要的拓扑比较trivial；但我认为更重要的是，在已经给出了多项式的导数的情况下，用导数等于自身且0处的值为1定义出exp是自然且足够简单的

2022-04-06 08:22 UTC, Saisyc commented
> > 文中关于多项式复合的结论有误，请考虑g=x^m的情形
> > 作者对于微分和exp的理解有纰漏，文中对多项式求导和多项式exp的讨论存在一些根本性的问题
> 
> 多项式复合对于 g=x^m 的讨论没有问题，但复合的结论确实存在问题，已经修复。
> 
> 对于微分和 exp 存在的问题，我认为一方面是因为其依赖多项式复合方面的结论，另一方面，它们 **极度依赖** 环 R 的性质。 （比如一般环上的导数无法公理化定义）

g_0=0 确实无误，我将其错看为了g=0；但需要注意f,g拥有一些特殊的相关性时，其复合可能是可行的

此外，多项式环上的微分所需要的拓扑比较trivial；但我认为更重要的是，在已经给出了多项式的导数的情况下，用导数等于自身且0处的值为1定义出exp是自然且足够简单的

2022-04-06 08:23 UTC, Saisyc commented on docs/math/poly/intro.md
> +[HALF-GCD](https://loj.ac/p/172) 允许我们在 $O(n\log n)$ 时间内计算多项式欧几里得。
@wangr-x 关于这一点你可参考EntropyIncreaser的知乎文章

2022-04-06 08:26 UTC, Saisyc commented
> 目前最大的问题在于，环 R 的性质对其上多项式的性质影响巨大，很难对适用范围进行分类。
> 
> 《信息学竞赛中的生成函数计算理论框架》给出的分类是实用性的，而非理论性的。

我认为对于绝大部分OIer，可能只需要介绍整数、实数、复数的多项式环，及其取模的情形

2022-04-06 08:26 UTC, wangr-x commented
> > > 文中关于多项式复合的结论有误，请考虑g=x^m的情形
> > > 作者对于微分和exp的理解有纰漏，文中对多项式求导和多项式exp的讨论存在一些根本性的问题
> > 
> > 
> > 多项式复合对于 g=x^m 的讨论没有问题，但复合的结论确实存在问题，已经修复。
> > 对于微分和 exp 存在的问题，我认为一方面是因为其依赖多项式复合方面的结论，另一方面，它们 **极度依赖** 环 R 的性质。 （比如一般环上的导数无法公理化定义）
> 
> g_0=0 确实无误，我将其错看为了g=0；但需要注意f,g拥有一些特殊的相关性时，其复合可能是可行的
> 
> 此外，多项式环上的微分所需要的拓扑比较trivial；但我认为更重要的是，在已经给出了多项式的导数的情况下，用导数等于自身且0处的值为1定义出exp是自然且足够简单的

确实是一个有效的方法！这样形式幂级数 exp 的定义不必要求包含有理数域为其子域了

2022-04-06 08:29 UTC, Saisyc commented
> > > > 文中关于多项式复合的结论有误，请考虑g=x^m的情形
> > > > 作者对于微分和exp的理解有纰漏，文中对多项式求导和多项式exp的讨论存在一些根本性的问题
> > > 
> > > 
> > > 多项式复合对于 g=x^m 的讨论没有问题，但复合的结论确实存在问题，已经修复。
> > > 对于微分和 exp 存在的问题，我认为一方面是因为其依赖多项式复合方面的结论，另一方面，它们 **极度依赖** 环 R 的性质。 （比如一般环上的导数无法公理化定义）
> > 
> > 
> > g_0=0 确实无误，我将其错看为了g=0；但需要注意f,g拥有一些特殊的相关性时，其复合可能是可行的
> > 此外，多项式环上的微分所需要的拓扑比较trivial；但我认为更重要的是，在已经给出了多项式的导数的情况下，用导数等于自身且0处的值为1定义出exp是自然且足够简单的
> 
> 确实是一个有效的方法！这样形式幂级数 exp 的定义不必要求包含有理数域为其子域了

还需注意sin和cos可以直接由exp直接导出，但是tan会出现形式幂级数的分式形式

2022-04-06 08:30 UTC, wangr-x commented
> > 目前最大的问题在于，环 R 的性质对其上多项式的性质影响巨大，很难对适用范围进行分类。
> > 《信息学竞赛中的生成函数计算理论框架》给出的分类是实用性的，而非理论性的。
> 
> 我认为对于绝大部分OIer，可能只需要介绍整数、实数、复数的多项式环，及其取模的情形

多项式环上的多项式环（即多元多项式）

> > > > > 文中关于多项式复合的结论有误，请考虑g=x^m的情形
> > > > > 作者对于微分和exp的理解有纰漏，文中对多项式求导和多项式exp的讨论存在一些根本性的问题
> > > > 
> > > > 
> > > > 多项式复合对于 g=x^m 的讨论没有问题，但复合的结论确实存在问题，已经修复。
> > > > 对于微分和 exp 存在的问题，我认为一方面是因为其依赖多项式复合方面的结论，另一方面，它们 **极度依赖** 环 R 的性质。 （比如一般环上的导数无法公理化定义）
> > > 
> > > 
> > > g_0=0 确实无误，我将其错看为了g=0；但需要注意f,g拥有一些特殊的相关性时，其复合可能是可行的
> > > 此外，多项式环上的微分所需要的拓扑比较trivial；但我认为更重要的是，在已经给出了多项式的导数的情况下，用导数等于自身且0处的值为1定义出exp是自然且足够简单的
> > 
> > 
> > 确实是一个有效的方法！这样形式幂级数 exp 的定义不必要求包含有理数域为其子域了
> 
> 还需注意sin和cos可以直接由exp直接导出，但是tan会出现形式幂级数的分式形式

如果限制到实数域上，这一做法或许不可行

2022-04-06 08:32 UTC, Saisyc commented
> > > > > > 文中关于多项式复合的结论有误，请考虑g=x^m的情形
> > > > > > 作者对于微分和exp的理解有纰漏，文中对多项式求导和多项式exp的讨论存在一些根本性的问题
> > > > > 
> > > > > 
> > > > > 多项式复合对于 g=x^m 的讨论没有问题，但复合的结论确实存在问题，已经修复。
> > > > > 对于微分和 exp 存在的问题，我认为一方面是因为其依赖多项式复合方面的结论，另一方面，它们 **极度依赖** 环 R 的性质。 （比如一般环上的导数无法公理化定义）
> > > > 
> > > > 
> > > > g_0=0 确实无误，我将其错看为了g=0；但需要注意f,g拥有一些特殊的相关性时，其复合可能是可行的
> > > > 此外，多项式环上的微分所需要的拓扑比较trivial；但我认为更重要的是，在已经给出了多项式的导数的情况下，用导数等于自身且0处的值为1定义出exp是自然且足够简单的
> > > 
> > > 
> > > 确实是一个有效的方法！这样形式幂级数 exp 的定义不必要求包含有理数域为其子域了
> > 
> > 
> > 还需注意sin和cos可以直接由exp直接导出，但是tan会出现形式幂级数的分式形式
> 
> 如果限制到实数域上，这一做法或许不可行

为了定义的一致性和简洁性，我认为进行有必要的扩域是有必要的

2022-04-06 09:14 UTC, wangr-x commented
目前存在一个问题，就是**有限域**上**形式幂级数**的积分如何定义

因为只要度数足够大的情况下，

> > > > > > > 文中关于多项式复合的结论有误，请考虑g=x^m的情形
> > > > > > > 作者对于微分和exp的理解有纰漏，文中对多项式求导和多项式exp的讨论存在一些根本性的问题
> > > > > > 
> > >  
> > >  多项式复合对于 g=x^m 的讨论没有问题，但复合的结论确实存在问题，已经修复。
> > >  对于微分和 exp 存在的问题，我认为一方面是因为其依赖多项式复合方面的结论，另一方面，它们 **极度依赖** 环 R 的性质。 （比如一般环上的导数无法公理化定义）
> > 
> > 
> > g_0=0 确实无误，我将其错看为了g=0；但需要注意f,g拥有一些特殊的相关性时，其复合可能是可行的
> > 此外，多项式环上的微分所需要的拓扑比较trivial；但我认为更重要的是，在已经给出了多项式的导数的情况下，用导数等于自身且0处的值为1定义出exp是自然且足够简单的
> 
> 
>  确实是一个有效的方法！这样形式幂级数 exp 的定义不必要求包含有理数域为其子域了

收回我刚才的说法，对于 Zp 上的多项式环，恒有 (x^p)'=0

这时 x^{p-1} 的积分和 exp 是未定义的。尽管在 OI 的数据范围内（如 10^5），截取有限项已足够。

2022-04-06 09:18 UTC, wangr-x commented
此外，OI 范围内形式导数已经足够，且一般的多项式环上并无拓扑结构

2022-04-06 09:28 UTC, Saisyc commented
> > > > > 文中关于多项式复合的结论有误，请考虑g=x^m的情形
> > > > > 作者对于微分和exp的理解有纰漏，文中对多项式求导和多项式exp的讨论存在一些根本性的问题
> > > > 
> > > > 
> > > > 多项式复合对于 g=x^m 的讨论没有问题，但复合的结论确实存在问题，已经修复。
> > > > 对于微分和 exp 存在的问题，我认为一方面是因为其依赖多项式复合方面的结论，另一方面，它们 **极度依赖** 环 R 的性质。 （比如一般环上的导数无法公理化定义）
> > > 
> > > 
> > > g_0=0 确实无误，我将其错看为了g=0；但需要注意f,g拥有一些特殊的相关性时，其复合可能是可行的
> > > 此外，多项式环上的微分所需要的拓扑比较trivial；但我认为更重要的是，在已经给出了多项式的导数的情况下，用导数等于自身且0处的值为1定义出exp是自然且足够简单的
> > 
> > 
> > 确实是一个有效的方法！这样形式幂级数 exp 的定义不必要求包含有理数域为其子域了
> 
> 收回我刚才的说法，对于 Zp 上的多项式环，恒有 (x^p)'=0
> 
> 这时 x^{p-1} 的积分和 exp 是未定义的。尽管在 OI 的数据范围内（如 10^5），截取有限项已足够。

请注意区分R上的多项式环R[x]与R上的多项式函数

2022-04-06 09:34 UTC, Saisyc commented
> 此外我认为，OI 范围内形式导数已经足够，且一般的多项式环上并无拓扑结构

R[x]的微分依赖于R[Δx][x]的拓扑，一个平凡的R[Δx]拓扑可以产生的结果是：Δx→0时R[Δx]中元素的极限是其常数项。

不过，形式导数确实似乎已足够，但请注明“形式导数”而与“导数”做区分

2022-04-06 10:10 UTC, Saisyc reviewed
我其实想过要不要将 exp(ln(*)/2) 作为 sqrt 的定义

2022-04-06 10:30 UTC, Great-designer commented
> > ```
> > 对于任意域 $P$ 上的多项式环 $P[x]$，  
> > 多项式均可唯一因式分解，且可用欧几里得算法计算最大公因式。
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这个结论真的成立吗？
> 
> 这个结论真的成立，不过一定要注意在一般环上不成立
> 
> 综合全文而言，较为冒昧的，我认为作者的抽象代数和微分学水平有可能不太足以**足够良好**地介绍多项式环和形式幂级数环的重要性质（还有一种可能是需要进行一定的学术写作练习～）；此后，若非必要，我可能不太会对#3899跟进

意思是任意域上的多项式环均为Euclid环，Euclid是最强的条件，因而最后推得唯一分解。推得只用了环本身的性质，与域和多项式无关。
代数基本定理说的是唯一分解的不可约式在复数域条件下都是一次式。推论是实数域条件下都是一次或二次式。
（试图翻译这段对话）

2022-04-06 10:35 UTC, Great-designer commented
> 我其实想过要不要将 exp(ln(*)/2) 作为 sqrt 的定义

这个在复变函数那边还真就是这么定义的，sqrt是exp套ln。由于ln本身是Ln的主值支，sqrt本身也只是一个主值支。

在p-adic数中也可以这么定义（限于p为奇素数的情形）。到2-adic数寻找平方元的开平方结果，则是不完备的，一个平方元能开出4个根。

2022-04-06 10:48 UTC, wangr-x commented
> > > > > 文中关于多项式复合的结论有误，请考虑g=x^m的情形
> > > > > 作者对于微分和exp的理解有纰漏，文中对多项式求导和多项式exp的讨论存在一些根本性的问题
> > > > 
> > > > 
> > > > 多项式复合对于 g=x^m 的讨论没有问题，但复合的结论确实存在问题，已经修复。
> > > > 对于微分和 exp 存在的问题，我认为一方面是因为其依赖多项式复合方面的结论，另一方面，它们 **极度依赖** 环 R 的性质。 （比如一般环上的导数无法公理化定义）
> > > 
> > > 
> > > g_0=0 确实无误，我将其错看为了g=0；但需要注意f,g拥有一些特殊的相关性时，其复合可能是可行的
> > > 此外，多项式环上的微分所需要的拓扑比较trivial；但我认为更重要的是，在已经给出了多项式的导数的情况下，用导数等于自身且0处的值为1定义出exp是自然且足够简单的
> > 
> > 
> > 确实是一个有效的方法！这样形式幂级数 exp 的定义不必要求包含有理数域为其子域了
> 
> 还需注意sin和cos可以直接由exp直接导出，但是tan会出现形式幂级数的分式形式


> > > ```
> > > 对于任意域 $P$ 上的多项式环 $P[x]$，  
> > > 多项式均可唯一因式分解，且可用欧几里得算法计算最大公因式。
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 这个结论真的成立吗？
> > 
> > 
> > 这个结论真的成立，不过一定要注意在一般环上不成立
> > 综合全文而言，较为冒昧的，我认为作者的抽象代数和微分学水平有可能不太足以**足够良好**地介绍多项式环和形式幂级数环的重要性质（还有一种可能是需要进行一定的学术写作练习～）；此后，若非必要，我可能不太会对#3899跟进
> 
> 意思是任意域上的多项式环均为Euclid环，Euclid是最强的条件，因而最后推得唯一分解。推得只用了环本身的性质，与域和多项式无关。 代数基本定理说的是唯一分解的不可约式在复数域条件下都是一次式。推论是实数域条件下都是一次或二次式。 （试图翻译这段对话）

因为是给初学者的介绍，所以略去了欧几里得环部分。

2022-04-06 11:02 UTC, wangr-x commented
定义方面本人有两个问题：
- 反三角函数沿用复变函数定义是否是自然的？
- 如果限制在实数域内，用与 exp 相同的方法定义三角函数是否是自然的
  （如 cos(0)=1,cos'(0)=0,cos''(x)=cos(x)）

2022-04-06 11:40 UTC, wangr-x commented
顺带一提，在 wikipedia 中，开根用 exp 或广义二项式定义都是正确的

2022-04-06 12:04 UTC, Great-designer commented
> 定义方面本人有两个问题：
> 
> * 反三角函数沿用复变函数定义是否是自然的？
> * 如果限制在实数域内，用与 exp 相同的方法定义三角函数是否是自然的
>   （如 cos(0)=1,cos'(0)=0,cos''(x)=cos(x)）

关于这个我只能说自己的pr那边的情况。如果不适用这个pr可以无视。一切仅供参考。
* 关于反三角：
因为文章前半部分，我只想讲明白单位根，然后倒着构建知识体系，所以根本没有讲复变函数的反三角。
而文章末尾C和C++的复数头文件里面，有反三角，这是罗列的客观事实。
一是OI用不到复数自变量的反三角，二是前文倒着构建知识体系也用不到反三角，所以提一句就完了。
* 关于实数域的余弦函数：
对于高中生而言，不管书上怎么写，现实情况大多是直接背诵函数图像，所谓“心中有图”。图像的定义不够严谨，却实用，当下就能落到纸面上，拿出来就能解题。
对于OI-Wiki，由于余弦函数本身写在初高中课本上，甚至是入门内容，就连高一的物理课本有关力学的分析，都会不加证明的直接使用余弦函数。OI-Wiki本身没必要收录“实数域内的余弦函数”这种东西。
复数采用 exp 的定义方法，完全是因为简洁直观。和上文“心中有图”的道理完全一致。
* 回到本pr
到多项式这里，随便怎么定义，只要直观并方便。
沿用复数是可行的一种思路，不排除其他思路。证明多个表述的等价性，也是可以考虑的办法。

2022-04-08 04:40 UTC, sshwy commented
我就简单说，大家看看就好（
专业名词不是不能有，而是不能光有这个词没有解释，就好像写代码声明的变量必需有对应的定义
要达到引入的效果，合理安排文章顺序（概念的引入顺序）完全可以做到
活用markdown链接语法可以使文章的结结构在一定程度上摆脱完全线性

2022-04-20 03:40 UTC, wangr-x commented
因为本人已经退役，这个 pr 需要换个人接手

2022-04-22 08:06 UTC, Great-designer commented
已经转移至

https://github.com/OI-wiki/OI-wiki/pull/3928

2022-05-22 11:01 UTC, Enter-tainer commented
> 已经转移至
> 
> #3928

hello, 请问这个pr可以关掉吗（如果说内容已经移动过去了的话）

2022-05-23 10:54 UTC, Great-designer commented
> > 已经转移至
> > #3928
> 
> hello, 请问这个pr可以关掉吗（如果说内容已经移动过去了的话）

内容已经移动过去了：D

2022-05-23 11:05 UTC, closed without merging