feat(math/probability/*): 完善概率论相关理论的讨论
OI-wiki/OI-wiki pull request #3903
Opened 2022-04-06 15:04 UTC by MegaOwIer

主要修改：
1. 将原有“概率初步”页面重命名为“快速上手概率论”并移除其中有关概率论公理化定义和连续型随机变量的讨论。
2. 新增一系列文档完善上面删掉的讨论。

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
3. 不论您是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈您的感受
4. 如果您熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
5. 请**尽量**保持跟进直到它被 merge 或 close

2022-04-06 17:13 UTC, Saisyc requested changes
删除公理化定义，忽略测度论在概率论中起到的重要作用，对于概率论的学习具有严重的害处，可能会导致许多看似直观的悖论

此外，“事件空间”在中文文献中似乎一般称为“事件域”

2022-04-06 17:30 UTC, MegaOwIer commented
> 删除公理化定义，忽略测度论在概率论中起到的重要作用，对于概率论的学习具有严重的害处，可能会导致许多看似直观的悖论

原有的单个页面内容过于杂乱，看起来像是给完全没有接触过相关知识的选手准备的“快速上手指南”。我认为公理化定义中复杂的符号表述并不利于帮助一个啥都不会的新手在短时间内一种直观上的理解。

另一方面您所强调的公理化定义的重要性是无所争辩的，因此我实际上只是将相关内容移到了新加入的其他文档中。

> 此外，“事件空间”在中文文献中似乎一般称为“事件域”

关于专有名词的使用我明天会修改，今天宿舍已经断电了不太好搞orz

2022-04-06 17:37 UTC, Saisyc commented
> > 删除公理化定义，忽略测度论在概率论中起到的重要作用，对于概率论的学习具有严重的害处，可能会导致许多看似直观的悖论
> 
> 原有的单个页面内容过于杂乱，看起来像是给完全没有接触过相关知识的选手准备的“快速上手指南”。我认为公理化定义中复杂的符号表述并不利于帮助一个啥都不会的新手在短时间内一种直观上的理解。
> 
> 另一方面您所强调的公理化定义的重要性是无所争辩的，因此我实际上只是将相关内容移到了新加入的其他文档中。
> 
> > 此外，“事件空间”在中文文献中似乎一般称为“事件域”
> 
> 关于专有名词的使用我明天会修改，今天宿舍已经断电了不太好搞orz

辛苦了，概率论的公理化定义可能对于新手不太友好，先直观理解再学习严格内容是可行的；但请务必注意，在表述非严格的直观性理解的概念时，一定要避免该直观理解可能导致的问题，因为许多所谓的直观只在有限的样本空间中成立，一个最典型的例子是：不是所有的样本空间的子集都一定能在事件域内

一旦产生了如是般的误解，对于后续的学习与纠正将是灾难性的

2022-04-09 21:10 UTC, Saisyc reviewed
个人观点：不加定义地使用“随机事件”“样本空间”的概念对概率论的学习可能是有害的；但对于快速应用而言可能是有益的，因此我给出了Comment

一个与之类似的问题是，大部分人在使用“集合”时并未真正系统学习过集合论；但是一个重要区别是：大多数时候计算机科学研究的数学总是在一个具体的良定义的集合上的，但OI中的许多概率论问题对于新手而言是在一个直观上以为显然但实质上根本并不清晰的样本空间中，很容易导致“悖论”

2022-04-09 22:22 UTC, MegaOwIer commented
> 个人观点：不加定义地使用“随机事件”“样本空间”的概念对概率论的学习可能是有害的；但对于快速应用而言可能是有益的，因此我给出了Comment
> 
> 一个与之类似的问题是，大部分人在使用“集合”时并未真正系统学习过集合论；但是一个重要区别是：大多数时候计算机科学研究的数学总是在一个具体的良定义的集合上的，但OI中的许多概率论问题对于新手而言是在一个直观上以为显然但实质上根本并不清晰的样本空间中，很容易导致“悖论”

我之前把“随机事件”“样本空间”这两个概念移出这个页面主要是因为印象中在我上高中时课本上并没有强调或者根本没有提到所谓“样本空间”的概念，对“随机事件”的定义也仅限于“结果不确定的事件”。但刚才去查了一下貌似最新版的课本里已经有了相关表述，那这步操作就确实显得不是很必要了。

稍后会有一个 commit 修改这个事情。

2022-04-10 01:10 UTC, Saisyc reviewed
一个比较麻烦的问题是，在OI中，尤其是Markov类的问题，样本空间很多时候不是有限集

2022-04-10 08:40 UTC, MegaOwIer commented
> 一个比较麻烦的问题是，在OI中，尤其是Markov类的问题，样本空间很多时候不是有限集

能给个具体点的例子吗，印象中没觉得这玩意有多常见啊...

2022-04-10 08:53 UTC, EntropyIncreaser commented
他的意思应该是随机游走

2022-04-10 09:14 UTC, Saisyc commented
> > 一个比较麻烦的问题是，在OI中，尤其是Markov类的问题，样本空间很多时候不是有限集
> 
> 能给个具体点的例子吗，印象中没觉得这玩意有多常见啊...

eg：抛硬币，求首次出现正面时抛掷次数的期望值

2022-04-10 12:05 UTC, MegaOwIer commented
那感觉目前最省事的解决方案就是直接删掉原来那个速成手册性质的页面了（）

2022-04-10 12:13 UTC, Saisyc commented
> 那感觉目前最省事的解决方案就是直接删掉原来那个速成手册性质的页面了（）

速成性质的概率论可能更适合中小学教学使学生对概率论产生较为朴素的理解，但或许真的不太适合作为wiki的正文

2022-04-10 12:20 UTC, MegaOwIer commented
> > 那感觉目前最省事的解决方案就是直接删掉原来那个速成手册性质的页面了（）
> 
> 速成性质的概率论可能更适合中小学教学使学生对概率论产生较为朴素的理解，但或许真的不太适合作为wiki的正文

保留那个页面主要是担心会导致一些选手博客/题解引用此界面的链接失效，直接删了真的呆胶布吗

2022-04-19 07:20 UTC, Enter-tainer commented on docs/math/probability/random-variable.md
> +    1, & \omega \in A \newline
```suggestion
    1, & \omega \in A \\
```

2022-04-19 07:22 UTC, Enter-tainer commented on docs/math/probability/exp-var.md
> +    1, & \omega \in A \newline
```suggestion
    1, & \omega \in A \\
```

2022-04-19 07:22 UTC, Enter-tainer commented on docs/math/probability/exp-var.md
> +        1, & k \leq d \newline
```suggestion
        1, & k \leq d \\
```

2022-04-19 07:58 UTC, Enter-tainer commented
LaTeX build is happy now!

2022-04-19 08:00 UTC, Enter-tainer submitted a review, later dismissed
辛苦了

2022-04-19 14:25 UTC, MegaOwIer commented
概率论部分需要写的感觉暂时就这么多（？）
不知道还有没有需要调整或增加的内容。

2022-04-19 14:27 UTC, Enter-tainer approved these changes

2022-05-22 09:31 UTC, MegaOwIer commented
所以有没有更进一步的修改意见啊（）

2022-07-15 03:51 UTC, Great-designer commented
如果OI选手上大学后，想要学习人工智能（算法）领域的话（事实上在我的观测范围内多数OI选手上大学后会选择这个领域，还有计算机视觉等等），概率论是最为最为基础的内容，所有对于梯度下降算法的优化全部用到了概率论或者信息论，论文里到处都是“P”（概率）、“E”（期望）、“H”（熵）。因此，深入地多写一些并不过分。

我个人上大学后概率论学得很烂，因此也没有涉足人工智能领域。这方面也可能是未来OI的发展方向，还是交给高手们写写。

2022-07-25 10:22 UTC, Saisyc reviewed
删除的 概率论公理化定义和连续型随机变量 可能找个词条放着比较好

2022-07-25 10:22 UTC, Saisyc commented on docs/math/probability/exp-var.md
> +设随机变量 $X$ 的分布函数为 $F(x)$，若 [Stieltjes 积分](https://baike.baidu.com/item/%E9%BB%8E%E6%9B%BC%EF%BC%8D%E6%96%AF%E8%92%82%E5%B0%94%E6%9D%B0%E6%96%AF%E7%A7%AF%E5%88%86/15572209)
注意到你使用的参考文献中提到：

    黎曼－斯蒂尔杰斯积分有数种定义方式，但不是每种定义方式都是彼此等价的。

故应当指明采用的定义或更换参考文献；此外，百度百科中的数学词条许多都错漏百出。

2022-07-25 10:49 UTC, MegaOwIer commented on docs/math/probability/exp-var.md
> +设随机变量 $X$ 的分布函数为 $F(x)$，若 [Stieltjes 积分](https://baike.baidu.com/item/%E9%BB%8E%E6%9B%BC%EF%BC%8D%E6%96%AF%E8%92%82%E5%B0%94%E6%9D%B0%E6%96%AF%E7%A7%AF%E5%88%86/15572209)
留百度百科单纯是担心留wikipedia可能会有链接打不开的问题。如果oi-wiki并不在意这一点直接把链接换成wikipedia就好了。

2022-07-25 10:59 UTC, MegaOwIer commented
> 

这两部分内容本来就只是移到了展开讨论的其他页面中。

2022-07-25 11:01 UTC, Saisyc commented on docs/math/probability/exp-var.md
> +设随机变量 $X$ 的分布函数为 $F(x)$，若 [Stieltjes 积分](https://baike.baidu.com/item/%E9%BB%8E%E6%9B%BC%EF%BC%8D%E6%96%AF%E8%92%82%E5%B0%94%E6%9D%B0%E6%96%AF%E7%A7%AF%E5%88%86/15572209)
> 留百度百科单纯是担心留wikipedia可能会有链接打不开的问题。如果oi-wiki并不在意这一点直接把链接换成wikipedia就好了。

详情请参考格式手册或咨询管理员；我只是认为你的参考文献中提及了“各种表述不一定等价”那么自然就需要指明采用的是哪种定义

2022-07-25 11:20 UTC, MegaOwIer commented on docs/math/probability/exp-var.md
> +设随机变量 $X$ 的分布函数为 $F(x)$，若 [Stieltjes 积分](https://baike.baidu.com/item/%E9%BB%8E%E6%9B%BC%EF%BC%8D%E6%96%AF%E8%92%82%E5%B0%94%E6%9D%B0%E6%96%AF%E7%A7%AF%E5%88%86/15572209)
格式手册里只说要保证“引用链接的稳定性”，像wikipedia这种需要特殊手段才能访问的网站也没明确说能不能用。

另外 Stieltjes 积分在概率论中的应用场景并没有落在百度百科给出两种定义的差集当中，在这里不去点明具体采用哪种定义似乎也不会对概念理解有什么影响。

2022-07-25 11:21 UTC, Enter-tainer commented on docs/math/probability/exp-var.md
> +设随机变量 $X$ 的分布函数为 $F(x)$，若 [Stieltjes 积分](https://baike.baidu.com/item/%E9%BB%8E%E6%9B%BC%EF%BC%8D%E6%96%AF%E8%92%82%E5%B0%94%E6%9D%B0%E6%96%AF%E7%A7%AF%E5%88%86/15572209)
提示： @Saisyc 并不是管理员，他的意见不对review造成影响，仅供参考

2022-07-25 11:34 UTC, Saisyc commented on docs/math/probability/exp-var.md
> +设随机变量 $X$ 的分布函数为 $F(x)$，若 [Stieltjes 积分](https://baike.baidu.com/item/%E9%BB%8E%E6%9B%BC%EF%BC%8D%E6%96%AF%E8%92%82%E5%B0%94%E6%9D%B0%E6%96%AF%E7%A7%AF%E5%88%86/15572209)
> 格式手册里只说要保证“引用链接的稳定性”，像wikipedia这种需要特殊手段才能访问的网站也没明确说能不能用。
> 
> 另外 Stieltjes 积分在概率论中的应用场景并没有落在百度百科给出两种定义的差集当中，在这里不去点明具体采用哪种定义似乎也不会对概念理解有什么影响。

初学者可能不能区分具体概率论场景下采用的是哪种定义（但我觉得这主要就是百度百科的锅

2022-07-25 11:34 UTC, MegaOwIer commented on docs/math/probability/exp-var.md
> +设随机变量 $X$ 的分布函数为 $F(x)$，若 [Stieltjes 积分](https://baike.baidu.com/item/%E9%BB%8E%E6%9B%BC%EF%BC%8D%E6%96%AF%E8%92%82%E5%B0%94%E6%9D%B0%E6%96%AF%E7%A7%AF%E5%88%86/15572209)
参考意见也是意见啊，就是仅出于礼节也是回复一下的好（）

2022-07-25 11:41 UTC, Saisyc commented on docs/math/probability/exp-var.md
> +设随机变量 $X$ 的分布函数为 $F(x)$，若 [Stieltjes 积分](https://baike.baidu.com/item/%E9%BB%8E%E6%9B%BC%EF%BC%8D%E6%96%AF%E8%92%82%E5%B0%94%E6%9D%B0%E6%96%AF%E7%A7%AF%E5%88%86/15572209)
采用含有不明确信息的参考文献对于初学者可能是有害的，其实我觉得本来不给链接也挺好的~

2022-07-25 11:52 UTC, MegaOwIer commented on docs/math/probability/exp-var.md
> +设随机变量 $X$ 的分布函数为 $F(x)$，若 [Stieltjes 积分](https://baike.baidu.com/item/%E9%BB%8E%E6%9B%BC%EF%BC%8D%E6%96%AF%E8%92%82%E5%B0%94%E6%9D%B0%E6%96%AF%E7%A7%AF%E5%88%86/15572209)
就算不给链接，看到一个完全没见过的专有名词也会去搜，而我这边 Google 和 Baidu 搜索词条 “stieltjes积分” 权重最高的结果分别来自中文维基和百度百科，这两个页面的内容几乎完全一致。

2022-07-25 12:27 UTC, Great-designer commented
万岁！终于把概率论拆成一大堆页面了。这本来就是一个系统性学科

2022-07-29 08:11 UTC, merged