fix(seg-in-bit.md): change title
OI-wiki/OI-wiki pull request #3909
Opened 2022-04-09 15:42 UTC by xyf007

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论您是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈您的感受
3. 如果您熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2022-04-09 17:13 UTC, Saisyc requested changes
旗帜鲜明的反对将“主席树”作为正式称呼

2022-04-22 15:07 UTC, Menci submitted a review, later dismissed

2022-05-23 04:57 UTC, shuzhouliu reviewed
orz
主席树 -> 权值线段树

2022-07-08 01:28 UTC, xyf007 commented
谔谔

2022-07-09 00:39 UTC, Konano submitted a review, later dismissed

2022-08-07 04:06 UTC, Great-designer commented
too complex to resolve conflicts

2022-08-08 02:44 UTC, Great-designer commented
已经向此pr作者发起了解决冲突的pr
https://github.com/xyf007/OI-wiki/pull/1

2022-08-31 02:55 UTC, Great-designer commented
已经继承至 #4271

2022-08-31 02:55 UTC, closed without merging