Update fft.md
OI-wiki/OI-wiki pull request #3930
Opened 2022-04-22 06:41 UTC by Great-designer

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论您是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈您的感受
3. 如果您熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

继承

https://github.com/OI-wiki/OI-wiki/pull/3384

试着修改了一下FFT页面。

2022-04-22 08:32 UTC, Saisyc requested changes
依据格式手册，DFT 在句内不宜写作 $DFT$，且代码中的 < 无须改为 &lt

基2-FFT中分奇偶项讨论时宜指明 基2，且“利用单位复根的性质”或许应具体说明是利用何性质

    就是每一项 **取倒数**，再 **除以多项式的长度 $n$**

严格来说，逆变换时的 n 是变换的长度而不是多项式的长度（补0可能造成多项式长度存在歧义）

2022-04-22 08:33 UTC, Saisyc requested changes
依据格式手册，DFT 在句内不宜写作 $DFT$，且代码中的 < 无须改为 &lt

基2-FFT中分奇偶项讨论时宜指明 基2，且“利用单位复根的性质”或许应具体说明是利用何性质

    就是每一项 **取倒数**，再 **除以多项式的长度 $n$**

严格来说，逆变换时的 n 是变换的长度而不是多项式的长度（补0可能造成多项式长度存在歧义）

2022-04-22 08:50 UTC, Saisyc commented
请务必特别注意 **复数的单位根的乘法逆元是其共轭复数** 的性质对于一般环上的离散傅里叶变换不成立，介绍朴素的 FFT 时可能应尽量避免共轭的使用

2022-04-22 13:10 UTC, PeterlitsZo commented
前人：谢谢你！我的神！

2022-04-22 14:55 UTC, Great-designer commented
> 依据格式手册，DFT 在句内不宜写作 $DFT$，且代码中的 < 无须改为 &lt
> 
> 基2-FFT中分奇偶项讨论时宜指明 基2，且“利用单位复根的性质”或许应具体说明是利用何性质
> 
> ```
> 就是每一项 **取倒数**，再 **除以多项式的长度 $n$**
> ```
> 
> 严格来说，逆变换时的 n 是变换的长度而不是多项式的长度（补0可能造成多项式长度存在歧义）

这几条全都改完了

2022-04-22 14:56 UTC, Great-designer commented
> 请务必特别注意 **复数的单位根的乘法逆元是其共轭复数** 的性质对于一般环上的离散傅里叶变换不成立，介绍朴素的 FFT 时可能应尽量避免共轭的使用

幸运的是，这篇目前里面只字未提到“共轭”二字

2022-05-23 04:44 UTC, shuzhouliu requested changes

2022-05-23 04:44 UTC, shuzhouliu commented on docs/math/poly/fft.md
>      ```cpp
az 不应该把cpp上传到code下面去吗

2022-05-23 04:44 UTC, shuzhouliu commented on docs/math/poly/fft.md
> -author: AndrewWayne, GavinZhengOI, ChungZH, henryrabbit, Xeonacid, sshwy, Yukimaikoriya, EarthMessenger
why delete the authors

2022-05-23 04:44 UTC, shuzhouliu commented on docs/math/poly/fft.md
> +关于离散傅里叶变换，在隔壁的数学竞赛里也有。例如计算：
```suggestion
例如计算：
```

2022-05-23 04:44 UTC, shuzhouliu commented on docs/math/poly/fft.md
> +规律：其实就是原来的那个序列，每个数用二进制表示，然后把二进制翻转对称一下，就是最终那个位置的下标。比如 $x_1$ 是 001，翻转是 100，也就是 4，而且最后那个位置确实是 4。我们称这个变换为位逆序置换（bit-reversal permutation，国内也称蝴蝶变换），证明留给读者自证。
~~为什么不把证明加上呢~~

2022-05-23 04:44 UTC, shuzhouliu commented on docs/math/poly/fft.md
> +\end{aligned}
az，多项式乘法应该不用举例吧（x

2022-05-23 04:44 UTC, shuzhouliu commented on docs/math/poly/fft.md
> +两个多项式相乘的积 $C = A \times B$，我们可以在 $O(n^2)$ 的时间复杂度中解得（这里 $n$ 为 $A$ 或者 $B$ 多项式的度，这里它们的最高项的次数都为 $3$，那么 $n = 3$）：
```suggestion
两个多项式相乘的积 $C = A \times B$，我们可以在 $O(n^2)$ 的时间复杂度中解得（这里 $n$ 为 $A$ 或者 $B$ 多项式的度）：
```
度的概念在https://oi-wiki.org/math/poly/intro/有所提及

2022-05-23 04:51 UTC, shuzhouliu requested changes

2022-05-23 04:51 UTC, shuzhouliu commented on docs/math/poly/fft.md
> +  ={}& (5x^2 + 3x + 7)(7x^2 + 2x + 1) \\
```suggestion
```

2022-05-23 04:51 UTC, shuzhouliu commented on docs/math/poly/fft.md
> +  ={}& 35x^4 + (10 + 21)x^3 + (5 + 6 + 49)x^2 + (3 + 14)x + 7 \\
```suggestion
```

2022-05-23 04:51 UTC, shuzhouliu commented on docs/math/poly/fft.md
> +  ={}& 35x^4 + 31x^3 + 60x^2 + 17x + 7
直接到最后应该就好了吧（x

2022-05-23 10:56 UTC, Great-designer commented on docs/math/poly/fft.md
>      ```cpp
表示不会弄

2022-05-23 10:57 UTC, Great-designer commented on docs/math/poly/fft.md
> +规律：其实就是原来的那个序列，每个数用二进制表示，然后把二进制翻转对称一下，就是最终那个位置的下标。比如 $x_1$ 是 001，翻转是 100，也就是 4，而且最后那个位置确实是 4。我们称这个变换为位逆序置换（bit-reversal permutation，国内也称蝴蝶变换），证明留给读者自证。
这里是前人写的。我这知道是找规律，暂时也不会证。

2022-05-23 10:58 UTC, Great-designer commented on docs/math/poly/fft.md
> +\end{aligned}
确实

2022-05-23 10:58 UTC, Great-designer commented on docs/math/poly/fft.md
> +  ={}& 35x^4 + 31x^3 + 60x^2 + 17x + 7
确实

2022-05-23 10:58 UTC, Great-designer commented on docs/math/poly/fft.md
> -author: AndrewWayne, GavinZhengOI, ChungZH, henryrabbit, Xeonacid, sshwy, Yukimaikoriya, EarthMessenger
往后作者越来越多就……太麻烦

2022-05-23 11:10 UTC, shuzhouliu commented on docs/math/poly/fft.md
>      ```cpp
在pull request页面键盘敲一下`.`

或者直接对Patch commit就行了

2022-05-23 11:11 UTC, shuzhouliu commented on docs/math/poly/fft.md
> -author: AndrewWayne, GavinZhengOI, ChungZH, henryrabbit, Xeonacid, sshwy, Yukimaikoriya, EarthMessenger
有道理

2022-05-23 11:15 UTC, shuzhouliu commented on docs/math/poly/fft.md
>      ```cpp
我试试交个pr到你的Branch

2022-05-23 11:22 UTC, shuzhouliu commented on docs/math/poly/fft.md
>      ```cpp
交了。详见 https://github.dev/Great-designer/OI-wiki/pull/1 。

2022-07-16 11:22 UTC, shuzhouliu commented
<img width="656" alt="image" src="https://user-images.githubusercontent.com/64518651/179352796-539a885b-ce40-46cb-a3a9-e591135aa88a.png">
我这write access是假的吧

2022-07-16 11:26 UTC, shuzhouliu commented
<img width="620" alt="image" src="https://user-images.githubusercontent.com/64518651/179352893-ed22e328-be5b-4b19-9be9-1ef02d156d13.png">

再试了一遍也没啥用 我开个pr吧

2022-07-16 11:29 UTC, shuzhouliu commented
https://github.com/Great-designer/OI-wiki/pull/2 please kindly merge this

2022-07-16 12:16 UTC, shuzhouliu approved these changes

2022-07-16 13:27 UTC, Great-designer commented
> [Great-designer#2](https://github.com/Great-designer/OI-wiki/pull/2) please kindly merge this

辛苦了！谢谢！

2022-07-16 13:29 UTC, Great-designer commented
看到管理员这么累我非常感动（感动地流下热泪）

2022-07-16 13:52 UTC, Enter-tainer approved these changes
大家辛苦了～

2022-07-16 14:02 UTC, Great-designer commented
牛逼！All passed

2022-07-16 14:03 UTC, merged