feat(docs/math/poly/lagrange.md): 添加横坐标连续的拉格朗日插值
OI-wiki/OI-wiki pull request #3950
Opened 2022-05-02 13:44 UTC by qz-cqy

添加了横坐标连续时的线性拉格朗日插值，并添加一道例题。

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论您是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈您的感受
3. 如果您熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2022-05-02 14:44 UTC, hly1204 commented
代码可能宏的话不是特别适合，然后变量和循环次数或许可以减少：比方说我们有 f(0),f(1),...,f(n-1) 的点值数组和逆元数组，只需要额外一个临时数组应该就可以完成线性的单个点值的求算了（我记得应该是这样的）。

2022-05-02 15:52 UTC, Saisyc requested changes
将“横坐标是连续整数”简称为“横坐标连续”不妥

2022-05-02 23:47 UTC, qz-cqy commented
> 代码可能宏的话不是特别适合，然后变量和循环次数或许可以减少：比方说我们有 f(0),f(1),...,f(n-1) 的点值数组和逆元数组，只需要额外一个临时数组应该就可以完成线性的单个点值的求算了（我记得应该是这样的）。

把宏和一些没必要的代码模板部分删掉了，后面这个不太清楚。

2022-05-02 23:47 UTC, qz-cqy commented
> 将“横坐标是连续整数”简称为“横坐标连续”不妥

感谢指出，fixed。

2022-05-03 02:32 UTC, hly1204 commented
> @hly1204
> 
> > 代码可能宏的话不是特别适合，然后变量和循环次数或许可以减少：比方说我们有 f(0),f(1),...,f(n-1) 的点值数组和逆元数组，只需要额外一个临时数组应该就可以完成线性的单个点值的求算了（我记得应该是这样的）。
> 
> 把宏和一些没必要的代码模板部分删掉了，后面这个不太清楚。

给出点值 <img src="https://render.githubusercontent.com/render/math?math=f(0), f(1), \dots ,f(n - 1)"> 求 <img src="https://render.githubusercontent.com/render/math?math=f(c)"> 考虑

<img src="https://render.githubusercontent.com/render/math?math=f(x) = \sum _ {0 \leq i \lt n} f(i) \prod _ {0 \leq j \lt n \land j \neq i} \frac{x - j}{i - j}">

定义 <img src="https://render.githubusercontent.com/render/math?math=k_i := \frac{f(i)}{i!} \prod _ {0 \leq j \lt i}(x - j)">

我们有 <img src="https://render.githubusercontent.com/render/math?math=f(x) = \sum _ {0 \leq i \lt n} k_i \frac{(-1)^{n - 1 - i}}{(n - 1 - i)!} \prod _ {i \lt j \lt n}(x - j).">

求出 <img src="https://render.githubusercontent.com/render/math?math=k_i"> 可以从 1 迭代到 n-1，0 特殊处理一下，后面就是从 n-2 迭代到 0，n-1 特殊处理一下。

2022-05-03 02:55 UTC, hly1204 approved these changes

2022-05-03 13:12 UTC, Early0v0 commented
累乘的分子最好用 前缀 × 后缀 的形式而不是 乘积 ÷ 单个，避免出现 (x-i)≡0 (mod p) 这种情况

2022-06-19 10:36 UTC, Early0v0 approved these changes

2022-06-19 10:36 UTC, merged