更新了二次域相关内容
OI-wiki/OI-wiki pull request #3958
Opened 2022-05-12 09:07 UTC by Great-designer

想了想还是把二次域相关的内容专门分离出来作为一节单独介绍。其中含有高斯整数，艾森斯坦整数，勾股方程，圆上整点问题，特殊的椭圆上整点问题，以及费马大定理在取值3、4时的简单情形。

2022-05-12 09:18 UTC, Saisyc requested changes
**主理想整环** 的定义与 **Bezout环** 杂糅从而产生了错误

此外，各个词汇可以考虑添上相应英文

2022-05-12 13:02 UTC, Great-designer commented
还有就是，介绍这几个整环，至少是非常必要——事实上整个数论部分就是照着这个顺序搭起来的

2022-05-13 07:25 UTC, Great-designer commented
改完了。
目前bug可能是需要rebase

>

2022-07-16 04:10 UTC, Great-designer commented
看了看，在伟大而厉害的技术向管理员的悉心帮助与高能操作下，目前的情形：
这个已经没有了任何冲突（可以移掉标签）。
FFT那个还有内容冲突（GitHub提示一个红叉）。
更新多项式简介和合并生成函数目录的那个没有内容冲突（没有红叉），然而还有文件冲突（有冲突文件列表）。

2022-07-20 08:11 UTC, Great-designer commented
> 看了看，在伟大而厉害的技术向管理员的悉心帮助与高能操作下，目前的情形： 这个已经没有了任何冲突（可以移掉标签）。 FFT那个还有内容冲突（GitHub提示一个红叉）。 更新多项式简介和合并生成函数目录的那个没有内容冲突（没有红叉），然而还有文件冲突（有冲突文件列表）。

现在只剩这个了。其他的冲突都解决并合并了。

2022-07-25 03:25 UTC, Great-designer commented
想好了。等这个处理完了之后，我删掉旧分支再重建一个，考虑整理、外加写一点儿线性代数。现在这里全是应用，和建构逻辑真是不一样。
这个就不会一下子发好几个Pull Request了，一个发完了再发下一个；也不会有太多证明，证明之类的留白。
（也要考虑到读硕士的时候忙不忙）

2022-07-29 02:34 UTC, Great-designer commented
> 想好了。等这个处理完了之后，我删掉旧分支再重建一个，考虑整理、外加写一点儿线性代数。现在这里全是应用，和建构逻辑真是不一样。 这个就不会一下子发好几个Pull Request了，一个发完了再发下一个；也不会有太多证明，证明之类的留白。 （也要考虑到读硕士的时候忙不忙）

所以这个到8月是不是就能审完了……

2022-07-29 04:39 UTC, Konano approved these changes
LGTM

2022-07-29 04:40 UTC, merged

2022-07-29 08:28 UTC, Great-designer commented
万岁！撒花