fix: 线段树区间修改代码修改
OI-wiki/OI-wiki pull request #3968
Opened 2022-05-19 15:43 UTC by Jebearssica

将区间修改为特定值时，和区间修改增加不同，无法通过修改值是否为0来判断修改是否合法，因此需要引入额外的空间储存是否发生修改，即新增的 `m[p]` 代表索引为 p 的区间打上了修改标记

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论您是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈您的感受
3. 如果您熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2022-05-19 16:06 UTC, Jebearssica commented
额外补充，有关两年前 [pot-code](https://github.com/pot-code) 提到的有关下面代码中，是否正确判断叶子结点以防止 index out of range

```c++
if (b[p] && s != t) {
	d[p * 2] += b[p] * (m - s + 1), d[p * 2 + 1] += b[p] * (t - m);
	b[p * 2] += b[p], b[p * 2 + 1] += b[p];
	b[p] = 0;
}
```

我个人觉得目前的写法能够满足情况，当且仅当 s == t 时，我们才会递归至叶子结点的孩子结点，导致索引溢出。然而，当且仅当该叶子结点完全被搜索区间覆盖时，我们才会遍历到该结点，即当前区间直接返回值了，都不会有 pushdown 的过程

2022-05-20 01:31 UTC, Early0v0 requested changes

2022-05-20 01:31 UTC, Early0v0 commented on docs/ds/seg.md
> +  if (l > t || r < s) return 0;
其实这句不用加，之后有保证不重叠

2022-05-20 01:31 UTC, Early0v0 commented on docs/ds/seg.md
> +  if (l > t || r < s) return 0;
同上

2022-05-20 01:31 UTC, Early0v0 commented on docs/ds/seg.md
> +  if (m[p]) {
`m` 与表示区间中点的 `m` 重复了，建议换一个

2022-05-20 01:48 UTC, Jebearssica commented on docs/ds/seg.md
> +  if (l > t || r < s) return 0;
fix in [acfa1a7](https://github.com/OI-wiki/OI-wiki/pull/3968/commits/acfa1a79f85ec5b9b6d6ff270c75b079c959bcf8)

2022-05-20 01:48 UTC, Jebearssica commented on docs/ds/seg.md
> +  if (m[p]) {
fix in [acfa1a7](https://github.com/OI-wiki/OI-wiki/pull/3968/commits/acfa1a79f85ec5b9b6d6ff270c75b079c959bcf8)

2022-05-20 02:10 UTC, Early0v0 approved these changes

2022-05-22 10:26 UTC, CoelacanthusHex approved these changes

2022-05-22 10:29 UTC, merged