feat:增加java进阶页面
OI-wiki/OI-wiki pull request #3984
Opened 2022-05-28 18:02 UTC by 1804040636

java进阶章节添加
第一次进行提交，按教程做的，如有不对的地方请大佬指正orz

2022-05-28 18:14 UTC, 1804040636 commented
orz不太明白这个显示的红叉叉是什么意思

2022-05-29 00:28 UTC, abc1763613206 reviewed
🤔 看上去您并没有添加上相应的文件。

2022-05-29 15:31 UTC, aofall commented
从提交记录来看你只提交了目录的更新，具体进阶页面的文档被落下了

2022-05-29 16:05 UTC, 1804040636 commented
> 从提交记录来看你只提交了目录的更新，具体进阶页面的文档被落下了

那具体进阶页面的文档我是在上一个Pull requests中申请的，之前一次更新发现他是打了√，然后刚刚我又提交了新的部分，那么现在具体流程应该是？先去把.md加入到mkdocs.yml吗，还是先将java-pro.md加入到lang/下呢？

2022-05-31 03:42 UTC, Cubik65536 commented
我向你的 repo 提交了一个 Pull Request（ https://github.com/1804040636/OI-wiki/pull/1 ）你可以参考一下或直接使用

2022-05-31 03:45 UTC, 1804040636 commented
> 我向你的 repo 提交了一个 Pull Request（ [1804040636#1](https://github.com/1804040636/OI-wiki/pull/1) ）你可以参考一下或直接使用

好的谢谢

2022-05-31 14:53 UTC, 1804040636 commented
有大佬可以指导push一下嘛QAQ,能合到master分支吗

2022-05-31 15:20 UTC, Cubik65536 commented
我今/明天做一个初步 review

2022-05-31 15:23 UTC, Cubik65536 commented on docs/lang/java-pro.md
> +        }out.println("NO");
`}` 后面换行

2022-05-31 15:24 UTC, Cubik65536 commented on docs/lang/java-pro.md
> +
同上

2022-05-31 15:25 UTC, Cubik65536 commented on docs/lang/java.md
> +```
同上

2022-05-31 15:55 UTC, 1804040636 commented on docs/lang/java-pro.md
> +# java 进阶
好的，这个我会注意并重新进行校对修改

2022-05-31 15:56 UTC, 1804040636 commented on docs/lang/java-pro.md
> +```
好的谢谢，这个我会注意

2022-05-31 15:59 UTC, 1804040636 commented on docs/lang/java.md
> +```
抱歉刚刚手不小心点到resolve conversation了，刚好在记东西，鼠标划到了

2022-05-31 16:01 UTC, 1804040636 commented on docs/lang/java-pro.md
> +        }out.println("NO");
好的，感谢，收到

2022-05-31 16:15 UTC, Cubik65536 requested changes
`=` 前后空格的问题还存在不少

2022-05-31 16:15 UTC, Cubik65536 commented on docs/lang/java-pro.md
> +
此处的同上指的是 `=` 前后空格问题

2022-05-31 16:15 UTC, Cubik65536 commented on docs/lang/java-pro.md
> +}
`=` 前后空格问题

2022-05-31 16:15 UTC, Cubik65536 commented on docs/lang/java.md
> +```
此处的同上指的是 `=` 前后空格问题

2022-05-31 16:21 UTC, 1804040636 commented on docs/lang/java-pro.md
> +}
好的，明白了

2022-05-31 16:24 UTC, 1804040636 commented on docs/lang/java-pro.md
> +
就是说每一个空格都应该要有前后空格，我之前理解成要不然全部有空格，要不然全部没空格了

2022-05-31 16:30 UTC, 1804040636 commented on docs/lang/java-pro.md
> +}
之前理解成=前后空格格式要不然都有，要不然都没有，然后刚刚反应过来，然后code format了一下

2022-06-01 09:35 UTC, aofall commented on docs/lang/java-pro.md
> +## 数据结构
对于以下这些JDK集合可以讲的更详细一些

2022-06-01 09:38 UTC, 1804040636 commented on docs/lang/java-pro.md
> +## 数据结构
好的，我是每天晚上回去添加的

2022-06-01 09:39 UTC, aofall commented
之前也有人提交过Java进阶页面，部分内容在写集合相关时值得参考 #3773

2022-06-03 01:51 UTC, Cubik65536 reviewed
已有的内容都还不错，再次提醒，尽量统一代码风格，运算符前后的空格，函数是否在 `{` / `}` 中间/前后换行，函数的 `{` 之前的空格，`,` 之后的空格。

**这对增加可读性很重要，同一篇文章代码风格需要统一**

2022-06-03 01:51 UTC, Cubik65536 commented on docs/lang/java.md
> +    public static float nextFloat() throws IOException{ in.nextToken(); return (float)in.nval; }
```suggestion
    public static float nextFloat() throws IOException { in.nextToken(); return (float)in.nval; }
```

2022-06-03 01:51 UTC, Cubik65536 commented on docs/lang/java.md
> +    public static double nextDouble() throws IOException{ in.nextToken(); return in.nval; }
```suggestion
    public static double nextDouble() throws IOException { in.nextToken(); return in.nval; }
```

2022-06-03 01:51 UTC, Cubik65536 commented on docs/lang/java.md
> +    public static long nextLong() throws Exception{ in.nextToken();return (long)in.nval;}
```suggestion
    public static long nextLong() throws Exception { in.nextToken();return (long)in.nval;}
```

2022-06-03 01:51 UTC, Cubik65536 commented on docs/lang/java.md
> +        return in.sval;
```suggestion

```

2022-06-03 01:51 UTC, Cubik65536 commented on docs/lang/java.md
> +    }
```suggestion

```

2022-06-03 01:51 UTC, Cubik65536 commented on docs/lang/java.md
> +        int n=nextInt();
```suggestion
        int n = nextInt();
```

2022-06-03 01:51 UTC, Cubik65536 commented on docs/lang/java.md
> +    public static void main(String[] args) throws Exception{
```suggestion
    public static void main(String[] args) throws Exception {
```

2022-06-03 01:51 UTC, Cubik65536 commented on docs/lang/java.md
> +        out.flush();
```suggestion
        out.close();
```

2022-06-03 01:51 UTC, Cubik65536 commented on docs/lang/java.md
> +    public static StreamTokenizer in = new StreamTokenizer(new BufferedReader(new InputStreamReader(System.in),32768));
```suggestion
    public static StreamTokenizer in = new StreamTokenizer(new BufferedReader(new InputStreamReader(System.in), 32768));
```

2022-06-04 07:45 UTC, 1804040636 commented on docs/lang/java.md
> +    public static float nextFloat() throws IOException{ in.nextToken(); return (float)in.nval; }
好的谢谢大佬，最近在复习，等复习完继续赶进度

2022-07-13 08:47 UTC, yusancky commented on docs/lang/java-pro.md
> +???+note "[[codeforces]Quality vs Quantity](https://www.luogu.com.cn/problem/P1216)"
> ？？？ 是我打算做成一个点击触发下拉的，但是不太知道语法，看了下别人代码里的语法是这样的

下拉框语法可见： https://oi-wiki.org/intro/format/#markdown 。

2022-07-13 15:50 UTC, Cubik65536 commented
先暂时移除后面的标题大纲把目前已有内容合并不知道是不是一个可行方案
/cc @1804040636 @aofall

2022-07-13 16:00 UTC, undefined-moe commented
test

2022-07-21 12:01 UTC, yusancky commented
> **Reply**: @Cubik65536 
> 先暂时移除后面的标题大纲把目前已有内容合并不知道是不是一个可行方案
> /cc @1804040636 @aofall

如果原作者@1804040636 仍 `失去响应`，我认为这是最好的方案之一。
> **[English Version]** If @1804040636 is still `No Response`, I think it's one of the best choices. 

> **Note**
> 当然，我们也可以额外开一个拉取请求，并按目前的进度继续编写。
> > **[English Version]** We can also open another pull request bases on the progress now, of course. 
> 
> > 此外，我在 [`yusancky:patch-2`](https://github.com/yusancky/OI-wiki/tree/patch-2) 分支中添加了两个提交（ yusancky@10e69e7 、 yusancky@48394bd ），并提交至了 1804040636/OI-wiki#2。
> > 如果采用这一方案，欢迎以这个分支为基础。
> > > **[English Version]**
> > > In addition, I committed two times ( yusancky@10e69e7 & yusancky@48394bd ) in the branch [`yusancky:patch-2`](https://github.com/yusancky/OI-wiki/tree/patch-2) . They are also the changed commits in 1804040636/OI-wiki#2. 
> > > If our future choice is to open another pull request, I will be glad if you start bases on the branch.

2022-07-27 04:37 UTC, Cubik65536 commented
> 跟进（2022/7/27）： **我认为是时候选择一种方案了。**

/cc @aofall 

我暂时没有时间重新进行施工，也没有移除未完成内容标题并 Merge 的权限。先等待 Admin 的决定吧，假如 Admin 决定暂时先这么放着就只能这样，我会在有时间之后尝试进行内容的修缮并提交新的 PR

2022-07-27 06:39 UTC, yusancky commented
2eb126e 的 `|` 似乎被识别为了表格的分隔符。

2022-07-27 07:10 UTC, Enter-tainer commented
疑似是 bot bug了，把这个页面加到 .remark-ignore 里面吧

2022-07-29 03:12 UTC, aofall commented
格式部分我无力帮忙纠正。如果暂时没有写集合相关内容的计划可以先把标题从大纲中去掉以便Merge，只有标题没有内容review是不通过的

2022-07-29 04:42 UTC, Xeonacid commented
按照这个分法的话，感觉“更高速的输入输出”放到Java 进阶会更合适 :thinking:

2022-07-29 07:13 UTC, 1804040636 commented on docs/lang/java-pro.md
> +???+note "[[Codeforces] Quality vs Quantity](https://www.luogu.com.cn/problem/P1216)"
好的

2022-07-29 07:27 UTC, 1804040636 commented
QAQ有大佬要来push吗，刚完成了数据结构，但是格式内容不知道如何

2022-07-29 16:10 UTC, aofall commented on docs/lang/java-pro.md
> +Queue<Integer> q=new LinkedList<>();
Queue or List ?是不是复制的时候多出来了

2022-07-29 16:21 UTC, aofall commented on docs/lang/java-pro.md
> +## 数据结构
这里的标题我觉得应称之为集合（Collection）而不是数据结构，是Java提供的包装完成的库而不单单是“结构”，Java对其也是这么称呼的，集合只是该数据结构存储以及操作的（或许是当前最佳或者通用性最高）实现方法。其存在的意义与C++的STL差不多，都是为了防止重复造轮子。如果需要学习数据结构，OI-Wiki 上也有相应的专题来讲解。

2022-07-29 16:23 UTC, aofall commented on docs/lang/java-pro.md
> +    static List<Integer> array=new ArrayList<>();
实例化 = 的前后空格，下一行也一样。
（题外话：不知道你是用什么编辑器，可以看看是否有自动格式化代码这一功能，如果有这一功能后续可以省去不少麻烦。）

2022-07-29 16:26 UTC, aofall commented on docs/lang/java-pro.md
> +        for (int i = 0; i < array.size(); i++) out.println(array.get(i));//遍历自增数组，复杂度为O(n)
虽然 for 循环中只有一行语句可以不加大括号最终编译器会帮你加上，但为了养成良好的习惯让代码可读性更好，同时也为了代码过程中加逻辑后产生避免不必要的麻烦来耗时排查，还是建议加上大括号

2022-07-29 16:30 UTC, aofall commented on docs/lang/java-pro.md
> +## 数据结构
另外就是，集合专题前或许可以讲一下泛型，毕竟集合和泛型在实际应用中几乎是组队出现的。否则一般读者可能会不疑惑 List 一定得是 List<Integer> 这样的类型吗，可以 List<Long> 吗，或者 Map 是否可以 Map<String, Set<Integer>> 来套娃巧妙解决一些问题如重复判断、去重等等....

2022-07-29 16:44 UTC, Cubik65536 commented
> 按照这个分法的话，感觉“更高速的输入输出”放到 Java 进阶会更合适 🤔

更高速的输入输出是当时我写到基础部分里的，因为当时没有写进阶的计划，现在可以考虑 refactor 到进阶

2022-07-29 16:52 UTC, 1804040636 commented on docs/lang/java-pro.md
> +Queue<Integer> q=new LinkedList<>();
啊就是，Queue是个java的接口，可以用LinkedList去实现

2022-07-29 16:53 UTC, 1804040636 commented on docs/lang/java-pro.md
> +## 数据结构
好的

2022-07-29 16:53 UTC, 1804040636 commented on docs/lang/java-pro.md
> +    static List<Integer> array=new ArrayList<>();
ok，我把所有代码再格式化一下

2022-07-30 05:59 UTC, aofall commented
泛型（对应着C++ Template）还没有补充哦，除了泛型之外好像还可以增加基本类型（如int）与包装类型（如Integer）的区别方便理解。

集合可补充以下两点，这里我以 List<T> 举例：

如果不明确指定类型时 `List list = new ArrayList<>();`，此时可以往实例化后的 List 放任意类型的数据，但没有特殊需求的话不推荐这么做，编译器无法帮你检查存入的数据是否安全，取值时不明确数据类型（都为Object），需要手动转型，稍有不慎可能出现误转型异常。

如果是明确了类型如 `List<Integer>` 此时编译器会检查放入的数据类型，只能放入整数的数据。以及声明集合变量时只能使用包装类型  `List<Integer>`  而不是基本类型  `List<int>`

2022-07-30 06:32 UTC, 1804040636 commented
> 泛型（对应着C++ Template）还没有补充哦，除了泛型之外好像还可以增加基本类型（如int）与包装类型（如Integer）的区别方便理解。
> 
> 集合可补充以下两点，这里我以 `List<T>` 举例：
> 
> 1.如果不明确指定类型时，此时可以往实例化后的 List 放任意类型的数据。
> 
> ```
>     List list = new ArrayList<>();
>     list.add(1);
>     list.add(true);
>     list.add(1.01);
>     list.add(1L);
>     list.add("I am String")
> ```
> 
> 但没有特殊需求的话不推荐这么做，编译器无法帮你检查存入的数据是否安全， list.get(index) 取值时无法明确数据的类型（取到的数据类型都为Object），需要手动转回原来的类型，稍有不慎可能出现误转型异常。
> 
> 2.如果是明确了类型如 `List<Integer>` 此时编译器会检查放入的数据类型，只能放入整数的数据。以及声明集合变量时只能使用包装类型 `List<Integer>` 或者自定义的 Class，而不能是基本类型 `List<int>`

好的惹，这个我再补充一下

2022-07-30 07:26 UTC, aofall commented on docs/lang/java-pro.md
> +#### 遍历List的三种方法
这里可以加一个 warning ，不要在 for/foreach 遍历 List 的过程中删除其中的元素，会抛出异常

原因也很简单，因为遍历开始时 for 条件中的 `i < list.size` 已经确定了循环的次数，不会因为 List 中元素被删除而改变。如果不此时不直接抛异常，删除后依旧按照原来的条件循环，最终也会抛出 index 越界的异常，以及操作的数据不符合预期。

2022-07-30 07:30 UTC, 1804040636 commented on docs/lang/java-pro.md
> +#### 遍历List的三种方法
好的，但是i<list.size(),我感觉删除后list长度也是改变的，这里的list.size()应该是动态变化的，就类似于队列出队一样，是动态变化的长度

2022-07-30 07:39 UTC, aofall commented on docs/lang/java-pro.md
> +#### 遍历List的三种方法
更改了一下描述

2022-07-30 08:44 UTC, 1804040636 commented on docs/lang/java-pro.md
> +#### 遍历List的三种方法
好的，已增加

2022-07-30 16:22 UTC, aofall commented
剩下的交由其他人来审阅了，大致内容上没什么问题了，细节的如代码格式、语句通顺程度我就不细看啦

2022-07-31 08:33 UTC, 1804040636 commented
有大佬来review嘛QAQ

2022-08-02 15:17 UTC, Cubik65536 commented on CNAME
> +beifeng.oiwiki.cn
CNAME 不应该添加到这里

2022-08-02 15:27 UTC, 1804040636 commented on CNAME
> +beifeng.oiwiki.cn
好的惹，这是哪个文件呢QAQ，我昨天好像瞎搞了一些东西

2022-08-02 15:28 UTC, Cubik65536 commented on CNAME
> +beifeng.oiwiki.cn
> 好的惹，这是哪个文件呢QAQ，我昨天好像瞎搞了一些东西

就是那个 `CNAME` 文件 /cc @1804040636

2022-08-02 15:30 UTC, 1804040636 commented on CNAME
> +beifeng.oiwiki.cn
好的，找到并删除了

2022-08-03 01:36 UTC, yusancky approved these changes

2022-08-03 02:11 UTC, Cubik65536 commented
@1804040636 我向你的仓库提交了 Pull Request https://github.com/1804040636/OI-wiki/pull/3

请注意 Markdown 语法规范，你有些地方有多余空行有些地方有少的，表格也没有正常排版，粗体字的格式也没有统一，还有大大小小其他一些问题。而这些都是用个 VSCode 插件就能找到甚至直接解决的事情，以后请自行解决。虽然这些问题不影响阅读，但是会严重影响其他想要往这里增改内容的其他贡献者。我接下来这句话不太好听，请谅解：这个 PR 改的我很难受。所以，以后**请一定要**认真考虑格式问题。

2022-08-03 18:54 UTC, Cubik65536 requested changes
修复了一些标点符号和脚注等内容。还有另外两个通篇都有的问题需要改正，因为数量很多就不一个一个标出来了：

1. 程序在结束之前统一使用 `out.close();` 而非 `out.flush();`
2. 单行注释的 `//` 前面两个空格，后面一个空格

2022-08-03 18:54 UTC, Cubik65536 commented on docs/lang/java-pro.md
> +该方法无法无法对指定区间进行搜索。
```suggestion
该方法无法对指定区间进行搜索。
```

2022-08-04 00:33 UTC, Cubik65536 commented on docs/lang/java-pro.md
> +2. 从数组 a 中二分查找是否存在 `key`，如果存在，便返回其下标,搜索区间为左开右闭 `[firstIdx,lastIdx)` 。若不存在，则返回一个负数。
> 左开右闭与描述似乎不太符合

我在上面 review 里提到过了，唯一一个目前不是 outdated 状态的那个，不知道为啥没改

2022-08-04 00:36 UTC, Cubik65536 commented on docs/lang/java-pro.md
> +2. 从数组 a 中二分查找是否存在 `key`，如果存在，便返回其下标,搜索区间为左开右闭 `[firstIdx,lastIdx)` 。若不存在，则返回一个负数。
> 你改的那个和描述也不符合啊

好像是的... 尴尬了

2022-08-04 00:38 UTC, yusancky commented on docs/lang/java-pro.md
> +2. 从数组 a 中二分查找是否存在 `key`，如果存在，便返回其下标,搜索区间为左开右闭 `[firstIdx,lastIdx)` 。若不存在，则返回一个负数。
> 左开右闭与描述似乎不太符合

我也注意到了这个问题，确实应该是左闭右开区间。我正在修改。

2022-08-04 00:40 UTC, yusancky commented
[基本运算一节](https://github.com/OI-wiki/OI-wiki/blob/9300491103a0fe7b385b5c890f068a403bc799c4/docs/lang/java-pro.md#基本运算)的表格右侧要不要处理一下？

2022-08-04 00:42 UTC, Cubik65536 commented
> [基本运算一节](https://github.com/OI-wiki/OI-wiki/blob/9300491103a0fe7b385b5c890f068a403bc799c4/docs/lang/java-pro.md#%E5%9F%BA%E6%9C%AC%E8%BF%90%E7%AE%97)的表格右侧要不要处理一下？

要，我提交到他那的 style PR 里本来是处理过一次的，但是好像插件没处理好，我直接手动对一次

2022-08-04 00:50 UTC, yusancky commented on docs/lang/java-pro.md
> +2. 从数组 a 中二分查找是否存在 `key`，如果存在，便返回其下标,搜索区间为左开右闭 `[firstIdx,lastIdx)` 。若不存在，则返回一个负数。
```suggestion
2. 从数组 a 中二分查找是否存在 `key`，如果存在，便返回其下标,搜索区间为左闭右开 `[firstIdx,lastIdx)` 。若不存在，则返回一个负数。
```

2022-08-04 00:52 UTC, yusancky commented
> > [基本运算一节](https://github.com/OI-wiki/OI-wiki/blob/9300491103a0fe7b385b5c890f068a403bc799c4/docs/lang/java-pro.md#%E5%9F%BA%E6%9C%AC%E8%BF%90%E7%AE%97)的表格右侧要不要处理一下？
> 
> 要，我提交到他那的 style PR 里本来是处理过一次的，但是好像插件没处理好，我直接手动对一次
> 
> 其实是对齐的，但是似乎因为字体大小原因在 GitHub 上看就是没对齐的了
> 
> <img alt="image" width="666" src="https://user-images.githubusercontent.com/72877496/182739361-da0d9eff-82e6-4b5f-ae1c-f47a6c446866.png">

我的意思是：右侧内容是否需要统一表述方式，即不混用 $\TeX$ 与行内代码块表示符号？

2022-08-04 00:55 UTC, Cubik65536 commented
> > > > @yusancky ：
> 
> > > > [基本运算一节](https://github.com/OI-wiki/OI-wiki/blob/9300491103a0fe7b385b5c890f068a403bc799c4/docs/lang/java-pro.md#%E5%9F%BA%E6%9C%AC%E8%BF%90%E7%AE%97)的表格右侧要不要处理一下？
> 
> > > 
> 
> > > 
> 
> > > @Cubik65536 ：
> 
> > > 要，我提交到他那的 style PR 里本来是处理过一次的，但是好像插件没处理好，我直接手动对一次
> 
> > > 其实是对齐的，但是似乎因为字体大小原因在 GitHub 上看就是没对齐的了
> 
> > > <img alt="image" width="666" src="https://user-images.githubusercontent.com/72877496/182739361-da0d9eff-82e6-4b5f-ae1c-f47a6c446866.png">
> 
> > 
> 
> > 我的意思是：右侧内容是否需要统一表述方式，即尽量不混用 TEX 与行内代码块表示符号？
> 
> 
> 
> 混用在哪里（（

pow，好像是

2022-08-04 00:55 UTC, yusancky commented
> > > > @yusancky ：
> > > > [基本运算一节](https://github.com/OI-wiki/OI-wiki/blob/9300491103a0fe7b385b5c890f068a403bc799c4/docs/lang/java-pro.md#%E5%9F%BA%E6%9C%AC%E8%BF%90%E7%AE%97)的表格右侧要不要处理一下？
> > > 
> > > 
> > > @Cubik65536 ：
> > > 要，我提交到他那的 style PR 里本来是处理过一次的，但是好像插件没处理好，我直接手动对一次
> > > 其实是对齐的，但是似乎因为字体大小原因在 GitHub 上看就是没对齐的了
> > > <img alt="image" width="666" src="https://user-images.githubusercontent.com/72877496/182739361-da0d9eff-82e6-4b5f-ae1c-f47a6c446866.png">
> > 
> > 
> > 我的意思是：右侧内容是否需要统一表述方式，即尽量不混用 TEX 与行内代码块表示符号？
> 
> 混用在哪里（（

既有形如 `this + val` 的内容，又有 $this ^ e$。

2022-08-04 01:00 UTC, yusancky commented
> 要是变成
> 
> ```
> `^`
> ```
> 
> 的话就和其他内容混合了

似乎是，那就算了吧。
反正不是大问题。

2022-08-04 08:31 UTC, 1804040636 commented on docs/lang/java-pro.md
> +2. 从数组 a 中二分查找是否存在 `key`，如果存在，便返回其下标,搜索区间为左开右闭 `[firstIdx,lastIdx)` 。若不存在，则返回一个负数。
是左闭右开，我写错了orz，神志不清了

2022-08-04 17:20 UTC, Cubik65536 requested changes
单行注释还是不对啊

是

``` diff
- out.close();//Comment
+ out.close();  // Comment
```

不是

``` diff
- out.close();//Comment
+ out.close();//  Comment 
```

2022-08-04 20:53 UTC, Cubik65536 submitted a review, later dismissed
我觉得没有大问题了

2022-08-04 20:56 UTC, 1804040636 commented
> 我觉得没有大问题了

感谢大佬的帮忙orz

2022-08-05 02:42 UTC, aofall requested changes

2022-08-05 02:42 UTC, aofall commented on docs/lang/java-pro.md
> +2. 八个包装类分别是`Byte` ，`Double` ，`Float` ，`Integer` ，`Long` ，`Short` ，`Character`，`Boolean`。
基本类型与包装类型的对应关系或许可以改为表格形式方便阅读？

2022-08-05 02:42 UTC, aofall commented on docs/lang/java-pro.md
> +
可以补充基本类型与包装类型的的装箱、拆箱，仅供参考。

Integer 的本质是对象， int 是基本类型，正常来说两个类型之间是不能直接赋值的。
需要将基础类型转换为包装类型，这种做法称为装箱，反过来则称为拆箱。

```
    // 基本类型
    int value1 = 1;
    // 装箱转换为包装类型
    Integer integer = Integer.valueOf(value1);
    // 拆箱转换为基本类型
    int value2 = integer.intValue();
```

 JDK1.5 开始引入了自动装箱拆箱的机制。

```
    Integer integer = 1;
    int value = integer;
```

warning:虽然JDK增加了自动装箱拆箱的机制，但在声明变量时请选择合适的类型，因为包装类型Integer可以接受 null，而基本类型int不能接受null，如果使用null值的包装类型进行拆箱操作时会出现异常。

```
    Integer integer = Integer.valueOf(null);
    integer.intValue();  // 抛出 java.lang.NumberFormatException 异常

    Integer integer = null;
    integer.intValue();  // 抛出 java.lang.NumberFormatException 异常
```

2022-08-05 02:42 UTC, aofall commented on docs/lang/java-pro.md
> +如果没有特殊需求的话不推荐这么做第2种行为，编译器无法帮你检查存入的数据是否安全， `list.get(index)` 取值时无法明确数据的类型（取到的数据类型都为 `Object` ），需要手动转回原来的类型，稍有不慎可能出现误转型异常。
1.第2种行为？CV前注意一下上下文内容哦

2.

  > 编译器无法帮你检查存入的数据是否安全

虽然原内容是我提供的但仅供参考，尽量避免出现“你、我、他”之类的人称代词。可以改为“编译器无法帮忙检查存入的数据是否安全”

2022-08-05 02:42 UTC, aofall commented on docs/lang/java-pro.md
> +如果是明确了类型如 `List<Integer>` ，此时编译器会检查放入的数据类型，只能放入整数的数据。以及声明集合变量时只能使用包装类型 `List<Integer>` 或者自定义的 `Class`，而不能是基本类型  `List<int>`。
> 声明集合变量时只能使用包装类型 `List<Integer>` 或者自定义的 `Class`，而不能是基本类型 `List<int>`。

放到容器定义那边去或许会好一些，明确包装类型可以与上一段放在一起。

2022-08-05 02:42 UTC, aofall commented on docs/lang/java-pro.md
> +Map<String,Set<Int>> map = new HashMap<>();
Map<String, Set<Integer>> map = new HashMap<>();

逗号后空格以及 Int->Integer 的问题

2022-08-05 02:42 UTC, aofall commented on docs/lang/java-pro.md
> +        // 由于 Java 8 后有 lambda 表达式，第三个重载及第四个重载亦可写为
引用 Lambda 表达式写法且没有说明，是不是不利于刚入门的人阅读？可以在本PR补充或者后续开个新PR继续补充

2022-08-05 07:43 UTC, yusancky requested changes
**全文总体来说是相当不错的，内容的量相当大。**

但是，文章仍存在一些瑕疵。

因此，这个 review 针对相关问题，从以下两方面入手，提出了改进意见。
- 提出一些解决文本内容存在的不足的意见。
- 对于文本格式问题，选取一部分进行了修改。
  > **Warning**
  > 并不是对全部格式问题进行修改，在代码块注释中仍然有不少空格问题。

2022-08-05 07:43 UTC, yusancky commented on docs/lang/java-pro.md
> +泛型：指在类定义时不会设置类中的属性或方法参数的具体类型，而是在类使用时（创建对象）再进行类型的定义。会在编译期检查类型是否错误。
有必要简单介绍泛型的本质、优点等内容，这里给出一些基本内容，欢迎继续补充：
```suggestion
泛型指在类定义时不设置类中的属性或方法参数的具体类型，而是在使用（或创建对象）时再进行类型的定义。泛型本质是参数化类型，即所操作的数据类型被指定为一个参数。

泛型提供了编译时类型安全检测的机制，该机制允许编译时检测非法类型。
```

2022-08-05 07:43 UTC, yusancky commented on docs/lang/java-pro.md
> +倘若你不指定数据类型，而当成 `Object` 类型随意添加数据，在 `Java8` 中虽能编译通过，但会有很多警告风险。
这里使用 `Java 8` 而不是 ``` `Java8` ```：
```suggestion
倘若你不指定数据类型，而当成 `Object` 类型随意添加数据，在 Java 8 中虽能编译通过，但会有很多警告风险。
```

2022-08-05 07:43 UTC, yusancky commented on docs/lang/java-pro.md
> +`Collection` 是 Java 中的接口，被多个泛型容器接口所实现。在这里，`Collection`是指代存放对象类型的数据结构。
这里缺少一个 ` `：
```suggestion
`Collection` 是 Java 中的接口，被多个泛型容器接口所实现。在这里，`Collection` 是指代存放对象类型的数据结构。
```

2022-08-05 07:43 UTC, yusancky commented on docs/lang/java-pro.md
> +常用接口为：`List` 、`Queue` 、 `Set` 、 `Map`。
> **Note**
> ``` ` ``` 与符号之间不需要添加 ` `；

删去 ``` ` ``` 与符号之间的 ` `；将 `有` 修改为 `包括`；增加一个换行：
```suggestion

常用的接口包括 `List`、`Queue`、`Set` 和 `Map`。
```

2022-08-05 07:43 UTC, yusancky commented on docs/lang/java-pro.md
> +1. 当你 `Arrays.sort` 的参数数组元素类型为基本数据类型时 `(byte、short、char、int、long、double、float)` 时，默认为 `DualPivotQuicksort` (双轴快排)，复杂度最坏可以达到$O(n^2)$。
> **Note**
> 列举时的 `(` 与 `)`（应改为 `（` 与 `）`）及分隔时使用的 `、` 作为正文的一部分，而不是行内代码的一部分：
> ```diff
> - `(byte、short、char、int、long、double、float)`
> + （`byte`、`short`、`char`、`int`、`long`、`double`、`float`）
> ```
```suggestion
1. 当你 `Arrays.sort` 的参数数组元素类型为基本数据类型（`byte`、`short`、`char`、`int`、`long`、`double`、`float`）时，默认为 `DualPivotQuicksort`（双轴快排），复杂度最坏可以达到 $O(n^2)$。
```

2022-08-05 07:43 UTC, yusancky commented on docs/lang/java-pro.md
> +`Arrays.fill()` 是将数组中连续位置的元素赋值为统一元素
首先是文本格式和语法的小问题：
```diff
- `Arrays.fill()` 是将数组中连续位置的元素赋值为统一元素
+ `Arrays.fill()` 方法将数组中连续位置的元素赋值为统一元素。
```

但是，正如你所说（修改后）：
> `Arrays.fill()` 方法将数组中**连续位置的元素**赋值为统一元素。

是不是应该像前文一样解释一下 `fromIndex` 与 `toIndex` 参数？因为前文有相关内容，这里可以只简单地介绍：
```suggestion
`Arrays.fill()` 方法将数组中连续位置的元素赋值为统一元素。其接受的参数为数组、`fromIndex`、`toIndex` 和需要填充的数。方法执行后，数组左闭右开区间 `[firstIdx,lastIdx)` 内的所有元素的值均为需要填充的数。
```

2022-08-05 07:43 UTC, yusancky commented on docs/lang/java-pro.md
> +如果没有特殊需求的话不推荐这么做第2种行为，编译器无法帮你检查存入的数据是否安全， `list.get(index)` 取值时无法明确数据的类型（取到的数据类型都为 `Object` ），需要手动转回原来的类型，稍有不慎可能出现误转型异常。
> 1.第2种行为？CV前注意一下上下文内容哦
> 
> 
> > 编译器无法帮你检查存入的数据是否安全
> 
> 虽然原内容是我提供的但仅供参考，尽量避免出现“你、我、他”之类的人称代词。可以改为“编译器无法帮忙检查存入的数据是否安全”

修改格式问题：
```suggestion
如果没有特殊需求的话不推荐这么做第 2 种行为，编译器无法帮忙检查存入的数据是否安全，`list.get(index)` 取值时无法明确数据的类型（取到的数据类型都为 `Object`），需要手动转回原来的类型，稍有不慎可能出现误转型异常。
```

2022-08-05 09:54 UTC, 1804040636 commented on docs/lang/java-pro.md
> +    static void isPrime() {  // 判定该数是否是素数 基于米勒罗宾,参数越大准确性越高，复杂度越高。准确性为(1-1/(val*2))
这里没注意，我来个超链接

2022-08-05 10:00 UTC, 1804040636 commented on docs/lang/java-pro.md
> +        // 由于 Java 8 后有 lambda 表达式，第三个重载及第四个重载亦可写为
已补充

2022-08-05 10:30 UTC, aofall requested changes

2022-08-05 10:30 UTC, aofall commented on docs/lang/java-pro.md
> +warning:虽然 JDK 增加了自动装箱拆箱的机制，但在声明变量时请选择合适的类型，因为包装类型 `Integer` 可以接受 `null`，而基本类型 `int` 不能接受 `null`，如果使用 `null` 值的包装类型进行拆箱操作时会出现异常。
请使用 `!!!` 写法的warning，可参考链接

https://oi-wiki.org/intro/format/#markdown

2022-08-05 10:30 UTC, aofall commented on docs/lang/java-pro.md
> +1. 是一个接口，符合 java接口定义。
Java 的 J 大写，前后空格统一

2022-08-05 10:30 UTC, aofall commented on docs/lang/java-pro.md
> +Map<String,Set<Integer>> map = new HashMap<>();
> String, Set

逗号后漏了空格

2022-08-05 10:30 UTC, aofall commented on docs/lang/java-pro.md
> +5. 和 3 同理，用 lambda 表达式优化了代码长度。
Lambda 的大小写或许该全文统一下（Lambda or lambda）？注释中小写与讲解专题大写。
个人倾向于使用前者

2022-08-05 10:55 UTC, 1804040636 commented on docs/lang/java-pro.md
> +5. 和 3 同理，用 lambda 表达式优化了代码长度。
好的

2022-08-06 06:48 UTC, aofall reviewed
勘误了一处错误，然后就是warning的引用好像不太对，具体有请 @shuzhouliu 来看看，如果不符合需要再改一下。内容部分就没什么大问题了，改完之后就可以 approve changes

预览效果：https://deploy-preview-3984--oi-wiki.netlify.app/lang/java-pro/#_8

2022-08-06 06:48 UTC, aofall commented on docs/lang/java-pro.md
> +integer.intValue();  // 抛出 java.lang.NumberFormatException 异常
勘误，此处抛出 java.lang.NullPointerException 异常

2022-08-06 06:48 UTC, aofall commented on docs/lang/java-pro.md
> +???+ warning "注意"
/cc @shuzhouliu 此处的warning引用是否符合要求呢，预览页可见效果。

https://deploy-preview-3984--oi-wiki.netlify.app/lang/java-pro/#_8

2022-08-06 07:27 UTC, yusancky commented on docs/lang/java-pro.md
> +  虽然 JDK 增加了自动装箱拆箱的机制，但在声明变量时请选择合适的类型，因为包装类型 `Integer` 可以接受 `null`，而基本类型 `int` 不能接受 `null`。因此，对使用 `null` 值的包装类型进行拆箱操作时，会抛出异常。
> @aofall ：warning引用是否符合要求呢

抱歉，我格式化的时候没有留意。

把这里的缩进改成 4 个空格就可以了：
```suggestion
    虽然 JDK 增加了自动装箱拆箱的机制，但在声明变量时请选择合适的类型，因为包装类型 `Integer` 可以接受 `null`，而基本类型 `int` 不能接受 `null`。因此，对使用 `null` 值的包装类型进行拆箱操作时，会抛出异常。
```

2022-08-06 12:29 UTC, yusancky approved these changes

2022-08-06 12:50 UTC, aofall commented
896行的warning也有一样的问题

2022-08-06 13:07 UTC, aofall approved these changes
LGTM. Thx!

2022-08-06 13:44 UTC, merged