chore(misc/modifiable-mo-algo): 增加前往“普通莫队算法”页面的链接
OI-wiki/OI-wiki pull request #3987
Opened 2022-06-02 12:05 UTC by renbaoshuo

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论您是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈您的感受
3. 如果您熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2022-06-02 16:25 UTC, Backl1ght commented on docs/misc/modifiable-mo-algo.md
> +请确保您已经会普通莫队算法了。如果您还不会，请先阅读前面的“[普通莫队算法](./mo-algo.md)”。
```suggestion
请确保您已经会普通莫队算法了。如果您还不会，请先阅读前面的[普通莫队算法](./mo-algo.md)。
```

2022-06-02 16:25 UTC, Backl1ght commented on docs/misc/modifiable-mo-algo.md
> +请确保您已经会普通莫队算法了。如果您还不会，请先阅读前面的“[普通莫队算法](./mo-algo.md)”。
个人认为引号是多余的

2022-06-03 06:22 UTC, shuzhouliu requested changes

2022-06-03 06:22 UTC, shuzhouliu commented on docs/misc/modifiable-mo-algo.md
> +author: StudyingFather, Backl1ght, countercurrent-time, Ir1d, greyqz, MicDZ, ouuan, renbaoshuo
~~只是加个链接为什么要加author~~

2022-06-08 12:31 UTC, Early0v0 approved these changes

2022-06-11 09:42 UTC, WAAutoMaton approved these changes

2022-06-11 09:44 UTC, merged