fix #1932 feat: 增加Lambda表达式单独页面
OI-wiki/OI-wiki pull request #3988
Opened 2022-06-04 04:32 UTC by Persdre

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论您是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈您的感受
3. 如果您熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2022-06-06 07:25 UTC, Saisyc commented
不加说明的使用该图示，可能导致初学者误认为三分法问题的函数都是连续的

2022-06-06 07:38 UTC, Saisyc approved these changes
希望能简单介绍“Lambda表达式”名称的由来以及$\lambda$-演算的简单内容

2022-06-07 05:35 UTC, CoderOJ commented
> 希望能简单介绍“Lambda表达式”名称的由来以及-演算的简单内容

感觉 λ-演算 的内容和语法层面上的 lambda 关系不大吧，而且加了也会有很多内容，最好放到单独页面

2022-06-08 01:50 UTC, shuzhouliu requested changes
如果觉得我改的不必要的话可以不改（

2022-06-08 01:50 UTC, shuzhouliu commented on docs/lang/lambda.md
> +  // The following code declares a lambda expression that returns
```suggestion
  // 返回另一个计算两数之和 Lambda 表达式
```

2022-06-08 01:50 UTC, shuzhouliu commented on docs/lang/lambda.md
> +  // another lambda expression that adds two numbers.
```suggestion

```

2022-06-08 01:50 UTC, shuzhouliu commented on docs/lang/lambda.md
> +  // The returned lambda expression captures parameter x by value.
```suggestion

```

2022-06-08 01:50 UTC, shuzhouliu commented on docs/lang/lambda.md
> +  // lambda expression as its argument.
```suggestion

```

2022-06-08 01:50 UTC, shuzhouliu commented on docs/lang/lambda.md
> +  // The following code declares a lambda expression that takes another
同理

2022-06-08 01:50 UTC, shuzhouliu commented on docs/lang/lambda.md
> +  // The following code declares a lambda expression that takes another
```suggestion
  // 接受另外一个函数f作为参数，返回 f(z) 的两倍
```

2022-06-08 01:50 UTC, shuzhouliu commented on docs/lang/lambda.md
> +  // The lambda expression applies the argument z to the function f
```suggestion

```

2022-06-08 01:50 UTC, shuzhouliu commented on docs/lang/lambda.md
> +  // and multiplies by 2.
```suggestion

```

2022-06-08 01:50 UTC, shuzhouliu commented on docs/lang/lambda.md
> +  // Call the lambda expression that is bound to higherorder.
```suggestion
  // 调用绑定到 higherorder 的 Lambda 表达式
```

2022-06-08 01:50 UTC, shuzhouliu commented on mkdocs.yml
>        - 新版 C++ 特性: lang/new.md
https://oi-wiki.org/lang/new/ 中有 Lambda 表达式部分
<img width="596" alt="image" src="https://user-images.githubusercontent.com/64518651/172512767-6270de72-6d14-472c-9624-de55af334970.png">
可以考虑一下删除或合并到本页面（到这个pr

2022-06-08 01:50 UTC, shuzhouliu commented on docs/lang/lambda.md
> +int a = 0;  // Define an integer variable
好像没有什么必要吧（

2022-06-08 01:50 UTC, shuzhouliu commented on docs/lang/lambda.md
> +int a = 0;  // Define an integer variable
```suggestion
int a = 0;
```

2022-06-08 01:50 UTC, shuzhouliu commented on docs/lang/lambda.md
> +  // Print the result, which is (7+8)*2.
没有什么必要吧（

2022-06-08 01:50 UTC, shuzhouliu commented on docs/lang/lambda.md
> +  // Print the result, which is (7+8)*2.
```suggestion

```

2022-06-08 01:50 UTC, shuzhouliu commented on docs/lang/lambda.md
> +由于 **parameters 参数列表** 是可选的，如果不将参数传递给 Lambda 表达式，并且其 Lambda 声明器不包含 mutable，则可以省略空括号。
> parameters 参数列表

应该只有参数列表也可以

2022-06-08 01:50 UTC, shuzhouliu commented on docs/lang/lambda.md
> +int a = 0;                         // Define an integer variable
```suggestion
int a = 0;
```

2022-06-08 01:50 UTC, shuzhouliu commented on docs/lang/lambda.md
> +auto f = []() { return a * 9; };   // Error: 'a' cannot be accessed
```suggestion
auto f = []() { return a * 9; };   // Error: 'a' 不能被访问
```

2022-06-08 01:50 UTC, shuzhouliu commented on docs/lang/lambda.md
> +auto f = [a]() { return a * 9; };  // OK, 'a' is "captured" by value
```suggestion
auto f = [a]() { return a * 9; };  // OK, 'a' 被用值“捕获”
```

2022-06-08 01:50 UTC, shuzhouliu commented on docs/lang/lambda.md
> +auto f = [&a]() { return a++; };   // OK, 'a' is "captured" by reference
```suggestion
auto f = [&a]() { return a++; };   // OK, 'a' 被用引用“捕获”
```

2022-06-08 01:50 UTC, shuzhouliu commented on docs/lang/lambda.md
> +                                   //      Note: It is the responsibility of the
```suggestion
 // 请在 Lambda 被调用时确保 a 没有被摧毁
```

2022-06-08 01:50 UTC, shuzhouliu commented on docs/lang/lambda.md
> +                                   // programmer to ensure that a is not
```suggestion

```

2022-06-08 01:50 UTC, shuzhouliu commented on docs/lang/lambda.md
> +// destroyed before the lambda is called.
```suggestion

```

2022-06-08 01:50 UTC, shuzhouliu commented on docs/lang/lambda.md
> +auto b = f();  // Call the lambda function. a is taken from the capture list and
```suggestion
auto b = f();  // a 在捕获列表里取出，不在参数列表传入
```

2022-06-08 01:50 UTC, shuzhouliu commented on docs/lang/lambda.md
> +               // not passed here.
```suggestion

```

2022-06-08 01:50 UTC, shuzhouliu commented on docs/lang/lambda.md
> +auto x2 = [] { return {1, 2}; };    // ERROR: 返回类型被推导为 void
```suggestion
auto x2 = [] { return {1, 2}; };    // Error, 返回类型被推导为 void
```
前后文case不符合

2022-06-08 02:28 UTC, shuzhouliu requested changes
另外，标题中 fix #1932 应当挪到 pr 正文中

2022-06-08 12:45 UTC, Persdre commented
> 另外，标题中 fix #1932 应当挪到 pr 正文中
这个已经改好啦

2022-06-09 09:37 UTC, Marcythm commented
woc，原来本来是存在这个条目的吗，这下我得背锅了（当时 check 是否新内容的时候我没找到这个页面）
（不过仍然是有一些新内容的，合并进去也是可以的
另外我认为或许把一些篇幅较多的特性拆成单独页面进行讲解会好一些？
把注释都修改成中文的必要性还有待商榷，但现在 suggestion 中的翻译我认为还有明显提升的空间

2022-06-09 10:17 UTC, shuzhouliu commented
> 把注释都修改成中文的必要性还有待商榷，但现在 suggestion 中的翻译我认为还有明显提升的空间

确实，所以我说如果觉得我改的不必要的话可以不改（

2022-06-10 14:05 UTC, Saisyc commented
> > 希望能简单介绍“Lambda表达式”名称的由来以及-演算的简单内容
> 
> 感觉 λ-演算 的内容和语法层面上的 lambda 关系不大吧，而且加了也会有很多内容，最好放到单独页面

本人不太了解这方面，只是感觉貌似 Lambda 表达式可能与 $\lambda$-演算 有关，主要还是希望能简单介绍 Lambda 表达式的名称由来

2022-06-13 02:35 UTC, Persdre commented
> > > 希望能简单介绍“Lambda表达式”名称的由来以及-演算的简单内容
> > 
> > 
> > 感觉 λ-演算 的内容和语法层面上的 lambda 关系不大吧，而且加了也会有很多内容，最好放到单独页面
> 
> 本人不太了解这方面，只是感觉貌似 Lambda 表达式可能与 λ-演算 有关，主要还是希望能简单介绍 Lambda 表达式的名称由来

这个名字来自微积分数学中的 λ，其涵义是声明为了表达一个函数具体需要什么。

2022-06-13 13:44 UTC, Marcythm commented
根据 [haskell wiki](https://wiki.haskell.org/Lambda_abstraction) 的说法，
> A lambda abstraction is another name for an [anonymous function](https://wiki.haskell.org/Anonymous_function). It gets its name from the usual notation for writing it: for example, $\lambda x \to x^2$.. (Another common, equivalent notation is: $\lambda x . x^2$.)
而此处 $\lambda x.x^2$ 这一记法应是来源于 [lambda abstraction](https://en.wikipedia.org/wiki/Lambda_calculus)。

2022-06-14 09:56 UTC, renbaoshuo commented on docs/lang/lambda.md
> +                                   //      Note: It is the responsibility of the
@shuzhouliu 个人认为这里使用「销毁」要比「摧毁」好。

2022-07-09 15:58 UTC, Enter-tainer approved these changes

2022-07-09 22:49 UTC, Marcythm approved these changes

2022-07-10 01:13 UTC, merged