fix(number-theory/wilson): typo
OI-wiki/OI-wiki pull request #3996
Opened 2022-06-10 03:37 UTC by Tiphereth-A

#3991 

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论您是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈您的感受
3. 如果您熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2022-06-10 03:39 UTC, shuzhouliu requested changes
请将正文
> #3991

改为fix #3991

2022-06-10 03:40 UTC, Tiphereth-A commented
> 请将正文
> 
> > #3991
> 
> 改为fix #3991

done

2022-06-10 13:34 UTC, mudream4869 approved these changes

2022-06-11 09:48 UTC, WAAutoMaton approved these changes

2022-06-11 13:00 UTC, shuzhouliu approved these changes

2022-06-12 03:33 UTC, yizr-cnyali approved these changes
LGTM,thx!

2022-06-12 03:34 UTC, merged