fix: 修复了可持久化字典树页面的错误
OI-wiki/OI-wiki pull request #4001
Opened 2022-06-15 10:55 UTC by wood3

fix: 修复了可持久化字典树页面的错误

2022-06-23 09:56 UTC, Saisyc requested changes
```if(l==0)``` 没必要 ```max(l - 1, 0)```

2022-06-23 09:56 UTC, Saisyc approved these changes

2022-06-23 09:59 UTC, Early0v0 commented on docs/ds/code/persistent-trie/persistent-trie_1.cpp
> +        printf("%d\n", st.query(st.rt[r], st.rt[max(l - 1, 0)], s[n] ^ x));
```suggestion
        printf("%d\n", st.query(st.rt[r], st.rt[l - 1], s[n] ^ x));
```

2022-06-23 10:05 UTC, wood3 commented
> `if(l==0)` 分支下没必要 `max(l - 1, 0)`

原本是想不对原代码变动太多，既然大家觉得改了更好的话，我改好了~

2022-06-23 10:13 UTC, Saisyc commented
调试代码宜删除而非注释，此外，词条中的 Trie 应与字典树词条一致而写作 trie

2022-06-23 10:14 UTC, Saisyc commented
插播一句 ```o``` 做变量名不是件好事，在一些字体下，```o``` 和 ```0``` 非常像

2022-06-23 10:17 UTC, wood3 commented
> 调试代码宜删除而非注释，此外，词条中的 Trie 应与字典树词条一致而写作 trie
> 插播一句 `o` 做变量名不是件好事，在一些字体下，`o` 和 `0` 非常像

我知道你说的这些都是都是对的，但是我这个 pr 只想修复”当前被通过了的页面“中的错误。: )

2022-06-23 10:18 UTC, Saisyc commented
> > 调试代码宜删除而非注释，此外，词条中的 Trie 应与字典树词条一致而写作 trie
> > 插播一句 `o` 做变量名不是件好事，在一些字体下，`o` 和 `0` 非常像
> 
> 我知道你说的这些都是都是对的，但是我这个 pr 只想修复”当前被通过了的页面“中的错误。: )

支持 : )

2022-06-29 02:44 UTC, akakw1 approved these changes

2022-06-29 05:14 UTC, merged