feat: 添加了旋转 treap 的代码解释以及图片，前置知识，和更详细的简介
OI-wiki/OI-wiki pull request #4004
Opened 2022-06-19 00:51 UTC by ttzytt

修改了 `ds/treap.md`，添加了更详细的简介，前置知识，旋转 treap 的代码和一些示意图

2022-06-21 00:18 UTC, shuzhouliu requested changes

2022-06-21 00:18 UTC, shuzhouliu commented on docs/ds/treap.md
> +这个树就会变得非常“瘦长”（每次插入的节点都比前面的大，所以都被安排到右子节点了）：![](https://ttzytt.com/img/treap/search_tree_chain.svg)
外链？上传一下到oi-wiki/oi-wiki.

2022-06-21 17:24 UTC, ttzytt commented on docs/ds/treap.md
> +这个树就会变得非常“瘦长”（每次插入的节点都比前面的大，所以都被安排到右子节点了）：![](https://ttzytt.com/img/treap/search_tree_chain.svg)
ok，是直接上传到 `docs/ds/images` 吧

2022-06-22 02:45 UTC, Early0v0 reviewed
图和注释非常用心:heart:，但是：
1. 无旋 Treap 和 有旋 Treap 一个为大根堆，一个为小根堆，可能要统一一下？
2. 有旋 Treap 可以调整到「将 treap 包装成为 std::set」前。

2022-06-22 02:45 UTC, Early0v0 commented on docs/ds/treap.md
> +- 右子节点的值（$\textit{priority}$）比父节点小（当然这也是可以反过来的）
```suggestion
- 左子节点的值（$\textit{val}$）比父节点小
- 右子节点的值（$\textit{val}$）比父节点大（当然这也是可以反过来的）
```

2022-06-22 02:51 UTC, ttzytt commented on docs/ds/treap.md
> +- 右子节点的值（$\textit{priority}$）比父节点小（当然这也是可以反过来的）
彳亍，我晚点改

2022-06-26 21:33 UTC, ttzytt commented on docs/ds/treap.md
> +- 右子节点的值（$\textit{priority}$）比父节点小（当然这也是可以反过来的）
fixed，但是如果你感觉有问题，请先不要 merge，我这里还在写无旋 treap 的区间操作，应该较快就能搞好。

2022-06-26 23:10 UTC, ttzytt commented on docs/ds/treap.md
> +- 右子节点的值（$\textit{priority}$）比父节点小（当然这也是可以反过来的）
突然发现好像区间操作还要一段时间，如果可以的话还是先 merge 吧

2022-06-28 00:32 UTC, Early0v0 submitted a review, later dismissed

2022-06-29 02:40 UTC, akakw1 approved these changes

2022-06-29 06:30 UTC, Early0v0 approved these changes

2022-06-29 06:32 UTC, merged