Update devcpp.md
OI-wiki/OI-wiki pull request #4007
Opened 2022-06-21 01:58 UTC by BobRocket

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论您是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈您的感受
3. 如果您熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2022-06-21 17:55 UTC, CoelacanthusHex requested changes

2022-06-21 17:55 UTC, CoelacanthusHex commented on docs/tools/editor/devcpp.md
> +在国内大部分信息学竞赛中，Dev-C++ 是官方指定 IDE。
依 CCF NOI 科学委员会规定，自2021年9月1日起，NOI Linux 2.0 为 CCF 主办的 NOI 及 CSP-J/S 的标准竞赛环境。[^1]而 NOI Linux 2.0 并未包含 Dev-C++，故该条与事实不符。

[^1]: https://www.noi.cn/gynoi/jsgz/2021-07-16/732450.shtml

2022-06-22 02:15 UTC, abc1763613206 commented on docs/tools/editor/devcpp.md
> +在国内大部分信息学竞赛中，Dev-C++ 是官方指定 IDE。
https://www.noi.cn/xw/2021-10-19/745497.shtml

详细的环境可以参照这份名单。有些省仅提供Li;ux环境，故无Devcpp。

2022-06-22 02:33 UTC, ksyx commented
请参考 [如何贡献](https://oi-wiki.org/intro/htc/) 注意 commit msg 格式 thx :)

2022-06-23 09:49 UTC, Saisyc requested changes
参考 [NOI系列活动标准竞赛环境](https://www.noi.cn/gynoi/jsgz/2018-08-13/710465.shtml) 及其 [相关更新](https://www.noi.cn/gynoi/jsgz/2021-07-16/732450.shtml)，“在国内大部分信息学竞赛中，Dev-C++是官方指定IDE。”的说法可以认为是严重的事实错误！

2022-07-06 16:14 UTC, closed without merging