Add 对C++ STL复数文本运算符的介绍
OI-wiki/OI-wiki pull request #4014
Opened 2022-06-24 03:52 UTC by CharlesWuQiushi

增添了复数文本运算符的介绍。

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论您是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈您的感受
3. 如果您熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2022-06-24 04:19 UTC, Saisyc reviewed
请留意“文本运算符”的说法是否准确和通用，可参考 [cppreference : ""i](https://en.cppreference.com/w/cpp/numeric/complex/operator%22%22i)

2022-06-26 07:37 UTC, Tiphereth-A requested changes
这个东西的正式名称似乎叫字面量...

2022-06-26 07:37 UTC, Tiphereth-A commented on docs/math/complex.md
> +在 C++14 及以后的版本中，定义了文本运算符 `""if`、`""i`、`""il`。例如输入 `100i`，三者将分别返回实部为 $0$，虚部为 $100$ 的 `complex<float>`、`complex<double>` 以及 `complex<long double>`。这使得我们可以方便地书写形如 `auto z = 4 + 3i` 的复数声明。
```suggestion
在 C++14 及以后的版本中，定义了字面量 `std::literals::complex_literals::operator""if`、`std::literals::complex_literals::operator""i`、`std::literals::complex_literals::operator""il`. 例如 `100if`, `100i`, `100il`，分别相当于 `std::complex<float>{0.0f, 100.0f}`, `std::complex<double>{0.0, 100.0}` 以及 `std::complex<long double>{0.0l, 100.0l}`. 这使得我们可以方便地书写形如 `auto z = 4 + 3i` 的复数声明。
```

2022-06-27 07:12 UTC, Saisyc requested changes
我估摸着这也不叫“运算符”啊

2022-06-27 07:13 UTC, CharlesWuQiushi commented
> 我估摸着这也不叫“运算符”啊

cppreference是这么写的。

2022-06-27 07:15 UTC, Saisyc commented
> > 我估摸着这也不叫“运算符”啊
> 
> cppreference是这么写的。 “尽管 if 在 C++ 中是[关键词](https://zh.cppreference.com/w/cpp/keywords/if)，它亦为 operator ""if 形式的[字面量运算符](https://zh.cppreference.com/w/cpp/language/user_literal) 的 ud-suffix ，并在如 1if 或 1.0if 的字面量表达式中，因为它不被空白符分隔而且它不是独立记号。”

坏了，漏看了 `operator`

2022-06-27 07:21 UTC, Enter-tainer approved these changes
辛苦了

2022-06-29 06:34 UTC, Early0v0 approved these changes

2022-06-29 06:35 UTC, merged