feat: A format checker guided by format manuals v0.1
OI-wiki/OI-wiki pull request #4038
Opened 2022-07-07 22:01 UTC by llh721113

1. 使用 TypeScript 程序对仓库的文件进行格式检查
2. yarn run check <options> 以手动检查
3. 使用 husky 集成到 git hook 中，pre-commit 时自动触发
4. 编辑 checker_flag.json 以修改查错内容

2022-07-07 22:20 UTC, llh721113 commented
Usage: 
        -h      Show help.
        -f <path>       Check specified path.
        -a      Check all files.
        -s      Sort results according to files' name.
        -r      Show suggestions. Implies -s.
        -q      Check files quietly.
        --after=<time>, --before=<time>, --author=<time>, --grep<time>  Check matched files. Implies -a.

2022-07-07 23:09 UTC, abc1763613206 commented on package.json
> +	"name": "oi-wiki",
这里建议统一一下缩进，现在这种情况不太好比较差异。

2022-07-07 23:10 UTC, abc1763613206 commented on .husky/pre-commit
> +yarn run check
既然仓库里没有 `yarn.lock`，这里还是考虑换成 `npm` 吧。

2022-07-07 23:59 UTC, llh721113 commented
关于TypeScript源码适合在何时编译的问题，诸位有何看法（

2022-07-08 02:03 UTC, CoelacanthusHex commented
> 弱问 pre-commit hook 会影响在 web edit 吗

web edit 似乎是不执行 git hook 的

2022-07-08 03:10 UTC, CoelacanthusHex reviewed
在 CODEOWNERS 末尾加入
```
scripts/checker/	@llh721113
```
并在 `package.json` 行加入你的名字

2022-07-08 03:12 UTC, CoelacanthusHex commented
引用群内讨论
![图片](https://user-images.githubusercontent.com/43064781/177909709-fdea29cf-46e5-4bdd-b620-3b5b65600750.png)

2022-07-08 03:24 UTC, Menci commented
@CoelacanthusHex 可以这部分我这两天尽快做好

2022-07-09 00:45 UTC, Ir1d commented
@24OI-bot lint please

2022-07-11 06:36 UTC, CoelacanthusHex reviewed
- Need to rebase after https://github.com/OI-wiki/OI-wiki/pull/4033 merged.
- As https://github.com/OI-wiki/OI-wiki/pull/4038#issuecomment-1178494175 said, you need use `yarn ts-node-esm` as [`b9e8d0b` (#4041)](https://github.com/OI-wiki/OI-wiki/pull/4041/commits/b9e8d0b6d723d7ab8fa98eff18a9393106518935) do instead of generate js in repo.

2022-07-11 06:36 UTC, CoelacanthusHex commented on .husky/pre-commit
> +npm run check
lol, it need to change back to yarn.

2022-07-11 06:36 UTC, CoelacanthusHex commented on scripts/checker/checker.mts
> +	//console.log('git log --format="" --name-only ' + args);
May remove debug code or trigger it with an option?

2022-07-12 15:43 UTC, Menci commented on tsconfig.json
> +    "strict": true,
This breaks other scripts' compilation, remember to set it to `false`.

2022-07-30 13:47 UTC, CoelacanthusHex commented on package.json
> +    "check": "tsc && node ./scripts/checker/checker.mjs"
重复一遍，请使用 ts-node-esm

2022-07-30 13:47 UTC, CoelacanthusHex commented on package.json
> +    "gulp-purifycss": "^0.2.0",
这是原本删除的，又被你重新引入了（应该还有别的），请清理

2022-07-30 14:14 UTC, CoelacanthusHex commented on tsconfig.json
> +    "module": "ES2022",
我记得是因为bug刻意调低的版本

2022-07-30 14:33 UTC, CoelacanthusHex commented on tsconfig.json
> +    "target": "ES2020",
咋还矫枉过正了呢……

2022-07-30 15:29 UTC, llh721113 commented
暂时没有做hook，打算放到下一个PR做

2022-07-30 15:35 UTC, Menci requested changes

2022-07-30 15:35 UTC, Menci commented on scripts/checker/checker.ts
> +async function main() {
不需要用一个 async 函数来写 await 了，可以直接 top-level await

2022-08-09 09:17 UTC, llh721113 commented
@Menci

2022-08-09 09:18 UTC, Enter-tainer approved these changes
Generally LGTM

2022-08-09 09:21 UTC, Menci submitted a review, later dismissed

2022-08-09 10:13 UTC, Menci approved these changes

2022-08-09 11:51 UTC, merged

2022-08-23 04:29 UTC, Ir1d commented
本次事故提醒我们，在修改 package.json 后要重新检查一遍 bot, action 等脚本是否工作正常。本 pr 在检查 bot 后加了 remark 14 的依赖，然后忘记再查一遍了.. 因为现在 remark-details 还不能在 remark 14 工作，于是就崩坏了