更正主定理证明的格式
OI-wiki/OI-wiki pull request #4053
Opened 2022-07-14 03:19 UTC by Persdre

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论您是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈您的感受
3. 如果您熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2022-07-14 03:21 UTC, shuzhouliu commented
this branch is complicated 🤣

2022-07-14 03:21 UTC, shuzhouliu commented
try switching a branch for this pull request

2022-07-14 03:32 UTC, shuzhouliu requested changes
1. please do not put chinese characters in `$$` `$$` 
2. please consider the case of the words `case 1`, `case 2`, `case 3`
3. (not required) is there an svg for `master-theorem-proof.png`? If there is, please replace the png with svg format.

2022-07-14 03:33 UTC, shuzhouliu requested changes

2022-07-14 03:33 UTC, shuzhouliu commented on docs/basic/complexity.md
> +    case 2: 首先 g(n) = \Omega(f(n))，又因为 a f(n/b) <= c f(n)，只要 c 的取值是一个足够小的正数，且 n 的取值足够大，因此可以推导出：g(n) = O(f(n))。两侧夹逼可以得出，g(n) = \Theta(f(n))。
```suggestion
    case 2: 首先 g(n) = \Omega(f(n))，又因为 a f(\dfrac{n}{b}) <= c f(n)，只要 c 的取值是一个足够小的正数，且 n 的取值足够大，因此可以推导出：g(n) = O(f(n))。两侧夹逼可以得出，g(n) = \Theta(f(n))。
```

2022-07-14 03:34 UTC, shuzhouliu requested changes

2022-07-14 03:34 UTC, shuzhouliu commented on docs/basic/complexity.md
> +    case 3: f(n) = \Theta(n^{\log_b a})，因此 g(n) = O(n^{\\log_b a} {\\log n})。T(n) 的结果可在 g(n) 得出后显然得到。
```suggestion
    case 3: f(n) = \Theta(n^{\log_b a})，因此 g(n) = O(n^{\log_b a} {\log n})。T(n) 的结果可在 g(n) 得出后显然得到。
```
why use double `\`?

2022-07-14 03:36 UTC, shuzhouliu commented
<img width="584" alt="image" src="https://user-images.githubusercontent.com/64518651/178892634-56cb1168-a5ed-474f-a470-4e09faec4329.png">

2022-07-14 05:25 UTC, shuzhouliu commented
fixed:
- the fraction err
- the double \ err

You might still need to fix the Chinese chars in math blocks.

2022-07-14 05:56 UTC, Saisyc requested changes
一方面，主定理的中的系数$a,b$ 不必是正整数（虽然绝大多数情况都是正整数，但是对于具有不同分支的随机算法计算期望的时间复杂度时，系数往往不是整数）；

另一方面，$n^{\log_{b} a}$ 个 $\Theta(1)$ 相加得到 $\Theta(n^{\log_{b} a})$ 是乏力的，因为每个 $\Theta(1)$ 的系数不同，所有 $\Theta(1)$ 系数的上界的存在性没有保证；

此外，算法竞赛中真正使用的往往是 $\tau (n) = a \tau (\left\lfloor \frac{n}{b} \right\rfloor) + \tau(n \bmod b) + f(n)$，可以考虑对其进一步讨论证明其与 $\tau' (n) = a \tau' (\frac{n}{b}) + f(n)$ 的关系。

2022-07-14 06:05 UTC, Saisyc commented
我倾向于直接展开得到：

$$
\tau (n) = a \tau (\frac{n}{b}) + f(n) \implies \tau (n) = a^m \tau (\frac{n}{b^m}) + \sum_{0 \leqslant k < m} a^k f (\frac{n}{b^k})
$$

2022-07-14 23:17 UTC, shuzhouliu commented
@24OI-bot lint please

2022-07-15 00:30 UTC, shuzhouliu submitted a review, later dismissed
still better if you use svgs :heart:

2022-07-15 08:07 UTC, Marcythm approved these changes

2022-07-15 08:13 UTC, shuzhouliu approved these changes

2022-07-15 08:32 UTC, shuzhouliu commented
> 一方面，主定理的中的系数a,b 不必是正整数（虽然绝大多数情况都是正整数，但是对于具有不同分支的随机算法计算期望的时间复杂度时，系数往往不是整数），且 logb⁡n 往往不是整数；
> 
> 另一方面，nlogb⁡a 个 Θ(1) 相加得到 Θ(nlogb⁡a) 是有误导性的，因为每个 Θ(1) 的系数不同，所有 Θ(1) 系数的上界的存在性没有保证；
> 
> 此外，算法竞赛中真正使用的往往是 τ(n)=aτ(⌊nb⌋)+τ(nmodb)+f(n)，可以考虑对其进一步讨论证明其与 τ′(n)=aτ′(nb)+f(n) 的关系。

若您对此有疑义，欢迎pr。:heart:

2022-07-15 08:52 UTC, merged