feat(dp/basic): 加入最长公共子序列的名词解释和例题
OI-wiki/OI-wiki pull request #4092
Opened 2022-07-19 13:59 UTC by Persdre

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论您是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈您的感受
3. 如果您熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2022-07-19 20:57 UTC, Saisyc requested changes
赘述且口语化

2022-07-20 02:34 UTC, Persdre commented on docs/dp/basic.md
> +首先我们要说明一下什么是子序列。子序列指的是不改变一个序列的顺序，但从这个序列中去掉若干元素从而获得的一个新的序列。例如：$abc$ 的子序列可以是 $ab$，$ac$。子序列是不需要在原来的序列之中连续出现的。与子序列相对应的一个概念是子串。子串必须在原来的序列之中连续出现。所以 $abc$ 的子串就不包括 $ac$ 了。
ok,那我这里改成一个链接好了

2022-07-20 02:36 UTC, Persdre commented on docs/dp/basic.md
> +如果一个序列既是 $A$ 的子序列，也是 $B$ 的子序列， 那么该序列称为 $A$ 和 $B$ 的公共子序列。 公共子序列可能有多个，例如字符串 $abcde$ 与字符串 $acde$， 它们的公共子序列有 $a$，$c$，$d$，$e$，$ac$，$ad$，$ae$，$cd$，$ce$，$de$，$ade$，$ace$，$cde$，$acde$。最长公共子序列问题即是求解两个字符串的所有公共
这里是想给一个具体的例子来着，所以列出了所有的公共子序列

2022-07-20 09:54 UTC, Saisyc requested changes
反对赘述

2022-07-21 00:57 UTC, Saisyc commented
作为一篇独立题解，加入基础概念的解释与示例，特别是对于初学者读者而言，可能是友好的；

但是作为OI-wiki的内容，大概是冗余而不合适的

2022-07-21 19:05 UTC, Saisyc requested changes
在动态规划词条详细介绍字符串词条的术语定义是不必要与不合适的

2022-07-21 23:56 UTC, Marcythm commented
> 在动态规划词条详细介绍字符串词条的术语定义是不必要与不合适的

在 OI-wiki 整天说别人做的工作是「不必要与不合适的」却不亲自上手做任何建设性的工作甚至讨论，是不必要不合适甚至不礼貌的，不妨考虑输出到社会

2022-07-22 00:57 UTC, Marcythm approved these changes

2022-07-22 00:58 UTC, merged