feat(tools/compiler): 编译器安装教程
OI-wiki/OI-wiki pull request #4105
Opened 2022-07-22 07:44 UTC by renbaoshuo

resolves #1766.

---

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论您是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈您的感受
3. 如果您熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2022-07-22 08:10 UTC, GitPinkRabbit commented
Windows 下，对于 WinLibs 有必要进行介绍吗？进一步地，对于 WinLibs 和 MinGW 之间的关系有必要进行介绍吗？

因为我都是从 WinLibs 那里装的，我自己也不太清楚其中关系（上次从奇怪渠道下载 MinGW 得到了很老的版本）

2022-07-22 08:15 UTC, alphagocc commented
winlibs 感觉是一个 mingw distro 的这样子？

2022-07-22 08:34 UTC, Enter-tainer commented
感觉需要区分一下 mingw mingw-w64 ? 印象里面这几个东西好像有点区别。但是我好像也记不清了（

2022-07-22 08:39 UTC, GitPinkRabbit requested changes
为什么要改成用命令来打开环境变量设置，感觉挺麻烦的。可以考虑用外部链接来解释如何打开修改环境变量的界面，或者恢复原先用图形界面打开的版本

2022-07-22 08:42 UTC, renbaoshuo commented
> 感觉需要区分一下 mingw mingw-w64 ? 印象里面这几个东西好像有点区别。但是我好像也记不清了（

我记得 MinGW 凉好久了，现在都指 MinGW-w64

2022-07-22 08:46 UTC, yizr-cnyali commented
> > 感觉需要区分一下 mingw mingw-w64 ? 印象里面这几个东西好像有点区别。但是我好像也记不清了（
> 
> 我记得 MinGW 凉好久了，现在都指 MinGW-w64

那要不要再简单的讲下 MinGW-w64 的不同 build 呀 上面粉兔的 comment 也有提到不同下载渠道提供的build version的差异

2022-07-22 09:00 UTC, GitPinkRabbit commented
> > 为什么要改成用命令来打开环境变量设置，感觉挺麻烦的。可以考虑用外部链接来解释如何打开修改环境变量的界面，或者恢复原先用图形界面打开的版本
> 
> 因为不同版本的 Windows 10 打开环境变量设置页面的步骤不尽相同，使用命令打开会更通用一些。

我以前甚至没听说过能用 Win+R 运行 + 命令直接打开环境变量界面。  
主要是感觉 “打开环境变量设置界面” 是一个一般化的需求，特别是考虑到 OI Wiki 中存在复数个页面提到这一设置：

![image](https://user-images.githubusercontent.com/46786295/180403590-01e08c6d-0802-4856-8162-9d7923414708.png)

（当然，其中一些是提示进行自动设置）  
所以可能不适合在任何一个提到的地方单独讲或直接不讲

2022-07-22 09:05 UTC, negiizhao commented
> > > 为什么要改成用命令来打开环境变量设置，感觉挺麻烦的。可以考虑用外部链接来解释如何打开修改环境变量的界面，或者恢复原先用图形界面打开的版本
> > 
> > 
> > 因为不同版本的 Windows 10 打开环境变量设置页面的步骤不尽相同，使用命令打开会更通用一些。
> 
> 我以前甚至没听说过能用 Win+R 运行 + 命令直接打开环境变量界面。 主要是感觉 “打开环境变量设置界面” 是一个一般化的需求，特别是考虑到 OI Wiki 中存在复数个页面提到这一设置：
> 
> ![image](https://user-images.githubusercontent.com/46786295/180403590-01e08c6d-0802-4856-8162-9d7923414708.png)
> 
> （当然，其中一些是提示进行自动设置） 所以可能不适合在任何一个提到的地方单独讲或直接不讲

从我的使用体验上来说，win10以上使用左下的搜索功能打开环境变量似乎是最方便的……不过并没有广泛测试过这个方法

2022-07-22 09:25 UTC, CoelacanthusHex requested changes

2022-07-22 09:25 UTC, CoelacanthusHex commented on docs/tools/compiler.md
> +```
首先 Ss 不是安装命令，是搜索命令
其次这两条命令可以合成一条
````suggestion
使用命令直接安装即可：

```bash
sudo pacman -Syu gcc
```
````

2022-07-22 13:23 UTC, Backl1ght commented
我在想是否有必要增加安装某个特定版本编译器的部分？

2022-07-22 16:19 UTC, hly1204 commented
稍微说一点在 Linux 下用源代码安装 GCC 版本的一些简单描述，首先使用系统一般就有的包管理工具安装类似于 gmp，m4，texinfo 的 `-devel` 后缀的相关依赖（如果在系统安装时没有选择精简版一般不用特地安装），一般系统都是自带 gnu make 的构建工具，然后通过包管理工具安装可能不是最新版的 GCC 编译器二进制文件，从 <http://www.gnu.org/prep/ftp.html> 上的镜像列表中下载源文件的打包，然后在本地进入包的目录下，使用 `./configure --help` 查看配置选项，选择 host 和 target 以及语言（一般是 c,c++）和 `prefix` 路径等，后会生成一个 `Makefile`，使用命令 `make -j8 && make install` 安装到指定的路径下，当然 `-j8` 是看处理器核心数量什么的多线程搞，也可以是 `-j6`，然后在对应目录（前面指定的或者默认）下的 `bin` 当中就有了编译出来的 GCC 编译器啦。

然后说到 MinGW-w64 也可以在 Linux 上用 <https://github.com/Zeranoe/mingw-w64-build> 的脚本安装，然后编译出不依赖于 `libstdc++.dll` 的 Windows 的可执行文件等，但是这个貌似 OI 不太有用。

2022-07-22 16:25 UTC, CoelacanthusHex commented
不推荐裸编译安装，debian 系和 rpm 系请用 checkinstall 安装，Arch 系请 AUR

2022-07-23 02:21 UTC, Cubik65536 requested changes
提供一下 macOS 的安装方法：

------

1. 首先更新包管理器

``` bash
brew upgrade
brew update
```

2. 然后直接使用命令安装：

``` bash
brew install gcc
```

备注：需要使用 `g++-11` 命令才可以使用正确的 GNU GCC，GCC 12 成为 brew 默认版本后可能会变成 `g++-12`

------

我认为还是挺有用的，另外，实测在使用 VSCode + Code Runner 插件并且将编译器设置（`code-runner.executorMap` -> `cpp`）为 gcc 时，万能头 `#include <bits/stdc++.h>` 可以直接使用而不需要像[此处](https://oi.wiki/tools/editor/xcode/#_6)所讲的进行额外设置

2022-07-23 04:06 UTC, Xeonacid commented on docs/tools/compiler.md
> +接下来打开终端，输入 `g++ --version` 并按下回车，如果出现如图所示的提示则代表安装成功。
加完环境变量需要重启/刷一下path才能生效

2022-07-23 05:30 UTC, alphagocc commented on docs/tools/compiler.md
> +接下来打开终端，输入 `g++ --version` 并按下回车，如果出现如图所示的提示则代表安装成功。
不需要，只要开一个新终端的就可以了

2022-07-23 09:47 UTC, CoelacanthusHex commented
> 
> 我认为还是挺有用的，另外，实测在使用 VSCode + Code Runner 插件并且将编译器设置（`code-runner.executorMap` -> `cpp`）为 gcc 时，万能头 `#include <bits/stdc++.h>` 可以直接使用而不需要像[此处](https://oi.wiki/tools/editor/xcode/#_6)所讲的进行额外设置

事实上那篇文章有提到使用 GNU 工具链是有万能头的……

2022-07-23 17:23 UTC, Cubik65536 commented
> > 我认为还是挺有用的，另外，实测在使用 VSCode + Code Runner 插件并且将编译器设置（`code-runner.executorMap` -> `cpp`）为 gcc 时，万能头 `#include <bits/stdc++.h>` 可以直接使用而不需要像[此处](https://oi.wiki/tools/editor/xcode/#_6)所讲的进行额外设置
> 
> 事实上那篇文章有提到使用 GNU 工具链是有万能头的……

是的，但是那篇文章没提到的是怎么安装使用GNU工具链，所以我说我认为在此处添加这个是有很大用的

2022-07-24 05:09 UTC, renbaoshuo commented
@Cubik65536 感谢，已添加。

2022-09-29 09:01 UTC, alphagocc approved these changes
LGTM

2022-10-02 02:00 UTC, Cubik65536 approved these changes

2022-10-02 05:38 UTC, Enter-tainer commented
@CoelacanthusHex review pls

2022-10-02 05:41 UTC, Tiphereth-A commented on mkdocs.yml
> +    - 编译器: tools/compiler.md
这个感觉叫 GCC 更合适一些
```suggestion
    - GCC: tools/compiler.md
```

2022-10-02 05:43 UTC, renbaoshuo commented on mkdocs.yml
> +    - 编译器: tools/compiler.md
CCF 官方指定的编译器就是 GCC 系列的编译器，如果改名的话个人认为不太合适。

另外，在页面内也有提示：

> 本页面主要介绍了各系统下 GCC 编译器的安装步骤。

2022-10-02 05:44 UTC, Tiphereth-A commented on mkdocs.yml
> +    - 编译器: tools/compiler.md
另外, GCC 全称是 GNU Compiler Collection, "GCC 编译器" 的说法似乎赘余了 🤔

2022-10-02 05:46 UTC, yizr-cnyali commented on mkdocs.yml
> +    - 编译器: tools/compiler.md
那把页面内的提示改成“各系统下 GCC 的安装步骤”应该就ok了吧

2022-10-02 05:47 UTC, renbaoshuo commented on mkdocs.yml
> +    - 编译器: tools/compiler.md
Updated.

2022-10-02 05:52 UTC, Tiphereth-A commented on mkdocs.yml
> +    - 编译器: tools/compiler.md
> CCF 官方指定的编译器就是 GCC 系列的编译器，如果改名的话个人认为不太合适。

OI wiki 上介绍和使用的语言不止是 C/C++, 要是页面名字叫编译器的话那至少还应该补充 Java 和 Python 的常用编译器安装流程 (Pascal 也可以补充)

2022-10-02 06:17 UTC, CoelacanthusHex commented on mkdocs.yml
> +    - 编译器: tools/compiler.md
要改就文件名标题一起改

2022-10-02 06:18 UTC, CoelacanthusHex commented on mkdocs.yml
> +    - 编译器: tools/compiler.md
> > CCF 官方指定的编译器就是 GCC 系列的编译器，如果改名的话个人认为不太合适。
> 
> OI wiki 上介绍和使用的语言不止是 C/C++, 要是页面名字叫编译器的话那至少还应该补充 Java 和 Python 的常用编译器/解释器安装流程 (Pascal 也可以补充)

我觉得大可不必一次就写完整

2022-10-02 06:34 UTC, Tiphereth-A commented on mkdocs.yml
> +    - 编译器: tools/compiler.md
> 我觉得大可不必一次就写完整

那可以加一些空章节, 然后在之后的 PR 中补充 🤔

2022-10-03 00:39 UTC, Xeonacid approved these changes

2022-10-03 00:48 UTC, hly1204 approved these changes

2022-10-03 02:29 UTC, Great-designer commented
@CoelacanthusHex

2022-10-03 06:11 UTC, CoelacanthusHex approved these changes

2022-10-03 06:12 UTC, merged