feat(math/linear-algebra-index.md): 添加线性代数简介与线性空间相关内容
OI-wiki/OI-wiki pull request #4120
Opened 2022-07-25 04:26 UTC by codewasp942

笔者认为，讲讲线性代数的本质，追溯概念的根源与联系，让读者对于线性代数有一个初步但是成体系的认识，确实有其必要性。

2022-07-25 09:14 UTC, Saisyc requested changes
“基域 $P$”并不是规范的术语

2022-07-25 09:18 UTC, Saisyc commented
“三原色”“三基色” 可能引起歧义

2022-07-25 09:39 UTC, Saisyc reviewed
存在一些容易改善的瑕疵；此外，可考虑将本词条与向量词条合并。

然而，词条名为线性代数简介，但几乎只介绍了线性空间，似乎不太相符。

2022-07-25 09:39 UTC, Saisyc commented on docs/math/linear-algebra-index.md
> +已知线性方程组最早的应用是 1500 多年前的鸡兔同笼问题。此后，经过一代代数学家的摸索，线性代数在 20 世纪成为了一个独立的数学分支。从鸡兔同笼算起，线性代数的创立历时一千余年。
**缺乏可靠信息来源**

2022-07-25 09:39 UTC, Saisyc commented on docs/math/linear-algebra-index.md
> +这些性质与所描述对象的 **缩放**、**分解**、**叠加** 等有关。线性代数把这些性质从具体对象中抽象出来，作为一个独立的学科来研究。在 OI 中，线性代数的知识可以直接用来解决问题，也可以用于优化算法、数据结构等。例如：
举例中，与“力”及三角函数相比，“颜色”的“缩放”可能不是比较显然的

2022-07-25 09:39 UTC, Saisyc commented on docs/math/linear-algebra-index.md
> +线性代数源于人们的观察。人们发现，很多对象都拥有相似的性质，比如：
举例内容在 OI 与线性代数中可能不够具有代表性

2022-07-25 09:39 UTC, Saisyc commented on docs/math/linear-algebra-index.md
> +不是很严谨地说，数量乘法对应着一种 **“缩放”**，基域 $P$ 中的元素就代表着缩放的 **“比例”**，向量加法对应 **“叠加”**。同时，$P$ 中的元素还代表着向量的 **“坐标”** 的取值范围。
标量与数量的称呼应统一

2022-07-25 09:39 UTC, Saisyc commented on docs/math/linear-algebra-index.md
> +1. **标量乘法一致于标量的域乘法**：对于 $a,b\in P,u\in V$，$a(bu)=(ab)u$
“域乘法”不必写作“标量的域乘法”

2022-07-25 09:50 UTC, Saisyc commented on docs/math/linear-algebra-index.md
> +已知线性方程组最早的应用是 1500 多年前的鸡兔同笼问题。此后，经过一代代数学家的摸索，线性代数在 20 世纪成为了一个独立的数学分支。从鸡兔同笼算起，线性代数的创立历时一千余年。
请注意以下两个方面：

### 1 线性方程组 *最早* 的应用是否是鸡兔同笼问题？    

参考 [A Brief History of Linear Algebra](https://www.math.utah.edu/~gustafso/s2016/2270/web-projects/christensen-HistoryLinearAlgebra.pdf)：

    Around 4000 years ago, the people of Babylon knew how to solve a simple 2X2 system of linear
    equations with two unknowns. Around 200 BC, the Chinese published that “Nine Chapters of the
    Mathematical Art,” they displayed the ability to solve a 3X3 system of equations (Perotti).

### 2 线性代数成为 *独立* 数学分支是否在 20 世纪？

参考 [Linear algebra](https://en.wikipedia.org/wiki/Linear_algebra#History)：

    Linear algebra took its modern form in the first half of the twentieth century,
    when many ideas and methods of previous centuries were generalized as abstract algebra.

2022-07-25 09:52 UTC, Great-designer commented
好家伙。这种引入方式从“线性空间”开始了……有些惊艳

2022-07-25 10:08 UTC, Saisyc commented
> 好家伙。这种引入方式从“线性空间”开始了……有些惊艳

别从有限阶的行列式和有限维的矩阵乘法开始就好

2022-07-25 10:42 UTC, codewasp942 commented on docs/math/linear-algebra-index.md
> +1. **标量乘法一致于标量的域乘法**：对于 $a,b\in P,u\in V$，$a(bu)=(ab)u$
已修正

2022-07-25 10:42 UTC, codewasp942 commented on docs/math/linear-algebra-index.md
> +不是很严谨地说，数量乘法对应着一种 **“缩放”**，基域 $P$ 中的元素就代表着缩放的 **“比例”**，向量加法对应 **“叠加”**。同时，$P$ 中的元素还代表着向量的 **“坐标”** 的取值范围。
fixed!

2022-07-25 10:45 UTC, Saisyc commented on docs/math/linear-algebra-index.md
> +早在几千年前，就有古人应用线性方程组解决问题；此后，经过一代代数学家的摸索，线性代数在 20 世纪成为了一个独立的数学分支。从鸡兔同笼算起，线性代数的创立历时一千余年。
“20世纪成为独立数学分支”可能缺乏可靠信息来源。

“从鸡兔同笼算起线性代数的创立”缺乏合理性。

2022-07-25 10:47 UTC, Saisyc requested changes
请注意格式手册有关要求

2022-07-25 10:47 UTC, Saisyc commented on docs/math/linear-algebra-index.md
>      本篇与“线性代数”分类下的其他篇目关联不大。但笔者认为，讲讲线性代数的本质，追溯概念的根源与联系，让读者对于线性代数有一个初步但是成体系的认识，确实有其必要性。
引号的使用请参考格式手册

2022-07-25 10:50 UTC, Saisyc approved these changes
若有余力，可考虑对整个向量词条进行公理化思路的重构

2022-07-25 10:50 UTC, Saisyc commented on docs/math/vector.md
> +## 向量的更严格定义
使用二级标题不太合适，宜作为 `## 向量` 的子内容

2022-07-25 11:04 UTC, codewasp942 commented
刚刚 dismissed 是怎么了？

2022-07-25 11:21 UTC, Great-designer commented
> > 好家伙。这种引入方式从“线性空间”开始了……有些惊艳
> 
> 别从有限阶的行列式与有限维的矩阵乘法开始就好

啥……我是想从方程组引入来着。这样就可以对于新手而言由简单到困难一步一步来：先讲OI常用的高斯消元，再讲其他概念等等。

不过，先讲空间也可以，没什么问题。行列式必须要出现在矩阵之后，矩阵必须出现在向量之后，这个必然是共识。

2022-07-25 12:23 UTC, Great-designer commented
> 刚刚 dismissed 是怎么了？

是这样的：view只对那个版本有效。只要更新，就会使得上一个版本的所有view无效。所有的approve观点都适用于这里。有可能某个版本得到了较多的approve，但是一更新，approve全没了。因此要珍惜approve。

如果view认为文本段中哪里有问题，则需要修改该文本段，才能消掉这个view，这时候会显示相应的评论outdated或者可以resolved。

2022-07-25 12:32 UTC, Great-designer commented
我读了读，认为对于线性代数这种很杂乱的学科，作为引入章节而言，写成啥样都问题不大。其中重点的话，只要把逻辑体系搭建好就行。所以这个Pull request写的还可以。

注：都是入门章节，由于学科特点，线性代数给人的感觉和数论是相反的。线性代数让人看起来入门就眼花缭乱困难（实际不应该困难），数论入门是让人一看这也太小儿科了吧（实际应该尽可能严谨），所以入门章节应当有着不太一样的要求。

2022-07-25 13:46 UTC, Saisyc commented
我对这个例子感到有些困惑：

    用高斯消元解决复杂概率问题

似乎 Markov 过程等问题中用到高斯消元其实就是纯粹的解列出的线性方程组？

2022-07-29 08:37 UTC, Great-designer commented
现在我这边完全不急（没开始写），等等这个PR吧。

2022-07-29 09:12 UTC, codewasp942 commented
> 现在我这边完全不急（没开始写），等等这个PR吧。

我改完了，求merge。

vector 词条的公理化重构到时候再追加吧。

2022-07-29 14:30 UTC, Great-designer commented
> > 现在我这边完全不急（没开始写），等等这个PR吧。
> 
> 我改完了，求merge。
> 
> vector 词条的公理化重构到时候再追加吧。

挺好。我这里到时候打算改改架构，页面会变成：
——线性代数外——
- 坐标系（coordinate）
——线性代数里——
- 简介
- 向量
- 内积与外积（product，外积只需要二阶和三阶行列式，可以作为特例单独定义）
- 矩阵（介绍矩阵之前必须介绍向量内积，不然很难理解矩阵乘法）
- 行列式（determinate，用到初等行变换）
- 高斯消元（用到初等行变换）
……其他
欢迎内容上的公理化重构。我这可能只会改改架构，顺便补点我了解到的由于地区不同（西方或者其他中文地区，例如部分西方地区用字母“\tau”表示二倍圆周率（弧度制部分），中国台湾地区对于“行”和“列”的翻译恰好与中国大陆地区相反），以及数学物理学科不同的翻译不同（例如向量/矢量、内积/标积/点乘（俗称）、外积/矢积/叉乘（俗称）、特征/本征、酉/幺正），计算机距离数学更近一些，OI Wiki正文当然遵从数学学科的翻译。

2022-07-30 08:19 UTC, Enter-tainer approved these changes

2022-07-30 12:53 UTC, merged

2022-07-30 12:58 UTC, Great-designer commented
贺电！