feat(graph/scc): 完善算法流程,令其可读性更强
OI-wiki/OI-wiki pull request #4136
Opened 2022-07-29 09:30 UTC by F1shAndCat

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论您是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈您的感受
3. 如果您熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2022-07-29 09:50 UTC, Saisyc requested changes
支持更详细的讲解，但请注意 [格式手册](https://oi-wiki.org/intro/format/) 有关规定~

2022-07-29 09:50 UTC, Saisyc commented on docs/graph/scc.md
> +2. $\textit{low}_u$：在u的子树中能够回溯到的最早的已经在栈中的结点。设以 $u$ 为根的子树为 $\textit{Subtree}_u$。$\textit{low}_u$ 定义为以下结点的 $\textit{dfn}$ 的最小值：$\textit{Subtree}_u$ 中的结点；从 $\textit{Subtree}_u$ 通过一条不在搜索树上的边能到达的结点。
为保持上下文的一致性，应使用 $u$ 而非 `u`

2022-07-29 09:50 UTC, Saisyc commented on docs/graph/scc.md
> +按照深度优先搜索算法搜索的次序对图中所有的结点进行搜索,按搜索次序对各个结点dfn赋值,且入栈。当找到一个强连通元素时,按照该元素包含结点数目让栈中元素退栈。在搜索过程中，对于结点 $u$ 和与其相邻的结点 $v$（$v$ 不是 $u$ 的父节点）考虑 3 种情况：
`按搜索次序对各个结点dfn赋值` 与 dfn 的定义重复，但这种冗余的说明可能对于初学者是友好的，需要作者自行判断；但总的来说 ·按照深度优先搜索算法搜索的次序对图中所有的结点进行搜索,按搜索次序对各个结点dfn赋值,且入栈` 读起来有些吃力与复杂，可能需要改善；此外，注意英文逗号与中文逗号不要混用。

`让栈中元素退栈` 注意“出栈”是更通用的术语。

2022-07-29 10:09 UTC, F1shAndCat commented on docs/graph/scc.md
> +按照深度优先搜索算法搜索的次序对图中所有的结点进行搜索,按搜索次序对各个结点dfn赋值,且入栈。当找到一个强连通元素时,按照该元素包含结点数目让栈中元素退栈。在搜索过程中，对于结点 $u$ 和与其相邻的结点 $v$（$v$ 不是 $u$ 的父节点）考虑 3 种情况：
我的我的,马上修改

2022-07-29 10:09 UTC, F1shAndCat commented on docs/graph/scc.md
> +2. $\textit{low}_u$：在u的子树中能够回溯到的最早的已经在栈中的结点。设以 $u$ 为根的子树为 $\textit{Subtree}_u$。$\textit{low}_u$ 定义为以下结点的 $\textit{dfn}$ 的最小值：$\textit{Subtree}_u$ 中的结点；从 $\textit{Subtree}_u$ 通过一条不在搜索树上的边能到达的结点。
收到

2022-07-29 10:11 UTC, Saisyc commented on docs/graph/scc.md
> +按照深度优先搜索算法搜索的次序对图中所有的结点进行搜索,按搜索次序对各个结点dfn赋值,且入栈。当找到一个强连通元素时,按照该元素包含结点数目让栈中元素退栈。在搜索过程中，对于结点 $u$ 和与其相邻的结点 $v$（$v$ 不是 $u$ 的父节点）考虑 3 种情况：
> 我的我的,马上修改

其实除了英文逗号以外其实其他的大概都是可改可不改的东西~

2022-07-29 10:16 UTC, Saisyc requested changes
英文逗号一堆堆，鉴定为该换键盘了~（逃

2022-07-29 10:16 UTC, Saisyc commented on docs/graph/scc.md
> +2. $\textit{low}_u$：在$u$的子树中能够回溯到的最早的已经在栈中的结点。设以 $u$ 为根的子树为 $\textit{Subtree}_u$。$\textit{low}_u$ 定义为以下结点的 $\textit{dfn}$ 的最小值：$\textit{Subtree}_u$ 中的结点；从 $\textit{Subtree}_u$ 通过一条不在搜索树上的边能到达的结点。
按照格式手册 `在$u$的` 貌似要写作 `在 $u$ 的`，可以去确认一下，毕竟上下文都是这么写的；

2022-07-29 10:16 UTC, Saisyc commented on docs/graph/scc.md
> +按照深度优先搜索算法搜索的次序对图中所有的结点进行搜索,维护每个结点的变量,且让搜索到的结点入栈。,每当找到一个强连通元素,就按照该元素包含结点数目让栈中元素出栈。在搜索过程中，对于结点 $u$ 和与其相邻的结点 $v$（$v$ 不是 $u$ 的父节点）考虑 3 种情况：
`入栈。,每当` 与 `元素,就按照` 还是英文逗号哇~

2022-07-29 10:16 UTC, Saisyc submitted a review, later dismissed

2022-07-29 10:16 UTC, F1shAndCat commented on docs/graph/scc.md
> +按照深度优先搜索算法搜索的次序对图中所有的结点进行搜索,维护每个结点的变量,且让搜索到的结点入栈。,每当找到一个强连通元素,就按照该元素包含结点数目让栈中元素出栈。在搜索过程中，对于结点 $u$ 和与其相邻的结点 $v$（$v$ 不是 $u$ 的父节点）考虑 3 种情况：
刚刚已经改了,没有显示出来吗

2022-07-29 10:18 UTC, F1shAndCat commented on docs/graph/scc.md
> +2. $\textit{low}_u$：在$u$的子树中能够回溯到的最早的已经在栈中的结点。设以 $u$ 为根的子树为 $\textit{Subtree}_u$。$\textit{low}_u$ 定义为以下结点的 $\textit{dfn}$ 的最小值：$\textit{Subtree}_u$ 中的结点；从 $\textit{Subtree}_u$ 通过一条不在搜索树上的边能到达的结点。
收到,格式上错误好多,我哭死😭

2022-07-29 10:22 UTC, Saisyc approved these changes
每个 commit 的 approve 是独立的，以及只有管理员的 approve 对于合并才是有作用的；接下来等管理员就好啦~~~

虽然但是，此 PR 的标题也是英文逗号（哈哈哈 O(∩_∩)O

2022-07-29 10:25 UTC, F1shAndCat commented
> 每个 commit 的 approve 是独立的，以及只有管理员的 approve 对于合并才是有作用的；接下来等管理员就好啦~~~
> 
> 虽然但是，此 PR 的标题也是英文逗号（哈哈哈 O(∩_∩)O

我...😭😭😭(其实是为了防止码代码的时候开开输入法导致出错在系统设置里开了始终使用英文符号)

2022-07-29 10:29 UTC, Menci requested changes

2022-07-29 10:29 UTC, Menci commented on docs/graph/scc.md
> +按照深度优先搜索算法搜索的次序对图中所有的结点进行搜索，维护每个结点的变量，且让搜索到的结点入栈。每当找到一个强连通元素，就按照该元素包含结点数目让栈中元素出栈。在搜索过程中，对于结点 $u$ 和与其相邻的结点 $v$（$v$ 不是 $u$ 的父节点）考虑 3 种情况：
什么是「结点的变量」？

2022-07-29 10:30 UTC, F1shAndCat commented on docs/graph/scc.md
> +按照深度优先搜索算法搜索的次序对图中所有的结点进行搜索，维护每个结点的变量，且让搜索到的结点入栈。每当找到一个强连通元素，就按照该元素包含结点数目让栈中元素出栈。在搜索过程中，对于结点 $u$ 和与其相邻的结点 $v$（$v$ 不是 $u$ 的父节点）考虑 3 种情况：
dfn和low

2022-07-29 10:31 UTC, Saisyc commented on docs/graph/scc.md
> +按照深度优先搜索算法搜索的次序对图中所有的结点进行搜索，维护每个结点的变量，且让搜索到的结点入栈。每当找到一个强连通元素，就按照该元素包含结点数目让栈中元素出栈。在搜索过程中，对于结点 $u$ 和与其相邻的结点 $v$（$v$ 不是 $u$ 的父节点）考虑 3 种情况：
> 什么是「结点的变量」？

也许是指 dfn；看来又出锅了~

2022-07-29 10:33 UTC, F1shAndCat commented on docs/graph/scc.md
> +按照深度优先搜索算法搜索的次序对图中所有的结点进行搜索，维护每个结点的变量，且让搜索到的结点入栈。每当找到一个强连通元素，就按照该元素包含结点数目让栈中元素出栈。在搜索过程中，对于结点 $u$ 和与其相邻的结点 $v$（$v$ 不是 $u$ 的父节点）考虑 3 种情况：
> > 什么是「结点的变量」？
> 
> 也许是指 dfn；看来又出锅了~

😨不是吧 我要谢罪了

2022-07-29 10:35 UTC, F1shAndCat commented on docs/graph/scc.md
> +按照深度优先搜索算法搜索的次序对图中所有的结点进行搜索，维护每个结点的变量，且让搜索到的结点入栈。每当找到一个强连通元素，就按照该元素包含结点数目让栈中元素出栈。在搜索过程中，对于结点 $u$ 和与其相邻的结点 $v$（$v$ 不是 $u$ 的父节点）考虑 3 种情况：
> > dfn和low
> 
> 可能显式地写出来比较好

emm确实,刚刚写的时候描述有点重复了,但是不写就有点不清楚了

2022-07-29 16:09 UTC, Xeonacid commented
@24OI-bot lint please

2022-07-30 13:05 UTC, F1shAndCat commented
修改完毕 求approve😄

2022-07-30 13:07 UTC, Marcythm commented on docs/graph/scc.md
> +按照深度优先搜索算法搜索的次序对图中所有的结点进行搜索，维护每个结点的dfn与low变量，且让搜索到的结点入栈。每当找到一个强连通元素，就按照该元素包含结点数目让栈中元素出栈。在搜索过程中，对于结点 $u$ 和与其相邻的结点 $v$（$v$ 不是 $u$ 的父节点）考虑 3 种情况：
空...空格要记得
另外变量名应当使用 tt？
```suggestion
按照深度优先搜索算法搜索的次序对图中所有的结点进行搜索，维护每个结点的 `dfn` 与 `low` 变量，且让搜索到的结点入栈。每当找到一个强连通元素，就按照该元素包含结点数目让栈中元素出栈。在搜索过程中，对于结点 $u$ 和与其相邻的结点 $v$（$v$ 不是 $u$ 的父节点）考虑 3 种情况：
```
看看格式手册吧.png

2022-07-30 13:09 UTC, F1shAndCat commented on docs/graph/scc.md
> +按照深度优先搜索算法搜索的次序对图中所有的结点进行搜索，维护每个结点的dfn与low变量，且让搜索到的结点入栈。每当找到一个强连通元素，就按照该元素包含结点数目让栈中元素出栈。在搜索过程中，对于结点 $u$ 和与其相邻的结点 $v$（$v$ 不是 $u$ 的父节点）考虑 3 种情况：
啊😰,我又犯病了

2022-07-30 14:10 UTC, Marcythm submitted a review, later dismissed

2022-07-30 14:39 UTC, CoelacanthusHex submitted a review, later dismissed

2022-07-31 00:53 UTC, Xeonacid submitted a review, later dismissed

2022-07-31 09:37 UTC, Konano submitted a review, later dismissed

2022-07-31 15:15 UTC, F1shAndCat commented
@Menci 改好了 求approve😄

2022-08-05 03:24 UTC, aofall submitted a review, later dismissed

2022-08-07 15:13 UTC, Great-designer commented
6个approve……（尴尬）

2022-08-07 15:14 UTC, F1shAndCat commented
原来这个PR没有被merge吗👀

2022-08-07 15:15 UTC, F1shAndCat commented
@Menci 求approve

2022-08-08 01:34 UTC, Great-designer commented
因为作者还在……实在等不及的话，可以关掉再重开一个新的

2022-08-08 02:30 UTC, Great-designer commented
> 为什么要merge master，一下子把所有approve都dismiss了

根据时间顺序，这个是bot做的。merge master不会造成dismiss。
还有，只有request changes的发起者才能对这个pull request有效，其他的approve目前看来都没什么效果。如果再等不到“那位”管理员，这个pull request就可以关掉重开一个了。

2022-08-08 02:31 UTC, Great-designer approved these changes

2022-08-08 02:31 UTC, Menci approved these changes

2022-08-08 02:32 UTC, merged

2022-08-08 02:47 UTC, abc1763613206 commented
@Great-designer 这种是可以让更高权限的dismiss的