Add the method of loop "goto" in loop.md
OI-wiki/OI-wiki pull request #4228
Opened 2022-08-19 12:39 UTC by baoxuanming250

**审核的同学** 请着重关注以下四方面：

1. 注意有没有 typo
2. 不论您是否熟悉相关知识，都请以初学者的角度把这个 PR 的内容阅读一遍，跟着作者的思路走，然后谈谈您的感受
3. 如果您熟悉相关知识，请按照自己的理解评估这个 PR 的内容是否合适
4. 请**尽量**保持跟进直到它被 merge 或 close

2022-08-19 12:39 UTC, baoxuanming250 commented
这是自动回复邮件。Hi,你的邮件Bcy已经收到！我会尽量快速回复的！

2022-08-21 08:38 UTC, Enter-tainer requested changes

2022-08-21 08:38 UTC, Enter-tainer commented on docs/lang/loop.md
> +    但在OI比赛中，我们不建议用这种办法实现循环
首先，感谢你的贡献意愿。

但是既然不推荐，为什么要特意加一下这种方法呢

2022-08-23 01:54 UTC, Great-designer commented
确实

2022-08-23 01:54 UTC, closed without merging

2022-08-23 15:11 UTC, baoxuanming250 commented
这主要是我想给初学者普及一下实际上C++中还是有这么一种循环办法的，只是不常用，也希望初学者如果真的遇到这样的代码也能看得懂




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OI-wiki/OI-wiki"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月21日(星期天) 下午4:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OI-wiki/OI-wiki] Add the method of loop "goto" in loop.md (PR #4228)





 
@Enter-tainer requested changes on this pull request.
 
 
In docs/lang/loop.md:
 &gt; @@ -76,6 +76,21 @@ do {  } while (next_permutation(a + 1, a + n + 1));  ```   +???+ tip +    其实，还有一种循环的办法，就是使用 `goto`。 +     +    如： +    ```cpp +    loop: +      //循环语句 +      ... +      goto loop; +    ``` +     +    但在OI比赛中，我们不建议用这种办法实现循环  
首先，感谢你的贡献意愿。
 
但是既然不推荐，为什么要特意加一下这种方法呢
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2022-08-23 15:12 UTC, baoxuanming250 commented on docs/lang/loop.md
> +    但在OI比赛中，我们不建议用这种办法实现循环
这主要是我想给初学者普及一下实际上C++中还是有这么一种循环办法的，只是不常用，也希望初学者如果真的遇到这样的代码也能看得懂

2022-08-24 00:48 UTC, CCXXXI commented
@baoxuanming250