feat(rotating-calipers.md): 增加习题
OI-wiki/OI-wiki pull request #4264
Opened 2022-08-29 08:35 UTC by lychees

2022-08-29 10:41 UTC, Backl1ght submitted a review, later dismissed

2022-08-29 10:41 UTC, Backl1ght commented on docs/geometry/rotating-calipers.md
> +- [POJ 3608. Bridge Across Islands](https://vjudge.net/problem/POJ-3608)
请使用题目原本的来源

2022-08-29 10:41 UTC, Backl1ght commented on docs/geometry/rotating-calipers.md
> +- [2011 ACM-ICPC World Finals, Problem K. Trash Removal](https://vjudge.net/problem/Gym-101175K)
这个也是

2022-08-30 09:29 UTC, lychees commented on docs/geometry/rotating-calipers.md
> +- [2011 ACM-ICPC World Finals, Problem K. Trash Removal](https://vjudge.net/problem/Gym-101175K)
Done.

2022-08-30 09:29 UTC, lychees commented on docs/geometry/rotating-calipers.md
> +- [POJ 3608. Bridge Across Islands](https://vjudge.net/problem/POJ-3608)
Done.

2022-09-03 11:11 UTC, lychees commented
ping.

2022-09-03 11:13 UTC, Enter-tainer submitted a review, later dismissed

2022-09-04 01:10 UTC, ChungZH requested changes

2022-09-04 01:10 UTC, ChungZH commented on docs/geometry/convex-hull.md
列表的每一项之间是不需要空行的。

2022-09-13 07:37 UTC, Ir1d approved these changes

2022-09-13 09:00 UTC, Great-designer commented
@Backl1ght 麻烦您了！

2022-09-13 11:30 UTC, Enter-tainer approved these changes

2022-09-13 11:31 UTC, merged