feat:(expression.md)：完善表达式求值
OI-wiki/OI-wiki pull request #4281
Opened 2022-09-04 09:03 UTC by Great-designer

来自#4266 翻译e-maxx，仅将OI Wiki上的旧代码都换成了新代码。

2022-09-04 09:06 UTC, Great-designer commented
第一段代码被bot当成正文魔改了……（老人地铁手机）

2022-09-04 12:50 UTC, Great-designer commented
这回bot正常了

2022-09-05 07:50 UTC, littlefrogfromthenorth requested changes

2022-09-05 07:50 UTC, littlefrogfromthenorth commented on docs/misc/expression.md
>  1. [表达式求值（NOIP2013）](https://vijos.org/p/1849)
下面这部分建议这么改:
```suggestion
## 习题

1. [表达式求值（NOIP2013）](https://vijos.org/p/1849)

## 参考资料
**本页面主要译自博文 [Разбор выражений. Обратная польская нотация](https://e-maxx.ru/algo/expressions_parsing) 与其英文翻译版 [Expression parsing](https://cp-algorithms.com/string/expression_parsing.html))。其中俄文版版权协议为 Public Domain + Leave a Link；英文版版权协议为 CC-BY-SA 4.0。**
```

2022-09-05 07:59 UTC, littlefrogfromthenorth requested changes

2022-09-05 07:59 UTC, littlefrogfromthenorth commented on docs/misc/expression.md
> +以下是四个运算符 $+$、$-$、$\*$、$\/$ 的此方法的实现：
```suggestion
以下是四个运算符 $+$、$-$、$*$、$/$ 的此方法的实现：
```

2022-09-05 07:59 UTC, littlefrogfromthenorth commented on docs/misc/expression.md
> +这里是二进制运算符 $+$、$-$、$\*$、$\/$ 和一元运算符 $+$ 和 $-$ 的实现：
```suggestion
这里是二进制运算符 $+$、$-$、$*$、$/$ 和一元运算符 $+$ 和 $-$ 的实现：
```

2022-09-05 08:03 UTC, littlefrogfromthenorth requested changes

2022-09-05 08:03 UTC, littlefrogfromthenorth commented on docs/misc/expression.md
> +a+b\*c\*d+(e-f)\*(g\*h+i)
就 LaTeX 里 * 号是不需要加 `\` 的
```suggestion
a+b*c*d+(e-f)*(g*h+i)
```

2022-09-05 08:03 UTC, littlefrogfromthenorth commented on docs/misc/expression.md
> +abc\*d\*+ef-gh\*i+\*+
同上.
```suggestion
abc*d*+ef-gh*i+*+
```

2022-09-05 08:03 UTC, littlefrogfromthenorth commented on docs/misc/expression.md
> +a+b\*c
同上.
```suggestion
a+b*c
```

2022-09-06 00:07 UTC, littlefrogfromthenorth requested changes

2022-09-06 00:07 UTC, littlefrogfromthenorth commented on docs/misc/expression.md
> +
![image](https://user-images.githubusercontent.com/49180735/188522397-8597b6d8-5bbd-42e3-9797-ec64c1d7d307.png)
![image](https://user-images.githubusercontent.com/49180735/188522357-83f84659-027e-460e-a791-354da37abb35.png)

话说这里怎么这样了........

2022-09-06 01:09 UTC, Great-designer commented on docs/misc/expression.md
> +
在上文直接点了commit suggestion

2022-09-06 01:11 UTC, littlefrogfromthenorth submitted a review, later dismissed
虽然 Approve 了也没用

2022-09-14 04:39 UTC, greyqz submitted a review, later dismissed
看起来不错。为啥不merge？

2022-09-22 05:32 UTC, Enter-tainer commented on docs/misc/expression.md
> +表达式求值要解决的问题一般是输入一个字符串表示的表达式，要求输出它的值。当然也有变种比如表达式中是否包含括号，指数运算，含多少变量，判断多个表达式是否等价，等等。其中判断表达式等价的部分使用了拉格朗日插值法等数学工具，在此暂不进行展开。
> 其中判断表达式等价的部分使用了拉格朗日插值法等数学工具，在此暂不进行展开。

??这啥

2022-09-22 05:33 UTC, Enter-tainer submitted a review, later dismissed
other part LGTM

2022-09-22 10:39 UTC, ouuan commented on docs/misc/expression.md
> +表达式求值要解决的问题一般是输入一个字符串表示的表达式，要求输出它的值。当然也有变种比如表达式中是否包含括号，指数运算，含多少变量，判断多个表达式是否等价，等等。其中判断表达式等价的部分使用了拉格朗日插值法等数学工具，在此暂不进行展开。
这里是列举了一些本文没讲到的相关问题，建议挪到文章结尾，删掉“在此暂不进行展开”这个误导性的话（因为其它几个问题也没有展开，这样说好像只有判断等价没有展开一样）。

我感觉也可以直接删了，因为这篇文章讲的是表达式解析，也没必要提及判断表达式等价。而另外几个相关问题是 trival 的。

2022-09-22 16:20 UTC, Ir1d commented on docs/misc/expression.md
> +表达式求值要解决的问题一般是输入一个字符串表示的表达式，要求输出它的值。当然也有变种比如表达式中是否包含括号，指数运算，含多少变量，判断多个表达式是否等价，等等。其中判断表达式等价的部分使用了拉格朗日插值法等数学工具，在此暂不进行展开。
let me remove these 🙏

2022-09-22 16:21 UTC, Ir1d approved these changes

2022-09-22 16:22 UTC, Enter-tainer approved these changes
cool

2022-09-22 16:58 UTC, merged