feat(dsu): 添加删除操作 & 重构其他部分
OI-wiki/OI-wiki pull request #4300
Opened 2022-09-12 14:02 UTC by CCXXXI

- [x] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

2022-09-14 06:38 UTC, Tiphereth-A commented on docs/ds/dsu.md
> +    }
建议使用列表初始化并添加 `explicit` 关键字
```suggestion
    explicit dsu(size_t size): pa(size) {
        iota(pa.begin(), pa.end(), 0);
    }
```

2022-09-14 06:38 UTC, Tiphereth-A commented on docs/ds/dsu.md
> +    }
同上
```suggestion
    explicit dsu(size_t _size): pa(_size), size(_size, 1) {
        iota(pa.begin(), pa.end(), 0);
    }
```

2022-09-14 06:38 UTC, Tiphereth-A commented on docs/ds/dsu.md
> +    }
同上
```suggestion
    explicit dsu(size_t _size): pa(_size * 2), size(_size * 2, 1) {
        iota(pa.begin(), pa.begin() + _size, _size);
        iota(pa.begin() + _size, pa.end(), _size);
    }
```

2022-09-14 06:46 UTC, Tiphereth-A requested changes
一点建议

2022-09-16 08:24 UTC, Tiphereth-A approved these changes

2022-09-21 05:32 UTC, Enter-tainer approved these changes
LGTM

2022-09-21 06:42 UTC, Great-designer approved these changes

2022-09-21 06:43 UTC, merged