Update state.md
OI-wiki/OI-wiki pull request #4334
Opened 2022-09-23 01:25 UTC by hqztrue

Fix the symbols for Boolean AND and OR.
Fix the time complexity.

p.s. the "preview" seems problematic?

- [ ] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

2022-09-23 03:52 UTC, Great-designer submitted a review, later dismissed

2022-09-23 10:15 UTC, Tiphereth-A requested changes

2022-09-23 10:15 UTC, Tiphereth-A commented on docs/dp/opt/state.md
> +f_{s, i} = \bigvee_{j\in s, j\neq i}f_{s - \\{i\\}, j}\wedge g_{j, i} \left(i\in s\right)
差集请用 `\setminus`

```suggestion
f_{s, i} = \bigvee_{j\in s, j\neq i}f_{s \setminus \{i\}, j}\wedge g_{j, i} \left(i\in s\right)
```

2022-09-23 10:15 UTC, Tiphereth-A commented on docs/dp/opt/state.md
> +时间复杂度 $O(n^2/w\times 2^n)$, 可以通过这道题。
请说明 $w$ 的含义

2022-09-23 10:49 UTC, Tiphereth-A commented on docs/dp/opt/state.md
> +时间复杂度 $O(n^2/w\times 2^n)$, 可以通过这道题。
```suggestion
时间复杂度 $O(n^2/w\times 2^n)$, 可以通过这道题，其中 $w$ 为 `int` 的位数。
```

2022-09-23 10:51 UTC, Tiphereth-A approved these changes

2022-09-24 14:47 UTC, greyqz approved these changes

2022-09-24 14:47 UTC, merged