feat(lang/pb-ds/hash): 添加pbds中hash表的有关叙述
OI-wiki/OI-wiki pull request #4337
Opened 2022-09-25 00:52 UTC by qingdkj

- [x] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

2022-09-26 01:26 UTC, Great-designer submitted a review, later dismissed

2022-09-27 02:52 UTC, Tiphereth-A requested changes

2022-09-27 02:52 UTC, Tiphereth-A commented on docs/lang/pb-ds/hash.md
> +在阅读之前，请确保熟悉 [`Hash表`](https://oi-wiki.org/ds/hash/) 的相关内容。
请使用相对链接
```suggestion
在阅读之前，请确保熟悉 [`Hash表`](../../ds/has.md) 的相关内容。
```

2022-09-27 02:52 UTC, Tiphereth-A commented on docs/lang/pb-ds/hash.md
> +
模板形参介绍太少了, 请参照 [官方文档](https://gcc.gnu.org/onlinedocs/libstdc++/ext/pb_ds/hash_based_containers.html) 补充

2022-09-30 12:46 UTC, closed without merging