feat(ds/leafy-tree): 增加leafy tree内容
OI-wiki/OI-wiki pull request #4353
Opened 2022-09-27 13:15 UTC by Persdre

reviewers 加油！
- [x] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

2022-09-27 17:28 UTC, Tiphereth-A requested changes

2022-09-27 17:28 UTC, Tiphereth-A commented on docs/ds/leafy-tree.md
> +```
看起来所有的代码都需要重新格式化一遍 🤔

2022-09-27 17:28 UTC, Tiphereth-A commented on docs/ds/leafy-tree.md
> +```
建议使用 Details 语法并将代码分离出来, 具体请参照格式手册

example: https://github.com/RIvance/OI-wiki/blob/650a5948d4f9f8a18b99bc0ccf1e7e041bce0906/docs/ds/sbt.md?plain=1 的 362 行至最后一行

2022-09-28 00:02 UTC, Great-designer commented on docs/ds/leafy-tree.md
> +```
我建议联系管理bot的同学修理bot

2022-09-28 02:09 UTC, Persdre commented on docs/ds/leafy-tree.md
> +```
好我先来看下

2022-09-28 02:09 UTC, Persdre commented on docs/ds/leafy-tree.md
> +```
好的我看下

2022-09-28 02:11 UTC, Tiphereth-A commented
@24OI-bot lint please

2022-09-29 07:37 UTC, Enter-tainer commented
cc @Ir1d bot 最近似乎不工作了

2022-09-29 15:05 UTC, Ir1d commented
神奇啊，不知道 bot 点啥赞，我来看看

2022-09-30 03:15 UTC, Ir1d commented
@24OI-bot lint please

2022-09-30 06:26 UTC, Ir1d commented
@24OI-bot lint please

2022-09-30 06:28 UTC, Ir1d commented on docs/ds/code/size-balanced-tree/SizeBalancedTreeMap.hpp
> +       clang-format on
@ksyx k 神帮看一下这是咋回事

2022-09-30 14:07 UTC, Marcythm reviewed
文字质量不错了（但是受灾现场一样的 commit history 是咋回事

2022-09-30 14:47 UTC, Ir1d commented
@24OI-bot lint please

2022-09-30 14:54 UTC, negiizhao commented on docs/ds/leafy-tree.md
> +这种结构中，每个叶子存储值，每个非叶节点值负责维护树的形态而不维护树的信息，但通常会维护孩子信息，从而加速查询。线段树的结构属于一种 Leafy Tree。所以 Leafy Tree 也被称为平衡线段树。
我建议把结构与其维护方式区分开，Leafy 只能说明信息存储结构而不能说明使用 WBT 的平衡策略。尽管如果在 OI 中形成了某种用语习惯的话我不会坚持这个要求。

2022-10-01 01:02 UTC, Great-designer commented on docs/ds/leafy-tree.md
> +```
bot已经格式化过了

2022-10-01 03:41 UTC, Tiphereth-A commented on docs/ds/leafy-tree.md
> +```
> bot已经格式化过了

这缩进不对吧...

2022-10-01 03:41 UTC, Tiphereth-A commented
@24OI-bot lint please

2022-10-01 03:43 UTC, Tiphereth-A commented
看起来 bot 不会格式化 markdown 里的代码 🤔

2022-10-01 04:41 UTC, Ir1d commented on docs/math/linear-algebra/basis.md
> +5. 对找到的一组极大线性无关组（或基），求其张成的线性空间中的最大元/最小元。
很难想象之前 bot 经历了什么

2022-10-01 05:11 UTC, Enter-tainer commented
bot 好像把一些行间公式改成了行内公式？

![Screenshot_2022-10-01-13-11-12-107_com.github.android.jpg](https://user-images.githubusercontent.com/25521218/193393669-b07d2722-96c7-4b01-823d-1476e9b11131.jpg)

2022-10-01 05:15 UTC, Ir1d commented
哦哦 行间公式得 $$ 换行的，这样写好像确实会被改

2022-10-01 05:27 UTC, Tiphereth-A commented
格式应该没问题了罢 😇

2022-10-01 05:36 UTC, Great-designer approved these changes

2022-10-01 07:38 UTC, Tiphereth-A approved these changes

2022-10-01 08:09 UTC, merged

2022-10-01 10:23 UTC, Enter-tainer commented
似乎有一些有用的讨论被淹没在了和bot的大战之中。。总之之后需要修改的话再另开PR吧

2022-10-01 16:56 UTC, Tiphereth-A commented
> 似乎有一些有用的讨论被淹没在了和bot的大战之中。。总之之后需要修改的话再另开PR吧

我先开个issue吧