feat(concentration-inequality.md): 添加概率不等式相关内容
OI-wiki/OI-wiki pull request #4354
Opened 2022-09-28 01:53 UTC by MegaOwIer

- [x] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

主要修改：
1. 合并概率论目录下“快速上手”和“基本概念”页面。(#4153)
2. 修正概率论相关页面的若干错别字。
3. 更新部分页面到概率论相关主题的内链。
4. 添加概率不等式相关内容。

另外写的时候注意到现有 [随机化技巧](https://oi-wiki.org/misc/rand-technique/#%E6%A6%82%E7%8E%87%E4%B8%8A%E7%95%8C%E7%9A%84%E5%88%86%E6%9E%90) 页面中有部分篇幅也在讨论这个话题，要不要考虑合并到一起？

2022-09-28 03:48 UTC, Great-designer approved these changes

2022-09-28 06:17 UTC, Great-designer commented
> 另外写的时候注意到现有 [随机化技巧](https://oi-wiki.org/misc/rand-technique/#%E6%A6%82%E7%8E%87%E4%B8%8A%E7%95%8C%E7%9A%84%E5%88%86%E6%9E%90) 页面中有部分篇幅也在讨论这个话题，要不要考虑合并到一起？

可以，将原位置的内容删掉并挂上引用内链，然后在本位置补上就行。

2022-09-29 07:36 UTC, Enter-tainer approved these changes
cool

2022-09-29 07:39 UTC, Enter-tainer requested changes
数学公式渲染好像有问题啊，see https://deploy-preview-4354--oi-wiki.netlify.app/math/probability/concentration-inequality/

---

行内公式请使用单美元（？

2022-09-29 07:40 UTC, Enter-tainer commented
cc @Great-designer 也请之后review的时候注意下查看预览

2022-09-29 07:48 UTC, MegaOwIer commented
az....那些按理说都不是行内公式啊

2022-09-29 07:49 UTC, Enter-tainer commented
@MegaOwIer 试试额外空一行（？）markdown里面，两个回车才是另起一段

2022-09-29 08:35 UTC, Great-designer commented
> cc @Great-designer 也请之后review的时候注意下查看预览

喵

2022-09-29 08:35 UTC, Great-designer commented
全部空两行应该就没问题了

2022-09-29 08:38 UTC, Great-designer commented
手动排了一下。另外修bot的不知道有没有修好……应该是没有罢

2022-09-29 08:40 UTC, Enter-tainer commented
@Great-designer 之后遇到bot问题请 @Ir1d ，不然他可能不知道有这个事情。另外，目前美国时间应该还是晚上

2022-09-29 08:42 UTC, Enter-tainer commented
> 全部空一行应该就没问题了

似乎还有别的文件没修完

2022-09-29 09:32 UTC, Great-designer commented
> 似乎还有别的文件没修完

似乎已经修完了

2022-09-29 09:33 UTC, Great-designer commented
> @Great-designer 之后遇到bot问题请 @Ir1d ，不然他可能不知道有这个事情。另外，目前美国时间应该还是晚上

@Ir1d

另外不必太在乎美国时间，美国登录GitHub比我这里通畅得多

2022-09-29 09:36 UTC, Enter-tainer commented
> 另外不必太在乎美国时间，美国登录GitHub比我这里通畅得多

我不知道你在说什么。。我只是想说Ir1d人在美国 🌚

2022-09-29 09:37 UTC, Enter-tainer commented on docs/math/probability/basic-conception.md
> +其中 $\#(\cdot)$ 表示对随机事件（一个集合）大小的度量。
```suggestion
那么对于每个事件 $A$，定义它的概率为

$$
P(A)=\frac{\#(A)}{\#(\Omega)}
$$

其中 $\#(\cdot)$ 表示对随机事件（一个集合）大小的度量。
```

2022-09-29 09:42 UTC, Enter-tainer submitted a review, later dismissed
anyway, LGTM now

2022-09-29 09:51 UTC, Great-designer submitted a review, later dismissed

2022-09-29 10:00 UTC, MegaOwIer commented
> > 另外写的时候注意到现有 [随机化技巧](https://oi-wiki.org/misc/rand-technique/#%E6%A6%82%E7%8E%87%E4%B8%8A%E7%95%8C%E7%9A%84%E5%88%86%E6%9E%90) 页面中有部分篇幅也在讨论这个话题，要不要考虑合并到一起？
> 
> 可以，将原位置的内容删掉并挂上引用内链，然后在本位置补上就行。

最新的 push 修了格式然后搞了下这个事情，没注意您二位已经修过格式了自己搞完之后发现死活推不上就 --force 了（）

现在应该算是完工了（吧）

2022-09-29 10:11 UTC, Enter-tainer approved these changes
辛苦了

2022-09-29 10:25 UTC, Tiphereth-A approved these changes

2022-09-29 10:39 UTC, merged