Create Vandermonde's Convolution.md
OI-wiki/OI-wiki pull request #4360
Opened 2022-09-28 23:53 UTC by tidongCrazy

- [x] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

2022-09-29 03:17 UTC, Tiphereth-A requested changes
1. 请参照 https://oi-wiki.org/intro/htc/#%E5%AF%B9%E4%BA%8E%E7%9B%AE%E5%BD%95%E5%92%8C%E5%BC%95%E7%94%A8%E7%9A%84%E5%8F%98%E6%9B%B4 在 mkdocs.yml 作对应改动
2. 请参照 https://oi-wiki.org/intro/format/#%E6%96%87%E6%A1%A3%E5%BC%95%E7%94%A8%E4%B8%8E%E5%AD%98%E5%82%A8%E7%9A%84%E6%A0%BC%E5%BC%8F 修改文件名

2022-09-29 05:03 UTC, Great-designer commented
没写文件目录。另外这类组合恒等式可以考虑做个集合啥的。

2022-09-29 06:58 UTC, Tiphereth-A commented on docs/math/combinatorics/vandermonde-convolution.md
> +1.[Vandermonde's Convolution Formula](https://www.cut-the-knot.org/arithmetic/algebra/VandermondeConvolution.shtml#)
```suggestion
1. [Vandermonde's Convolution Formula](https://www.cut-the-knot.org/arithmetic/algebra/VandermondeConvolution.shtml#)
```

2022-09-29 07:29 UTC, Tiphereth-A commented on docs/math/combinatorics/vandermonde-convolution.md
> +$$=\sum_{k=0}^{n+m}\sum_{r=0}^k{n\choose r}{m\choose k-r}x^k$$
请使用 `\begin{aligned} ... \end{aligned}` 表示多行对齐的公式

2022-09-29 07:29 UTC, Tiphereth-A commented on docs/math/combinatorics/vandermonde-convolution.md
> +## 范德蒙德卷积
```suggestion
## 引入
```

2022-09-29 07:29 UTC, Tiphereth-A commented on docs/math/combinatorics/vandermonde-convolution.md
> +
```suggestion

### 证明

```

2022-09-29 07:29 UTC, Tiphereth-A commented on docs/math/combinatorics/vandermonde-convolution.md
> +
```suggestion

### 证明

```

2022-09-29 07:29 UTC, Tiphereth-A commented on docs/math/combinatorics/vandermonde-convolution.md
> +### 范德蒙德卷积推论
```suggestion
### 推论
```

2022-09-29 07:41 UTC, Tiphereth-A commented on docs/math/combinatorics/vandermonde-convolution.md
> +### 范德蒙德卷积公式
```suggestion
## 范德蒙德卷积公式
```

2022-09-29 08:06 UTC, Tiphereth-A submitted a review, later dismissed
辛苦了

2022-09-29 08:09 UTC, Tiphereth-A commented on docs/math/combinatorics/vandermonde-convolution.md
> +$$\sum_{i=0}^k{n\choose i}{m\choose k-i}={n+m\choose k}$$
`${m\choose n}$` 是不推荐的写法, 请使用 `$\binom{m}{n}$`

2022-09-29 09:41 UTC, Tiphereth-A approved these changes

2022-10-01 06:55 UTC, Backl1ght approved these changes
lgtm

2022-10-01 08:28 UTC, merged