feat(compilers) add misc/compilers
OI-wiki/OI-wiki pull request #4472
Opened 2022-11-26 17:17 UTC by inclyc

- [x] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

Fixes: https://github.com/OI-wiki/OI-wiki/issues/4471

2022-11-27 01:30 UTC, Enter-tainer commented on docs/misc/compilers.md
> +### 常见的编译器优化
```suggestion
## 常见的编译器优化
```

感觉应该是二级标题

2022-11-27 15:03 UTC, ImpleLee commented on docs/misc/compilers.md
> +```
有点担心选手把这里误读作“开了优化的比赛里未初始化的栈变量一定为0”……
感觉cppreference里的另一个例子可能比较有冲击性？
```cpp
bool p;
if(p)
    std::puts("p is true");
if(!p)
    std::puts("p is false");
```
这个例子甚至可能输出
```
p is true
p is false
```
即未初始化的变量不仅值是未定义的，甚至也不保证多次读取得到同一个值。

2022-11-27 15:05 UTC, ImpleLee commented on docs/misc/compilers.md
> +```
有点担心选手把这里误读作“开了优化的比赛里未初始化的栈变量一定为0”……
感觉cppreference里的另一个例子可能比较有冲击性？
```cpp
bool p;
if(p)
    std::puts("p is true");
if(!p)
    std::puts("p is false");
```
这个例子甚至可能输出
```
p is true
p is false
```
即未初始化的变量不仅值是未定义的，甚至也不保证多次读取得到同一个值。

2022-11-27 15:14 UTC, inclyc commented on docs/misc/compilers.md
> +```
但实际上编译优化会假定未初始化变量为 0 值？我其实是想说明这一点

2022-11-27 15:54 UTC, Xeonacid commented on docs/misc/compilers.md
> +## Undefined behavior
https://oi-wiki.org/contest/common-mistakes/ 已经有了类似的内容，这里应该不需要了？

2022-11-27 15:54 UTC, Xeonacid commented on mkdocs.yml
> +    - 编译优化和语言提示: misc/compilers.md
放到 /tools 下，跟 /tools/compiler 组成一个目录层级应该更合适
/misc 放的都是算法内容

2022-11-27 15:55 UTC, inclyc commented on docs/misc/compilers.md
> +## Undefined behavior
UB 整节都删除吗

2022-11-27 15:55 UTC, inclyc commented on mkdocs.yml
> +    - 编译优化和语言提示: misc/compilers.md
行

2022-11-27 16:12 UTC, Xeonacid commented on docs/misc/compilers.md
> +## Undefined behavior
> UB 整节都删除吗

也可以合并到常见错误页面去

2022-11-27 16:14 UTC, inclyc commented on docs/misc/compilers.md
> +## Undefined behavior
没问题

2022-11-27 16:15 UTC, inclyc commented
Thanks to the OI-wiki folks for the quick review!

2022-11-28 06:29 UTC, inclyc commented
@Xeonacid  tools 下面看起来有一个编译器安装的话题了，放在 tools 下面好像也有点 OT ?

2022-11-28 06:34 UTC, inclyc commented
![Screenshot_20221128_143352](https://user-images.githubusercontent.com/36667224/204209538-9eec0b1d-f8c0-4c6b-82cf-4043d65e0794.png)

```yml
    - 编译器: 
      - 安装: tools/compilers/installation.md
      - 编译优化和语言提示: tools/compilers/optimization.md
```

打算放成这样

2022-11-28 15:36 UTC, alphagocc commented on docs/tools/compilers/optimization.md
> +### inline - 内联
和上面自动内联合并一下？

2022-11-28 15:36 UTC, alphagocc commented on docs/tools/compilers/optimization.md
> +int add(int x) {
gcc 有一个 `__always_inline__` 的 attribute

2022-11-28 15:36 UTC, alphagocc commented on docs/tools/compilers/optimization.md
> +如果比赛没有采用 C++20 以上标准，则可以利用 `__builtin_expect`
gcc only

2022-11-28 15:37 UTC, alphagocc commented on docs/tools/compilers/optimization.md
> +### inline - 内联
哦，这个是语言误用，看错了（

2022-11-28 15:47 UTC, inclyc commented on docs/tools/compilers/optimization.md
> +如果比赛没有采用 C++20 以上标准，则可以利用 `__builtin_expect`
此扩展 clang 也有。有算法竞赛使用 msvc 吗？

2022-11-28 15:48 UTC, inclyc commented on docs/tools/compilers/optimization.md
> +如果比赛没有采用 C++20 以上标准，则可以利用 `__builtin_expect`
给出的参数或行为如果编译器相关我事后说明吧

2022-11-28 18:52 UTC, inclyc commented on docs/tools/compilers/optimization.md
> +int add(int x) {
不打算写了，inline 与否让编译器判断其实更好

2022-11-29 04:09 UTC, ouuan commented on mkdocs.yml
> +    - 编译优化和语言提示: misc/compilers.md
我觉得放在 tools 下不合适，tools 应该是工具如何使用

2022-11-29 04:13 UTC, ouuan commented on mkdocs.yml
> +    - 编译优化和语言提示: misc/compilers.md
除了杂项，也可以考虑放 C++ 进阶

2022-11-29 04:24 UTC, inclyc commented
所以这些内容放哪

2022-11-29 05:12 UTC, Tiphereth-A commented on docs/tools/compilers/optimization.md
> +如果比赛没有采用 C++20 以上标准，则可以利用 `__builtin_expect`
> 此扩展 clang 也有。有算法竞赛使用 msvc 吗？

Codeforces 有 MSVC 的选项

2022-11-29 05:48 UTC, inclyc commented on docs/tools/compilers/optimization.md
> +如果比赛没有采用 C++20 以上标准，则可以利用 `__builtin_expect`
好的喵

2022-11-29 07:00 UTC, CCXXXI commented on docs/tools/compilers/optimization.md
> +常见的编译优化，甚至很多 OI 选手可以自己执行这种优化。
这里的意思是「选手应该自己执行这种优化」，还是「（因为编译器会自动优化所以）选手不需要自己执行这种优化」？

2022-11-29 07:19 UTC, CCXXXI requested changes

2022-11-29 07:19 UTC, CCXXXI commented on docs/tools/compilers/optimization.md
> +接跑寄存器分配来的聪明。此关键字已经在 C++17 中被标记为无任何语义。
根据 [Storage class specifiers - cppreference.com](https://en.cppreference.com/w/cpp/language/storage_duration#:~:text=in%20C%2B%2B%2C%20a%20variable%20declared%20register%20is%20semantically%20indistinguishable%20from%20a%20variable%20declared%20without%20any%20storage%20class%20specifiers.)

> in C++, a variable declared register is semantically indistinguishable from a variable declared without any storage class specifiers.

此关键字之前就没有特殊语义，C++17 的变动是彻底移除了这个关键字

2022-11-29 09:01 UTC, inclyc commented on docs/tools/compilers/optimization.md
> +接跑寄存器分配来的聪明。此关键字已经在 C++17 中被标记为无任何语义。
关键词一般不用“移除”吧，就是被标记为过期，并作为保留用。在此前是有语义的https://en.cppreference.com/w/cpp/keyword/register

2022-11-29 09:02 UTC, inclyc commented on docs/tools/compilers/optimization.md
> +常见的编译优化，甚至很多 OI 选手可以自己执行这种优化。
意思就是有人喜欢用移位代替乘法，算是手动强度削减

2022-11-29 09:03 UTC, inclyc commented on docs/tools/compilers/optimization.md
> +接跑寄存器分配来的聪明。此关键字已经在 C++17 中被标记为无任何语义。
automatic storage duration. Also hints to the compiler to place the object in the processor's register.

2022-11-29 09:05 UTC, CCXXXI commented on docs/tools/compilers/optimization.md
> +接跑寄存器分配来的聪明。此关键字已经在 C++17 中被标记为无任何语义。
> 关键词一般不用“移除”

[Remove Deprecated Use of the register Keyword (open-std.org)](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0001r1.html)

2022-11-29 09:13 UTC, CCXXXI commented on docs/tools/compilers/optimization.md
> +常见的编译优化，甚至很多 OI 选手可以自己执行这种优化。
那要不要说明一下这种手动强度削减是多余的

2022-11-29 09:30 UTC, CCXXXI commented on docs/tools/compilers/optimization.md
> +接跑寄存器分配来的聪明。此关键字已经在 C++17 中被标记为无任何语义。
```suggestion
接跑寄存器分配来的聪明。此关键字于 C++11 被弃用，于 C++17 被删除[^p0001r1]。
```

2022-11-29 09:31 UTC, CCXXXI commented on docs/tools/compilers/optimization.md
> +在这里观察各个编译器的行为和汇编代码: https://godbolt.org
```suggestion
在这里观察各个编译器的行为和汇编代码: https://godbolt.org

## 参考资料与注释

[^p0001r1]: [Remove Deprecated Use of the register Keyword (open-std.org)](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0001r1.html)
```

2022-11-29 09:53 UTC, inclyc commented on docs/tools/compilers/optimization.md
> +常见的编译优化，甚至很多 OI 选手可以自己执行这种优化。
可以，之后我写，举点例子什么的

2022-11-29 09:55 UTC, inclyc commented on docs/tools/compilers/optimization.md
> +接跑寄存器分配来的聪明。此关键字已经在 C++17 中被标记为无任何语义。
LG

2022-11-29 09:57 UTC, inclyc commented on docs/tools/compilers/optimization.md
> +寄存器，比通用寄存器更宽，例如一次放 4 个无整数然后计算。OI 选手不需要了解自动向量化的细节，通常而言，clang 编译器会做比 GCC 更激进的自动向量化:
忘记折行了（

2022-11-29 10:00 UTC, inclyc commented
这个 bot lint 把块放置那里的注释搞坏了，难绷

2022-11-29 10:31 UTC, Xeonacid commented on docs/tools/compilers/optimization.md
> +寄存器，比通用寄存器更宽，例如一次放 4 个无整数然后计算。OI 选手不需要了解自动向量化的细节，通常而言，clang 编译器会做比 GCC 更激进的自动向量化:
> 忘记折行了（

为什么要折行？这是wiki而非邮件列表（

2022-11-29 10:32 UTC, Xeonacid commented
> 这个 bot lint 把块放置那里的注释搞坏了，难绷

可以在代码块开头加一个 `// clang-format off`

2022-11-29 18:20 UTC, inclyc commented on docs/tools/compilers/optimization.md
> +寄存器，比通用寄存器更宽，例如一次放 4 个无整数然后计算。OI 选手不需要了解自动向量化的细节，通常而言，clang 编译器会做比 GCC 更激进的自动向量化:
好的，这就把tw删掉

2022-11-30 14:46 UTC, inclyc commented
这几天返乡，先咕了

2022-11-30 17:36 UTC, inclyc commented
@inclyc 目前算法竞赛开 O2 的情况是啥？我刚知道 noip 也开 O2 了（

2022-11-30 18:55 UTC, inclyc commented on docs/lang/optimizations.md
> +<!-- TODO: 开 O2 的比赛 -->
此处不会了，已经退役很久

2022-11-30 18:57 UTC, inclyc commented
草，只能 request 一个吗（溜了

2022-12-01 02:26 UTC, inclyc commented
@Tiphereth-A 话说为什么是 mipsasm，而不是 x86/amd64 ?

2022-12-01 02:42 UTC, Tiphereth-A commented on docs/lang/optimizations.md
> +<!-- TODO: 开 O2 的比赛 -->
现在似乎不开 O2 的比赛是少数

2022-12-01 02:42 UTC, Tiphereth-A commented on docs/lang/optimizations.md
> +```
```suggestion
???+note 布局1
    ```c++
    // clang-format off
    hotblock1:
        Stmts; // <-- 热！
        if (/* 边界条件不成立 */ true)
            goto hotblock2; // 经常发生！ ------+
    coldblock:                           /*   |   */
        Stmt; // <- 冷                        |
        Stmt; // <- 冷                        |
        Stmt; // <- 冷                        |  跨越了大量指令，代价高昂！
        Stmt; // <- 冷                        |
        Stmt; // <- 冷                        |
        Stmt; // <- 冷                        |
        Stmt; // <- 冷                        |
    hotblock2:                          /*    |   */
        Stmts; // <- 热！           <----------+
    ```
```
```

2022-12-01 02:42 UTC, Tiphereth-A commented on docs/lang/optimizations.md
> +```
```suggestion
???+note 布局2
    ```c++
    // clang-format off
    hotblock1:
        Stmts; // <-- 热！
        if (/* 边界条件 */ false)
            goto coldblock; // 很少发生
    hotblock2:                         /*   |  低代价！  */
        Stmts; // <- 热！  <-----------------+
    coldblock:
        Stmt; // <- 冷
        Stmt; // <- 冷
        Stmt; // <- 冷
        Stmt; // <- 冷
        Stmt; // <- 冷
    ```
```

2022-12-01 02:42 UTC, Tiphereth-A commented on docs/lang/optimizations.md
> +```
```suggestion
???+note 不好的写法
    ```c++
    // clang-format off
    hotblock1:
      Stmts; // <-- 热！
      if (/* 边界条件不成立 */ true)
        goto hotblock2; // 经常发生！ ------+
    coldblock:                            /*   |   */
      Stmt; // <- 冷                        |
      Stmt; // <- 冷                        |
      Stmt; // <- 冷                        |  跨越了大量指令，代价高昂！
      Stmt; // <- 冷                        |
      Stmt; // <- 冷                        |
      Stmt; // <- 冷                        |
      Stmt; // <- 冷                        |
    hotblock2:                           /*    |   */
      Stmts; // <- 热！           <----------+
    ```
```

2022-12-01 02:42 UTC, Tiphereth-A commented on docs/lang/optimizations.md
> +```
```suggestion
???+note 好的写法
    ```c++
    // clang-format off
    hotblock1:
      Stmts;  // <-- 热！
    if (/* 边界条件不成立 */ true)
      codeBlock();  // 将冷代码分离出，使得热路径对 cache 更友好
    hotblock2:
      Stmts;  // <- 热！
    void coldBlock() {
      Stmt;  // <- 冷
      Stmt;  // <- 冷
      Stmt;  // <- 冷
      Stmt;  // <- 冷
      Stmt;  // <- 冷
      Stmt;  // <- 冷
      Stmt;  // <- 冷
    }
    ```
```

2022-12-01 02:42 UTC, Tiphereth-A commented on docs/lang/optimizations.md
> +```
```suggestion
???+note [GCD](https://godbolt.org/z/8Wb6WEnzv)
    ```cpp
    int gcd(int a, int b) { return b ? gcd(b, a % b) : a; }
    ```
```

2022-12-01 02:42 UTC, Tiphereth-A commented on docs/lang/optimizations.md
> +```
```suggestion
???+note [斐波那契数列](https://godbolt.org/z/4enof6Wcb)
    ```cpp
    int fib(int n) {
      if (n < 2) return 1;
      return fib(n - 1) + fib(n - 2);
    }
    ```
```

2022-12-01 02:42 UTC, Tiphereth-A commented on docs/lang/optimizations.md
> +```
```suggestion
???+note [阶乘](https://godbolt.org/z/n64e75xrf)
    ```cpp
    unsigned fac(unsigned n) {
      if (n < 2) return 1;
      return n * fac(n - 1);
    }
    ```
```

2022-12-01 02:45 UTC, Tiphereth-A commented
> @Tiphereth-A 话说为什么是 mipsasm，而不是 x86/amd64 ?

因为我看 HighlightJS 给的 demo 里只有 MIPS Assembly 的行注释是 `#` 开头的

2022-12-01 04:03 UTC, inclyc commented on docs/lang/optimizations.md
> +```
```diff
- 好的写法
+ 好的代码布局
```

这样会不会好点？因为这各部分其实是 CPU 指令，是编译器生成的，而不是自己写的

2022-12-01 04:09 UTC, inclyc commented on docs/lang/optimizations.md
> +<!-- TODO: 开 O2 的比赛 -->
需要一个表格之类的东西列一下各大赛事/OJ是否开优化

2022-12-01 04:12 UTC, inclyc commented on docs/lang/optimizations.md
> +```
我这两个例子是由最开始的一份C++代码翻译而来，这里本来应该贴汇编，但是怕读者看不懂，所以写成了用 C++ label 的 “伪汇编” 形式

2022-12-01 06:10 UTC, Tiphereth-A commented on docs/lang/optimizations.md
> +```
> ```diff
> - 好的写法
> + 好的代码布局
> ```
> 
> 这样会不会好点？因为这各部分其实是 CPU 指令，是编译器生成的，而不是自己写的

seems great

2022-12-01 07:37 UTC, CoelacanthusHex commented on docs/lang/optimizations.md
> +OI 届的常用编程语言是 C++。既然使用了这门语言，就注定要和编译器、语言标准打交道了。众所周知，C++ 非常混乱邪恶，本文旨在给出实用的编译器相关知识，足够竞赛使用。
```suggestion
OI 界的常用编程语言是 C++。既然使用了这门语言，就注定要和编译器、语言标准打交道了。众所周知，C++ 非常混乱邪恶，本文旨在给出实用的编译器相关知识，足够竞赛使用。
```
届无此词义

2022-12-01 08:29 UTC, inclyc commented on docs/lang/optimizations.md
> +OI 届的常用编程语言是 C++。既然使用了这门语言，就注定要和编译器、语言标准打交道了。众所周知，C++ 非常混乱邪恶，本文旨在给出实用的编译器相关知识，足够竞赛使用。
nice catch!

2022-12-02 05:19 UTC, CCXXXI requested changes
typo

2022-12-02 05:19 UTC, CCXXXI commented on docs/lang/optimizations.md
> +单指令流多数据流是很好的提供单核并行的方法。使用这种指令，可以利用 CPU 的 SIMD 寄存器，比通用寄存器更宽，例如一次放 4 个整数然后计算。OI 选手不需要了解自动向量化的细节，通常而言，clang 编译器会做比 GCC 更激进的自动向量化：
```suggestion
单指令流多数据流是很好的提供单核并行的方法。使用这种指令，可以利用 CPU 的 SIMD 寄存器，比通用寄存器更宽，例如一次放 4 个整数然后计算。OI 选手不需要了解自动向量化的细节，通常而言，Clang 编译器会做比 GCC 更激进的自动向量化：
```

根据 [官网](https://clang.llvm.org/)，标准的拼写是 **C**lang

2022-12-02 09:44 UTC, Enter-tainer commented on docs/lang/optimizations.md
> +GCC 和 Clang 都支持这个 Sanitizer。自动检查你的程序有无未定义行为。例如初始化前使用。
use before init 应该是 memory san 查的

2022-12-02 09:51 UTC, inclyc commented on docs/lang/optimizations.md
> +GCC 和 Clang 都支持这个 Sanitizer。自动检查你的程序有无未定义行为。例如初始化前使用。
啊！这里想举一个UB的例子，但是这个 UB 恰好不是 ubsan 查的

2022-12-02 09:51 UTC, inclyc commented on docs/lang/optimizations.md
> +GCC 和 Clang 都支持这个 Sanitizer。自动检查你的程序有无未定义行为。例如初始化前使用。
Nice catch!

2022-12-02 09:52 UTC, Enter-tainer commented on docs/lang/optimizations.md
> +GCC 和 Clang 都支持这个 Sanitizer。自动检查你的程序有无未定义行为。例如初始化前使用。
> Nice catch!

因为前几天我自己写了个use before init，ubsan没查出来。。怀恨在心

后来才发现是 memory san 查的

2022-12-02 09:57 UTC, Tiphereth-A reviewed
fix collapsible blocks

2022-12-02 09:57 UTC, Tiphereth-A commented on docs/lang/optimizations.md
> +???+note 布局1
```suggestion
???+note "布局1"
```

2022-12-02 09:57 UTC, Tiphereth-A commented on docs/lang/optimizations.md
> +???+note 布局2
```suggestion
???+note "布局2"
```

2022-12-02 09:57 UTC, Tiphereth-A commented on docs/lang/optimizations.md
> +???+note 不好的写法
```suggestion
???+note "不好的代码布局"
```

2022-12-02 09:57 UTC, Tiphereth-A commented on docs/lang/optimizations.md
> +???+note 好的写法
```suggestion
???+note "好的代码布局"
```

2022-12-02 09:57 UTC, Tiphereth-A commented on docs/lang/optimizations.md
> +???+note [GCD](https://godbolt.org/z/8Wb6WEnzv)
```suggestion
???+note "[GCD](https://godbolt.org/z/8Wb6WEnzv)"
```

2022-12-02 09:57 UTC, Tiphereth-A commented on docs/lang/optimizations.md
> +???+note [斐波那契数列](https://godbolt.org/z/4enof6Wcb)
```suggestion
???+note "[斐波那契数列](https://godbolt.org/z/4enof6Wcb)"
```

2022-12-02 09:57 UTC, Tiphereth-A commented on docs/lang/optimizations.md
> +???+note [阶乘](https://godbolt.org/z/n64e75xrf)
```suggestion
???+note "[阶乘](https://godbolt.org/z/n64e75xrf)"
```

2022-12-02 09:57 UTC, Backl1ght commented on docs/lang/optimizations.md
> +### Address Sanitizer -fsanitize=address
建议补充加了这个的代价

2022-12-02 09:58 UTC, inclyc commented on docs/lang/optimizations.md
> +### Address Sanitizer -fsanitize=address
好的

2022-12-02 10:06 UTC, inclyc commented on docs/lang/optimizations.md
> +GCC 和 Clang 都支持这个 Sanitizer。自动检查你的程序有无未定义行为。例如初始化前使用。
感谢！

2022-12-03 05:03 UTC, inclyc commented
打算删除斐波那契数列的例子，虽然编译器做了尾递归自动展开成循环，但这个循环仍然是指数级别的

2022-12-03 05:04 UTC, inclyc commented
> 打算删除斐波那契数列的例子，虽然编译器做了尾递归自动展开成循环，但这个循环仍然是指数级别的

加一句注释

2022-12-03 05:50 UTC, QuarticCat commented
手动强制 inline 还是有意义的，见这两个例子：

- https://blog.quarticcat.com/posts/optimize-difftastic/#manual-inlining
- https://github.com/rust-lang/hashbrown/pull/375 （在 MIR 这一层没有达到 inline 的阈值导致错失了一些优化

2022-12-03 05:55 UTC, inclyc commented
> 手动强制 inline 还是有意义的，见这两个例子：
> 
>     * https://blog.quarticcat.com/posts/optimize-difftastic/#manual-inlining
> 
>     * [Add `#[inline(always)]` to `find_inner` rust-lang/hashbrown#375](https://github.com/rust-lang/hashbrown/pull/375) （在 MIR 这一层没有达到 inline 的阈值导致错失了一些优化
> 
> 
> > <img alt="" height="14" src="https://camo.githubusercontent.com/181ff4147b07e15aa88b45a5ffb4eb4a686976f33e03822675c3085a132c0731/68747470733a2f2f626c6f672e717561727469636361742e636f6d2f66617669636f6e2d33327833322e706e67"> QuarticCat's Blog**[How Do I Boost Difftastic By 4x](https://blog.quarticcat.com/posts/optimize-difftastic/)**Difftastic is a structural diff that understands syntax. The diff results it generates are very fancy, but its performance is poor, and it consumes a lot of memory. Recently, I boosted it by 4x while using only 29% of memory (#393, #395, #401). This post explains how I accomplished this. Hope it can bring you some inspiration.
> > When I started to write this post, not all optimizations were reviewed and merged.

你写了之后，OI 届未来直接 `#define il __attribute__((always_inline))`，评价是如果搞不懂什么时候需要 `inline` 那最好是别写

2022-12-03 05:56 UTC, inclyc commented
BTW OI 还在用 C++ ，暂无 MIR 这种东西

2022-12-03 06:01 UTC, QuarticCat commented
本来也不是鼓励无脑 inline 。至于有没有效果，其实只要大样例测两轮做个对比就行了，以 benchmark 结果为基准。

MIR 这个只是一个额外的例子用来说明编译器有可能错失 inline 带来的优化机会

2022-12-03 06:03 UTC, inclyc commented
> 本来也不是鼓励无脑 inline 。至于有没有效果，其实只要大样例测两轮做个对比就行了，以 benchmark 结果为基准。
> 
> MIR 这个只是一个额外的例子用来说明编译器有可能错失 inline 带来的优化机会

那应该 blame 编译器，而不是手动 inline

2022-12-03 06:06 UTC, inclyc commented on docs/lang/optimizations.md
> +<!-- TODO: 开 O2 的比赛 -->
这段先留着不写吧，等后续 PR 来写

2022-12-03 06:21 UTC, inclyc commented
这个 PR 就先这样吧，别的内容通过后续 PR 写

2022-12-03 06:30 UTC, Enter-tainer submitted a review, later dismissed
cool！辛苦了

2022-12-03 07:45 UTC, abc1763613206 submitted a review, later dismissed

2022-12-03 07:47 UTC, Enter-tainer approved these changes

2022-12-03 07:47 UTC, Enter-tainer commented
好像得merge一下现在的master，要不然ci过不去

2022-12-03 08:12 UTC, CoelacanthusHex approved these changes

2022-12-03 13:13 UTC, inclyc commented
> 好像得merge一下现在的master，要不然ci过不去

rebase 上去？

2022-12-03 13:40 UTC, Tiphereth-A approved these changes

2022-12-03 13:54 UTC, merged