feat(lang/java-pro.md):增加arrayQueue的说明
OI-wiki/OI-wiki pull request #4477
Opened 2022-11-30 23:29 UTC by 1804040636

- [ ] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

2022-12-01 03:05 UTC, Tiphereth-A commented on docs/lang/java-pro.md
> +|      modInverse(BigInteger p)      |          返回 a `mod` p 的乘法逆元          |
```suggestion
|      `modInverse(BigInteger p)`      |          返回 a `mod` p 的乘法逆元          |
```

2022-12-03 02:30 UTC, 1804040636 commented on docs/lang/java-pro.md
> +1. **数据结构**：在数据结构上，ArrayDeque 和 LinkedList 都实现了 Java Deque 双端队列接口。但 ArrayDeque 没有实现了 Java List 列表接口，所以不具备根据索引位置操作的行为。
1. **数据结构**：在数据结构上，`ArrayDeque` 和 `LinkedList` 都实现了 `Deque` 双端队列接口。但 `ArrayDeque` 没有实现了 `List` 列表接口，所以不具备根据索引位置操作的行为。

2022-12-03 02:30 UTC, 1804040636 commented on docs/lang/java-pro.md
> +2. **线程安全**：ArrayDeque 和 LinkedList 都不考虑线程同步，不保证线程安全
2. **线程安全**：`ArrayDeque` 和 `LinkedList` 都不考虑线程同步，不保证线程安全

2022-12-03 02:30 UTC, 1804040636 commented on docs/lang/java-pro.md
> +4. **在遍历速度上**：ArrayDeque 是一块连续内存空间，基于局部性原理能够更好地命中 CPU 缓存行，而 LinkedList 是离散的内存空间对缓存行不友好。
4. **在遍历速度上**：`ArrayDeque` 是一块连续内存空间，基于局部性原理能够更好地命中 CPU 缓存行，而 `LinkedList` 是离散的内存空间，对缓存行不友好。

2022-12-03 02:30 UTC, 1804040636 commented on docs/lang/java-pro.md
> +5. **在操作速度上**：ArrayDeque 和 LinkedList 的栈和队列行为都是 O(1) 时间复杂度，ArrayDeque 的入栈和入队有可能会触发扩容，但从均摊分析上看依然是 O(1) 时间复杂度。
5. **在操作速度上**：`ArrayDeque` 和 `LinkedList` 的栈和队列行为都是 O(1) 时间复杂度，ArrayDeque 的入栈和入队有可能会触发扩容，但从均摊分析上看依然是 O(1) 时间复杂度。

2022-12-03 02:30 UTC, 1804040636 commented on docs/lang/java-pro.md
> +6. **额外内存消耗上**：ArrayDeque 在数组的头指针和尾指针外部有闲置空间，而 LinkedList 在节点上增加了前驱和后继指针。
6. **额外内存消耗上**：`ArrayDeque` 在数组的头指针和尾指针外部有闲置空间，而 `LinkedList` 在节点上增加了前驱和后继指针。

2022-12-03 02:30 UTC, 1804040636 commented on docs/lang/java-pro.md
> +3. **底层实现**：在底层实现上，ArrayDeque 是基于动态数组的，而 LinkedList 是基于双向链表的。
3. **底层实现**：在底层实现上，`ArrayDeque` 是基于动态数组的，而 `LinkedList` 是基于双向链表的。

2022-12-03 02:49 UTC, 1804040636 commented
刚刚看到一个奇怪的东西，好像在这个pr下面一起修改了雾、
[fix(misc/cdq-divide.md):干掉了奇怪的参考注释](https://github.com/OI-wiki/OI-wiki/pull/4477/commits/65dada22337e666c313d6121e981251fef3e5737)

2022-12-03 03:06 UTC, 1804040636 commented
(misc/cdq-divide.md):CDQ分治部分的代码用了data作为变量名，在c++14是可行的，在c++17及以后的版本中会有冲突，这个问题导致了本pr无法check成功，于是我就打算修改那部分的代码，把变量名改成data1

2022-12-03 03:40 UTC, inclyc commented
@1804040636 改了之后最好加一句注释

2022-12-03 03:48 UTC, 1804040636 commented on docs/dp/code/tree/tree_3.cpp
//因为github最近的c++标准升级为了17，所以修改了size变量名为size1

2022-12-03 03:48 UTC, 1804040636 commented on docs/misc/code/cdq-divide/cdq-divide_1.cpp
//因为github最近的c++标准升级为了17，所以修改了data变量名为data1

2022-12-03 03:48 UTC, 1804040636 commented on docs/misc/code/cdq-divide/cdq-divide_3.cpp
//因为github最近的c++标准升级为了17，所以修改了data变量名为data1

2022-12-03 03:48 UTC, 1804040636 commented on docs/misc/code/cdq-divide/cdq-divide_2.cpp
//因为github最近的c++标准升级为了17，所以修改了data变量名为data1

2022-12-03 03:57 UTC, 1804040636 commented
> @1804040636 改了之后最好加一句注释

好的，已经给修改过的部分增加了

2022-12-03 04:06 UTC, yusancky commented
从短期看，是不是可以先试试改一下编译指令？

https://github.com/OI-wiki/OI-wiki/blob/96fdbe9ff4d83e783010d3f93299307007dfdaeb/scripts/test.py#L34

```diff
-   cmd = 'g++ '+cpp+' -o '+name
+   cmd = 'g++ -std=c++14 '+cpp+' -o '+name
```

2022-12-03 04:56 UTC, Tiphereth-A commented
一个 pr 最好只做一件事情，修改代码规范建议开个新 pr

2022-12-03 05:01 UTC, inclyc reviewed
一个 PR 只做一件事情，这样可以方便开发者 revert 任何一个有问题的 PR. 这里面混入了 Java 相关的描述和你改的 `data1`

`data` 到底和哪个标识符冲突了？可以在注释中指明吗？

而且 `data1` 是个相当丑陋的命名

2022-12-03 05:03 UTC, Enter-tainer commented on docs/lang/java-pro.md
> +|      `modInverse(BigInteger p)`      |          返回 a `mod` p 的乘法逆元          |
这个估计是bot改的

2022-12-03 05:05 UTC, Tiphereth-A commented on docs/lang/java-pro.md
> +|      `modInverse(BigInteger p)`      |          返回 a `mod` p 的乘法逆元          |
> 这跟代码规范没关系

这个是这个 pr 原本要修改的部分

2022-12-03 05:09 UTC, inclyc commented on docs/lang/java-pro.md
> +|      `modInverse(BigInteger p)`      |          返回 a `mod` p 的乘法逆元          |
那应该开两个 PR，这个 review comment 是按照目前的  PR 标题写的

2022-12-03 05:11 UTC, Enter-tainer commented
提出一个比较方便的方案：
- 撤销目前对 data 的修改
- 将workflow中，将编译选项加入 -std=c++14 （这个事情或许可以在新的pr里面做？）

2022-12-03 05:12 UTC, inclyc commented
你可以新开一个分支，把改 C++17 相关的 commit cherry-pick 过去。然后现在这个分支 reset hard 到改 C++ 17 之前的版本，等另一个 PR land 之后，这边的  CI 应该就过了。

---

通常我们只在一个 patch 做一件事情，最终形成一个 commit ，这样可以 revert 相应的 commit 而不同时 revert 掉无关的。

2022-12-03 05:44 UTC, CCXXXI commented on docs/misc/code/cdq-divide/cdq-divide_1.cpp
> +//因为github最近的c++标准升级为了17，所以修改了data变量名为data1
https://zh.cppreference.com/w/cpp/iterator/data

但这不足以成为改名的理由

2022-12-03 05:53 UTC, CCXXXI requested changes
`data1` 也一样

2022-12-03 05:53 UTC, CCXXXI commented on docs/dp/code/tree/tree_3.cpp
> +long long n, size1[1000010], dep[1000010];
`size1` 这种命名意义不明，建议以下方案之一：

1. `size_`，后缀下划线按惯例用于避免命名冲突，不过一般用在 `if_` 这种和关键字冲突的严重情况
2. `sz`，缩写以避免冲突
3. 不修改命名，使用 `using ::size` 消歧义
4. 不修改命名，使用时改用 `::size` 明确指代

2022-12-03 07:17 UTC, 1804040636 commented
那这个分支我暂时就还是作为Java-pro.md,c++17的内容我等会发一个新的pr出来

2022-12-03 08:13 UTC, closed without merging