Update sgt.md:修正删除节点sz未更新的bug,添加替罪羊树整体实现
OI-wiki/OI-wiki pull request #4504
Opened 2022-12-09 13:09 UTC by xiezheyuan

- [x] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

2022-12-09 17:22 UTC, Backl1ght requested changes

2022-12-09 17:22 UTC, Backl1ght commented on docs/ds/sgt.md
> +  sz[k]--;
sz会在回溯的时候重新计算，这不是bug

2022-12-09 17:22 UTC, Backl1ght commented on docs/ds/sgt.md
> +```
请按照[代码块的格式要求](https://oi-wiki.org/intro/format/#%E4%BB%A3%E7%A0%81%E5%9D%97%E7%9A%84%E6%A0%BC%E5%BC%8F%E8%A6%81%E6%B1%82)进行修改

2022-12-10 01:51 UTC, xiezheyuan commented on docs/ds/sgt.md
> +  sz[k]--;
这样子也没有问题。

2022-12-10 02:11 UTC, xiezheyuan commented on docs/ds/sgt.md
> +```
我不大会使用 github，请问怎么样修改发过PR的代码？

2022-12-10 02:13 UTC, xiezheyuan commented on docs/ds/sgt.md
> +```
我不大会使用 github，请问怎么样修改发过PR的代码？

2022-12-10 02:15 UTC, xiezheyuan commented on docs/ds/sgt.md
> +  sz[k]--;
不对，按照我实现的经验，如果不加这一行会导致查询排名时出锅。而且网上几乎所有的博客都加了这一行。

等一下，我觉得锅的问题应该是在找到节点的时候没有sz--。

2022-12-10 02:23 UTC, Backl1ght commented on docs/ds/sgt.md
> +```
这个PR是要将[xiezheyuan:patch-2](https://github.com/xiezheyuan/OI-wiki/tree/patch-2)的改动合入[OI-wiki:master](https://github.com/OI-wiki/OI-wiki)，所以你在[xiezheyuan:patch-2](https://github.com/xiezheyuan/OI-wiki/tree/patch-2)会同步到这个PR

2022-12-10 02:28 UTC, Backl1ght commented on docs/ds/sgt.md
> +  sz[k]--;
我看下来是没有问题的，这个也会在Calc(k)的时候被处理

2022-12-10 03:45 UTC, xiezheyuan commented on docs/ds/sgt.md
> +  sz[k]--;
问题就出在这里呀。

如果 `sz` 没有再找到节点时 `--`，又没有 `pushup`，其实是没有被处理的。

[没有sz--时的提交记录](https://www.luogu.com.cn/record/96966556)

2022-12-10 03:55 UTC, xiezheyuan commented on docs/ds/sgt.md
> +```
已修正。

2022-12-10 12:48 UTC, Backl1ght commented on docs/ds/sgt.md
> +  sz[k]--;
emmmm，没看到它return了，确实有问题

2022-12-10 12:58 UTC, Backl1ght commented on docs/ds/code/sgt/sgt_1.cpp
> +    if (t[i].cnt > 0) t[i].cnt--;
这样和前文的描述相符，试了下也是对的

2022-12-11 01:54 UTC, xiezheyuan commented on docs/ds/code/sgt/sgt_1.cpp
> +    if (t[i].cnt > 0) t[i].cnt--;
已修改

2022-12-11 03:32 UTC, Backl1ght commented on docs/ds/sgt.md
> +  sz[k]--;
额，刚刚看了一下，原本的代码是没有问题的，它找到节点之后没有return，一定会走Calc(k)，你的return了走不到。而且对于经过的每个节点都sz--的话在不保证删除节点存在的时候会有问题。

2022-12-18 11:21 UTC, xiezheyuan commented
怎么还没有取消修改请求呀，谁能帮我一下。

2022-12-18 11:26 UTC, Enter-tainer commented
cc @Backl1ght

2022-12-29 00:08 UTC, xiezheyuan commented
@Backl1ght 都三周了，请来看看。

2022-12-30 11:35 UTC, Backl1ght commented
sorry因为前段时间阳了所以鸽了很久。

2022-12-30 11:45 UTC, Backl1ght commented
我看下来还是认为原本的描述没有问题，不会接受对原本的描述的修改。

然后我认为增加整体实现是ok的。但是你给出的实现在不保证被删除节点存在时会有问题。

2022-12-30 12:34 UTC, xiezheyuan commented
> 我看下来还是认为原本的描述没有问题，不会接受对原本的描述的修改。
> 
> 然后我认为增加整体实现是ok的。但是你给出的实现在不保证被删除节点存在时会有问题。

先回答第一段的问题。先不论原来的描述是否有问题，但使用原来的删除节点的实现只有48分，说明实现有问题。具体提交记录看之前的评论。而且我记得您在阳之前是同意的呀。

再回答第二段的问题，原题保证删除操作合法

2022-12-30 12:36 UTC, xiezheyuan commented
https://www.luogu.com.cn/record/96966556

2022-12-30 12:46 UTC, Backl1ght commented
> > 我看下来还是认为原本的描述没有问题，不会接受对原本的描述的修改。
> > 然后我认为增加整体实现是ok的。但是你给出的实现在不保证被删除节点存在时会有问题。
> 
> 先回答第一段的问题。先不论原来的描述是否有问题，但使用原来的删除节点的实现只有48分，说明实现有问题。具体提交记录看之前的评论。而且我记得您在阳之前是同意的呀。
> 
> 再回答第二段的问题，原题保证删除操作合法

但不是所有的题目都保证删除操作合法，我认为给出的参考实现不应该有这样的问题

2023-01-18 02:52 UTC, yanboishere approved these changes

2023-01-18 09:04 UTC, xiezheyuan commented
我觉得这可以通过简单的特判实现

2023-03-05 00:20 UTC, closed without merging