修改python部分代码
OI-wiki/OI-wiki pull request #4561
Opened 2023-01-02 06:20 UTC by WASSER2545

- [ ] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

2023-01-02 07:16 UTC, Great-designer commented
> * [ ]  我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

请勾选“我已认真阅读贡献指南……”，或者在发起pr的时候把模板删了，以免造成现在的尴尬：您不勾选，在这儿留下一个空的任务框，下面这个task-list检查就终止不了，它也合并不了。如果我急迫地替您勾选，您又确实没有“声明自己看过”，那就更加尴尬了。

2023-01-02 07:43 UTC, WASSER2545 commented
@Great-designer 抱歉抱歉

2023-01-02 13:54 UTC, Great-designer approved these changes

2023-01-03 04:06 UTC, Tiphereth-A commented
请阅读 https://oi-wiki.org/intro/htc/#commit-%E4%BF%A1%E6%81%AF%E6%A0%BC%E5%BC%8F%E8%A7%84%E8%8C%83 ，这是贡献指南的一部分

cc @Great-designer @Alex-Github-Programmer @yanboishere

2023-01-03 04:15 UTC, Tiphereth-A commented
> 或者在发起pr的时候把模板删了

这样欠妥吧，如果一个人不阅读一个项目的 htc 和 coc 等就来参与是否说明这个人不太尊重这个项目 🤔

2023-01-03 04:34 UTC, Menci commented
@Tiphereth-A 我们老成员都是把模板删了的（

2023-01-03 06:13 UTC, Tiphereth-A requested changes

2023-01-03 06:13 UTC, Tiphereth-A commented on docs/ds/hash.md
>              return -1
#4564

2023-01-03 06:19 UTC, Great-designer commented on docs/ds/hash.md
>              return -1
啥玩意儿啊……

2023-01-03 06:20 UTC, Tiphereth-A commented on docs/ds/hash.md
>              return -1
> 啥玩意儿啊……

既然作者想要修改而这个 PR 还没有修改，那这个 PR 就不应该 merge 吧 🤔

2023-01-03 06:30 UTC, Great-designer commented
> 这样欠妥吧，如果一个人不阅读一个项目的 htc 和 coc 等就来参与是否说明这个人不太尊重这个项目 🤔

一般而言是要求管理员尽可能尊重pr提交者，因为是人家给本项目提修改或建设意见，属于pr提交者的意见始终是重要的。

管理员无需尊重pr提交者的情形，例如相应的pr有硬伤，或者根本救不起来，那么管理员可以直接关掉。

至于pr提交者是否在“阅读贡献指南/社区公约”这件事情上尊重本项目，事实上没有硬性要求。因为本项目的架构在机制上是保护管理员方的，必须有非提交者的2个通过意见才能修改。本项目不是偏向用户方的wikipedia架构，不是用户随便就能改的那种。

本项目的架构也与OI本身迭代速度较慢，偏向稳定，是相关的。

换句话说，即使pr提交者发一个奇烂无比的东西，那么管理员不通过，也不可能对项目主体造成损害。从而，提交方形式上尊重与否，相对不重要，相关内容的审核才是相对更重要的。

2023-01-03 06:32 UTC, CoelacanthusHex commented
@Great-designer 尊重是相互的，如果提交者不尊重维护者（完全不看htc和coc），那么维护者也不必尊重提交者

2023-01-03 06:42 UTC, Ir1d approved these changes
感谢大家！ 考虑到 @WASSER2545  对 github 可能不太熟练我就顺手改了hhh 还麻烦 @Tiphereth-A 有空再看下

2023-01-03 06:43 UTC, WASSER2545 commented
@Ir1d 抱歉给你们添麻烦了

2023-01-03 06:45 UTC, Ir1d commented
@WASSER2545 感谢大佬帮忙捉 bug 🙏

2023-01-03 06:46 UTC, Tiphereth-A approved these changes

2023-01-03 07:25 UTC, merged