add (p-adic.md)：更新 p 进数
OI-wiki/OI-wiki pull request #4578
Opened 2023-01-06 13:33 UTC by Great-designer

如题

2023-01-06 13:39 UTC, CoelacanthusHex commented on docs/math/number-theory/p-adic.md
> +有理数集的基数是阿列夫零，其中有很多的洞，填补这些洞的方法有若干种。通常的填补这些洞的方法创造出实数，实数集的基数是阿列夫一。
```suggestion
有理数集的基数是 $\aleph_0$，其中有很多的洞，填补这些洞的方法有若干种。通常的填补这些洞的方法创造出实数，实数集的基数是 $\aleph_1$。
```
我觉得用符号更好一些

2023-01-06 13:43 UTC, CoelacanthusHex commented
你这个 base 已经两个多月没更新了，请 rebase

2023-01-06 14:43 UTC, Great-designer commented
> 下面有个update branch点一下就可以了。相信不需要多少门槛。（

提醒，已经没有update branch了……这个东西很可能是管理员可见

另外，权限越低，网页端不能直接使用之后，在本地pull和push的连接通畅概率显著下降，不停点击fetch origin按钮重复15分钟才可能成功一次，rebase这件事的成本大约是30分钟

2023-01-06 14:50 UTC, Enter-tainer commented
@Great-designer 可以考虑使用 fastgit.org 等反代服务。不过我也不清楚这个能不能push...

2023-01-08 14:43 UTC, Great-designer commented
处理了所有的 e。本文没有 i，不涉及字母 i 的问题。

2023-01-08 14:49 UTC, Enter-tainer commented
有兴趣的话，可以在格式手册里面添加一段关于 e, i 的描述，这样之后的贡献者就可以自己把e和i写成直立的

2023-01-09 01:41 UTC, Great-designer commented
> 有兴趣的话，可以在格式手册里面添加一段关于 e, i 的描述，这样之后的贡献者就可以自己把e和i写成直立的

这个很可能不会像预想地那么有效……虽然当代人经历过这些都知道了，后来人不会考虑这么多的……因为加一个样式并不好些，也不容易想到。

多数人即使看了很多书，也不会注意到其中字体的细节，不强调是难以看出来的。

定期整理格式是好办法。每过一段时间专门不改内容而整一遍格式。

2023-01-12 03:21 UTC, Enter-tainer approved these changes
thx

2023-01-20 09:01 UTC, Great-designer commented
作为前置可以看看#4580

2023-01-25 04:28 UTC, Tiphereth-A requested changes

2023-01-25 04:28 UTC, Tiphereth-A commented on docs/math/number-theory/p-adic.md
> +有理数集的基数是 $\aleph_0$，其中有很多的洞，填补这些洞的方法有若干种。通常的填补这些洞的方法创造出实数，实数集的基数是 $\aleph_1$。
错误的, 实数集的基数是 $2^{\aleph_0}$, 连续统假设成立的时候才是 $\aleph_1$

2023-01-25 09:17 UTC, Great-designer commented on docs/math/number-theory/p-adic.md
> +有理数集的基数是 $\aleph_0$，其中有很多的洞，填补这些洞的方法有若干种。通常的填补这些洞的方法创造出实数，实数集的基数是 $\aleph_1$。
这件事情我不知道，或者说不能判断正误。

在百度百科的《连续统假设》正文写道：

“1874年[格奥尔格·康托尔](https://baike.baidu.com/item/%E6%A0%BC%E5%A5%A5%E5%B0%94%E6%A0%BC%C2%B7%E5%BA%B7%E6%89%98%E5%B0%94/4614747?fromModule=lemma_inlink)猜测在[可列集](https://baike.baidu.com/item/%E5%8F%AF%E5%88%97%E9%9B%86/9555116?fromModule=lemma_inlink)基数和实数基数之间没有别的基数，这就是著名的[连续统](https://baike.baidu.com/item/%E8%BF%9E%E7%BB%AD%E7%BB%9F?fromModule=lemma_inlink)假设。”

“[自然数集](https://baike.baidu.com/item/%E8%87%AA%E7%84%B6%E6%95%B0%E9%9B%86?fromModule=lemma_inlink)是最小的无穷集合，自然数集的势记作[阿列夫](https://baike.baidu.com/item/%E9%98%BF%E5%88%97%E5%A4%AB?fromModule=lemma_inlink)零。康托尔证明连续统势等于自然数集的幂集的势。是否存在一个无穷集合，它的势比自然数集的势大，比连续统势小？这个问题被称为连续统问题。
康托尔猜想这个问题的解答是否定的，即连续统势是比自然数集的势大的势中最小的一个无穷势，记作C1；自然数集的势记作C0。这个猜想就称为[连续统](https://baike.baidu.com/item/%E8%BF%9E%E7%BB%AD%E7%BB%9F?fromModule=lemma_inlink)假设。”

这个定义的逻辑关系，究竟是在证明“可列集是$\aleph_0$，连续统是$\aleph_1$，可列集和连续统之间没有其他基数”，还是在证明你说的这种情况，我大概不是恨明白，究竟业内通识上是怎样认为的。

不过为了避免争议，这一段不算重要，也可以删掉。

2023-01-25 14:29 UTC, Great-designer commented on docs/math/number-theory/p-adic.md
> +有理数集的基数是 $\aleph_0$，其中有很多的洞，填补这些洞的方法有若干种。通常的填补这些洞的方法创造出实数，实数集的基数是 $\aleph_1$。
删完了

2023-01-26 10:45 UTC, Tiphereth-A commented on docs/math/number-theory/p-adic.md
> +有理数集的基数是 $\aleph_0$，其中有很多的洞，填补这些洞的方法有若干种。通常的填补这些洞的方法创造出实数，实数集的基数是 $\aleph_1$。
> 这个定义的逻辑关系，究竟是在证明“可列集是$\aleph_0$，连续统是$\aleph_1$，可列集和连续统之间没有其他基数”，还是在证明你说的这种情况，我大概不是恨明白，究竟业内通识上是怎样认为的。

$\aleph_1$ 指的是大于可列集的最小无限集的基数, 连续统是实数集的基数. See <https://mathworld.wolfram.com/Aleph-1.html>

另外, 考虑到 OI wiki 的受众人群, 如果您打算介绍相关内容, 建议多补充一下集合论的相关内容

2023-01-26 10:51 UTC, Tiphereth-A commented on docs/math/number-theory/p-adic.md
> +有理数集是可列集，当中有很多的洞。填补这些洞的方法有若干种。通常的填补这些洞的方法创造出实数，实数是连续统。
目前的描述是令人困惑的, 对于不了解实数的完备性这类概念的人群, 这句话的含义不明, 可能难以理解为什么实数没有所谓的 "洞"; 对于了解实数的完备性这类概念的人群, 这句话又过于简略和不严谨了

2023-01-27 02:19 UTC, Great-designer commented on docs/math/number-theory/p-adic.md
> +有理数集是可列集，当中有很多的洞。填补这些洞的方法有若干种。通常的填补这些洞的方法创造出实数，实数是连续统。
呃……我想想看。实在不行删了得了

2023-01-27 02:25 UTC, Great-designer commented on docs/math/number-theory/p-adic.md
> +有理数集是可列集，当中有很多的洞。填补这些洞的方法有若干种。通常的填补这些洞的方法创造出实数，实数是连续统。
改完了

2023-01-27 02:30 UTC, Great-designer commented on docs/math/number-theory/p-adic.md
> +有理数集的基数是 $\aleph_0$，其中有很多的洞，填补这些洞的方法有若干种。通常的填补这些洞的方法创造出实数，实数集的基数是 $\aleph_1$。
> 另外, 考虑到 OI wiki 的受众人群, 如果您打算介绍相关内容, 建议多补充一下集合论的相关内容

您的代数系统还没更。

另外数学分析的戴德金分割、柯西收敛、单调有界、闭区间套，这一堆玩意儿，是数学系的数学分析，是不建议写的……高中课本对此也是一笔带过，仅仅说“从有理数扩充至实数”而已。计算机领域大多为离散的东西，很少研究连续的玩意儿。

定义自然数用了皮亚诺公理，也不会有人在这里写皮亚诺公理。然后扩充至整数不难，扩充至有理数也不难，都不用写。到实数这里又是一套麻烦的东西。（复数反而简单，已经写了。）

2023-03-05 02:33 UTC, Great-designer commented
《如果此 PR 在将来的 14 天内仍未恢复活动》

2023-04-16 01:36 UTC, Great-designer commented
学校里的网络登录GitHub过于困难，并且经常有保密审查，恐怕难以经常登录。

我思考了思考，因为p-adic在计算机里面主要是左展开和自然溢出的运算（p进负整数和有理数用到自然溢出，旁边的#4580 5为底的对数也是自然溢出），并且相比之下应用确实暂时难以找到（ACM/ICPC还没有出过这样的题吧），所以这个还是关了。

由于模数是2的幂，乘法群结构和复数循环群不同（1有4个平方根，有点像四元数却不同构，甚至没有虚数单位i），这上面也无法进行傅里叶变换等操作，所以也没有傅里叶这类高级手法。

如果有愿意出这题的，例如“寻找一个64位整型的3倍为1”之类的，后续再说。

2023-04-16 01:36 UTC, closed without merging