feat(constant.md)：更新数学常数
OI-wiki/OI-wiki pull request #4585
Opened 2023-01-08 12:05 UTC by Great-designer

考虑到e和i的写法需要统一成mathrm

2023-01-08 12:32 UTC, Great-designer commented
感觉改完了

2023-01-08 14:20 UTC, Great-designer commented on docs/math/constant.md
> +虽然目前算法竞赛领域普遍支持的版本是 C++14，但是迟早有一天算法竞赛的支持版本会到达 C++20，也许在不算太遥远的未来，介绍 `<numbers>` 头文件是必需的。
这个我查过了：M_PI 是一个宏定义，此宏定义和编译器有关，TC中M_PI宏就定义在<math.h>里面。但vc的<math.h>中没有了M_PI的宏定义。

这表明，这类定义是编译器标准而非语言标准，换一个编译器存在立即跑不通的风险。不能保证打比赛时赛方使用的编译器标准。

部分编译器的<math.h>支持这些宏：

```c++
#if defined(_USE_MATH_DEFINES) && !defined(_MATH_DEFINES_DEFINED)
#define _MATH_DEFINES_DEFINED
#define M_E        2.71828182845904523536
#define M_LOG2E    1.44269504088896340736
#define M_LOG10E   0.434294481903251827651
#define M_LN2      0.693147180559945309417
#define M_LN10     2.30258509299404568402
#define M_PI       3.14159265358979323846
#define M_PI_2     1.57079632679489661923
#define M_PI_4     0.785398163397448309616
#define M_1_PI     0.318309886183790671538
#define M_2_PI     0.636619772367581343076
#define M_2_SQRTPI 1.12837916709551257390
#define M_SQRT2    1.41421356237309504880
#define M_SQRT1_2  0.707106781186547524401
#endif  /* _USE_MATH_DEFINES */
```

2023-01-08 14:23 UTC, Great-designer commented on docs/math/constant.md
> +\int_1^x \frac{1}{t}dt
有道理

2023-01-08 15:13 UTC, CoelacanthusHex commented on docs/math/constant.md
> +虽然目前算法竞赛领域普遍支持的版本是 C++14，但是迟早有一天算法竞赛的支持版本会到达 C++20，也许在不算太遥远的未来，介绍 `<numbers>` 头文件是必需的。
这些常量是 POSIX 标准规定的语法拓展[^1]
同时 GNU 拓展规定了一系列以 fN 和 fNx 为为后缀的不同精度的宏定义常量[^2]
此外这个和编译器本身无关，和C标准库实现有关

[^1]: https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/math.h.html
[^2]: https://www.gnu.org/software/libc/manual/html_node/Mathematical-Constants.html

2023-01-08 15:15 UTC, CoelacanthusHex commented on docs/math/constant.md
> +虽然目前算法竞赛领域普遍支持的版本是 C++14，但是迟早有一天算法竞赛的支持版本会到达 C++20，也许在不算太遥远的未来，介绍 `<numbers>` 头文件是必需的。
需要注意的是 GNU 拓展规定的这些常量使用的是 ISO/IEC TS 18661-3 规定的机器无关浮点数类型

2023-01-08 16:13 UTC, CoelacanthusHex requested changes
虽然这是数学板块的一部分，但我觉得大可不必用主要篇幅讲数学史吧

2023-01-08 16:32 UTC, r-value requested changes
同步一下在tg群里的建议(

2023-01-08 16:32 UTC, r-value commented on docs/math/constant.md
> +还有一个内置数学常数是欧拉常数 $\gamma$，记作 `egamma`。
建议修改这一整节. 这段文本几乎没有任何用处, 看完什么都没有明白. 既没有教会读者怎么用, 读者又在很多竞赛中不能用.

2023-01-08 16:32 UTC, r-value commented on docs/math/constant.md
> +$$
$\pi$ 的积分或级数性质在算法竞赛中没有任何用处. 与此相对地, $\mathrm{e}$ 的级数性质在生成函数部分有用应当保留.

2023-01-08 16:32 UTC, r-value commented on docs/math/constant.md
> +## 自然常数
既然给了 $\pi$ 的一般求法建议也给出 $\mathrm{e}$ 的.

2023-01-09 01:45 UTC, Great-designer commented
> 虽然这是数学板块的一部分，但我觉得大可不必用主要篇幅讲数学史吧

这点不赞同。作为介绍者，当然要介绍介绍“它是怎么来的”。就像要尊重贡献者的创作一样，写论文也喜欢引用大佬的名字拜拜码头，百年前的大佬好不容易发现这些，后来人说“自己不是大佬们的门徒”无法做到。

作为读者，不感兴趣，类似于影视剧前面的“xx声明”，大不了跳过不看就是。但作为介绍者的角度，该尽到的义务还是要尽到的。

2023-01-09 01:46 UTC, Great-designer commented on docs/math/constant.md
> +## 自然常数
这个建议合理。不过e的级数的收敛足够快，足以计算e了吧

2023-01-09 01:47 UTC, Great-designer commented on docs/math/constant.md
> +还有一个内置数学常数是欧拉常数 $\gamma$，记作 `egamma`。
这个建议合理。我可以和前文前几个人介绍的常量结合结合，考虑一下怎么改……

2023-01-09 01:55 UTC, Great-designer commented on docs/math/constant.md
> +$$
这点不赞同。我从后来人的视角看，它们都是较为合理的定义方法。

（甚至可以在网上随便找到一大堆“快速计算圆周率”的算法类文章，甚至都是些一大堆收敛得更快的级数，拉马努金之类，还有什么BBP公式，一般常人听都没听说过）

从定义的视角看，这里的定义才是和e“对称的”，是数值的定义办法。大家在小学学过的圆周率，是以基本事实的形式给出的，具体是多少并不能说清楚。然而在后来的数学视角看，给出一个清晰明快的级数表达式定义，比几何直观要重要得多。在复数域之外的数域上可能没有平面与周角的几何直观，但可能有完全类似的圆周率，这就是因为，虽然几何不能迁移，但是级数可以迁移。

并且级数相对于几何，更加与算法直接相关。如果后来人想介绍“计算圆周率”的算法，直接顺着这里往后补就行，无非是一些收敛更快的级数。

2023-01-09 02:02 UTC, Great-designer commented on docs/math/constant.md
> +## 自然常数
已补充完毕

2023-01-09 02:05 UTC, inclyc commented on docs/math/constant.md
> +虽然目前算法竞赛领域普遍支持的版本是 C++14，但是迟早有一天算法竞赛的支持版本会到达 C++20，也许在不算太遥远的未来，介绍 `<numbers>` 头文件是必需的。
你不会以为OI代码要兼容msvc吧

2023-01-09 02:16 UTC, Great-designer commented on docs/math/constant.md
> +虽然目前算法竞赛领域普遍支持的版本是 C++14，但是迟早有一天算法竞赛的支持版本会到达 C++20，也许在不算太遥远的未来，介绍 `<numbers>` 头文件是必需的。
已经补充介绍完毕。

2023-01-09 02:17 UTC, Great-designer commented
上述大佬们提的意见都改完了。

2023-01-09 03:57 UTC, r-value commented on docs/math/constant.md
> +还有一个内置数学常数是欧拉常数 $\gamma$，记作 `egamma`。
`<numbers>` 的问题仍然存在.

> 既没有教会读者怎么用, 读者又在很多竞赛中不能用.

2023-01-09 03:58 UTC, r-value commented on docs/math/constant.md
> +$$
合理, 但这里是 **OI** Wiki

2023-01-09 04:03 UTC, r-value requested changes

2023-01-09 04:03 UTC, r-value commented on docs/math/constant.md
> +因为这个级数收敛的速度足够快，编程的时候通常用 $x$ 取 $1$ 或 $-1$ 时得到的级数直接计算自然常数 $\mathrm{e}$。
OI 里没有人会想写一段代码用级数计算 $\mathrm{e}$. 请换一个更方便的方法.

2023-01-09 04:03 UTC, r-value commented on docs/math/constant.md
> +还有一个内置数学常数是欧拉常数 $\gamma$，常量记作 `egamma`。
这一段依然什么都没有说明白. 读完几乎没有获得任何实用信息 (i.e. 还是不会用).

2023-01-09 04:13 UTC, r-value commented
> 作为读者，不感兴趣，类似于影视剧前面的“xx声明”，大不了跳过不看就是。但作为介绍者的角度，该尽到的义务还是要尽到的。

那么这部分建议留一个外链或默认折叠, 提高有用的信息密度, 方便主要受众 (i.e. OIers) 快速找到其中对读者有用的信息而不必在您提供的无关信息中筛选.

2023-01-09 04:50 UTC, Great-designer commented on docs/math/constant.md
> +还有一个内置数学常数是欧拉常数 $\gamma$，常量记作 `egamma`。
参考自https://zh.cppreference.com/w/cpp/numeric/constants

如果您觉得有更好的写法，不妨给个suggestion出来

2023-01-09 04:51 UTC, Great-designer commented on docs/math/constant.md
> +因为这个级数收敛的速度足够快，编程的时候通常用 $x$ 取 $1$ 或 $-1$ 时得到的级数直接计算自然常数 $\mathrm{e}$。
予以补充的意见合理。

2023-01-09 04:53 UTC, alphagocc requested changes

2023-01-09 04:53 UTC, alphagocc commented on docs/math/constant.md
> +同时，GNU 拓展规定了一系列以 fN 和 fNx 为为后缀的不同精度的宏定义常量 [2](#user-content-fn-2-e92077518d669f2735cd5034a5c6ae51)，GNU 拓展规定的常量使用的是 ISO/IEC TS 18661-3 规定的机器无关浮点数类型。
ISO/IEC TS 18661-3 规定了什么

2023-01-09 04:53 UTC, alphagocc commented on docs/math/constant.md
> +以下内置常数均为 `inline constexpr double` 类型，均为与相应无理数最接近的浮点数。以下给出常量名，以及该常量的介绍。
应表述为双精度浮点，此处的 `inline constexpr` 在本 wiki 内不能起到任何实际性的作用

2023-01-09 04:53 UTC, alphagocc commented on docs/math/constant.md
> +更多内容见弧度制与坐标系一文。
文内并未提到圆周率

2023-01-09 04:53 UTC, alphagocc commented on docs/math/constant.md
> +一般在 C 语言中取 $\pi$ 为 `acos(-1)`，只有这个值是最接近 $\pi$ 的浮点数。使用 `acos(-1)` 或者 `4*atan(1)` 写出来的 $\pi$ 是 $3.14159265358979310000$。
`acosl(-1)` 更加精确

2023-01-09 04:53 UTC, alphagocc commented on docs/math/constant.md
> +一般在 C 语言中取 $\pi$ 为 `acos(-1)`，只有这个值是最接近 $\pi$ 的浮点数。使用 `acos(-1)` 或者 `4*atan(1)` 写出来的 $\pi$ 是 $3.14159265358979310000$。
所以需要限定双精度浮点？

2023-01-09 04:53 UTC, alphagocc commented on docs/math/constant.md
> +一般在 C 语言中取 $\pi$ 为 `acos(-1)`，只有这个值是最接近 $\pi$ 的浮点数。使用 `acos(-1)` 或者 `4*atan(1)` 写出来的 $\pi$ 是 $3.14159265358979310000$。
哦，从原来那里搬过来的，那就顺手改一下吧

2023-01-09 04:56 UTC, Great-designer commented
我声明，所有的数学史都只是“在开头写了一小句”

“1690 年，莱布尼茨在信中第一次提到自然常数 $\mathrm{e}$。”无可厚非

“最早圆周率作为一种几何的基本事实来认识，对圆周率的计算也是借助测量、几何学推导等方法进行。”——为了证明下文写级数是必要的。如果研究全靠测量，那么要算法干什么？

“$\pi$ 和 $\tau$ 两个数学常数”——这是搬来的，首先搬之前没收到过任何意见。这是一个严肃的争议话题，以至于python里面内置了pi和tau两个数学常数，专门平息这种争议。

“欧拉常数又称欧拉马歇罗尼常数，一般用希腊字母 $\gamma$ 表示，最早在 1735 年由欧拉发现。1790 年意大利数学家马歇罗尼（Lorenzo Mascheroni）将该常数计算到小数点后 32 位，但他的计算在第 20 位往后出现了错误。”
介绍“欧拉马歇罗尼常数”不介绍马歇罗尼能行吗？这就是举手之劳

没有数学史了。真的不知道这怎么就“全篇都在写数学史”

退一万步讲，一个wiki有这种东西刚好证明知识渊博啊，书香气息浓厚啊……总之肯定是锦上添花的

2023-01-09 04:59 UTC, r-value commented
> 那么这部分建议留一个外链或默认折叠, 提高有用的信息密度, 方便主要受众 (i.e. OIers) 快速找到其中对读者有用的信息而不必在您提供的无关信息中筛选.

clarify: 写这句话的时候这里指的是 $\pi$ 的级数定义等有趣但对主要读者没用的知识. 虽然数学史也应归于此类.

2023-01-09 05:01 UTC, r-value commented on docs/math/constant.md
> +因为这个级数收敛的速度足够快，编程的时候通常用 $x$ 取 $1$ 或 $-1$ 时得到的级数直接计算自然常数 $\mathrm{e}$。
可以认为这个实现很有趣值得介绍, 但这里不应隐含地推荐读者真的这样实现, 也不应作为唯一实现.

2023-01-09 05:51 UTC, Great-designer commented on docs/math/constant.md
> +同时，GNU 拓展规定了一系列以 fN 和 fNx 为为后缀的不同精度的宏定义常量 [2](#user-content-fn-2-e92077518d669f2735cd5034a5c6ae51)，GNU 拓展规定的常量使用的是 ISO/IEC TS 18661-3 规定的机器无关浮点数类型。
> ISO/IEC TS 18661-3 规定了什么

问一下 @CoelacanthusHex

2023-01-09 05:51 UTC, Great-designer commented on docs/math/constant.md
> +以下内置常数均为 `inline constexpr double` 类型，均为与相应无理数最接近的浮点数。以下给出常量名，以及该常量的介绍。
合理

2023-01-09 05:52 UTC, Great-designer commented on docs/math/constant.md
> +更多内容见弧度制与坐标系一文。
合理。应当删去

2023-01-09 06:02 UTC, Great-designer commented
累了。歇了。

写这些东西确实很有趣，甚至比打游戏还要有趣。但现在确实有一个矛盾。我看了看上面的讨论，大多问题还是针对格式方面的，例如“重点展示和略过”，“详略得当”这事属于格式层次，确实需要考虑。又例如一些更多的补充意见，也确实说得对。

希望大家多提些切实可行的建设性意见，而不是意见提出来完全没有任何建设性，纯粹为了攻击而攻击，这实在无趣，结束也是一地鸡毛。

至于那个changes requested提到的“主要篇幅讲数学史”，这种根本性错误几乎等价于完全没读文章就给评判的事，我也反驳过了，不予采纳。

至于更多指摘，需要我自己自证清白的，我是懒得弄了。我不想做这种“自证清白”的事情，无关紧要的事情有罪就有罪，这无所谓。更多的事情改不改的罢，至少在写的时候我已经开心了，就好。

2023-01-09 06:25 UTC, r-value commented on docs/math/constant.md
> +还有一个内置数学常数是欧拉常数 $\gamma$，常量记作 `egamma`。
我比较好奇您是否真的自己用过, 因为您对这些标识符具体如何使用在程序里绝口不提, 也没有给出哪怕一些正确使用的线索(比如最基本的, 它们位于哪个命名空间)

2023-01-09 07:33 UTC, Great-designer commented on docs/math/constant.md
> +还有一个内置数学常数是欧拉常数 $\gamma$，常量记作 `egamma`。
> 我比较好奇您是否真的自己用过, 因为您对这些标识符具体如何使用在程序里绝口不提, 也没有给出哪怕一些正确使用的线索(比如最基本的, 它们位于哪个命名空间)

看到这样的回复，说明您没有阅读过cppreference。

2023-01-09 07:34 UTC, r-value commented on docs/math/constant.md
> +还有一个内置数学常数是欧拉常数 $\gamma$，常量记作 `egamma`。
> 看到这样的回复，说明您没有阅读过cppreference。

如果需要我读 cppreference 才能学会, 建议直接留 cppreference 链接.

2023-01-09 07:36 UTC, r-value commented on docs/math/constant.md
> +还有一个内置数学常数是欧拉常数 $\gamma$，常量记作 `egamma`。
更精确地, 这些标识符均不是 OI 正常环境即可引用的. 它们并不位于 `::` 或 `std::` 命名空间.

2023-01-09 07:42 UTC, r-value commented on docs/math/constant.md
> +还有一个内置数学常数是欧拉常数 $\gamma$，常量记作 `egamma`。
要想使用这些标识符 至少应当指明它们位于 `std::numbers` 命名空间

2023-01-09 07:44 UTC, renbaoshuo commented on docs/math/constant.md
> +还有一个内置数学常数是欧拉常数 $\gamma$，常量记作 `egamma`。
这些数学常数均位于 [`std::numbers`](https://zh.cppreference.com/w/cpp/numeric/constants) 命名空间下，以 `sqrt2` 为例，使用时有以下两种方案：

1. 使用 `using namespace std::numbers` 语句，然后直接使用 `sqrt2` 即可。
2. 使用 `std::numbers::sqrt2` 的形式。

2023-01-09 09:17 UTC, Great-designer commented on docs/math/constant.md
> +还有一个内置数学常数是欧拉常数 $\gamma$，常量记作 `egamma`。
> 这些数学常数均位于 [`std::numbers`](https://zh.cppreference.com/w/cpp/numeric/constants) 命名空间下，以 `sqrt2` 为例，使用时有以下两种方案：
> 
> 1. 使用 `using namespace std::numbers` 语句，然后直接使用 `sqrt2` 即可。
> 2. 使用 `std::numbers::sqrt2` 的形式。

这是优秀的建设性意见。

2023-01-09 09:20 UTC, Great-designer commented on docs/math/constant.md
> +还有一个内置数学常数是欧拉常数 $\gamma$，常量记作 `egamma`。
已按照意见修改完毕。如果再进行吹毛求疵，将视为多数人对少数人的暴政。

2023-01-09 09:21 UTC, Great-designer commented on docs/math/constant.md
> +以下内置常数均为 `inline constexpr double` 类型，均为与相应无理数最接近的浮点数。以下给出常量名，以及该常量的介绍。
已更正。

2023-01-09 09:21 UTC, Great-designer commented on docs/math/constant.md
> +一般在 C 语言中取 $\pi$ 为 `acos(-1)`，只有这个值是最接近 $\pi$ 的浮点数。使用 `acos(-1)` 或者 `4*atan(1)` 写出来的 $\pi$ 是 $3.14159265358979310000$。
这个改不改都无所谓

2023-01-09 09:22 UTC, Great-designer commented on docs/math/constant.md
> +更多内容见弧度制与坐标系一文。
已删去。

2023-01-09 09:24 UTC, Great-designer commented
看情况改了改，等待@CoelacanthusHex 对于 ISO/IEC TS 18661-3 的建议。

2023-01-09 09:28 UTC, r-value commented on docs/math/constant.md
> +2. 使用 `std::numbers::sqrt2` 的形式。
建议 rebase 并在 commit message 中添加 `Co-Authored-By: Baoshuo Ren <i@baoshuo.ren>`.

2023-01-09 09:35 UTC, CoelacanthusHex commented on docs/math/constant.md
> +同时，GNU 拓展规定了一系列以 fN 和 fNx 为为后缀的不同精度的宏定义常量 [2](#user-content-fn-2-e92077518d669f2735cd5034a5c6ae51)，GNU 拓展规定的常量使用的是 ISO/IEC TS 18661-3 规定的机器无关浮点数类型。
这里用到的是 _FloatN 和 _FloatNx 两类类型固定宽度和编码格式的二进制浮点数类型，该标准包含的就是以几类固定宽度和编码格式的浮点数类型及各种标准库常量和函数的对应类型变体（如这里一样，使用 fN 和 fNx 作为对应的后缀）

2023-01-09 10:05 UTC, CoelacanthusHex commented on docs/math/constant.md
> +#endif /* _USE_MATH_DEFINES */
```suggestion
# define M_E        2.7182818284590452354   /* e */
# define M_LOG2E    1.4426950408889634074   /* log_2 e */
# define M_LOG10E   0.43429448190325182765  /* log_10 e */
# define M_LN2      0.69314718055994530942  /* log_e 2 */
# define M_LN10     2.30258509299404568402  /* log_e 10 */
# define M_PI       3.14159265358979323846  /* pi */
# define M_PI_2     1.57079632679489661923  /* pi/2 */
# define M_PI_4     0.78539816339744830962  /* pi/4 */
# define M_1_PI     0.31830988618379067154  /* 1/pi */
# define M_2_PI     0.63661977236758134308  /* 2/pi */
# define M_2_SQRTPI 1.12837916709551257390  /* 2/sqrt(pi) */
# define M_SQRT2    1.41421356237309504880  /* sqrt(2) */
# define M_SQRT1_2  0.70710678118654752440  /* 1/sqrt(2) */
```

glibc 包含的这个带注释的版本可能更好些

2023-01-09 10:05 UTC, CoelacanthusHex commented on docs/math/constant.md
> +同时，GNU 拓展规定了一系列以 fN 和 fNx 为为后缀的不同精度的宏定义常量 [2](#user-content-fn-2-e92077518d669f2735cd5034a5c6ae51)，GNU 拓展规定的常量使用的是 ISO/IEC TS 18661-3 规定的机器无关浮点数类型。
再补充一点吧，GNU 拓展还规定了以 `f` 和 `l` 作为后缀的版本的，分别对应 `float` 和 `long double` 类型

2023-01-09 10:27 UTC, Great-designer commented on docs/math/constant.md
> +$$
本条为“诉诸政治”，完全不是合作的态度。我不认为这可以和平解决。

2023-01-09 10:29 UTC, Great-designer commented on docs/math/constant.md
> +2. <https://www.gnu.org/software/libc/manual/html_node/Mathematical-Constants.html> [↩](#user-content-fnref-2-e92077518d669f2735cd5034a5c6ae51)
麻烦您进一步指正一下……

2023-01-09 10:29 UTC, Great-designer commented on docs/math/constant.md
> +#endif /* _USE_MATH_DEFINES */
合理

2023-01-09 10:32 UTC, Great-designer commented
我专门声明：我在本项目发的pr，如果管理员直接关了，并且照抄一份发出来，没有我的名字，我表示没有意见。仅限于本项目、我和pr。

2023-01-09 10:33 UTC, r-value commented on docs/math/constant.md
> +2. 使用 `std::numbers::sqrt2` 的形式。
> 不同意。

您没有立场说这句话.

> 但我允许其他人直接把我的这一篇搬走，且不必署名我的名字。

您对 wiki 的贡献均以 CC-BY-SA 3.0 协议进行许可.

2023-01-09 10:34 UTC, CoelacanthusHex commented on docs/math/constant.md
> +2. 使用 `std::numbers::sqrt2` 的形式。
另请注意，请注意，依据《中华人民共和国著作权法》，署名权是不允许放弃的权力

2023-01-09 10:43 UTC, Great-designer commented
因为涉及法律问题，本pr close

2023-01-09 10:44 UTC, closed without merging