feat(modifiable-mo-algo.md): 增添最优块长证明
OI-wiki/OI-wiki pull request #4615
Opened 2023-01-12 12:14 UTC by 2008verser

并采用了更为严谨的时间复杂度说明。

- [ ] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

2023-01-12 12:20 UTC, Enter-tainer commented on docs/misc/modifiable-mo-algo.md
>  ???+note "证明"
能否模仿之前的样式，把新添加的证明也收纳进折叠框中？

2023-01-12 12:25 UTC, 2008verser commented on docs/misc/modifiable-mo-algo.md
>  ???+note "证明"
这个没有收纳吗？

2023-01-12 12:26 UTC, 2008verser commented on docs/misc/modifiable-mo-algo.md
>  ???+note "证明"
是哪里格式不对

2023-01-12 12:27 UTC, Enter-tainer commented on docs/misc/modifiable-mo-algo.md
>  ???+note "证明"
我等下看看预览的效果。

折叠框内的内容，应该需要缩进四个空格才行

2023-01-12 12:27 UTC, 2008verser commented on docs/misc/modifiable-mo-algo.md
>  ???+note "证明"
噢

2023-01-12 13:00 UTC, Enter-tainer reviewed
其他部分 LGTM

2023-01-12 13:00 UTC, Enter-tainer commented on docs/misc/modifiable-mo-algo.md
> +    当上述式子取等时有最小值：
话说，基本不等式是 a=b 的时候取等号来着？不过算出来应该和这个差不多。。

2023-01-12 16:59 UTC, alphagocc requested changes

2023-01-12 16:59 UTC, alphagocc commented on docs/misc/modifiable-mo-algo.md
> +    根据基本不等式，当 $ms=\frac{n^2t}{s^2}$ 时原式有最小值。
可以仔细说明一下此处的原理吗，貌似不是很符合基本不等式的要求

2023-01-12 17:13 UTC, alphagocc commented on docs/misc/modifiable-mo-algo.md
> +    根据基本不等式，当 $ms=\frac{n^2t}{s^2}$ 时原式有最小值。
观察了一下您原来的过程
![image](https://user-images.githubusercontent.com/28982331/212134173-d9f47d0d-30e6-4b3b-b747-4e6fb3786c5c.png)
此处 $\sqrt{n^2mt}\leq ms\sqrt s+\frac{n^2t}{s\sqrt s}$ 最小
不意味着 $ms+\frac{n^2t}{s^2}$ 最小

2023-01-13 01:30 UTC, alphagocc requested changes

2023-01-13 01:30 UTC, alphagocc commented on docs/misc/modifiable-mo-algo.md
> +    当上述式子取等时 $s$ 有最小值。
此处 $ms\sqrt s+\frac{n^2t}{s\sqrt s}$ 最小
不意味着 $ms+\frac{n^2t}{s^2}$ 最小
更不意味着 $s$ 最小 (typo?

2023-01-13 01:30 UTC, alphagocc commented on docs/misc/modifiable-mo-algo.md
> +    当上述式子取等时 $s$ 有最小值。
感觉你没有理解我上一个 review 的意思

2023-01-13 01:32 UTC, 2008verser commented on docs/misc/modifiable-mo-algo.md
> +    当上述式子取等时 $s$ 有最小值。
这里的公式不是您写的这一个

2023-01-13 01:33 UTC, 2008verser commented on docs/misc/modifiable-mo-algo.md
> +    当上述式子取等时 $s$ 有最小值。
$2\sqrt{n^2mt}\leq ms\sqrt s+\frac{n^2t}{s\sqrt s}$ 取等， 意味右边的式子取最小值。
左边是没有 $s$ 的！

2023-01-13 01:34 UTC, 2008verser commented on docs/misc/modifiable-mo-algo.md
> +    当上述式子取等时 $s$ 有最小值。
确实

2023-01-14 02:27 UTC, 2008verser commented on docs/misc/modifiable-mo-algo.md
> +    当上述式子取等时 $s$ 有最小值。
已经改正

2023-01-14 02:31 UTC, alphagocc requested changes

2023-01-14 02:31 UTC, alphagocc commented on docs/misc/modifiable-mo-algo.md
> +    当这个式子取等号，$a$ 有最小值，也就是 $s$ 有最小值。
目标怎么是 $s$ 有最小值？

2023-01-14 02:45 UTC, alphagocc commented on docs/misc/modifiable-mo-algo.md
> +    当这个式子取等号，$a$ 有最小值，也就是 $s$ 有最小值。
此外，我个人认为此处证明需要求导

2023-01-14 02:48 UTC, 2008verser commented on docs/misc/modifiable-mo-algo.md
> +    当这个式子取等号，$a$ 有最小值，也就是 $s$ 有最小值。
是我搞混了

2023-01-14 02:48 UTC, 2008verser commented on docs/misc/modifiable-mo-algo.md
> +    当这个式子取等号，$a$ 有最小值，也就是 $s$ 有最小值。
我再看看

2023-01-14 03:05 UTC, 2008verser reviewed
刚才是我搞混了，要求的就是那个时间复杂度式子的最小值。直接取等计算一下就好了。

2023-01-14 03:07 UTC, alphagocc requested changes

2023-01-14 03:07 UTC, alphagocc commented on docs/misc/modifiable-mo-algo.md
> +    当此式取等号时，时间复杂度式子有最小值。所以我们要解这一方程：
取等号的时候，不等式左边有s右边有s，这正确吗

2023-01-14 03:09 UTC, 2008verser commented on docs/misc/modifiable-mo-algo.md
> +    当此式取等号时，时间复杂度式子有最小值。所以我们要解这一方程：
等同于把左边s乘没，再取等号，再两侧同除以s。
我认为可以的。

2023-01-14 03:13 UTC, Enter-tainer commented on docs/misc/modifiable-mo-algo.md
> +    设 $x=ms,y=\frac{n^2t}{s^2}$，根据基本不等式 $\sqrt{xy}\leq\frac{x+y}{2}$，可以得到：
想起来高中时候学的，基本不等式应该是有 一正二定三相等的条件，这个感觉不满足“二定”。因为x和y的和/积都不是定值

2023-01-14 03:15 UTC, alphagocc commented on docs/misc/modifiable-mo-algo.md
> +    当此式取等号时，时间复杂度式子有最小值。所以我们要解这一方程：
$2\sqrt{\frac{n^2mt}{s}}\leq ms+\frac{n^2t}{s^2}$
你说乘一下
那么就有  $2\sqrt{n^2mt}\leq ms\sqrt s+\frac{n^2t}{s\sqrt s}$
此时得到了  $ms\sqrt s+\frac{n^2t}{s\sqrt s}$ 的最小值
与原目标最小值的式子不同

2023-01-14 03:18 UTC, 2008verser commented on docs/misc/modifiable-mo-algo.md
> +    设 $x=ms,y=\frac{n^2t}{s^2}$，根据基本不等式 $\sqrt{xy}\leq\frac{x+y}{2}$，可以得到：
疏忽了...

2023-01-14 03:49 UTC, 2008verser commented
找到问题了。
分块后一“组”询问的端点可以被构造成乱序，共会移动 $O(s^2)$ 次，并非原本写的 $O(s)$ 。

2023-01-14 03:52 UTC, 2008verser commented
所以这好像跟普通莫队不一样……不能直接基本不等式。

2023-01-28 02:55 UTC, 2008verser commented
求导可以

2023-01-28 07:12 UTC, alphagocc requested changes

2023-01-28 07:12 UTC, alphagocc commented on docs/misc/modifiable-mo-algo.md
> +    设 $s=s_0+\epsilon,\epsilon\in \mathbb{R}$?。
不必要设什么 $\epsilon$ 证明

2023-01-28 07:12 UTC, alphagocc commented on docs/misc/modifiable-mo-algo.md
> +    所以 $s=s_0$?处确为极小。
多余的问号是怎么回事？

2023-01-28 07:18 UTC, alphagocc commented on docs/misc/modifiable-mo-algo.md
> +    设 $s=s_0+\epsilon,\epsilon\in \mathbb{R}$?。
此处的连续性是显然的
况且你设了 $\epsilon \in \mathbb{R}$ 这个真的对吗

2023-01-28 11:42 UTC, yanboishere submitted a review, later dismissed

2023-01-28 13:42 UTC, alphagocc commented
好像还有多余的问号

2023-01-28 13:48 UTC, alphagocc submitted a review, later dismissed

2023-01-28 13:53 UTC, dbxxx-oi commented
这个最优块长证明默认不展开会不会好一点（

2023-01-28 13:58 UTC, Enter-tainer commented on docs/misc/modifiable-mo-algo.md
> +    也就是当块长取 $\frac{n^\frac23t^\frac13}{m^\frac13}$ 时有最优时间复杂度 $O(n^\frac23m^\frac23t^\frac13)$ 。
按上面求出来的，块长不应该是 sqrt[3](1/2) * 你写的这个 吗

2023-01-28 14:00 UTC, 2008verser commented on docs/misc/modifiable-mo-algo.md
> +    也就是当块长取 $\frac{n^\frac23t^\frac13}{m^\frac13}$ 时有最优时间复杂度 $O(n^\frac23m^\frac23t^\frac13)$ 。
哪有问题，我没明白。
s就是块长啊，把sqrt3拆掉好看一点罢了

2023-01-28 14:02 UTC, Enter-tainer commented on docs/misc/modifiable-mo-algo.md
> +    也就是当块长取 $\frac{n^\frac23t^\frac13}{m^\frac13}$ 时有最优时间复杂度 $O(n^\frac23m^\frac23t^\frac13)$ 。
> 哪有问题，我没明白。

<img width="413" alt="image" src="https://user-images.githubusercontent.com/25521218/215270529-fb12dd63-a0bd-418f-921f-62554f2b6de2.png">

就是丢了个常数。常数丢掉之后，还是极值点吗

2023-01-28 14:04 UTC, Enter-tainer commented on docs/misc/modifiable-mo-algo.md
> +    也就是当块长取 $\frac{n^\frac23t^\frac13}{m^\frac13}$ 时有最优时间复杂度 $O(n^\frac23m^\frac23t^\frac13)$ 。
另外我刚才验算了一下，这个极值点确实是极小值点

2023-01-28 14:05 UTC, 2008verser commented on docs/misc/modifiable-mo-algo.md
> +    也就是当块长取 $\frac{n^\frac23t^\frac13}{m^\frac13}$ 时有最优时间复杂度 $O(n^\frac23m^\frac23t^\frac13)$ 。
这个常数……
OI一般不管吧。。

2023-01-28 14:07 UTC, Enter-tainer commented on docs/misc/modifiable-mo-algo.md
> +    也就是当块长取 $\frac{n^\frac23t^\frac13}{m^\frac13}$ 时有最优时间复杂度 $O(n^\frac23m^\frac23t^\frac13)$ 。
事实是，如果把这个常数扔了，带进去导数就不是零了。

2023-01-28 14:07 UTC, 2008verser commented on docs/misc/modifiable-mo-algo.md
> +    也就是当块长取 $\frac{n^\frac23t^\frac13}{m^\frac13}$ 时有最优时间复杂度 $O(n^\frac23m^\frac23t^\frac13)$ 。
抛开常数带回时间复杂度去算也还是一个常数。
时间复杂度不管这个。

2023-01-28 14:08 UTC, Enter-tainer commented on docs/misc/modifiable-mo-algo.md
> +    也就是当块长取 $\frac{n^\frac23t^\frac13}{m^\frac13}$ 时有最优时间复杂度 $O(n^\frac23m^\frac23t^\frac13)$ 。
这玩意是 cubic_root(2) = 1.25992104989 ，好像确实区别不是很大。。

2023-01-28 14:09 UTC, 2008verser commented
讨论怎么不见了

2023-01-28 14:09 UTC, Enter-tainer commented on docs/misc/modifiable-mo-algo.md
> +    也就是当块长取 $\frac{n^\frac23t^\frac13}{m^\frac13}$ 时有最优时间复杂度 $O(n^\frac23m^\frac23t^\frac13)$ 。
> 抛开常数带回时间复杂度去算也还是一个常数。

好像还真是，那感觉这个好神奇啊，感觉随便取 s0 的倍数都是最优复杂度。这合理吗

2023-01-28 14:09 UTC, Enter-tainer approved these changes

2023-01-28 14:10 UTC, alphagocc commented
> 讨论怎么不见了

你刚才点到 resolved 了吧

2023-01-28 14:11 UTC, 2008verser commented
> 

现在好了

2023-01-28 14:11 UTC, Enter-tainer commented on docs/misc/modifiable-mo-algo.md
> +    常说的 $O(n^\frac35)$ 便是把 $n,m,t$ 当做同数量级的时间复杂度。
这个应该是 三分之五 吧

2023-01-28 14:12 UTC, Enter-tainer commented on docs/misc/modifiable-mo-algo.md
> +    也就是当块长取 $\frac{n^\frac23t^\frac13}{m^\frac13}$ 时有最优时间复杂度 $O(n^\frac23m^\frac23t^\frac13)$ 。
emm感觉也算合理，resolve了

2023-01-28 14:14 UTC, Enter-tainer approved these changes
辛苦！

2023-01-28 14:15 UTC, alphagocc approved these changes

2023-01-28 14:16 UTC, 2008verser commented
我的错误太多了[笑哭]
辛苦各位

2023-01-28 14:16 UTC, Enter-tainer approved these changes

2023-01-28 15:49 UTC, alphagocc approved these changes
LGTM

2023-01-28 15:49 UTC, merged