feat(quadratic.md)：一些漏网之鱼
OI-wiki/OI-wiki pull request #4619
Opened 2023-01-13 04:15 UTC by Great-designer

再仔细检查检查……

2023-01-17 12:15 UTC, inclyc commented on docs/math/number-theory/quadratic.md
> +**主理想整环**：每一个理想都是主理想的整环。一个重要的性质是，它满足 **裴蜀定理**。
改 \mathrm 看起来和这个更改没什么关系。如果此 PR 能够管好自己分内的事情更好，建议分成两个 PR

2023-01-18 03:37 UTC, Great-designer commented on docs/math/number-theory/quadratic.md
> +**主理想整环**：每一个理想都是主理想的整环。一个重要的性质是，它满足 **裴蜀定理**。
不建议这种刷PR数量的形式主义做法。具体问题具体分析，一次能做到药到病除是最好的，确实做不到的再说拆分问题。

关于这个可以讨论一下，大家认为写成“Bezout 定理”好还是“裴蜀定理”好？我觉得没啥区别，这里看上下文也许写成中文会显得更加整齐一些。不知大家怎么看。

2023-01-24 03:33 UTC, yusancky commented on docs/math/number-theory/quadratic.md
> +**主理想整环**：每一个理想都是主理想的整环。一个重要的性质是，它满足 **裴蜀定理**。
> 关于这个可以讨论一下，大家认为写成“Bezout 定理”好还是“裴蜀定理”好？我觉得没啥区别，这里看上下文也许写成中文会显得更加整齐一些。不知大家怎么看。

感觉用「裴蜀定理」确实更舒服。

2023-01-24 08:23 UTC, inclyc requested changes
分成两个功能独立的PR。

2023-01-24 10:21 UTC, Great-designer commented
> 分成两个功能独立的PR。

此为形式主义。不如请您来干

2023-01-24 10:46 UTC, Enter-tainer commented
感觉这个case分不分都行，因为更改很小，基本不可能造成冲突

2023-01-24 10:50 UTC, inclyc commented
> 感觉这个case分不分都行，因为更改很小，基本不可能造成冲突

如果只改 mathrm 我觉得可以，但是改裴蜀定理我觉得是多余的。

如果这是两个 PR 的话，我会 Approve 一个而在另一个讨论

2023-01-24 10:51 UTC, Enter-tainer commented
这个一共只有 27 行的diff，感觉无论拆不拆都不会影响review

2023-01-24 10:51 UTC, inclyc commented
> 这个一共只有 27 行的diff，感觉无论拆不拆都不会影响review

行。

2023-01-24 10:56 UTC, inclyc commented
顺便一提绝大多数社区都鼓励分开各个 patch 的功能。这不是形式主义，而是经过检验的社区实践

> not contain any unrelated changes

Link: https://llvm.org/docs/Contributing.html#how-to-submit-a-patch

> Don't mix together changes made for different reasons. 

Link: https://gcc.gnu.org/contribute.html

> Separate each logical change into a separate patch.

https://www.kernel.org/doc/html/v4.14/process/submitting-patches.html

2023-01-24 10:57 UTC, Enter-tainer commented
> 顺便一提绝大多数社区都鼓励分开各个 patch 的功能。这不是形式主义，而是经过检验的社区实践

理解，但是就这个pr而言，做的基本上就是typo fix之类的事情。感觉没太必要深究。。。

2023-01-24 10:58 UTC, inclyc approved these changes

2023-01-24 11:02 UTC, inclyc commented
Note: 隐藏了一些 offtopic comments, 在讨论本 PR 的功能是否独立，我们的共识是没必要纠结这个小 typo patch

2023-01-24 13:09 UTC, Tiphereth-A commented
Bézout 定理的主流音译方案似乎有裴蜀定理和贝祖定理两种，个人感觉后者更贴发音一些

2023-01-24 13:23 UTC, Tiphereth-A commented
另外我不认为修改 Bezout 定理这个是有必要的，毕竟音译方案可以有很多 🤔

2023-01-24 13:24 UTC, Enter-tainer commented
@Tiphereth-A 和这里对齐吧 https://oi-wiki.org/math/number-theory/bezouts/

2023-01-24 13:30 UTC, Tiphereth-A commented
> @Tiphereth-A 和这里对齐吧 https://oi-wiki.org/math/number-theory/bezouts/
> 
> <blockquote><div><strong><a href="https://oi-wiki.org/math/number-theory/bezouts/">裴蜀定理 - OI Wiki</a></strong></div><div>OI Wiki 是一个编程竞赛知识整合站点，提供有趣又实用的编程竞赛知识以及其他有帮助的内容，帮助广大编程竞赛爱好者更快更深入地学习编程竞赛</div></blockquote>

那感觉更好的方案应该是插个内链而不是做这种修改 🤔

2023-01-24 13:35 UTC, Tiphereth-A commented on docs/math/number-theory/quadratic.md
> +**主理想整环**：每一个理想都是主理想的整环。一个重要的性质是，它满足 **裴蜀定理**。
```suggestion
**主理想整环**：每一个理想都是主理想的整环。一个重要的性质是，它满足 **[Bezout 定理](./bezouts.md)**。
```

2023-01-24 13:37 UTC, inclyc commented
我们有无一个统一的标准规定用英文名还是其翻译？

2023-01-24 13:38 UTC, inclyc commented
看起来 @Great-Designer 已经在这方面做了不少修改

2023-01-24 13:49 UTC, Great-designer commented
楼上提到了特别多的意见。这似乎已经是一个社会学实验，最早我写这些文章的时候译名完全是随便写的，想起哪个用哪个，而只能通过第一稿，后续却不可以改动。诸如“Bezout定理”当初是我写的，“裴蜀定理”当初也仍旧是我写的。

「多做多错，少做少错，不做不错。」很多时候错的多往往是因为做的多。不过问题并不大，只需要后续调整过来就行。

另注：如果遵照原书写的话，Bezout应写作Bézout，e上有法文闭音符。因为是法国数学家艾蒂安贝祖（Étienne Bézout），音译的话应该按照法文发音。

> 我们有无一个统一的标准规定用英文名还是其翻译？

楼上提了个关键的问题。一个完备的wiki应当有一套完备的译名标准，诸如游戏/动画类wiki都是这么做的。即：

- 用统一的译名，那么Bézout这个人都被译为同一套汉字“示例”，并配一个统一的译名表。
- 统一用原始语言写法，即写作Bézout。

这应该是一个NFC议案。

2023-01-24 14:02 UTC, Great-designer commented
讲一个典故：定义数学常数 $\pi$ 的人是欧拉，但是欧拉把 $\pi$ 在不同的地方也是想起多少就用多少，有时定义为 3.14，有时定义为 6.28，有时定义为 1.57。

参见3b1b《【官方双语】“π”=圆周率的由来：欧拉差点把“π”设置为6.283185了吗？》：https://www.bilibili.com/video/BV1EW411p727

后人在 $\pi$  $\tau$ 之争中都拿欧拉当挡箭牌，已经作古的欧拉成了“自己反对自己”。这就是最开始书写的时候不注意，从而引发的麻烦。

一本合格的著作也会书末配一个符号表或译名表，避免此类争议，并规定行文中只能使用一种。

举一个同为wiki的bulbapedia的例子，在每个页面下方都会给出词条的译名。随便举一个页面：
https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_Sword_and_Shield

可以看到文末都有该词条的译名。

<html>
<body>
<!--StartFragment-->

Language | Title
-- | --
Japanese | ポケットモンスター ソード・シールド
Chinese | Cantonese | 寶可夢 劍／盾
Mandarin | 寶可夢 劍／盾宝可梦 剑／盾
French | Canada | Pokémon Sword et Shield
Europe | Pokémon Épée et Bouclier
German | Pokémon Schwert und Schild
Italian | Pokémon Spada e Scudo
Korean | 포켓몬스터 소드・실드
Spanish | Pokémon Espada y Escudo

<!--EndFragment-->
</body>
</html>

作为基于日文游戏的百科，英文网站也不得不在译名上下功夫，搞错译名是可怕的。

无论是数学或者计算机或者什么科学，也都是国际化的，不可能全是中国人，势必也会遇到这种问题。所以译名表或者译名使用规则也必然需要统一。

包括定理等专有名词也是一样，虽然市面上叫法甚多，但显然还是统一了最好。

2023-01-24 14:13 UTC, Great-designer commented
另注，作为一个wiki，甚至可以在适当的位置顺便介绍一下艾蒂安贝祖（Étienne Bézout）这个人的典故，如果查得到的话。这会使得读者阅读时产生亲切感，仿佛这个生疏的人活灵活现想和人交朋友，而不是看到生疏名词的畏惧感。

2023-01-24 14:14 UTC, Great-designer commented on docs/math/number-theory/quadratic.md
> +**主理想整环**：每一个理想都是主理想的整环。一个重要的性质是，它满足 **裴蜀定理**。
随便。现在看来这个已经不是重要的了

2023-01-24 14:32 UTC, Great-designer commented
至于本pr究竟怎么办，其实真的不重要了。

引出一个新的问题已经足够重要。本pr本身也是i和e的标准化讨论搞出来的，在标准化之前也是因为当初写的时候注重了内容，而没有注重形式。

内容和形式是同等重要的。目前内容已经完备了，我们从一个议案走到下一个议案，这是一个大进步。

2023-01-24 15:08 UTC, Tiphereth-A submitted a review, later dismissed

2023-01-24 15:32 UTC, yusancky approved these changes

2023-01-25 05:18 UTC, inclyc requested changes

2023-01-25 05:18 UTC, inclyc commented on docs/math/number-theory/quadratic.md
> +**主理想整环**：每一个理想都是主理想的整环。一个重要的性质是，它满足 **[Bezout 定理](./bezouts.md)**。
我建议先不要merge，把这个修改删掉，等RFC讨论出共识再说。其余部分没问题

2023-01-25 05:21 UTC, inclyc commented
Link #4650

2023-01-25 07:33 UTC, Tiphereth-A commented on docs/math/number-theory/quadratic.md
> +**主理想整环**：每一个理想都是主理想的整环。一个重要的性质是，它满足 **[Bezout 定理](./bezouts.md)**。
> 我建议先不要merge，把这个修改删掉，等RFC讨论出共识再说。其余部分没问题

所以这里只是先加了个内链

当然, 我也赞同把这个分到另一个 PR 中

2023-01-25 08:10 UTC, inclyc commented on docs/math/number-theory/quadratic.md
> +**主理想整环**：每一个理想都是主理想的整环。一个重要的性质是，它满足 **[Bezout 定理](./bezouts.md)**。
> 分到另一个 PR 中

晚上我来做这事吧

2023-01-25 10:14 UTC, inclyc approved these changes

2023-01-25 13:13 UTC, Tiphereth-A approved these changes

2023-01-25 13:18 UTC, merged