feat: 增加 Pull Request 模板中 CLA 的英文翻译
OI-wiki/OI-wiki pull request #4625
Opened 2023-01-15 02:19 UTC by renbaoshuo

- [x] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

2023-01-15 02:20 UTC, Enter-tainer approved these changes
cool

2023-01-15 02:20 UTC, yizr-cnyali submitted a review, later dismissed
LGTM,thx!

2023-01-15 02:21 UTC, Ir1d approved these changes

2023-01-15 02:25 UTC, Great-designer commented
好！

2023-01-15 02:27 UTC, Ir1d approved these changes

2023-01-15 02:27 UTC, yizr-cnyali approved these changes

2023-01-15 02:32 UTC, Enter-tainer requested changes

2023-01-15 02:32 UTC, Enter-tainer commented on .github/pull_request_template.md
> +- [ ] 我已认真阅读 [贡献指南](https://github.com/OI-wiki/OI-wiki/blob/master/.github/CONTRIBUTING.md) 和 [社区公约](https://github.com/OI-wiki/OI-wiki/blob/master/CODE_OF_CONDUCT.md)，并遵循了 [如何参与](https://oi-wiki.org
好像coc是中文的？

2023-01-17 10:53 UTC, yanboishere approved these changes

2023-03-05 00:20 UTC, closed without merging