fix(math/pollard-rho.md):修正了一些表达
OI-wiki/OI-wiki pull request #4632
Opened 2023-01-18 07:04 UTC by 383494

- [ ] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

2023-01-18 07:07 UTC, Great-designer commented
合理

2023-01-18 07:31 UTC, inclyc commented on docs/math/number-theory/pollard-rho.md
> +给定一个正整数 $N \in \mathbf{N}_{+}$，试快速找到它的一个非平凡因数。
可以考虑解释一下什么是非平凡，或者给出相关链接

2023-01-18 07:31 UTC, inclyc commented on docs/math/number-theory/pollard-rho.md
> +考虑朴素算法，因数是成对分布的，$N$ 的所有非平凡因数可以被分成两块，即 $(1,\sqrt N]$ 和 $[\sqrt N+1,N)$。只需要把 $(1,\sqrt N]$ 里的数遍历一遍，再根据除法就可以找出至少两个因数了。这个方法的时间复杂度为 $O(\sqrt N)$。
```suggestion
考虑朴素算法，因数是成对分布的，$N$ 的所有非平凡因数可以被分成两块，即 $[2, \sqrt N]$ 和 $[\sqrt N+1,N)$。只需要把 $[2, \sqrt N]$ 里的数遍历一遍，再根据除法就可以找出至少两个因数了。这个方法的时间复杂度为 $O(\sqrt N)$。
```

左闭区间或许看起来更好

2023-01-18 07:31 UTC, inclyc commented on docs/math/number-theory/pollard-rho.md
> +最简单的算法即为从 $(1,\sqrt N]$ 进行遍历。
```suggestion
最简单的算法即为从 $[2, \sqrt N]$ 进行遍历。
```

2023-01-18 07:36 UTC, 383494 commented on docs/math/number-theory/pollard-rho.md
> +考虑朴素算法，因数是成对分布的，$N$ 的所有非平凡因数可以被分成两块，即 $(1,\sqrt N]$ 和 $[\sqrt N+1,N)$。只需要把 $(1,\sqrt N]$ 里的数遍历一遍，再根据除法就可以找出至少两个因数了。这个方法的时间复杂度为 $O(\sqrt N)$。
有理，那$[\sqrt N+1,N)$ 要不要写成闭区间

2023-01-18 07:42 UTC, Great-designer commented on docs/math/number-theory/pollard-rho.md
> +给定一个正整数 $N \in \mathbf{N}_{+}$，试快速找到它的一个非平凡因数。
这是一个数论上的非常常见的表达。对于一个整数 n，1和n本身称为“平凡因子”或“平凡的因数”。

如果允许负数的话，-1和-n也是平凡的因数，当然在解实际问题的时候一般默认因数在正整数范围内。关于有关正因数讨论的默认习惯，详见“数论基础”页面。

2023-01-18 07:43 UTC, 383494 commented on docs/math/number-theory/pollard-rho.md
> +考虑朴素算法，因数是成对分布的，$N$ 的所有非平凡因数可以被分成两块，即 $(1,\sqrt N]$ 和 $[\sqrt N+1,N)$。只需要把 $(1,\sqrt N]$ 里的数遍历一遍，再根据除法就可以找出至少两个因数了。这个方法的时间复杂度为 $O(\sqrt N)$。
写成开区间好像更能体现“非平凡”？

2023-01-18 07:46 UTC, 383494 commented on docs/math/number-theory/pollard-rho.md
> +给定一个正整数 $N \in \mathbf{N}_{+}$，试快速找到它的一个非平凡因数。
在“数论基础”一节中补充会不会更好

2023-01-18 09:16 UTC, Great-designer commented on docs/math/number-theory/pollard-rho.md
> +给定一个正整数 $N \in \mathbf{N}_{+}$，试快速找到它的一个非平凡因数。
> 在“数论基础”一节中补充，这里给个链接会不会更好

可以补充。链接的话……对于做数学的或者对数论有所了解的存在认为必要性不太大的可能性。

2023-01-18 09:39 UTC, 383494 commented on docs/math/number-theory/pollard-rho.md
> +给定一个正整数 $N \in \mathbf{N}_{+}$，试快速找到它的一个非平凡因数。
那加个前置知识？

2023-01-18 09:48 UTC, Great-designer reviewed
看了看前后文格式，使用了“如果没有特殊说明”的加粗表述方法。

在北大版《初等数论》（潘承洞、潘承彪著）中使用了“显然”、“非显然”的翻译方法。“平凡”、“非平凡”应该也是翻译自同一个外文词汇，可以通用。

2023-01-18 09:48 UTC, Great-designer commented on docs/math/number-theory/basic.md
> +对于一个整数 $n$，$1$ 和 $n$ 本身称为“平凡因子”或“平凡的因数”，其余因数称为“非平凡因数”。如果允许负数的话，$-1$ 和 $-n$ 也是平凡的因数，当然在解实际问题的时候一般默认因数在正整数范围内。
```suggestion

```

2023-01-18 09:48 UTC, Great-designer commented on docs/math/number-theory/basic.md
```suggestion
- $a\mid b\iff-a\mid b\iff a\mid-b\iff|a|\mid|b|$
- $a\mid b\land b\mid c\implies a\mid c$
- $a\mid b\land a\mid c\iff\forall x,y\in\mathbf{Z}, a\mid(xb+yc)$
- $a\mid b\land b\mid a\implies b=\pm a$
- 设 $m\ne0$，那么 $a\mid b\iff ma\mid mb$。
- 设 $b\ne0$，那么 $a\mid b\implies|a|\le|b|$。
- 设 $a\ne0,b=qa+c$，那么 $a\mid b\iff a\mid c$。
$0$ 是所有非 $0$ 整数的倍数。对于整数 $b\ne0$，$b$ 的约数只有有限个。
显然约数（显然因数、平凡约数）：对于整数 $b\ne0$，$\pm1$、$\pm b$ 是 $b$ 的显然约数。当 $b=\pm1$ 时，$b$ 只有两个显然约数。
对于整数 $b\ne0$，$b$ 的其他约数称为真约数（真因数、非显然约数、非平凡因数）。
约数的性质：
- 设整数 $b\ne0$。当 $d$ 遍历 $b$ 的全体约数的时候，$\dfrac{b}{d}$ 也遍历 $b$ 的全体约数。
- 设整数 $b>0$，则当 $d$ 遍历 $b$ 的全体正约数的时候，$\dfrac{b}{d}$ 也遍历 $b$ 的全体正约数。

在具体问题中，**如果没有特别说明，约数总是指正约数。**
```

2023-01-18 09:50 UTC, Great-designer commented on docs/math/number-theory/pollard-rho.md
> +给定一个正整数 $N \in \mathbf{N}_{+}$，试快速找到它的一个非平凡因数。
> 那加个前置知识？

整个数论目录默认的前置知识应该就是“数论基础”吧……我不太清楚前置知识要不要写“数论基础”。当初书写“数论基础”这个页面的目的就是避免整个网站行文出现数论方面的此类争议。

如果看后文看不懂，或许应该看看前文……

2023-01-18 11:59 UTC, inclyc commented on docs/math/number-theory/pollard-rho.md
> +给定一个正整数 $N \in \mathbf{N}_{+}$，试快速找到它的一个非平凡因数。
> 这是一个数论上的非常常见的表达

您说的非常正确，但不影响我们在这里的建议，我认为不应该默认阅读此文的高中生有设计师一样的博学多才。

> 链接的话……对于做数学的或者对数论有所了解的存在认为必要性不太大的可能性。

OI-wiki 不是做数学的，还是对新手友好一点，这不是写专著

2023-01-18 12:00 UTC, inclyc commented on docs/math/number-theory/pollard-rho.md
> +考虑朴素算法，因数是成对分布的，$N$ 的所有非平凡因数可以被分成两块，即 $(1,\sqrt N]$ 和 $[\sqrt N+1,N)$。只需要把 $(1,\sqrt N]$ 里的数遍历一遍，再根据除法就可以找出至少两个因数了。这个方法的时间复杂度为 $O(\sqrt N)$。
右侧区间一般写开区间，左侧一般写闭区间

2023-01-18 12:03 UTC, inclyc commented
分成两个PR写，一个写平凡因数，现在这个链接可以留一个 FIXME.

2023-01-18 12:08 UTC, 383494 commented on docs/math/number-theory/pollard-rho.md
> +给定一个正整数 $N \in \mathbf{N}_{+}$，试快速找到它的一个非平凡因数。
> OI-wiki 不是做数学的，还是对新手友好一点，这不是写专著

对比了一下前后效果，认为在第一次出现的地方加链接
- 可以方便没看过数论基础/看过但不太熟悉的人
- 也不会影响其他人的阅读体验

@Great-designer 您的观点？

2023-01-18 13:01 UTC, 383494 commented
> 分成两个PR写，一个写平凡因数，现在这个链接可以留一个 FIXME.

#4634

2023-01-18 15:20 UTC, inclyc approved these changes

2023-01-19 00:20 UTC, yanboishere submitted a review, later dismissed

2023-01-19 08:16 UTC, Tiphereth-A requested changes

2023-01-19 08:16 UTC, Tiphereth-A commented on docs/math/number-theory/pollard-rho.md
> +对于一个数 $n$，用[Miller Rabin 算法]\(./prime.md#miller-rabin - 素性测试）判断是否为素数，如果是就可以直接返回了，否则用 Pollard-Rho 算法找一个因子 $p$，将 $n$ 除去因子 $p$。再递归分解 $n$ 和 $p$，用 Miller Rabin 判断是否出现质因子，并用 max_factor 更新就可以求出最大质因子了。由于这个题目
```suggestion
对于一个数 $n$，用 [Miller Rabin 算法](./prime.md#miller-rabin-素性测试) 判断是否为素数，如果是就可以直接返回了，否则用 Pollard-Rho 算法找一个因子 $p$，将 $n$ 除去因子 $p$。再递归分解 $n$ 和 $p$，用 Miller Rabin 判断是否出现质因子，并用 max_factor 更新就可以求出最大质因子了。由于这个题目的数据过于庞大，用 Floyd 判环的方法是不够的，这里采用倍增优化的方法。
```

2023-01-19 08:16 UTC, Tiphereth-A commented on docs/math/number-theory/pollard-rho.md
> +对于一个数 $n$，用[Miller Rabin 算法]\(./prime.md#miller-rabin - 素性测试）判断是否为素数，如果是就可以直接返回了，否则用 Pollard-Rho 算法找一个因子 $p$，将 $n$ 除去因子 $p$。再递归分解 $n$ 和 $p$，用 Miller Rabin 判断是否出现质因子，并用 max_factor 更新就可以求出最大质因子了。由于这个题目
请 revert 此处的修改, 不要破坏内链引用

2023-01-19 09:00 UTC, Tiphereth-A approved these changes

2023-01-19 09:34 UTC, inclyc approved these changes
LGTM

关于标题我觉得可以用一些更具体的描述 ”修正了一些表达“ ？是什么表达呢
```diff
- fix(math/pollard-rho.md):修正了一些表达
+ fix(math/pollard-rho.md):修正区间表示和说明生日悖论天数
```

2023-01-19 09:37 UTC, 383494 commented
> LGTM
> 
> 关于标题我觉得可以用一些更具体的描述 ”修正了一些表达“ ？是什么表达呢
> 
> ```diff
> - fix(math/pollard-rho.md):修正了一些表达
> + fix(math/pollard-rho.md):修正区间表示和说明生日悖论天数
> ```

fixed

2023-01-19 10:45 UTC, merged