feat(check-characters): Check md file for radicals
OI-wiki/OI-wiki pull request #4635
Opened 2023-01-19 12:52 UTC by yusancky

History: yusancky/OI-wiki#30

Workflow Preview: yusancky/OI-wiki#29 ( https://github.com/yusancky/OI-wiki/actions/runs/3958324150/jobs/6779754543 )

Add a new GitHub Actions workflow which checks for CJK radicals or strokes in Markdown files. If a CJK radical or stroke (_or more_) is present, it will list all the characters to be replaced in order by file (_with the corresponding Unicode encoding_).

- [x] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

2023-01-19 12:59 UTC, yusancky commented
CC: @CoelacanthusHex @Enter-tainer

2023-01-19 13:02 UTC, CoelacanthusHex approved these changes
LGTM

2023-01-19 13:02 UTC, diauweb commented
另，我认为 `find_jk.py` 可以移除了

2023-01-19 13:04 UTC, Enter-tainer commented on scripts/cjk-map.json
> +{
话说这个列表全吗

2023-01-19 13:04 UTC, Enter-tainer commented on scripts/check-characters.py
> +    raise ChangeNeeded('Some characters need to be changed. ')
这里可以考虑输出为 github action annotation 的格式？不过不做也没关系

效果类似这样 
![image](https://user-images.githubusercontent.com/25521218/213449890-aff7dcdf-e4b3-4c48-a751-dfca199210d6.png)

2023-01-19 13:04 UTC, Enter-tainer commented on scripts/check-characters.py
> +    raise ChangeNeeded('Some characters need to be changed. ')
文档可以看这里 https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-error-message

2023-01-19 13:15 UTC, Great-designer commented on scripts/cjk-map.json
> +{
完全全的表应该是做不到的吧……Unicode里面的字太多了，覆盖常用的应该就行

2023-01-19 13:17 UTC, Enter-tainer commented on scripts/cjk-map.json
> +{
这个东西本来就是为了处理各种极端情况的，当然是越全越好。

不过我还是好奇这个表是怎么来的..

2023-01-19 13:22 UTC, CoelacanthusHex commented on scripts/cjk-map.json
> +{
康熙部首在Unicode是专门的区块，很容易找到全部，只是要一个个填对应的正常汉字，比较麻烦

2023-01-19 13:24 UTC, CoelacanthusHex commented on scripts/cjk-map.json
> +{
U+2F00..U+2FD5 即为所有康熙部首

2023-01-19 13:26 UTC, CoelacanthusHex commented on scripts/cjk-map.json
> +{
看起来这个表还收录了一些异体字

2023-01-19 13:27 UTC, Enter-tainer commented on scripts/cjk-map.json
> +{
0xd5 = 213，看了这个表已经比康熙部首还多了

2023-01-19 13:27 UTC, yusancky commented on scripts/cjk-map.json
> +{
> 话说这个列表全吗

我直接使用了 [上次进行替换时使用的 Go 项目的片段](https://github.com/mochi-co/equivalent-unified-ideograph/blob/51466e2b4af05235d9f5e8aabb67d4ddc8bdbca6/static.go#L1746-L2095)。

它的仓库中已有 [EquivalentUnifiedIdeograph-14.0.0.txt \(unicode.org\)](https://www.unicode.org/Public/14.0.0/ucd/EquivalentUnifiedIdeograph.txt)， 看起来应该是从该文件提取出的。

此外，在最初查找相关资料时，我在 https://blog.hawkhai.com/blog/2021/03/14/Equivalent-Unified-Ideograph 也找到了不同（_指顺序等，未对具体内容进行核对_）的 JSON 文件。[^1]感觉可以尝试排序 JSON 后具体逐一比较。

[^1]: 「不同的 JSON 文件」是指顺序、使用版本（博文中使用 Unicode 13.0.0 版，但差异应该较小）等有出入，未对详细内容进行核对。

2023-01-19 13:29 UTC, CoelacanthusHex commented on scripts/cjk-map.json
> +{
Unicode共收录部首康熙部首214+中日韩部首补充115=329个，表中收录348个，不知剩下的19个属于什么

2023-01-19 13:31 UTC, CoelacanthusHex commented on scripts/cjk-map.json
> +{
那看起来剩下19个是笔画

2023-01-19 13:54 UTC, yusancky commented on scripts/check-characters.py
> +    raise ChangeNeeded('Some characters need to be changed. ')
> **Note**
> 
> 以下内容包含个人理解。如果您认为不正确，欢迎指出。

其实以前尝试过 [作业摘要（Job Summary）](https://docs.github.com/zh/actions/using-workflows/workflow-commands-for-github-actions#%E6%B7%BB%E5%8A%A0%E4%BD%9C%E4%B8%9A%E6%91%98%E8%A6%81)，但大概是因为我操作不当，摘要总只显示第一行，以失败而告终。

出现 CJK 部首问题，可以使用编辑器的替换工具快速解决，因此标记文件和要修改的字即可定位问题，我觉得不必额外使用工作流命令信息。

2023-01-19 13:55 UTC, Enter-tainer approved these changes

2023-01-19 16:29 UTC, alphagocc requested changes

2023-01-19 16:29 UTC, alphagocc commented on scripts/cjk-map.json
> +  "⺕": "彐",
根据 https://www.unicode.org/Public/15.0.0/ucd/EquivalentUnifiedIdeograph.txt
U+2E95 现在的对应字为 扩展C区 的 U+2B739

2023-01-19 16:43 UTC, billchenchina requested changes

2023-01-19 16:43 UTC, billchenchina commented on scripts/cjk-map.json
> +{
那就是这个列表不会发生变化的意思吗？🤔

2023-01-19 16:43 UTC, billchenchina commented on scripts/cjk-map.json
> +{
以及...感觉这东西可以提出来变成一个 workflow 一样的东西（

2023-01-19 17:41 UTC, alphagocc commented on scripts/cjk-map.json
> +  "⺕": "彐",
不过考虑到该字符几乎目前没有字体支持，可以保持原样

2023-01-19 18:10 UTC, yusancky commented on scripts/cjk-map.json
> +  "⺕": "彐",
> 根据 https://www.unicode.org/Public/15.0.0/ucd/EquivalentUnifiedIdeograph.txt
> U+2E95 现在的对应字为 扩展C区 的 U+2B739

我在日前对仓库进行全局扫描前，[在我复刻的仓库里将 Unicode 标准升为了 15.0.0](https://github.com/yusancky/equivalent-unified-ideograph/commit/ed2e80d3743a82219490956e406bbf5e42140a26)，因而也注意了 15.0 的这一更新。

在不造成其它问题的情况下，我个人基本总是更新。

但 `𫜹`（U+2B739）是新字符，绝大部分字体会漏字，使用其存在相对更大的不足（虽然不是绝对劣势，因为字体也在更新），所以 `彐`（U+5F50）会更好。

同样地，在大多数输入法上，你不能得到 `𫜹`（U+2B739），但是可以得到 `彐`（U+5F50）。

综上，我保留使用 Unicode 14.0 的意见。

另：其实是否更新的影响很小，因为 `彐`（U+5F50）不是现汉常用汉字，[^1]不会对读者造成困扰。

----

> 不过考虑到该字符几乎目前没有字体支持，可以保持原样

雾。写完才发现已经回了。

[^1]: `彐`（U+5F50）曾作「雪」的第二批简化字，但后于 1986 年被国务院正式宣布停用。

2023-01-19 18:16 UTC, billchenchina submitted a review, later dismissed
LGTM, Thanks!

2023-01-19 18:20 UTC, alphagocc commented
其实我还有一个问题 CJK Compatibility 区里的要不要改

2023-01-19 18:24 UTC, alphagocc commented
https://github.com/RimoChan/unvcode/blob/slave/html/d.json
部分更改可酌情参考此处

2023-01-19 18:28 UTC, yusancky commented on scripts/cjk-map.json
> +{
> 那就是这个列表不会发生变化的意思吗？🤔

总体内容不变，但随更新内容进行较小的增修。

例如，Unicode 15.0 与 Unicode 14.0 间（本表表头及注释外的）仅更新一处；Unicode 14.0 与 Unicode 13.0 没有差异。

----

> 以及...感觉这东西可以提出来变成一个 workflow 一样的东西（

这里的 `（` 似乎有一定迷惑性。

Unicode 更新频率小而不定期，每次更新的内容也少，编写与使用自动化更新程序在一定程度上比人工（根据文件差异）修改费事。

2023-01-20 04:01 UTC, yusancky commented
对于两点内容，我的看法是这样的：
- `find_jk.py` 与这个的目的有差异，还是先留着吧。
- 对中文部分 Compatibility 区，参考 [上文](#issuecomment-1397422884) 给出的 [文件](https://github.com/RimoChan/unvcode/blob/slave/html/d.json) 增大字体映射表。目前，我已 [删除部分不需要的字符](https://github.com/OI-wiki/OI-wiki/files/10462980/d.txt)，但还能进行进一步删改（字集越小，性能越佳）。

----

我对字表的改动是这样的：
1. 删去不需要的字符（日韩文、特殊字符等）
2. 对于样式有出入、但看起来认为是同一汉字的，改为正确汉字与每一样式对照。如对原映射表中 `工` 等字符的片段，按这样修改：
    ```diff
    - "ェ": "ｪ",
    - "工": "ｴ",
    + "工": "ｪ",
    + "工": "ェ",
    + "工": "ｴ",
    ```
    
    > **Note**
    > 
    > 在上方示例中，第 2 行（`-`）与第 5 行（`+`）是一样的，所以更准确的差异应该是这样的：
    > ```diff
    > - "ェ": "ｪ",
    > + "工": "ｪ",
    > + "工": "ェ",
    >   "工": "ｴ",
    > ```
 
----

另：最近比较忙，没有时间进行过多操作。我 25 号前没有进一步删减的计划，欢迎帮助删减。

2023-01-20 04:56 UTC, Great-designer commented
看来这个字表是个长期的工作。按照经验，一般字表类都会是长期工作。

2023-01-20 06:49 UTC, yusancky commented
> 看来这个字表是个长期的工作。按照经验，一般字表类都会是长期工作。

这类的参考资料与素材比较多，后面应该会很快

2023-01-20 07:21 UTC, yusancky commented
中文部分 Compatibility 区的表基本上完工了，会在比对后合并到当前分支。

以下是 `d.json` 中的符号对照表（`key` 为规范符号，`value` 为需要替换的符号），OI Wiki 是否需要这方面的规范？如果需要，是否需要添加更多符号？

```json
{
  "、": "､",
  "。": "｡",
  "〈": "〈",
  "〉": "〉",
  "〔": "﹝",
  "〕": "﹞",
  "・": "･"
}
```

2023-01-20 08:40 UTC, Great-designer commented
> 中文部分 Compatibility 区的表基本上完工了，会在比对后合并到当前分支。

辛苦，期待。

> 以下是 `d.json` 中的符号对照表（`key` 为规范符号，`value` 为需要替换的符号），OI Wiki 是否需要这方面的规范？如果需要，是否需要添加更多符号？
> 
> ```json
> {
>   "、": "､",
>   "。": "｡",
>   "〈": "〈",
>   "〉": "〉",
>   "〔": "﹝",
>   "〕": "﹞",
>   "・": "･"
> }
> ```

符号方面建议谨慎，例如全半角替换等等……因为LaTeX里面也有大量的半角符号。

2023-01-21 03:09 UTC, yusancky commented
现在的「需要讨论」可以撤下了

2023-01-21 04:16 UTC, alphagocc approved these changes

2023-01-23 04:37 UTC, Enter-tainer submitted a review, later dismissed

2023-01-23 05:31 UTC, Great-designer commented
看前面提交有一个

“[防止日文中的 ー 被识别](https://github.com/OI-wiki/OI-wiki/pull/4635/commits/76e8b96d37a3912b8723367be896d09372f4ab40)”

我不知道这个是不是必要的……

2023-01-23 06:24 UTC, yusancky commented
> 看前面提交有一个
> 
> “[防止日文中的 ー 被识别](https://github.com/OI-wiki/OI-wiki/pull/4635/commits/76e8b96d37a3912b8723367be896d09372f4ab40)”
> 
> 我不知道这个是不是必要的……

JOI 春训营（ $\text{\color{grey}春季トレ\color{red}ー\color{grey}ニング合宿}$ ）的 `ー`（`U+30FC`）是日语片假名。[^1][^2]

76e8b96d37a3912b8723367be896d09372f4ab40 的修改仅会跳过对 `oi.md` 的测试，可以较好解决这一问题。当然，更好的方案是只跳过这一文件中的这一映射。

[^1]: 虽然我不了解日文，但这里的用法与 joi.ioi-jp.org 一致，可参考 [其首页](https://joi.ioi-jp.org/)、[JOI 春季トレーニング｜第 22 回日本情報オリンピック](https://www.ioi-jp.org/joi/2022/training) 等页面。
[^2]: `ー` 不是 CJK 部首或笔画，属于映射表第二次修改新增的相似字，映射表中对应替换字符为中日韩象形文字 `一`（`U+4E00`）。

2023-01-23 06:28 UTC, Great-designer commented
> > 看前面提交有一个
> > “[防止日文中的 ー 被识别](https://github.com/OI-wiki/OI-wiki/pull/4635/commits/76e8b96d37a3912b8723367be896d09372f4ab40)”
> > 我不知道这个是不是必要的……
> 
> JOI 春训营（ 春季トレーニング合宿春季トレーニング合宿 ）的 `ー`（`U+30FC`）是日语片假名。[1](#user-content-fn-1-6156dd3f17f364ed05cbb92210128e10)[2](#user-content-fn-2-6156dd3f17f364ed05cbb92210128e10)
> 
> [76e8b96](https://github.com/OI-wiki/OI-wiki/commit/76e8b96d37a3912b8723367be896d09372f4ab40) 的修改仅会跳过对 `oi.md` 的测试，可以较好解决这一问题。当然，更好的方案是只跳过这一文件中的这一映射。
> 
> ## Footnotes
> 1. 虽然我不了解日文，但这里的用法与 joi.ioi-jp.org 一致，可参考 [其首页](https://joi.ioi-jp.org/)、[JOI 春季トレーニング｜第 22 回日本情報オリンピック](https://www.ioi-jp.org/joi/2022/training) 等页面。 [↩](#user-content-fnref-1-6156dd3f17f364ed05cbb92210128e10)
> 2. `ー` 不是 CJK 部首或笔画，属于映射表第二次修改新增的相似字，映射表中对应替换字符为中日韩象形文字 `一`（`U+4E00`）。 [↩](#user-content-fnref-2-6156dd3f17f364ed05cbb92210128e10)

那很好，偶尔也会有日文等其他语言。如果是其他语言必须的部件儿，确实不该修改。

2023-01-25 08:40 UTC, billchenchina requested changes
没有其它问题了，只是 file object 是可以直接 for 的，改掉更好）

2023-01-25 08:40 UTC, billchenchina commented on scripts/check-characters.py
> +with open(listfile) as file_object:
其实 `file_object` 本身就是  iterable 的，不需要 readlines（

2023-01-25 11:23 UTC, billchenchina approved these changes
LGTM, Thanks!

2023-01-25 14:07 UTC, alphagocc approved these changes

2023-01-25 14:08 UTC, CoelacanthusHex approved these changes
LGTM

2023-01-25 14:09 UTC, Enter-tainer approved these changes

2023-01-25 14:22 UTC, merged