feat(notation.md)：更新符号表
OI-wiki/OI-wiki pull request #4669
Opened 2023-01-29 05:54 UTC by Great-designer

fix #4587 

符号表作为一个**长期**试行的工作呈现。由于修改了格式手册，针对符号表的内容可以进行充分的讨论。后续行文如果大量使用了某符号或者使用了某重要符号，可以写入符号表。

2023-01-29 05:55 UTC, Great-designer commented
由于对《格式手册》删减了一些内容，如果认为进行了错误删减，例如没有在《符号表》一文中体现，可以重新补回去。

2023-01-29 06:06 UTC, r-value commented
个人建议 "符号表" 应当命名为 "记号与约定" 或 "数学记号", "符号表" 一词在计算机科学中另有常用含义.

2023-01-29 06:11 UTC, Great-designer commented
> 个人建议 "符号表" 应当命名为 "记号与约定" 或 "数学记号", "符号表" 一词在计算机科学中另有常用含义.

可以

2023-01-29 06:12 UTC, r-value commented
`$\nmid$` 在预览里未能正确渲染, 尝试一下 `$\not \mid$`?

2023-01-29 06:15 UTC, Great-designer commented
> `$\nmid$` 在预览里未能正确渲染, 尝试一下 `$\not \mid$`?

已修改。等待预览渲染。

2023-01-29 08:19 UTC, inclyc commented
感觉没有必要移动 `{math -> intro}/notation.md`

2023-01-29 09:39 UTC, Great-designer commented
> 感觉没有必要移动 `{math -> intro}/notation.md`

不正确。这个符号表是统领全站的，囊括全站符号，并且严格来说是格式标准，是格式手册的一部分。

2023-01-29 10:04 UTC, r-value commented
> 严格来说是格式标准，是格式手册的一部分。

作为手册应该把落脚点放在 "在 xxx 情况下使用符号 yyy" 而不是只列出符号的样子?

比如前两节 "字体" 与 "字母" 并未说明什么情况下要使用这样的样式.

同时对于符号的含义描述也有不清晰, 比如 "阶乘" 一项, 个人认为更应当使用类似下面的描述:

 + $n$ 的阶乘记为 $n!$, 源码为 `$n!$`, 表示 $1\times 2 \times \cdots \times n$. 特别地, $0!=1$.

这部分行文方式可以参考很多数学教材都有的 "记号" 部分.

以及作为格式手册应该更形而上一些, 比如:

 + 对于数列, 使用 $\langle 1,2,\dots,n \rangle$
 + 在指数结构较简单(如: 只包含一行)的情况下使用 `$\mathrm{e}^x$`, 否则使用 `$\exp(x)$`

2023-01-29 10:47 UTC, Great-designer commented
> 比如前两节 "字体" 与 "字母" 并未说明什么情况下要使用这样的样式.

"字体" 这里确实是有问题，应该删一删，没解释的就不要了。"字母" 的话还是写全为好，读者看着用，没听说只介绍一半留一半的。

> * n 的阶乘记为 n!, 源码为 `$n!$`, 表示 1×2×⋯×n. 特别地, 0!=1.

这就有些离谱了。符号表告诉读者“写成这样是规范的”，而不是告诉读者“这东西是啥”。如果“是啥”问题能在符号表解释清楚，就不需要 wiki 了。

例如阶乘，万一有读者想不开，写成转义的 `\!` 或者全角的 `！` 就麻烦了，这是给予读者的规范。至于阶乘究竟是什么意思，那不管，哪怕研究的是复数的阶乘也不管，都得这么写。

> 定义的部分也可以选择留一个内/外链接. 这部分行文方式可以参考很多数学教材都有的 "记号" 部分.

看起来麻烦，现在还有质疑移动问题的呢，移动页面之后内链都要改。这个后续再处理吧。

> * 对于数列, 使用 ⟨1,2,…,n⟩

没看懂。

> * 在指数结构较简单(如: 只包含一行)的情况下使用 `$\mathrm{e}^x$`, 否则使用 `$\exp(x)$`

可以采纳。

2023-01-29 11:03 UTC, r-value commented
> 符号表告诉读者“写成这样是规范的”

那么首先"**什么东西**要写成这样"需要有一个良定义. 

> 例如阶乘，万一有读者想不开，写成转义的 `\!` 或者全角的 `！` 就麻烦了，这是给予读者的规范。

我举阶乘的例子指的是应当代入一个值表示其具体含义, 而不是一个生硬的符号. 读者想不开甚至可以用 `$!n$`. 比如对于 "取函数多项式展开的某一项系数" 符号就应当描述为:

 + $\left[z^n\right]f(z)$ 表示 $f(z)$ 的多项式展开中 $z^n$ 项的系数.

2023-01-29 11:32 UTC, Great-designer commented
> 那么首先"**什么东西**要写成这样"需要有一个良定义，还有 "在本站看到 xxx 的时候它表示的是 yyy".

不需要。这是抬杠。“什么东西”，要么是常识，要么在本站其他地方写了。

您之前指出“留一个内/外链接”，是很好的解决“本站其他地方写了”的办法。我说这个比较麻烦，后续有机会在处理，没有就算了。

> 我举阶乘的例子指的是应当代入一个值表示其具体含义, 而不是一个生硬的符号. 读者想不开甚至可以用 `$!n$`. 

可以修正，

> * [zn]f(z) 表示 f(z) 的多项式展开中 zn 项的系数.

可以加进去。

2023-01-29 11:41 UTC, r-value commented
> “什么东西”，要么是常识，要么在本站其他地方写了。

那么您的新表不能替代 `math/notation.md`. 该文件中包含必要的数学常识的定义, 如求和符号/阶乘/取模等.

2023-01-29 11:45 UTC, Great-designer commented
> 还有 "在本站看到 xxx 的时候它表示的是 yyy"

本站看到 xxx 的时候它表示的是啥，这我不知道，我知道它一般表示的是啥，本站一般情况下逃离不了一般表示的范围。

比如说未来有头铁的小孩就要介绍复数的阶乘，并且还真的介绍了，比如介绍 C++ 的复数 Gamma 函数啥的，就会和这里的定义有矛盾。所以这里应当写一些泛化的东西，大家知道它“是阶乘运算”就完了，哪怕语义上说不通、“它是一个汉字的阶乘”，也暂时先不管，首先符合语法。

您说的 `!n` 是一个不合语法的好例子，需要修正，并且已经修正。

泛化的方便就是往里面加东西方便，修正方便，想写什么新东西都行。认为这里写的东西不够可以加。

> 那么您的新表不能替代 math/notation.md. 该文件中包含必要的数学常识的定义, 如求和符号/阶乘/取模等.

另注：阶乘的定义应该写在“排列组合”的全排列页面，不应写在这里。同理，“取模”的定义应该写在数论基础。

您上面指出“求和”的定义问题是中肯的。可以往里加。

2023-01-29 11:48 UTC, Great-designer commented
> 必要的数学常识的定义

声明一下，加号“+”和减号“-”的定义不应当写在 OI wiki，它不是必要的。

什么是必要的数学常识？如果真的是必要的，应该已经写在了其他页面才对。

2023-01-29 11:55 UTC, dbxxx-oi commented
我觉得删除 math/notation.md 不太恰当吧，因为这里描述了很多记号的具体含义。如果它们的位置不对的话或许应该是另一个 PR 要做的事情？正如您所说记号的含义和表达规范不同？

2023-01-29 11:57 UTC, dbxxx-oi commented
或者至少在这个 PR 把 math/notation.md 删除的内容在另外您认为正确的地方补上吧，但我不太清楚这个算不算一个 PR 做两件事（

2023-01-29 11:59 UTC, Great-designer commented
> 我觉得删除 math/notation.md 不太恰当吧，因为这里描述了很多记号的具体含义。如果它们的位置不对的话或许应该是另一个 PR 要做的事情？正如您所说记号的含义和表达规范不同？

这个您可以给个建议，如何分成俩pr。

我看了半天，实在没看出来“很多记号的具体含义”是咋写的……

> 或者至少在这个 PR 把 math/notation.md 删除的内容在另外您认为正确的地方补上吧，但我不太清楚这个算不算一个 PR 做两件事（

不用补，我的前人们早就已经把它们写到对应页面了。详见对应页面。

2023-01-29 12:01 UTC, r-value commented
> 本站看到 xxx 的时候它表示的是啥，这我不知道，我知道它一般表示的是啥，本站一般情况下逃离不了一般表示的范围。

恕我我完全没看懂您想表达的意思, 但是 "记号表的作用是双向的" 这一点无可置疑. 数学教科书和论文中常有的 "记号与约定" 一节的主要目的也是为了解释 "在本书/本文中看到符号 xxx, 则它表达的含义是 yyy". 在本站中需要与之相反的映射(含义→符号)是因为有参与撰写的需求. 就读者而言, 符号到含义的映射是十分必要的.

2023-01-29 12:10 UTC, Great-designer commented
> 数学教科书和论文中常有的 "记号与约定" 一节的主要目的也是为了解释 "在本书/本文中看到符号 xxx, 则它表达的含义是 yyy". 

啊这，那这就是标题写得不好了。感觉一个符号表应该就已经够了。

> 在本站中需要与之相反的映射(含义→符号)是因为有参与撰写的需求. 就读者而言, 符号到含义的映射是十分必要的.

从实际角度讲，如果新的作者想写的是旧含义，那么确实在网站里已经有了，直接在对应地方写就完了。比如作者想继续补充整数 $n$ 的阶乘，那么在《排列组合》的相关位置继续补就可以，不会造成矛盾。

如果新的作者想写的是新含义，那么在网站里确实没有，比如作者想写实数的阶乘。这个时候怎么办？当然还是要在对应地方写定义，比如进一步阐述“实数的阶乘是啥”。

本站出现过这种情况。比如 $\log$ 表示对数，但是离散对数呢？多项式的对数呢？同一个记号 $\log$ 表示的还是“对数”的意思吗？我们只知道它确实是“对数”，但是不同的对数有着不同的解释，这些解释都与具体使用环境密切相关。

真的，如果在符号表真的能讲定义，那么 wiki 就没用了。

2023-01-29 12:13 UTC, Great-designer commented
首先需求分析要做好。我要告诉读者“对数”是 $\log$，$\log$ 是“对数”，而不是告诉读者“对数”具体是啥，费这个劲没有意义，这是具体的页面干的活。这叫做把功能都拆分开了。

2023-01-29 12:15 UTC, inclyc requested changes
首先需要指出我觉得不应该删除 math/notations.md ，这是因为你写的 intro/notations.md 和 math/notations.md 是面对不同用户群体的两个文件

- math/notations.md 学习 OI-wiki 给出的内容，需要先认识数学符号的人
- intro/notations.md OI-wiki 的贡献者，需要学习如何排版

显然学习数学内容并不强依赖如何排版，学习者可以认识 $e^x$ ，而不需要把他打出来。

其次，我觉得你不如把所有 TeX 相关的，公式的注意事项单独分成一页。比如 intro/tex.md

2023-01-29 12:15 UTC, inclyc commented on docs/intro/notation.md
> +author: sshwy, hsfzLZH1, Enter-tainer
> 不正确。这个符号表是统领全站的，囊括全站符号，并且严格来说是格式标准，是格式手册的一部分。

你写的这些格式化规范看起来和 math/notations.md 做的是不同的事情，你应该**新增** "intro/notations" 作为格式化风格推荐，而不是删了自己 remake。其他人的评论也提到了这一点

2023-01-29 12:15 UTC, inclyc commented on docs/intro/notation.md
> +## 字体
你的字体行文存在逻辑耦合，分别是：

1. 某种“排版元素”应该使用什么字体，比如“正文中的公式”
2. 如何打出某种字体，比如 `\mathrm`

我认为这样书写是混乱的。我们没必要写第二点，因为如何打出等宽字体 `\mathtt` 应该是 TeX 用户自己学习的。我们应该告诉贡献者 “程序代码应使用等宽字体”

2023-01-29 12:15 UTC, inclyc commented on docs/intro/notation.md
> +- 还有一些字体尚未有应用，仅列在这里，表示网站 OI wiki 的架构支持下列 LaTeX 字体。
> 表示网站 OI wiki 的架构

的架构？直接写出渲染引擎吧。

2023-01-29 12:15 UTC, inclyc commented on docs/intro/notation.md
> +| 打印机体      | `\mathtt{something}`             | $\mathtt{something}$           | 支持大小写英文字母、大写希腊字母和数字 |
等宽字体。

2023-01-29 12:15 UTC, inclyc commented on docs/intro/format.md
> +LaTeX 符号的书写可参考 [KaTeX 的 Supported Functions 页面](https://katex.org/docs/supported.html)（不是全部），也可以搜索求解。
既然独立出了符号的排版意见，不如把 TeX 排版单独成页，将你写的符号约定和 TeX 排版要求一并写上。然后在 format.md 留下链接。

2023-01-29 12:15 UTC, Great-designer commented
换到编辑人员的视角也是自然的。读完格式手册，自动就会读符号表，然后找自己需要的东西，如果没有就加进去。

2023-01-29 12:21 UTC, inclyc commented
这个 PR 看起来已经完工，只是有点争议

2023-01-29 12:23 UTC, inclyc commented
> 换到编辑人员的视角也是自然的。读完格式手册，自动就会读符号表，然后找自己需要的东西，如果没有就加进去。

我不理解为什么看 "数学" 版块的人要学习如何打出数学符号。

2023-01-29 12:25 UTC, Great-designer commented
我感觉管理员对于删文件这事儿意见很大。我没有删文件，整个新文件就是在旧文件基础上改过来的，没有旧文件确实也没有新文件，两者重复率确实也非常高……

如果不让删，也可以把旧的先恢复过来，就是两个文件重复度会很高。

> 学习 OI-wiki 给出的内容，需要先认识数学符号/OI-wiki 的贡献者，需要学习如何排版

认识符号和学习排版，两者本身不是矛盾的事情……而且一般假定大家已经认识了符号……

有可能就是原“数学/符号.md”这个文件多余的东西太多了，好多东西确实应该写在对应页面。这是历史遗留问题，“数学/符号.md”这个文件在建站早期可能就有，那时符号介绍还不完备，不像现在相关定义非常完备。

2023-01-29 12:28 UTC, Great-designer commented
> 认识符号和学习排版，两者本身不是矛盾的事情……

一个笑话：数学系毕业生在和其他系合作论文的时候，一般负责 LaTeX 排版。

这意味着学数学的家伙们，在学的时候就已经同时在精通 LaTeX 写法了。

2023-01-29 12:28 UTC, inclyc commented
> 认识符号和学习排版，两者本身不是矛盾的事情……

这挺矛盾的吧。

2023-01-29 12:28 UTC, alphagocc commented
> > 认识符号和学习排版，两者本身不是矛盾的事情……
> 
> 这挺矛盾的吧。

应该说是正交的

2023-01-29 12:29 UTC, Great-designer commented
上述有关建议我已经收到了。接下来我试着把旧文件恢复一下……

2023-01-29 12:29 UTC, inclyc commented
> 一个笑话：数学系毕业生在和其他系合作论文的时候，一般负责 LaTeX 排版。
> 这意味着学数学的家伙们，在学的时候就已经同时在精通 LaTeX 写法了。

学 OI 的人不一定是数学系，初学者看个数学符号还要人家会打出来？

我要再说明一次，这里是 OI-wiki ，不是 Math-Wiki

2023-01-29 12:32 UTC, dbxxx-oi commented
PR 作者的意思是 math/notation.md 里面的内容要么在其他页面都有了，要么属于常识，所以顺便删掉了。（我没有求证这个说法的真实性）

2023-01-29 12:35 UTC, inclyc commented
我觉得似乎我们对 math/notation.md 的认识不同。PR 作者似乎认为这是一个 OI-wiki 的全站符号表，指导贡献者格式（或许）

https://github.com/OI-wiki/OI-wiki/issues/4587#issuecomment-1404749300

2023-01-29 12:45 UTC, Great-designer commented on docs/intro/notation.md
> +author: sshwy, hsfzLZH1, Enter-tainer
已修正

2023-01-29 12:46 UTC, Great-designer commented on docs/intro/notation.md
> +## 字体
给个suggestion

2023-01-29 12:46 UTC, Great-designer commented on docs/intro/notation.md
> +- 还有一些字体尚未有应用，仅列在这里，表示网站 OI wiki 的架构支持下列 LaTeX 字体。
不知道。给个suggestion

2023-01-29 12:46 UTC, Great-designer commented on docs/intro/format.md
> +LaTeX 符号的书写可参考 [KaTeX 的 Supported Functions 页面](https://katex.org/docs/supported.html)（不是全部），也可以搜索求解。
没看懂

2023-01-29 12:47 UTC, Great-designer commented on docs/intro/notation.md
> +| 打印机体      | `\mathtt{something}`             | $\mathtt{something}$           | 支持大小写英文字母、大写希腊字母和数字 |
已修正

2023-01-29 12:48 UTC, Great-designer commented
math/notation 已经还原了。至于这个文件是否有必要，以下不再讨论

2023-01-29 13:36 UTC, inclyc commented on docs/_redirects
> +/math/sign /math/notation
此处更改是不必要的。

2023-01-29 13:36 UTC, inclyc commented on docs/intro/format.md
> +LaTeX 符号的书写可参考 [KaTeX 的 Supported Functions 页面](https://katex.org/docs/supported.html)（不是全部），也可以搜索求解。
就是把这些和 tex 相关的移动到你写的 tex.md 中。

2023-01-29 13:36 UTC, inclyc commented on docs/intro/format.md
> +- 请使用 `\begin{aligned} ... \end{aligned}` 表示多行对齐的公式。
tex 相关的。

2023-01-29 13:36 UTC, inclyc commented on docs/intro/format.md
> +- 如果这些多行对齐的公式需要 **编号**，请用 `align` 或 `equation` 环境。
tex 相关的

2023-01-29 13:36 UTC, inclyc commented on docs/intro/format.md
> +- 书写 LaTeX 直接书写 LaTeX 即可，不建议使用 LaTeX 符号。若要输出 LaTeX 符号 $\rm{\LaTeX}$，请用 `$\rm{\LaTeX}$`，而不是 `mathrm`；（`\LaTeX` 在 TeX 排版系统中是一个不能用于数学模式下的命令，而 `\mathrm` 又不能在普通模式下使用；另外，`\text` 命令虽然在 TeX 上正常输出，但是在 MathJax
tex 相关的

2023-01-29 13:36 UTC, inclyc commented on docs/intro/format.md
> +请注意，尽管上述输入公式的语法和真正的 LaTeX 排版系统非常相似，但 **MathJax 和 LaTeX 是两个完全没有关系的东西**，MathJax 仅仅使用了一部分与 LaTeX 非常相似的语法而已。实际上，二者之间有不少细节差别，而这些差别经常导致写出来的公式在二者之间不通用。
tex 相关的

2023-01-29 13:36 UTC, inclyc commented on docs/math/index.md
> +在学习数学的过程中大家会见到许多复杂的公式符号。因此在学习具体内容之前，建议大家首先理解常见符号的含义。一些特殊的符号会在对应的章节中讲到，极为常见的符号则需要大家提前掌握。请参见 [记号与约定](../intro/tex.md)。
多余修改，应删去：看 math/index.md 的人不一定需要学习如何用 TeX 书写公式

2023-01-29 13:36 UTC, inclyc commented on mkdocs.yml
> +    - 记号与约定: intro/tex.md
```suggestion
    - TeX 公式排版规范: intro/tex.md
```

2023-01-30 01:26 UTC, Great-designer commented on docs/_redirects
> +/math/sign /math/notation
等价，懒得改了

2023-01-30 02:20 UTC, Great-designer commented
请管理员隐藏一下失效的对话现在版面太长了

2023-01-30 04:07 UTC, inclyc commented on docs/_redirects
> +/math/sign /math/notation
行8，之后我帮你改

2023-01-30 04:44 UTC, inclyc commented on docs/intro/format.md
> +OI wiki 的符号书写规范，见 [记号与约定](./tex.md)。符号之外的一些行文规范包括：
> 记号与约定

这里可以改成“TeX 公式排版规范”

2023-01-30 04:44 UTC, inclyc commented on docs/intro/format.md
> +- 公式中不要使用中括号连缀（即 C++ 高维数组的表示方式）而多使用下标。
应该移动到 tex.md?

2023-01-30 04:44 UTC, inclyc commented on docs/intro/format.md
> +- 中文建议尽量不放在 LaTeX 公式中。如果出现数学公式中的中文文字，**必须置于 `\text{}` 命令之中**，而变量、数字、运算符、函数名称则必须置于 `\text{}` 命令之外。**请不要在 `\text{}` 命令中嵌套数学公式**。
移动到 tex.md?

2023-01-30 04:44 UTC, inclyc commented on docs/intro/format.md
> +相关内容在 [记号与约定](./tex.md) 中给出，已经向 MathJax 做了尽可能多的妥协。导出工具兼容了一部分原本仅能在 MathJax 中正常输出的写法。
TeX 公式排版规范

2023-01-30 04:44 UTC, inclyc commented on docs/intro/tex.md
> +author: sshwy, hsfzLZH1, Enter-tainer
author 似乎还是 math/notation.md 来的，改成你自己的名字吧

2023-01-30 04:44 UTC, inclyc commented on docs/intro/tex.md
> +| Italic 粗体 | `\boldsymbol{something}`         | $\boldsymbol{something}$       |                     |
文中提到了不少 Italic/Roman，写成中文的罗马/意大利，我们要不统一一下？

规范成 “斜体” “衬线体”

2023-01-30 05:23 UTC, Great-designer commented on docs/intro/tex.md
> +author: sshwy, hsfzLZH1, Enter-tainer
不必了。中间求和求积部分是抄来的，我也不知是其中哪个人写的，干脆全列上

2023-01-30 05:59 UTC, yanboishere approved these changes

2023-01-30 08:34 UTC, Great-designer commented
改完了

2023-02-27 04:02 UTC, Great-designer commented
已经有了#4760 ，后续工作由#4760 完成

2023-02-27 04:02 UTC, closed without merging