fix(faq.md):添加fastgithub&google hosts 替换为 GitHub520
OI-wiki/OI-wiki pull request #4676
Opened 2023-01-31 05:23 UTC by Find-NICK

- [x] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

 fix #4675

2023-01-31 06:30 UTC, alphagocc requested changes

2023-01-31 06:30 UTC, alphagocc commented on docs/intro/faq.md
> +- [清华云盘](https://cloud.tsinghua.edu.cn/d/df482a15afb64dfeaff8/)
是官方提供的吗

2023-01-31 06:30 UTC, alphagocc commented on docs/intro/faq.md
> +A：推荐使用[`FastGithub`](https://github.com/dotnetcore/FastGithub),支持`Windows`/`MacOS`/`Linux`.
该软件似乎是 mitmproxy 类似物，我不确定加速 github 需要 mitm

2023-01-31 06:30 UTC, alphagocc commented on docs/intro/faq.md
> +可以在[ `Github520` 主页](https://github.com/521xueweihan/GitHub520) 上了解到更多信息。
注意到该内容经常更新，仅保留指向 repo 的链接即可

2023-01-31 06:30 UTC, alphagocc commented on docs/intro/faq.md
> -Linux 和 macOS 用户可以尝试使用 [依云](https://github.com/lilydjwg/) 的 [gh-check 脚本](https://gist.github.com/lilydjwg/93d33ed04547e1b9f7a86b64ef2ed058) 获取访问最快的 IP，使用 `--hosts` 参数可以直接更新 hosts 文件。使用 `--help` 参数可以
你把这玩意删了干啥

2023-01-31 06:30 UTC, alphagocc commented on docs/intro/faq.md
> +可以在[ `Github520` 主页](https://github.com/521xueweihan/GitHub520) 上了解到更多信息。
其次不要复制别人 readme

2023-01-31 06:31 UTC, Find-NICK commented on docs/intro/faq.md
> -Linux 和 macOS 用户可以尝试使用 [依云](https://github.com/lilydjwg/) 的 [gh-check 脚本](https://gist.github.com/lilydjwg/93d33ed04547e1b9f7a86b64ef2ed058) 获取访问最快的 IP，使用 `--hosts` 参数可以直接更新 hosts 文件。使用 `--help` 参数可以
不小心...

2023-01-31 06:31 UTC, Find-NICK commented on docs/intro/faq.md
> +可以在[ `Github520` 主页](https://github.com/521xueweihan/GitHub520) 上了解到更多信息。
ok

2023-01-31 06:32 UTC, Find-NICK commented on docs/intro/faq.md
> +A：推荐使用[`FastGithub`](https://github.com/dotnetcore/FastGithub),支持`Windows`/`MacOS`/`Linux`.
本地反代

2023-01-31 06:33 UTC, Find-NICK commented on docs/intro/faq.md
> +- [清华云盘](https://cloud.tsinghua.edu.cn/d/df482a15afb64dfeaff8/)
好像不是

2023-01-31 10:21 UTC, yusancky requested changes
格式需要改改。

另外，强烈建议删去该项目过于详细的信息。[#4676 (review)](https://github.com/OI-wiki/OI-wiki/pull/4676/files/2853052e6e18f556324b6fa0a35217f38871c4fd#diff-f6f9be616412c5de5a59a9cc33ad31c45fd32ce794900dd589d3866b8994a860)

2023-01-31 10:21 UTC, yusancky commented on docs/intro/faq.md
> +A：推荐使用 [`FastGithub`](https://github.com/dotnetcore/FastGithub), 支持 `Windows`/`MacOS`/`Linux`.
```suggestion
A：推荐使用 [`FastGithub`](https://github.com/dotnetcore/FastGithub)，支持 Windows/macOS/Linux。
```

2023-01-31 10:21 UTC, yusancky commented on docs/intro/faq.md
> +- ~~发送电子邮件到 `fastgithub@qq.com`~~（已失效）
```suggestion
```

2023-01-31 13:30 UTC, 383494 reviewed
这里会403

官方示例：
> git clone https://ghproxy.com/https://github.com/stilleshan/ServerStatus

2023-02-01 01:33 UTC, yanboishere submitted a review, later dismissed

2023-02-04 06:43 UTC, yusancky requested changes
格式问题

2023-02-04 06:43 UTC, yusancky commented on docs/intro/faq.md
> +A：推荐使用 [`FastGithub`](https://github.com/dotnetcore/FastGithub), 支持 Windows/MacOS/Linux.
```suggestion
A：推荐使用 [`FastGithub`](https://github.com/dotnetcore/FastGithub)，支持 Windows/macOS/Linux。
```

2023-02-04 06:43 UTC, yusancky commented on docs/intro/faq.md
> +- ~~发送电子邮件到 `fastgithub@qq.com`~~（已失效）
```suggestion
```

2023-02-04 06:43 UTC, yusancky commented on docs/intro/faq.md
> +或者，也可以在 hosts 中加入 [此页面](https://raw.hellogithub.com/hosts) 中的内容：
### 改动小的版本
```suggestion
或者，也可以在 hosts 中加入 [此页面](https://raw.hellogithub.com/hosts) 中的内容。
```

### 个人认为更好的版本
```suggestion
或者，也可以在 hosts 文件中加入 [此文件](https://raw.hellogithub.com/hosts) 中的内容。
```

2023-02-04 15:51 UTC, yusancky commented
CC: @alphagocc

2023-02-04 16:01 UTC, alphagocc commented on docs/intro/faq.md
> +A：推荐使用 [`FastGithub`](https://github.com/dotnetcore/FastGithub)，支持 Windows/macOS/Linux。
建议把 推荐 改成 可以。因为推荐比较主观，而且推荐这个项目这件事也比较难以达成wiki内一致。
另外对于我个人来说，我不是很推荐使用。

2023-02-10 16:13 UTC, yusancky commented on docs/intro/faq.md
> +A：推荐使用 [`FastGithub`](https://github.com/dotnetcore/FastGithub)，支持 Windows/macOS/Linux。
```suggestion
A：可以使用 [`FastGithub`](https://github.com/dotnetcore/FastGithub)，支持 Windows/macOS/Linux。
```

CC: @Find-NICK

2023-02-10 16:21 UTC, yusancky requested changes

2023-02-10 16:21 UTC, yusancky commented on docs/intro/faq.md
> +git clone https://ghproxy.com/https://github.com/OI-wiki/OI-wiki
```suggestion
git clone https://ghproxy.com/https://github.com/username/OI-wiki
```

2023-02-10 16:34 UTC, yusancky commented
> 这里直接 clone 会 403
> 
> 官方示例：
> 
> 
> ```powershell
> git clone https://ghproxy.com/https://github.com/stilleshan/ServerStatus
> ```
> 
> _引用自 [拉取请求审查 1277181321](#pullrequestreview-1277181321)_

[这里](#pullrequestreview-1277181321) 的请求更改可标为已解决了。

2023-02-11 12:14 UTC, yusancky commented on docs/intro/faq.md
> +A：可以使用 [`FastGithub`](https://github.com/dotnetcore/FastGithub)，支持 Windows/macOS/Linux。
以下有两种不同的方案，个人建议用列表区分。

```markdown
A：可以采用以下两种方案：

- 方案一
    下载链接
- 方案二
   更多信息链接
```

> **Note**
> 上面的「方案一／二」应改为具体的方案，如 ``使用 [`FastGithub`](https://github.com/dotnetcore/FastGithub)``。

另，其实每个方案的内容都较少，但都被分为了两段，可以考虑合并为一段。

2023-02-12 14:58 UTC, alphagocc submitted a review, later dismissed

2023-02-18 02:46 UTC, yusancky commented
等待 [<img src="https://www.svgrepo.com/download/361185/git-pull-request.svg" alt="拉取请求" width="16" height="16" align="center" /> fix(faq.md): 增加空行以尝试修复列表问题 Find-NICK#3](https://github.com/Find-NICK/OI-wiki/pull/3) 合并 👀

2023-02-18 07:04 UTC, yusancky approved these changes

2023-02-18 10:08 UTC, yanboishere approved these changes

2023-02-18 12:00 UTC, alphagocc approved these changes

2023-02-20 11:22 UTC, diauweb requested changes

2023-02-20 11:22 UTC, diauweb commented on docs/intro/faq.md
> +- 你可以使用 [`FastGithub`](https://github.com/dotnetcore/FastGithub)（支持 Windows/macOS/Linux）进行本地代理。前往 [GitHub Release](https://github.com/dotnetcore/FastGithub/releases) 下载软件后，按照 [其文档](https://github.com
```suggestion
- 你可以使用 [`FastGithub`](https://github.com/dotnetcore/FastGithub)（支持 Windows/macOS/Linux）进行本地代理。前往 [GitHub Release](https://github.com/dotnetcore/FastGithub/releases) 下载软件后，按照 [FastGitHub 的文档](https://github.com/dotnetcore/FastGithub#2-%E9%83%A8%E7%BD%B2%E6%96%B9%E5%BC%8F) 进行部署即可使用。
```

2023-02-24 14:30 UTC, yusancky submitted a review, later dismissed

2023-02-25 10:55 UTC, yusancky commented
CC: @diauweb

2023-03-16 15:33 UTC, alphagocc approved these changes

2023-04-24 15:34 UTC, Tiphereth-A requested changes

2023-04-24 15:34 UTC, Tiphereth-A commented on docs/intro/faq.md
> +-   你可以使用 [`FastGithub`](https://github.com/dotnetcore/FastGithub)（支持 Windows/macOS/Linux）进行本地代理。前往 [GitHub Release](https://github.com/dotnetcore/FastGithub/releases) 下载软件后，按照 [FastGitHub 的文档](https
安装和无条件信任自颁发的 CA 证书有潜在的安全风险，不推荐介绍这种方式

2023-06-11 00:18 UTC, closed without merging