fix(combinatory,md)：修正组合数记号
OI-wiki/OI-wiki pull request #4687
Opened 2023-02-01 04:10 UTC by Great-designer

fix #4655 

目前我找到的C形式组合数有这些。如果还能找到更多，可以指出

2023-02-01 04:32 UTC, Great-designer commented
Build LaTeX document / OI-Wiki LaTeX Build (pull_request) Failing after 18m

2023-02-01 04:35 UTC, Great-designer commented
> Build LaTeX document / OI-Wiki LaTeX Build (pull_request) Failing after 18m

似乎修好了

2023-02-19 06:03 UTC, 383494 submitted a review, later dismissed

2023-02-28 20:35 UTC, untitledunrevised requested changes
以及对于数学这一版块还有一些没修的：
[升幂定理](https://oi-wiki.org/math/number-theory/lift-the-exponent/)
[莫比乌斯反演](https://oi-wiki.org/math/number-theory/mobius/#%E8%AF%81%E6%98%8E)
[快速傅里叶变换](https://oi-wiki.org/math/poly/fft/#%E7%A6%BB%E6%95%A3%E5%82%85%E9%87%8C%E5%8F%B6%E5%8F%98%E6%8D%A2)
[Entringer Number](https://oi-wiki.org/math/combinatorics/entringer/#%E4%BA%A4%E6%9B%BF%E7%BD%AE%E6%8D%A2%E4%B8%8E-zigzag-%E6%95%B0)

2023-02-28 20:35 UTC, untitledunrevised commented on docs/math/combinatorics/combination.md
> +如何理解上述公式？我们考虑 $n$ 个人 $m$($m \le n$) 个出来，不排队，不在乎顺序 $\dbinom{n}{m}$。如果在乎排列那么就是 $\mathrm A_n^m$，如果不在乎那么就要除掉重复，那么重复了多少？同样选出的来的 $m$ 个人，他们还要“全排”得 $\mathrm A_n^m$，所以得：
```suggestion
如何理解上述公式？我们考虑 $n$ 个人选 $m$ 个出来（$m \le n$），不排队，不在乎顺序。如果在乎顺序那么就是 $\mathrm A_n^m$，如果不在乎那么就要除掉重复，那么重复了多少？同样选出来的 $m$ 个人，他们还要「全排」得 $m!$，所以得：
```
修标点，修空格，修表述

2023-02-28 20:35 UTC, untitledunrevised commented on docs/math/combinatorics/combination.md
> +从 $n$ 个不同元素中，任取 $m$($m\leq n$) 个元素组成一个集合，叫做从 $n$ 个不同元素中取出 $m$ 个元素的一个组合；从 $n$ 个不同元素中取出 $m$($m\leq n$) 个元素的所有组合的个数，叫做从 $n$ 个不同元素中取出 $m$ 个元素的组合数。用符号 $\dbinom{n}{m}$ 来表示，读作「$n$ 选 $m$」。
```suggestion
从 $n$ 个不同元素中，任取 $m \leq n$ 个元素组成一个集合，叫做从 $n$ 个不同元素中取出 $m$ 个元素的一个组合；从 $n$ 个不同元素中取出 $m \leq n$ 个元素的所有组合的个数，叫做从 $n$ 个不同元素中取出 $m$ 个元素的组合数，用符号 $\dbinom{n}{m}$ 来表示，读作「$n$ 选 $m$」。
```
直接 $m \leq n$ 好了，简洁又好看

2023-03-01 03:39 UTC, Great-designer commented
上述问题已修正完毕

2023-04-09 06:20 UTC, Great-designer commented
本pr未增添新内容，仅为样式的简单替换修改

（然而现在却“30 天未响应”）

2023-04-09 07:52 UTC, untitledunrevised approved these changes

2023-05-21 03:35 UTC, Great-designer commented
已经发两遍未响应通知了

2023-05-22 09:42 UTC, Tiphereth-A approved these changes

2023-05-22 09:42 UTC, merged