feat: dark mode
OI-wiki/OI-wiki pull request #4695
Opened 2023-02-03 12:12 UTC by NachtgeistW

- [ ] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

添加 Material for MkDocs 原生支持的暗色模式

2023-02-03 14:17 UTC, Enter-tainer commented on mkdocs.yml
> +      primary: blue
```suggestion
      primary: slate
```

试一试 感觉就是这样

2023-02-03 14:30 UTC, NachtgeistW commented on mkdocs.yml
> +      primary: blue
但 slate 不是 color 是 color scheme

2023-02-03 15:06 UTC, Enter-tainer commented
暴力修改 md-primary-fg-color 好像有点问题， 比如链接的颜色也变成了这个颜色

<img width="322" alt="image" src="https://user-images.githubusercontent.com/25521218/216637002-6324d5c1-83a9-47b0-a9c1-4cc1822ce743.png">

这是因为链接的颜色是 --md-typeset-a-color，而在css中，它的定义就是 primary-fg-color

2023-02-04 01:56 UTC, Enter-tainer commented
加入暗色模式之后， https://github.com/OI-wiki/OI-wiki/blob/master/docs/_static/js/extra.js 和 主页的那些按钮是不是都可以扬了

因为我看localstorage里面，已经存了palette的信息

```
{"index":1,"color":{"scheme":"slate","primary":"blue","accent":"blue"}}
```

2023-02-04 02:54 UTC, NachtgeistW commented
> 加入暗色模式之后， https://github.com/OI-wiki/OI-wiki/blob/master/docs/_static/js/extra.js 和 主页的那些按钮是不是都可以扬了
> 
> 因为我看localstorage里面，已经存了palette的信息
> 
> ```
> {"index":1,"color":{"scheme":"slate","primary":"blue","accent":"blue"}}
> ```
> 
> <blockquote><img src="https://opengraph.githubassets.com/cc22c504d3cb190b1288edc1a62ad60c7666738072e70902d9c9c2a2b5473aa9/OI-wiki/OI-wiki" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/OI-wiki/OI-wiki">OI-wiki/extra.js at master · OI-wiki/OI-wiki</a></strong></div><div>:star2: Wiki of OI / ICPC for everyone. （某大型游戏线上攻略，内含炫酷算术魔法） - OI-wiki/extra.js at master · OI-wiki/OI-wiki</div></blockquote>

不清楚，可以扬一下试试（

2023-02-04 10:28 UTC, diauweb commented
NachtgeistW/OI-wiki#2

2023-02-04 11:14 UTC, ouuan commented
https://github.com/NachtgeistW/OI-wiki/pull/2#issuecomment-1416723821

我这刚加载出来的时候 giscus 主题是错的。为什么不改成用 JS 添加 giscus，除了跨仓库合并麻烦，还有什么原因吗

2023-02-04 11:27 UTC, ouuan commented
是不是应该在主仓库指定一下 mkdocs-material 版本，感觉没啥坏处，也不会需要经常更新

2023-02-04 11:30 UTC, Menci commented
@ouuan 对，这个是很常见的实践

2023-02-05 03:53 UTC, Enter-tainer commented
目前的giscus暗色好像还是有点问题：把页面切换成暗色后，再访问其他页面，会发现giscus依然是亮色的。 可能还是去改模板比较好

2023-02-09 13:25 UTC, Enter-tainer commented
看起来现在的dark mode工作的很好很正常

2023-02-10 05:23 UTC, Enter-tainer submitted a review, later dismissed
cool，之后要做的事情

- 找个时间把mkdocs里面的分支合上，并更新submodule的commit hash

2023-02-10 05:32 UTC, ouuan requested changes

2023-02-10 05:32 UTC, ouuan commented on docs/index.md
> -  document.getElementsByClassName('md-nav__title')[1].click()
这个和主题颜色无关，删了之后 #758 的问题又出现了。但感觉这个 fix 有点脏啊，有没有更好的处理方式（

2023-02-10 05:52 UTC, diauweb commented on docs/index.md
> -  document.getElementsByClassName('md-nav__title')[1].click()
暂时把这行加回来了 更好的处理方式可以继续讨论

2023-02-10 05:54 UTC, ouuan approved these changes

2023-02-10 05:54 UTC, Enter-tainer approved these changes

2023-02-10 06:28 UTC, merged