Update: 添加了哈希碰撞的多种解决方法，完善了个别git指令
OI-wiki/OI-wiki pull request #4713
Opened 2023-02-10 05:31 UTC by junwang0510

- [ ] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

2023-02-12 08:09 UTC, WAAutoMaton commented on docs/ds/hash.md
> +- 二次探查法（quadratic probing）：如果在 `d` 处发生冲突，就依次检查 `d + 1`, `d + 4`, `d + 9`......（i次探查后的位置 = (hash(key) + i^2) % TableSize)。缺点：容易导致secondary clustering, hash到同样初始位置的keys会重复很多探查步骤。并且，随着列表存的数据增加，二次探查法会陷入循
正确实现的二次探测不太可能出现“无法插入”的情况。如，当哈希表大小M为质数时，二次探测至少可以遍历 M/2 个位置；使用特定的参数还可以完整遍历整个表。
二次探测的主要缺点是：取模运算效率较低；扩增哈希表时要寻找接近特定大小的质数。
（以上内容来自我们课件，若有问题请指出

2023-02-12 09:35 UTC, junwang0510 commented on docs/ds/hash.md
> +- 二次探查法（quadratic probing）：如果在 `d` 处发生冲突，就依次检查 `d + 1`, `d + 4`, `d + 9`......（i次探查后的位置 = (hash(key) + i^2) % TableSize)。缺点：容易导致secondary clustering, hash到同样初始位置的keys会重复很多探查步骤。并且，随着列表存的数据增加，二次探查法会陷入循
感谢指正，我写的不够严谨，正确实现的二次探测确实不会出现无法插入的情况。

补充一下：如果哈希表大小M为质数并且 λ < 1/2的话，二次探查法会在 <= M/2次探查下找到一个空位以插入数据。

另外，我赞成你提出的二次探测的主要缺点。

2023-02-19 03:09 UTC, 383494 requested changes

2023-02-19 03:09 UTC, 383494 commented on docs/ds/hash.md
> +- 线性探查法（linear probing）：如果在 `d` 处发生冲突，就依次检查 `d + 1`，`d + 2`.....（i次探查后的位置 = (hash(key) + i) % TableSize)。 缺点：容易导致primary clustering, 大部分数据集中在列表的一部分，导致后期的数据查找极慢（O(n))
```suggestion
- 线性探查法（linear probing）：如果在 `d` 处发生冲突，就依次检查 `d + 1`，`d + 2`.....（$i$ 次探查后的位置为 `(hash(key) + i) % TableSize)`）。 缺点：容易导致 primary clustering，大部分数据集中在列表的一部分，导致后期的数据查找极慢（O(n)）
```

2023-02-20 14:08 UTC, Tiphereth-A reviewed
另外，请注意 https://oi-wiki.org/intro/htc/#pull-request-%E4%BF%A1%E6%81%AF%E6%A0%BC%E5%BC%8F%E8%A7%84%E8%8C%83

2023-02-20 14:08 UTC, Tiphereth-A commented on docs/tools/git.md
> +利用 `git branch <分支名称>` 命令可以创建分支，`git switch <分支名称>` 命令可以切换分支，`git switch -c <分支名称>` 命令可以创建分支并切换到这个新分支。
一个 PR 应该只做一件事，这个建议分到另外一个 PR 中

2023-04-16 00:16 UTC, closed without merging