fix(math/game-theory/misere-game.md): 改进格式
OI-wiki/OI-wiki pull request #4754
Opened 2023-02-25 12:41 UTC by Suyun114

主要修正了对 LaTeX 公式的滥用。

- [ ] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

2023-02-25 12:42 UTC, Suyun114 commented
注意：`math/game-theory/misere-game.md` 在最后一部分仍然存在大小写混乱导致几乎不可读的问题。

2023-02-28 19:09 UTC, untitledunrevised requested changes
hi suyun，竟然在这也看到你了（
既然是修排版的 pr，那我也来重新调整一下页面布局，修一下标点符号，修一下语序、表述什么的。

2023-02-28 19:09 UTC, untitledunrevised commented on docs/math/game-theory/misere-game.md
> +反常游戏、反 Nim 游戏的 [定义](./intro.md#反常游戏)。
```suggestion
前置知识：[反常游戏与反 Nim 游戏的定义](./intro.md#反常游戏)。
```

2023-02-28 19:09 UTC, untitledunrevised commented on docs/math/game-theory/misere-game.md
> +以反 Nim 游戏为例，这里给出反 Nim 游戏的结论以及证明：
```suggestion
```

2023-02-28 19:09 UTC, untitledunrevised commented on docs/math/game-theory/misere-game.md
> +也就是说 **当至少 2 个 $a_{i}>1,T\neq 0$ 时为 N 态，否则为 P 态。**
```suggestion
也就是说 **当 $T\neq 0$ 且存在至少 2 个 $a_{i}>1$ 时，该情况为 N 态，否则为 P 态。**
```

2023-02-28 19:09 UTC, untitledunrevised commented on docs/math/game-theory/misere-game.md
```suggestion

以反 Nim 游戏为例，下面给出反 Nim 游戏的结论以及证明：

```

2023-02-28 19:13 UTC, untitledunrevised requested changes

2023-02-28 19:13 UTC, untitledunrevised commented on docs/math/game-theory/misere-game.md
>  综上，1 和 2 皆得证。结论得证。
```suggestion
综上，结论 1 和 2 皆得证。证毕。
```

2023-02-28 19:25 UTC, untitledunrevised commented on docs/math/game-theory/misere-game.md
> +所以在情况 b 下，小情况 b 为 N 态，a 为 P 态。
```suggestion
所以在情况 B 下，小情况 b 为 N 态，小情况 a 为 P 态。
```

2023-04-23 00:16 UTC, closed without merging