feat(intro/symbol.md): 用于 OI wiki 的数学符号表
OI-wiki/OI-wiki pull request #4760
Opened 2023-02-26 20:18 UTC by Tiphereth-A

- [x] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

resolve #4587

todo:

- [ ] 画坐标系的图

2023-02-26 20:27 UTC, Tiphereth-A commented
张量和一些特殊函数因为 OI 中用处不大就先去掉了

2023-02-27 04:17 UTC, Enter-tainer requested changes

2023-02-27 04:17 UTC, Enter-tainer commented on docs/intro/format.md
> +-   双目运算符（如 $+$,$-$,$/$）前后均需插入空格，如 $1-(-2)+3.14~/~4$. 若 $/$ 用于表示分数，则不需插入空格，如 $5/4$.
还有这事

2023-02-27 04:17 UTC, Enter-tainer commented on docs/intro/format.md
> +-   双目运算符（如 $+$,$-$,$/$）前后均需插入空格，如 $1-(-2)+3.14~/~4$. 若 $/$ 用于表示分数，则不需插入空格，如 $5/4$.
但是这里的示例也没加空格？

2023-02-27 04:17 UTC, Enter-tainer commented on docs/intro/format.md
> +-   如果表达式须分成多行书写，则应遵循如下换行规则：
感觉这种适合给bot做。。本pr还是应该focus在数学符号上？

2023-02-27 04:17 UTC, Enter-tainer commented on docs/intro/format.md
> +    -   将换行符放在 $=$,$+$,$-$,$\pm$,$\mp$ 之前，如果有必要，也可放在 $\times$,$\cdot$,$/$ 之前。如：
说实话，渲染之后应该也看不出来你源代码里面是怎么换行的吧

2023-02-27 04:17 UTC, Enter-tainer commented on docs/intro/symbol.md
> +| n1.1<a id="n1.1" href="#n1.1">¶</a> | $p \land q$                                          | $p$ 和 $q$ 的合取                   | $p$ 与 $q$
这个页面怎么这么多html。。

2023-02-27 04:17 UTC, Enter-tainer commented on docs/intro/symbol.md
> +| n1.1<a id="n1.1" href="#n1.1">¶</a> | $p \land q$                                          | $p$ 和 $q$ 的合取                   | $p$ 与 $q$
如果是复制的什么国标的话，感觉还不如不复制

2023-02-27 04:46 UTC, Great-designer commented on docs/intro/symbol.md
> +| n2.2<a id="n2.2" href="#n2.2">¶</a>    | $y \notin A$                               | $y$ 不属于 $A$,<br>$y$ 不是集合 $A$ 中的元素                                                                           | $
“notni”似乎不能通过LaTeX building。详见LaTeX build错误报告。

2023-02-27 04:54 UTC, Tiphereth-A commented on docs/intro/symbol.md
> +| n1.1<a id="n1.1" href="#n1.1">¶</a> | $p \land q$                                          | $p$ 和 $q$ 的合取                   | $p$ 与 $q$
html 是用来打标签方便索引的

2023-02-27 04:55 UTC, Tiphereth-A commented on docs/intro/format.md
> +-   双目运算符（如 $+$,$-$,$/$）前后均需插入空格，如 $1-(-2)+3.14~/~4$. 若 $/$ 用于表示分数，则不需插入空格，如 $5/4$.
这里叙述有点歧义，这里的空格指的是渲染之后的效果要用6空格，LaTeX 默认是会加的

2023-02-27 04:56 UTC, Tiphereth-A commented on docs/intro/format.md
> +    -   将换行符放在 $=$,$+$,$-$,$\pm$,$\mp$ 之前，如果有必要，也可放在 $\times$,$\cdot$,$/$ 之前。如：
这个指的是长式子的折行，行间公式默认不会自动折行

2023-02-27 04:57 UTC, Tiphereth-A commented on docs/intro/format.md
> +-   如果表达式须分成多行书写，则应遵循如下换行规则：
这段是从 ISO 搬过来的，删掉也行

2023-02-27 04:59 UTC, Tiphereth-A commented on docs/intro/symbol.md
> +| n1.1<a id="n1.1" href="#n1.1">¶</a> | $p \land q$                                          | $p$ 和 $q$ 的合取                   | $p$ 与 $q$
另外表格里似乎不能用 markdown 的换行和列表语法，所以这些也是用的 html

2023-02-27 05:41 UTC, Great-designer commented
目前的预览 https://deploy-preview-4760--oi-wiki.netlify.app/

状况一塔湖图。猜测是LaTeX渲染问题，需要先把相关渲染问题解决之后才能正常预览

2023-02-27 08:56 UTC, Tiphereth-A commented on docs/intro/symbol.md
> +| n1.1<a id="n1.1" href="#n1.1">¶</a> | $p \land q$                                          | $p$ 和 $q$ 的合取                   | $p$ 与 $q$
看起来表格里的 html 会导致 Build LaTeX document 失败，那就先删了 🤔

2023-02-27 10:27 UTC, Enter-tainer reviewed
没看完 先看了一部分

2023-02-27 10:27 UTC, Enter-tainer commented on docs/intro/symbol.md
> +| n1.4 | $p \Rightarrow q$                                 | $p$ 蕴含 $q$; 若 $p$ 为真，则 $q$ 为真 | $q \Leftarrow p$ 和 $p \Rightarrow q$ 同义。$\Rightarrow$ 称为实质蕴涵。也可使用 $\implies$ 与 $\impliedby$
这个，应该是使用 implies 系列的。不应该使用前面的

长度不一样呀！前面的不够长

2023-02-27 10:27 UTC, Enter-tainer commented on docs/intro/symbol.md
> +| n3.1  | $\mathsf{N}$ | 自然数集              | $\mathsf{N} = \{0, 1, 2, 3, \dots\}$;$\mathsf{N}^* = \mathsf{N}_+ = \{1, 2, 3, \dots\}$; 可用如下方式添加其他限制：$\mathsf{N}_{> 5} = \{n \in \mathsf{N} ~\vert~ n > 5
这里又变成 mathsf 了...现在已经有 bb bf sf 三种流派了

2023-02-27 10:31 UTC, Tiphereth-A commented on docs/intro/symbol.md
> +| n1.4 | $p \Rightarrow q$                                 | $p$ 蕴含 $q$; 若 $p$ 为真，则 $q$ 为真 | $q \Leftarrow p$ 和 $p \Rightarrow q$ 同义。$\Rightarrow$ 称为实质蕴涵。也可使用 $\implies$ 与 $\impliedby$
国标和 ISO 都是写的短箭头，还允许使用 $\leftarrow$ 之类的，很怪。一会修了

2023-02-27 10:32 UTC, Tiphereth-A commented on docs/intro/symbol.md
> +| n3.1  | $\mathsf{N}$ | 自然数集              | $\mathsf{N} = \{0, 1, 2, 3, \dots\}$;$\mathsf{N}^* = \mathsf{N}_+ = \{1, 2, 3, \dots\}$; 可用如下方式添加其他限制：$\mathsf{N}_{> 5} = \{n \in \mathsf{N} ~\vert~ n > 5
那要不就 bb 吧 🤔

2023-02-27 10:34 UTC, Enter-tainer commented on docs/intro/symbol.md
> +| n1.4 | $p \Rightarrow q$                                 | $p$ 蕴含 $q$; 若 $p$ 为真，则 $q$ 为真 | $q \Leftarrow p$ 和 $p \Rightarrow q$ 同义。$\Rightarrow$ 称为实质蕴涵。也可使用 $\implies$ 与 $\impliedby$
擦 还有这事，那这个可能还需要高手来讨论一下

2023-02-27 10:34 UTC, Enter-tainer commented on docs/intro/symbol.md
> +| n3.1  | $\mathsf{N}$ | 自然数集              | $\mathsf{N} = \{0, 1, 2, 3, \dots\}$;$\mathsf{N}^* = \mathsf{N}_+ = \{1, 2, 3, \dots\}$; 可用如下方式添加其他限制：$\mathsf{N}_{> 5} = \{n \in \mathsf{N} ~\vert~ n > 5
感觉这个也不好说..可能需要讨论

2023-02-27 10:35 UTC, Tiphereth-A commented on docs/intro/symbol.md
> +| n1.4 | $p \Rightarrow q$                                 | $p$ 蕴含 $q$; 若 $p$ 为真，则 $q$ 为真 | $q \Leftarrow p$ 和 $p \Rightarrow q$ 同义。$\Rightarrow$ 称为实质蕴涵。也可使用 $\implies$ 与 $\impliedby$
那这个就先放一下

2023-02-27 10:37 UTC, Tiphereth-A commented on docs/intro/symbol.md
> +| n3.1  | $\mathsf{N}$ | 自然数集              | $\mathsf{N} = \{0, 1, 2, 3, \dots\}$;$\mathsf{N}^* = \mathsf{N}_+ = \{1, 2, 3, \dots\}$; 可用如下方式添加其他限制：$\mathsf{N}_{> 5} = \{n \in \mathsf{N} ~\vert~ n > 5
另外这个 sf 实际上是目测的，也许不太行

2023-02-27 12:14 UTC, Great-designer commented
这个pr没有使用长表格longtabu，也没有使用prevdepth命令，而目前的报错里面出现了这个。

2023-02-27 14:08 UTC, Tiphereth-A commented
LaTeX 文档构建我本地跑是正常的

https://mega.nz/file/JNsmhBjB#UecM4GU1M3q-qJla3as6aTxUBAZpMuFoUJhT688USHs

2023-02-27 16:28 UTC, Tiphereth-A commented on docs/intro/symbol.md
> +| n3.1  | $\mathsf{N}$ | 自然数集              | $\mathsf{N} = \{0, 1, 2, 3, \dots\}$;$\mathsf{N}^* = \mathsf{N}_+ = \{1, 2, 3, \dots\}$; 可用如下方式添加其他限制：$\mathsf{N}_{> 5} = \{n \in \mathsf{N} ~\vert~ n > 5
国标是 bf, ISO 是 sf, bb 也挺常用的 🤯

2023-02-28 04:02 UTC, Enter-tainer commented
https://tex.stackexchange.com/questions/427283/improper-prevdepth-when-using-multicols LaTeX 可能是因为这个

2023-02-28 04:27 UTC, Tiphereth-A commented
> https://tex.stackexchange.com/questions/427283/improper-prevdepth-when-using-multicols LaTeX 可能是因为这个
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/d4fe86ccaf523d3a8ade918ea79b3ee2aa84cd0840af292fdf4483fb2140d4c3/68747470733a2f2f63646e2e737374617469632e6e65742f53697465732f7465782f496d672f6170706c652d746f7563682d69636f6e40322e706e673f763d656166323662343631373230">TeX - LaTeX Stack Exchange**["Improper \prevdepth" when using multicols*](https://tex.stackexchange.com/questions/427283/improper-prevdepth-when-using-multicols)**As I wanted to fill the first column before going to the next one, I was using the environment \begin{multicols*}\end{multicols*}. When I compile the following scrip I have the error: "Improper \

神奇，这个换行似乎不能从 markdown 引入，构建 tex 文档的时候会忽略掉 `<br>`，加句点也不行，也许加汉字就可以了 🤔

2023-02-28 04:37 UTC, Enter-tainer commented
@Tiphereth-A 可以考虑去改一下exporter？另外为啥你本地能跑呢？是不是我们升级一下ci的latex版本也许

2023-02-28 04:51 UTC, Tiphereth-A commented
> @Tiphereth-A 可以考虑去改一下exporter？另外为啥你本地能跑呢？是不是我们升级一下ci的latex版本也许

```
$ apt search texlive-full
Sorting... Done
Full Text Search... Done
texlive-full/jammy,now 2021.20220204-1 all [installed]
  TeX Live: metapackage pulling in all components of TeX Live
```

系统是 Ubuntu 2204

看起来似乎是我这边的更老一些 🤯

2023-02-28 04:52 UTC, Enter-tainer commented
思考，要不我晚上看看怎么在exporter里面加个换行吧。或者你有空的话看看也行（

2023-02-28 06:30 UTC, Great-designer commented
@24OI-bot lint please

2023-02-28 11:17 UTC, Tiphereth-A commented
https://github.com/OI-wiki/OI-Wiki-export/pull/34 didn't work，等高人帮忙了

2023-02-28 11:23 UTC, Enter-tainer commented
@Tiphereth-A 思考，要不给export加一个ignore list。。。

2023-02-28 11:31 UTC, Tiphereth-A commented
> @Tiphereth-A 思考，要不给export加一个ignore list。。。

这样似乎会破坏 tex 文件间的引用...而且感觉要是允许用只含 `\label` 的空文档替换部分页面的话观感怪怪的 🤔

2023-02-28 14:49 UTC, Great-designer commented
> [OI-wiki/OI-Wiki-export#34](https://github.com/OI-wiki/OI-Wiki-export/pull/34) didn't work，等高人帮忙了

得再随意更新一下本pr，让评测机重新跑一次

2023-02-28 14:58 UTC, Tiphereth-A commented
> > [OI-wiki/OI-Wiki-export#34](https://github.com/OI-wiki/OI-Wiki-export/pull/34) didn't work，等高人帮忙了
> 
> 得再随意更新一下本pr，让评测机重新跑一次

已经重跑两遍了，你可以看一下记录

2023-03-01 12:00 UTC, Great-designer commented
牛的！不妨在格式手册里补充一点：

表格中的单格内换行使用br标记，不可使用公式中换行的双反斜线。

2023-03-02 06:30 UTC, Great-designer approved these changes
整体不错

2023-03-02 06:30 UTC, Great-designer commented on docs/intro/symbol.md
> +| n4.3  | $a := b$             | $a$ 定义为 $b$        | 例如：<br>$\mathbf{p} := m\mathbf{v}$, 其中 $\mathbf{p}$ 为动量，$m$ 为质量，$\mathbf{v}$ 为速度。                    |
建议更换一个例子，不再使用物理学相关

2023-03-02 06:30 UTC, Great-designer commented on docs/intro/symbol.md
> +| n4.4  | $a~\hat{=}~b$        | $a$ 相当于 $b$        | 例如：<br>当地图上的 $1~\rm{cm}$ 对应实际上的 $10~\rm{km}$ 时，可以记作 $1~\rm{cm}~\hat{=}~10~\rm{km}$.                  |
建议更换一个例子，不再使用度量衡相关

2023-03-02 06:30 UTC, Great-designer commented on docs/intro/symbol.md
> +| n12.2  | $A + B$                            | 矩阵 $A$ 和 $B$ 的和     | $(A + B)_{ij} = (A)_{ij} + (B)_{ij}$;<br>矩阵 $A$ 和 $B$ 的行数和列数必须相同。                         |
```suggestion
| n12.2  | $A + B$                            | 矩阵 $A$ 和 $B$ 的和     | $(A + B)_{ij} = (A)_{ij} + (B)_{ij}$;<br>矩阵 $A$ 和 $B$ 必须同型。                         |
```

2023-03-02 06:30 UTC, Great-designer commented on docs/intro/symbol.md
> +| n12.2  | $A + B$                            | 矩阵 $A$ 和 $B$ 的和     | $(A + B)_{ij} = (A)_{ij} + (B)_{ij}$;<br>矩阵 $A$ 和 $B$ 的行数和列数必须相同。                         |
这样书写可以避免歧义

2023-03-02 07:11 UTC, Tiphereth-A commented on docs/intro/symbol.md
> +| n4.4  | $a~\hat{=}~b$        | $a$ 相当于 $b$        | 例如：<br>当地图上的 $1~\rm{cm}$ 对应实际上的 $10~\rm{km}$ 时，可以记作 $1~\rm{cm}~\hat{=}~10~\rm{km}$.                  |
这个符号 OI 中应该没用，感觉这条可以删了

2023-03-05 13:09 UTC, Enter-tainer reviewed
别的地方还好。另外pdf的效果居然意外的还不错

2023-03-05 13:09 UTC, Enter-tainer commented on docs/intro/symbol.md
> +| n2.11 | $\displaystyle \bigcup\limits_{i=1}^n A_i$ | 集合 $A_1, A_2, \dots, A_n$ 的并集   | $\displaystyle \bigcup\limits_{i=1}^n A_i=A_1\cup A_2\cup \dots \cup A_n$;<br>也可使用 $\displaystyle \bigcup\noli
逗号后面应该空一格

2023-03-05 13:09 UTC, Enter-tainer commented on docs/intro/symbol.md
> +| n6.5  | $a \cdot b$;<br>$a \times b$;<br>$ab$                       | $a$ 乘 $b$                             | 若出现小数点，则应只使用 $\times$;<br>部分用例参见 n2.16,n2.17,n14.11,n14.12
逗号后面要有空格，洋文排版的规则是这样的

2023-03-05 13:09 UTC, Enter-tainer commented on docs/intro/symbol.md
> +| n6.5  | $a \cdot b$;<br>$a \times b$;<br>$ab$                       | $a$ 乘 $b$                             | 若出现小数点，则应只使用 $\times$;<br>部分用例参见 n2.16,n2.17,n14.11,n14.12
其他地方还有类似case, 需要改一下

2023-03-05 13:49 UTC, Tiphereth-A commented on docs/intro/symbol.md
> +| n2.11 | $\displaystyle \bigcup\limits_{i=1}^n A_i$ | 集合 $A_1, A_2, \dots, A_n$ 的并集   | $\displaystyle \bigcup\limits_{i=1}^n A_i=A_1\cup A_2\cup \dots \cup A_n$;<br>也可使用 $\displaystyle \bigcup\noli
bot 会把 `$foo$, $bar$` 改成 `$foo$,$bar$`, 感觉应该是 bot 的 bug 🤔

2023-03-05 13:50 UTC, Tiphereth-A commented on docs/intro/symbol.md
> +| n6.5  | $a \cdot b$;<br>$a \times b$;<br>$ab$                       | $a$ 乘 $b$                             | 若出现小数点，则应只使用 $\times$;<br>部分用例参见 n2.16,n2.17,n14.11,n14.12
fixed

2023-03-06 05:12 UTC, Enter-tainer commented on docs/intro/symbol.md
> +| n2.11 | $\displaystyle \bigcup\limits_{i=1}^n A_i$ | 集合 $A_1, A_2, \dots, A_n$ 的并集   | $\displaystyle \bigcup\limits_{i=1}^n A_i=A_1\cup A_2\cup \dots \cup A_n$;<br>也可使用 $\displaystyle \bigcup\noli
可能需要去改改 remark-math-space？不过我也不太确定。。要不先merge了也行。。

2023-03-06 05:21 UTC, Tiphereth-A commented on docs/intro/symbol.md
> +| n2.11 | $\displaystyle \bigcup\limits_{i=1}^n A_i$ | 集合 $A_1, A_2, \dots, A_n$ 的并集   | $\displaystyle \bigcup\limits_{i=1}^n A_i=A_1\cup A_2\cup \dots \cup A_n$;<br>也可使用 $\displaystyle \bigcup\noli
先用中文逗号代替了，至少观感上好看一些 😇

2023-03-06 12:50 UTC, Tiphereth-A commented
> 这好像还没写……这是之前出现的红叉bug，不知现在修好了没有
> 
> 如果已经修好了这个红叉bug，就不必写了

不是 bug，之前我本地和 OI Wiki 这边行为不同是宏包的版本差异导致的

2023-03-06 12:54 UTC, Enter-tainer approved these changes

2023-03-07 04:17 UTC, Great-designer commented
> > 这好像还没写……这是之前出现的红叉bug，不知现在修好了没有
> > 如果已经修好了这个红叉bug，就不必写了
> 
> 不是 bug，之前我本地和 OI Wiki 这边行为不同是宏包的版本差异导致的

那既然已经通过了就算了吧

2023-03-18 10:00 UTC, Enter-tainer commented
anyone take a look pls

2023-03-21 03:59 UTC, inclyc commented
我不太熟悉这个领域 :)

2023-03-22 07:43 UTC, StudyingFather commented
想问一下如何协调这个符号表和目前已经有的数学等分类下的符号表之间的关系呢 :thinking:

2023-03-22 10:27 UTC, Tiphereth-A commented
> 想问一下如何协调这个符号表和目前已经有的数学等分类下的符号表之间的关系呢 thinking

目前的这个版本是和 https://oi-wiki.org/math/notation/ 兼容的。

至于

- https://oi-wiki.org/basic/complexity/#%E6%B8%90%E8%BF%9B%E7%AC%A6%E5%8F%B7%E7%9A%84%E5%AE%9A%E4%B9%89
- https://oi-wiki.org/math/bit/#%E4%B8%8E%E6%88%96%E5%BC%82%E6%88%96
- https://oi-wiki.org/math/number-theory/quad-residue/#legendre-%E7%AC%A6%E5%8F%B7
- https://oi-wiki.org/math/number-theory/basic/#%E4%BE%8B%E5%AD%90

之类的，目前看来没有冲突，感觉整合过来或者保持原状都是可以的。

2023-03-28 02:49 UTC, StudyingFather approved these changes

2023-03-28 02:49 UTC, merged

2023-03-28 04:44 UTC, Great-designer commented
恭喜