refactor(du.md): 修正描述
OI-wiki/OI-wiki pull request #4767
Opened 2023-03-03 07:19 UTC by Tiphereth-A

- [x] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

resolve #4766

- 修正杜教筛使用情形描述的描述
- 补充杜教筛时间复杂度的推导
- 调整公式格式

2023-03-03 09:58 UTC, Enter-tainer submitted a review, later dismissed

2023-03-05 12:56 UTC, Enter-tainer submitted a review, later dismissed

2023-03-08 03:09 UTC, Great-designer submitted a review, later dismissed

2023-04-10 16:28 UTC, GitPinkRabbit commented
建议补充一个关于

> 无论数论函数 $f$ 是否为积性函数，只要可以快速求出 $\sum_{i=1}^n(f * g)(i)$, 便都可以考虑用杜教筛求 $f$ 的前缀和。

这句话的具体的例子（例题）

2023-04-10 16:41 UTC, Nanarikom requested changes

2023-04-10 16:41 UTC, Nanarikom commented on docs/math/number-theory/du.md
> +杜教筛被用来处理数论函数的前缀和问题。对于求解一个前缀和，杜教筛可以在低于线性时间的复杂度内求解。
```suggestion
杜教筛被用于处理一类数论函数的前缀和问题。对于数论函数 $f$，杜教筛可以在低于线性时间的复杂度内计算 $S(n)=\sum_{i=1}^{n}f(i)$。
```

2023-04-10 16:41 UTC, Nanarikom commented on docs/math/number-theory/du.md
> +## 公式推导
```suggestion
## 算法思想
```

2023-04-10 16:41 UTC, Nanarikom commented on docs/math/number-theory/du.md
> +对于数论函数 $f$，要求我们计算 $S(n)=\sum_{i=1}^{n}f(i)$.
```suggestion

```

2023-04-10 16:41 UTC, Nanarikom commented on docs/math/number-theory/du.md
> +g(1)S(n)=\sum_{i=1}^n(f * g)(i)-\sum_{i=2}^ng(i)S\left(\left\lfloor\frac{n}{i}\right\rfloor\right)
```suggestion
\begin{aligned}
g(1)S(n)	& = \sum_{i=1}^n g(i)S\left(\left\lfloor\frac{n}{i}\right\rfloor\right) - \sum_{i=2}^n g(i)S\left(\left\lfloor\frac{n}{i}\right\rfloor\right) \\
			& = \sum_{i=1}^n (f * g)(i) - \sum_{i=2}^n g(i)S\left(\left\lfloor\frac{n}{i}\right\rfloor\right) \\
\end{aligned}
```

2023-04-10 16:41 UTC, Nanarikom commented on docs/math/number-theory/du.md
> +假如我们可以快速对 $\sum_{i=1}^n(f * g)(i)$ 求和，并用数论分块求解 $\sum_{i=2}^ng(i)S\left(\left\lfloor\frac{n}{i}\right\rfloor\right)$ 就可以在较短时间内求得 $g(1)S(n)$.
```suggestion
假如我们可以构造恰当的数论函数 $g$ 使得：
1. 可以快速计算 $\sum_{i=1}^n(f * g)(i)$；
2. 可以快速计算 $g$ 的单点值以用数论分块求解 $\sum_{i=2}^ng(i)S\left(\left\lfloor\frac{n}{i}\right\rfloor\right)$。
则我们可以在较短时间内求得 $g(1)S(n)$。
```

2023-04-10 16:41 UTC, Nanarikom commented on docs/math/number-theory/du.md
> +如果 $f$ 是积性函数，则我们可以通过线性筛预处理出 $S(1)$ 到 $S(k)$ 的值，此时的 $\sum_i S\left(\left\lfloor \dfrac{n}{i}\right\rfloor\right)$ 中我们只需要计算 $k<\left\lfloor \dfrac{n}{i}\right\rfloor\leq n$ 的部分。设计算这一部分的复杂度为 $T'(n)$，则有：
是否需要考虑 $f$ 无积性的情形？

2023-04-10 16:41 UTC, Nanarikom commented on docs/math/number-theory/du.md
>  由 **狄利克雷卷积**，我们知道：
```suggestion
我们知道：
```
「由狄利克雷卷积可得」听上去就像「由加法可得」、「由乘法可得」...

2023-04-10 16:41 UTC, Nanarikom commented on docs/math/number-theory/du.md
>  对于较大的值，需要用 `map` 存下其对应的值，方便以后使用时直接使用之前计算的结果。
```suggestion
对于较大的值，需要用 `map/unordered_map` 存下其对应的值，方便以后使用时直接使用之前计算的结果。
```

2023-04-12 03:54 UTC, Tiphereth-A commented
> 要不直接贴个 ref 啥的（

例子是我自己编的，还没找到 ref（

2023-04-15 05:56 UTC, Tiphereth-A commented
> 建议补充一个关于
> 
> > 无论数论函数 f 是否为积性函数，只要可以快速求出 ∑i=1n(f∗g)(i), 便都可以考虑用杜教筛求 f 的前缀和。
> 
> 这句话的具体的例子（例题）

done

2023-04-21 03:39 UTC, Nanarikom approved these changes

2023-05-28 03:41 UTC, Enter-tainer approved these changes

2023-05-28 03:42 UTC, merged