增加了一道例题及其做法
OI-wiki/OI-wiki pull request #4806
Opened 2023-03-28 12:53 UTC by SmallTualatin

增加了一道例题

- [ ] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

2023-03-28 13:38 UTC, Enter-tainer commented on docs/contest/dictionary.md
> +??+ note "例题 2 完全平方数"
有link的话，给一个oj上的link

2023-03-28 13:38 UTC, Enter-tainer commented on docs/contest/dictionary.md
> +为了展现压缩算法的威力同时为了精简篇幅，贴了 $len=10^6$ 的代码（它的信息处理方式和题解的方式 **略有不同**）而并非 $len=10^5$ 的代码，前者只有 2k 左右，后者能拿到目前最优解排行第四。
具体是哪里不同呢？不如上面直接讲“略有不同”的那个写法

2023-03-28 13:39 UTC, Enter-tainer commented on docs/contest/dictionary.md
> +为了展现压缩算法的威力同时为了精简篇幅，贴了 $len=10^6$ 的代码（它的信息处理方式和题解的方式 **略有不同**）而并非 $len=10^5$ 的代码，前者只有 2k 左右，后者能拿到目前最优解排行第四。
另外感觉可以再想想这个例题怎么写。。目前有点show off的感觉。。

2023-03-28 13:40 UTC, Enter-tainer commented on docs/contest/dictionary.md
> +注意可见字符塞进程序之前 **需要判断转义字符**，比如 `\` 和 `"` 和 `'`。
这个土质压缩。。也行吧，但是为什么不 b64 呢，通用性还更强一点

2023-04-15 06:21 UTC, Tiphereth-A requested changes

2023-04-15 06:21 UTC, Tiphereth-A commented on docs/contest/dictionary.md
> +    "`GGAOASML2XYVDHWAA2OKUG8TOCNJ0F9VQM=i(IMV?F8]PBHfMN<tFRV5;h\'U@"
```suggestion
    "`GGAOASML2XYVDHWAA2OKUG8TOCNJ0F9VQM=i(IMV?F8]PBHfMN<tFRV5;h\'U@"
```

请注意这一行中的字符 0x19 会导致无法通过 checks，建议使用 base64 等编码方式

2023-04-22 11:28 UTC, Great-designer commented on docs/contest/dictionary.md
> +    "`GGAOASML2XYVDHWAA2OKUG8TOCNJ0F9VQM=i(IMV?F8]PBHfMN<tFRV5;h\'U@"
这不太合理……应该修改checks，而不是本末倒置

2023-04-22 16:38 UTC, Enter-tainer commented on docs/contest/dictionary.md
> +    "`GGAOASML2XYVDHWAA2OKUG8TOCNJ0F9VQM=i(IMV?F8]PBHfMN<tFRV5;h\'U@"
所以说还是应该用正常的base64编码呀！（而不是手搓的怪东西）

2023-04-23 04:52 UTC, Great-designer commented on docs/contest/dictionary.md
> +    "`GGAOASML2XYVDHWAA2OKUG8TOCNJ0F9VQM=i(IMV?F8]PBHfMN<tFRV5;h\'U@"
看来本来在C代码中应该用转义字符的，结果没使用转义字符

（不过C里面似乎也没有东西能转义成ASCII的0x19，至多只能强行对char类型赋值，不知这个代码是怎么跑起来的）

2023-04-23 11:53 UTC, Tiphereth-A commented on docs/contest/dictionary.md
> +    "`GGAOASML2XYVDHWAA2OKUG8TOCNJ0F9VQM=i(IMV?F8]PBHfMN<tFRV5;h\'U@"
> （不过C里面似乎也没有东西能转义成ASCII的0x19，至多只能强行对char类型赋值，不知这个代码是怎么跑起来的）

有没有一种可能，'\x19' 就是 🤔

2023-04-23 14:20 UTC, Great-designer commented on docs/contest/dictionary.md
> +    "`GGAOASML2XYVDHWAA2OKUG8TOCNJ0F9VQM=i(IMV?F8]PBHfMN<tFRV5;h\'U@"
那直接改转义字符就对了，这是代码错误

2023-06-11 00:18 UTC, closed without merging