feat(ds/bst.md):增加平衡性定义，维持平衡性操作的共性和特性分析
OI-wiki/OI-wiki pull request #4966
Opened 2023-07-02 17:19 UTC by yuhuoji

- [x] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

新增图片，内容还没修改完。

2023-08-22 07:39 UTC, r-value requested changes
多处显著格式错误以及需讨论的与标题无关的修改。

2023-08-22 07:39 UTC, r-value commented on docs/ds/bst.md
>      ```
大量的代码重构是否与该PR标题有关？考虑拟一个更合适的标题或者revert掉commit [7d79ded](https://github.com/OI-wiki/OI-wiki/pull/4966/commits/7d79deda534571d48092995a2bfff696af148347)？
另外根据[格式手册：文档的合理性](https://oi.wiki/intro/format/#%E6%96%87%E6%A1%A3%E7%9A%84%E5%90%88%E7%90%86%E6%80%A7)，大幅的覆盖性修改应经过讨论。

2023-08-22 07:39 UTC, r-value commented on docs/ds/bst.md
> +-   若 $root$ 的权值小于 $value$，在 $root$ 的右子树中插入权值为 $value$ 的节点。
请勿滥用 $\LaTeX$ 公式

2023-08-22 07:39 UTC, r-value commented on docs/ds/bst.md
> +````
显著的格式错误。

2023-08-26 12:30 UTC, yuhuoji commented on docs/ds/bst.md
>      ```
已修改pr标题。增加的部分内容与页面开始的”二叉搜索树节点的定义“等内容有关联，考虑到易读性所以重构了页面的部分代码

2023-09-06 13:16 UTC, Marcythm commented on docs/ds/bst.md
> +    TreeNode* remove(TreeNode* root, int value) {
接口使用方法呢？此处不同于一般的删除代码，应当注明此处返回值为删除 value 后的新 root，最好给出一个使用例子如 `root = remove(root, 1)`

2023-09-06 13:16 UTC, Marcythm commented on docs/ds/bst.md
> +    int queryrnk(TreeNode* root, int v) {
建议一以贯之，改成 `queryRank`

2023-09-06 13:16 UTC, Marcythm commented on docs/ds/bst.md
> +[Splay 树](splay.md) 中，对于任意节点的访问操作（搜索、插入还是删除），都会将被访问的节点移动到树的根节点位置。
此处或许可以考虑使用列表格式来举例

2023-09-11 00:00 UTC, Marcythm approved these changes

2023-09-27 23:24 UTC, merged