feat(ds/global-bst.md):add 全局平衡二叉树 (#4405)
OI-wiki/OI-wiki pull request #4977
Opened 2023-07-08 09:42 UTC by yuhuoji

- [x] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

新建页面
增加全局平衡二叉树的内容
#4405

2023-07-10 08:39 UTC, inclyc commented on docs/ds/global-bst.md
> +    inline int read() {
这些 inline 其实没什么用，可以删除

2023-07-10 14:52 UTC, yuhuoji commented on docs/ds/global-bst.md
> +    inline int read() {
已修改

2023-07-23 09:15 UTC, Tiphereth-A reviewed
这个领域我不是很熟悉 😢

2023-08-22 07:56 UTC, r-value requested changes

2023-08-22 07:56 UTC, r-value commented on docs/graph/euler.md
> +    -   恰有 0 或 2 个奇度顶点
无关修改 可能是 [这个 commit](https://github.com/OI-wiki/OI-wiki/pull/4977/commits/1144ac21272b8a20839533de607187656c796257) 引入的

2023-08-22 07:56 UTC, r-value commented on docs/ds/global-bst.md
> +由代码可以看出建树的时间复杂度是*O*(*n*log*n*)。接下来我们可以证明树高是*O*(log*n*) 的：考虑从任意一个点跳父节点到根。跳轻边就相当于在原树中跳到另一条重链，由重链剖分的性质可得跳轻边最多*O*(*n*log*n*）条；因为建二叉树的时候根节点找的是算轻儿子的加权中点，那么跳一次重边算上轻儿子的 size 至少翻倍，所以跳重边最多也是*O*(*n*log*n*) 条。整体
请使用 $\LaTeX$ 公式

2023-10-17 23:52 UTC, Marcythm reviewed
内容上除了大幅混淆 log n 和 n log n 之外没问题。。

2023-10-17 23:52 UTC, Marcythm commented on docs/ds/global-bst.md
> +3.  算上重边和轻边，全局平衡二叉树的高度是 $O(n\log n)$ 级别的。这条是保证全局平衡二叉树时间复杂度的性质。
```suggestion
-   $O(\log n)$ 一条链整体修改。
-   $O(\log n)$ 一条链整体查询。
-   $O(\log n)$ 求最近公共祖先，子树修改，子树查询等，这些复杂度和重链剖分是一样的。

## 主要性质

1.  全局平衡二叉树由很多棵二叉树通过轻边连起来组成，每一棵二叉树维护了原树的一条重链，其中序遍历的顺序就是这条重链深度单调递增的顺序。每个节点都仅出现在一棵二叉树中。
2.  边分为重边和轻边，重边是包含在二叉树中的边，维护的时候就像正常维护二叉树一样，记录左右儿子和父节点。轻边从一颗二叉树的根节点指向它所对应的重链顶端节点的父节点。轻边维护的时候 "认父不认子"，即只能从子节点访问到父节点，不能反过来。注意，全局平衡二叉树中的边和原树中的边没有对应关系。
3.  算上重边和轻边，全局平衡二叉树的高度是 $O(\log n)$ 级别的。这条是保证全局平衡二叉树时间复杂度的性质。
```

2023-10-17 23:52 UTC, Marcythm commented on docs/ds/global-bst.md
> +由代码可以看出建树的时间复杂度是 $O(n\log n)$。接下来我们可以证明树高是 $O(\log n)$ 的：考虑从任意一个点跳父节点到根。跳轻边就相当于在原树中跳到另一条重链，由重链剖分的性质可得跳轻边最多 $O(n\log n)$ 条；因为建二叉树的时候根节点找的是算轻儿子的加权中点，那么跳一次重边算上轻儿子的 size 至少翻倍，所以跳重边最多也是 $O(n\log n)$ 条。整体树
```suggestion
由代码可以看出建树的时间复杂度是 $O(n\log n)$。接下来我们可以证明树高是 $O(\log n)$ 的：考虑从任意一个点跳父节点到根。跳轻边就相当于在原树中跳到另一条重链，由重链剖分的性质可得跳轻边最多 $O(\log n)$ 条；因为建二叉树的时候根节点找的是算轻儿子的加权中点，那么跳一次重边算上轻儿子的 size 至少翻倍，所以跳重边最多也是 $O(\log n)$ 条。整体树高就是 $O(\log n)$ 的。
```
这怎么同一段之内还能搞混的，不懂。。

2023-10-17 23:52 UTC, Marcythm commented on docs/ds/global-bst.md
> +首先是像普通重链剖分一样，一次 dfs 求出每个节点的重儿子。然后从根开始，找到根节点所在的重链，对于这些点的轻儿子递归建树，并连上轻边。然后我们需要给重链上的点建一棵二叉树。我们先把重链上的点存到数组里，求出每个点轻儿子的 size 和 +1。然后我们按照这个求出这条重链的加权中点，把它作为二叉树的根，两边递归建树，并连上重边。
```suggestion
首先是像普通重链剖分一样，一次 DFS 求出每个节点的重儿子。然后从根开始，找到根节点所在的重链，对于这些点的轻儿子递归建树，并连上轻边。然后我们需要给重链上的点建一棵二叉树。我们先把重链上的点存到数组里，求出每个点轻儿子的子树大小之和加一（即该点本身所贡献的 size）。然后我们按照这个求出这条重链的加权中点，把它作为二叉树的根，两边递归建树，并连上重边。
```

2023-10-17 23:52 UTC, Marcythm commented on docs/ds/global-bst.md
> +实际上关于全局平衡二叉树的部分就已经讲完了，剩下的链修改、链查询只需要从要操作的点往根跳，要操作某个点重链上比它深度小的所有点，就相当于在这条重链的二叉树里操作这个点左侧的所有点，可以拆成一系列子树操作，像维护普通二叉树一样维护子树和，打子树加标记就行。这里使用的是标记永久化，其实也是可以标记用 pushdown，子树和用 pushup 的，不过可能不太好写（因为平时处理二叉树都是自上而下，这里
这里口语化有点严重了，建议修改

2023-10-17 23:52 UTC, Marcythm commented on docs/ds/global-bst.md
> +因为树链剖分是 $O(n\log^2 n)$ 的，所以有可能被卡。而我们熟知的 $O(n\log n)$ 的 LCT 又往往加上常数后比树剖还慢。那么有什么既是 $O(n\log n)$ 的，常数又相对较小的方法呢？这个时候全局平衡二叉树就出现了。
为什么是 n log^2 n 的就可能被卡？这里的逻辑有点跳跃了，可能需要修改

2023-10-17 23:58 UTC, Marcythm commented
叙述、介绍引进的部分我觉得可以有更好的讲法
因为全局平衡二叉树、LCT、树链剖分（或者更准确地，我们常说的重链剖分）都是基于「轻重链剖分」这一分析手段来保证复杂度，是有很大的共性的

1. 重链剖分是最朴素的轻重链剖分，获得轻重链后用最一些稍微复杂的数据结构（树状数组、线段树）来维护重链的信息，也就是「单独考虑每一条重链」，在重链之间不做任何额外考虑，仅使用「重链深度 log n」这一性质来 bound 复杂度；
2. LCT 是动态的轻重链剖分，为了在动态情况下维持结构选择了动态平衡树来维护重链信息，这是很自然的选择；
3. 全局平衡二叉树则是重链剖分的改进版本，从它的名字就可以感受到：「全局平衡」，意味着不仅每一条重链是一个平衡的数据结构（重链剖分中的线段树），同时这一些平衡结构之间（按轻重链关系）链接后得到的大结构同样也是平衡的。如何保证这一性质呢？那自然是在建立完全平衡二叉树（线段树）的时候将每个点下辖的结构多少也考虑进去，即每个点非重儿子的 size。

这些都是很自然的推理，我觉得完全可以用更循序渐进的方式介绍，应该易懂得多
这就留待后话了，可能我啥时候有时间有兴趣了自己写一下。。这个 pr 还是先合了吧

2023-10-20 00:06 UTC, Marcythm approved these changes

2023-10-20 00:06 UTC, merged