fix(docs/math/number-theory/sieve.md):对筛法求约数个数部分修正
OI-wiki/OI-wiki pull request #4980
Opened 2023-07-11 19:37 UTC by 1804040636

对筛法求约数个数的代码中意义不明的地方删除:
1. 如果该数是质数，就把该数标记为不是质数->删除
2. 将多余的else删除。

同时对实现部分添加了补充说明

- [ ] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

2023-07-13 17:15 UTC, alphagocc requested changes

2023-07-13 17:15 UTC, alphagocc commented on docs/math/number-theory/sieve.md
> +        d[1] = 1;
这里缩进有点怪异啊

2023-07-13 17:15 UTC, alphagocc commented on docs/math/number-theory/sieve.md
> -                v[i] = 1; tot = tot + 1; p[tot] = i; d[i] = 2; num[i] = 1
也不能说完全没有意义吧

2023-07-13 17:15 UTC, alphagocc commented on docs/math/number-theory/sieve.md
> -                    d[i * p[j]] = d[i] * 2
从语义上来讲原来的代码其实更好一点吧，表示了另一种情况是什么
尽管这两种写法执行上是没有任何区别的

2023-07-13 17:19 UTC, 1804040636 commented on docs/math/number-theory/sieve.md
> -                    d[i * p[j]] = d[i] * 2
> 从语义上来讲原来的代码其实更好一点吧，表示了另一种情况是什么 尽管这两种写法执行上是没有任何区别的

那按照您的意见是保持原有的代码，只增加实现部分的补充说明吗？

2023-07-13 17:22 UTC, 1804040636 commented on docs/math/number-theory/sieve.md
> -                v[i] = 1; tot = tot + 1; p[tot] = i; d[i] = 2; num[i] = 1
> 也不能说完全没有意义吧

这一行的v[i]=1，我初见时感觉有些怪，看完全部代码觉得这个 v[i]=1应该是没有存在的必要的，可能会有一些误导人的因素，因为这一部分其实是基于线性筛的扩展，而线性筛的代码是没有 v[i]=1的存在，要不更改意见为，else保留，但是v[i]=1删除

2023-07-13 17:27 UTC, 1804040636 commented
@alphagocc 您再看看

2023-07-14 07:44 UTC, alphagocc commented on docs/math/number-theory/sieve.md
> +3.  当 $p,q$ 互质时，$num[i]=1,d[i]=d[q]\times(num[i]+1)$。
https://oi.wiki/intro/format/#%E4%BE%8B-3
建议参照格式手册修改此处公式

2023-07-15 10:52 UTC, alphagocc commented on docs/math/number-theory/sieve.md
> +1.  当 $i$ 为质数时，$num[i] = 1,d[i] = 2$，设 $q = \lfloor \dfrac{i}{p} \rfloor$，$p$ 为 $i$ 的最小质因子。
不是这里啊。
我的意思是中括号是不正确的
（抱歉我上次没有说清楚）

2023-07-15 12:20 UTC, Tiphereth-A commented on docs/math/number-theory/sieve.md
> +1.  当 $i$ 为质数时，$num[i] = 1,d[i] = 2$，设 $q = \lfloor \dfrac{i}{p} \rfloor$，$p$ 为 $i$ 的最小质因子。
这里要么应该写成代码块，要么应该写成 $\textit{num}_i\gets 1$ 这种

2023-07-15 16:44 UTC, 1804040636 commented
![image](https://github.com/OI-wiki/OI-wiki/assets/64389500/a296e7ba-9b86-47f8-bc24-fd2d01556b40) 渲染结果是这样的

2023-07-15 16:52 UTC, Tiphereth-A commented on docs/math/number-theory/sieve.md
> +1.  当 $i$ 为质数时，$\textit{num}_i \gets 1,\textit{d}_i \gets 2$，设 $q \gets \left\lfloor \dfrac {i}{p} \right\rfloor$，$p$ 为 $i$ 的最小质因子。
```suggestion
1.  当 $i$ 为质数时，$\textit{num}_i \gets 1,\textit{d}_i \gets 2$，设 $q = \left\lfloor \dfrac {i}{p} \right\rfloor$，$p$ 为 $i$ 的最小质因子。
```

2023-07-16 07:24 UTC, 1804040636 commented
@Tiphereth-A 是否只需要修改这一处等于号呢，还是说等式右边是变量或者数学公式时使用 $\gets$，等式右边为常数时使用 $\gets$?

2023-07-16 07:27 UTC, Tiphereth-A commented
> @Tiphereth-A 是否只需要修改这一处等于号呢，还是说等式右边是变量或者数学公式时使用 ←，等式右边为常数时使用 ←?

$\gets$ 表示赋值

2023-07-16 07:32 UTC, Tiphereth-A commented on docs/math/number-theory/sieve.md
既然补充说明了代码，那不妨补充一下 $\textit{num}$ 和 $d$ 的含义？🤔

2023-07-16 07:44 UTC, 1804040636 commented on docs/math/number-theory/sieve.md
在这部分开头是有定义的
![image](https://github.com/OI-wiki/OI-wiki/assets/64389500/c7e52704-d695-4224-9ab1-c17b73f2502f)

2023-07-16 07:46 UTC, 1804040636 commented
> > @Tiphereth-A 是否只需要修改这一处等于号呢，还是说等式右边是变量或者数学公式时使用 ←，等式右边为常数时使用 ←?
> 
> ← 强调赋值，$=$ 强调定义

懂了，那看上去定义只有 q

2023-07-16 07:47 UTC, Tiphereth-A commented on docs/math/number-theory/sieve.md
> +1.  当 $i$ 为质数时，$\textit{num}_i \gets 1,\textit{d}_i \gets 2$，设 $q = \left\lfloor \dfrac {i}{p} \right\rfloor$，$p$ 为 $i$ 的最小质因子。
这里是不是缺了个否则 🤔

```suggestion
1.  当 $i$ 为质数时，$\textit{num}_i \gets 1,\textit{d}_i \gets 2$，否则设 $q = \left\lfloor \dfrac {i}{p} \right\rfloor$，其中 $p$ 为 $i$ 的最小质因子。
```

2023-07-16 08:05 UTC, 1804040636 commented on docs/math/number-theory/sieve.md
> +1.  当 $i$ 为质数时，$\textit{num}_i \gets 1,\textit{d}_i \gets 2$，设 $q = \left\lfloor \dfrac {i}{p} \right\rfloor$，$p$ 为 $i$ 的最小质因子。
应该是没有缺少的，不过实际中的代码和我这里表述有点差距，他是用 i * p[j] 代表我这里的i，用i代表我这里设的 q，但表达的含义都是一样的，这里的代码在依据原理实现的时候而采用了另一种表达形式。
这部分我觉得可以将 否则 改为 同时，然后 其中 保留

2023-07-16 09:12 UTC, Tiphereth-A approved these changes
LGTM

2023-07-16 10:45 UTC, alphagocc approved these changes
LGTM

2023-07-16 10:46 UTC, merged