feat(graph/three-rings-count.md): 添加三元环计数
OI-wiki/OI-wiki pull request #5040
Opened 2023-07-27 06:44 UTC by Molmin

- [x] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

2023-08-12 14:33 UTC, untitledunrevised commented on docs/graph/rings-count.md
> +    若已经枚举 $u,\ v$，那么剩下的枚举量为 $v$ 的出度。
参考[图论相关概念](https://oi-wiki.org/graph/concept/#%E5%BA%A6%E6%95%B0)里面的记号，度数可以用 $d(v)$，出度可以用 $d^{+}(v)$

2023-08-12 14:53 UTC, untitledunrevised requested changes

2023-08-12 14:53 UTC, untitledunrevised commented on docs/graph/rings-count.md
> +    若 $v$ 的出度 $\leq\sqrt m$，由于 $u$ 的个数至多为 $n$，所以这部分时间复杂度为 $\Theta(n\sqrt m)$。
我想并不是大 $\Theta$ 这样的紧界，全文应该都是大 $O$ 符号。
参考[复杂度 - 大 θ 符号](https://oi-wiki.org/basic/complexity/#%E5%A4%A7-%CE%B8-%E7%AC%A6%E5%8F%B7)

2023-08-12 14:53 UTC, untitledunrevised commented on docs/graph/rings-count.md
> +**三元环计数问题** 的目标是遍历这些三元环。
计数问题不一定非要一个一个遍历，这并不是该问题的目标。
比如我可以对简单无向图的邻接矩阵 $A$ 计算 $\mathrm{Tr}(A^3)$ 来得到答案。

2023-08-12 14:53 UTC, untitledunrevised commented on docs/graph/rings-count.md
> +首先给无向边进行定向。我们规定从度数大的点指向度数小的点，度数相同就从编号小的点指向编号大的点。那么此时此图是一张有向无环图。
```suggestion
首先给无向边进行定向。我们规定从度数小的点指向度数大的点，度数相同就从编号小的点指向编号大的点。那么此时此图是一张有向无环图。
```

2023-08-12 14:53 UTC, untitledunrevised commented on docs/graph/rings-count.md
> +**三元环** 指的是一个简单无向图 $G$ 中的一个无序三元组 $(u,\ v,\ w)$ 满足存在三条边分别连接 $(u,\ v)$，$(v,\ w)$ 和 $(w,\ u)$。
有向图也有三元环的概念。参考[图论相关概念 - 路径](https://oi-wiki.org/graph/concept/#%E8%B7%AF%E5%BE%84)

2023-08-21 03:00 UTC, Molmin commented
我那道gym的题没调出来，等我调出来再说（）

2023-08-25 00:52 UTC, Early0v0 commented on docs/graph/rings-count.md
> +    若 $v$ 的出度 $\leq\sqrt m$，由于 $u$ 的个数至多为 $n$，所以这部分时间复杂度为 $\Theta(n\sqrt m)$。
> 我想并不是大 Θ 这样的紧界，全文应该都是大 O 符号。 参考[复杂度 - 大 θ 符号](https://oi-wiki.org/basic/complexity/#%E5%A4%A7-%CE%B8-%E7%AC%A6%E5%8F%B7)

大部分应该是大 $\mathcal O$，但少部分是可以使用 $\Theta$ 的

2023-09-07 04:03 UTC, Tiphereth-A reviewed
因为目前页面的文件名是 `rings-count.md`，所以建议补充一些比较一般的环计数介绍，比如 <https://codeforces.com/problemset/problem/11/D>

2023-09-13 12:57 UTC, Tiphereth-A commented on docs/graph/rings-count.md
> +    对于状态 $f_{i,j}$，枚举下一个结点 $u$。若 $u$ 在集合 $i$ 中且是编号最小的那个（即起点），就将答案加上 $f_{i,j}$。若 $u$ 不在 $i$ 中，就将 $f_{i,j}$ 加上 $f_{i|(1<<u),u}$。
不要在非代码区域使用任何程序设计语言的表示方式

see <https://oi-wiki.org/intro/format/#latex-%E5%85%AC%E5%BC%8F%E7%9A%84%E6%A0%BC%E5%BC%8F%E8%A6%81%E6%B1%82>

2023-09-15 06:12 UTC, yyf525 commented on docs/graph/rings-count.md
> +类似地，**四元环** 就是指四个点 $a,\ b,\ c,\ d$ 满足 $(a,\ b)$，$(b,\ c)$，$(c,\ d)$ 和 $(d,\ a)$ 均有边链接。
```suggestion
类似地，**四元环** 就是指四个点 $a,\ b,\ c,\ d$ 满足 $(a,\ b)$，$(b,\ c)$，$(c,\ d)$ 和 $(d,\ a)$ 均有边连接。
```

2023-09-17 13:20 UTC, Tiphereth-A submitted a review, later dismissed
LGTM

2023-09-18 06:10 UTC, yyf525 approved these changes

2023-09-19 21:40 UTC, untitledunrevised approved these changes

2023-09-20 03:37 UTC, Tiphereth-A commented on docs/graph/rings-count.md
> +    这样会把二元环（即重边）也算上，并且每个非二元环会被计算两次（因为固定起点可以向两个方向走），所以答案为 $\dfrac{cnt-m}2$，其中 $m$ 表示边数。时间复杂度 $O(2^nm)$。
```suggestion
    对于状态 $f(s,i)$，枚举下一个结点 $u$。若 $u$ 在集合 $s$ 中且是编号最小的那个（即起点），就将答案 $A$ 加上 $f(s,i)$。若 $u$ 不在 $s$ 中，就将 $f(s,i)$ 加上 $f(s\cup\{u\},u)$。

    这样会把二元环（即重边）也算上，并且每个非二元环会被计算两次（因为固定起点可以向两个方向走），所以答案为 $\dfrac{A-m}2$，其中 $m$ 表示边数。时间复杂度 $O(2^nm)$。
```

2023-09-20 03:37 UTC, Tiphereth-A commented on docs/graph/rings-count.md
> +    反证法，反设存在环，那么环中的点度数一个比一个大，要形成环，所有点的度数必须相等，但是编号必定不同，矛盾。
```suggestion
    反证法，假设存在环，那么环中的点度数一个比一个大，要形成环，所有点的度数必须相等，但是编号必定不同，矛盾。
```

2023-09-20 03:37 UTC, Tiphereth-A commented on docs/graph/rings-count.md
> +??? note "该图没有环的证明"
其实有个更简洁的证法：可以发现这个定向规则是严格偏序，从而得到的图（Hasse 图）一定是 DAG。不过为了方便初学者，这个证法可以作为补充说明。

2023-09-20 03:37 UTC, Tiphereth-A commented on docs/graph/rings-count.md
> +    $2\leq n\leq 10^5$，$1\leq m\leq\min\{2\times 10^5,\ \dfrac{n(n-1)}2\}$。
```suggestion
    $2\leq n\leq 10^5$，$1\leq m\leq\min\left\{2\times 10^5,\ \dfrac{n(n-1)}2\right\}$。
```

2023-09-20 03:37 UTC, Tiphereth-A commented on docs/graph/rings-count.md
> +    ![](./images/rings-count1.svg)
> An "A-structure" can be seen as a non-directional subgraph G, with a set of four nodes V and a set of five edges E.
>
> If $V=(A,B,C,D)$ and $E=(AB,BC,CD,DA,AC)$, we call G as an "A-structure".

题里面说的图不是 $K_4$

2023-09-20 03:37 UTC, Tiphereth-A commented on docs/graph/rings-count.md
> +考虑枚举排在最后面的点 $a$，此时只需要对于每个比 $a$ 排名更前的点 $c$，都求出有多少个排名比 $a$ 前的点 $b$ 满足 $(a,\ b)$，$(b,\ c)$ 有边。然后只需要从这些 $b$ 中任取两个都能成为一个四元环。求 $b$ 的数量只需要遍历一遍 $b$ 和 $c$ 即可。
这里似乎没考虑度相等的情况？🤔

2023-09-20 03:37 UTC, Tiphereth-A commented on docs/graph/rings-count.md
> +    $$
不要在非代码区域使用任何程序设计语言的表示方式，在数学公式中表示点 $v$ 的度请统一成 $d(v)$

2023-09-20 07:14 UTC, Molmin commented on docs/graph/rings-count.md
> +    ![](./images/rings-count1.svg)
Sorry，画图的时候画错了，解释应该是对的

2023-09-20 09:23 UTC, Molmin commented on docs/graph/rings-count.md
> +考虑枚举排在最后面的点 $a$，此时只需要对于每个比 $a$ 排名更前的点 $c$，都求出有多少个排名比 $a$ 前的点 $b$ 满足 $(a,\ b)$，$(b,\ c)$ 有边。然后只需要从这些 $b$ 中任取两个都能成为一个四元环。求 $b$ 的数量只需要遍历一遍 $b$ 和 $c$ 即可。
度数可能相等，但是排序之后排名互不相同？

我将添加度数相同的说明。

2023-09-20 14:21 UTC, Tiphereth-A commented on docs/graph/rings-count.md
> +    事实上，上述定向规则是一个严格偏序，从而得到的哈斯图（Hasse diagram）一定是一个 DAG。
```suggestion
    事实上，上述定向规则满足严格偏序的条件，所以按此规则构造的图（也即该偏序的 Hasse 图）一定是一个 DAG。
```

2023-09-22 05:40 UTC, Tiphereth-A approved these changes
LGTM, thx

2023-09-22 05:40 UTC, merged