fix(basic/construction.md): 修正了例题 2 中的错别字
OI-wiki/OI-wiki pull request #5055
Opened 2023-07-30 14:21 UTC by Marquis03

- [x] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

2023-07-30 15:43 UTC, inclyc commented on docs/basic/construction.md
> +    和 task1 同样的思路，我们发现 $1$ 必定出现在数列的第一位，否则 $1$ 出现前后的两个前缀积必然相等；而 $n$ 必定出现在数列的最后一位，因为 $n$ 出现位置后的所有前缀积在模意义下都为 $0$。看完几组样例以后发现，所有样例中均有一组合法解满足前缀积在模意义下为 $1,2,3,\cdots,n$，因此我们可以构造出上文所述的数列来满足这个条件。那么我们只需证明这 $n$
这个真的是错别字吗？

2023-07-30 15:43 UTC, inclyc commented on docs/basic/construction.md
> +    看完 $n=3,4,5$ 的情况，我们可以找到一个构造思路。
+1

2023-07-30 15:46 UTC, inclyc approved these changes
虽然感觉 ”手玩“ 并非错别字，但我对此无强烈反对意见

2023-08-05 18:07 UTC, alphagocc commented on docs/basic/construction.md
> +    和 task1 同样的思路，我们发现 $1$ 必定出现在数列的第一位，否则 $1$ 出现前后的两个前缀积必然相等；而 $n$ 必定出现在数列的最后一位，因为 $n$ 出现位置后的所有前缀积在模意义下都为 $0$。看完几组样例以后发现，所有样例中均有一组合法解满足前缀积在模意义下为 $1,2,3,\cdots,n$，因此我们可以构造出上文所述的数列来满足这个条件。那么我们只需证明这 $n$
不应把手玩改成看完吧
看不出来的，除非动手算一下

2023-08-12 14:41 UTC, Tiphereth-A requested changes

2023-08-12 14:41 UTC, Tiphereth-A commented on docs/basic/construction.md
> +    和 task1 同样的思路，我们发现 $1$ 必定出现在数列的第一位，否则 $1$ 出现前后的两个前缀积必然相等；而 $n$ 必定出现在数列的最后一位，因为 $n$ 出现位置后的所有前缀积在模意义下都为 $0$。看完几组样例以后发现，所有样例中均有一组合法解满足前缀积在模意义下为 $1,2,3,\cdots,n$，因此我们可以构造出上文所述的数列来满足这个条件。那么我们只需证明这 $n$
我不支持这处修改，这样改完了之后读起来明显有更强的违和感，而且我不认为「手玩」能够算作错别字。

2023-08-12 14:41 UTC, Tiphereth-A commented on docs/basic/construction.md
> +    看完 $n=3,4,5$ 的情况，我们可以找到一个构造思路。
同上。

2023-09-28 04:55 UTC, Marcythm commented
正如之前的 review 意见所述，您提出的修改似乎并不恰当。
”手玩”一词确实不够正式，但合适的替代或许应该是“手动计算”或近义的词。仅仅“看完”一词所表示的意义显然是相去甚远的。

2023-09-28 09:33 UTC, yuhuoji commented
我觉得“考虑...的情况”“尝试几组样例”“通过分析or计算”之类的措辞比较通顺，也比较正式

2023-09-28 13:36 UTC, Marquis03 reviewed
综合大家的意见和建议后，我发现使用“看完”也确实欠妥，现提出新的修改方案。

2023-10-05 11:40 UTC, Enter-tainer approved these changes
thx

2023-10-05 11:42 UTC, Tiphereth-A approved these changes
LGTM

2023-10-05 11:42 UTC, merged