<fix>(</math/poly/fwt>): <修复了可能引起的乘号误解>
OI-wiki/OI-wiki pull request #5217
Opened 2023-10-19 13:47 UTC by lin-luo-zql

- [ ] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

2023-10-19 14:20 UTC, r-value requested changes

2023-10-19 14:20 UTC, r-value commented on docs/math/poly/fwt.md
> +现在要得到 $FWT[C] = FWT[A] \times FWT[B]$，我们就要构造这个 fwt 的规则。
同17行 使用点乘是合适的

2023-10-19 14:20 UTC, r-value commented on docs/math/poly/fwt.md
> +那么显然会有 $C_{i} = \sum_{i=j|k}A_{j} \times B_{k} \implies FWT[C] = FWT[A] \times FWT[B]$
同17行

2023-10-19 14:44 UTC, lin-luo-zql commented
zqd，是我疏忽了

2023-10-20 00:08 UTC, Marcythm commented on docs/math/poly/fwt.md
> +现在要得到 $FWT[C] = FWT[A] \times FWT[B]$，我们就要构造这个 fwt 的规则。
虽然你说是点乘，但原文这里用的好像也是 * 也即 \ast 而非 \cdot 吧，还是要改的

2023-10-20 00:08 UTC, Marcythm commented on docs/math/poly/fwt.md
> +那么显然会有 $C_{i} = \sum_{i=j|k}A_{j} \times B_{k} \implies FWT[C] = FWT[A] \times FWT[B]$
同上

2023-12-17 00:17 UTC, closed without merging