feat(contest/common-mistakes.md): 添加因环境不同导致的错误
OI-wiki/OI-wiki pull request #5293
Opened 2023-12-02 03:08 UTC by broken-paint

- [x] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

主要是想加入 [这个](https://www.luogu.com.cn/discuss/738046)

2023-12-02 04:52 UTC, HeRaNO commented
1. 这些问题应该可以归类在本页中分类的问题吧
2. 关于「Linux 视文件名为二进制数据」，我第一次听说这样的说法，有出处吗
3. 「Windows 下栈空间不足，导致 CE 或 程序返回 3221225725」，首先「或 程」多了个空格，其次为什么运行时栈空间不足会导致编译期错误，再次为什么会返回 $3221225725$，这个是 Windows 下的返回值吧，Linux 的 SIGSEGV 应该有不一样的返回值
4. 「`%I64d` 说明符」`%I64` 是[转换指示符](https://zh.cppreference.com/w/c/io/fprintf)，或同步其他页面中关于 `%d` 的描述

2023-12-02 05:32 UTC, alphagocc commented on docs/contest/common-mistakes.md
> +-   `scanf` 或 `printf` 使用 `%I64d` 格式指示符在 Linux 下会导致 CE。
来源请求
在 `gcc version 13.2.1 20230912 [revision b96e66] (SUSE Linux) `
中正常编译

2023-12-02 05:37 UTC, HeRaNO commented on docs/contest/common-mistakes.md
> +-   Windows 下栈空间不足，导致 SIGSEGV，Windows 下程序返回 3221225725。
SIGSEGV 是 Linux 下的信号，而且我的问题是为什么栈空间不开大会导致 CE 而不是 RE。

2023-12-02 05:45 UTC, broken-paint commented on docs/contest/common-mistakes.md
> +-   Windows 下栈空间不足，导致 SIGSEGV，Windows 下程序返回 3221225725。
windows下我用VSCode gcc也报错SIGSEGV，而且已经移动到RE里了吧 orz

2023-12-02 05:56 UTC, HeRaNO commented on docs/contest/common-mistakes.md
> +-   Windows 下栈空间不足，导致 SIGSEGV，Windows 下程序返回 3221225725。
> windows下我用VSCode gcc也报错SIGSEGV，而且已经移动到RE里了吧 orz

看错了，但是为什么 Windows 下能报出 Linux 下的信号呢，是 gcc 私货，vscode 私货还是 Windows 已经有了这个东西呢？

返回值建议补充一下 0xC00000FD，这是 [NTSTATUS](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55) 定义的

2023-12-02 05:59 UTC, HeRaNO commented on docs/contest/common-mistakes.md
> +-   Windows 下栈空间不足，导致 SIGSEGV，Windows 下程序返回 3221225725。
看了一下，感觉应该加在「只在程序在本地运行的时候造成影响的错误」里？

2023-12-10 01:27 UTC, broken-paint commented on docs/contest/common-mistakes.md
> +-   Windows 下栈空间不足，导致 SIGSEGV，Windows 下程序返回 3221225725。
>看错了，但是为什么 Windows 下能报出 Linux 下的信号呢，是 gcc 私货，vscode 私货还是 Windows 已经有了这个东西呢？

也有可能是vscode插件加上的，不是很懂。

2023-12-10 01:28 UTC, broken-paint commented on docs/contest/common-mistakes.md
> +-   `scanf` 或 `printf` 使用 `%I64d` 格式指示符在 Linux 下会导致 CE。
我记得ccf给的noip注意事项上面是有的orz 如果是我记错了或者现在已经不会有这个问题了的话我就删了吧

2023-12-25 14:45 UTC, CoelacanthusHex commented
> 1. 这些问题应该可以归类在本页中分类的问题吧
> 
>     2. 关于「Linux 视文件名为二进制数据」，我第一次听说这样的说法，有出处吗

严格来讲是 Linux 文件名并未规定编码，是当作 NUL-termination bytes 处理的。（使用 `char*` 类型的自然结果）但是很多应用和文件系统有自己的规定，比如 NFSv3 是 iso-8859-1(latin1)、NFSv4 是 UTF-8、NTFS 是 UTF-16LE，再比如很多「现代」程序会假设 Linux 的文件名都是 UTF-8 编码，所以这件事仅在理论上成立，事实上 Linux 上通行的是 UTF-8 编码。

> 
>     3. 「Windows 下栈空间不足，导致 CE 或 程序返回 3221225725」，首先「或 程」多了个空格，其次为什么运行时栈空间不足会导致编译期错误，再次为什么会返回 3221225725，这个是 Windows 下的返回值吧，Linux 的 SIGSEGV 应该有不一样的返回值
> 
>     4. 「`%I64d` 说明符」`%I64` 是[转换指示符](https://zh.cppreference.com/w/c/io/fprintf)，或同步其他页面中关于 `%d` 的描述

2023-12-25 15:24 UTC, CoelacanthusHex commented on docs/contest/common-mistakes.md
> +-   `scanf` 或 `printf` 使用 `%I64d` 格式指示符在 Linux 下会导致 CE。
确实是可以正常编译，但是不能正常识别，会被实际识别为按宽度64打印int. 流程是首先在 https://github.com/bminor/glibc/blob/81be2a61dafc168327c1639e97b6dae128c7ccf3/stdio-common/printf-parsemb.c#L143 匹配到 I，随后在 https://github.com/bminor/glibc/blob/81be2a61dafc168327c1639e97b6dae128c7ccf3/stdio-common/printf-parsemb.c#L191 匹配到宽度 64，然后在 https://github.com/bminor/glibc/blob/81be2a61dafc168327c1639e97b6dae128c7ccf3/stdio-common/printf-parsemb.c#L378 匹配到 d.

2023-12-26 06:21 UTC, HeRaNO commented
> > 1. 这些问题应该可以归类在本页中分类的问题吧
> >    
> >    2. 关于「Linux 视文件名为二进制数据」，我第一次听说这样的说法，有出处吗
> 
> 严格来讲是 Linux 文件名并未规定编码，是当作 NUL-termination bytes 处理的。（使用 `char*` 类型的自然结果）但是很多应用和文件系统有自己的规定，比如 NFSv3 是 iso-8859-1(latin1)、NFSv4 是 UTF-8、NTFS 是 UTF-16LE，再比如很多「现代」程序会假设 Linux 的文件名都是 UTF-8 编码，所以这件事仅在理论上成立，事实上 Linux 上通行的是 UTF-8 编码。
> 
> > ```
> > 3. 「Windows 下栈空间不足，导致 CE 或 程序返回 3221225725」，首先「或 程」多了个空格，其次为什么运行时栈空间不足会导致编译期错误，再次为什么会返回 3221225725，这个是 Windows 下的返回值吧，Linux 的 SIGSEGV 应该有不一样的返回值
> > 
> > 4. 「`%I64d` 说明符」`%I64` 是[转换指示符](https://zh.cppreference.com/w/c/io/fprintf)，或同步其他页面中关于 `%d` 的描述
> > ```

最早是觉得这么表达有点怪，没太深层考虑。但是这个表达确实也挺哏的，Windows 下难道文件名就不是二进制数据了吗（或者说归根结底能被计算机处理的数据不都是二进制数据吗），重点应该是 Windows 下会忽略大小写而 Linux 不会，这一点应该是 Windows 和 Linux 的文件系统对待文件名的行为不同导致的。

现在感觉应该不会出现这种问题吧，NOI 系列赛事都会把要求的各种文件名（提交的源代码文件名，输入输出文件名）放在题面首页，大家直接复制就好了，为什么会涉及大小写导致的问题呢？如果解决了下面 `scanf` 和 `printf` 的问题，新加的「因环境不同导致的错误」就只剩这一条了，但是个人不觉得这个错误十分主要，是（不需要细心就）完全可以避免的，直白地说，过于蠢了（无冒犯意味）。

无论如何，感谢你提供的信息。

2023-12-26 06:34 UTC, CoelacanthusHex commented
> > > 1. 这些问题应该可以归类在本页中分类的问题吧
> > >    
> > >    2. 关于「Linux 视文件名为二进制数据」，我第一次听说这样的说法，有出处吗
> > 
> > 
> > 严格来讲是 Linux 文件名并未规定编码，是当作 NUL-termination bytes 处理的。（使用 `char*` 类型的自然结果）但是很多应用和文件系统有自己的规定，比如 NFSv3 是 iso-8859-1(latin1)、NFSv4 是 UTF-8、NTFS 是 UTF-16LE，再比如很多「现代」程序会假设 Linux 的文件名都是 UTF-8 编码，所以这件事仅在理论上成立，事实上 Linux 上通行的是 UTF-8 编码。
> > > ```
> > > 3. 「Windows 下栈空间不足，导致 CE 或 程序返回 3221225725」，首先「或 程」多了个空格，其次为什么运行时栈空间不足会导致编译期错误，再次为什么会返回 3221225725，这个是 Windows 下的返回值吧，Linux 的 SIGSEGV 应该有不一样的返回值
> > > 
> > > 4. 「`%I64d` 说明符」`%I64` 是[转换指示符](https://zh.cppreference.com/w/c/io/fprintf)，或同步其他页面中关于 `%d` 的描述
> > > ```
> 
> 最早是觉得这么表达有点怪，没太深层考虑。但是这个表达确实也挺哏的，Windows 下难道文件名就不是二进制数据了吗（或者说归根结底能被计算机处理的数据不都是二进制数据吗），重点应该是 Windows 下会忽略大小写而 Linux 不会，这一点应该是 Windows 和 Linux 的文件系统对待文件名的行为不同导致的。
> 
> 现在感觉应该不会出现这种问题吧，NOI 系列赛事都会把要求的各种文件名（提交的源代码文件名，输入输出文件名）放在题面首页，大家直接复制就好了，为什么会涉及大小写导致的问题呢？如果解决了下面 `scanf` 和 `printf` 的问题，新加的「因环境不同导致的错误」就只剩这一条了，但是个人觉得这个错误并不十分主要，是（不需要细心就）完全可以避免的，直白地说，过于蠢了（无冒犯意味）。
> 
> 无论如何，感谢你提供的信息。

Windows 下文件名严格使用 UTF-16LE 作为编码，但是 Linux 没有这个规定，内核只是原样从用户空间转发到文件系统驱动，用户空间可以输入任何编码，如果文件系统自己没有拦下（比如 NFSv4），你输入是啥就是啥，直接写进去，读取的时候也同理，文件名被视作当前 locale 编码。而在 Windows 上，Windows 在读取或写入时会进行一次 UTF16LE 和 locale 之间的转换。
简而言之，在 Windows 下以 GBK 编码写入一个文件的文件名，切换到 cp65001 读出来是正常的。但是在 Linux 下以 zh_CN.GBK 写入一个文件名，然后以 zh_CN.UTF-8 读取则会得到乱码。
当然，这在 OI 里没什么影响，OI 里事实上都是 ASCII 的，我只是把信息放这里供 review 参考。

2024-02-08 02:28 UTC, broken-paint commented on docs/contest/common-mistakes.md
> +-   Windows 下栈空间不足，导致 SIGSEGV，Windows 下程序返回 3221225725。
>看错了，但是为什么 Windows 下能报出 Linux 下的信号呢，是 gcc 私货，vscode 私货还是 Windows 已经有了这个东西呢？

见下图

<img width="1280" alt="屏幕截图 2024-02-08 102550" src="https://github.com/OI-wiki/OI-wiki/assets/131476796/d6e587f3-9068-4f2f-a184-19c110d63f6e">

2024-02-08 03:20 UTC, broken-paint commented
蒟蒻没有专业知识，看不懂各位神犇在说什么 orzorzorz

第一条可能不太会有人错，已经删去了

后面这一条还有哪里需要修改吗

2024-02-08 03:24 UTC, alphagocc commented on docs/contest/common-mistakes.md
> +-   Windows 下栈空间不足，导致 SIGSEGV，Windows 下程序返回 3221225725。
个人倾向于插件帮你翻译了一下

2024-02-08 03:35 UTC, alphagocc commented on docs/contest/common-mistakes.md
> +-   Windows 下栈空间不足，导致 SIGSEGV，Windows 下程序返回 3221225725。
> Windows 已经有了这个东西呢？

https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/signal?view=msvc-170

好像是真的有

2024-02-08 03:43 UTC, alphagocc requested changes

2024-02-08 03:43 UTC, alphagocc commented on docs/contest/common-mistakes.md
> +-   Windows 下栈空间不足，导致 SIGSEGV，Windows 下程序返回 3221225725（即 0xC00000FD, NTSTATUS 定义为 `STATUS_STACK_OVERFLOW`)。
```suggestion
-   Windows 下栈空间不足，导致栈空间溢出，Windows 向程序发出 SIGSEGV 信号，程序终止并返回 3221225725（即 0xC00000FD, NTSTATUS 定义为 `STATUS_STACK_OVERFLOW`)。  
```

2024-02-08 03:43 UTC, alphagocc commented on docs/contest/common-mistakes.md
> +    若使用 gcc 编译器，应在编译时加入命令 `-Wl,--stack=SIZE`，其中 `SIZE` 为栈空间大小字节数。
```suggestion
    若使用 gcc 编译器，可在编译时加入命令 `-Wl,--stack=SIZE` 以扩展栈空间，其中 `SIZE` 为栈空间大小字节数。
```

2024-02-08 03:50 UTC, HeRaNO commented
@broken-paint 看一下 Suggested change

2024-02-10 11:55 UTC, alphagocc approved these changes

2024-02-10 11:56 UTC, merged