fix(docs/ds/bst.md): 二叉搜索树的一些方法的实现并不周详 (#5344)
OI-wiki/OI-wiki pull request #5345
Opened 2024-01-01 14:29 UTC by lingkerio

- [x] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

2024-01-02 07:46 UTC, Confr1ngo requested changes
不应该在 struct 声明变量时直接初始化。写一个构造函数。
TreeNode():size(1),count(1),left(nullptr),right(nullptr){}

2024-01-02 15:45 UTC, lingkerio commented
> 不应该在 struct 声明变量时直接初始化。写一个构造函数。 TreeNode():size(1),count(1),left(nullptr),right(nullptr){}

目前已经修改为构造函数的形式

2024-01-03 12:48 UTC, Confr1ngo approved these changes

2024-01-03 12:49 UTC, Confr1ngo approved these changes

2024-01-04 09:40 UTC, lingkerio reviewed
保持了缩进一致

2024-01-04 10:23 UTC, Tiphereth-A approved these changes
LGTM

2024-01-05 08:53 UTC, merged