feat(docs/zeller.md):添加蔡勒公式页面 (#5756)
OI-wiki/OI-wiki pull request #5757
Opened 2024-08-01 05:24 UTC by marscheng1

feat(docs/zeller.md):添加蔡勒公式页面

- [x] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

在杂项中添加 **蔡勒公式** 界面，在其中介绍蔡勒公式的表达式和应用

2024-08-01 05:27 UTC, HeRaNO commented
1. 是针对儒略历法还是格里高利历法
2. 怎么证明得出的这个结论
3. 有参考文献吗

2024-08-01 05:49 UTC, marscheng1 commented
1. 针对格里高利历法，现已加入说明。
2. 暂时不想写证明，做题的话背下来就行。
3. 没有参考文献，直接把背的写下来就行

2024-08-01 06:08 UTC, HeRaNO commented
> 直接把背的写下来了

那我不支持现在合并，请其他 reviewer 看一下吧

2024-08-01 06:10 UTC, qwqAutomaton commented
我[维基](https://en.wikipedia.org/wiki/Zeller%27s_congruence)上查到的名字好像是蔡勒同余式？而且这上面对于儒略历和格里高利历的公式都有（下面还有分析）。

2024-08-01 06:14 UTC, marscheng1 commented
信奥的一本通关是写的蔡勒公式，而且儒略历一般用不到吧，这东西大概也就是初赛用

2024-08-01 06:16 UTC, alphagocc commented
> 2. 暂时不想写证明，做题的话背下来就行。
> 3. 没有参考文献，直接把背的写下来了

暂时close，没有理由

2024-08-02 02:12 UTC, marscheng1 commented
> 我已经添加了表达式的推导，并添加了参考资料，可以重新 open 了
@HeRaNO @qwqAutomaton @alphagocc

2024-08-03 01:54 UTC, qwqAutomaton commented
reopen 应该是要 author 自己来的吧 🤔

2024-08-03 02:06 UTC, marscheng1 commented
我自己 open 不了，好像要权限

2024-08-03 02:25 UTC, marscheng1 commented
如果刚才 reopen 不了可能是因为我之后又 push 过那个分支，现在我把分支退回去了，可能就可以 reopen 了

2024-08-04 07:06 UTC, marscheng1 commented
> 我已经添加了表达式的推导，并添加了参考资料，可以重新 open 了
@HeRaNO @qwqAutomaton @alphagocc

2024-08-04 15:40 UTC, caijianhong commented
你的最后两个关于表达式的推导的 commit 为什么没了

2024-08-05 02:34 UTC, qwqAutomaton commented on docs/misc/zeller.md
> +注意此公式只适用于格里高利历（现行公历）
句末句号

2024-08-05 06:13 UTC, marscheng1 commented
> 你的最后两个关于表达式的推导的 commit 为什么没了
我查到好像要先把之后的commit撤回去才可以reopen，所以先撤掉了，现在已经重新push上去了

2024-08-09 11:24 UTC, marscheng1 commented
最后两个关于表达式的推导的 commit 已经重新push上去了，根据预览没有问题

2024-08-12 23:57 UTC, marscheng1 commented
> 最后两个关于表达式的推导的 commit 已经重新push上去了，根据预览没有问题

@HeRaNO @qwqAutomaton @alphagocc @caijianhong

2024-08-17 02:26 UTC, marscheng1 commented
> 最后两个关于表达式的推导的 commit 已经重新push上去了，根据预览没有问题

@HeRaNO @qwqAutomaton @alphagocc @caijianhong

2024-08-26 11:36 UTC, akakw1 approved these changes, later dismissed

2024-08-31 04:18 UTC, gavinliu266 requested changes
乘号应该用 `\times` 而不是 `*`。

2024-08-31 04:18 UTC, gavinliu266 commented on docs/misc/zeller.md
> +    D_1 = 365 * (y - 1) + \lfloor\frac{y - 1}{4}\rfloor - \lfloor\frac{y - 1}{100}\rfloor + \lfloor\frac{y - 1}{400}\rfloor
乘号应该用 `\times` 而不是 `*`。

2024-08-31 04:18 UTC, gavinliu266 commented on docs/misc/zeller.md
> +    那 $D_2$ 又应该如何计算呢，我们发现闰年时二月多一天，这一点的实现需要很多复杂的判断，所以不妨考虑将 1 月和 2 月看成上一年的 13 月和 14 月来计算，这样就可以避免闰年的判断，然后考虑月份，即从今年一月一号到上个月最后一天天的天数，经过构造，我们发现可以使用 $(m - 1) * 28 + \lfloor\frac{13 * (m + 1)}{5}\rfloor - 7$
“经过构造……”，如何构造？

建议将构造过程写出。

2024-08-31 04:18 UTC, gavinliu266 commented on docs/misc/zeller.md
> +    对该式进行构造和化简后，可以得到最简的式子（具体的化简过程见参考资料 1）
如何构造？

“见参考资料”，建议把化简的过程写一遍。

2026-06-29 13:11 UTC, marscheng1 commented
刚翻到这个以前的 pr，当时感觉不是很会推就 close 了。重写了一下推导过程，然后把公式换了一个版本。我感觉这个版本的公式理解、记忆、实现、推导都比原来的简单，原版的蔡勒公式是基于口算的需求设计的，和 OI 的需求有一点偏差

2026-06-29 13:24 UTC, HeRaNO commented
我个人的 concern 如下：

1. [OI Wiki 不是百科全书](https://oi-wiki.org/intro/what-oi-wiki-is-not/#oi-wiki-%E4%B8%8D%E6%98%AF%E7%99%BE%E7%A7%91%E5%85%A8%E4%B9%A6)
2. 此算法仅限于日期计算，如果我理解的没错本质是在一个特定规律下的速算法，那么自然限制了应用面，也就是说「背一个公式做这种题」

如果非要放的话，应该开一个页面专门放这种公式，单独开一个页面感觉略为鸡肋。

2026-06-29 13:25 UTC, HeRaNO commented on docs/misc/formula.md
> +
少了 ```

2026-06-29 13:34 UTC, marscheng1 commented
我当时开这个 pr 好像是因为看到一本通上记了这个公式，也有些题要用，还是算 OI 知识点的。不过看着确实太鸡肋了，把这个页面改成这类杂公式的集合我是支持的

2026-06-29 13:56 UTC, marscheng1 commented
note 框里面的表格渲染是不是有点问题，那个地方的语法应该没问题吧

2026-07-06 06:08 UTC, marscheng1 commented
目前该 pr 的 CI 根据日志应该是被 [#6888](https://github.com/OI-wiki/OI-wiki/issues/6888) 所反映的问题影响了。这里先 close，等该问题处理完再重新 open。

2026-07-09 06:51 UTC, marscheng1 commented
CI 的 bug 已经在 [#118](https://github.com/OI-wiki/OI-Wiki-export/pull/118) 中修复，现重新 open

2026-07-09 07:02 UTC, HeRaNO commented
折腾这么多其实都没必要，对分支 commit 会重启 workflows。

从内容质量上来看，仍然没有解决核心问题，我是觉得符合 [OI Wiki 不是百科全书](https://oi-wiki.org/intro/what-oi-wiki-is-not/#oi-wiki-%E4%B8%8D%E6%98%AF%E7%99%BE%E7%A7%91%E5%85%A8%E4%B9%A6)，没必要非得往 OI Wiki 里加这个公式的，OI 领域感觉并不涉及，XCPC 领域也罕见。如果我们有一个公式页面的话可以往里加，但现在并没有，在这个 PR 之后我想不到这个公式页面还可以为谁服务，所以加上后就感觉十分冗余。

2026-07-09 07:28 UTC, marscheng1 commented
确实这个东西也就刚接触 OI 的时候会看到，实际上尤其是近年几乎没有出现过。这种既没有所属知识点又没有什么用的公式质量太低了。而且其他符合要求的公式我也想不太到。

类似细小且不成体系的 trick 倒是存在，比如说随机序列的前缀最值期望是log，或者树上子树内 2-deg 的和为 1。这类杂项 trick 或许需要一个页面收纳。

如果将这个页面用作收录这些 trick，那这个公式其实也不重要，主要是抛砖引玉。如果这个公式放这显得太冗余，那我也可以将上述比较有用的 trick 证一下写上去。

2026-07-09 10:05 UTC, closed without merging