fix: docs/tools/editor/cpeditor.md 修改错误的作者名称
OI-wiki/OI-wiki pull request #5854
Opened 2024-09-15 07:49 UTC by xk2013

- [x] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

修改错误的作者名称，zarrtic -> zarttic。

2024-09-15 10:04 UTC, AtomAlpaca requested changes
个人认为直接移动页面不妥, 这个页面介绍的只是作为平衡树的 SATT, 直接放到一级数据结构页面是不合理的

个人认为应该不移动该页面(或者改名为 SATT), 然后在一级数据结构下另写一个关于树簇理论的 general 的页面

2024-09-16 01:15 UTC, alphagocc commented on .github/workflows/incrementally-build-pdf.yml
> +            wget "https://mirror.math.princeton.edu/pub/CTAN/fonts/cm-unicode.zip" --no-check-certificate
请不要头痛医头脚痛医脚，加个 `--no-check-certificate` 最多作为临时解决方案

2024-09-16 02:04 UTC, HeRaNO commented on docs/tools/editor/cpeditor.md
> +    具体可以查阅官方文档[^ref2]。
为啥一定要改成 ref 格式的

2024-09-16 02:34 UTC, HeRaNO commented
这个 PR 里包含三个 topic 的修改，请分开提 PR

而且有一些修改并不被支持

2024-09-16 03:44 UTC, closed without merging