feat(math/number-theory/basic.md): 将积性函数移至数论函数下，补充加性函数内容
OI-wiki/OI-wiki pull request #5911
Opened 2024-10-05 14:23 UTC by Qiu-Quanzhi

- [x] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

### 内容修改

1. 更改个别语序。
2. 将积性函数移至数论函数之下。

### 内容添加

1. 补充加性函数相关介绍

2024-10-05 15:21 UTC, Marcythm requested changes

2024-10-05 15:21 UTC, Marcythm commented on docs/math/number-theory/basic.md
> +-   莫比乌斯函数：$\mu(n)=\begin{cases}1&n=1\\0&\exists d>1,d^{2}\mid n\\(-1)^{\omega(n)}&\text{otherwise}\end{cases}$，其中 $\omega(n)$ 是一个加性函数，表示 $n$ 的本质不同质因子个数。
此处的修改不仅没有好处，反而使句子的结构变得更劣了。对于上下文来说，omega 是一个未知的东西，在对其进行解释时应当优先用已知解释未知来使其明确，而不是用同样未知的「加性函数」这一概念去对其进行解释，使读者一头雾水。就算不考虑上下文，也应先对概念（或记号）进行定义，再介绍其所具有的性质，而非倒过来。

2024-10-05 15:21 UTC, Marcythm commented on docs/math/number-theory/basic.md
> +-   相异质因子之和：$a_1(n)$ 或 $sopf(n)$。
sopf 和 sopfr 是啥？我没有找到任何相关的解释。

2024-10-05 15:21 UTC, Marcythm commented on docs/math/number-theory/basic.md
> +    数论中，若函数 $f(n)$ 满足 $f(1)=1$ 且 $\forall x,y\in\mathbf{N}^*,~(x,y)=1$ 都有 $f(xy)=f(x)f(y)$，则 $f(n)$ 为 **积性函数**。
添加一个规范语境范围的短句可以接受，但为啥句子都不写完整？抄 wikipedia 总会抄吧，「在数论中」，这才是一个完整的句子。

2024-10-05 15:21 UTC, Marcythm commented on docs/math/number-theory/basic.md
> +    数论中，若函数 $f(n)$ 满足 $f(1)=0$ 且 $\forall x,y\in\mathbf{N}^*,~(x,y)=1$ 都有 $f(xy)=f(x)+f(y)$，则 $f(n)$ 为 **加性函数**。
同上。

2024-10-05 15:21 UTC, Marcythm commented on docs/math/number-theory/basic.md
> +    若函数 $f(n)$ 满足 $f(1)=0$ 且 $\forall x,y\in\mathbf{N}^*$ 都有 $f(xy)=f(x)+f(y)$，则 $f(n)$ 为 **完全加性函数**。
同上。

2024-10-05 15:21 UTC, Marcythm commented on docs/math/number-theory/basic.md
>      若函数 $f(n)$ 满足 $f(1)=1$ 且 $\forall x,y\in\mathbf{N}^*$ 都有 $f(xy)=f(x)f(y)$，则 $f(n)$ 为 **完全积性函数**。
为什么上面一行加了限定范围的短句而这里却不加？

2024-10-05 16:29 UTC, Qiu-Quanzhi commented on docs/math/number-theory/basic.md
> +-   相异质因子之和：$a_1(n)$ 或 $sopf(n)$。
这条出自在Wikipedia，没有佐证资料，且明显不是广泛使用的，确实应当删去，谨慎对待无引证资料

2024-10-06 02:02 UTC, Marcythm commented on docs/math/number-theory/basic.md
>  ???+ note "加性函数"
其实下面都有系统介绍了就没必要再加这么一个 note 了。我自己来改吧。

2024-10-06 02:13 UTC, Marcythm submitted a review, later dismissed

2024-10-06 02:14 UTC, Marcythm commented
我对 pr 内容做了一些我认为更正确的修改。你看看你对于当前的结构和叙述是否有其他问题或建议？

2024-10-06 04:08 UTC, Qiu-Quanzhi commented
> 我对 pr 内容做了一些我认为更正确的修改。您看看对于当前的结构和叙述是否有其他问题或建议？

似乎公式渲染有误

2024-10-06 10:12 UTC, Marcythm commented
你这个引入记号 P 又不讲明白是做什么用的... 我按我的讲法改了。

2024-10-06 10:13 UTC, Marcythm commented
> 你这个引入记号 P 又不讲明白是做什么用的... 我按我的讲法改了。

另外，mathbb P 不要乱用，一般这个记号还有表示概率的用法..

2024-10-06 10:13 UTC, Marcythm approved these changes

2024-10-06 10:23 UTC, Qiu-Quanzhi commented
> 你这个引入记号 P 又不讲明白是做什么用的... 我按我的讲法改了。

好的，吸取经验教训。

review辛苦了，十分感谢。

2024-10-06 10:24 UTC, merged