feat(contest/io.md): 增加对 mmap 的说明
OI-wiki/OI-wiki pull request #5920
Opened 2024-10-07 07:43 UTC by ZnPdCo

方便卡常

- [x] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

2024-10-07 08:05 UTC, Enter-tainer requested changes

2024-10-07 08:05 UTC, Enter-tainer commented on docs/contest/io.md
> +`mmap` 则会调度内核级函数，将文件一次性地映射到内存中，类似于可以指针引用的内存区域。中间不需要阻塞系统调用，不需要内核缓存，只需要一次 `lseek`，因而有更优的速度，是极限卡常者不二选择。在 `fread(new)` 已经非常快的情况下再甩一段时间，而且实际使用的时候速度更快。`mmap` 确保了进程间自动共享，存储区如果可以也会与内核缓存分享信息，确保了更少的拷贝操作。但是在日常程
```suggestion
`mmap` 是 linux 系统调用，可以将文件一次性地映射到内存中。在一些场景下有更优的速度。
```

其他的部分写的有点难评，一些是不知道哪来的”X快，Y慢“，另一些是有事实错误

2024-10-07 08:05 UTC, Enter-tainer commented on docs/contest/io.md
> +```
这个代码不太好，这里是在 mmap stdin，在pipe或者终端输入的情况下是不行的。建议改成用 open 然后直接 mmap open 出来的 fd。另一个是，既然已经是输入文件了，可以直接用 fstat 来获取文件长度

2024-10-07 08:05 UTC, Enter-tainer commented on docs/contest/io.md
> +  write(1234);
这句是干啥的

2024-10-07 08:05 UTC, Enter-tainer commented on docs/contest/io.md
> +  write(
这代码能跑过吗。好像你的 write 和 write 系统调用重名了

2024-10-07 08:06 UTC, Enter-tainer commented
这个 mmap 输出好像不太可能会更快，既然你已经知道了文件长度，说明你大概率已经把要输出的东西全都 buffer 到内存里面了。这时候好像直接写出去就是最快的。

2024-10-07 08:07 UTC, ZnPdCo commented
> 这个 mmap 输出好像不太可能会更快，既然你已经知道了文件长度，说明你大概率已经把要输出的东西全都 buffer 到内存里面了。这时候好像直接写出去就是最快的。

要不把输出删了？只保留输入？

2024-10-07 08:08 UTC, Enter-tainer commented
合理的

2024-10-07 08:15 UTC, ZnPdCo commented on docs/contest/io.md
> +```
可以在pipe中使用：https://www.luogu.com.cn/record/180732506

2024-10-07 08:16 UTC, Enter-tainer commented on docs/contest/io.md
> +```
![image](https://github.com/user-attachments/assets/aeafe7dd-f809-4f83-9731-3399b18bf84d)

2024-10-07 08:17 UTC, Enter-tainer commented on docs/contest/io.md
> +```
https://man7.org/linux/man-pages/man2/lseek.2.html#:~:text=ESPIPE%20fd%20is%20associated%20with%20a%20pipe%2C%20socket%2C%20or%20FIFO.

2024-10-07 08:18 UTC, ZnPdCo commented on docs/contest/io.md
> +```
sry忘记开了：
![image](https://github.com/user-attachments/assets/b098939a-aa5e-4690-8700-975d245c5f3d)
总之可以过。而且我认为这些写好记

2024-10-07 08:20 UTC, Enter-tainer requested changes

2024-10-07 08:20 UTC, Enter-tainer commented on docs/contest/io.md
>  对于输出，我们还有对应的 `fwrite` 函数。
这里原来对 fread 的介绍好像不见了

2024-10-07 08:20 UTC, Enter-tainer commented on docs/contest/io.md
>  对于输出，我们还有对应的 `fwrite` 函数。
另外这里好像有一些误解，getchar putchar 也是有缓冲区的呀

2024-10-07 08:21 UTC, Enter-tainer commented on docs/contest/io.md
> +```
这个不一定是pipe，可能是重定向，pipe是 `cat xxx.in | your_prog`

2024-10-07 08:21 UTC, Enter-tainer commented on docs/contest/io.md
> +```
> 总之可以过。而且我认为这些写好记

我觉得还是要严谨一些，mmap和seek stdin本身就不是正常的操作

2024-10-07 08:22 UTC, ZnPdCo commented on docs/contest/io.md
>  对于输出，我们还有对应的 `fwrite` 函数。
> 这里原来对 fread 的介绍好像不见了

刚刚好像不小心删掉了。

> 另外这里好像有一些误解，getchar putchar 也是有缓冲区的呀

我copy了原来的。

2024-10-07 08:22 UTC, ZnPdCo commented on docs/contest/io.md
> +```
好的。

2024-10-07 10:27 UTC, Tiphereth-A commented
话说这个页面是不是应该补一个 benchmark 🤔

2024-10-08 00:51 UTC, ZnPdCo commented
> 话说这个页面是不是应该补一个 benchmark 🤔

可以到时候再补

2024-10-09 12:15 UTC, Enter-tainer commented on docs/contest/io.md
> +  // 0，意思是从 stdin 读入
mmap stdin 是很诡异的操作，不建议这样做

2024-10-09 12:25 UTC, ZnPdCo commented on docs/contest/io.md
> +  // 0，意思是从 stdin 读入
> mmap stdin 是很诡异的操作，不建议这样做

那在洛谷等不使用文件操作的平台怎么办

2024-10-17 05:22 UTC, Enter-tainer approved these changes

2024-10-17 05:22 UTC, merged