feat: add example problem, code and data
OI-wiki/OI-wiki pull request #5935
Opened 2024-10-12 09:37 UTC by XuYueming520

- [x] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

新增快读读入在洛谷上的模板题，替换原先完整带调试版至参考代码中，并配了 $n = 10^6$ 的数据，由于一些原因，无法实现 $n = 10^8$。

2024-10-12 09:42 UTC, Tiphereth-A commented on docs/contest/examples/io_1.ans
应该放到 docs/contest/examples/io/io_1.ans

2024-10-12 09:42 UTC, Tiphereth-A commented on docs/contest/examples/io_1.in
应该放到 docs/contest/examples/io/io_1.in

2024-10-14 11:16 UTC, alphagocc commented
我不认为我们需要一个 7.05 MB 的输入文件，如果要做正确性测试的话一个不超过 1KB 的文件足以。
如果要提供 benchmark 的话也许可以提供一个指向第三方平台的链接

2024-10-14 23:50 UTC, XuYueming520 commented
> 我不认为我们需要一个 7.05 MB 的输入文件，如果要做正确性测试的话一个不超过 1KB 的文件足以。 如果要提供 benchmark 的话也许可以提供一个指向第三方平台的链接

哦哦，我这就去改。我就把测试文件调小一些吧，需要测试的话让读者往洛谷上交就行了。

2024-10-14 23:58 UTC, Marcythm requested changes

2024-10-14 23:58 UTC, Marcythm commented on docs/contest/io.md
> +        此题为快速读入模板题。算法理论时间复杂度 $O(n)$ 正确，但是由于读入 $10 ^ 8$ 个数是算法的瓶颈，需要使用快速读入。
> 算法理论时间复杂度 $O(n)$ 正确

时间复杂度本就是理论上的概念，不应当还说「理论」。

> 但是由于读入 $10 ^ 8$ 个数是算法的瓶颈，需要使用快速读入。

这样的表述我认为是有问题的... 这为什么是瓶颈？原因呢？哪方面的瓶颈？
而且应该说这是「实现的效率瓶颈」，而非「算法的瓶颈」...毕竟前面已经说了「算法时间复杂度正确」，这不是前后文矛盾吗？

2024-10-15 00:00 UTC, XuYueming520 commented on docs/contest/io.md
> +        此题为快速读入模板题。算法理论时间复杂度 $O(n)$ 正确，但是由于读入 $10 ^ 8$ 个数是算法的瓶颈，需要使用快速读入。
是我有些随意了

2024-10-15 23:47 UTC, XuYueming520 commented on docs/contest/io.md
> +        此题为快速读入模板题。朴素算法时间复杂度为 $O(n)$，对于 $n \leq 10^8$ 的数据应该可以通过。但是由于如果不做任何优化，读入 $10 ^ 8$ 个数会使程序常数增加，从而导致超时。此时需要使用快速读入来优化读入时的常数。
您看我做如下修改是否合理：

此题为快速读入模板题。朴素算法时间复杂度为 $O(n)$，对于 $n \leq 10^8$ 的数据应该可以通过。但是正如上文所言，如果不做任何优化，读入 $10 ^ 8$ 个数是十分缓慢的，从而将导致超时。此时需要使用快速读入来优化读入时的常数。

2024-12-31 07:12 UTC, HeRaNO commented
感觉不需要解题思路部分，只把文章中的代码移出到 `code` 文件夹，新增一个测试数据，并且提供一个题目链接就足够了

2024-12-31 09:45 UTC, XuYueming520 commented
> 感觉不需要解题思路部分，只把文章中的代码移出到 `code` 文件夹，新增一个测试数据，并且提供一个题目链接就足够了

按照您的意思，删除解题思路了。

2025-01-01 04:29 UTC, alphagocc approved these changes

2025-01-02 09:25 UTC, HeRaNO commented
@Marcythm PTAL, thx!

2025-01-02 15:39 UTC, Marcythm approved these changes
thanks!

2025-01-02 15:58 UTC, merged