feat(ds/seg.md): 添加线段树二分（#5952）
OI-wiki/OI-wiki pull request #5962
Opened 2024-10-24 09:09 UTC by hhc0001

- [x] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

2024-12-16 11:21 UTC, Tiphereth-A commented on docs/ds/seg.md
> +    $1 \le n, q \le 10^6$。
能不能直接讲算法，然后引例题，而不是搞什么「用一个例题来引入」……

2025-01-04 08:17 UTC, Tiphereth-A commented on docs/ds/seg.md
> +    $1 \le n, q \le 10^6$。
换句话说就是需要让算法和例题解耦，否则内容看起来就像是题解了

2025-03-20 09:27 UTC, Tiphereth-A commented on docs/ds/seg.md
> +然后，就可以发现，这个结构，天生适合二分。
应该避免口语化表述

2025-03-20 09:27 UTC, Tiphereth-A commented on docs/ds/seg.md
> +![](./images/segt10.svg)
这几个新图片的空白部分有点大，能不能调小点 🤔

2025-03-20 09:27 UTC, Tiphereth-A commented on docs/ds/seg.md
> +  pushdn(p, l, r);
代码里缺少了这个函数的实现

2025-03-20 09:27 UTC, Tiphereth-A commented on docs/ds/seg.md
> +  pushdn(p, l, r);
另外，变量名字等应该和上文的统一

2025-03-20 09:27 UTC, Tiphereth-A commented on docs/ds/seg.md
> +用一个例题来解释：
在讲例题之前应足够清晰明确地介绍算法流程等内容

2025-05-21 05:29 UTC, c-forrest commented
有一个小建议，如果有空您可以考虑一下，就是是不是没有必要在介绍线段树二分的时候引入懒标记下传的部分。这好像会使得问题更为复杂，而且懒标记下传并非线段树二分的必要组成部分。

2025-05-21 09:01 UTC, Tiphereth-A commented
我看了下这几个 svg，这写的是直接把 png 按 base64 格式插进来吧……这是不是不太对 🤔

2025-06-02 13:33 UTC, hhc0001 commented
> 我看了下这几个 svg，这写的是直接把 png 按 base64 格式插进来吧……这是不是不太对 🤔

主要是因为用 excalidraw 搞的

2025-06-03 14:21 UTC, hhc0001 commented
> 有一个小建议，如果有空您可以考虑一下，就是是不是没有必要在介绍线段树二分的时候引入懒标记下传的部分。这好像会使得问题更为复杂，而且懒标记下传并非线段树二分的必要组成部分。

考虑考虑？

2025-06-04 05:21 UTC, Tiphereth-A requested changes
我不同意引入伪装成 SVG 的 PNG 图像

2025-07-20 00:29 UTC, closed without merging