refactor(bigraph-match.md): 重构例题部分
OI-wiki/OI-wiki pull request #5997
Opened 2024-11-12 00:50 UTC by hhc0001

- [x] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

2024-12-14 11:18 UTC, Tiphereth-A commented on docs/graph/graph-matching/bigraph-match.md
> +    ??? note "代码"
例题代码需要分离成单独的文件

see https://oi-wiki.org/intro/format/#%E4%BB%A3%E7%A0%81%E5%9D%97%E7%9A%84%E6%A0%BC%E5%BC%8F%E8%A6%81%E6%B1%82

2024-12-14 11:18 UTC, Tiphereth-A commented on docs/graph/graph-matching/bigraph-match.md
> +## 例题，与常见建模方法
```suggestion
## 例题
```

2024-12-14 11:18 UTC, Tiphereth-A commented on docs/graph/graph-matching/bigraph-match.md
> -    None
为什么删掉这两题 🤔

2024-12-14 11:18 UTC, Tiphereth-A commented on docs/graph/graph-matching/bigraph-match.md
> +??? note "[CF 1404E Bricks](https://codeforces.com/problemset/problem/1404/E)"
```suggestion
??? note "[CodeForces 1404E Bricks](https://codeforces.com/problemset/problem/1404/E)"
```

2024-12-14 11:18 UTC, Tiphereth-A commented on docs/graph/graph-matching/bigraph-match.md
> +    ???+ note "题意"
这个 Details 没意义吧 🤔

2024-12-14 11:18 UTC, Tiphereth-A commented on docs/graph/graph-matching/bigraph-match.md
> +    ???+ note "题意"
同上

2024-12-14 11:37 UTC, hhc0001 commented on docs/graph/graph-matching/bigraph-match.md
> -    None
主要是我搞到一半咕咕咕了

2024-12-14 11:39 UTC, Tiphereth-A commented on docs/graph/graph-matching/bigraph-match.md
> -    None
> 主要是我搞到一半咕咕咕了

可以留作习题（

2024-12-14 11:40 UTC, hhc0001 commented on docs/graph/graph-matching/bigraph-match.md
> -    None
而且这两个题似乎是一个 idea

2024-12-16 10:33 UTC, Tiphereth-A reviewed
请完整阅读 https://oi-wiki.org/intro/format/#%E4%BB%A3%E7%A0%81%E5%9D%97%E7%9A%84%E6%A0%BC%E5%BC%8F%E8%A6%81%E6%B1%82 一节

2024-12-16 10:33 UTC, Tiphereth-A commented on docs/graph/code/graph-matching/bigraph-match/bigraph-match_4.cpp
> +  // cout << rcnt << ' ' << dcnt << '\n';
不要保留无用注释

2024-12-16 10:33 UTC, Tiphereth-A commented on docs/graph/code/graph-matching/bigraph-match/bigraph-match_1.cpp
> +  cin.tie(0), cout.tie(0);
不要用 `0` 代替 `false` 与 `nullptr`

2024-12-16 10:33 UTC, Tiphereth-A commented on docs/graph/graph-matching/bigraph-match.md
> +        --8<-- "/docs/code/graph-matching/bigraph-match/bigraph-match_1.cpp"
```suggestion
        --8<-- "docs/code/graph-matching/bigraph-match/bigraph-match_1.cpp"
```

2025-02-09 00:36 UTC, hhc0001 commented on docs/graph/graph-matching/bigraph-match.md
> -    None
好了，我回来了

2025-03-16 05:45 UTC, yusancky commented
可以再拉一下 master，看看 test 能不能过。#5952 同理。

2025-05-21 05:16 UTC, c-forrest requested changes

2025-05-21 05:16 UTC, c-forrest commented on docs/graph/code/graph-matching/bigraph-match/bigraph-match_2.cpp
> +// There was a delta here...
请问这是什么意思？

2025-05-21 05:16 UTC, c-forrest commented on docs/graph/code/graph-matching/bigraph-match/bigraph-match_3.cpp
> +// There was a delta here...
还有这个

2025-05-21 05:16 UTC, c-forrest commented on docs/graph/code/graph-matching/bigraph-match/bigraph-match_4.cpp
> +// There was a delta here...
这个

2025-05-21 05:16 UTC, c-forrest commented on docs/graph/code/graph-matching/bigraph-match/bigraph-match_5.cpp
> +  // cout << x << '\n';
调试的代码也应该删掉

2025-05-21 05:16 UTC, c-forrest commented on docs/graph/code/graph-matching/bigraph-match/bigraph-match_5.cpp
> +  // cout << rcnt << ' ' << dcnt << '\n';
还有这，以及下面

2025-05-21 05:16 UTC, c-forrest commented on docs/graph/code/graph-matching/bigraph-match/bigraph-match_6.cpp
> +  // cout << x << '\n';
这个文件也有

2025-05-21 05:16 UTC, c-forrest commented on docs/graph/code/graph-matching/bigraph-match/bigraph-match_7.cpp
> +// There was a delta here...
这里

2025-05-21 05:16 UTC, c-forrest commented on docs/graph/code/graph-matching/bigraph-match/bigraph-match_7.cpp
> +  //}
以及这里

2025-05-21 05:16 UTC, c-forrest commented on docs/graph/graph-matching/bigraph-match.md
> +[洛谷 P2071 - 座位安排](https://www.luogu.com.cn/problem/P2071) 拆点
可以写成列表的形式？

2025-05-21 05:16 UTC, c-forrest commented on docs/graph/code/graph-matching/bigraph-match/bigraph-match_6.cpp
> +#include <bits/stdc++.h>
请不要使用万能头文件。oi wiki 的 UB check 会测 gcc 之外的编译器

2025-05-21 05:16 UTC, c-forrest commented on docs/graph/graph-matching/bigraph-match.md
> +    ??? note "代码"
缺少代码

2025-06-02 14:29 UTC, c-forrest commented on docs/graph/graph-matching/bigraph-match.md
> +author: accelsao, thallium, Chrogeek, Enter-tainer, ksyx, StudyingFather, H-J-Granger, Henry-ZHR, countercurrent-time, william-song-shy, 5ab-juruo, XiaoQuQuSDm, hhc0001
别的改没细看，这里是不是多了个 m 😂

2025-06-02 14:51 UTC, c-forrest commented on docs/graph/graph-matching/bigraph-match.md
> +??? note "[洛谷 P3355 - 骑士共存问题](https://www.luogu.com.cn/problem/P3355)"
包括这道题目在内，有几道题目的题面是缺失的。我理解您可能觉得题面太长等，但是考虑到这个同时也会输出打印版的 pdf，您最好是归纳总结一下题面，放到本页面。

另外，题面可以默认打开，把解答和代码折叠起来就好了。

2025-06-02 16:28 UTC, c-forrest commented on docs/graph/graph-matching/bigraph-match.md
> +???+ note "[CodeForces 1404E Bricks](https://codeforces.com/problemset/problem/1404/E)"
```suggestion
???+ note "[Codeforces 1404E Bricks](https://codeforces.com/problemset/problem/1404/E)"
```

2025-06-02 16:36 UTC, c-forrest commented on docs/graph/graph-matching/bigraph-match.md
> +        然后就可以直接二分图 MIS 了。
本文没有出现 MIS 这种缩写。突然使用可能会造成困惑。

```suggestion
        然后就可以直接二分图最大独立集了。
```

2025-06-02 16:39 UTC, c-forrest commented on docs/graph/graph-matching/bigraph-match.md
> +        于是就可以二分图匹配了。
```suggestion
        注意到，当存在 $n$ 个 $1$，使得这些 $1$ 不在同一行、同一列，那么必然有解，否则必然无解。问题转化成了能否找到这 $n$ 个 $1$。

        考虑对于一个 $1$ 而言，最终的方案中选了这个 $1$ 代表这个 $1$ 的行、列被占用。于是可以建出一个 $n$ 个左部点、$n$ 个右部点的二分图，其中对于某个为 $1$ 的元素，我们建一条连接它的行的左部点和它的列的右部点。于是就可以二分图匹配了。
```

2025-06-02 16:41 UTC, c-forrest commented on docs/graph/graph-matching/bigraph-match.md
> +        可惜的是本题只能使用匈牙利算法。
以这个为例，如果方便，您也可以调整一下其它的文字部分。

1. 尽量使用书面化的语言，避免使用过多口语和指代不明的词语；
2. 如果出现某个记号，最好是前文已经存在了它的定义，否则容易引起困惑；
3. 分段以表意功能为主，不要一句一段，甚至半句一段。

```suggestion
        先考虑如果没有删除元素时怎么做。对于每一个多重集 $i$，开一个新点 $l_i$；对于每一个可能的答案 $a$，开一个新点 $r_a$。然后，对于某一个对应点 $l_i$ 的多重集的一个元素 $a$，连一条 $l_i$ 至 $r_a$ 的边。此时这个弱化版本变成了一个二分图最大匹配。

        现在考虑删除元素的操作，发现删除一条边会引起匹配的巨变，复杂度无法接受。于是，可以反过来考虑，每一次加一条边，然后以它为起点重新增广。本题只能使用匈牙利算法。
```

2025-06-02 16:49 UTC, c-forrest commented on docs/graph/graph-matching/bigraph-match.md
> +        然后原问题转化成了一个二分图最大独立集。
这一段实际上可能会出现「懂的人能看懂，不懂的人看不懂」的情况。如果您方便，可以适当地补充一下。

2025-06-03 14:39 UTC, merged