fix(graph/shortest-path): 修正 Dijkstra 复杂度分析
OI-wiki/OI-wiki pull request #6046
Opened 2024-12-06 07:48 UTC by Eletary

- [x] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

此处将“优先队列”与“二叉堆” 并列作为 Dijkstra 的一种优化显然是不合理的。另外关于斐波那契堆部分的复杂度分析有误，并非是 push O(1) 而是 Decrease-key O(1) 才使得复杂度能优化至 O(nlogn +m)

2024-12-08 11:31 UTC, aofall requested changes

2024-12-08 11:31 UTC, aofall commented on docs/graph/shortest-path.md
> +???+ note "`std::priority_queue` 实现 "
代码并不局限于C++，其他语言不一定有 `std` 这种 namespace 写法，上面其他地方的修改同理

2024-12-14 02:46 UTC, Eletary commented on docs/graph/shortest-path.md
> +???+ note "`std::priority_queue` 实现 "
那请问应该怎么改比较合适

2024-12-15 15:05 UTC, aofall commented on docs/graph/shortest-path.md
> +???+ note "`std::priority_queue` 实现 "
保持原来“优先队列”的描述就可以了

2024-12-26 08:27 UTC, Tiphereth-A submitted a review, later dismissed

2024-12-26 14:46 UTC, aofall approved these changes

2024-12-26 15:07 UTC, Tiphereth-A approved these changes

2024-12-26 15:15 UTC, merged